-- Go pieces of a unit's abilities (see LawSpec.AbilityNames), in the unit's
-- package, lawspec_abilities.go: an interface per ability, a struct per
-- spec handler (made by New<Handler>) and a recording struct per ability
-- (New<Ability>Recording). Handlers travel in the symbols map generated code
-- passes to every definition, under lsHandlersKey.
--
-- Every package holds the checked bodies of every unit, and its own copy of
-- the data types, so each package declares the interface and recording of
-- every ability the program uses, and the spec handlers its unit declares or
-- any body installs with handle ... with h end.
module LawSpec.AbilityEmit.Go (emit, productionStub, methodName) where

import Data.Char (toUpper)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.AbilityNames
import qualified LawSpec.GoData as Native
import qualified LawSpec.GoDefinitions as Definitions
import qualified LawSpec.GoExpr as E
import qualified LawSpec.Code.Doc as D

-- An operation's Go method: exported, so other packages can implement it.
methodName :: String -> String
methodName (c : cs) = toUpper c : cs
methodName [] = []

emit :: Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit minify bits datas units = case clashes of
  (name, owners) : _ -> Left ("in Go, every package holds every ability of the program, so two cannot share a name: " ++
    name ++ " is declared by " ++ intercalate " and " owners)
  [] -> mapM unitFile (filter wanted units)
  where
    clashes = [ (interfaceName a, owners) | a <- everyAbility
              , let owners = distinctOn id [ownerName b | v <- units, b <- C.unitAbilities v, interfaceName b == interfaceName a]
              , length owners > 1 ]
    wanted u = unitAbilityPieces u || (not (null everyAbility) && not (null (C.unitDefinitions u)))
    everyAbility = distinctOn interfaceName [a | v <- units, a <- C.unitAbilities v]
    scoped = [h | v <- units, d <- C.unitDefinitions v, h <- scopedHandlers (C.definitionBody d)]
    scopedHandlers e = case C.expressionNode e of
      C.Handle (C.WithHandler _ (C.SpecHandler h)) body -> h : scopedHandlers body
      _ -> concatMap scopedHandlers (C.children e)
    handlersOf u = distinctOn specName (C.unitHandlers u ++ [h | identity <- scoped, v <- units, h <- C.unitHandlers v, C.handlerId h == identity])
    distinctOn key = foldr (\x acc -> x : filter ((/= key x) . key) acc) []
    layout = if minify then D.CompactTabs else D.PrettyTabs 100
    calls = Definitions.definitionCalls units
    line = D.text
    schema = "_lawSpecDefinitionSchema"
    unitFile u = do
      let identity = C.idText (C.unitId u)
          packageName = reverse (takeWhile (/= '.') (reverse identity))
      interfaces <- mapM interface everyAbility
      handlers <- mapM specHandler (handlersOf u)
      recordings <- mapM recording everyAbility
      let source = line "// Generated by LawSpec. Do not edit." <> D.hardline <>
            line ("package " ++ packageName) <> D.hardline <> D.hardline <>
            D.joinWith (D.hardline <> D.hardline) (interfaces ++ handlers ++ recordings) <> D.hardline
      pure (Artifact (map (\c -> if c == '.' then '/' else c) identity ++ "/lawspec_abilities.go")
        (D.render layout source) "generated" "source")
    signature ty = do
      let (args, result) = C.functionType ty
      types <- mapM (Native.goDataType datas) args
      resultType <- if result == C.scalarType "Unit" then pure "" else (' ' :) <$> Native.goDataType datas result
      pure ("(" ++ intercalate ", " ["value" ++ show i ++ " " ++ t | (i, t) <- zip [0 :: Int ..] types] ++ ")" ++ resultType)
    interface a = do
      methods <- mapM (\(op, ty) -> (\s -> line (methodName op ++ s)) <$> signature ty) (C.abilityOperations a)
      pure (line ("// " ++ interfaceName a ++ " is the " ++ C.abilityName a ++ " ability: a handler answers each of its operations.") <> D.hardline <>
        line ("type " ++ interfaceName a ++ " interface ") <> D.block 8 (D.joinWith D.hardline methods))
    codecs ty = do
      let (args, result) = C.functionType ty
      argumentCodecs <- mapM (Native.goCodecWithContext "symbols" datas) args
      resultCodec <- Native.goCodecWithContext "symbols" datas result
      pure (argumentCodecs, resultCodec)
    prelude = [line ("schema := " ++ schema), line ("bits := " ++ show bits), line "_, _ = schema, bits"]
    specHandler h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (lookup (C.handlerAbility h) [(C.abilityInstance a, a) | a <- everyAbility])
      initialState <- case C.handlerState h of
        Nothing -> pure []
        Just (_, start) -> do
          value <- E.renderExpression datas bits schema (const "_unbound") (\_ _ -> Left "a handler's start value calls nothing") start
          pure [line "handler.state = " <> value]
      let name = specName h
      methods <- mapM (\(op, ty) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        s <- signature ty
        (argumentCodecs, resultCodec) <- codecs ty
        let (args, result) = C.functionType ty
            arguments = line "symbols" : [line "handler.state" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [line "lsAbsent(\"Unit\")"]
               else [E.call ("codec" ++ show i ++ ".fromNative") [line ("value" ++ show i)] | i <- [0 .. length args - 1]])
            invocation = E.call evaluate arguments
            outcome = case C.handlerState h of
              Nothing -> [line "result := " <> invocation]
              Just _ -> [line "result, next := lsPairFields(" <> invocation <> line ")", line "handler.state = next"]
            returned
              | result == C.scalarType "Unit" = [line "_ = resultCodec.toNative(result)"]
              | otherwise = [line "return resultCodec.toNative(result)"]
        pure (line ("func (handler *" ++ name ++ ") " ++ methodName op ++ s ++ " ") <> D.block 8 (D.joinWith D.hardline
          ([line "symbols := handler.symbols", line "_ = symbols"] ++ prelude ++
           [line ("codec" ++ show i ++ " := " ++ c) | (i, c) <- zip [0 :: Int ..] argumentCodecs] ++
           [line ("resultCodec := " ++ resultCodec)] ++ outcome ++ returned)))) (C.abilityOperations ability)
      pure (line ("// " ++ name ++ " is the spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ".") <> D.hardline <>
        line ("type " ++ name ++ " struct ") <> D.block 8 (D.joinWith D.hardline
          [line "symbols map[string]*LawSpecSymbol", line "state   LawSpecValue"]) <> D.hardline <> D.hardline <>
        line ("// New" ++ name ++ " makes " ++ C.handlerName h ++ "; symbols is the context of the law it serves.") <> D.hardline <>
        line ("func New" ++ name ++ "(symbols map[string]*LawSpecSymbol) *" ++ name ++ " ") <> D.block 8 (D.joinWith D.hardline
          ([line ("handler := &" ++ name ++ "{symbols: symbols}")] ++
           (if null initialState then [] else prelude ++ initialState) ++ [line "return handler"])) <>
        D.hardline <> D.hardline <> D.joinWith (D.hardline <> D.hardline) methods)
    recording a = do
      let name = recordingName a
      methods <- mapM (\(op, ty) -> do
        s <- signature ty
        (argumentCodecs, _) <- codecs ty
        let (args, result) = C.functionType ty
            values = intercalate ", " ["value" ++ show i | i <- [0 .. length args - 1]]
            logged = "[]LawSpecValue{" ++ intercalate ", " ["codec" ++ show i ++ ".fromNative(value" ++ show i ++ ")" | i <- [0 .. length args - 1]] ++ "}"
            forward = "recording.Inner." ++ methodName op ++ "(" ++ values ++ ")"
        pure (line ("func (recording *" ++ name ++ ") " ++ methodName op ++ s ++ " ") <> D.block 8 (D.joinWith D.hardline
          ([line "symbols := recording.symbols", line "_ = symbols"] ++ (if null args then [] else prelude) ++
           [line ("codec" ++ show i ++ " := " ++ c) | (i, c) <- zip [0 :: Int ..] argumentCodecs] ++
           [line ("recording.Calls = append(recording.Calls, LawSpecCall{Operation: " ++ show op ++ ", Arguments: " ++ logged ++ "})"),
            line (if result == C.scalarType "Unit" then forward else "return " ++ forward)])))) (C.abilityOperations a)
      pure (line ("// " ++ name ++ " records each call to a " ++ C.abilityName a ++ " handler, then passes it on.") <> D.hardline <>
        line ("type " ++ name ++ " struct ") <> D.block 8 (D.joinWith D.hardline
          [line ("Inner   " ++ interfaceName a), line "Calls   []LawSpecCall", line "symbols map[string]*LawSpecSymbol"]) <> D.hardline <> D.hardline <>
        line ("// New" ++ name ++ " records the calls to inner.") <> D.hardline <>
        line ("func New" ++ name ++ "(inner " ++ interfaceName a ++ ", symbols map[string]*LawSpecSymbol) *" ++ name ++ " ") <>
        D.block 8 (line ("return &" ++ name ++ "{Inner: inner, symbols: symbols}")) <> D.hardline <> D.hardline <>
        line ("func (recording *" ++ name ++ ") lawSpecCalls() []LawSpecCall ") <> D.block 8 (line "return recording.Calls") <>
        D.hardline <> D.hardline <> D.joinWith (D.hardline <> D.hardline) methods)

-- The user-owned production handler of each ability, in adapter.go: a struct
-- and New<Ability>Handler, which the generated tests call.
productionStub :: [C.DataDeclaration] -> C.Ability -> Either String String
productionStub datas a = do
  methods <- mapM (\(op, ty) -> do
    let (args, result) = C.functionType ty
    types <- mapM (Native.goDataType datas) args
    resultType <- if result == C.scalarType "Unit" then pure "" else (' ' :) <$> Native.goDataType datas result
    pure ("func (handler *" ++ productionName a ++ ") " ++ methodName op ++ "(" ++
      intercalate ", " ["value" ++ show i ++ " " ++ t | (i, t) <- zip [0 :: Int ..] types] ++ ")" ++ resultType ++
      " {\n\tpanic(" ++ show op ++ ")\n}\n")) (C.abilityOperations a)
  pure ("\n// " ++ productionName a ++ " is the native handler of " ++ C.abilityName a ++ ": " ++
    intercalate ", " (map fst (C.abilityOperations a)) ++ ".\ntype " ++ productionName a ++ " struct{}\n\n" ++
    "// New" ++ productionName a ++ " makes the native handler the generated tests use.\nfunc New" ++ productionName a ++
    "() " ++ interfaceName a ++ " {\n\treturn &" ++ productionName a ++ "{}\n}\n\n" ++ intercalate "\n" methods)
