-- Haskell pieces of a unit's abilities (see LawSpec.AbilityNames). Each
-- ability is a record of IO functions, one per operation, in
-- LawSpecAbilities.<Unit>; its spec handlers (fakeGateway :: SymbolContext ->
-- IO Gateway) and recording (gatewayRecording) are in LawSpecHandlers.<Unit>,
-- apart, since the definitions that perform operations import the records
-- and the handlers call the definitions. Handlers travel with the symbol
-- context (LS.installHandlers); a performed operation finds its handler
-- with LS.handlerOf and runs with LS.performIO.
module LawSpec.AbilityEmit.Haskell (emit, productionStub, typesModule, handlersModule, handlerFunction, recordingFunction, productionFunction) where

import Data.Char (toLower, toUpper)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.AbilityNames
import LawSpec.Collections (isCollectionsType)
import qualified LawSpec.HaskellData as Native
import qualified LawSpec.HaskellDefinitions as Definitions
import qualified LawSpec.HaskellExpr as E
import qualified LawSpec.Code.Doc as D

capitalize, lower :: String -> String
capitalize (c : cs) = toUpper c : cs
capitalize [] = []
lower (c : cs) = toLower c : cs
lower [] = []

split :: Char -> String -> [String]
split c s = case break (== c) s of
  (a, []) -> [a]
  (a, _ : rest) -> a : split c rest

modulePart :: String -> String
modulePart = concatMap capitalize . split '_'

unitModule :: String -> C.Unit -> String
unitModule prefix u = intercalate "." (prefix : map modulePart (split '.' (C.idText (C.unitId u))))

-- The module of a unit's ability records, and of its handlers.
typesModule, handlersModule :: C.Unit -> String
typesModule = unitModule "LawSpecAbilities"
handlersModule = unitModule "LawSpecHandlers"

-- fakeGateway's function, gatewayRecording, gatewayHandler (the user's).
handlerFunction :: C.Handler -> String
handlerFunction = C.handlerName

recordingFunction, productionFunction :: C.Ability -> String
recordingFunction = lower . recordingName
productionFunction = lower . productionName

emit :: Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit minify bits datas units = concat <$> mapM unitFiles (filter unitAbilityPieces units)
  where
    layout = if minify then D.Compact else D.Pretty 80
    calls = Definitions.definitionCalls units
    line = D.text
    collections = any (isCollectionsType . C.idText . C.dataId) datas
    imports extra = map line
      ([ "import Prelude ()", "import qualified Prelude as P", "import qualified Data.Int as I", "import qualified Data.Word as W"
       , "import qualified Data.Text as T", "import qualified Data.ByteString as B", "import qualified Data.Complex as C"
       , "import qualified Data.IORef as IORef"
       , "import LawSpecRuntime (Scalar(..))", "import qualified LawSpecRuntime as LS"
       , "import qualified LawSpecSchema as Schema", "import qualified LawSpecCodecs as Codec"
       , "import qualified LawSpecData as Data", "import qualified LawSpecDataSchema as DataSchema"
       , "import qualified LawSpecDataCodecs as Codecs" ] ++
       (if collections then [ "import qualified LawSpecCollectionCodecs as Collections", "import qualified Data.Set as Set"
                            , "import qualified Data.Map.Strict as Map", "import qualified Data.Sequence as Seq" ] else []) ++ extra)
    environment = map line ["_lawspecSchema :: Schema.Schema",
      "_lawspecSchema = P.either P.error P.id DataSchema.schema",
      "_lawspecBits :: P.Int", "_lawspecBits = " ++ show bits]
    file name header bodies = Artifact ("src/" ++ map (\c -> if c == '.' then '/' else c) name ++ ".hs")
      (D.render layout (D.joinWith D.hardline header <> D.hardline <> D.hardline <>
        D.joinWith (D.hardline <> D.hardline) bodies <> D.hardline)) "generated" "source"
    unitFiles u = do
      records <- mapM record (C.unitAbilities u)
      handlers <- mapM (specHandler u) (C.unitHandlers u)
      recordings <- mapM recording (C.unitAbilities u)
      let types = file (typesModule u)
            ([line "-- Generated by LawSpec. Do not edit.", line ("-- The abilities of " ++ C.idText (C.unitId u) ++ ": a record of operations for each."),
              line ("module " ++ typesModule u ++ " where"), line ""] ++ imports []) records
          handlerFile = file (handlersModule u)
            ([line "-- Generated by LawSpec. Do not edit.", line ("-- The spec handlers of " ++ C.idText (C.unitId u) ++ ", and a recording of any handler."),
              line ("module " ++ handlersModule u ++ " where"), line ""] ++
             imports (["import qualified LawSpecDefinitionBodies as Definitions" | not (null (C.unitHandlers u))] ++
               ["import " ++ typesModule u]) ++ [line ""] ++ environment) (handlers ++ recordings)
      pure [types, handlerFile]
    nativeType ty = Native.haskellDataType datas ty
    parenthesized t = if ' ' `elem` t && take 1 t /= "(" then "(" ++ t ++ ")" else t
    operationType ty = do
      let (args, result) = C.functionType ty
      types <- mapM nativeType args
      resultType <- nativeType result
      pure (intercalate " -> " (map parenthesized types ++ ["P.IO " ++ parenthesized resultType]))
    record a = do
      fields <- mapM (\(op, ty) -> (\t -> op ++ " :: " ++ t) <$> operationType ty) (C.abilityOperations a)
      pure (line ("-- | The " ++ C.abilityName a ++ " ability: a handler answers each of its operations.") <> D.hardline <>
        line ("data " ++ interfaceName a ++ " = " ++ interfaceName a) <> D.nest 2 (D.hardline <>
          D.joinWith D.hardline [line ((if i == 0 then "{ " else ", ") ++ f) | (i, f) <- zip [0 :: Int ..] fields] <>
          D.hardline <> line "}"))
    codec ty = Native.haskellCodecDocWithContext (E.apply "P.Just" [line "symbols"]) datas "_lawspecSchema" "_lawspecBits" ty
    specHandler u h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (lookup (C.abilityRefId (C.handlerAbility h)) [(C.abilityId a, a) | a <- C.unitAbilities u])
      start <- case C.handlerState h of
        Nothing -> pure []
        Just (_, value) -> do
          rendered <- E.renderExpression datas bits "_lawspecSchema" "symbols" (const "_unbound") (\_ _ -> Left "a handler's start value calls nothing") value
          pure [line "state <- IORef.newIORef" <> D.nest 2 (D.softline <> E.parens rendered)]
      fields <- mapM (\(i, (op, ty)) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        let (args, result) = C.functionType ty
            values = ["value" ++ show k | k <- [0 .. length args - 1]]
        codecs <- mapM codec args
        resultCodec <- codec result
        let inputs = [line ("argument" ++ show k ++ " <- ") <> E.apply "Codec.encode" [c, line v] | (k, (c, v)) <- zip [0 :: Int ..] (zip codecs values)]
            arguments = [line "symbols"] ++ [line "current" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [line "(LS.SAbsent \"Unit\")"] else [line ("argument" ++ show k) | k <- [0 .. length args - 1]])
            invocation = E.apply evaluate arguments
            lambda = if null values then mempty else line ("\\" ++ unwords values ++ " -> ")
            body = case C.handlerState h of
              Nothing -> lambda <> line "LS.runClause (do" <> D.nest 2 (D.hardline <> D.joinWith D.hardline
                (inputs ++ [line "result <- " <> invocation, E.apply "Codec.decode" [resultCodec, line "result"]]) <> line ")")
              Just _ -> lambda <> line "do" <> D.nest 2 (D.hardline <> D.joinWith D.hardline
                [ line "current <- IORef.readIORef state"
                , line "(result, next) <- LS.runClause (do" <> D.nest 2 (D.hardline <> D.joinWith D.hardline
                    (inputs ++ [line "pair <- " <> invocation, line "P.pure (LS.pairFields pair))"]))
                , line "IORef.writeIORef state next"
                , line "LS.runClause " <> E.parens (E.apply "Codec.decode" [resultCodec, line "result"]) ])
        pure (line ((if i == 0 then "{ " else ", ") ++ op ++ " =") <> D.nest 4 (D.hardline <> body))) (zip [0 :: Int ..] (C.abilityOperations ability))
      let name = handlerFunction h
      pure (line ("-- | The spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ".") <> D.hardline <>
        line (name ++ " :: LS.SymbolContext -> P.IO " ++ interfaceName ability) <> D.hardline <>
        line (name ++ " symbols = do") <> D.nest 2 (D.hardline <> D.joinWith D.hardline
          (start ++ [line ("P.pure " ++ interfaceName ability) <> D.nest 2 (D.hardline <> D.joinWith D.hardline fields <> D.hardline <> line "}")])))
    recording a = do
      fields <- mapM (\(i, (op, ty)) -> do
        let (args, _) = C.functionType ty
            values = ["value" ++ show k | k <- [0 .. length args - 1]]
        codecs <- mapM codec args
        let logged = E.apply "LS.runClause" [E.apply "P.sequence" [E.array [E.apply "Codec.encode" [c, line v] | (c, v) <- zip codecs values]]]
            lambda = if null values then mempty else line ("\\" ++ unwords values ++ " -> ")
            body = lambda <> line "do" <> D.nest 2 (D.hardline <> D.joinWith D.hardline
              [ line "logged <- " <> logged
              , line ("LS.recordCall calls " ++ show op ++ " logged")
              , line (unwords ((op ++ " inner") : values)) ])
        pure (line ((if i == 0 then "{ " else ", ") ++ op ++ " =") <> D.nest 4 (D.hardline <> body))) (zip [0 :: Int ..] (C.abilityOperations a))
      let name = recordingFunction a
      pure (line ("-- | Records each call to a " ++ C.abilityName a ++ " handler, then passes it on.") <> D.hardline <>
        line (name ++ " :: LS.SymbolContext -> " ++ interfaceName a ++ " -> P.IO (" ++ interfaceName a ++ ", LS.Calls)") <> D.hardline <>
        line (name ++ " symbols inner = do") <> D.nest 2 (D.hardline <> D.joinWith D.hardline
          [ line "calls <- LS.newCalls"
          , line ("P.pure (" ++ interfaceName a) <> D.nest 2 (D.hardline <> D.joinWith D.hardline fields <> D.hardline <> line "}, calls)") ]))

-- The user-owned production handler of each ability, in the unit's adapter
-- module: gatewayHandler :: IO Gateway is what the tests use.
productionStub :: [C.DataDeclaration] -> C.Ability -> Either String D.Doc
productionStub datas a = do
  let name = productionFunction a
      fields = [(if i == 0 then "{ " else ", ") ++ "Abilities." ++ op ++ " = " ++
                 (if null args then "" else "\\" ++ unwords (replicate (length args) "_") ++ " -> ") ++ "P.error " ++ show op
               | (i, (op, ty)) <- zip [0 :: Int ..] (C.abilityOperations a), let (args, _) = C.functionType ty]
  _ <- mapM (Native.haskellDataType datas . snd . C.functionType . snd) (C.abilityOperations a)
  pure (D.text ("-- | The native handler of " ++ C.abilityName a ++ ": " ++ intercalate ", " (map fst (C.abilityOperations a)) ++ ".") <> D.hardline <>
    D.text (name ++ " :: P.IO Abilities." ++ interfaceName a) <> D.hardline <>
    D.text (name ++ " = P.pure Abilities." ++ interfaceName a) <> D.nest 2 (D.hardline <> D.joinWith D.hardline (map D.text fields) <> D.hardline <> D.text "}"))
