-- Java pieces of a unit's abilities (see LawSpec.AbilityNames), in the class
-- lawspec.abilities.<unit package>.<Unit>: a nested interface per ability, a
-- class per spec handler and a recording class per ability. Handlers travel
-- in the symbols map generated code passes to every definition.
module LawSpec.AbilityEmit.Java (emit, productionStub, abilitiesClass, abilitiesClassOf, adapterClassOf) where

import Data.Char (toUpper)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.AbilityNames
import qualified LawSpec.JavaData as Native
import qualified LawSpec.JavaDefinitions as Definitions
import qualified LawSpec.JavaExpr as E
import qualified LawSpec.Code.Doc as D

capitalize :: String -> String
capitalize (c : cs) = toUpper c : cs
capitalize [] = []

split :: Char -> String -> [String]
split c s = case break (== c) s of
  (a, []) -> [a]
  (a, _ : rest) -> a : split c rest

-- The generated class holding a unit's abilities, fully qualified.
abilitiesClass :: C.Unit -> String
abilitiesClass = abilitiesClassOf . C.idText . C.unitId

-- The same, by the unit's name: an imported ability's pieces are its owner's.
abilitiesClassOf :: String -> String
abilitiesClassOf unit =
  let parts = split '.' unit
  in intercalate "." ("lawspec" : "abilities" : init parts ++ [concatMap capitalize (split '_' (last parts))])

-- A unit's user-owned adapter class, fully qualified: example.abilities is
-- example.Abilities. It holds the production handlers of the unit's abilities.
adapterClassOf :: String -> String
adapterClassOf unit =
  let parts = split '.' unit
  in intercalate "." (init parts ++ [concatMap capitalize (split '_' (last parts))])

emit :: Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit minify bits datas units = mapM unitFile (filter unitAbilityPieces units)
  where
    layout = if minify then D.Compact else D.Pretty 100
    calls = Definitions.definitionCalls units
    line = D.text
    unitFile u = do
      let qualified = split '.' (abilitiesClass u)
          package = intercalate "." (init qualified)
          name = last qualified
      nestedClashes "Java" name u
      interfaces <- mapM interface (ownAbilities u)
      handlers <- mapM (specHandler u) (C.unitHandlers u)
      recordings <- mapM recording (ownAbilities u)
      let source = line "// Generated by LawSpec. Do not edit." <> D.hardline <>
            line ("package " ++ package ++ ";") <> D.hardline <> D.hardline <>
            line "import java.util.Map;" <> D.hardline <>
            line "import lawspec.runtime.LawSpecRuntime;" <> D.hardline <>
            line "import lawspec.runtime.LawSpecRuntime.Value;" <> D.hardline <> D.hardline <>
            line ("/** The abilities of " ++ C.idText (C.unitId u) ++ ": an interface for each, its spec handlers, and a recording of any handler of it. */") <> D.hardline <>
            line ("public final class " ++ name ++ " ") <> D.block 2 (D.joinWith (D.hardline <> D.hardline)
              ([line ("private " ++ name ++ "() {}"),
                line "private static final lawspec.runtime.LawSpecSchema _schema = lawspec.runtime.LawSpecDataSchema.create();"] ++
               interfaces ++ handlers ++ recordings)) <> D.hardline
      pure (Artifact ("src/main/java/" ++ intercalate "/" qualified ++ ".java") (D.render layout source) "generated" "source")
    signature op ty = do
      let (args, result) = C.functionType ty
      types <- mapM (Native.javaDataTypeDoc datas) args
      resultType <- if result == C.scalarType "Unit" then pure (line "void") else Native.javaDataTypeDoc datas result
      pure (resultType <> line (" " ++ op) <> D.delimitTrailing 4 "(" ")" [t <> line (" value" ++ show i) | (i, t) <- zip [0 :: Int ..] types])
    interface a = do
      methods <- mapM (\(op, ty) -> (<> line ";") <$> signature op ty) (C.abilityOperations a)
      pure (line ("/** The " ++ C.abilityName a ++ " ability: a handler answers each of its operations. */") <> D.hardline <>
        line ("public interface " ++ interfaceName a ++ " ") <> D.block 2 (D.joinWith D.hardline methods))
    codec ty = Native.javaCodecDocWithContext (line "symbols") datas bits ty
    specHandler u h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (unitAbility u (C.handlerAbility h))
      initialState <- case C.handlerState h of
        Nothing -> pure []
        Just (_, start) -> do
          value <- E.renderExpression datas bits (const "_unbound") (\_ _ -> Left "a handler's start value calls nothing") start
          pure [line "this.state = " <> value <> line ";"]
      let name = specName h
      methods <- mapM (\(op, ty) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        s <- signature op ty
        let (args, result) = C.functionType ty
        argumentCodecs <- mapM codec args
        resultCodec <- codec result
        let arguments = line "symbols" : [line "state" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [line "LawSpecRuntime.absent(\"Unit\")"]
               else [c <> line (".encode(value" ++ show i ++ ")") | (i, c) <- zip [0 :: Int ..] argumentCodecs])
            invocation = E.call evaluate arguments
            outcome = case C.handlerState h of
              Nothing -> [line "var result = " <> invocation <> line ";"]
              Just _ -> [line "var pair = LawSpecRuntime.pairFields(" <> invocation <> line ");", line "state = pair.get(1);", line "var result = pair.get(0);"]
            returned
              | result == C.scalarType "Unit" = []
              | otherwise = [line "return " <> resultCodec <> line ".decode(result);"]
        pure (line "@Override" <> D.hardline <> line "public " <> s <> line " " <> D.block 2 (D.joinWith D.hardline (outcome ++ returned)))) (C.abilityOperations ability)
      pure (line ("/** The spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ". */") <> D.hardline <>
        line ("public static final class " ++ name ++ " implements " ++ abilitiesClassOf (ownerName ability) ++ "." ++ interfaceName ability ++ " ") <> D.block 2 (D.joinWith (D.hardline <> D.hardline)
          ([ line "private final Map<String, Object> symbols;" <> D.hardline <> line "private Value state;"
           , line ("public " ++ name ++ "(Map<String, Object> symbols) ") <> D.block 2 (D.joinWith D.hardline (line "this.symbols = symbols;" : initialState)) ] ++
           methods)))
    recording a = do
      let name = recordingName a
      methods <- mapM (\(op, ty) -> do
        s <- signature op ty
        let (args, result) = C.functionType ty
        argumentCodecs <- mapM codec args
        let logged = E.call "java.util.List.of" [c <> line (".encode(value" ++ show i ++ ")") | (i, c) <- zip [0 :: Int ..] argumentCodecs]
            forward = "inner." ++ op ++ "(" ++ intercalate ", " ["value" ++ show i | i <- [0 .. length args - 1]] ++ ");"
        pure (line "@Override" <> D.hardline <> line "public " <> s <> line " " <> D.block 2 (D.joinWith D.hardline
          [ line ("calls.add(new LawSpecRuntime.RecordedCall(" ++ show op ++ ", ") <> logged <> line "));"
          , line (if result == C.scalarType "Unit" then forward else "return " ++ forward) ]))) (C.abilityOperations a)
      pure (line ("/** Records each call to a " ++ C.abilityName a ++ " handler, then passes it on. */") <> D.hardline <>
        line ("public static final class " ++ name ++ " implements " ++ interfaceName a ++ ", LawSpecRuntime.Recorded ") <> D.block 2 (D.joinWith (D.hardline <> D.hardline)
          ([ line "private final Map<String, Object> symbols;" <> D.hardline <>
             line ("public final " ++ interfaceName a ++ " inner;") <> D.hardline <>
             line "public final java.util.List<LawSpecRuntime.RecordedCall> calls = new java.util.ArrayList<>();"
           , line ("public " ++ name ++ "(" ++ interfaceName a ++ " inner, Map<String, Object> symbols) ") <>
             D.block 2 (line "this.inner = inner;" <> D.hardline <> line "this.symbols = symbols;")
           , line "@Override" <> D.hardline <> line "public java.util.List<LawSpecRuntime.RecordedCall> lawSpecCalls() " <> D.block 2 (line "return calls;") ] ++
           methods)))

-- The user-owned production handler of each ability, nested in the unit's
-- adapter class: new <Unit>.<Ability>Handler() is what the tests use.
productionStub :: [C.DataDeclaration] -> C.Unit -> C.Ability -> Either String D.Doc
productionStub datas u a = do
  methods <- mapM (\(op, ty) -> do
    let (args, result) = C.functionType ty
    types <- mapM (Native.javaDataTypeDoc datas) args
    resultType <- if result == C.scalarType "Unit" then pure (D.text "void") else Native.javaDataTypeDoc datas result
    pure (D.text "@Override" <> D.hardline <> D.text "public " <> resultType <> D.text (" " ++ op) <>
      D.delimitTrailing 4 "(" ")" [t <> D.text (" value" ++ show i) | (i, t) <- zip [0 :: Int ..] types] <> D.text " " <>
      D.block 2 (D.text ("throw new UnsupportedOperationException(" ++ show op ++ ");")))) (C.abilityOperations a)
  pure (D.text ("/** The native handler of " ++ displayName a ++ ": " ++ intercalate ", " (map fst (C.abilityOperations a)) ++ ". */") <> D.hardline <>
    D.text ("public static final class " ++ productionName a ++ " implements " ++ abilitiesClass u ++ "." ++ interfaceName a ++ " ") <>
    D.block 2 (D.joinWith (D.hardline <> D.hardline) methods))
