-- Kotlin pieces of a unit's abilities (see LawSpec.AbilityNames), in the
-- object lawspec.abilities.<unit package>.<Unit>: a nested interface per
-- ability, a class per spec handler and a recording class per ability.
-- Handlers travel in the symbols map generated code passes to every
-- definition; the shared JVM bodies reach a Kotlin handler through a bridge
-- in LawSpecKotlinAdapters (see LawSpec.KotlinDefinitions).
module LawSpec.AbilityEmit.Kotlin (emit, productionStub, abilitiesObject) where

import Data.Char (toUpper)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.AbilityNames
import qualified LawSpec.KotlinData as Native
import qualified LawSpec.JavaDefinitions as Definitions
import qualified LawSpec.KotlinExpr as E
import qualified LawSpec.Code.Doc as D

capitalize :: String -> String
capitalize (c : cs) = toUpper c : cs
capitalize [] = []

split :: Char -> String -> [String]
split c s = case break (== c) s of
  (a, []) -> [a]
  (a, _ : rest) -> a : split c rest

-- The generated object holding a unit's abilities, fully qualified.
abilitiesObject :: C.Unit -> String
abilitiesObject u =
  let parts = split '.' (C.idText (C.unitId u))
  in intercalate "." ("lawspec" : "abilities" : init parts ++ [concatMap capitalize (split '_' (last parts))])

emit :: Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit minify bits datas units = mapM unitFile (filter unitAbilityPieces units)
  where
    layout = if minify then D.Compact else D.Pretty 100
    calls = Definitions.definitionCalls units
    line = D.text
    unitFile u = do
      let qualified = split '.' (abilitiesObject u)
          package = intercalate "." (init qualified)
          name = last qualified
      interfaces <- mapM interface (C.unitAbilities u)
      handlers <- mapM (specHandler u) (C.unitHandlers u)
      recordings <- mapM recording (C.unitAbilities u)
      let source = line "// Generated by LawSpec. Do not edit." <> D.hardline <>
            line ("package " ++ package) <> D.hardline <> D.hardline <>
            line "import lawspec.runtime.LawSpecRuntime" <> D.hardline <>
            line "import lawspec.runtime.LawSpecDataSchema" <> D.hardline <>
            line "import lawspec.runtime.LawSpecSchema" <> D.hardline <>
            line "import lawspec.runtime.LawSpecDataCodecs" <> D.hardline <>
            line "import lawspec.runtime.LawSpecKotlinCodecs" <> D.hardline <> D.hardline <>
            line ("/** The abilities of " ++ C.idText (C.unitId u) ++ ": an interface for each, its spec handlers, and a recording of any handler of it. */") <> D.hardline <>
            line ("object " ++ name ++ " ") <> D.block 4 (D.joinWith (D.hardline <> D.hardline)
              ([line "private val schema = LawSpecDataSchema.create()",
                line "private val _schema = schema",
                line ("private const val bits = " ++ show bits)] ++
               interfaces ++ handlers ++ recordings)) <> D.hardline
      pure (Artifact ("src/main/kotlin/" ++ intercalate "/" qualified ++ ".kt") (D.render layout source) "generated" "source")
    signature op ty = do
      let (args, result) = C.functionType ty
      types <- mapM (Native.kotlinDataTypeDoc datas) args
      resultType <- if result == C.scalarType "Unit" then pure (line "Unit") else Native.kotlinDataTypeDoc datas result
      pure (line ("fun " ++ op) <> D.delimitTrailing 4 "(" ")" [line ("value" ++ show i ++ ": ") <> t | (i, t) <- zip [0 :: Int ..] types] <>
        line ": " <> resultType)
    interface a = do
      methods <- mapM (\(op, ty) -> signature op ty) (C.abilityOperations a)
      pure (line ("/** The " ++ C.abilityName a ++ " ability: a handler answers each of its operations. */") <> D.hardline <>
        line ("interface " ++ interfaceName a ++ " ") <> D.block 4 (D.joinWith D.hardline methods))
    codec ty = Native.kotlinCodecDocWithContext (line "symbols") datas ty
    specHandler u h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (lookup (C.abilityRefId (C.handlerAbility h)) [(C.abilityId a, a) | a <- C.unitAbilities u])
      initialState <- case C.handlerState h of
        Nothing -> pure (line "null")
        Just (_, start) -> E.renderExpression datas bits (const "_unbound") (\_ _ -> Left "a handler's start value calls nothing") start
      let name = specName h
      methods <- mapM (\(op, ty) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        s <- signature op ty
        let (args, result) = C.functionType ty
        argumentCodecs <- mapM codec args
        resultCodec <- codec result
        let arguments = line "symbols" : [line "state!!" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [line "LawSpecRuntime.absent(\"Unit\")"]
               else [c <> line (".encode(value" ++ show i ++ ")") | (i, c) <- zip [0 :: Int ..] argumentCodecs])
            invocation = E.call evaluate arguments
            outcome = case C.handlerState h of
              Nothing -> [line "val result = " <> invocation]
              Just _ -> [line "val pair = LawSpecRuntime.pairFields(" <> invocation <> line ")", line "state = pair[1]", line "val result = pair[0]"]
            returned
              | result == C.scalarType "Unit" = []
              | otherwise = [line "return " <> resultCodec <> line ".decode(result)"]
        pure (line "override " <> s <> line " " <> D.block 4 (D.joinWith D.hardline (outcome ++ returned)))) (C.abilityOperations ability)
      pure (line ("/** The spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ". */") <> D.hardline <>
        line ("class " ++ name ++ "(private val symbols: MutableMap<String, Any>) : " ++ interfaceName ability ++ " ") <>
        D.block 4 (D.joinWith (D.hardline <> D.hardline)
          (line "private var state: LawSpecRuntime.Value? = " <> initialState : methods)))
    recording a = do
      let name = recordingName a
      methods <- mapM (\(op, ty) -> do
        s <- signature op ty
        let (args, _) = C.functionType ty
        argumentCodecs <- mapM codec args
        let logged = E.call "listOf" [c <> line (".encode(value" ++ show i ++ ")") | (i, c) <- zip [0 :: Int ..] argumentCodecs]
            forward = "inner." ++ op ++ "(" ++ intercalate ", " ["value" ++ show i | i <- [0 .. length args - 1]] ++ ")"
        pure (line "override " <> s <> line " " <> D.block 4 (D.joinWith D.hardline
          [ line ("calls.add(LawSpecRuntime.RecordedCall(" ++ show op ++ ", ") <> logged <> line "))"
          , line ("return " ++ forward) ]))) (C.abilityOperations a)
      pure (line ("/** Records each call to a " ++ C.abilityName a ++ " handler, then passes it on. */") <> D.hardline <>
        line ("class " ++ name ++ "(val inner: " ++ interfaceName a ++ ", private val symbols: MutableMap<String, Any>) : " ++
          interfaceName a ++ ", LawSpecRuntime.Recorded ") <> D.block 4 (D.joinWith (D.hardline <> D.hardline)
          ([ line "val calls: MutableList<LawSpecRuntime.RecordedCall> = mutableListOf()"
           , line "override fun lawSpecCalls(): List<LawSpecRuntime.RecordedCall> = calls" ] ++
           methods)))

-- The user-owned production handler of each ability, nested in the unit's
-- adapter object: <Unit>.<Ability>Handler() is what the tests use.
productionStub :: [C.DataDeclaration] -> C.Unit -> C.Ability -> Either String D.Doc
productionStub datas u a = do
  methods <- mapM (\(op, ty) -> do
    let (args, result) = C.functionType ty
    types <- mapM (Native.kotlinDataTypeDoc datas) args
    resultType <- if result == C.scalarType "Unit" then pure (D.text "Unit") else Native.kotlinDataTypeDoc datas result
    pure (D.text ("override fun " ++ op) <>
      D.delimitTrailing 4 "(" ")" [D.text ("value" ++ show i ++ ": ") <> t | (i, t) <- zip [0 :: Int ..] types] <>
      D.text ": " <> resultType <> D.text (" = TODO(" ++ show op ++ ")"))) (C.abilityOperations a)
  pure (D.text ("/** The native handler of " ++ C.abilityName a ++ ": " ++ intercalate ", " (map fst (C.abilityOperations a)) ++ ". */") <> D.hardline <>
    D.text ("class " ++ productionName a ++ " : " ++ abilitiesObject u ++ "." ++ interfaceName a ++ " ") <>
    D.block 4 (D.joinWith D.hardline methods))
