-- Python pieces of a unit's abilities (see LawSpec.AbilityNames): a
-- typing.Protocol per ability, a class per spec handler and a recording
-- class per ability, in lawspec_abilities/<unit path>.py.
--
-- Handlers travel in the symbols context that generated code already passes
-- to every definition (evidence passing): a law installs them with
-- ls.install_handlers, and a performed operation finds its handler with
-- ls.handler(symbols, key). Native code gets them as arguments instead.
module LawSpec.AbilityEmit.Python (emit, modulePath, moduleName, moduleNameOf, productionStub) where

import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.AbilityNames
import LawSpec.PythonTypes (pythonDataTypeDoc, pythonTypeReferenceDoc)
import qualified LawSpec.PythonDefinitions as Definitions
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.PythonExpr as E
import LawSpec.Scalar (Scalar(..))

-- The generated module of a unit's abilities.
moduleName :: C.Unit -> String
moduleName = moduleNameOf . C.idText . C.unitId

-- The generated module of the unit of this name.
moduleNameOf :: String -> String
moduleNameOf unit = "lawspec_abilities." ++ unit

modulePath :: C.Unit -> String
modulePath u = "src/lawspec_abilities/" ++ map (\c -> if c == '.' then '/' else c) (C.idText (C.unitId u)) ++ ".py"

emit :: Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit minify bits datas units = mapM unitModule (filter unitAbilityPieces units)
  where
    layout = D.selectLayout minify (D.Pretty 79)
    calls = Definitions.definitionCalls units
    width = D.text (show bits)
    schemaCall name ty value = do
      ref <- pythonTypeReferenceDoc ty
      pure (E.call ("_lawspec_schema." ++ name) [ref, value, width, D.text "symbols"])
    unitModule u = do
      protocols <- mapM protocol (ownAbilities u)
      handlers <- mapM (specHandler u) (C.unitHandlers u)
      recordings <- mapM recording (ownAbilities u)
      let header = D.joinWith D.hardline (map D.text
            [ "# Generated by LawSpec. Do not edit."
            , "\"\"\"The abilities of " ++ C.idText (C.unitId u) ++ ": an interface for each,"
            , "its spec handlers, and a recording of any handler of it.\"\"\""
            , "from __future__ import annotations"
            , ""
            , "import builtins as _builtins"
            , "import typing as _typing"
            , ""
            , "import lawspec_data as data"
            , "import lawspec_runtime as ls"
            , "import lawspec_schema as _schema" ] ++
            [D.text "import lawspec_definition_bodies as _definitions" | not (null (C.unitHandlers u))] ++
            [D.hardline <> D.text "_lawspec_schema = data.make_schema()"])
          body = D.joinWith (D.hardline <> D.hardline <> D.hardline) (protocols ++ handlers ++ recordings)
      pure (Artifact (modulePath u) (D.render layout (header <> D.hardline <> D.hardline <> D.hardline <> body <> D.hardline)) "generated" "source")
    parameters ty = do
      let (args, result) = C.functionType ty
      types <- mapM (pythonDataTypeDoc datas) args
      resultType <- if result == C.scalarType "Unit" then pure (D.text "None") else pythonDataTypeDoc datas result
      pure (D.delimitTrailing 4 "(" ")" (D.text "self" : [D.text ("value" ++ show i ++ ": ") <> t | (i, t) <- zip [0 :: Int ..] types]) <>
        D.text " -> " <> resultType)
    protocol a = do
      methods <- mapM (\(op, ty) -> (\ps -> D.text ("def " ++ op) <> ps <> D.text ": ...") <$> parameters ty) (C.abilityOperations a)
      pure (E.suite (D.text ("class " ++ interfaceName a ++ "(_typing.Protocol)"))
        (D.joinWith D.hardline (D.text ("\"\"\"The " ++ interfaceName a ++ " ability: a handler answers each of its operations.\"\"\"") : methods)))
    specHandler u h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (unitAbility u (C.handlerAbility h))
      initialState <- case C.handlerState h of
        Nothing -> pure []
        Just (_, start) -> do
          value <- E.renderExpression datas bits (const "_unbound") (\_ _ -> Left "a handler's start value calls nothing") start
          pure [D.text "symbols = self._symbols", D.text "self._state = " <> value]
      methods <- mapM (\(op, ty) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        ps <- parameters ty
        let (args, result) = C.functionType ty
        inputs <- sequence [schemaCall "from_native" t (D.text ("value" ++ show i)) | (i, t) <- zip [0 :: Int ..] args]
        let arguments = D.text "symbols" : [D.text "self._state" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [E.scalarLiteral (SAbsent "Unit")] else inputs)
            invocation = E.call evaluate arguments
        output <- schemaCall "to_native" result (D.text "result")
        let statements = case C.handlerState h of
              Nothing -> [D.text "result = " <> invocation]
              Just _ -> [D.text "pair = " <> invocation, D.text "self._state = pair.fields[1]", D.text "result = pair.fields[0]"]
        pure (E.suite (D.text ("def " ++ op) <> ps)
          (D.joinWith D.hardline (D.text "symbols = self._symbols" : statements ++ [D.text "return " <> output])))) (C.abilityOperations ability)
      pure (E.suite (D.text ("class " ++ specName h))
        (D.joinWith D.hardline (D.text ("\"\"\"The spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ".\"\"\"") : D.text "" :
          E.suite (D.text "def __init__(self, symbols=None)")
            (D.joinWith D.hardline (D.text "self._symbols = {} if symbols is None else symbols" : initialState)) :
          concatMap (\m -> [D.text "", m]) methods)))
    recording a = do
      methods <- mapM (\(op, ty) -> do
        ps <- parameters ty
        let (args, _) = C.functionType ty
        logged <- sequence [schemaCall "from_native" t (D.text ("value" ++ show i)) | (i, t) <- zip [0 :: Int ..] args]
        let values = [D.text ("value" ++ show i) | i <- [0 .. length args - 1]]
        pure (E.suite (D.text ("def " ++ op) <> ps) (D.joinWith D.hardline
          [ D.text "symbols = self._symbols"
          , D.text "self.calls.append(" <> D.delimitTrailing 4 "(" ")" [E.quoted op, E.array logged] <> D.text ")"
          , D.text "return self.inner." <> E.call op values ]))) (C.abilityOperations a)
      pure (E.suite (D.text ("class " ++ recordingName a))
        (D.joinWith D.hardline ([ D.text ("\"\"\"Records each call to a " ++ C.abilityName a ++ " handler, then passes it on.\"\"\"")
          , D.text ""
          , E.suite (D.text "def __init__(self, inner, symbols=None)") (D.joinWith D.hardline (map D.text
              [ "self.inner = inner"
              , "self.calls = []"
              , "self._symbols = {} if symbols is None else symbols" ])) ] ++
          concatMap (\m -> [D.text "", m]) methods)))

-- The user-owned production handler of each ability, in the unit's
-- adapter module.
productionStub :: [C.DataDeclaration] -> C.Ability -> Either String String
productionStub datas a = do
  methods <- mapM (\(op, ty) -> do
    let (args, result) = C.functionType ty
    types <- mapM (pythonDataTypeDoc datas) args
    resultType <- if result == C.scalarType "Unit" then pure (D.text "None") else pythonDataTypeDoc datas result
    pure (E.suite (D.text ("def " ++ op) <>
      D.delimitTrailing 4 "(" ")" (D.text "self" : [D.text ("value" ++ show i ++ ": ") <> t | (i, t) <- zip [0 :: Int ..] types]) <>
      D.text " -> " <> resultType) (D.text ("raise NotImplementedError(" ++ show op ++ ")")))) (C.abilityOperations a)
  pure (D.render (D.Pretty 79) (E.suite (D.text ("class " ++ productionName a))
    (D.joinWith D.hardline (D.text ("\"\"\"The native handler of " ++ displayName a ++ ": " ++
      intercalate ", " (map fst (C.abilityOperations a)) ++ ".\"\"\"") : concatMap (\m -> [D.text "", m]) methods))) ++ "\n")
