-- Rust pieces of the program's abilities (see LawSpec.AbilityNames), in
-- src/lawspec_abilities.rs, one module per unit: a trait per ability, a
-- struct per spec handler (made by new), a recording struct per ability,
-- and a perform bridge per operation, which the generated definitions and
-- tests call with the context: the handler is installed in it (evidence
-- passing). Rust panics are the Fail ability's aborts; see
-- ls::raise_failure.
module LawSpec.AbilityEmit.Rust (emit, moduleOf, moduleOfName, performBridges, productionStub, traitPath, handlerConstruction, foreignOwners) where

import Data.Char (isAlphaNum)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.AbilityNames
import LawSpec.RustAbilityPaths
import qualified LawSpec.RustData as Native
import qualified LawSpec.RustDefinitions as Definitions
import qualified LawSpec.RustExpr as E
import qualified LawSpec.Code.Doc as D

-- How a test makes the handler a law chose for an ability, as an
-- ls::Installed; root is "" in a test crate and "crate::" in the library.
handlerConstruction :: Maybe String -> [C.Unit] -> C.Unit -> C.AbilityRef -> C.HandlerRef -> String
handlerConstruction library units current ref choice = case choice of
  C.RecordingHandler inner ->
    "{ let recording = " ++ base ++ recordingFor ++ "::new(" ++ handle inner ++ "); let calls = recording.calls.clone(); " ++
    "ls::installed_recording(std::sync::Arc::new(recording) as std::sync::Arc<dyn " ++ trait ++ ">, calls) }"
  _ -> "ls::installed(" ++ handle choice ++ ")"
  where
    trait = traitPath units ref
    found = snd <$> C.findAbility units ref
    base = case found of
      Just a -> "lawspec_abilities::" ++ moduleOfName (ownerName a) ++ "::"
      Nothing -> ""
    recordingFor = maybe "Unknown" recordingName found
    adapterModule = case found of
      Just a | ownerName a /= C.idText (C.unitId current) -> moduleOfName (ownerName a)
      _ -> "adapter"
    handle c = case c of
      C.ProductionHandler | Just parts <- native ->
        "std::sync::Arc::new(" ++ intercalate "::" [if p == "crate" then maybe p id library else p | p <- parts] ++ "()) as std::sync::Arc<dyn " ++ trait ++ ">"
      C.ProductionHandler -> "std::sync::Arc::new(" ++ adapterModule ++ "::" ++ productionFor ++ "::default()) as std::sync::Arc<dyn " ++ trait ++ ">"
      C.SpecHandler h -> "std::sync::Arc::new(lawspec_abilities::" ++ moduleOf current ++ "::" ++ maybe "Unknown" specName (specHandlerOf units h) ++ "::new(ctx)) as std::sync::Arc<dyn " ++ trait ++ ">"
      C.RecordingHandler inner -> handle inner
    native = found >>= C.abilityNative
    productionFor = maybe "Unknown" productionName found

emit :: Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String String
emit minify bits datas units = do
  modules <- mapM unitModule (filter unitAbilityPieces units)
  pure (D.render layout (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
    D.text "#![allow(unused_variables, unused_imports, dead_code, non_snake_case, unused_mut)]" <> D.hardline <>
    D.text "use crate::lawspec_runtime as ls;" <> D.hardline <> D.hardline <>
    D.joinWith (D.hardline <> D.hardline) modules <> D.hardline))
  where
    layout = D.selectLayout minify (D.Pretty 100)
    calls = Definitions.definitionNames units
    line = D.text
    width = show bits
    unwrap = ".unwrap_or_else(|error| panic!(\"{error}\"))"
    nativeType ty = Native.rustDataType datas ty
    unitModule u = do
      traits <- mapM trait (ownAbilities u)
      handlers <- mapM (specHandler u) (C.unitHandlers u)
      recordings <- mapM recording (ownAbilities u)
      bridges <- concat <$> mapM bridge (ownAbilities u)
      pure (line ("pub mod " ++ moduleOf u ++ " ") <> D.block 4 (line "use super::ls;" <> D.hardline <> D.hardline <>
        D.joinWith (D.hardline <> D.hardline) (traits ++ handlers ++ recordings ++ bridges)))
    signature op ty = do
      let (args, result) = C.functionType ty
      types <- mapM nativeType args
      resultType <- nativeType result
      pure ("fn " ++ op ++ "(&self" ++ concat [", value" ++ show i ++ ": " ++ t | (i, t) <- zip [0 :: Int ..] types] ++ ") -> " ++ resultType)
    trait a = do
      methods <- mapM (\(op, ty) -> (\s -> line (s ++ ";")) <$> signature op ty) (C.abilityOperations a)
      pure (line ("/// The " ++ C.abilityName a ++ " ability: a handler answers each of its operations.") <> D.hardline <>
        line ("pub trait " ++ interfaceName a ++ ": Send + Sync ") <> D.block 4 (D.joinWith D.hardline methods))
    -- A native result from a logical value, as the definitions' wrappers do.
    toNative ty value = do
      native <- nativeType ty
      ref <- E.reference ty
      pure [ line "let schema = crate::lawspec_schema::schema()" <> line unwrap <> line ";"
           , line "let result = schema.native_value_with_context(" <> line value <> line ", &" <> ref <> line (", " ++ width ++ ", ctx)" ++ unwrap ++ ";")
           , line ("<" ++ native ++ " as ls::FromValue>::from_value(result)" ++ unwrap) ]
    specHandler u h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (unitAbility u (C.handlerAbility h))
      start <- case C.handlerState h of
        Nothing -> pure (line "None")
        Just (_, value) -> do
          rendered <- E.renderExpression datas bits [] [] value
          pure (line "Some((|| -> ls::Result<ls::Value> " <> D.block 4 (line "let ctx = &mut ctx;" <> D.hardline <>
            line "let value = " <> rendered <> line ";" <> D.hardline <> line "Ok(value)") <> line ")()" <> line unwrap <> line ")")
      methods <- mapM (\(op, ty) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        s <- signature op ty
        let (args, result) = C.functionType ty
        converted <- toNative result "result"
        let arguments = [line "self.state.lock().unwrap().clone().unwrap()" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [line "ls::Value::Unit"]
               else [line ("ls::IntoValue::into_value(value" ++ show i ++ ")") | i <- [0 .. length args - 1]])
            invocation = line ("crate::lawspec_definitions::" ++ evaluate ++ "(ctx, ") <> E.vector arguments <> line (")" ++ unwrap)
            outcome = case C.handlerState h of
              Nothing -> [line "let result = " <> invocation <> line ";"]
              Just _ -> [ line "let pair = " <> invocation <> line ";"
                        , line ("let (result, next) = ls::pair_fields(pair)" ++ unwrap ++ ";")
                        , line "*self.state.lock().unwrap() = Some(next);" ]
        pure (line s <> line " " <> D.block 4 (D.joinWith D.hardline
          ([line "let mut guard = self.ctx.lock().unwrap();", line "let ctx = &mut *guard;"] ++ outcome ++ converted)))) (C.abilityOperations ability)
      let name = specName h
      pure (line ("/// The spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ".") <> D.hardline <>
        line ("pub struct " ++ name ++ " ") <> D.block 4 (D.joinWith D.hardline
          [line "ctx: std::sync::Mutex<ls::Context>,", line "state: std::sync::Mutex<Option<ls::Value>>,"]) <> D.hardline <> D.hardline <>
        line ("impl " ++ name ++ " ") <> D.block 4
          (line "/// The handler for a law; it evaluates its clauses in a copy of the law's context." <> D.hardline <>
           line "pub fn new(ctx: &ls::Context) -> Self " <> D.block 4 (D.joinWith D.hardline
             [ line "let mut ctx = ctx.clone();"
             , line "let state = " <> start <> line ";"
             , line ("Self { ctx: std::sync::Mutex::new(ctx), state: std::sync::Mutex::new(state) }") ])) <> D.hardline <> D.hardline <>
        line ("impl super::" ++ moduleOfName (ownerName ability) ++ "::" ++ interfaceName ability ++ " for " ++ name ++ " ") <> D.block 4 (D.joinWith (D.hardline <> D.hardline) methods))
    recording a = do
      methods <- mapM (\(op, ty) -> do
        s <- signature op ty
        let (args, _) = C.functionType ty
            values = ["value" ++ show i | i <- [0 .. length args - 1]]
        pure (line s <> line " " <> D.block 4 (D.joinWith D.hardline
          [ line ("self.calls.record(" ++ show op ++ ", ") <> E.vector [line ("ls::IntoValue::into_value(" ++ v ++ ".clone())") | v <- values] <> line ");"
          , line ("self.inner." ++ op ++ "(" ++ intercalate ", " values ++ ")") ]))) (C.abilityOperations a)
      let name = recordingName a
      pure (line ("/// Records each call to a " ++ C.abilityName a ++ " handler, then passes it on.") <> D.hardline <>
        line ("pub struct " ++ name ++ " ") <> D.block 4 (D.joinWith D.hardline
          [line ("pub inner: std::sync::Arc<dyn " ++ interfaceName a ++ ">,"), line "pub calls: ls::Calls,"]) <> D.hardline <> D.hardline <>
        line ("impl " ++ name ++ " ") <> D.block 4
          (line ("pub fn new(inner: std::sync::Arc<dyn " ++ interfaceName a ++ ">) -> Self ") <>
           D.block 4 (line "Self { inner, calls: ls::Calls::default() }")) <> D.hardline <> D.hardline <>
        line ("impl " ++ interfaceName a ++ " for " ++ name ++ " ") <> D.block 4 (D.joinWith (D.hardline <> D.hardline) methods))
    -- Each operation's bridge: the handler from the context, the arguments
    -- to native values and the result back.
    bridge a = mapM (\(op, ty) -> do
      let (args, result) = C.functionType ty
      types <- mapM nativeType args
      refs <- mapM E.reference args
      let decode n (t, ref) = line ("let native_" ++ show n ++ " = ") <>
            E.call ("<" ++ t ++ " as ls::FromValue>::from_value")
              [E.call "schema.native_value_with_context" [line ("arguments[" ++ show n ++ "].clone()"), line "&" <> ref, line width, line "ctx"] <> line "?"] <> line "?;"
      pure (line ("/// " ++ op ++ ", answered by the handler installed for " ++ C.abilityName a ++ ".") <> D.hardline <>
        line ("pub fn perform_" ++ bridgeName a op ++ "(ctx: &mut ls::Context, arguments: Vec<ls::Value>) -> ls::Result<ls::Value> ") <>
        D.block 4 (D.joinWith D.hardline
          ([ line "let schema = crate::lawspec_schema::schema()?;"
           , line ("let handler = ctx.handler::<std::sync::Arc<dyn " ++ interfaceName a ++ ">>(" ++ show (C.abilityKey (C.abilityInstance a)) ++ ")?;") ] ++
           zipWith decode [0 :: Int ..] (zip types refs) ++
           [ line ("let native_result = handler." ++ op ++ "(" ++ intercalate ", " ["native_" ++ show n | n <- [0 .. length args - 1]] ++ ");")
           , if result == C.scalarType "Unit" then line "Ok(ls::Value::Unit)" else line "Ok(ls::IntoValue::into_value(native_result))" ])))) (C.abilityOperations a)

-- The user-owned production handler of each ability, in the unit's adapter
-- module: <Ability>Handler::default() is what the tests use.
productionStub :: [C.DataDeclaration] -> C.Unit -> C.Ability -> Either String D.Doc
productionStub datas u a = do
  methods <- mapM (\(op, ty) -> do
    let (args, result) = C.functionType ty
    types <- mapM (Native.rustDataType datas) args
    resultType <- Native.rustDataType datas result
    pure (D.text ("fn " ++ op ++ "(&self" ++ concat [", value" ++ show i ++ ": " ++ t | (i, t) <- zip [0 :: Int ..] types] ++ ") -> " ++ resultType ++ " ") <>
      D.block 4 (D.text ("todo!(" ++ show op ++ ")")))) (C.abilityOperations a)
  pure (D.text ("/// The native handler of " ++ displayName a ++ ": " ++ intercalate ", " (map fst (C.abilityOperations a)) ++ ".") <> D.hardline <>
    D.text "#[derive(Default)]" <> D.hardline <>
    D.text ("pub struct " ++ productionName a ++ ";") <> D.hardline <> D.hardline <>
    D.text ("impl crate::lawspec_abilities::" ++ moduleOf u ++ "::" ++ interfaceName a ++ " for " ++ productionName a ++ " ") <>
    D.block 4 (D.joinWith (D.hardline <> D.hardline) methods))
