-- JavaScript and TypeScript pieces of a unit's abilities (see
-- LawSpec.AbilityNames): an interface per ability (TypeScript), a class per
-- spec handler and a recording class per ability, in
-- lawspec_abilities/<unit path>.mjs (or .ts). Handlers travel in the symbols
-- Map generated code passes to every definition, as in Python.
module LawSpec.AbilityEmit.Web (emit, modulePath, productionStub) where

import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.AbilityNames
import LawSpec.WebData (webDataTypeDoc, webTypeReferenceDoc)
import qualified LawSpec.WebDefinitions as Definitions
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.WebExpr as E

-- The generated module of a unit's abilities, from the project root.
modulePath :: Bool -> C.Unit -> String
modulePath ts u = "src/lawspec_abilities/" ++ map (\c -> if c == '.' then '/' else c) (C.idText (C.unitId u)) ++ (if ts then ".ts" else ".mjs")

emit :: Bool -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit ts minify bits datas units = mapM unitModule (filter unitAbilityPieces units)
  where
    layout = D.selectLayout minify (D.Pretty 80)
    calls = Definitions.definitionCalls units
    width = D.text (show bits)
    extension = if ts then "js" else "mjs"
    annotation ty = if ts then D.text ": " <> ty else mempty
    schemaCall name ty value = do
      ref <- webTypeReferenceDoc ty
      pure (E.call ("_lawspec_schema." ++ name) [ref, value, width, D.text "symbols"])
    unitModule u = do
      let depth = 1 + length (filter (== '.') (C.idText (C.unitId u)))
          root = concat (replicate depth "../")
      interfaces <- if ts then mapM interface (C.unitAbilities u) else pure []
      handlers <- mapM (specHandler u) (C.unitHandlers u)
      recordings <- mapM recording (C.unitAbilities u)
      let header = D.joinWith D.hardline (map D.text (
            [ "// @ts-nocheck" | ts ] ++
            [ "// Generated by LawSpec. Do not edit."
            , "// The abilities of " ++ C.idText (C.unitId u) ++ ": " ++ (if ts then "an interface for each, " else "") ++
              "its spec handlers, and a recording of any handler of it."
            , "import * as data from '" ++ root ++ "lawspec_data." ++ extension ++ "';"
            , "import * as ls from '" ++ root ++ "lawspec_runtime." ++ extension ++ "';"
            , "import * as schema from '" ++ root ++ "lawspec_schema." ++ extension ++ "';" ] ++
            [ "import * as _definitions from '" ++ root ++ "lawspec_definition_bodies." ++ extension ++ "';" | not (null (C.unitHandlers u)) ] ++
            [ "", "const _lawspec_schema = data.makeSchema();" ]))
          body = D.joinWith (D.hardline <> D.hardline) (interfaces ++ handlers ++ recordings)
      pure (Artifact (modulePath ts u) (D.render layout (header <> D.hardline <> D.hardline <> body <> D.hardline)) "generated" "source")
    signature ty = do
      let (args, result) = C.functionType ty
      types <- mapM (webDataTypeDoc datas) args
      resultType <- if result == C.scalarType "Unit" then pure (D.text "void") else webDataTypeDoc datas result
      pure (D.delimitTrailing 4 "(" ")" [D.text ("value" ++ show i) <> annotation t | (i, t) <- zip [0 :: Int ..] types] <>
        annotation resultType)
    interface a = do
      methods <- mapM (\(op, ty) -> (\s -> D.text op <> s <> D.text ";") <$> signature ty) (C.abilityOperations a)
      pure (D.text ("/** The " ++ C.abilityName a ++ " ability: a handler answers each of its operations. */") <> D.hardline <>
        D.text ("export interface " ++ interfaceName a ++ " ") <> D.block 2 (D.joinWith D.hardline methods))
    specHandler u h = do
      ability <- maybe (Left ("unknown ability of handler " ++ C.handlerName h)) Right
        (lookup (C.abilityRefId (C.handlerAbility h)) [(C.abilityId a, a) | a <- C.unitAbilities u])
      initialState <- case C.handlerState h of
        Nothing -> pure []
        Just (_, start) -> do
          value <- E.renderExpression ts datas bits (const "_unbound") (\_ _ -> Left "a handler's start value calls nothing") start
          pure [D.text "this._state = " <> value <> D.text ";"]
      methods <- mapM (\(op, ty) -> do
        clause <- maybe (Left (C.handlerName h ++ ": no clause for " ++ op)) Right (lookup op (C.handlerClauses h))
        evaluate <- maybe (Left ("unresolved clause " ++ C.idText clause)) Right (lookup clause calls)
        s <- signature ty
        let (args, result) = C.functionType ty
        inputs <- sequence [schemaCall "fromNative" t (D.text ("value" ++ show i)) | (i, t) <- zip [0 :: Int ..] args]
        let arguments = D.text "symbols" : [D.text "this._state" | Just _ <- [C.handlerState h]] ++
              (if null args && C.handlerState h == Nothing then [E.call "ls.literal" [D.text "{type: 'Unit'}", D.text "symbols"]] else inputs)
            invocation = E.call (Definitions.plainCall evaluate) arguments
        output <- schemaCall "toNative" result (D.text "result")
        let statements = case C.handlerState h of
              Nothing -> [D.text "const result = " <> invocation <> D.text ";"]
              Just _ -> [D.text "const pair = " <> invocation <> D.text ";", D.text "this._state = pair.fields[1];", D.text "const result = pair.fields[0];"]
        pure (D.text op <> s <> D.text " " <> D.block 2
          (D.joinWith D.hardline (D.text "const symbols = this._symbols;" : statements ++ [D.text "return " <> output <> D.text ";"])))) (C.abilityOperations ability)
      pure (D.text ("/** The spec handler " ++ C.handlerName h ++ " for " ++ C.abilityName ability ++ ". */") <> D.hardline <>
        D.text ("export class " ++ specName h ++ (if ts then " implements " ++ interfaceName ability else "") ++ " ") <> D.block 2 (D.joinWith D.hardline (
          D.text "constructor(symbols = new Map()) " <> D.block 2 (D.joinWith D.hardline (D.text "this._symbols = symbols;" : initialState)) :
          methods)))
    recording a = do
      methods <- mapM (\(op, ty) -> do
        s <- signature ty
        let (args, _) = C.functionType ty
        logged <- sequence [schemaCall "fromNative" t (D.text ("value" ++ show i)) | (i, t) <- zip [0 :: Int ..] args]
        let values = [D.text ("value" ++ show i) | i <- [0 .. length args - 1]]
        pure (D.text op <> s <> D.text " " <> D.block 2 (D.joinWith D.hardline
          [ D.text "const symbols = this._symbols;"
          , D.text "this.calls.push(" <> E.array [E.quoted op, E.array logged] <> D.text ");"
          , D.text "return this.inner." <> E.call op values <> D.text ";" ]))) (C.abilityOperations a)
      pure (D.text ("/** Records each call to a " ++ C.abilityName a ++ " handler, then passes it on. */") <> D.hardline <>
        D.text ("export class " ++ recordingName a ++ (if ts then " implements " ++ interfaceName a else "") ++ " ") <> D.block 2 (D.joinWith D.hardline (
          D.text "constructor(inner, symbols = new Map()) " <> D.block 2 (D.joinWith D.hardline (map D.text
            [ "this.inner = inner;", "this.calls = [];", "this._symbols = symbols;" ])) :
          methods)))

-- The user-owned production handler of each ability, in the unit's adapter
-- module.
productionStub :: Bool -> [C.DataDeclaration] -> C.Ability -> Either String String
productionStub ts datas a = do
  methods <- mapM (\(op, ty) -> do
    let (args, result) = C.functionType ty
    types <- mapM (webDataTypeDoc datas) args
    resultType <- if result == C.scalarType "Unit" then pure (D.text "void") else webDataTypeDoc datas result
    pure (D.text op <> D.delimitTrailing 4 "(" ")" [D.text ("value" ++ show i) <> (if ts then D.text ": " <> t else mempty) | (i, t) <- zip [0 :: Int ..] types] <>
      (if ts then D.text ": " <> resultType else mempty) <> D.text " " <>
      D.block 2 (D.text "throw " <> E.call "new Error" [E.quoted op] <> D.text ";"))) (C.abilityOperations a)
  pure (D.render (D.Pretty 80) (D.text ("/** The native handler of " ++ C.abilityName a ++ ": " ++ intercalate ", " (map fst (C.abilityOperations a)) ++ ". */") <> D.hardline <>
    D.text ("export class " ++ productionName a ++ (if ts then " implements abilities." ++ interfaceName a else "") ++ " ") <> D.block 2 (D.joinWith D.hardline methods)) ++ "\n")
