// Generated by LawSpec. Do not edit.
// Known-answer tests of lawspec.crypto's default handlers, against NIST's
// vectors (see docs/reference/language/cryptography.md for the sources).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { ml_kem768 } from '@noble/post-quantum/ml-kem.js';
import { ml_dsa65 } from '@noble/post-quantum/ml-dsa.js';
import * as crypto from '../src/lawspec/crypto.js';

const vectorText = String.raw`@@VECTORS@@`;

function vectors(kind: string): string[][] {
  const found = vectorText.split('\n').map((line) => line.trim().split(/\s+/))
    .filter((fields) => fields[0] === kind).map((fields) => fields.slice(1).map((f) => (f === '-' ? '' : f)));
  assert.ok(found.length > 0, kind);
  return found;
}

const unhex = (text: string): Uint8Array => new Uint8Array(Buffer.from(text, 'hex'));
const hex = (data: Uint8Array): string => Buffer.from(data).toString('hex');
const sha3 = (data: Uint8Array): string => createHash('sha3-256').update(data).digest('hex');
const flipped = (data: Uint8Array): Uint8Array => { const copy = new Uint8Array(data); copy[0] ^= 1; return copy; };

test('SHA3-256', () => {
  for (const [message, digest] of vectors('sha3-256')) assert.equal(hex(crypto.sha3_256(unhex(message))), digest);
});

test('SHAKE256', () => {
  for (const [message, length, output] of vectors('shake256')) assert.equal(hex(crypto.shake256(unhex(message), Number(length))), output);
});

test('AES-256-GCM', () => {
  for (const [key, iv, plaintext, associated, ciphertext, tag] of vectors('aes-256-gcm')) {
    const sealed = crypto.aes256GcmEncrypt(unhex(key), unhex(iv), unhex(plaintext), unhex(associated));
    assert.equal(hex(sealed), ciphertext + tag);
    assert.equal(hex(crypto.aes256GcmDecrypt(unhex(key), unhex(iv), sealed, unhex(associated)) ?? new Uint8Array([1])), plaintext);
    assert.equal(crypto.aes256GcmDecrypt(unhex(key), unhex(iv), flipped(sealed), unhex(associated)), undefined);
  }
});

test('ML-KEM-768 key generation', () => {
  for (const [d, z, publicDigest, secretDigest] of vectors('mlkem768-keygen')) {
    const { publicKey, secretKey } = ml_kem768.keygen(unhex(d + z));
    assert.equal(sha3(publicKey), publicDigest);
    assert.equal(sha3(secretKey), secretDigest);
    assert.equal(hex(crypto.mlKem768KeyPairFromSeed(unhex(d + z)).publicKey), hex(publicKey));
  }
});

test('ML-KEM-768 encapsulation', () => {
  for (const [publicKey, message, ciphertext, secret] of vectors('mlkem768-encaps')) {
    const made = crypto.mlKem768Encapsulate(unhex(publicKey), unhex(message));
    assert.equal(hex(made.ciphertext), ciphertext);
    assert.equal(hex(made.secret), secret);
  }
});

test('ML-KEM-768 decapsulation', () => {
  for (const [secretKey, ciphertext, secret] of vectors('mlkem768-decaps')) {
    assert.equal(hex(crypto.mlKem768DecapsulateExpanded(unhex(secretKey), unhex(ciphertext))), secret);
  }
  for (const [seed, ciphertext, secret] of vectors('mlkem768-decaps-seed')) {
    assert.equal(hex(crypto.mlKem768Decapsulate(unhex(seed), unhex(ciphertext))), secret);
  }
});

test('ML-DSA-65 key generation', () => {
  for (const [seed, publicDigest, secretDigest] of vectors('mldsa65-keygen')) {
    const { publicKey, secretKey } = ml_dsa65.keygen(unhex(seed));
    assert.equal(sha3(publicKey), publicDigest);
    assert.equal(sha3(secretKey), secretDigest);
    assert.equal(sha3(crypto.mlDsa65PublicKey(unhex(seed))), publicDigest);
  }
});

test('ML-DSA-65 verification', () => {
  for (const [publicKey, message, context, signature, passed] of vectors('mldsa65-verify')) {
    assert.equal(crypto.mlDsa65Verify(unhex(publicKey), unhex(message), unhex(signature), unhex(context)), passed === 'true');
  }
});

test('ML-DSA-65 deterministic signature', () => {
  for (const [seed, message, signature] of vectors('mldsa65-sign-seed')) {
    assert.equal(hex(crypto.mlDsa65Sign(unhex(seed), unhex(message), new Uint8Array(0), true)), signature);
    const publicKey = crypto.mlDsa65PublicKey(unhex(seed));
    assert.ok(crypto.mlDsa65Verify(publicKey, unhex(message), unhex(signature)));
    assert.ok(!crypto.mlDsa65Verify(publicKey, flipped(unhex(message)), unhex(signature)));
  }
});

test('SLH-DSA-SHAKE-128f key generation', () => {
  for (const [skSeed, skPrf, pkSeed, publicKey, secretDigest] of vectors('slhdsa128f-keygen')) {
    const made = crypto.slhDsaKeyPair(unhex(skSeed), unhex(skPrf), unhex(pkSeed));
    assert.equal(hex(made.publicKey), publicKey);
    assert.equal(sha3(made.secretKey), secretDigest);
  }
});

test('SLH-DSA-SHAKE-128f verification', () => {
  for (const [publicKey, message, context, signature, passed] of vectors('slhdsa128f-verify')) {
    assert.equal(crypto.slhDsaVerify(unhex(publicKey), unhex(message), unhex(signature), unhex(context)), passed === 'true');
    assert.ok(!crypto.slhDsaVerify(unhex(publicKey), flipped(unhex(message)), unhex(signature), unhex(context)));
  }
});

test('SLH-DSA-SHAKE-128f round trip', () => {
  for (const [skSeed, skPrf, pkSeed] of vectors('slhdsa128f-keygen')) {
    const { publicKey, secretKey } = crypto.slhDsaKeyPair(unhex(skSeed), unhex(skPrf), unhex(pkSeed));
    const message = new TextEncoder().encode('LawSpec');
    const signature = crypto.slhDsaSign(secretKey, message);
    assert.ok(crypto.slhDsaVerify(publicKey, message, signature));
    assert.ok(!crypto.slhDsaVerify(publicKey, flipped(message), signature));
  }
});
