// Generated by LawSpec. Do not edit.
package lawspec

/** The default handler of lawspec.concurrent's Async: threads. A pause yields this thread. */
object Concurrent {
    /** Native concurrency: pause lets other threads run. */
    class AsyncHandler : lawspec.abilities.lawspec.Concurrent.Async {
        override fun pause() {
            Thread.yield()
        }
    }
}
