// Generated by LawSpec. Do not edit.
package lawspec

import io.kotest.core.spec.style.StringSpec

/**
 * Known-answer tests of lawspec.crypto's default handlers, against NIST's
 * vectors (see docs/reference/language/cryptography.md for the sources).
 */
class CryptoVectorsTest : StringSpec({
    val lines = arrayOf(
@@VECTOR_LINES@@
    )

    fun vectors(kind: String): List<List<String>> {
        val found = lines.map { it.trim().split(Regex("\\s+")) }
            .filter { it.first() == kind }
            .map { fields -> fields.drop(1).map { if (it == "-") "" else it } }
        check(found.isNotEmpty()) { kind }
        return found
    }

    fun unhex(text: String): ByteArray = java.util.HexFormat.of().parseHex(text)
    fun hex(data: ByteArray): String = java.util.HexFormat.of().formatHex(data)
    fun sha3(data: ByteArray): String = hex(Crypto.sha3_256(data))
    fun flipped(data: ByteArray): ByteArray = data.copyOf().also { it[0] = (it[0].toInt() xor 1).toByte() }
    fun expect(condition: Boolean, what: String) = check(condition) { what }

    "SHA3-256" {
        for (v in vectors("sha3-256")) expect(hex(Crypto.sha3_256(unhex(v[0]))) == v[1], "SHA3-256 ${v[0]}")
    }

    "SHAKE256" {
        for (v in vectors("shake256")) expect(hex(Crypto.shake256(unhex(v[0]), v[1].toInt())) == v[2], "SHAKE256 ${v[0]}")
    }

    "AES-256-GCM" {
        for (v in vectors("aes-256-gcm")) {
            val sealed = Crypto.aes256GcmEncrypt(unhex(v[0]), unhex(v[1]), unhex(v[2]), unhex(v[3]))
            expect(hex(sealed) == v[4] + v[5], "AES-256-GCM encryption")
            expect(Crypto.aes256GcmDecrypt(unhex(v[0]), unhex(v[1]), sealed, unhex(v[3]))?.let(::hex) == v[2], "AES-256-GCM decryption")
            expect(Crypto.aes256GcmDecrypt(unhex(v[0]), unhex(v[1]), flipped(sealed), unhex(v[3])) == null, "AES-256-GCM tampering")
        }
    }

    "ML-KEM-768 key generation" {
        for (v in vectors("mlkem768-keygen")) expect(sha3(Crypto.mlKem768PublicKey(unhex(v[0] + v[1]))) == v[2], "ML-KEM-768 key")
    }

    "ML-KEM-768 encapsulation" {
        for (v in vectors("mlkem768-encaps")) {
            val (ciphertext, secret) = Crypto.mlKem768Encapsulate(unhex(v[0]), Crypto.Seeded(unhex(v[1])))
            expect(hex(ciphertext) == v[2] && hex(secret) == v[3], "ML-KEM-768 encapsulation")
        }
    }

    "ML-KEM-768 decapsulation" {
        for (v in vectors("mlkem768-decaps")) {
            // A PKCS#8 key holding the expanded decapsulation key.
            val key = unhex(v[0])
            val body = unhex("020100300b06096086480165030404020482" + "%04x".format(key.size + 4) + "0482" + "%04x".format(key.size)) + key
            val pkcs8 = unhex("3082" + "%04x".format(body.size)) + body
            val privateKey = java.security.KeyFactory.getInstance("ML-KEM").generatePrivate(java.security.spec.PKCS8EncodedKeySpec(pkcs8))
            expect(hex(Crypto.mlKem768Decapsulate(privateKey, unhex(v[1]))) == v[2], "ML-KEM-768 decapsulation")
        }
        for (v in vectors("mlkem768-decaps-seed")) {
            expect(hex(Crypto.mlKem768Decapsulate(unhex(v[0]), unhex(v[1]))) == v[2], "ML-KEM-768 decapsulation from a seed")
        }
    }

    "ML-DSA-65 key generation" {
        for (v in vectors("mldsa65-keygen")) expect(sha3(Crypto.mlDsa65PublicKey(unhex(v[0]))) == v[1], "ML-DSA-65 key")
    }

    // The JDK's ML-DSA takes no context strings, so only the vectors with an
    // empty context apply to it.
    "ML-DSA-65 verification" {
        for (v in vectors("mldsa65-verify")) {
            if (v[2].isEmpty()) expect(Crypto.mlDsa65Verify(unhex(v[0]), unhex(v[1]), unhex(v[3])) == (v[4] == "true"), "ML-DSA-65 verification")
        }
    }

    "ML-DSA-65 deterministic signature" {
        for (v in vectors("mldsa65-sign-seed")) {
            expect(hex(Crypto.mlDsa65Sign(unhex(v[0]), unhex(v[1]), true)) == v[2], "ML-DSA-65 deterministic signature")
            val publicKey = Crypto.mlDsa65PublicKey(unhex(v[0]))
            expect(Crypto.mlDsa65Verify(publicKey, unhex(v[1]), unhex(v[2])), "ML-DSA-65 verifies its signature")
            expect(!Crypto.mlDsa65Verify(publicKey, flipped(unhex(v[1])), unhex(v[2])), "ML-DSA-65 rejects a changed message")
        }
    }

    "SLH-DSA-SHAKE-128f key generation" {
        for (v in vectors("slhdsa128f-keygen")) {
            val (publicKey, secretKey) = Crypto.slhDsaKeyPair(unhex(v[0]), unhex(v[1]), unhex(v[2]))
            expect(hex(publicKey) == v[3] && sha3(secretKey) == v[4], "SLH-DSA key generation")
        }
    }

    "SLH-DSA-SHAKE-128f verification" {
        for (v in vectors("slhdsa128f-verify")) {
            expect(Crypto.slhDsaVerify(unhex(v[0]), unhex(v[1]), unhex(v[3]), unhex(v[2])) == (v[4] == "true"), "SLH-DSA verification")
            expect(!Crypto.slhDsaVerify(unhex(v[0]), flipped(unhex(v[1])), unhex(v[3]), unhex(v[2])), "SLH-DSA rejects a changed message")
        }
    }

    "SLH-DSA-SHAKE-128f round trip" {
        for (v in vectors("slhdsa128f-keygen")) {
            val (publicKey, secretKey) = Crypto.slhDsaKeyPair(unhex(v[0]), unhex(v[1]), unhex(v[2]))
            val message = "LawSpec".toByteArray()
            val signature = Crypto.slhDsaSign(secretKey, message, ByteArray(0))
            expect(Crypto.slhDsaVerify(publicKey, message, signature, ByteArray(0)), "SLH-DSA round trip")
            expect(!Crypto.slhDsaVerify(publicKey, flipped(message), signature, ByteArray(0)), "SLH-DSA rejects a changed message")
        }
    }
})
