// Generated by LawSpec. Do not edit.
package lawspec

/**
 * The default handlers of lawspec.randomness. Random is the generator of
 * `seeded random n` (a 64-bit linear congruential generator, the same on
 * every target), started at the run's seed: LAWSPEC_SEED, or 0. SecureRandom
 * is the operating system's cryptographically secure generator.
 */
object Randomness {
    fun randomStep(state: Long): Long = 6364136223846793005L * state + 1442695040888963407L

    /** A draw from 0 up to bound, as lawspec.randomness's randomDraw makes it. */
    fun randomDraw(state: Long, bound: Long): Long {
        if (bound < 1) return 0
        val first = randomStep(state)
        val bits = ((first ushr 32) shl 32) + (randomStep(first) ushr 32)
        return java.lang.Long.remainderUnsigned(bits, bound)
    }

    fun runSeed(): Long {
        val value = java.lang.System.getenv("LAWSPEC_SEED")
        return if (value.isNullOrEmpty()) 0L else java.math.BigInteger(value).toLong()
    }

    /** Reproducible draws from the run's seed. */
    class RandomHandler : lawspec.abilities.lawspec.Randomness.Random {
        private var state = runSeed()

        override fun randomBelow(value0: kotlin.Long): kotlin.Long {
            val current = state
            state = randomStep(randomStep(current))
            return randomDraw(current, value0)
        }
    }

    private val secure = java.security.SecureRandom()

    /** The operating system's generator (java.security.SecureRandom). */
    class SecureRandomHandler : lawspec.abilities.lawspec.Randomness.SecureRandom {
        override fun secureBytes(value0: kotlin.Int): kotlin.ByteArray =
            ByteArray(maxOf(value0, 0)).also { secure.nextBytes(it) }

        override fun secureBelow(value0: kotlin.Long): kotlin.Long =
            if (value0 < 1) 0L else secure.nextLong(value0)

        override fun secureToken(): kotlin.String =
            java.util.HexFormat.of().formatHex(ByteArray(32).also { secure.nextBytes(it) })
    }
}
