// Generated by LawSpec. Do not edit.
//go:build go1.26

// The ACVP encapsulation vectors, through crypto/mlkem/mlkemtest (Go 1.26).
package @@PACKAGE@@

import (
	"crypto/mlkem"
	"crypto/mlkem/mlkemtest"
	"encoding/hex"
	"testing"
)

func TestMlKem768EncapsulationVectors(t *testing.T) {
	for _, v := range lsVectors(t, "mlkem768-encaps") {
		key, err := mlkem.NewEncapsulationKey768(lsUnhex(t, v[0]))
		if err != nil {
			t.Fatal(err)
		}
		secret, ciphertext, err := mlkemtest.Encapsulate768(key, lsUnhex(t, v[1]))
		if err != nil {
			t.Fatal(err)
		}
		if hex.EncodeToString(ciphertext) != v[2] || hex.EncodeToString(secret) != v[3] {
			t.Errorf("ML-KEM-768 encapsulation differs")
		}
	}
}
