// Generated by LawSpec. Do not edit.
// The default handlers of lawspec.randomness. Random is the generator of
// `seeded random n` (a 64-bit linear congruential generator, the same on
// every target), started at the run's seed: LAWSPEC_SEED, or 0. SecureRandom
// is the operating system's cryptographically secure generator.
package @@PACKAGE@@

import (
	cryptorand "crypto/rand"
	"encoding/hex"
	"math/big"
	"os"
	"strconv"
)

func lsRandomStep(state uint64) uint64 {
	return 6364136223846793005*state + 1442695040888963407
}

// lsRandomDraw is a draw from 0 up to bound, as lawspec.randomness's randomDraw
// makes it.
func lsRandomDraw(state uint64, bound int64) int64 {
	if bound < 1 {
		return 0
	}
	first := lsRandomStep(state)
	bits := (first>>32)<<32 + lsRandomStep(first)>>32
	return int64(bits % uint64(bound))
}

func lsRunSeed() uint64 {
	if value := os.Getenv("LAWSPEC_SEED"); value != "" {
		if seed, err := strconv.ParseInt(value, 10, 64); err == nil {
			return uint64(seed)
		}
		if seed, err := strconv.ParseUint(value, 10, 64); err == nil {
			return seed
		}
	}
	return 0
}

// RandomHandler gives reproducible draws from the run's seed.
type RandomHandler struct {
	state uint64
}

// NewRandomHandler makes the default Random handler.
func NewRandomHandler() Random {
	return &RandomHandler{state: lsRunSeed()}
}

func (handler *RandomHandler) RandomBelow(value0 int64) int64 {
	state := handler.state
	handler.state = lsRandomStep(lsRandomStep(state))
	return lsRandomDraw(state, value0)
}

// SecureRandomHandler is the operating system's generator (crypto/rand).
type SecureRandomHandler struct{}

// NewSecureRandomHandler makes the default SecureRandom handler.
func NewSecureRandomHandler() SecureRandom {
	return &SecureRandomHandler{}
}

func (handler *SecureRandomHandler) SecureBytes(value0 int32) []byte {
	if value0 < 0 {
		value0 = 0
	}
	out := make([]byte, value0)
	if _, err := cryptorand.Read(out); err != nil {
		panic(err)
	}
	return out
}

func (handler *SecureRandomHandler) SecureBelow(value0 int64) int64 {
	if value0 < 1 {
		return 0
	}
	n, err := cryptorand.Int(cryptorand.Reader, big.NewInt(value0))
	if err != nil {
		panic(err)
	}
	return n.Int64()
}

func (handler *SecureRandomHandler) SecureToken() string {
	var raw [32]byte
	if _, err := cryptorand.Read(raw[:]); err != nil {
		panic(err)
	}
	return hex.EncodeToString(raw[:])
}

