// Generated by LawSpec. Do not edit.
// The default handler of lawspec.time's Clock: the system clock, kept from
// going back by Go's monotonic clock. An Instant is microseconds since
// 1970-01-01T00:00:00Z.
package @@PACKAGE@@

import "time"

var lsClockStart = time.Now()

// lsNowMicros is the wall clock at start, moved on by the monotonic clock.
func lsNowMicros() int64 {
	return lsClockStart.UnixMicro() + time.Since(lsClockStart).Microseconds()
}

// ClockHandler is the system clock: now never goes back; sleep blocks the
// calling goroutine.
type ClockHandler struct{}

// NewClockHandler makes the default Clock handler.
func NewClockHandler() Clock {
	return &ClockHandler{}
}

func (handler *ClockHandler) Now() @@Instant@@ {
	return @@Instant@@{Value: lsNowMicros()}
}

func (handler *ClockHandler) Sleep(value0 LawSpecDuration) {
	target := lsNowMicros() + time.Duration(value0).Microseconds()
	for left := target - lsNowMicros(); left > 0; left = target - lsNowMicros() {
		time.Sleep(time.Duration(left) * time.Microsecond)
	}
}

// LawSpecRegisterClock lets the runtime read any Clock handler (this one, the
// virtual clock, a recording): workflows and mailboxes then wait on the
// clock a law installs. Only this handler is real time.
func LawSpecRegisterClock() {
	LawSpecRegisterClockAbility(
		func(handler any) int64 { return handler.(Clock).Now().Value },
		func(handler any, micros int64) { handler.(Clock).Sleep(LawSpecDuration(micros) * time.Microsecond) },
		func(handler any) bool {
			_, isDefault := handler.(*ClockHandler)
			return isDefault
		})
}
