// Generated by LawSpec. Do not edit.
// The default handler of lawspec.time's Clock: the system clock, kept from
// going back by Go's monotonic clock. An Instant is microseconds since
// 1970-01-01T00:00:00Z.
package @@PACKAGE@@

import "time"

var lsClockStart = time.Now()

// lsNowMicros is the wall clock at start, moved on by the monotonic clock.
func lsNowMicros() int64 {
	return lsClockStart.UnixMicro() + time.Since(lsClockStart).Microseconds()
}

// ClockHandler is the system clock: now never goes back; sleep blocks the
// calling goroutine.
type ClockHandler struct{}

// NewClockHandler makes the default Clock handler.
func NewClockHandler() Clock {
	return &ClockHandler{}
}

// LawSpecRealTime says this clock is real time: workflows time out in real
// time under it (the runtime's lsWorkflowRuntime), and a mailbox's receive
// within waits in real time.
func (handler *ClockHandler) LawSpecRealTime() bool { return true }

func (handler *ClockHandler) Now() @@Instant@@ {
	return @@Instant@@{Value: lsNowMicros()}
}

func (handler *ClockHandler) Sleep(value0 LawSpecDuration) {
	target := lsNowMicros() + time.Duration(value0).Microseconds()
	for left := target - lsNowMicros(); left > 0; left = target - lsNowMicros() {
		time.Sleep(time.Duration(left) * time.Microsecond)
	}
}
