"""Writes runtime/defaults/vectors.txt: a small subset of NIST's known-answer
vectors for the default crypto handlers (see docs/reference/language/
cryptography.md). Every target's generated vector test reads it.

    python3 dev/crypto-vectors.py [ACVP-Server checkout or download dir] [gcm dir]

Sources:
  * NIST ACVP-Server, gen-val/json-files (internalProjection.json):
    SHA3-256-2.0, SHAKE-256-1.0, ML-KEM-keyGen-FIPS203,
    ML-KEM-encapDecap-FIPS203, ML-DSA-keyGen-FIPS204, ML-DSA-sigVer-FIPS204,
    SLH-DSA-keyGen-FIPS205, SLH-DSA-sigVer-FIPS205.
    https://github.com/usnistgov/ACVP-Server
  * NIST CAVP GCM vectors, gcmEncryptExtIV256.rsp (gcmtestvectors.zip).
    https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program
  * Derived vectors (marked so): a key from an ACVP keyGen seed, then a
    deterministic encapsulation or signature computed with @noble/post-quantum
    0.7.1 and checked against Haskell's mlkem 0.2.3.0 and mldsa 0.1.1.0; they
    cover libraries that take keys only as seeds, and sign with an empty
    context.
"""
import json
import os
import sys
import hashlib
import urllib.request

ACVP = "https://raw.githubusercontent.com/usnistgov/ACVP-Server/master/gen-val/json-files"


def load(base, name):
    path = os.path.join(base, name, "internalProjection.json")
    if os.path.exists(path):
        return json.load(open(path))
    with urllib.request.urlopen(f"{ACVP}/{name}/internalProjection.json") as response:
        return json.load(response)


def h(s):
    return s.lower() if s else "-"


def sha3(s):
    return hashlib.sha3_256(bytes.fromhex(s)).hexdigest()


def tests(doc, **want):
    for g in doc["testGroups"]:
        if all(g.get(k) == v for k, v in want.items()):
            for t in g["tests"]:
                yield g, t


def by_id(doc, ids, **want):
    found = {t["tcId"]: (g, t) for g, t in tests(doc, **want)}
    return [found[i] for i in ids]


def main():
    base = sys.argv[1] if len(sys.argv) > 1 else "/tmp/acvp"
    gcm = sys.argv[2] if len(sys.argv) > 2 else os.path.join(base, "gcm")
    out = []
    say = out.append
    say("# Known-answer vectors for LawSpec's default crypto handlers.")
    say("# Generated by dev/crypto-vectors.py; see its header for the sources.")
    say("# One vector per line: a kind, then its fields; hex is lowercase, - is empty.")

    say("# SHA3-256 (FIPS 202): ACVP SHA3-256-2.0, AFT tcId 87, 19, 70")
    doc = load(base, "SHA3-256-2.0")
    for _, t in by_id(doc, [87, 19, 70], testType="AFT"):
        assert t["len"] % 8 == 0
        say(f"sha3-256 {h(t['msg'])} {h(t['md'])}")

    say("# SHAKE256 (FIPS 202): ACVP SHAKE-256-1.0, AFT tcId 8, 16 and VOT tcId 1176")
    doc = load(base, "SHAKE-256-1.0")
    for _, t in by_id(doc, [8, 16], testType="AFT") + by_id(doc, [1176], testType="VOT"):
        assert t["len"] % 8 == 0 and t["outLen"] % 8 == 0
        say(f"shake256 {h(t['msg'])} {t['outLen'] // 8} {h(t['md'])}")

    say("# AES-256-GCM (SP 800-38D): CAVP gcmEncryptExtIV256.rsp, 96-bit IV, 128-bit tag")
    records, current, header = [], {}, {}
    for line in open(os.path.join(gcm, "gcmEncryptExtIV256.rsp")):
        line = line.strip()
        if line.startswith("[") and "=" in line:
            k, v = line[1:-1].split(" = ")
            header[k] = int(v)
        elif " = " in line or line.endswith("="):
            k, _, v = line.partition(" =")
            current[k.strip()] = v.strip()
            if k.strip() == "Tag":
                records.append((dict(header), current))
                current = {}
    wanted = [(0, 0), (128, 128), (408, 160)]
    for pt, aad in wanted:
        header, r = next((hd, r) for hd, r in records
                         if hd["IVlen"] == 96 and hd["Taglen"] == 128 and hd["PTlen"] == pt and hd["AADlen"] == aad)
        say(f"aes-256-gcm {h(r['Key'])} {h(r['IV'])} {h(r['PT'])} {h(r['AAD'])} {h(r['CT'])} {h(r['Tag'])}")

    say("# ML-KEM-768 (FIPS 203): ACVP ML-KEM-keyGen-FIPS203 tcId 26, 27 (SHA3-256 of ek and dk)")
    doc = load(base, "ML-KEM-keyGen-FIPS203")
    for _, t in by_id(doc, [26, 27], parameterSet="ML-KEM-768"):
        say(f"mlkem768-keygen {h(t['d'])} {h(t['z'])} {sha3(t['ek'])} {sha3(t['dk'])}")
    doc = load(base, "ML-KEM-encapDecap-FIPS203")
    say("# ML-KEM-768 encapsulation: ACVP ML-KEM-encapDecap-FIPS203 tcId 26")
    for _, t in by_id(doc, [26], parameterSet="ML-KEM-768", function="encapsulation"):
        say(f"mlkem768-encaps {h(t['ek'])} {h(t['m'])} {h(t['c'])} {h(t['k'])}")
    say("# ML-KEM-768 decapsulation, expanded key: ACVP ML-KEM-encapDecap-FIPS203 tcId 86")
    for _, t in by_id(doc, [86], parameterSet="ML-KEM-768", function="decapsulation"):
        say(f"mlkem768-decaps {h(t['dk'])} {h(t['c'])} {h(t['k'])}")
    say("# ML-KEM-768 decapsulation, key as its seed (derived): the key of keyGen tcId 26, m = 00..1f,")
    say("# then the same ciphertext with its first bit flipped (implicit rejection)")
    derived = json.load(open(os.path.join(base, "derived-kem.json")))
    say(f"mlkem768-decaps-seed {derived['seed']} {derived['c']} {derived['k']}")
    say(f"mlkem768-decaps-seed {derived['seed']} {derived['cBad']} {derived['kBad']}")

    say("# ML-DSA-65 (FIPS 204): ACVP ML-DSA-keyGen-FIPS204 tcId 26, 27 (SHA3-256 of pk and sk)")
    doc = load(base, "ML-DSA-keyGen-FIPS204")
    for _, t in by_id(doc, [26, 27], parameterSet="ML-DSA-65"):
        say(f"mldsa65-keygen {h(t['seed'])} {sha3(t['pk'])} {sha3(t['sk'])}")
    say("# ML-DSA-65 verification, external interface, pure: ACVP ML-DSA-sigVer-FIPS204 tcId 43, 38")
    doc = load(base, "ML-DSA-sigVer-FIPS204")
    for g, t in by_id(doc, [43, 38], parameterSet="ML-DSA-65", signatureInterface="external", preHash="pure"):
        pk = t.get("pk") or g.get("pk")
        say(f"mldsa65-verify {h(pk)} {h(t['message'])} {h(t.get('context'))} {h(t['signature'])} {str(t['testPassed']).lower()}")
    say("# ML-DSA-65 deterministic signature, empty context (derived): the key of keyGen tcId 26")
    derived = json.load(open(os.path.join(base, "derived-dsa.json")))
    say(f"mldsa65-sign-seed {derived['seed']} {derived['msg']} {derived['sig']}")

    say("# SLH-DSA-SHAKE-128f (FIPS 205): ACVP SLH-DSA-keyGen-FIPS205 (first SHAKE-128f vector)")
    doc = load(base, "SLH-DSA-keyGen-FIPS205")
    _, t = next(tests(doc, parameterSet="SLH-DSA-SHAKE-128f"))
    say(f"slhdsa128f-keygen {h(t['skSeed'])} {h(t['skPrf'])} {h(t['pkSeed'])} {h(t['pk'])} {sha3(t['sk'])}")
    say("# SLH-DSA-SHAKE-128f verification, external, pure: ACVP SLH-DSA-sigVer-FIPS205 tcId 92")
    say("# (the tests also check that the signature fails for the message with a bit flipped)")
    doc = load(base, "SLH-DSA-sigVer-FIPS205")
    for g, t in by_id(doc, [92], parameterSet="SLH-DSA-SHAKE-128f", signatureInterface="external", preHash="pure"):
        pk = t.get("pk") or g.get("pk")
        say(f"slhdsa128f-verify {h(pk)} {h(t['message'])} {h(t.get('context'))} {h(t['signature'])} {str(t['testPassed']).lower()}")

    path = os.path.join(os.path.dirname(__file__), "..", "runtime", "defaults", "vectors.txt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
