-- Generated by LawSpec. Do not edit.
-- | The default handler of lawspec.concurrent's Async: GHC's threads. A pause
-- yields this thread. It is the runtime's nativeAsync, which also starts and
-- waits for the tasks of workflows and async adapters.
module Lawspec.Concurrent where

import Prelude
import qualified Prelude as P
import qualified LawSpecRuntime as LS
import qualified LawSpecAbilities.Lawspec.Concurrent as Abilities

-- | Native concurrency: pause lets other threads run.
asyncHandler :: P.IO Abilities.Async
asyncHandler = P.pure Abilities.Async
  { Abilities.pause = LS.asyncPause LS.nativeAsync
  }
