-- Generated by LawSpec. Do not edit.
-- | The default handlers of lawspec.logging: lines on standard error, each
-- with its level. Laws that inspect what was logged use @recording Log@.
module Lawspec.Logging where

import Prelude
import qualified Prelude as P
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import qualified System.IO as IO
import qualified LawSpecData as Data
import qualified LawSpecAbilities.Lawspec.Logging as Abilities

levelName :: @@LogLevel@@ -> T.Text
levelName level = case level of
  @@LogLevel/Debug@@ -> T.pack "DEBUG"
  @@LogLevel/Info@@ -> T.pack "INFO"
  @@LogLevel/Warning@@ -> T.pack "WARNING"
  @@LogLevel/Error@@ -> T.pack "ERROR"

-- | Logs to standard error.
logHandler :: P.IO Abilities.Log
logHandler = P.pure Abilities.Log
  { Abilities.logMessage = \level message -> TIO.hPutStrLn IO.stderr (levelName level <> T.pack ": " <> message)
  }

-- | Trace events, at debug level.
traceHandler :: P.IO Abilities.Trace
traceHandler = P.pure Abilities.Trace
  { Abilities.traceEvent = \event -> TIO.hPutStrLn IO.stderr (T.pack "DEBUG: trace: " <> event)
  }
