-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- A protocol P has two ends, First and Second (the second sends what the
-- first receives). Each end has a struct type per step, named for the end
-- and what the step does (ServeFirstReceiveInt32), with the step number
-- appended when that name repeats on the same end, and a Done type after
-- the last step. Send and Receive return the next step's type, so Go's
-- compiler rejects steps out of order; the runtime's LawSpecEnd panics when
-- an end is used twice. A step sending another protocol Q carries Q's first
-- end at its start.
module LawSpec.Sessions.Go (emit) where

import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.GoData (goDataType, goCodec, requiresSchema)
import LawSpec.MachineSpec (describe)
import Control.Monad (foldM)
import Data.Char (isAlphaNum, toUpper)
import Data.List (intercalate)

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ bits datas units = mapM (unitSessions bits datas) [u | u <- units, not (null (C.unitSessions u))]

-- lawspec_sessions.go in the unit's package.
unitSessions :: Int -> [C.DataDeclaration] -> C.Unit -> Either String Artifact
unitSessions bits datas u = do
  bodies <- mapM (protocol datas sessions) sessions
  networked <- concat <$> mapM (\s -> maybe (pure []) (networkText bits datas sessions s) (lookup (C.sessionName s) wires)) sessions
  pure (Artifact (intercalate "/" parts ++ "/lawspec_sessions.go") (unlines (header ++ concat bodies ++ networked)) "generated" "source")
  where
    sessions = C.unitSessions u
    parts = splitOn '.' (C.idText (C.unitId u))
    -- A protocol whose steps have wire descriptors can also run between
    -- nodes: Listen and Dial. A step sending another protocol's end carries
    -- the address the receiver takes the end over from (or a relay's, for a
    -- local end), so that protocol must run between nodes too.
    wired (table, acc) s = case foldM step (table, []) (C.sessionSteps s) of
      Right (table', ds) | not (null (C.sessionSteps s)) -> (table', acc ++ [(C.sessionName s, ds)])
      _ -> (table, acc)
    step (t, ds) (sends, ty) = case delegated sessions ty of
      Just _ -> Right (t, ds ++ [(sends, "(end)", ty)])
      Nothing -> (\(d, t') -> (t', ds ++ [(sends, d, ty)])) <$> describe bits datas t ty
    (types, described) = foldl wired ([], []) sessions
    settle ws = let kept = [w | w@(_, ds) <- ws, all (\(_, _, t) -> maybe True ((`elem` map fst ws) . C.sessionName) (delegated sessions t)) ds]
                in if length kept == length ws then ws else settle kept
    wires = settle described
    schemaUsed = or [requiresSchema datas t | (_, ds) <- wires, (_, _, t) <- ds]
    header =
      [ "// Generated by LawSpec. Do not edit."
      , "package " ++ last parts
      , "" ] ++
      [ "import \"time\"\n" | not (null wires) ] ++
      [ "var lawSpecSessionTypes = LawSpecTypes(" ++ show (unwords (map snd (reverse types))) ++ ")\n" | not (null wires) ] ++
      [ "var lawSpecSessionSchema = lawSpecDataSchemaRegistry()\n" | schemaUsed ] ++
      [ ""
      , "// Typed channel ends for this unit's protocols. Each end's type names the"
      , "// step it is at; Send or Receive returns the end for the next step, so steps"
      , "// out of order do not compile. Each end is used once: using it again panics."
      , "// A receive whose other end gave up (Abandon, or its process failed) panics"
      , "// with LawSpecPeerFailed; TryReceive returns it as an error instead."
      ]

-- Listen<P> and Dial<P>: a protocol's two ends on two nodes, over the
-- network's reliable channel endpoints, values converted with the codecs.
networkText :: Int -> [C.DataDeclaration] -> [C.Session] -> C.Session -> [(Bool, String, C.Type)] -> Either String [String]
networkText bits datas sessions s steps = do
  toLogicals <- mapM (\(_, _, ty) -> conversion True ty) steps
  toNatives <- mapM (\(_, _, ty) -> conversion False ty) steps
  let p = sessionName s
      opener verb end flip side call =
        [ ""
        , "func " ++ verb ++ p ++ "(node *LawSpecNode, " ++ (if verb == "Listen" then "name" else "address") ++ " string) (" ++ endType s end 0 ++ ", error) {"
        , "\tsteps, toLogical, toNative := lawSpecWire" ++ p ++ "(node)" ] ++
        [ "\tsteps = lsFlipSteps(steps)" | flip ] ++
        [ "\tendpoint, err := " ++ call ++ ", steps, lawSpecSessionTypes, 5*time.Second)"
        , "\tif err != nil {"
        , "\t\treturn " ++ endType s end 0 ++ "{}, err"
        , "\t}"
        , "\treturn " ++ endType s end 0 ++ "{lsNetEnd(endpoint, " ++ show side ++ ", toLogical, toNative)}, nil"
        , "}" ]
  pure $
    [ ""
    , "// lawSpecWire" ++ p ++ " is protocol " ++ C.sessionName s ++ "'s steps and conversions on node,"
    , "// from its first end. An end sent to another node moves there (a local end"
    , "// stays and is relayed by node)."
    , "func lawSpecWire" ++ p ++ "(node *LawSpecNode) ([]LawSpecWireStep, []func(any) LawSpecValue, []func(LawSpecValue) any) {"
    , "\t_ = node"
    , "\treturn []LawSpecWireStep{" ++ intercalate ", " ["{" ++ (if sends' then "true" else "false") ++ ", LawSpecDescriptor(" ++ show d ++ ")}" | (sends', d, _) <- steps] ++ "},"
    , "\t\t[]func(any) LawSpecValue{" ++ intercalate ", " toLogicals ++ "},"
    , "\t\t[]func(LawSpecValue) any{" ++ intercalate ", " toNatives ++ "}"
    , "}"
    , ""
    , "// Listen" ++ p ++ " is the first end of a channel named name on node, which"
    , "// another node dials at <node address>/name." ] ++ drop 1 (opener "Listen" First False (0 :: Int) "node.Listen(name") ++
    [ ""
    , "// Dial" ++ p ++ " is the second end of the channel listening at address on"
    , "// another node." ] ++ drop 1 (opener "Dial" Second True 1 "node.Dial(address")
  where
    unit t = t == C.Constructor "Unit" []
    codec ty = replace "schema, bits" ("lawSpecSessionSchema, " ++ show bits) <$> goCodec datas ty
    conversion logical ty
      | Just q <- delegated sessions ty =
          let wrapper = endType q First 0
              wire = "lawSpecWire" ++ sessionName q ++ "(node)"
          in pure (if logical
               then "func(v any) LawSpecValue { s, l, n := " ++ wire ++ "; return LawSpecOfferEnd(node, v.(" ++ wrapper ++ ").end, s, l, n, lawSpecSessionTypes) }"
               else "func(v LawSpecValue) any { s, l, n := " ++ wire ++ "; return " ++ wrapper ++ "{LawSpecAcceptEnd(node, v, s, l, n, lawSpecSessionTypes)} }")
      | unit ty = pure (if logical then "func(v any) LawSpecValue { return v.(LawSpecValue) }" else "func(v LawSpecValue) any { return v }")
      | requiresSchema datas ty = do
          c <- codec ty
          native <- goDataType datas ty
          pure (if logical then "func(v any) LawSpecValue { return " ++ c ++ ".fromNative(v.(" ++ native ++ ")) }"
                else "func(v LawSpecValue) any { return " ++ c ++ ".toNative(v) }")
      | C.Constructor n [] <- ty = do
          native <- goDataType datas ty
          pure (if logical then "func(v any) LawSpecValue { return lsFromNative(" ++ show n ++ ", v.(" ++ native ++ "), " ++ show bits ++ ") }"
                else "func(v LawSpecValue) any { return lsToNative(" ++ show n ++ ", v, " ++ show bits ++ ").(" ++ native ++ ") }")
      | otherwise = Left "no Go conversion for this type"

replace :: String -> String -> String -> String
replace old new s = case s of
  [] -> []
  _ | take (length old) s == old -> new ++ replace old new (drop (length old) s)
  c : rest -> c : replace old new rest

data End = First | Second deriving (Eq, Show)

-- The type of a protocol's end before step k (0-based); its Done type after
-- the last step.
endType :: C.Session -> End -> Int -> String
endType s end k
  | k >= length steps = sessionName s ++ show end ++ "Done"
  | otherwise = stepNames s end !! k
  where steps = C.sessionSteps s

stepNames :: C.Session -> End -> [String]
stepNames s end = [if length (filter (== base) bases) > 1 then base ++ "Step" ++ show k else base | (k, base) <- zip [1 :: Int ..] bases]
  where
    bases = [sessionName s ++ show end ++ verb (sends end first) ++ typeName ty | (first, ty) <- C.sessionSteps s]
    verb True = "Send"
    verb False = "Receive"

sessionName :: C.Session -> String
sessionName = capitalize . C.sessionName

-- Whether an end sends at a step whose first end sends when first is True.
sends :: End -> Bool -> Bool
sends First first = first
sends Second first = not first

-- A step type's part of a type name: Int32, ListInt32, or the protocol's
-- name for a delegated end.
typeName :: C.Type -> String
typeName ty = case ty of
  C.Constructor name arguments -> capitalize (filter isAlphaNum (lastSegment name)) ++ concat [typeName t | C.TypeArgument t <- arguments]
  _ -> "Value"
  where
    lastSegment name = case breakOn "::" name of
      (_, Just rest) -> lastSegment rest
      (whole, Nothing) -> reverse (takeWhile (/= '.') (reverse whole))

-- The protocol a step type delegates, if any.
delegated :: [C.Session] -> C.Type -> Maybe C.Session
delegated sessions (C.Constructor name []) = case [s | s <- sessions, C.idText (C.sessionId s) == name] of
  s:_ -> Just s
  [] -> Nothing
delegated _ _ = Nothing

protocol :: [C.DataDeclaration] -> [C.Session] -> C.Session -> Either String [String]
protocol datas sessions s = do
  firstSteps <- mapM (step First) (zip [0 ..] steps)
  secondSteps <- mapM (step Second) (zip [0 ..] steps)
  pure (open ++ concat firstSteps ++ done First ++ concat secondSteps ++ done Second)
  where
    p = sessionName s
    steps = C.sessionSteps s
    count = length steps
    -- Before step k, a wrapped end, or a Done value after the last step.
    wrap end k var
      | k >= count = endType s end k ++ "{}"
      | otherwise = endType s end k ++ "{" ++ var ++ "}"
    open =
      [ ""
      , "// Open" ++ p ++ " opens a channel for protocol " ++ C.sessionName s ++ " and returns its two"
      , "// ends: the first follows the protocol, the second does the reverse."
      , "func Open" ++ p ++ "() (" ++ endType s First 0 ++ ", " ++ endType s Second 0 ++ ") {" ] ++
      (if count == 0 then [] else ["\tfirst, second := LawSpecOpenEnds(LawSpecNewChannel(" ++ show count ++ "))"]) ++
      [ "\treturn " ++ wrap First 0 "first" ++ ", " ++ wrap Second 0 "second"
      , "}" ]
    done end =
      [ ""
      , "// " ++ endType s end count ++ " is protocol " ++ C.sessionName s ++ "'s " ++ endWord end ++ " end after its last step."
      , "type " ++ endType s end count ++ " struct{}" ]
    endWord First = "first"
    endWord Second = "second"
    nextWord k
      | k + 1 >= count = "its finished end"
      | otherwise = "the end for step " ++ show (k + 2)
    step end (k, (first, ty)) = do
      (goType, description) <- case delegated sessions ty of
        Just q -> pure (endType q First 0, "an unused first end of protocol " ++ C.sessionName q)
        Nothing -> (\t -> (t, "a value of type " ++ t)) <$> goDataType datas ty
      let name = endType s end k
          next = wrap end (k + 1) "next"
          bind = if k + 1 >= count then "_" else "next"
          heading = if sends end first then "sends " else "receives "
          -- A delegated end is spent here; the receiver gets a fresh one.
          sent = case delegated sessions ty of
            Just q | C.sessionSteps q /= [] -> goType ++ "{value.end.HandOver()}"
            _ -> "value"
      pure $
        [ ""
        , "// " ++ name ++ " is protocol " ++ C.sessionName s ++ "'s " ++ endWord end ++ " end at step " ++ show (k + 1) ++ " of " ++ show count ++ ": it"
        , "// " ++ heading ++ description ++ "."
        , "type " ++ name ++ " struct{ end *LawSpecEnd }"
        , ""
        , "// Abandon gives up the conversation: the other end's receives fail with"
        , "// LawSpecPeerFailed once it has received what was already sent."
        , "func (e " ++ name ++ ") Abandon() { e.end.Abandon() }"
        , "" ] ++
        (if sends end first then
          [ "// Send sends " ++ description ++ " and returns " ++ nextWord k ++ "." ] ++
          [ "// The end sent is spent: only its receiver may use it." | Just _ <- [delegated sessions ty] ] ++
          [ "func (e " ++ name ++ ") Send(value " ++ goType ++ ") " ++ endType s end (k + 1) ++ " {"
          , "\t" ++ (if bind == "_" then "" else "next := ") ++ "e.end.Send(" ++ sent ++ ")"
          , "\treturn " ++ next
          , "}" ]
        else
          [ "// Receive waits for " ++ description ++ " and returns it with " ++ nextWord k ++ "."
          , "// It panics with LawSpecPeerFailed when the other end gave up."
          , "func (e " ++ name ++ ") Receive() (" ++ goType ++ ", " ++ endType s end (k + 1) ++ ") {"
          , "\tvalue, " ++ bind ++ " := e.end.Receive()"
          , "\treturn value.(" ++ goType ++ "), " ++ next
          , "}"
          , ""
          , "// TryReceive is Receive, but returns LawSpecPeerFailed when the other end"
          , "// gave up, instead of panicking."
          , "func (e " ++ name ++ ") TryReceive() (" ++ goType ++ ", " ++ endType s end (k + 1) ++ ", error) {"
          , "\tvalue, " ++ bind ++ ", err := e.end.TryReceive()"
          , "\tif err != nil {"
          , "\t\tvar zero " ++ goType
          , "\t\treturn zero, " ++ endType s end (k + 1) ++ "{}, err"
          , "\t}"
          , "\treturn value.(" ++ goType ++ "), " ++ next ++ ", nil"
          , "}" ])

capitalize :: String -> String
capitalize [] = []
capitalize (c:cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn c s = case break (== c) s of
  (a, []) -> [a]
  (a, _:b) -> a : splitOn c b

breakOn :: String -> String -> (String, Maybe String)
breakOn _ [] = ([], Nothing)
breakOn sep s@(c:cs)
  | take (length sep) s == sep = ([], Just (drop (length sep) s))
  | otherwise = let (a, rest) = breakOn sep cs in (c:a, rest)
