-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- A protocol P has two ends, First and Second (the second sends what the
-- first receives). Each end has a struct type per step, named for the end
-- and what the step does (ServeFirstReceiveInt32), with the step number
-- appended when that name repeats on the same end, and a Done type after
-- the last step. Send and Receive return the next step's type, so Go's
-- compiler rejects steps out of order; the runtime's LawSpecEnd panics when
-- an end is used twice. A step sending another protocol Q carries Q's first
-- end at its start.
module LawSpec.Sessions.Go (emit) where

import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.GoData (goDataType)
import Data.Char (isAlphaNum, toUpper)
import Data.List (intercalate)

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ _ datas units = mapM (unitSessions datas) [u | u <- units, not (null (C.unitSessions u))]

-- lawspec_sessions.go in the unit's package.
unitSessions :: [C.DataDeclaration] -> C.Unit -> Either String Artifact
unitSessions datas u = do
  bodies <- mapM (protocol datas sessions) sessions
  pure (Artifact (intercalate "/" parts ++ "/lawspec_sessions.go") (unlines (header ++ concat bodies)) "generated" "source")
  where
    sessions = C.unitSessions u
    parts = splitOn '.' (C.idText (C.unitId u))
    header =
      [ "// Generated by LawSpec. Do not edit."
      , "package " ++ last parts
      , ""
      , "// Typed channel ends for this unit's protocols. Each end's type names the"
      , "// step it is at; Send or Receive returns the end for the next step, so steps"
      , "// out of order do not compile. Each end is used once: using it again panics."
      ]

data End = First | Second deriving (Eq, Show)

-- The type of a protocol's end before step k (0-based); its Done type after
-- the last step.
endType :: C.Session -> End -> Int -> String
endType s end k
  | k >= length steps = sessionName s ++ show end ++ "Done"
  | otherwise = stepNames s end !! k
  where steps = C.sessionSteps s

stepNames :: C.Session -> End -> [String]
stepNames s end = [if length (filter (== base) bases) > 1 then base ++ "Step" ++ show k else base | (k, base) <- zip [1 :: Int ..] bases]
  where
    bases = [sessionName s ++ show end ++ verb (sends end first) ++ typeName ty | (first, ty) <- C.sessionSteps s]
    verb True = "Send"
    verb False = "Receive"

sessionName :: C.Session -> String
sessionName = capitalize . C.sessionName

-- Whether an end sends at a step whose first end sends when first is True.
sends :: End -> Bool -> Bool
sends First first = first
sends Second first = not first

-- A step type's part of a type name: Int32, ListInt32, or the protocol's
-- name for a delegated end.
typeName :: C.Type -> String
typeName ty = case ty of
  C.Constructor name arguments -> capitalize (filter isAlphaNum (lastSegment name)) ++ concat [typeName t | C.TypeArgument t <- arguments]
  _ -> "Value"
  where
    lastSegment name = case breakOn "::" name of
      (_, Just rest) -> lastSegment rest
      (whole, Nothing) -> reverse (takeWhile (/= '.') (reverse whole))

-- The protocol a step type delegates, if any.
delegated :: [C.Session] -> C.Type -> Maybe C.Session
delegated sessions (C.Constructor name []) = case [s | s <- sessions, C.idText (C.sessionId s) == name] of
  s:_ -> Just s
  [] -> Nothing
delegated _ _ = Nothing

protocol :: [C.DataDeclaration] -> [C.Session] -> C.Session -> Either String [String]
protocol datas sessions s = do
  firstSteps <- mapM (step First) (zip [0 ..] steps)
  secondSteps <- mapM (step Second) (zip [0 ..] steps)
  pure (open ++ concat firstSteps ++ done First ++ concat secondSteps ++ done Second)
  where
    p = sessionName s
    steps = C.sessionSteps s
    count = length steps
    -- Before step k, a wrapped end, or a Done value after the last step.
    wrap end k var
      | k >= count = endType s end k ++ "{}"
      | otherwise = endType s end k ++ "{" ++ var ++ "}"
    open =
      [ ""
      , "// Open" ++ p ++ " opens a channel for protocol " ++ C.sessionName s ++ " and returns its two"
      , "// ends: the first follows the protocol, the second does the reverse."
      , "func Open" ++ p ++ "() (" ++ endType s First 0 ++ ", " ++ endType s Second 0 ++ ") {" ] ++
      (if count == 0 then [] else ["\tfirst, second := LawSpecOpenEnds(LawSpecNewChannel(" ++ show count ++ "))"]) ++
      [ "\treturn " ++ wrap First 0 "first" ++ ", " ++ wrap Second 0 "second"
      , "}" ]
    done end =
      [ ""
      , "// " ++ endType s end count ++ " is protocol " ++ C.sessionName s ++ "'s " ++ endWord end ++ " end after its last step."
      , "type " ++ endType s end count ++ " struct{}" ]
    endWord First = "first"
    endWord Second = "second"
    nextWord k
      | k + 1 >= count = "its finished end"
      | otherwise = "the end for step " ++ show (k + 2)
    step end (k, (first, ty)) = do
      (goType, description) <- case delegated sessions ty of
        Just q -> pure (endType q First 0, "an unused first end of protocol " ++ C.sessionName q)
        Nothing -> (\t -> (t, "a value of type " ++ t)) <$> goDataType datas ty
      let name = endType s end k
          next = wrap end (k + 1) "next"
          bind = if k + 1 >= count then "_" else "next"
          heading = if sends end first then "sends " else "receives "
          -- A delegated end is spent here; the receiver gets a fresh one.
          sent = case delegated sessions ty of
            Just q | C.sessionSteps q /= [] -> goType ++ "{value.end.HandOver()}"
            _ -> "value"
      pure $
        [ ""
        , "// " ++ name ++ " is protocol " ++ C.sessionName s ++ "'s " ++ endWord end ++ " end at step " ++ show (k + 1) ++ " of " ++ show count ++ ": it"
        , "// " ++ heading ++ description ++ "."
        , "type " ++ name ++ " struct{ end *LawSpecEnd }"
        , "" ] ++
        (if sends end first then
          [ "// Send sends " ++ description ++ " and returns " ++ nextWord k ++ "." ] ++
          [ "// The end sent is spent: only its receiver may use it." | Just _ <- [delegated sessions ty] ] ++
          [ "func (e " ++ name ++ ") Send(value " ++ goType ++ ") " ++ endType s end (k + 1) ++ " {"
          , "\t" ++ (if bind == "_" then "" else "next := ") ++ "e.end.Send(" ++ sent ++ ")"
          , "\treturn " ++ next
          , "}" ]
        else
          [ "// Receive waits for " ++ description ++ " and returns it with " ++ nextWord k ++ "."
          , "func (e " ++ name ++ ") Receive() (" ++ goType ++ ", " ++ endType s end (k + 1) ++ ") {"
          , "\tvalue, " ++ bind ++ " := e.end.Receive()"
          , "\treturn value.(" ++ goType ++ "), " ++ next
          , "}" ])

capitalize :: String -> String
capitalize [] = []
capitalize (c:cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn c s = case break (== c) s of
  (a, []) -> [a]
  (a, _:b) -> a : splitOn c b

breakOn :: String -> String -> (String, Maybe String)
breakOn _ [] = ([], Nothing)
breakOn sep s@(c:cs)
  | take (length sep) s == sep = ([], Just (drop (length sep) s))
  | otherwise = let (a, rest) = breakOn sep cs in (c:a, rest)
