-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- A unit's protocols become the module LawSpecSessions.<Unit>. Each end of
-- protocol P gets a newtype per step, named P ++ End ++ Verb ++ Message (the
-- step number appended when that name repeats on the end), and a Done type;
-- each step type is an instance of LawSpecRuntime's Send or Receive, whose
-- method returns the next step's type. openP opens a channel's two ends.
module LawSpec.Sessions.Haskell (emit) where

import Data.Char (isAlphaNum, toUpper)
import Data.List (intercalate, isPrefixOf, nub, sort)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.HaskellData (haskellNativeTypeWithParameters)

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ _ datas units = mapM (unitModule datas units) (filter (not . null . C.unitSessions) units)

-- An end of a protocol: the first follows its steps, the second reverses them.
data End = First | Second deriving (Eq, Show)

-- One step of an end, as generated.
data Step = Step { stepNumber :: Int, stepSends :: Bool, stepMessage :: C.Type, stepTypeName :: String }

unitModule :: [C.DataDeclaration] -> [C.Unit] -> C.Unit -> Either String Artifact
unitModule datas units unit = do
  protocols <- mapM (protocolSource datas units unit) sessions
  let body = concatMap snd protocols
      qualifiers = nub (concatMap fst protocols)
      header =
        [ "{-# LANGUAGE MultiParamTypeClasses, FlexibleInstances #-}"
        , "-- Generated by LawSpec. Do not edit."
        , "-- | Typed channel ends for the protocols of unit " ++ unitName ++ "."
        , "--"
        , "-- Each end of a protocol has a type per step: 'LS.send' or 'LS.receive' on"
        , "-- it returns the end for the next step, so steps out of order do not"
        , "-- compile. Every end is single use: using one twice fails at run time."
        , "module " ++ moduleName ]
        ++ exportList
        ++ [ "  ) where"
        , ""
        , "import qualified LawSpecRuntime as LS" ]
        ++ [ "import " ++ line | (prefix, line) <- imports, prefix `elem` qualifiers ]
  pure (Artifact ("src/" ++ map (\c -> if c == '.' then '/' else c) moduleName ++ ".hs")
    (unlines header ++ body) "generated" "source")
  where
    unitName = C.idText (C.unitId unit)
    moduleName = sessionModule unitName
    sessions = C.unitSessions unit
    -- Sections of exports, each under a Haddock heading.
    sections =
      [ (C.sessionName s, endTypes First s ++ endTypes Second s ++ ["open" ++ C.sessionName s]) | s <- sessions ]
      ++ [ ("Using ends", ["LS.Send(..)", "LS.Receive(..)"])
         , ("Processes", ["LS.Process", "LS.spawn", "LS.join", "LS.par"]) ]
    exportList = concat
      [ ["    -- * " ++ heading | i > 0] ++
          [ (if i == 0 && j == 0 then "  ( -- * " ++ heading ++ "\n    " else "  , ") ++ export
          | (j, export) <- zip [0 :: Int ..] names ]
      | (i, (heading, names)) <- zip [0 :: Int ..] sections ]
    endTypes end s = map stepTypeName (endSteps end s) ++ [doneName end s]
    -- Qualifiers the native type mapping uses, and their imports.
    imports =
      [ ("P.", "qualified Prelude as P"), ("I.", "qualified Data.Int as I")
      , ("W.", "qualified Data.Word as W"), ("T.", "qualified Data.Text as T")
      , ("B.", "qualified Data.ByteString as B"), ("C.", "qualified Data.Complex as C")
      , ("Seq.", "qualified Data.Sequence as Seq"), ("Set.", "qualified Data.Set as Set")
      , ("Map.", "qualified Data.Map.Strict as Map"), ("Data.", "qualified LawSpecData as Data") ]
      ++ [ (sessionModule (C.idText (C.unitId other)) ++ ".", "qualified " ++ sessionModule (C.idText (C.unitId other)))
         | other <- units, C.unitId other /= C.unitId unit ]

-- The module holding a unit's session types.
sessionModule :: String -> String
sessionModule unitName = intercalate "." ("LawSpecSessions" : map modulePart (splitOn '.' unitName))
  where modulePart = concatMap capitalize . splitOn '_'

-- A protocol's declarations, with the qualifiers its message types use.
protocolSource :: [C.DataDeclaration] -> [C.Unit] -> C.Unit -> C.Session -> Either String ([String], String)
protocolSource datas units unit session = do
  ends <- mapM endSource [First, Second]
  let messages = concat [ [ t | (t, _) <- types ] | (types, _) <- ends ]
  pure (concatMap qualifiersOf messages, unlines (protocolComment ++ concatMap snd ends ++ open))
  where
    name = C.sessionName session
    protocolComment =
      [ "", "-- " ++ name ++ ": the first end "
          ++ (if null (C.sessionSteps session) then "does nothing" else intercalate ", then " (map describeStep (C.sessionSteps session)))
          ++ ";", "-- the second end does the reverse." ]
    describeStep (sends, t) = (if sends then "sends " else "receives ") ++ describe t
    describe t = maybe (messageName t) (\s -> C.sessionName s ++ "'s first end") (delegated units t)
    endSource end = do
      let steps = endSteps end session
          nextName k = maybe (doneName end session) stepTypeName (lookupStep (k + 1) steps)
      declarations <- mapM (\st -> do
        message <- messageType datas units unit (stepMessage st)
        let verb = if stepSends st then "Send" else "Receive"
            this = stepTypeName st
            next = nextName (stepNumber st)
            method = if stepSends st then "send (" ++ this ++ " end) = LS.sendOn " ++ next ++ " end"
              else "receive (" ++ this ++ " end) = LS.receiveOn " ++ next ++ " end"
        pure (message,
          [ ""
          , "-- | " ++ name ++ "'s " ++ endWord end ++ " end before step " ++ show (stepNumber st) ++ ": "
              ++ (if stepSends st then "sends " else "receives ") ++ describe (stepMessage st) ++ "."
          , "newtype " ++ this ++ " = " ++ this ++ " LS.SessionEnd"
          , ""
          , "instance LS." ++ verb ++ " " ++ this ++ " " ++ parenthesize message ++ " " ++ next ++ " where"
          , "  " ++ method ])) steps
      let done = doneName end session
      pure (declarations, concatMap snd declarations ++
        [ "", "-- | " ++ name ++ "'s " ++ endWord end ++ " end after its last step."
        , "newtype " ++ done ++ " = " ++ done ++ " LS.SessionEnd" ])
    start end = maybe (doneName end session) stepTypeName (lookupStep 1 (endSteps end session))
    open =
      [ "", "-- | Opens a " ++ name ++ " channel: its first end and its second end, each before step 1."
      , "open" ++ name ++ " :: IO (" ++ start First ++ ", " ++ start Second ++ ")"
      , "open" ++ name ++ " = do"
      , "  (first, second) <- LS.openSession"
      , "  pure (" ++ start First ++ " first, " ++ start Second ++ " second)" ]

endWord :: End -> String
endWord First = "first"
endWord Second = "second"

-- An end's steps, named; a name repeated on the end carries its step number.
endSteps :: End -> C.Session -> [Step]
endSteps end session = [ Step k sends t (named k base) | (k, sends, t, base) <- bases ]
  where
    bases = [ (k, sends, t, C.sessionName session ++ show end ++ (if sends then "Send" else "Receive") ++ messageName t)
            | (k, (firstSends, t)) <- zip [1 :: Int ..] (C.sessionSteps session)
            , let sends = if end == First then firstSends else not firstSends ]
    named k base
      | length (filter (\(_, _, _, b) -> b == base) bases) > 1 = base ++ "Step" ++ show k
      | otherwise = base

lookupStep :: Int -> [Step] -> Maybe Step
lookupStep k steps = case filter ((== k) . stepNumber) steps of
  step : _ -> Just step
  [] -> Nothing

doneName :: End -> C.Session -> String
doneName end session = C.sessionName session ++ show end ++ "Done"

-- The protocol a step's type names, when it sends a protocol's first end.
delegated :: [C.Unit] -> C.Type -> Maybe C.Session
delegated units (C.Constructor name []) =
  case [ s | u <- units, s <- C.unitSessions u, C.idText (C.sessionId s) == name ] of
    s : _ -> Just s
    [] -> Nothing
delegated _ _ = Nothing

-- A message's name within a step type's name: Int32, ListInt32, Serve.
messageName :: C.Type -> String
messageName t = case t of
  C.Constructor name arguments -> capitalize (filter isAlphaNum (lastSegment name))
    ++ concat [ messageName a | C.TypeArgument a <- arguments ]
  C.TypeVariable v -> capitalize (filter isAlphaNum (C.idText v))
  C.Arrow a b -> messageName a ++ "To" ++ messageName b
  where
    lastSegment = reverse . takeWhile (\c -> c /= ':' && c /= '.') . reverse

-- The Haskell type a step carries: a delegated protocol's first start type,
-- or the native type of a value.
messageType :: [C.DataDeclaration] -> [C.Unit] -> C.Unit -> C.Type -> Either String String
messageType datas units unit t = case delegated units t of
  Just session -> pure (qualifier ++ maybe (doneName First session) stepTypeName (lookupStep 1 (endSteps First session)))
    where
      owner = [ u | u <- units, session `elem` C.unitSessions u ]
      qualifier = case owner of
        u : _ | C.unitId u /= C.unitId unit -> sessionModule (C.idText (C.unitId u)) ++ "."
        _ -> ""
  Nothing -> haskellNativeTypeWithParameters datas [] [] t

-- The module qualifiers a type's text uses (e.g. "I." in I.Int32).
qualifiersOf :: String -> [String]
qualifiersOf text = sort (nub (go text))
  where
    go [] = []
    go s@(c : rest)
      | c `elem` ['A' .. 'Z'], (name, after) <- span (\x -> isAlphaNum x || x == '.') s =
          prefixes name ++ go after
      | otherwise = go rest
    -- Every dotted prefix of a qualified name: "Data." and "LawSpecSessions.X." alike.
    prefixes name = [ take (i + 1) name | (i, '.') <- zip [0 ..] name, not ("." `isPrefixOf` drop (i + 1) name) ]

parenthesize :: String -> String
parenthesize text
  | ' ' `elem` text && not ("(" `isPrefixOf` text) && not ("[" `isPrefixOf` text) = "(" ++ text ++ ")"
  | otherwise = text

capitalize :: String -> String
capitalize [] = []
capitalize (c : cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn delimiter value = case break (== delimiter) value of
  (a, []) -> [a]
  (a, _ : rest) -> a : splitOn delimiter rest
