-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- A unit's protocols become the module LawSpecSessions.<Unit>. Each end of
-- protocol P gets a newtype per step, named P ++ End ++ Verb ++ Message (the
-- step number appended when that name repeats on the end), and a Done type;
-- each step type is an instance of LawSpecRuntime's Send or Receive, whose
-- method returns the next step's type. openP opens a channel's two ends.
module LawSpec.Sessions.Haskell (emit) where

import Data.Char (isAlphaNum, toUpper)
import Data.List (intercalate, isPrefixOf, isSuffixOf, nub, sort)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.HaskellData (haskellNativeTypeWithParameters, haskellCodecDoc)
import LawSpec.MachineSpec (describe)
import qualified LawSpec.Code.Doc as D
import Control.Monad (foldM)

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ bits datas units = mapM (unitModule bits datas units) (filter (not . null . C.unitSessions) units)

-- An end of a protocol: the first follows its steps, the second reverses them.
data End = First | Second deriving (Eq, Show)

-- One step of an end, as generated.
data Step = Step { stepNumber :: Int, stepSends :: Bool, stepMessage :: C.Type, stepTypeName :: String }

unitModule :: Int -> [C.DataDeclaration] -> [C.Unit] -> C.Unit -> Either String Artifact
unitModule bits datas units unit = do
  let helpers = if null wires then "" else unlines
        [ ""
        , "-- Values crossing the network are logical; ends carry native ones,"
        , "-- converted with the data types' codecs."
        , "_lawspecSchema :: Schema.Schema"
        , "_lawspecSchema = P.either P.error P.id DataSchema.schema"
        , ""
        , "_lawspecBits :: P.Int"
        , "_lawspecBits = " ++ show bits
        , ""
        , "_lawspecTypes :: LS.DataTable"
        , "_lawspecTypes = [(LS.descriptorName n, f) | f@(LS.DescList (LS.DescAtom \"data\" : n : _)) <- LS.readDescriptor " ++ show (unwords (map snd (reverse types))) ++ "]"
        , ""
        , "_lawspecDescriptor :: P.String -> LS.Descriptor"
        , "_lawspecDescriptor text = case LS.readDescriptor text of"
        , "  form : _ -> form"
        , "  [] -> P.error \"empty descriptor\"" ]
  protocols <- mapM (\s -> protocolSource datas units unit (lookup (C.sessionName s) wires) s) sessions
  let body = helpers ++ concatMap snd protocols
      qualifiers = nub ("P." : concatMap fst protocols ++ qualifiersOf helpers)
      header =
        [ "{-# LANGUAGE MultiParamTypeClasses, FlexibleInstances #-}"
        , "-- Generated by LawSpec. Do not edit."
        , "-- | Typed channel ends for the protocols of unit " ++ unitName ++ "."
        , "--"
        , "-- Each end of a protocol has a type per step: 'LS.send' or 'LS.receive' on"
        , "-- it returns the end for the next step, so steps out of order do not"
        , "-- compile. Every end is single use: using one twice fails at run time."
        , "-- A receive whose other end gave up ('LS.abandon') throws 'LS.PeerFailed'"
        , "-- after the values already sent; 'LS.tryReceive' returns it as a Left."
        , "module " ++ moduleName ]
        ++ exportList
        ++ [ "  ) where"
        , ""
        , "import qualified LawSpecRuntime as LS" ]
        ++ [ "import " ++ line | (prefix, line) <- imports, prefix `elem` qualifiers ]
  pure (Artifact ("src/" ++ map (\c -> if c == '.' then '/' else c) moduleName ++ ".hs")
    (unlines header ++ body) "generated" "source")
  where
    unitName = C.idText (C.unitId unit)
    moduleName = sessionModule unitName
    sessions = C.unitSessions unit
    -- A protocol can also run between nodes (listen and dial) when every
    -- step's type has a wire descriptor and a codec; a step sending another
    -- protocol's end (of this unit) relays it, so that protocol must run
    -- between nodes too.
    wired (table, acc) s = case foldM step (table, []) (C.sessionSteps s) of
      Right (table', ds) -> (table', acc ++ [(C.sessionName s, ds)])
      _ -> (table, acc)
    step (t, ds) (sends, ty) = case delegated units ty of
      Just q | q `elem` sessions ->
        let start = maybe (doneName First q) stepTypeName (lookupStep 1 (endSteps First q))
        in Right (t, ds ++ [(sends, "(end)", "LS.endConversion (\\(" ++ start ++ " end) -> end) " ++ start ++ " _lawspecWire" ++ C.sessionName q)])
      Just _ -> Left "a protocol of another unit"
      Nothing -> do
        (d, t') <- describe bits datas t ty
        c <- D.render (D.Pretty 10000) <$> haskellCodecDoc datas "_lawspecSchema" "_lawspecBits" ty
        native <- haskellNativeTypeWithParameters datas [] [] ty
        let codec = "(" ++ c ++ " :: Codec.Codec " ++ parenthesize native ++ ")"
        pure (t', ds ++ [(sends, d, "LS.conversion (Codec.encode " ++ codec ++ ") (Codec.decode " ++ codec ++ ")")])
    (types, described) = foldl wired ([], []) sessions
    settle ws = let kept = [w | w@(_, steps) <- ws, all (\(_, d, c) -> d /= "(end)" || any (\(n, _) -> ("_lawspecWire" ++ n) `isSuffixOf` c) ws) steps]
                in if length kept == length ws then ws else settle kept
    wires = settle described
    -- Sections of exports, each under a Haddock heading.
    sections =
      [ (C.sessionName s, endTypes First s ++ endTypes Second s ++ ["open" ++ C.sessionName s] ++
          concat [["listen" ++ C.sessionName s, "dial" ++ C.sessionName s] | Just _ <- [lookup (C.sessionName s) wires]])
      | s <- sessions ]
      ++ [ ("Using ends", ["LS.Send(..)", "LS.Receive(..)", "LS.tryReceive", "LS.Abandon(..)", "LS.PeerFailed(..)"])
         , ("Processes", ["LS.Process", "LS.spawn", "LS.join", "LS.par"]) ]
    exportList = concat
      [ ["    -- * " ++ heading | i > 0] ++
          [ (if i == 0 && j == 0 then "  ( -- * " ++ heading ++ "\n    " else "  , ") ++ export
          | (j, export) <- zip [0 :: Int ..] names ]
      | (i, (heading, names)) <- zip [0 :: Int ..] sections ]
    endTypes end s = map stepTypeName (endSteps end s) ++ [doneName end s]
    -- Qualifiers the native type mapping uses, and their imports.
    imports =
      [ ("P.", "qualified Prelude as P"), ("I.", "qualified Data.Int as I")
      , ("W.", "qualified Data.Word as W"), ("T.", "qualified Data.Text as T")
      , ("B.", "qualified Data.ByteString as B"), ("C.", "qualified Data.Complex as C")
      , ("Seq.", "qualified Data.Sequence as Seq"), ("Set.", "qualified Data.Set as Set")
      , ("Map.", "qualified Data.Map.Strict as Map"), ("Data.", "qualified LawSpecData as Data")
      , ("Schema.", "qualified LawSpecSchema as Schema"), ("Codec.", "qualified LawSpecCodecs as Codec")
      , ("Codecs.", "qualified LawSpecDataCodecs as Codecs"), ("DataSchema.", "qualified LawSpecDataSchema as DataSchema")
      , ("Collections.", "qualified LawSpecCollectionCodecs as Collections") ]
      ++ [ (sessionModule (C.idText (C.unitId other)) ++ ".", "qualified " ++ sessionModule (C.idText (C.unitId other)))
         | other <- units, C.unitId other /= C.unitId unit ]

-- The module holding a unit's session types.
sessionModule :: String -> String
sessionModule unitName = intercalate "." ("LawSpecSessions" : map modulePart (splitOn '.' unitName))
  where modulePart = concatMap capitalize . splitOn '_'

-- A protocol's declarations, with the qualifiers its message types use.
protocolSource :: [C.DataDeclaration] -> [C.Unit] -> C.Unit -> Maybe [(Bool, String, String)] -> C.Session -> Either String ([String], String)
protocolSource datas units unit wire session = do
  ends <- mapM endSource [First, Second]
  let messages = concat [ [ t | (t, _) <- types ] | (types, _) <- ends ]
      network = case wire of
        Nothing -> []
        Just steps ->
          let wire = "_lawspecWire" ++ name
          in [ ""
             , "-- " ++ name ++ "'s steps between nodes, from its first end: each step's"
             , "-- descriptor and how its value crosses (a channel end goes by a relay)."
             , wire ++ " :: ([(P.Bool, LS.Descriptor)], [LS.Conversion])"
             , wire ++ " ="
             , "  ( [" ++ intercalate ", " ["(" ++ (if s then "P.True" else "P.False") ++ ", _lawspecDescriptor " ++ show d ++ ")" | (s, d, _) <- steps] ++ "]"
             , "  , [" ++ intercalate ", " [c | (_, _, c) <- steps] ++ "] )"
             , ""
             , "-- | The first end of a " ++ name ++ " channel named name on a node, which another"
             , "-- node dials at <node address>/name. An end sent over it to another node is"
             , "-- relayed by this node."
             , "listen" ++ name ++ " :: LS.Node -> P.String -> P.IO " ++ start First
             , "listen" ++ name ++ " node channel = do"
             , "  endpoint <- LS.listenOn node channel (P.fst " ++ wire ++ ") _lawspecTypes"
             , "  side <- LS.netChannelSide endpoint (P.snd " ++ wire ++ ")"
             , "  " ++ start First ++ " P.<$> LS.sessionEnd side"
             , ""
             , "-- | The second end of the " ++ name ++ " channel listening at an address on another node."
             , "dial" ++ name ++ " :: LS.Node -> P.String -> P.IO " ++ start Second
             , "dial" ++ name ++ " node address = do"
             , "  endpoint <- LS.dialTo node address [(P.not s, d) | (s, d) <- P.fst " ++ wire ++ "] _lawspecTypes"
             , "  side <- LS.netChannelSide endpoint (P.snd " ++ wire ++ ")"
             , "  " ++ start Second ++ " P.<$> LS.sessionEnd side" ]
      body = protocolComment ++ concatMap snd ends ++ open ++ network
  pure (concatMap qualifiersOf messages ++ qualifiersOf (unlines network), unlines body)
  where
    name = C.sessionName session
    protocolComment =
      [ "", "-- " ++ name ++ ": the first end "
          ++ (if null (C.sessionSteps session) then "does nothing" else intercalate ", then " (map describeStep (C.sessionSteps session)))
          ++ ";", "-- the second end does the reverse." ]
    describeStep (sends, t) = (if sends then "sends " else "receives ") ++ describe t
    describe t = maybe (messageName t) (\s -> C.sessionName s ++ "'s first end") (delegated units t)
    endSource end = do
      let steps = endSteps end session
          nextName k = maybe (doneName end session) stepTypeName (lookupStep (k + 1) steps)
      declarations <- mapM (\st -> do
        message <- messageType datas units unit (stepMessage st)
        let verb = if stepSends st then "Send" else "Receive"
            this = stepTypeName st
            next = nextName (stepNumber st)
            method = if stepSends st then "send (" ++ this ++ " end) = LS.sendOn " ++ next ++ " end"
              else "receive (" ++ this ++ " end) = LS.receiveOn " ++ next ++ " end"
        pure (message,
          [ ""
          , "-- | " ++ name ++ "'s " ++ endWord end ++ " end before step " ++ show (stepNumber st) ++ ": "
              ++ (if stepSends st then "sends " else "receives ") ++ describe (stepMessage st) ++ "."
          , "newtype " ++ this ++ " = " ++ this ++ " LS.SessionEnd"
          , ""
          , "instance LS." ++ verb ++ " " ++ this ++ " " ++ parenthesize message ++ " " ++ next ++ " where"
          , "  " ++ method
          , ""
          , "instance LS.Abandon " ++ this ++ " where"
          , "  abandon (" ++ this ++ " end) = LS.abandonEnd end" ])) steps
      let done = doneName end session
      pure (declarations, concatMap snd declarations ++
        [ "", "-- | " ++ name ++ "'s " ++ endWord end ++ " end after its last step."
        , "newtype " ++ done ++ " = " ++ done ++ " LS.SessionEnd" ])
    start end = maybe (doneName end session) stepTypeName (lookupStep 1 (endSteps end session))
    open =
      [ "", "-- | Opens a " ++ name ++ " channel: its first end and its second end, each before step 1."
      , "open" ++ name ++ " :: P.IO (" ++ start First ++ ", " ++ start Second ++ ")"
      , "open" ++ name ++ " = do"
      , "  (first, second) <- LS.openSession"
      , "  P.pure (" ++ start First ++ " first, " ++ start Second ++ " second)" ]

endWord :: End -> String
endWord First = "first"
endWord Second = "second"

-- An end's steps, named; a name repeated on the end carries its step number.
endSteps :: End -> C.Session -> [Step]
endSteps end session = [ Step k sends t (named k base) | (k, sends, t, base) <- bases ]
  where
    bases = [ (k, sends, t, C.sessionName session ++ show end ++ (if sends then "Send" else "Receive") ++ messageName t)
            | (k, (firstSends, t)) <- zip [1 :: Int ..] (C.sessionSteps session)
            , let sends = if end == First then firstSends else not firstSends ]
    named k base
      | length (filter (\(_, _, _, b) -> b == base) bases) > 1 = base ++ "Step" ++ show k
      | otherwise = base

lookupStep :: Int -> [Step] -> Maybe Step
lookupStep k steps = case filter ((== k) . stepNumber) steps of
  step : _ -> Just step
  [] -> Nothing

doneName :: End -> C.Session -> String
doneName end session = C.sessionName session ++ show end ++ "Done"

-- The protocol a step's type names, when it sends a protocol's first end.
delegated :: [C.Unit] -> C.Type -> Maybe C.Session
delegated units (C.Constructor name []) =
  case [ s | u <- units, s <- C.unitSessions u, C.idText (C.sessionId s) == name ] of
    s : _ -> Just s
    [] -> Nothing
delegated _ _ = Nothing

-- A message's name within a step type's name: Int32, ListInt32, Serve.
messageName :: C.Type -> String
messageName t = case t of
  C.Constructor name arguments -> capitalize (filter isAlphaNum (lastSegment name))
    ++ concat [ messageName a | C.TypeArgument a <- arguments ]
  C.TypeVariable v -> capitalize (filter isAlphaNum (C.idText v))
  C.Arrow a b -> messageName a ++ "To" ++ messageName b
  where
    lastSegment = reverse . takeWhile (\c -> c /= ':' && c /= '.') . reverse

-- The Haskell type a step carries: a delegated protocol's first start type,
-- or the native type of a value.
messageType :: [C.DataDeclaration] -> [C.Unit] -> C.Unit -> C.Type -> Either String String
messageType datas units unit t = case delegated units t of
  Just session -> pure (qualifier ++ maybe (doneName First session) stepTypeName (lookupStep 1 (endSteps First session)))
    where
      owner = [ u | u <- units, session `elem` C.unitSessions u ]
      qualifier = case owner of
        u : _ | C.unitId u /= C.unitId unit -> sessionModule (C.idText (C.unitId u)) ++ "."
        _ -> ""
  Nothing -> haskellNativeTypeWithParameters datas [] [] t

-- The module qualifiers a type's text uses (e.g. "I." in I.Int32).
qualifiersOf :: String -> [String]
qualifiersOf text = sort (nub (go text))
  where
    go [] = []
    go s@(c : rest)
      | c `elem` ['A' .. 'Z'], (name, after) <- span (\x -> isAlphaNum x || x == '.') s =
          prefixes name ++ go after
      | otherwise = go rest
    -- Every dotted prefix of a qualified name: "Data." and "LawSpecSessions.X." alike.
    prefixes name = [ take (i + 1) name | (i, '.') <- zip [0 ..] name, not ("." `isPrefixOf` drop (i + 1) name) ]

parenthesize :: String -> String
parenthesize text
  | ' ' `elem` text && not ("(" `isPrefixOf` text) && not ("[" `isPrefixOf` text) = "(" ++ text ++ ")"
  | otherwise = text

capitalize :: String -> String
capitalize [] = []
capitalize (c : cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn delimiter value = case break (== delimiter) value of
  (a, []) -> [a]
  (a, _ : rest) -> a : splitOn delimiter rest
