-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- Every protocol P becomes a class P with an open() that makes a channel and
-- returns its two start ends, and two nested classes, P.First (the end that
-- follows the steps) and P.Second (sends and receives swapped). Each holds a
-- class per step, named for what it does (ReceiveInt32, SendInt64), and Done
-- for after the last step; send(value) returns the next end and receive()
-- returns (value, next end). The ends and the channel come from
-- lawspec_runtime (SessionEnd, Channel).
module LawSpec.Sessions.Python (emit, pythonSessions) where

import Data.Char (isAlphaNum, isAscii, isUpper, toLower)
import Data.List (intercalate, isPrefixOf, nub)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.PythonTypes (identifier, pythonDataTypeDoc, requiresSchema)
import LawSpec.PythonData (pythonTypeReferenceDoc)
import LawSpec.MachineSpec (describe)
import Control.Monad (foldM)
import LawSpec.Scalar (isInteger, primitive)
import qualified LawSpec.Code.Doc as D

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ bits datas units = do
  source <- pythonSessionsWith bits datas units
  pure [Artifact "src/lawspec_sessions.py" source "generated" "source"]

-- The lawspec_sessions module.
pythonSessions :: [C.DataDeclaration] -> [C.Unit] -> Either String String
pythonSessions = pythonSessionsWith 64

pythonSessionsWith :: Int -> [C.DataDeclaration] -> [C.Unit] -> Either String String
pythonSessionsWith bits datas units = do
  let sessions = concatMap C.unitSessions units
      names = map C.sessionName sessions
  mapM_ identifier names
  if length (nub names) /= length names
    then Left ("two protocols share a Python name: " ++ unwords names)
    else pure ()
  -- A protocol whose steps have wire descriptors (and delegate no ends)
  -- can also run between nodes: listen and dial.
  -- A protocol can also run between nodes (listen and dial) when every
  -- step's type has a wire descriptor; a step sending another protocol's
  -- end carries the address of a relay, so that protocol must run between
  -- nodes too.
  let wired (table, acc) s = case foldM step (table, []) (C.sessionSteps s) of
        Right (table', ds) -> (table', acc ++ [(C.sessionName s, ds)])
        _ -> (table, acc)
      step (t, ds) (sends, ty) = case delegated ty of
        Just _ -> Right (t, ds ++ [(sends, "(end)", ty)])
        Nothing -> (\(d, t') -> (t', ds ++ [(sends, d, ty)])) <$> describe bits datas t ty
      (types, described) = foldl wired ([], []) sessions
      settle ws = let kept = [w | w@(_, steps) <- ws, all (\(_, _, t) -> maybe True (`elem` map fst ws) (delegated t)) steps]
                  in if length kept == length ws then ws else settle kept
      wires = settle described
  classes <- mapM (\s -> protocol datas sessions (lookup (C.sessionName s) wires) s) sessions
  let usesData = any (requiresSchema datas . snd) (concatMap C.sessionSteps sessions)
      header =
        [ "# Generated by LawSpec. Do not edit."
        , "\"\"\"Typed channel ends for the protocols of " ++ intercalate ", " (nub (map (C.idText . C.unitId) units)) ++ "."
        , ""
        , "For a protocol P, P.open() makes a channel and returns its two ends:"
        , "P.First follows P's steps and P.Second does the reverse. Each class is"
        , "one end before one step: send(value) returns the end for the next step"
        , "and receive() returns (value, end for the next step); after the last"
        , "step the end is a Done. An end can be used only once."
        , "\"\"\""
        , "from __future__ import annotations"
        , ""
        , "import lawspec_runtime as ls" ] ++
        [ line | usesData, line <- ["import lawspec_data as data", "import lawspec_schema as _schema"] ] ++
        [ line | not (null wires), line <-
          [ ""
          , "_TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ show (unwords (map snd (reverse types))) ++ ")})"
          , if usesData then "_SCHEMA = data.make_schema()" else "_SCHEMA = None"
          , ""
          , ""
          , "def _d(text):"
          , "    return ls.read_descriptor(text)[0]" ] ]
  pure (unlines header ++ concatMap (\c -> "\n\n" ++ c) classes)

-- One end before one step: its class name and what the step does.
data Position = Position String (Maybe (Bool, C.Type))

positionClass :: Position -> String
positionClass (Position cls _) = cls

-- The class of an end before its first step (Done when there are none).
startClass :: [(Bool, C.Type)] -> String
startClass steps = case positions steps of
  p : _ -> positionClass p
  [] -> "Done"

protocol :: [C.DataDeclaration] -> [C.Session] -> Maybe [(Bool, String, C.Type)] -> C.Session -> Either String String
protocol datas sessions wire session = do
  first <- end "First" "follows" (C.sessionSteps session)
  second <- end "Second" "is the other side of" [(not sends, ty) | (sends, ty) <- C.sessionSteps session]
  let start which steps = name ++ "." ++ which ++ "." ++ startClass steps
      firstStart = start "First" (C.sessionSteps session)
      secondStart = start "Second" [(not s, t) | (s, t) <- C.sessionSteps session]
  pure $ unlines $
    [ "class " ++ name ++ ":"
    , "    \"\"\"Protocol " ++ name ++ ": " ++ describeSteps (C.sessionSteps session) ++ "\"\"\""
    , "" ] ++ first ++ [""] ++ second ++
    [ ""
    , "    @staticmethod"
    , "    def open() -> tuple[" ++ firstStart ++ ", " ++ secondStart ++ "]:"
    , "        \"\"\"Makes a channel; returns its first end and its second end.\"\"\""
    , "        channel = ls.Channel()"
    , "        return " ++ firstStart ++ "(channel, 0), " ++ secondStart ++ "(channel, 1)" ] ++
    case wire of
      Nothing -> []
      Just steps ->
        let part (_, _, t) = case delegated t of
              Just q -> "ls.EndPart(lambda: " ++ startOf q ++ ", " ++ q ++ "._wire)"
              Nothing -> reference t
        in [ ""
           , "    @staticmethod"
           , "    def _wire():"
           , "        \"\"\"Each step's wire descriptor and conversion, from the first end.\"\"\""
           , "        return ([" ++ intercalate ", " ["(" ++ (if s then "True" else "False") ++ ", _d(" ++ show d ++ "))" | (s, d, _) <- steps] ++ "],"
           , "                [" ++ intercalate ", " (map part steps) ++ "])"
           , ""
           , "    @staticmethod"
           , "    def listen(node: ls.Node, name: str) -> " ++ firstStart ++ ":"
           , "        \"\"\"The first end of a channel named name on node, which another node"
           , "        dials at <node address>/name. An end sent over it to another node is"
           , "        relayed by this node.\"\"\""
           , "        steps, parts = " ++ name ++ "._wire()"
           , "        return " ++ firstStart ++ "(ls.NativeChannel(node.listen(name, steps, _TYPES), parts, _SCHEMA), 0)"
           , ""
           , "    @staticmethod"
           , "    def dial(node: ls.Node, address: str) -> " ++ secondStart ++ ":"
           , "        \"\"\"The second end of the channel listening at address on another node.\"\"\""
           , "        steps, parts = " ++ name ++ "._wire()"
           , "        return " ++ secondStart ++ "(ls.NativeChannel(node.dial(address, [(not s, d) for s, d in steps], _TYPES), parts, _SCHEMA), 1)" ]
  where
    reference ty = if requiresSchema datas ty then either (const "None") (D.render (D.Pretty 1000)) (pythonTypeReferenceDoc ty) else "None"
    name = C.sessionName session
    describeSteps [] = "no steps."
    describeSteps steps = "the first end " ++ intercalate ", then " [verb s ++ " " ++ typeText t | (s, t) <- steps] ++ "."
    verb s = if s then "sends" else "receives"
    end which relation steps = do
      let ps = positions steps
          count = length steps
      bodies <- mapM (position which count) (zip3 [1 :: Int ..] ps (drop 1 ps))
      let done = "        class " ++ positionClass (last ps) ++ "(ls.SessionEnd):\n" ++
                 "            \"\"\"" ++ name ++ "'s " ++ map toLower which ++ " end after its last step: nothing more to do.\"\"\""
      pure $ [ "    class " ++ which ++ ":"
             , "        \"\"\"The end that " ++ relation ++ " " ++ name ++ "'s steps.\"\"\""
             , "" ] ++ map (++ "\n") bodies ++ [done]
      where
        position _ _ (_, Position _ Nothing, _) = Left "a session's last position has no step"
        position w total (k, Position cls (Just (sends, ty)), Position next _) = do
          native <- nativeType ty
          let qualified = name ++ "." ++ w ++ "." ++ next
              doc = name ++ "'s " ++ map toLower w ++ " end, step " ++ show k ++ " of " ++ show total ++ ": "
          pure $ intercalate "\n" $
            [ "        class " ++ cls ++ "(ls.SessionEnd):" ] ++
            if sends
              then [ "            \"\"\"" ++ doc ++ "send " ++ article ty ++ "."
                   , ""
                   , "            send(value) returns the end for the next step."
                   , "            \"\"\""
                   , ""
                   , "            def send(self, value: " ++ native ++ ") -> " ++ qualified ++ ":"
                   , "                \"\"\"Sends value; returns the end for the next step.\"\"\""
                   , "                return " ++ sendCall ty qualified ]
              else [ "            \"\"\"" ++ doc ++ "receive " ++ article ty ++ "."
                   , ""
                   , "            receive() returns the value and the end for the next step."
                   , "            \"\"\""
                   , ""
                   , "            def receive(self) -> tuple[" ++ native ++ ", " ++ qualified ++ "]:"
                   , "                \"\"\"Waits for the value; returns it and the end for the next step.\"\"\""
                   , "                return self._receive(" ++ qualified ++ ")" ]
    sendCall ty after = case delegated ty of
      Just q -> "self._send_end(value, " ++ startOf q ++ ", " ++ after ++ ")"
      Nothing -> case ty of
        C.Constructor n [] | checked n -> "self._send(ls.check_send(value, " ++ show n ++ "), " ++ after ++ ")"
        _ -> "self._send(value, " ++ after ++ ")"
    checked n = isInteger n || n `elem` ["Bool", "Text", "Char", "Bytes"]
    nativeType ty = case delegated ty of
      Just q -> pure (startOf q)
      Nothing -> strip . D.render (D.Pretty 1000) <$> pythonDataTypeDoc datas ty
    startOf q = case [s | s <- sessions, C.sessionName s == q] of
      s : _ -> q ++ ".First." ++ startClass (C.sessionSteps s)
      [] -> q
    article ty = case delegated ty of
      Just q -> q ++ "'s first end (unused)"
      Nothing -> let t = typeText ty in (if take 1 t `elem` map pure "AEIOU" then "an " else "a ") ++ t
    typeText ty = case delegated ty of
      Just q -> q ++ "'s first end"
      Nothing -> typeName ty
    -- builtins are shadowed nowhere in this module.
    builtins = "_builtins." :: String
    strip s = case s of
      [] -> []
      _ | builtins `isPrefixOf` s -> strip (drop (length builtins) s)
      c : rest -> c : strip rest

-- The classes of one end: one per step (Verb + type name, with the step
-- number appended when a name repeats on this end), then Done.
positions :: [(Bool, C.Type)] -> [Position]
positions steps = zipWith3 place [1 :: Int ..] bases (map Just steps) ++ [Position "Done" Nothing]
  where
    bases = [(if sends then "Send" else "Receive") ++ typeName ty | (sends, ty) <- steps]
    place k base step
      | length (filter (== base) bases) > 1 = Position (base ++ "Step" ++ show k) step
      | otherwise = Position base step

-- A step type's readable name: its last name segment, then its arguments'.
typeName :: C.Type -> String
typeName ty = case ty of
  C.Constructor n args -> capital (filter ok (lastSegment n)) ++ concatMap argument args
  C.TypeVariable v -> capital (filter ok (C.idText v))
  C.Arrow a b -> typeName a ++ "To" ++ typeName b
  where
    argument (C.TypeArgument t) = typeName t
    argument (C.IndexArgument (C.Natural n)) = show n
    argument (C.IndexArgument (C.IndexVariable v)) = capital (filter ok (C.idText v))
    ok c = isAscii c && isAlphaNum c
    capital (c : cs) | not (isUpper c) = toUpperAscii c : cs
    capital s = s
    toUpperAscii c = if c >= 'a' && c <= 'z' then toEnum (fromEnum c - 32) else c

lastSegment :: String -> String
lastSegment n = go n n
  where
    go acc s = case s of
      [] -> acc
      ':' : ':' : rest -> go rest rest
      _ : rest -> go acc rest

-- The protocol a step's type names, if it sends a protocol's first end.
delegated :: C.Type -> Maybe String
delegated (C.Constructor n []) | "::session::" `infixOf` n, primitive n == Nothing = Just (lastSegment n)
  where infixOf needle hay = any (needle `isPrefixOf`) (suffixes hay)
        suffixes s = s : case s of [] -> []; _ : r -> suffixes r
delegated _ = Nothing
