-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- A protocol P becomes the module lawspec_sessions::p, with open() and a
-- submodule per end (first, second). Each end has a struct per step, named
-- by what it does next (ReceiveInt32, SendInt64; the step number is added
-- when a name repeats on that end), plus Done. A step's method takes self by
-- value and returns the next step, so Rust's moves reject an end used twice
-- or out of order at compile time.
module LawSpec.Sessions.Rust (emit) where

import Data.Char (isAlphaNum, isAscii, isUpper, toLower, toUpper)
import Data.List (intercalate, isPrefixOf, nub, tails)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.RustData (rustDataType)
import qualified LawSpec.MachineSpec as MachineSpec
import Control.Monad (foldM)

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ bits datas units = do
  let sessions = [(C.unitId unit, session) | unit <- units, session <- C.unitSessions unit]
      plain = map (moduleName . C.sessionName . snd) sessions
      -- Protocols of the same name in different units are qualified by unit.
      named = [ (if length (filter (== m) plain) > 1 then unitPrefix unit ++ "_" ++ m else m, session)
              | ((unit, session), m) <- zip sessions plain ]
      modules = [(C.idText (C.sessionId session), m) | (m, session) <- named]
  if length (nub (map fst named)) /= length named
    then Left "protocols map to the same Rust session module"
    else do
      -- A protocol whose steps have wire descriptors can also run between
      -- nodes: listen and dial. A step sending another protocol's end
      -- carries a relay's address ((end)), so that protocol must run
      -- between nodes too.
      let wired (table, acc) (m, s) = case foldM step (table, []) (C.sessionSteps s) of
            Right (table', ds) | not (null ds) -> (table', acc ++ [(m, ds)])
            _ -> (table, acc)
          step (t, ds) (sends, ty) = case delegatedType modules ty of
            Just q -> Right (t, ds ++ [(sends, "(end)", Just q)])
            Nothing -> (\(d, t') -> (t', ds ++ [(sends, d, Nothing)])) <$> MachineSpec.describe bits datas t ty
          (types, described) = foldl wired ([], []) named
          settle ws = let kept = [w | w@(_, steps) <- ws, all (\(_, _, q) -> maybe True (`elem` map fst ws) q) steps]
                      in if length kept == length ws then ws else settle kept
          wires = settle described
      bodies <- mapM (\(m, s) -> protocolModule datas modules (lookup m wires) m s) named
      pure [Artifact "src/lawspec_sessions.rs" (render types bodies) "generated" "source"]
  where
    render types bodies = unlines
      [ "// Generated by LawSpec. Do not edit."
      , "//! Typed channel ends for each protocol. A step's method consumes its end"
      , "//! and returns the next, so steps out of order, or an end used twice, do"
      , "//! not compile. An end that is dropped (as when its process panics) or"
      , "//! abandoned gives up the conversation: the other end's receive panics with"
      , "//! PeerFailed, and its try_receive returns it, after what was already sent."
      , "#![allow(dead_code)]"
      , ""
      , "/// The data types the protocols' steps use on the wire."
      , "fn wire_types() -> crate::lawspec_runtime::Values {"
      , "    crate::lawspec_runtime::values_table(" ++ show (unwords (map snd (reverse types))) ++ ")"
      , "}"
      ] ++ concatMap (\body -> '\n' : body ++ "\n") bodies
    unitPrefix = snake . map (\c -> if isAlphaNum c then c else '_') . C.idText

-- A protocol's module: open() and its two ends.
protocolModule :: [C.DataDeclaration] -> [(String, String)] -> Maybe [(Bool, String, Maybe String)] -> String -> C.Session -> Either String String
protocolModule datas modules wire name session = do
  firstEnd <- endModule datas modules session True
  secondEnd <- endModule datas modules session False
  natives <- mapM (valueType datas modules . snd) (C.sessionSteps session)
  let firstStart = "first::" ++ start (stepNames True)
      secondStart = "second::" ++ start (stepNames False)
      ends = if null (C.sessionSteps session)
        then "    (" ++ firstStart ++ "(()), " ++ secondStart ++ "(()))"
        else unlines' [ "    let (first_end, second_end) = ls::sessions::channel();"
                      , "    (" ++ firstStart ++ "(first_end), " ++ secondStart ++ "(second_end))" ]
      network = case wire of
        Nothing -> []
        Just steps ->
          let d text = "ls::descriptor(" ++ show text ++ ")"
              stepList = "vec![" ++ intercalate ", " ["(" ++ (if s then "true" else "false") ++ ", " ++ d t ++ ")" | (s, t, _) <- steps] ++ "]"
              codec ((_, _, Just q), _) = "ls::net::end_codec::<super::" ++ q ++ "::first::Start>(super::" ++ q ++ "::wire, super::" ++ q ++ "::first_into_endpoint, super::" ++ q ++ "::first_from_endpoint)"
              codec (_, n) = "ls::net::step_codec::<" ++ n ++ ">()"
              codecs = "vec![" ++ intercalate ", " (map codec (zip steps natives)) ++ "]"
          in [ ""
             , "    /// Each step's direction and wire descriptor, from the first end, and"
             , "    /// its codec: how this protocol runs between nodes."
             , "    pub fn wire() -> (Vec<(bool, ls::Sexp)>, Vec<ls::net::StepCodec>) {"
             , "        (" ++ stepList ++ ", " ++ codecs ++ ")"
             , "    }"
             , ""
             , "    #[doc(hidden)]"
             , "    pub fn first_into_endpoint(end: first::Start) -> ls::sessions::Endpoint {"
             , "        end.0"
             , "    }"
             , ""
             , "    #[doc(hidden)]"
             , "    pub fn first_from_endpoint(end: ls::sessions::Endpoint) -> first::Start {"
             , "        " ++ firstStart ++ "(end)"
             , "    }"
             , ""
             , "    /// The first end of a channel named name on node, which another node"
             , "    /// dials at <node address>/name. An end sent over it to another node"
             , "    /// is relayed by this node."
             , "    pub fn listen(node: &ls::net::Node, name: &str) -> ls::Result<first::Start> {"
             , "        let (steps, codecs) = wire();"
             , "        let end = node.listen(name, steps, super::wire_types(), std::time::Duration::from_secs(5))?;"
             , "        let transport = ls::net::NetSession::new(end, codecs);"
             , "        Ok(" ++ firstStart ++ "(ls::sessions::Endpoint::on(transport, ls::sessions::Side::First)))"
             , "    }"
             , ""
             , "    /// The second end of the channel listening at address on another node."
             , "    pub fn dial(node: &ls::net::Node, address: &str) -> ls::Result<second::Start> {"
             , "        let (steps, codecs) = wire();"
             , "        let end = node.dial(address, steps.into_iter().map(|(s, d)| (!s, d)).collect(), super::wire_types(), std::time::Duration::from_secs(5))?;"
             , "        let transport = ls::net::NetSession::new(end, codecs);"
             , "        Ok(" ++ secondStart ++ "(ls::sessions::Endpoint::on(transport, ls::sessions::Side::Second)))"
             , "    }" ]
  pure $ unlines' $
    [ "/// The protocol " ++ C.sessionName session ++ ": its first end " ++ describe modules True session ++ ";"
    , "/// the second end does the reverse."
    , "pub mod " ++ name ++ " {"
    , "    use crate::lawspec_runtime as ls;"
    , ""
    , "    /// Opens a fresh channel and returns its two ends."
    , "    pub fn open() -> (first::Start, second::Start) {"
    , indent ends
    , "    }"
    ] ++ network ++
    [ ""
    , indent firstEnd
    , ""
    , indent secondEnd
    , "}"
    ]
  where
    stepNames first = names first (C.sessionSteps session)

-- One end of a protocol: a struct per step, and Done.
endModule :: [C.DataDeclaration] -> [(String, String)] -> C.Session -> Bool -> Either String String
endModule datas modules session first = do
  types <- mapM (valueType datas modules . snd) steps
  let structs = [ struct k sends ty value next
                | (k, (sends, ty), value, next) <- zip4' [1 :: Int ..] steps types (drop 1 stepNames ++ ["Done"]) ]
  pure $ unlines'
    ([ "/// " ++ endTitle ++ ": it " ++ describe modules first session ++ "."
     , "pub mod " ++ endName ++ " {"
     , "    use crate::lawspec_runtime as ls;"
     , ""
     , "    /// This end before its first step."
     , "    pub type Start = " ++ start stepNames ++ ";"
     ] ++ concatMap (\s -> ["", indent s]) structs ++
     [ ""
     , "    /// " ++ endTitle ++ " after its last step: the session is over."
     , "    pub struct Done(pub(super) ());"
     , "}"
     ])
  where
    endName = if first then "first" else "second"
    endTitle = C.sessionName session ++ "'s " ++ endName ++ " end"
    steps = [(sends == first, ty) | (sends, ty) <- C.sessionSteps session]
    stepNames = names first (C.sessionSteps session)
    struct k sends ty value next =
      let name = stepNames !! (k - 1)
          what = valueWords modules ty
          nextValue = if next == "Done" then next ++ "(())" else next ++ "(self.0)"
      in unlines'
        ([ "/// " ++ endTitle ++ " before step " ++ show k ++ ", which " ++ (if sends then "sends " else "receives ") ++ what ++ "."
         , "#[must_use = \"a session end must be used until it is done\"]"
         , "pub struct " ++ name ++ "(pub(super) ls::sessions::Endpoint);"
         , ""
         , "impl " ++ name ++ " {"
         ] ++ map ("    " ++) (if sends
           then [ "/// Sends " ++ what ++ " to the other end."
                , "pub fn send(self, value: " ++ value ++ ") -> " ++ next ++ " {"
                , "    self.0.send(value);"
                , "    " ++ nextValue
                , "}" ]
           else [ "/// Receives " ++ what ++ ", waiting until the other end sends it;"
                , "/// panics with PeerFailed if the other end gave up instead."
                , "pub fn receive(self) -> (" ++ value ++ ", " ++ next ++ ") {"
                , "    let value = self.0.receive();"
                , "    (value, " ++ nextValue ++ ")"
                , "}"
                , ""
                , "/// Receives " ++ what ++ ", or PeerFailed once the other end gave up"
                , "/// (its process failed, or it abandoned or dropped its end)."
                , "pub fn try_receive(self) -> Result<(" ++ value ++ ", " ++ next ++ "), ls::sessions::PeerFailed> {"
                , "    let value = self.0.try_receive()?;"
                , "    Ok((value, " ++ nextValue ++ "))"
                , "}" ]) ++
         [ ""
         , "    /// Gives up the conversation: the other end's receives fail with"
         , "    /// PeerFailed after what was already sent. Dropping the end does the same."
         , "    pub fn abandon(self) {"
         , "        self.0.abandon();"
         , "    }" ] ++
         [ "}" ])
    zip4' (a:as) (b:bs) (c:cs) (d:ds) = (a, b, c, d) : zip4' as bs cs ds
    zip4' _ _ _ _ = []

-- An end's first struct: its first step's, or Done.
start :: [String] -> String
start = foldr const "Done"

-- The struct names of an end's steps: the verb and type, plus the step
-- number when that name repeats on the end.
names :: Bool -> [(Bool, C.Type)] -> [String]
names first steps =
  [ if length (filter (== base) bases) > 1 then base ++ "Step" ++ show k else base
  | (k, base) <- zip [1 :: Int ..] bases ]
  where bases = [(if sends == first then "Send" else "Receive") ++ typeName ty | (sends, ty) <- steps]

-- The protocol module a step's type delegates, if it is a protocol's end.
delegatedType :: [(String, String)] -> C.Type -> Maybe String
delegatedType modules ty = case ty of
  C.Constructor identity [] -> lookup identity modules
  _ -> Nothing

-- The Rust type of a step's value: a delegated protocol's first end, or the
-- value's native type.
valueType :: [C.DataDeclaration] -> [(String, String)] -> C.Type -> Either String String
valueType datas modules ty = case ty of
  C.Constructor identity [] | Just m <- lookup identity modules -> pure ("super::super::" ++ m ++ "::first::Start")
  _ -> rustDataType datas ty

-- What an end does, in words: "receives Int32, receives Int32, then sends Int64".
describe :: [(String, String)] -> Bool -> C.Session -> String
describe modules first session = case [(if sends == first then "sends " else "receives ") ++ valueWords modules ty | (sends, ty) <- C.sessionSteps session] of
  [] -> "does nothing"
  [one] -> one
  many -> intercalate ", " (init many) ++ ", then " ++ last many

-- A step's value in words: "an Int32", or "Serve's first end".
valueWords :: [(String, String)] -> C.Type -> String
valueWords modules ty = case ty of
  C.Constructor identity [] | Just _ <- lookup identity modules -> typeName ty ++ "'s first end"
  _ -> article (typeName ty)

-- A type's name for identifiers and docs: its constructors, unqualified.
typeName :: C.Type -> String
typeName ty = case ty of
  C.Constructor name arguments -> capitalize (unqualified name) ++ concat [typeName t | C.TypeArgument t <- arguments]
  C.TypeVariable identity -> capitalize (unqualified (C.idText identity))
  C.Arrow a b -> typeName a ++ "To" ++ typeName b
  where
    unqualified = filter (\c -> isAscii c && isAlphaNum c) . lastSegment
    lastSegment s = case [rest | rest <- tails s, "::" `isPrefixOf` rest || "." `isPrefixOf` rest] of
      [] -> s
      found -> dropWhile (`elem` (":." :: String)) (last found)
    capitalize (c:cs) = toUpper c : cs
    capitalize [] = "Value"

article :: String -> String
article word@(c:_) | toLower c `elem` ("aeiou" :: String) = "an " ++ word
article word = "a " ++ word

-- A protocol's module name: snake_case, raw when it is a Rust keyword.
moduleName :: String -> String
moduleName name = let m = snake name in if m `elem` keywords then "r#" ++ m else m
  where keywords = words "as async await break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self static struct super trait true type unsafe use where while abstract become box do final macro override priv typeof unsized virtual yield try gen"

snake :: String -> String
snake = dropWhile (== '_') . go
  where
    go (c:cs) | isUpper c = '_' : toLower c : go cs
              | otherwise = c : go cs
    go [] = []

indent :: String -> String
indent = intercalate "\n" . map (\l -> if null l then l else "    " ++ l) . lines

unlines' :: [String] -> String
unlines' = intercalate "\n"
