-- Typed channel ends for implementation code: each protocol's steps as
-- types of this target (see LawSpec.Sessions).
--
-- A protocol P becomes the module lawspec_sessions::p, with open() and a
-- submodule per end (first, second). Each end has a struct per step, named
-- by what it does next (ReceiveInt32, SendInt64; the step number is added
-- when a name repeats on that end), plus Done. A step's method takes self by
-- value and returns the next step, so Rust's moves reject an end used twice
-- or out of order at compile time.
module LawSpec.Sessions.Rust (emit) where

import Data.Char (isAlphaNum, isAscii, isUpper, toLower, toUpper)
import Data.List (intercalate, isPrefixOf, nub, tails)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.RustData (rustDataType)

-- The session library for the given target, for every unit's protocols.
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [C.Unit] -> Either String [Artifact]
emit _ _ _ datas units = do
  let sessions = [(C.unitId unit, session) | unit <- units, session <- C.unitSessions unit]
      plain = map (moduleName . C.sessionName . snd) sessions
      -- Protocols of the same name in different units are qualified by unit.
      named = [ (if length (filter (== m) plain) > 1 then unitPrefix unit ++ "_" ++ m else m, session)
              | ((unit, session), m) <- zip sessions plain ]
      modules = [(C.idText (C.sessionId session), m) | (m, session) <- named]
  if length (nub (map fst named)) /= length named
    then Left "protocols map to the same Rust session module"
    else do
      bodies <- mapM (uncurry (protocolModule datas modules)) named
      pure [Artifact "src/lawspec_sessions.rs" (render bodies) "generated" "source"]
  where
    render bodies = unlines
      [ "// Generated by LawSpec. Do not edit."
      , "//! Typed channel ends for each protocol. A step's method consumes its end"
      , "//! and returns the next, so steps out of order, or an end used twice, do"
      , "//! not compile."
      , "#![allow(dead_code)]"
      ] ++ concatMap (\body -> '\n' : body ++ "\n") bodies
    unitPrefix = snake . map (\c -> if isAlphaNum c then c else '_') . C.idText

-- A protocol's module: open() and its two ends.
protocolModule :: [C.DataDeclaration] -> [(String, String)] -> String -> C.Session -> Either String String
protocolModule datas modules name session = do
  firstEnd <- endModule datas modules session True
  secondEnd <- endModule datas modules session False
  let firstStart = "first::" ++ start (stepNames True)
      secondStart = "second::" ++ start (stepNames False)
      ends = if null (C.sessionSteps session)
        then "    (" ++ firstStart ++ "(()), " ++ secondStart ++ "(()))"
        else unlines' [ "    let (first_end, second_end) = ls::sessions::channel();"
                      , "    (" ++ firstStart ++ "(first_end), " ++ secondStart ++ "(second_end))" ]
  pure $ unlines'
    [ "/// The protocol " ++ C.sessionName session ++ ": its first end " ++ describe modules True session ++ ";"
    , "/// the second end does the reverse."
    , "pub mod " ++ name ++ " {"
    , "    use crate::lawspec_runtime as ls;"
    , ""
    , "    /// Opens a fresh channel and returns its two ends."
    , "    pub fn open() -> (first::Start, second::Start) {"
    , indent ends
    , "    }"
    , ""
    , indent firstEnd
    , ""
    , indent secondEnd
    , "}"
    ]
  where
    stepNames first = names first (C.sessionSteps session)

-- One end of a protocol: a struct per step, and Done.
endModule :: [C.DataDeclaration] -> [(String, String)] -> C.Session -> Bool -> Either String String
endModule datas modules session first = do
  types <- mapM (valueType datas modules . snd) steps
  let structs = [ struct k sends ty value next
                | (k, (sends, ty), value, next) <- zip4' [1 :: Int ..] steps types (drop 1 stepNames ++ ["Done"]) ]
  pure $ unlines'
    ([ "/// " ++ endTitle ++ ": it " ++ describe modules first session ++ "."
     , "pub mod " ++ endName ++ " {"
     , "    use crate::lawspec_runtime as ls;"
     , ""
     , "    /// This end before its first step."
     , "    pub type Start = " ++ start stepNames ++ ";"
     ] ++ concatMap (\s -> ["", indent s]) structs ++
     [ ""
     , "    /// " ++ endTitle ++ " after its last step: the session is over."
     , "    pub struct Done(pub(super) ());"
     , "}"
     ])
  where
    endName = if first then "first" else "second"
    endTitle = C.sessionName session ++ "'s " ++ endName ++ " end"
    steps = [(sends == first, ty) | (sends, ty) <- C.sessionSteps session]
    stepNames = names first (C.sessionSteps session)
    struct k sends ty value next =
      let name = stepNames !! (k - 1)
          what = valueWords modules ty
          nextValue = if next == "Done" then next ++ "(())" else next ++ "(self.0)"
      in unlines'
        ([ "/// " ++ endTitle ++ " before step " ++ show k ++ ", which " ++ (if sends then "sends " else "receives ") ++ what ++ "."
         , "#[must_use = \"a session end must be used until it is done\"]"
         , "pub struct " ++ name ++ "(pub(super) ls::sessions::Endpoint);"
         , ""
         , "impl " ++ name ++ " {"
         ] ++ map ("    " ++) (if sends
           then [ "/// Sends " ++ what ++ " to the other end."
                , "pub fn send(self, value: " ++ value ++ ") -> " ++ next ++ " {"
                , "    self.0.send(value);"
                , "    " ++ nextValue
                , "}" ]
           else [ "/// Receives " ++ what ++ ", waiting until the other end sends it."
                , "pub fn receive(self) -> (" ++ value ++ ", " ++ next ++ ") {"
                , "    let value = self.0.receive();"
                , "    (value, " ++ nextValue ++ ")"
                , "}" ]) ++
         [ "}" ])
    zip4' (a:as) (b:bs) (c:cs) (d:ds) = (a, b, c, d) : zip4' as bs cs ds
    zip4' _ _ _ _ = []

-- An end's first struct: its first step's, or Done.
start :: [String] -> String
start = foldr const "Done"

-- The struct names of an end's steps: the verb and type, plus the step
-- number when that name repeats on the end.
names :: Bool -> [(Bool, C.Type)] -> [String]
names first steps =
  [ if length (filter (== base) bases) > 1 then base ++ "Step" ++ show k else base
  | (k, base) <- zip [1 :: Int ..] bases ]
  where bases = [(if sends == first then "Send" else "Receive") ++ typeName ty | (sends, ty) <- steps]

-- The Rust type of a step's value: a delegated protocol's first end, or the
-- value's native type.
valueType :: [C.DataDeclaration] -> [(String, String)] -> C.Type -> Either String String
valueType datas modules ty = case ty of
  C.Constructor identity [] | Just m <- lookup identity modules -> pure ("super::super::" ++ m ++ "::first::Start")
  _ -> rustDataType datas ty

-- What an end does, in words: "receives Int32, receives Int32, then sends Int64".
describe :: [(String, String)] -> Bool -> C.Session -> String
describe modules first session = case [(if sends == first then "sends " else "receives ") ++ valueWords modules ty | (sends, ty) <- C.sessionSteps session] of
  [] -> "does nothing"
  [one] -> one
  many -> intercalate ", " (init many) ++ ", then " ++ last many

-- A step's value in words: "an Int32", or "Serve's first end".
valueWords :: [(String, String)] -> C.Type -> String
valueWords modules ty = case ty of
  C.Constructor identity [] | Just _ <- lookup identity modules -> typeName ty ++ "'s first end"
  _ -> article (typeName ty)

-- A type's name for identifiers and docs: its constructors, unqualified.
typeName :: C.Type -> String
typeName ty = case ty of
  C.Constructor name arguments -> capitalize (unqualified name) ++ concat [typeName t | C.TypeArgument t <- arguments]
  C.TypeVariable identity -> capitalize (unqualified (C.idText identity))
  C.Arrow a b -> typeName a ++ "To" ++ typeName b
  where
    unqualified = filter (\c -> isAscii c && isAlphaNum c) . lastSegment
    lastSegment s = case [rest | rest <- tails s, "::" `isPrefixOf` rest || "." `isPrefixOf` rest] of
      [] -> s
      found -> dropWhile (`elem` (":." :: String)) (last found)
    capitalize (c:cs) = toUpper c : cs
    capitalize [] = "Value"

article :: String -> String
article word@(c:_) | toLower c `elem` ("aeiou" :: String) = "an " ++ word
article word = "a " ++ word

-- A protocol's module name: snake_case, raw when it is a Rust keyword.
moduleName :: String -> String
moduleName name = let m = snake name in if m `elem` keywords then "r#" ++ m else m
  where keywords = words "as async await break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self static struct super trait true type unsafe use where while abstract become box do final macro override priv typeof unsized virtual yield try gen"

snake :: String -> String
snake = dropWhile (== '_') . go
  where
    go (c:cs) | isUpper c = '_' : toLower c : go cs
              | otherwise = c : go cs
    go [] = []

indent :: String -> String
indent = intercalate "\n" . map (\l -> if null l then l else "    " ++ l) . lines

unlines' :: [String] -> String
unlines' = intercalate "\n"
