// Generated by LawSpec. Do not edit.
//! The default handler of lawspec.concurrent's Async: threads. A pause yields
//! this thread. It is the runtime's NativeAsync (ls::ASYNC), which also starts
//! and waits for the tasks of workflows and async adapters.
#![allow(unused_variables, unused_imports, non_snake_case)]
use crate::lawspec_runtime as ls;

/// Native concurrency: pause lets other threads run.
#[derive(Default)]
pub struct AsyncHandler;

impl AsyncHandler {
    /// The runtime's native async, which this handler passes on to.
    pub fn native(&self) -> &'static ls::NativeAsync {
        &ls::ASYNC
    }
}

// spawn, wait, wait_future and all, as NativeAsync gives them.
impl std::ops::Deref for AsyncHandler {
    type Target = ls::NativeAsync;

    fn deref(&self) -> &ls::NativeAsync {
        &ls::ASYNC
    }
}

impl crate::lawspec_abilities::lawspec_concurrent::Async for AsyncHandler {
    fn pause(&self) -> () {
        self.native().pause()
    }
}
