// Generated by LawSpec. Do not edit.
//! The default handlers of lawspec.crypto: SHA3-256 and SHAKE256 (FIPS 202),
//! ML-KEM-768 (FIPS 203), ML-DSA-65 (FIPS 204), AES-256-GCM, and
//! SLH-DSA-SHAKE-128f (FIPS 205) as the alternative Signature handler. Their
//! primitives are in crypto_primitives.rs.
#![allow(unused_variables, unused_imports, non_snake_case)]
use crate::lawspec_runtime as ls;

#[path = "crypto_primitives.rs"]
pub mod primitives;

/// SHA3-256 and SHAKE256.
#[derive(Default)]
pub struct HashHandler;

impl crate::lawspec_abilities::lawspec_crypto::Hash for HashHandler {
    fn sha3(&self, value0: std::vec::Vec<u8>) -> @@Digest@@ {
        @@Digest@@ { value: primitives::sha3_256(&value0) }
    }

    fn shake(&self, value0: std::vec::Vec<u8>, value1: i32) -> std::vec::Vec<u8> {
        primitives::shake256(&value0, value1.max(0) as usize)
    }
}

/// ML-KEM-768.
#[derive(Default)]
pub struct KeyExchangeHandler;

impl crate::lawspec_abilities::lawspec_crypto::KeyExchange for KeyExchangeHandler {
    fn exchangeKeyPair(&self) -> @@ExchangeKeyPair@@ {
        let seed = primitives::random_bytes(64);
        @@ExchangeKeyPair@@ {
            publicKey: @@ExchangePublicKey@@ { value: primitives::ml_kem_768_public_key(&seed) },
            secretKey: @@ExchangeSecretKey@@ { value: seed },
        }
    }

    fn encapsulate(&self, value0: @@ExchangePublicKey@@) -> @@Encapsulated@@ {
        let (ciphertext, secret) = primitives::ml_kem_768_encapsulate(&value0.value);
        @@Encapsulated@@ { ciphertext: @@Ciphertext@@ { value: ciphertext }, secret: @@SharedSecret@@ { value: secret } }
    }

    fn decapsulate(&self, value0: @@ExchangeSecretKey@@, value1: @@Ciphertext@@) -> @@SharedSecret@@ {
        @@SharedSecret@@ { value: primitives::ml_kem_768_decapsulate(&value0.value, &value1.value) }
    }
}

/// ML-DSA-65, hedged.
#[derive(Default)]
pub struct SignatureHandler;

impl crate::lawspec_abilities::lawspec_crypto::Signature for SignatureHandler {
    fn signingKeyPair(&self) -> @@SigningKeyPair@@ {
        let seed = primitives::random_bytes(32);
        @@SigningKeyPair@@ {
            verifyingKey: @@VerifyingKey@@ { value: primitives::ml_dsa_65_public_key(&seed) },
            signingKey: @@SigningKey@@ { value: seed },
        }
    }

    fn sign(&self, value0: @@SigningKey@@, value1: std::vec::Vec<u8>) -> @@SignatureBytes@@ {
        @@SignatureBytes@@ { value: primitives::ml_dsa_65_sign(&value0.value, &value1, &[], false) }
    }

    fn verify(&self, value0: @@VerifyingKey@@, value1: std::vec::Vec<u8>, value2: @@SignatureBytes@@) -> bool {
        primitives::ml_dsa_65_verify(&value0.value, &value1, &value2.value, &[])
    }
}

/// SLH-DSA-SHAKE-128f, hedged: the alternative Signature handler. Bind it in
/// lawspec.json: {"ability": "lawspec.crypto::Signature", "native": ["crate",
/// "lawspec_crypto", "SlhDsaSignatureHandler"]}.
#[derive(Default)]
pub struct SlhDsaSignatureHandler;

impl crate::lawspec_abilities::lawspec_crypto::Signature for SlhDsaSignatureHandler {
    fn signingKeyPair(&self) -> @@SigningKeyPair@@ {
        let (public, secret) = primitives::slh_dsa_key_pair(&primitives::random_bytes(16), &primitives::random_bytes(16), &primitives::random_bytes(16));
        @@SigningKeyPair@@ { verifyingKey: @@VerifyingKey@@ { value: public }, signingKey: @@SigningKey@@ { value: secret } }
    }

    fn sign(&self, value0: @@SigningKey@@, value1: std::vec::Vec<u8>) -> @@SignatureBytes@@ {
        @@SignatureBytes@@ { value: primitives::slh_dsa_sign(&value0.value, &value1, &[]) }
    }

    fn verify(&self, value0: @@VerifyingKey@@, value1: std::vec::Vec<u8>, value2: @@SignatureBytes@@) -> bool {
        primitives::slh_dsa_verify(&value0.value, &value1, &value2.value, &[])
    }
}

/// AES-256-GCM, a fresh random nonce per message.
#[derive(Default)]
pub struct AeadHandler;

impl crate::lawspec_abilities::lawspec_crypto::Aead for AeadHandler {
    fn aeadKey(&self) -> @@AeadKey@@ {
        @@AeadKey@@ { value: primitives::random_bytes(32) }
    }

    fn deriveAeadKey(&self, value0: @@SharedSecret@@, value1: std::vec::Vec<u8>) -> @@AeadKey@@ {
        let mut material = value0.value.clone();
        material.extend_from_slice(&value1);
        @@AeadKey@@ { value: primitives::shake256(&material, 32) }
    }

    fn seal(&self, value0: @@AeadKey@@, value1: std::vec::Vec<u8>, value2: std::vec::Vec<u8>) -> @@Sealed@@ {
        let mut sealed = primitives::random_bytes(12);
        let body = primitives::aes_256_gcm_encrypt(&value0.value, &sealed, &value1, &value2);
        sealed.extend_from_slice(&body);
        @@Sealed@@ { value: sealed }
    }

    fn unseal(&self, value0: @@AeadKey@@, value1: @@Sealed@@, value2: std::vec::Vec<u8>) -> std::option::Option<std::vec::Vec<u8>> {
        if value1.value.len() < 12 {
            return None;
        }
        primitives::aes_256_gcm_decrypt(&value0.value, &value1.value[..12], &value1.value[12..], &value2)
    }
}
