-- | Erlang tokens and names shared by the BEAM emitters. Source text is never
-- reparsed for formatting, and user text never becomes an unescaped token.
-- ref:DEC-readable-output-default ref:DEC-idiomatic-generated-types
module LawSpec.BeamCode
  ( atom, binary, string, array, tuple, record, call, remote, lambda, apply
  , function, moduleDoc, userModuleDoc, sequenceDoc, snake, moduleName, functionName
  , typeReference, reference, literal, json, value, nativeType, dataNames
  , nativeModule, nativeFunction, nativeName, pascal, elixirDataModule, elixirFields, gleamPath, gleamName
  , nativeCall
  ) where

import qualified LawSpec.Code.Doc as D
import qualified LawSpec.Core as C
import qualified LawSpec.Core.Schema as S
import qualified LawSpec.Core.Value as V
import LawSpec.Core.Types (freeExistentials)
import LawSpec.Scalar (Scalar(..), primitive, family, Family(..), integerBounds)
import Data.Char (isAscii, isAlphaNum, isUpper, isLower, isDigit, toLower, toUpper, ord)
import Data.List (intercalate, nub)
import qualified Data.Aeson as A
import qualified Data.Aeson.Key as K
import qualified Data.Aeson.KeyMap as KM
import qualified Data.Text as T
import Data.Foldable (toList)
import qualified Data.ByteString.Lazy.Char8 as B
import Numeric (showHex)
import Control.Monad (unless)

-- | Quoting atoms also admits Erlang keywords as declaration names. No runtime
-- atom is created from a specification or a received value.
atom :: String -> D.Doc
atom name = D.text (if plain name then name else quote '\'' name)
  where
    plain (c:cs) = c `elem` ['a'..'z'] && all (\x -> isAscii x && (isAlphaNum x || x `elem` ("_@" :: String))) cs && name `notElem`
      words "after begin case try cond catch andalso orelse end fun if let of receive when bnot not div rem band and bor bxor bsl bsr or xor maybe else"
    plain [] = False

string :: String -> D.Doc
string = D.text . quote '"'

binary :: String -> D.Doc
binary s = D.text "<<" <> string s <> D.text "/utf8>>"

quote :: Char -> String -> String
quote delimiter s = delimiter : concatMap escape s ++ [delimiter]
  where
    escape c | c == delimiter || c == '\\' = ['\\', c]
    escape '\n' = "\\n"
    escape '\r' = "\\r"
    escape '\t' = "\\t"
    escape c | ord c < 32 || ord c >= 127 = "\\x{" ++ showHex (ord c) "}"
    escape c = [c]

array, tuple :: [D.Doc] -> D.Doc
array = D.delimit 4 "[" "]"
tuple = D.delimit 4 "{" "}"

record :: [(D.Doc,D.Doc)] -> D.Doc
record fields = D.delimit 4 "#{" "}" [a <> D.text " => " <> b | (a,b) <- fields]

call :: String -> [D.Doc] -> D.Doc
call name args = atom name <> D.delimit 4 "(" ")" args

remote :: String -> String -> [D.Doc] -> D.Doc
remote owner name args = atom owner <> D.text ":" <> call name args

nativeCall :: String -> [String] -> [D.Doc] -> Either String D.Doc
nativeCall target parts values = do
  unless (length parts >= 2 && (target /= "erlang" || length parts == 2))
    (Left "BEAM native function references require a module and a function")
  let owner = case target of
        "erlang" -> intercalate "." (init parts)
        "elixir" -> "Elixir." ++ intercalate "." (init parts)
        _ -> intercalate "@" (init parts)
  unless (owner `notElem` ["lawspec_native_bindings","lawspec_native_generators","lawspec@native_constructors","lawspec@native_handlers","lawspec_abilities"])
    (Left "native function shadows generated BEAM binding support")
  pure (remote owner (last parts) values)

lambda :: [D.Doc] -> D.Doc -> D.Doc
lambda args body = D.group (D.text "fun" <> D.delimit 4 "(" ")" args <>
  D.text " ->" <> D.nest 4 (D.softline <> body) <> D.softline <> D.text "end")

apply :: D.Doc -> [D.Doc] -> D.Doc
apply f args = D.text "(" <> f <> D.text ")" <> D.delimit 4 "(" ")" args

sequenceDoc :: [D.Doc] -> D.Doc
sequenceDoc = D.joinWith (D.text "," <> D.softline)

function :: String -> [D.Doc] -> [D.Doc] -> D.Doc
function name args body = D.group (call name args <> D.text " ->" <>
  D.nest 4 (D.softline <> sequenceDoc body) <> D.text ".")

moduleDoc :: String -> [(String,Int)] -> [D.Doc] -> D.Doc
moduleDoc = moduleHeader "%% Generated by LawSpec. Do not edit."

userModuleDoc :: String -> [(String,Int)] -> [D.Doc] -> D.Doc
userModuleDoc = moduleHeader "%% User-owned LawSpec adapter. Implement these functions."

moduleHeader :: String -> String -> [(String,Int)] -> [D.Doc] -> D.Doc
moduleHeader header name exports body = D.text header <> D.hardline <>
  D.text "-module(" <> atom name <> D.text ")." <> D.hardline <>
  D.text "-export(" <> array [atom n <> D.text ("/" ++ show arity) | (n,arity) <- exports] <>
  D.text ")." <> D.hardline <> D.hardline <>
  D.joinWith (D.hardline <> D.hardline) body <> D.hardline

-- | Both camelCase and acronym names get ordinary snake_case spellings.
-- Collisions are diagnosed by the caller after this final normalization.
snake :: String -> String
snake s = intercalate "_" . filter (not . null) . split $ go Nothing s
  where
    go _ [] = []
    go previous (c:rest)
      | not (isAscii c && isAlphaNum c) = '_' : go Nothing rest
      | otherwise = (if boundary previous c rest then "_" else "") ++ [toLower c] ++ go (Just c) rest
    boundary (Just p) c rest = isUpper c && (isLower p || isDigit p ||
      isUpper p && case rest of n:_ -> isLower n; _ -> False)
    boundary _ _ _ = False
    split text = case break (== '_') text of (a,[]) -> [a]; (a,_:b) -> a : split b

moduleName :: C.Id -> String
moduleName = snake . C.idText

functionName :: C.Declaration -> String
functionName declaration = case snake (C.declarationName declaration) of
  "module_info" -> "lawspec_module_info"
  name -> name

-- | Elixir modules retain namespaces; their VM names carry the Elixir prefix.
nativeModule :: String -> C.Unit -> String
nativeModule "elixir" = ("Elixir." ++) . intercalate "." . map pascal . splitDot . C.idText . C.unitId
  where splitDot s = case break (== '.') s of (a,[]) -> [a]; (a,_:b) -> a : splitDot b
nativeModule "gleam" = map (\c -> if c == '/' then '@' else c) . gleamPath . C.unitId
nativeModule _ = moduleName . C.unitId

nativeFunction :: String -> C.Declaration -> String
nativeFunction target = nativeName target . functionName

nativeName :: String -> String -> String
nativeName "elixir" name = case name of
  n | n `elem` words "after alias and case catch cond def defmodule do else end false fn for if import in nil not or quote raise receive require rescue super true try unless unquote use when with __info__" -> n ++ "_lawspec"
  n -> n
nativeName "gleam" name = gleamName name
nativeName _ name = name

gleamPath :: C.Id -> String
gleamPath = intercalate "/" . map (gleamName . snake) . splitDot . C.idText
  where splitDot s = case break (== '.') s of (a,[]) -> [a]; (a,_:b) -> a : splitDot b

gleamName :: String -> String
gleamName n | n `elem` words "as assert auto case const delegate derive echo else fn if implement import let opaque panic pub test todo type use" = n ++ "_lawspec"
gleamName n = n

pascal :: String -> String
pascal = concatMap cap . words . map (\c -> if c == '_' then ' ' else c) . snake
  where cap [] = []; cap (c:cs) = toUpper c : cs

elixirDataModule :: String -> String
elixirDataModule = ("LawSpec.Data." ++) . pascal

elixirFields :: C.DataDeclaration -> C.DataConstructor -> [String]
elixirFields d c = map (snake . C.binderName) (C.constructorFields c) ++
  ["lawspec_type_" ++ show i | (i,_) <- zip [0::Int ..] (freeExistentials d c)]

-- | Type parameters stay positional in runtime metadata.
reference :: S.TypeRef -> D.Doc
reference (S.Parameter i) = tuple [atom "parameter", D.text (show i)]
reference (S.Named n args) = tuple [binary n, array (map reference args)]

typeReference :: C.Type -> Either String D.Doc
typeReference ty = reference <$> S.typeReference [] ty

-- | Lossless wire leaves are emitted as Erlang literals. JSON object keys are
-- binaries, including keys unknown to the runtime; none intern new atoms.
json :: A.Value -> D.Doc
json j = case j of
  A.Object fields -> record [(binary (K.toString k),json v) | (k,v) <- KM.toAscList fields]
  A.Array xs -> array (map json (toList xs))
  A.String s -> binary (T.unpack s)
  A.Number n -> D.text (B.unpack (A.encode n))
  A.Bool b -> atom (if b then "true" else "false")
  A.Null -> atom "null"

literal :: D.Doc -> Scalar -> D.Doc
literal symbols s = case s of
  SInteger _ n -> D.text (show n)
  SCharacter _ n -> D.text (show n)
  SBool b -> atom (if b then "true" else "false")
  _ -> remote "lawspec_beam_scalar" "literal" [json (A.toJSON s),symbols]

value :: D.Doc -> V.Value -> D.Doc
value symbols v = case v of
  V.ScalarValue s -> literal symbols s
  V.DataValue _ (C.Id "List::Nil") [] -> array []
  V.DataValue _ (C.Id "List::Cons") [h,t] ->
    D.text "[" <> value symbols h <> D.text " | " <> value symbols t <> D.text "]"
  V.DataValue _ tag fields -> tuple [atom "ls_data",binary (C.idText tag),array (map (value symbols) fields)]
  V.PresenceValue (C.Constructor n _) item -> tuple [atom "ls_presence",binary n,
    maybe (atom "none") (\x -> tuple [atom "some",value symbols x]) item]
  V.PresenceValue _ _ -> error "non-constructor presence in checked Core"

-- | A program has one data module. Ambiguous short names are qualified by
-- their resolved unit, and a remaining collision is reported before emission.
dataNames :: [C.DataDeclaration] -> Either String [(C.Id,String)]
dataNames declarations = do
  let shorts = [(C.dataId d,snake (C.dataName d)) | d <- declarations]
      reservedTypes = words "any none no_return atom map pid port reference tuple integer int float number binary bitstring bit_array boolean bool char string nonempty_string list nonempty_list improper_list nonempty_improper_list maybe_improper_list nonempty_maybe_improper_list byte arity identifier iodata iolist mfa module node timeout fun function term nothing just left right some non_null null undefined ok nil true false result utf_codepoint charlist nonempty_charlist as_boolean"
      types = [(identity, if length (filter ((== n) . snd) shorts) > 1 || n `elem` reservedTypes
        then snake (C.idText identity) else n) | (identity,n) <- shorts]
      constructors = [(C.constructorId c, if length (C.dataConstructors d) == 1 then n
        else n ++ "_" ++ snake (C.constructorName c))
        | d <- declarations, Just n <- [lookup (C.dataId d) types], c <- C.dataConstructors d]
      duplicates xs = [n | n <- nub (map snd xs), length (filter ((== n) . snd) xs) > 1]
      names = map snd types
      tags = map snd constructors
  if any (\n -> null n || length n > 255) (names ++ tags)
    then Left "BEAM data name is empty or exceeds the Erlang atom limit"
    else if length names /= length (nub names) || length tags /= length (nub tags)
    then Left ("colliding BEAM data names: " ++ show (duplicates (types ++ constructors)))
    else pure (types ++ constructors)

-- | Native Erlang interfaces use tuples, binaries, lists and bounded integers.
-- IEEE values are opaque bit-preserving wrappers, including infinity and NaN.
nativeType :: Int -> [(C.Id,String)] -> [(C.Id,String)] -> C.Type -> Either String D.Doc
nativeType bits names parameters ty = case ty of
  C.TypeVariable identity -> maybe (Left "unbound BEAM native type parameter") (Right . D.text) (lookup identity parameters)
  C.Constructor n args -> do
    ts <- mapM argument args
    case (n,ts) of
      ("List",[t]) -> pure (array [t])
      ("Maybe",[t]) -> pure (union [atom "nothing",tuple [atom "just",t]])
      ("Either",[a,b]) -> pure (union [tuple [atom "left",a],tuple [atom "right",b]])
      ("Nullable",[t]) -> pure (union [atom "null",tuple [atom "non_null",t]])
      ("Optional",[t]) -> pure (union [atom "none",tuple [atom "some",t]])
      (_,[]) | Just p <- primitive n -> pure $ case family p of
        IntegerFamily -> case integerBounds bits n of
          Just (lo,hi) -> D.text (show lo ++ ".." ++ show hi)
          Nothing -> call (if n == "BigUInt" then "non_neg_integer" else "integer") []
        Boolean -> call "boolean" []
        Floating -> remote "lawspec_beam_scalar" "ieee" []
        Complex -> remote "lawspec_beam_scalar" "complex" []
        Exact -> remote "lawspec_beam_scalar" (map toLower n) []
        Character -> call "non_neg_integer" []
        Sequence -> if n `elem` ["Text","Bytes"] then call "binary" [] else array [call "non_neg_integer" []]
        Identity -> remote "lawspec_beam_scalar" "symbol" []
        Absence -> atom (case n of "Unit" -> "ok"; "Null" -> "null"; _ -> "undefined")
      _ -> maybe (Left ("no BEAM native type: " ++ n))
        (\name -> pure (remote "lawspec_data" name ts)) (lookup (C.Id n) names)
  C.Arrow _ _ -> Left "function-valued BEAM data is unsupported"
  where
    argument (C.TypeArgument t) = nativeType bits names parameters t
    argument (C.IndexArgument _) = Left "unerased BEAM type index"
    union = D.joinWith (D.text " | ")
