module LawSpec.CoreScalarEmit (scalarEmit, typeKey) where
import LawSpec.Backend
import LawSpec.Common
import LawSpec.Testing
import qualified LawSpec.Core as C
import LawSpec.Scalar
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T
import Data.List (intercalate, isPrefixOf, isInfixOf)
import Control.Monad (unless)

q :: String -> String
q = T.unpack . T.decodeUtf8 . encode
json :: Scalar -> String
json = T.unpack . T.decodeUtf8 . encode
typeKey :: Type -> String
typeKey (Applied n t) = n ++ " " ++ typeKey t
typeKey t = prettyType t
scalarEmit :: Int -> String -> Unit -> [Expanded] -> Either [Diagnostic] [Artifact]
scalarEmit bits target u allLaws = do
  unless (target `elem` ["python","javascript","typescript"]) (Left [Diagnostic "target-runtime" ("portable scalar runtime is not implemented for " ++ target) Nothing])
  tests <- concat <$> mapM lawTests (zip [0 :: Int ..] ls)
  wrappers <- concat <$> mapM contractWrapper (contracts u)
  let completeHeader = if py || "fc." `isInfixOf` tests then testHeader else unlines (filter (/= "import fc from 'fast-check';") (lines testHeader))
  pure [Artifact stubPath stub "user" "source",Artifact testPath (completeHeader ++ testHelpers ++ wrappers ++ tests) "generated" "test"]
  where
    py = target == "python"
    ts = target == "typescript"
    ext = if py then ".py" else if ts then ".ts" else ".mjs"
    parts = split (unitName u)
    slash = intercalate "/" parts
    stubPath = "src/" ++ slash ++ ext
    testPath = (if py then "tests/test_" else "test/") ++ intercalate "_" parts ++ (if py then "_lawspec" else ".lawspec") ++ (if py then ".py" else ".test" ++ ext)
    ls = filter ((== unitName u) . owner) allLaws
    runtimeImport = if py then "import lawspec_runtime as ls\n" else "import * as ls from '../src/lawspec_runtime." ++ (if ts then "js" else "mjs") ++ "';\n"
    testHeader = (if ts then "// @ts-nocheck\n" else "") ++ (if py then "#" else "//") ++ " Generated by LawSpec.\n" ++ runtimeImport ++ if py
      then "import json\nfrom hypothesis import given, settings, strategies as st\n" ++ (if null (functions u) then "" else "import " ++ unitName u ++ " as impl\n")
      else "import {test} from 'node:test';\nimport assert from 'node:assert/strict';\nimport fc from 'fast-check';\nimport * as impl from '../src/" ++ slash ++ (if ts then ".js" else ".mjs") ++ "';\n"
    testHelpers = if py then unlines
      ["def _lawspec_assert(context, actual, expected, ta, tb):", "  try:", "    a, b = actual(), expected()", "    assert ls.equal(a, b, ta, tb), f'{context} | actual={a!r}, expected={b!r}'", "  except Exception as error:", "    raise AssertionError(f'{context}: {error}') from error", ""]
      else "function _lawspecAssert(context, actual, expected, ta, tb) { try { const a = actual(), b = expected(); assert.ok(ls.equal(a,b,ta,tb), `${context} | actual=${String(a)}, expected=${String(b)}`); } catch(error) { throw new Error(`${context}: ${error.message}`, {cause:error}); } }\n"
    native (Named n)
      | py = case n of
          "Bytes" -> "bytes"; "Bool" -> "bool"; "Text" -> "str"; "Char" -> "str"; "Decimal" -> "ls.Decimal"; "Rational" -> "ls.Fraction"
          "Float32" -> "float"; "Float64" -> "float"; "Complex64" -> "complex"; "Complex128" -> "complex"
          "Symbol" -> "ls.Symbol"; "Unit" -> "None"; _ | isInteger n || n `elem` ["CodePoint","CodeUnit16"] -> "int"
          _ | n `elem` ["Unit","Null","Undefined"] -> "ls.Absence"
          _ -> "ls.Raw"
      | otherwise = case n of
          "Bytes" -> "Uint8Array"; "Bool" -> "boolean"; "Text" -> "string"; "Char" -> "string"; "Symbol" -> "symbol"
          "Integer" -> "number | bigint"; "Null" -> "null"; "Undefined" -> "undefined"; "Unit" -> "void"
          _ | isInteger n -> if n `elem` ["Int8","Int16","Int32","UInt8","UInt16","UInt32"] then "number" else "bigint"
          _ | n `elem` ["Float32","Float64","CodePoint","CodeUnit16"] -> "number"
          _ -> "unknown"
    native _ = if py then "ls.Presence" else "unknown"
    stub = (if py then "#" else "//") ++ " User-owned LawSpec adapter.\n" ++ (if py then "import lawspec_runtime as ls\n" else "") ++ concatMap stubFn (functions u)
    nativeArg t = if t == Named "Integer" then (if py then "int" else "bigint") else if t == Named "Unit" then (if py then "ls.Absence" else "unknown") else native t
    stubFn (n,t) = let (args,r) = functionType t; args' = ["value" ++ show i ++ (if py || ts then ": " ++ nativeArg a else "") | (i,a) <- zip [0 :: Int ..] args] in
      if py then "def " ++ n ++ "(" ++ intercalate ", " args' ++ ") -> " ++ native r ++ ":\n    raise NotImplementedError(" ++ q n ++ ")\n"
      else "export function " ++ n ++ "(" ++ intercalate ", " args' ++ ")" ++ (if ts then ": " ++ native r else "") ++ " { throw new Error(" ++ q n ++ "); }\n"
    call n args = "ls." ++ n ++ "(" ++ intercalate ", " args ++ ")"
    lit s = call "literal" [if py then "json.loads(" ++ q (json s) ++ ")" else json s,"symbols"]
    converted t e = call "convert" [e,q (typeKey t),show bits]
    render term = case C.expressionNode term of
      C.Local n -> localName n
      C.Constant s -> lit s
      C.Convert C.CheckedArgument t e -> converted t (render e)
      C.Convert C.Explicit t e -> call "helper" [q (typeKey t),"[" ++ render e ++ "]","[" ++ q (typeKey (expressionType e)) ++ "]",show bits]
      C.ShortCircuit op a b -> "(" ++ render a ++ (if py then if op == C.And then " and " else " or " else if op == C.And then " && " else " || ") ++ render b ++ ")"
      C.Unary C.Not a -> "(" ++ (if py then "not " else "!") ++ render a ++ ")"
      C.Binary op _ a b -> call "binary" [q (C.binaryName op),render a,render b,q (typeKey (expressionType a)),q (typeKey (expressionType b))]
      C.Unary C.Negate a -> call "helper" [q "negate","[" ++ render a ++ "]","[" ++ q (typeKey (expressionType a)) ++ "]",show bits]
      C.Helper builtin args -> call "helper" [q (C.builtinName builtin),"[" ++ intercalate ", " (map render args) ++ "]","[" ++ intercalate ", " (map (q . typeKey . expressionType) args) ++ "]",show bits]
      C.ExternalCall decl args ->
        let n = declarationName decl
            t = expressionType term
            values = [converted (expressionType a) (render a) | a <- args]
            invocation = "impl." ++ n ++ "(" ++ intercalate ", " values ++ ")"
        in if n `elem` map contractName (contracts u)
          then "_lawspec_call_" ++ n ++ "(" ++ intercalate ", " ("symbols":values) ++ ")"
          else call "validate" [if t == Named "Unit" then call (if py then "unit_result" else "unitResult") [invocation] else invocation,q (typeKey t),show bits]
    assertionCode indent context proposition = case proposition of
      AssertAll ps -> concat <$> mapM (assertionCode indent context) ps
      AssertImplies g body -> do
        bs <- assertionCode (indent ++ "  ") context body
        pure $ indent ++ "if " ++ (if py then render g ++ ":\n" else "(" ++ render g ++ ") {\n") ++ bs ++ (if py then "" else indent ++ "}\n")
      AssertEqual a b ->
        let arguments = [q (context ++ " | expect " ++ propositionText proposition),(if py then "lambda: " else "() => ") ++ render a,(if py then "lambda: " else "() => ") ++ render b,q (typeKey (expressionType a)),q (typeKey (expressionType b))]
        in pure $ indent ++ (if py then "_lawspec_assert(" else "_lawspecAssert(") ++ intercalate ", " arguments ++ (if py then ")\n" else ");\n")
    symbolsLine indent = indent ++ "symbols = {}\n"
    jsSymbols indent = indent ++ "const symbols = new Map();\n"
    freshSymbols = if py then symbolsLine else jsSymbols
    block label name' body = if py then "def " ++ name' ++ "():\n" ++ freshSymbols "  " ++ body ++ "\n" else "test(" ++ q label ++ ", () => {\n" ++ freshSymbols "  " ++ body ++ "});\n"
    assign n v = "  " ++ (if py then n ++ " = " ++ v ++ "\n" else "const " ++ n ++ " = " ++ v ++ ";\n")
    lawTests (index,e) = do
      let label = owner e ++ "::" ++ name e; prefix = "test_law" ++ show index
      exampleTests <- concat <$> mapM (\(j,ex) -> do
        let values = [assign n (render v) | (n,v) <- bindings ex]
        checks <- concat <$> mapM (assertionCode "  " (label ++ " example " ++ exampleName ex)) (expectations ex)
        lawCheck <- assertionCode "  " label (assertion e)
        pure (block (label ++ " example: " ++ exampleName ex) (prefix ++ "_example" ++ show j) (concat values ++ checks ++ lawCheck))) (zip [0 :: Int ..] (examples (original e)))
      let finite = finiteCases e
          cases' = maybe (boundaryCases e) id finite
      boundaryTests <- concat <$> mapM (\(j,vs) -> do
        checks <- assertionCode "  " (label ++ " boundary " ++ show j) (assertion e)
        pure (block label (prefix ++ "_boundary" ++ show j) (concat [assign (inputId inp) (lit v) | (inp,v) <- zip (inputs e) vs] ++ checks))) (zip [0 :: Int ..] cases')
      body <- assertionCode "  " (label ++ " property") (assertion e)
      let gs = map (generator . inputType) (inputs e)
          ns = map inputId (inputs e)
          propertyTest = if py then "@given(" ++ intercalate ", " gs ++ ")\ndef " ++ prefix ++ "_property(" ++ intercalate ", " ns ++ "):\n" ++ freshSymbols "  " ++ body
            else "test(" ++ q (label ++ " property") ++ ", () => fc.assert(fc.property(" ++ intercalate ", " gs ++ ", (" ++ intercalate ", " ns ++ ") => {\n" ++ freshSymbols "  " ++ body ++ "})));\n"
      refined <- refinedProperty prefix label e body
      pure (metadata (if py then "#" else "//") e ++ exampleTests ++ boundaryTests ++ if maybe False (const True) finite then "" else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract" then refined else propertyTest)
    contractWrapper c = do
      let args = contractArguments c
          (resultName,resultType) = contractResult c
          conjunction [] = if py then "True" else "true"
          conjunction xs = intercalate (if py then " and " else " && ") ["(" ++ x ++ ")" | x <- xs]
          line context ps = "  " ++ call (if py then "require_contract" else "requireContract") [conjunction ps,q context] ++ (if py then "\n" else ";\n")
          invocation = "impl." ++ contractName c ++ "(" ++ intercalate ", " [converted t n | (n,t) <- args] ++ ")"
          value = call "validate" [if resultType == Named "Unit" then call (if py then "unit_result" else "unitResult") [invocation] else invocation,q (typeKey resultType),show bits]
          pre = map render (contractPreconditions c)
          post = map render (contractPostconditions c)
      pure $ (if py then "def " else "function ") ++ "_lawspec_call_" ++ contractName c ++ "(" ++ intercalate ", " ("symbols":map fst args) ++ (if py then "):\n" else ") {\n") ++
        line (contractName c ++ " precondition: " ++ intercalate " && " (map prettyExpr (contractPreconditions c))) pre ++ assign resultName value ++
        line (contractName c ++ " postcondition: " ++ intercalate " && " (map prettyExpr (contractPostconditions c))) post ++ "  return " ++ resultName ++ (if py then "\n\n" else ";\n}\n")
    refinedProperty prefix label e body = do
      ds <- mapM (domainCode e) (zip [0::Int ..] (generationPlan e))
      let cfg = generation e
          check = if py then "  def _check(_values):\n" ++ concat ["    " ++ inputId inp ++ " = _values[" ++ show j ++ "]\n" | (j,inp) <- zip [0::Int ..] (inputs e)] ++ unlines ["  " ++ line | line <- lines body]
                  else "  const _check = (_values) => {\n" ++ concat ["    const " ++ inputId inp ++ " = _values[" ++ show j ++ "];\n" | (j,inp) <- zip [0::Int ..] (inputs e)] ++ body ++ "  };\n"
          invoke = "  " ++ call (if py then "refined_case" else "refinedCase") ["[" ++ intercalate ", " ds ++ "]","_seed",show (maxAttempts cfg),show (maxShrinks cfg),"_check",q (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))] ++ (if py then "\n" else ";\n")
      pure $ if py then "@settings(max_examples=" ++ show (cases cfg) ++ ")\n@given(st.integers(min_value=0,max_value=2147483647))\ndef " ++ prefix ++ "_property(_seed):\n" ++ freshSymbols "  " ++ check ++ invoke
        else "test(" ++ q (label ++ " property") ++ ", () => fc.assert(fc.property(fc.integer({min:0,max:2147483647}), (_seed) => {\n" ++ freshSymbols "  " ++ check ++ invoke ++ "}), {numRuns:" ++ show (cases cfg) ++ "}));\n"
    domainCode e (index,plan) = do
      let inp = domainInput plan; previous = take index (inputs e)
          boundNames xs = intercalate ", " (map inputId xs)
          lambda xs seed expression' = if py then "lambda _values" ++ (if seed then ", _seed" else "") ++ ": (lambda " ++ boundNames xs ++ ": " ++ expression' ++ ")(*_values)"
             else "([" ++ boundNames xs ++ "]" ++ (if seed then ", _seed" else "") ++ ") => " ++ expression'
      let bs = ["[" ++ q op ++ ", " ++ render v ++ "]" | (op,v) <- domainBounds plan]
          hints = map render (generatorHints plan)
          ps = map render (inputRefinements inp)
      let candidates = call (if py then "domain_candidates" else "domainCandidates") [q (typeKey (inputType inp)),"_seed",show bits,"[" ++ intercalate ", " bs ++ "]","[" ++ intercalate ", " (map lit (generatorBoundaries plan) ++ hints) ++ "]"]
          predicate = if null ps then (if py then "True" else "true") else intercalate (if py then " and " else " && ") ["(" ++ p ++ ")" | p <- ps]
      pure ("[" ++ lambda previous True candidates ++ ", " ++ lambda (previous++[inp]) False predicate ++ "]")
    boundaries (Applied n t) = SPresent n Nothing : map (SPresent n . Just) (boundaries t)
    boundaries (Named n) = scalarBoundaries bits n
    boundaries _ = []
    generator t@(Applied n inner) = if py then "st.one_of(st.just(ls.Presence(" ++ q n ++ ", False)), " ++ generator inner ++ ".map(lambda x: ls.Presence(" ++ q n ++ ", True, x)))"
      else "fc.oneof(fc.constant(new ls.Presence(" ++ q n ++ ", false)), " ++ generator inner ++ ".map(x => new ls.Presence(" ++ q n ++ ", true, x)))"
    generator t@(Named n)
      | isInteger n = let b = integerBounds bits n; lo = maybe (if n == "BigUInt" then 0 else -2^(256::Int)) fst b; hi = maybe (2^(256::Int)) snd b in
          if py then "st.integers(min_value=" ++ show lo ++ ", max_value=" ++ show hi ++ ")"
          else "fc.bigInt({min:" ++ show lo ++ "n,max:" ++ show hi ++ "n}).map(x => ls.convert(x," ++ q n ++ "," ++ show bits ++ "))"
      | n == "Bool" = if py then "st.booleans()" else "fc.boolean()"
      | n == "Text" = if py then "st.text()" else "fc.array(fc.integer({min:0,max:1114111}).filter(x => x<55296 || x>57343),{maxLength:100}).map(xs => xs.map(x => String.fromCodePoint(x)).join(''))"
      | n `elem` ["Float32","Float64"] = if py then "st.floats(width=" ++ (if n == "Float32" then "32" else "64") ++ ")" else (if n == "Float32" then "fc.float()" else "fc.double()")
      | n == "Decimal" = if py then "st.tuples(st.integers(), st.integers(-20,20)).map(lambda v: ls.make_decimal(v[0],v[1]))" else "fc.tuple(fc.bigInt(),fc.integer({min:-20,max:20})).map(v => new ls.Decimal(v[0],v[1]))"
      | n == "Rational" = if py then "st.tuples(st.integers(),st.integers(min_value=1)).map(lambda v: ls.Fraction(v[0],v[1]))" else "fc.tuple(fc.bigInt(),fc.bigInt({min:1n})).map(v => new ls.Rational(v[0],v[1]))"
      | n `elem` ["Complex64","Complex128"] = let f = generator (Named (if n == "Complex64" then "Float32" else "Float64")) in if py then "st.tuples(" ++ f ++ "," ++ f ++ ").map(lambda v: complex(v[0],v[1]))" else "fc.tuple(" ++ f ++ "," ++ f ++ ").map(v => new ls.Complex(v[0],v[1]))"
      | n == "Char" = if py then "st.characters(blacklist_categories=('Cs',))" else "fc.integer({min:0,max:1114111}).filter(x => x<55296 || x>57343).map(x => String.fromCodePoint(x))"
      | n `elem` ["CodePoint","CodeUnit16"] = if py then "st.integers(0," ++ maximumUnit n ++ ")" else "fc.integer({min:0,max:" ++ maximumUnit n ++ "})"
      | n == "Bytes" = if py then "st.binary(max_size=100)" else "fc.array(fc.integer({min:0,max:255}),{maxLength:100}).map(v => new Uint8Array(v))"
      | n `elem` ["Bytes","CodePointText","Utf16Text"] = if py then "st.lists(st.integers(0," ++ maximumUnit n ++ "),max_size=100).map(lambda v: ls.Raw(" ++ q n ++ ",tuple(v)))" else "fc.array(fc.integer({min:0,max:" ++ maximumUnit n ++ "}),{maxLength:100}).map(v => new ls.Raw(" ++ q n ++ ",v))"
      | n == "Symbol" = if py then "st.text().map(ls.Symbol)" else "fc.string().map(x => Symbol(x))"
      | otherwise = if py then "st.sampled_from([" ++ intercalate ", " ["ls.literal(json.loads(" ++ q (json v) ++ "))" | v <- boundaries t] ++ "])"
          else "fc.constantFrom(" ++ intercalate ", " ["ls.literal(" ++ json v ++ ")" | v <- boundaries t] ++ ")"
    generator _ = error "non-scalar generator"
    maximumUnit n = if n == "Bytes" then "255" else if n `elem` ["CodeUnit16","Utf16Text"] then "65535" else "1114111"
    split s = case break (== '.') s of (a,[]) -> [a]; (a,_:b) -> a:split b
