module LawSpec.CoreNativeScalarEmit (nativeScalarEmit) where
import LawSpec.Backend
import LawSpec.Common
import LawSpec.Testing
import qualified LawSpec.Core as C
import LawSpec.Scalar
import LawSpec.RuntimeSources
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T
import Data.List (intercalate, isPrefixOf, isInfixOf)

q :: String -> String
q = T.unpack . T.decodeUtf8 . encode
key :: Type -> String
key (Applied n t) = n ++ " " ++ key t
key t = prettyType t
nativeScalarEmit :: Int -> String -> Unit -> [Expanded] -> Either [Diagnostic] [Artifact]
nativeScalarEmit bits target u allLaws = do
  tests <- concat <$> mapM lawTests (zip [0 :: Int ..] ls)
  wrappers <- concat <$> mapM contractWrapper (contracts u)
  let completeHeader = if hs then replace "spec :: Spec" (wrappers ++ "spec :: Spec") testHeader else if kt then replace "class " (wrappers ++ "class ") testHeader else (if go && not ("rapid.Check" `isInfixOf` tests) then replace "; \"pgregory.net/rapid\"" "" testHeader else testHeader) ++ wrappers
  pure ([Artifact stubPath stub "user" "source", Artifact testPath (completeHeader ++ tests ++ (if hs || go then "" else if kt then "})\n" else "}\n")) "generated" "test"] ++ [Artifact (intercalate "/" parts ++ "/lawspec_runtime.go") (replace "RUNTIME_PACKAGE" (last parts) (runtimeSource "go")) "generated" "source" | go])
  where
    kt = target == "kotlin"
    hs = target == "haskell"
    go = target == "go"
    parts = split (unitName u)
    cls = concatMap cap (splitOn '_' (last parts))
    pkg = intercalate "." (init parts)
    path = intercalate "/" (init parts ++ [cls])
    root = if kt then "kotlin" else "java"
    ext = if kt then ".kt" else ".java"
    stubPath | hs = "src/" ++ intercalate "/" (map hsPart parts) ++ ".hs"
             | go = intercalate "/" parts ++ "/adapter.go"
             | otherwise = "src/main/" ++ root ++ "/" ++ path ++ ext
    testPath | hs = "test/" ++ intercalate "/" (map hsPart parts) ++ "Spec.hs"
             | go = intercalate "/" parts ++ "/lawspec_test.go"
             | otherwise = "src/test/" ++ root ++ "/" ++ path ++ "LawSpecTest" ++ ext
    ls = filter ((== unitName u) . owner) allLaws
    header | go = "package " ++ last parts ++ "\n"
           | hs = "module " ++ intercalate "." (map hsPart parts) ++ " where\nimport LawSpecRuntime (Scalar, IntegerValue, integerValue)\nimport Data.Int\nimport Data.ByteString (ByteString)\nimport Data.Word\nimport Data.Text (Text)\nimport Data.Complex (Complex)\n"
           | otherwise = (if null pkg then "" else "package " ++ pkg ++ ";\n") ++ "import lawspec.runtime.LawSpecRuntime;\n" ++ (if kt then "" else "import lawspec.runtime.LawSpecRuntime.Value;\n")
    valueType = if go then "LawSpecValue" else if hs then "Scalar" else if kt then "LawSpecRuntime.Value" else "Value"
    stub | hs || go = (if hs then "--" else "//") ++ " User-owned LawSpec adapter.\n" ++ header ++ concatMap stubFn (functions u)
         | otherwise = "// User-owned LawSpec adapter.\n" ++ header ++ (if kt then "object " else "public final class ") ++ cls ++ " {\n" ++ concatMap stubFn (functions u) ++ "}\n"
    native t = maybe valueType id (nativeRepresentation target (key t))
    nativeArg t = if t == Named "Integer" then (if hs then "Integer" else if go then "*LawSpecBigInt" else "java.math.BigInteger") else if t == Named "Unit" && not hs then valueType else native t
    stubFn (n,t) = let (args,r) = functionType t; names = ["value" ++ show i | i <- [0 :: Int .. length args-1]] in
      if hs then n ++ " :: " ++ intercalate " -> " (map nativeArg args ++ [native r]) ++ "\n" ++ n ++ concatMap (const " _") args ++ " = error " ++ q (prettyType t) ++ "\n"
      else if go then "// " ++ prettyType t ++ "\nfunc " ++ cap n ++ "(" ++ intercalate ", " [x ++ " " ++ nativeArg a | (x,a) <- zip names args] ++ ") " ++ (if r == Named "Unit" then "" else native r) ++ " { panic(" ++ q n ++ ") }\n"
      else "  // " ++ prettyType t ++ "\n" ++ if kt then "  fun " ++ n ++ "(" ++ intercalate ", " [x ++ ": " ++ nativeArg a | (x,a) <- zip names args] ++ "): " ++ native r ++ " = TODO(" ++ q n ++ ")\n"
      else "  public static " ++ native r ++ " " ++ n ++ "(" ++ intercalate ", " [nativeArg a ++ " " ++ x | (x,a) <- zip names args] ++ ") { throw new UnsupportedOperationException(" ++ q (n ++ " -> " ++ prettyType r) ++ "); }\n"
    testHeader = testHeaderBase ++ (if hs || kt then "" else testHelpers)
    testHeaderBase | go = "// Generated by LawSpec.\n" ++ header ++ "import (\"testing\"; \"pgregory.net/rapid\")\n"
               | hs = "-- Generated by LawSpec.\nmodule " ++ intercalate "." (map hsPart parts) ++ "Spec (spec) where\nimport Test.Hspec\nimport Control.Exception (SomeException, catch, displayException)\nimport Test.Hspec.Hedgehog (hedgehog, modifyMaxSuccess)\nimport Hedgehog (forAll, evalIO, footnote)\nimport qualified Hedgehog.Gen as Gen\nimport qualified Hedgehog.Range as Range\nimport LawSpecRuntime (Scalar(..))\nimport qualified LawSpecRuntime as LS\nimport qualified " ++ intercalate "." (map hsPart parts) ++ " as Impl\n" ++ testHelpers ++ "spec :: Spec\nspec = do\n"
               | otherwise = "// Generated by LawSpec.\n" ++ header ++ if kt then "import io.kotest.core.spec.style.StringSpec\nimport io.kotest.property.checkAll\nimport io.kotest.property.Arb\nimport io.kotest.property.arbitrary.int\n" ++ testHelpers ++ "class " ++ cls ++ "LawSpecTest : StringSpec({\n" else "import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertTrue;\nimport java.util.*;\nimport org.jetbrains.jetCheck.Generator;\nimport org.jetbrains.jetCheck.PropertyChecker;\npublic final class " ++ cls ++ "LawSpecTest {\n"
    testHelpers
      | hs = "_lawspecAssert :: String -> Scalar -> Scalar -> IO ()\n_lawspecAssert context actual expected = catch action handler\n  where\n    action = if LS.equal actual expected then pure () else expectationFailure (context ++ \" | actual=\" ++ show actual ++ \" expected=\" ++ show expected)\n    handler :: SomeException -> IO ()\n    handler e = expectationFailure (context ++ \" | \" ++ displayException e)\n"
      | go = "func _lawspecAssert(t interface { Fatalf(string, ...any) }, context string, actual, expected func() LawSpecValue) { lsAssert(context,actual,expected) }\n"
      | kt = "private fun _lawspecAssert(context: String, actual: () -> LawSpecRuntime.Value, expected: () -> LawSpecRuntime.Value) { try { val a = actual(); val b = expected(); check(LawSpecRuntime.equal(a,b)) { \"$context | actual=$a expected=$b\" } } catch(error: Exception) { throw AssertionError(context, error) } }\n"
      | otherwise = "  private static void _lawspecAssert(String context, java.util.function.Supplier<Value> actual, java.util.function.Supplier<Value> expected) { try { var a = actual.get(); var b = expected.get(); assertTrue(LawSpecRuntime.equal(a,b), context + \" | actual=\" + a + \" expected=\" + b); } catch(RuntimeException error) { throw new AssertionError(context, error); } }\n"
    quote = if kt then concatMap (\c -> if c == '$' then "\\$" else [c]) . q else q
    call n args | hs = "(LS." ++ n ++ concatMap (\a -> " (" ++ a ++ ")") args ++ ")"
                | go = "ls" ++ cap n ++ "(" ++ intercalate ", " args ++ ")"
                | otherwise = "LawSpecRuntime." ++ n ++ "(" ++ intercalate ", " args ++ ")"
    arr xs | hs = "[" ++ intercalate ", " xs ++ "]"
           | go = "[]LawSpecValue{" ++ intercalate ", " xs ++ "}"
           | otherwise = (if kt then "arrayOf(" else "new Value[]{") ++ intercalate ", " xs ++ (if kt then ")" else "}")
    scalar s | hs = "(" ++ show s ++ ")"
             | otherwise = case s of
      SInteger t n -> call "integer" [q t,q (show n)]
      SBool b -> call "bool" [if b then "true" else "false"]
      SDecimal c e -> call "decimal" [q (show c),q (show e)]
      SRational n d -> call "rational" [q (show n),q (show d)]
      SFloat t bits' -> call "floating" [q t,q bits']
      SComplex t r i -> call "complex" [q t,scalar r,scalar i]
      SCharacter t c -> call "character" [q t,show c]
      SSequence t xs -> call "sequence" [q t,(if go then "[]int{" else if kt then "intArrayOf(" else "new int[]{") ++ intercalate "," (map show xs) ++ (if kt then ")" else "}")]
      SSymbol i d -> call "symbol" [quote i,quote d,"symbols"]
      SAbsent t -> call "absent" [q t]
      SPresent t v -> call "present" [q t,if go then maybe "nil" (\x -> "lsPointer(" ++ scalar x ++ ")") v else maybe "null" scalar v]
    convert t v = call "convert" [q (key t),v,show bits]
    render term = case C.expressionNode term of
      C.Local n -> localName n
      C.Constant s -> convert (expressionType term) (scalar s)
      C.Convert C.CheckedArgument t e -> convert t (render e)
      C.Convert C.Explicit t e -> call "helper" [q (key t),arr [render e],show bits]
      C.ShortCircuit op a b -> call "bool" ["(" ++ call "truth" [render a] ++ (if op == C.And then " && " else " || ") ++ call "truth" [render b] ++ ")"]
      C.Unary C.Not a -> call "bool" [(if hs then "not (" else "!(") ++ call "truth" [render a] ++ ")"]
      C.Binary op _ a b -> call "binary" [q (C.binaryName op),render a,render b]
      C.Unary C.Negate a -> call "helper" [q "negate",arr [render a],show bits]
      C.Helper builtin args -> call "helper" [q (C.builtinName builtin),arr (map render args),show bits]
      C.ExternalCall decl args ->
        let n = declarationName decl
            t = expressionType term
            values = [convert (expressionType a) (render a) | a <- args]
            callee = if hs then "Impl." ++ n else if go then cap n else cls ++ "." ++ n
            invocation = if hs then "(" ++ callee ++ concatMap (\a -> " (" ++ adapterArg a ++ ")") args ++ ")" else callee ++ "(" ++ intercalate ", " (map adapterArg args) ++ ")"
        in if n `elem` map contractName (contracts u)
          then if hs then "(_lawspec_call_" ++ n ++ concatMap (\v -> " (" ++ v ++ ")") values ++ ")" else "_lawspec_call_" ++ n ++ "(" ++ intercalate ", " ("symbols":values) ++ ")"
          else wrapResult t invocation
    wrapResult t invocation
      | t == Named "Unit" && not hs =
          if go then "func() LawSpecValue { " ++ invocation ++ "; return lsAbsent(\"Unit\") }()"
          else if kt then "run { " ++ invocation ++ "; LawSpecRuntime.absent(\"Unit\") }" else "LawSpecRuntime.unit(() -> " ++ invocation ++ ")"
      | otherwise = call "fromNative" [q (key t),invocation,show bits]
    adapterArg a = nativeValue (expressionType a) (render a)
    nativeValue t value | t == Named "Unit" && not hs = value
    nativeValue t value = case nativeRepresentation target (key t) of
      Nothing -> if go then "lsClone(" ++ convert t value ++ ")" else convert t value
      Just _ -> let nativeType = nativeArg t; converted = call "toNative" [q (key t),value,show bits] in
        if hs then converted else if go then converted ++ ".(" ++ nativeType ++ ")" else if kt then "(" ++ converted ++ " as " ++ nativeType ++ ")" else "((" ++ nativeType ++ ") " ++ converted ++ ")"
    assign n v | hs = "    let " ++ n ++ " = " ++ v ++ "\n"
               | go = "    " ++ n ++ " := " ++ v ++ "; _ = " ++ n ++ "\n"
               | otherwise = "    " ++ (if kt then "val " else "var ") ++ n ++ " = " ++ v ++ ";\n"
    code indent context proposition = case proposition of
      AssertAll ps -> concat <$> mapM (code indent context) ps
      AssertImplies g body -> do
        rest <- code (indent ++ "  ") context body
        pure (if hs then indent ++ "if " ++ call "truth" [render g] ++ " then do\n" ++ rest ++ indent ++ "else pure ()\n" else indent ++ "if (" ++ call "truth" [render g] ++ ") {\n" ++ rest ++ indent ++ "}\n")
      AssertEqual a b ->
        let av = render a; bv = render b; explanation = context ++ " | expect " ++ prettyExpr a ++ " = " ++ prettyExpr b in
        pure $ indent ++ if hs then "_lawspecAssert " ++ quote explanation ++ " (" ++ av ++ ") (" ++ bv ++ ")\n"
          else if go then "_lawspecAssert(t, " ++ quote explanation ++ ", func() LawSpecValue { return " ++ av ++ " }, func() LawSpecValue { return " ++ bv ++ " })\n"
          else if kt then "_lawspecAssert(" ++ quote explanation ++ ", { " ++ av ++ " }, { " ++ bv ++ " })\n"
          else "_lawspecAssert(" ++ quote explanation ++ ", () -> " ++ av ++ ", () -> " ++ bv ++ ");\n"
    block n body | hs = "  it " ++ q n ++ " $ do\n" ++ body
                 | go = "func Test" ++ cap n ++ "(t *testing.T) {\n    symbols := map[string]*lawSpecSymbol{}; _ = symbols\n" ++ body ++ "}\n"
                 | kt = "  " ++ q n ++ " {\n    val symbols = mutableMapOf<String, Any>();\n" ++ body ++ "  }\n"
                 | otherwise = "  @Test " ++ (if kt then "fun " ++ n ++ "()" else "void " ++ n ++ "()") ++ " {\n" ++ (if kt then "    val symbols = mutableMapOf<String, Any>();\n" else "    var symbols = new HashMap<String,Object>();\n") ++ body ++ "  }\n"
    boundaries (Named n) = scalarBoundaries bits n
    boundaries (Applied n t) = SPresent n Nothing : map (SPresent n . Just) (boundaries t)
    boundaries _ = []
    lawTests (i,e) = do
      let label = owner e ++ "::" ++ name e; fn = "law" ++ show i
      exs <- concat <$> mapM (\(j,ex) -> do
        let assignments = [assign n (render v) | (n,v) <- bindings ex]
        expectedChecks <- concat <$> mapM (code "    " (label ++ " example " ++ exampleName ex)) (expectations ex)
        lawCheck <- code "    " label (assertion e)
        pure (block (fn ++ "Example" ++ show j) (concat assignments ++ expectedChecks ++ lawCheck))) (zip [0 :: Int ..] (examples (original e)))
      let finite = finiteCases e
          cases' = maybe (boundaryCases e) id finite
      boundariesTests <- concat <$> mapM (\(j,vs) -> do
        check <- code "    " (label ++ " boundary " ++ show j) (assertion e)
        pure (block (fn ++ "Boundary" ++ show j) (concat [assign (inputId inp) (convert (inputType inp) (scalar v)) | (inp,v) <- zip (inputs e) vs] ++ check))) (zip [0 :: Int ..] cases')
      propertyCheck <- code "    " (label ++ " property") (assertion e)
      let assignments = concat [assign (inputId inp) (call "sample" [q (key (inputType inp)),if go then "int(seed) + " ++ show j else if hs then "seed + " ++ show j else "seed + " ++ show j,show bits]) | (j,inp) <- zip [0 :: Int ..] (inputs e)]
          propertyBody = assignments ++ propertyCheck
          propertyTest
            | hs = "  it " ++ q (label ++ " property") ++ " $ hedgehog $ do\n    seed <- forAll (Gen.int (Range.linear (-1000000) 1000000))\n    footnote " ++ q label ++ "\n    evalIO $ do\n" ++ unlines ["  " ++ l | l <- lines propertyBody]
            | go = "func Test" ++ cap fn ++ "Property(t *testing.T) { rapid.Check(t, func(t *rapid.T) {\n    seed := rapid.Int32().Draw(t, \"seed\"); _ = seed\n    symbols := map[string]*lawSpecSymbol{}; _ = symbols\n" ++ propertyBody ++ "}) }\n"
            | kt = "  " ++ q (label ++ " property") ++ " { checkAll(Arb.int()) { seed ->\n    val symbols = mutableMapOf<String, Any>();\n" ++ propertyBody ++ "  } }\n"
            | otherwise = "  @Test void " ++ fn ++ "Property() { PropertyChecker.forAll(Generator.integers(), seed -> {\n    var symbols = new HashMap<String,Object>();\n" ++ propertyBody ++ "    return true;\n  }); }\n"
      refined <- refinedProperty fn label e propertyCheck
      pure (metadata (if hs then "--" else "//") e ++ exs ++ boundariesTests ++ if maybe False (const True) finite then "" else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract" then refined else propertyTest)
    conjunction [] = if hs then "True" else "true"
    conjunction xs = intercalate " && " ["(" ++ x ++ ")" | x <- xs]
    contractWrapper c = do
      let args = contractArguments c
          (rn,rt) = contractResult c
          invoke = (if hs then "Impl." else if go then "" else cls ++ ".") ++ (if go then cap (contractName c) else contractName c) ++
            (if hs then concatMap (\(n,t) -> " (" ++ nativeValue t n ++ ")") args
             else "(" ++ intercalate ", " [nativeValue t n | (n,t) <- args] ++ ")")
          result = wrapResult rt invoke
          context stage ps = contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps)
          symbolParam = if go then "symbols map[string]*lawSpecSymbol" else if kt then "symbols: MutableMap<String, Any>" else "Map<String,Object> symbols"
          params = symbolParam:[if go then n ++ " LawSpecValue" else if kt then n ++ ": LawSpecRuntime.Value" else "Value " ++ n | (n,_) <- args]
      let pre = [call "truth" [render v] | v <- contractPreconditions c]
          post = [call "truth" [render v] | v <- contractPostconditions c]
      let preContext = context "precondition" (contractPreconditions c); postContext = context "postcondition" (contractPostconditions c)
      pure $ if hs then "_lawspec_call_" ++ contractName c ++ " :: " ++ intercalate " -> " (replicate (length args+1) "Scalar") ++ "\n_lawspec_call_" ++ contractName c ++ concatMap ((" " ++) . fst) args ++ " =\n  LS.contract " ++ quote preContext ++ " (" ++ conjunction pre ++ ") $\n    let " ++ rn ++ " = " ++ result ++ "\n    in " ++ rn ++ " `seq` LS.contract " ++ quote postContext ++ " (" ++ conjunction post ++ ") " ++ rn ++ "\n"
        else (if go then "func " else if kt then "private fun " else "  private static Value ") ++ "_lawspec_call_" ++ contractName c ++ "(" ++ intercalate ", " params ++ ")" ++ (if go then " LawSpecValue" else if kt then ": LawSpecRuntime.Value" else "") ++ " {\n" ++
          "    " ++ call "requireContract" [conjunction pre,quote preContext] ++ ";\n" ++ assign rn result ++ "    " ++ call "requireContract" [conjunction post,quote postContext] ++ ";\n    return " ++ rn ++ ";\n  }\n"
    domainCode e (index,plan) = do
      let inp=domainInput plan; prior=take index (inputs e)
          bindings' xs = concat [if hs then inputId i ++ " = _values !! " ++ show j ++ "; " else if go then inputId i ++ " := _values[" ++ show j ++ "]; _ = " ++ inputId i ++ "; " else if kt then "val " ++ inputId i ++ " = _values[" ++ show j ++ "]; " else "var " ++ inputId i ++ " = _values.get(" ++ show j ++ "); " | (j,i) <- zip [0::Int ..] xs]
          lambda xs seed value = if hs then "(\\_values" ++ (if seed then " _seed" else "") ++ " -> " ++ (if null xs then "" else "let { " ++ bindings' xs ++ "} in ") ++ value ++ ")"
            else if go then "func(_values []LawSpecValue" ++ (if seed then ", _seed int" else "") ++ ") " ++ (if seed then "[]LawSpecValue" else "bool") ++ " { " ++ bindings' xs ++ "return " ++ value ++ " }"
            else if kt then "{ _values" ++ (if seed then ", _seed" else "") ++ " -> " ++ bindings' xs ++ value ++ " }"
            else "(_values" ++ (if seed then ", _seed" else "") ++ ") -> { " ++ bindings' xs ++ "return " ++ value ++ "; }"
      bs <- mapM (\(op,v) -> let value = render v in pure (if hs then "(" ++ q op ++ "," ++ value ++ ")" else if go then "{" ++ q op ++ "," ++ value ++ "}" else (if kt then "LawSpecRuntime.Bound(" else "new LawSpecRuntime.Bound(") ++ q op ++ "," ++ value ++ ")")) (domainBounds plan)
      let hints = map render (generatorHints plan)
          ps = [call "truth" [render v] | v <- inputRefinements inp]
      let restrictions = (if hs then "[" else if go then "[]lawSpecBound{" else if kt then "arrayOf(" else "new LawSpecRuntime.Bound[]{") ++ intercalate "," bs ++ (if hs then "]" else if kt then ")" else "}")
          candidates = call "domainCandidates" [q (key (inputType inp)),"_seed",show bits,restrictions,arr (map scalar (generatorBoundaries plan) ++ hints)]
      pure $ if hs then "LS.Domain " ++ lambda prior True candidates ++ " " ++ lambda (prior++[inp]) False (conjunction ps)
        else (if go then "lawSpecDomain{" else if kt then "LawSpecRuntime.Domain(" else "new LawSpecRuntime.Domain(") ++ lambda prior True candidates ++ ", " ++ lambda (prior++[inp]) False (conjunction ps) ++ (if go then "}" else ")")
    refinedProperty fn label e check = do
      ds <- mapM (domainCode e) (zip [0::Int ..] (generationPlan e))
      let cfg=generation e
          domains = (if hs then "[" else if go then "[]lawSpecDomain{" else if kt then "arrayOf(" else "new LawSpecRuntime.Domain[]{") ++ intercalate ", " ds ++ (if hs then "]" else if kt then ")" else "}")
          binds = concat [assign (inputId inp) (if hs then "_values !! " ++ show j else if go || kt then "_values[" ++ show j ++ "]" else "_values.get(" ++ show j ++ ")") | (j,inp) <- zip [0::Int ..] (inputs e)]
          callback = if hs then "_check"
                     else if go then "func(_values []LawSpecValue) {\n" ++ binds ++ check ++ "  }"
                     else if kt then "{ _values ->\n" ++ binds ++ check ++ "  }"
                     else "_values -> {\n" ++ binds ++ check ++ "  }"
          invocation = call "refinedCase" [domains,"seed",show (maxAttempts cfg),show (maxShrinks cfg),callback,quote (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ if hs then "  modifyMaxSuccess (const " ++ show (cases cfg) ++ ") $ it " ++ q (label ++ " property") ++ " $ hedgehog $ do\n    seed <- forAll (Gen.int (Range.linear 0 2147483647))\n    footnote " ++ q label ++ "\n    let _check _values = do\n" ++ unlines ["      " ++ line | line <- lines (binds ++ check)] ++ "    evalIO $ " ++ invocation ++ "\n"
        else if go then "func Test" ++ cap fn ++ "Property(t *testing.T) {\n    defer func(){if err:=recover();err!=nil{t.Fatalf(\"%v\",err)}}()\n    for seed := 0; seed < " ++ show (cases cfg) ++ "; seed++ {\n    symbols := map[string]*lawSpecSymbol{}; _ = symbols\n    " ++ invocation ++ "\n  }\n}\n"
        else if kt then "  " ++ q (label ++ " property") ++ " { checkAll(" ++ show (cases cfg) ++ ", Arb.int()) { seed ->\n    val symbols = mutableMapOf<String, Any>();\n    " ++ invocation ++ "\n  } }\n"
        else "  @Test void " ++ fn ++ "Property() { PropertyChecker.customized().withIterationCount(" ++ show (cases cfg) ++ ").forAll(Generator.integers(), seed -> {\n    var symbols = new HashMap<String,Object>();\n    " ++ invocation ++ ";\n    return true;\n  }); }\n"
    hsPart = concatMap cap . splitOn '_'
    split = splitOn '.'
    splitOn c s = case break (== c) s of (a,[]) -> [a]; (a,_:b) -> a:splitOn c b
    cap [] = []
    cap (c:cs) = (if c >= 'a' && c <= 'z' then toEnum (fromEnum c - 32) else c):cs

replace :: String -> String -> String -> String
replace old new text | old `isPrefixOf` text = new ++ replace old new (drop (length old) text)
replace _ _ [] = []
replace old new (c:cs) = c:replace old new cs
