-- | Elixir tokens and native types; the checked expression implementation is
-- shared Erlang, while public functions and data stay idiomatic Elixir.
-- ref:DEC-idiomatic-generated-types ref:DEC-readable-output-default
module LawSpec.ElixirCode
  ( string, atom, array, tuple, call, remote, function, moduleDoc
  , nativeType, typeReference, reference ) where

import qualified LawSpec.Core as C
import qualified LawSpec.Core.Schema as S
import qualified LawSpec.Code.Doc as D
import LawSpec.Scalar (primitive, family, Family(..), integerBounds)
import Data.Char (ord, toLower, isAscii, isAlphaNum, isLower)
import Numeric (showHex)

string :: String -> D.Doc
string s = D.text ('"' : concatMap escape s ++ "\"")
  where
    escape c | c `elem` ['"','\\','#'] = ['\\',c]
    escape '\n' = "\\n"
    escape '\r' = "\\r"
    escape '\t' = "\\t"
    escape c | ord c < 32 || ord c >= 127 = "\\u{" ++ showHex (ord c) "}"
    escape c = [c]

atom :: String -> D.Doc
atom n = D.text ":" <> (if plain n then D.text n else string n)
  where
    plain (c:cs) = (isAscii c && isLower c || c == '_') && all (\x -> isAscii x && (isAlphaNum x || x `elem` ("_@!?" :: String))) cs
    plain [] = False

array, tuple :: [D.Doc] -> D.Doc
array = D.delimit 2 "[" "]"
tuple = D.delimit 2 "{" "}"

call :: String -> [D.Doc] -> D.Doc
call name args = D.text name <> D.delimit 2 "(" ")" args

remote :: String -> String -> [D.Doc] -> D.Doc
remote owner name args = D.text owner <> D.text "." <> call name args

function :: String -> [D.Doc] -> [D.Doc] -> D.Doc
function name args body = D.group (D.text "def " <> call name args <> D.text " do" <>
  D.nest 2 (D.softline <> D.joinWith (D.text ";" <> D.softline) body) <> D.softline <> D.text "end")

moduleDoc :: String -> Bool -> [D.Doc] -> D.Doc
moduleDoc name editable body = D.text (if editable then "# User-owned LawSpec adapter. Implement these functions." else "# Generated by LawSpec. Do not edit.") <>
  D.hardline <> D.text ("defmodule " ++ name ++ " do") <>
  D.nest 2 (D.hardline <> D.joinWith (D.hardline <> D.hardline) body) <> D.hardline <> D.text "end" <> D.hardline

reference :: S.TypeRef -> D.Doc
reference (S.Parameter i) = tuple [atom "parameter",D.text (show i)]
reference (S.Named n ts) = tuple [string n,array (map reference ts)]

typeReference :: C.Type -> Either String D.Doc
typeReference ty = reference <$> S.typeReference [] ty

nativeType :: Int -> [(C.Id,String)] -> [(C.Id,String)] -> C.Type -> Either String D.Doc
nativeType bits names parameters ty = case ty of
  C.TypeVariable identity -> maybe (Left "unbound Elixir type parameter") (Right . D.text) (lookup identity parameters)
  C.Constructor n args -> do
    ts <- mapM argument args
    case (n,ts) of
      ("List",[t]) -> pure (array [t])
      ("Maybe",[t]) -> pure (union [atom "nothing",tuple [atom "just",t]])
      ("Either",[a,b]) -> pure (union [tuple [atom "left",a],tuple [atom "right",b]])
      ("Nullable",[t]) -> pure (union [atom "null",tuple [atom "non_null",t]])
      ("Optional",[t]) -> pure (union [atom "none",tuple [atom "some",t]])
      (_,[]) | Just p <- primitive n -> pure $ case family p of
        IntegerFamily -> case integerBounds bits n of
          Just (lo,hi) -> D.text (show lo ++ ".." ++ show hi)
          Nothing -> call (if n == "BigUInt" then "non_neg_integer" else "integer") []
        Boolean -> call "boolean" []
        Floating -> remote ":lawspec_beam_scalar" "ieee" []
        Complex -> remote ":lawspec_beam_scalar" "complex" []
        Exact -> remote ":lawspec_beam_scalar" (map toLower n) []
        Character -> call "non_neg_integer" []
        Sequence -> if n `elem` ["Text","Bytes"] then call "binary" [] else array [call "non_neg_integer" []]
        Identity -> remote ":lawspec_beam_scalar" "symbol" []
        Absence -> atom (case n of "Unit" -> "ok"; "Null" -> "null"; _ -> "undefined")
      _ -> maybe (Left ("no Elixir native type: " ++ n))
        (\name -> pure (remote "LawSpec.Data" name ts)) (lookup (C.Id n) names)
  C.Arrow _ _ -> Left "function-valued Elixir data is unsupported"
  where
    argument (C.TypeArgument t) = nativeType bits names parameters t
    argument (C.IndexArgument _) = Left "unerased Elixir type index"
    union = D.joinWith (D.text " | ")
