module LawSpec.Emit (emit, emitWithLayout, targets) where

import LawSpec.Model
import LawSpec.Compile (prettyExpanded, normal)
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T
import Data.Char (toUpper, toLower, isAlphaNum, isAscii)
import Data.List (intercalate, nub, stripPrefix, isPrefixOf)
import Control.Monad (unless)

targets :: [String]
targets = ["java","python","javascript","typescript","go","haskell","kotlin"]
q :: String -> String
q = T.unpack . T.decodeUtf8 . encode
split :: Char -> String -> [String]
split c s = case break (==c) s of (a,[]) -> [a]; (a,_:b) -> a:split c b
cap :: String -> String
cap [] = []
cap (a:b) = toUpper a:b
pascal :: String -> String
pascal = concatMap cap . split '_'
comma :: [String] -> String
comma = intercalate ", "
comment :: (String -> String) -> String -> Expanded -> String
comment native prefix e = unlines [prefix ++ " " ++ map safe l | l <- lines text]
  where text = "Law: " ++ name e ++ "\nDescription: " ++ interpolate (description (original e)) ++ "\nRationale: " ++ interpolate (rationale (original e)) ++ "\nReferences: " ++ intercalate ", " (references (original e)) ++ "\nExpansion:\n" ++ unlines (trace e) ++ prettyExpanded e
        interpolate [] = []
        interpolate ('{':'{':xs) = '{':interpolate xs
        interpolate ('}':'}':xs) = '}':interpolate xs
        interpolate ('{':xs) = case break (== '}') xs of
          (n,'}':rest) -> native n ++ interpolate rest
          _ -> xs
        interpolate (c:xs) = c:interpolate xs
        safe '\\' = '／'
        safe c | c < ' ' || c == '\x2028' || c == '\x2029' = ' '
               | otherwise = c
reserved :: [String]
reserved = words "class interface enum public private protected static return import package module where data type newtype case of if then else let in do forall object fun val var when is as null true false None True False def lambda pass raise from with yield async await export default function const new delete switch throw try catch finally break continue for while match typealias struct func map range select defer go chan int string error assert test"

emit :: String -> [Unit] -> [Expanded] -> Either [Diagnostic] [Artifact]
emit target us es = do
  unless (target `elem` targets) (Left [Diagnostic "target" ("unknown target: " ++ target) Nothing])
  let bad = [n | u <- us, n <- map fst (functions u) ++ split '.' (unitName u), n `elem` reserved || not (all (\c -> isAscii c && (isAlphaNum c || c == '_')) n)]
  unless (null bad) (Left [Diagnostic "identifier" ("reserved target identifier: " ++ comma bad) Nothing])
  let files = concatMap (emitUnit target es) (filter (\u -> not (null (functions u)) || any ((== unitName u) . owner) es) us)
  unless (length (map artifactPath files) == length (nub (map (map toLower . artifactPath) files))) (Left [Diagnostic "collision" "units map to the same output path" Nothing])
  let generatedNames u = map (\(n,_) -> if target == "go" then cap n else n) (functions u)
  unless (all (\u -> let ns = generatedNames u in length ns == length (nub ns)) us) (Left [Diagnostic "collision" "functions map to the same target identifier" Nothing])
  pure files

emitUnit :: String -> [Expanded] -> Unit -> [Artifact]
emitUnit target allLaws u = [Artifact stubPath stub "user", Artifact testPath tests "generated"]
  where
    parts = split '.' (unitName u)
    base = last parts
    packageName = intercalate "." (init parts)
    className = pascal base
    moduleName = intercalate "." (map pascal parts)
    slash = intercalate "/" parts
    hsSlash = intercalate "/" (map pascal parts)
    javaSlash = intercalate "/" (init parts ++ [className])
    ls = filter ((== unitName u) . owner) allLaws
    indexed = zip [0 :: Int ..] ls
    fn n = if target == "go" then cap n else n
    ty (Named "Int32") = case target of "python" -> "int"; "java" -> "int"; "kotlin" -> "Int"; "go" -> "int32"; "haskell" -> "Int32"; _ -> "number"
    ty (Named "Bool") = case target of "python" -> "bool"; "java" -> "boolean"; "kotlin" -> "Boolean"; "go" -> "bool"; "haskell" -> "Bool"; _ -> "boolean"
    ty _ = case target of "python" -> "str"; "java" -> "String"; "kotlin" -> "String"; "go" -> "string"; "haskell" -> "Text"; _ -> "string"
    functions' = [(fn n, args,result) | (n,t) <- functions u, let (args,result) = functionType t]
    arguments args = zip (if length args == 1 then ["value"] else ["value" ++ show i | i <- [1 :: Int ..]]) args
    nativeArgs args = comma [case target of
      "java" -> ty t ++ " " ++ n
      "go" -> n ++ " " ++ ty t
      "javascript" -> n
      _ -> n ++ ": " ++ ty t | (n,t) <- arguments args]
    header prefix = prefix ++ " Scaffolded by LawSpec. User-owned; never overwritten.\n"
    generated prefix = prefix ++ " Generated by LawSpec 0.6.0. Do not edit.\n"
    pkg = if null packageName then "" else "package " ++ packageName ++ (if target == "java" then ";\n" else "\n")
    stubPath = case target of
      "java" -> "src/main/java/" ++ javaSlash ++ ".java"
      "kotlin" -> "src/main/kotlin/" ++ javaSlash ++ ".kt"
      "python" -> "src/" ++ slash ++ ".py"
      "haskell" -> "src/" ++ hsSlash ++ ".hs"
      "go" -> slash ++ "/adapter.go"
      _ -> "src/" ++ slash ++ if target == "typescript" then ".ts" else ".mjs"
    testPath = case target of
      "java" -> "src/test/java/" ++ javaSlash ++ "LawSpecTest.java"
      "kotlin" -> "src/test/kotlin/" ++ javaSlash ++ "LawSpecTest.kt"
      "python" -> "tests/test_" ++ intercalate "_" parts ++ "_lawspec.py"
      "haskell" -> "test/" ++ hsSlash ++ "Spec.hs"
      "go" -> slash ++ "/lawspec_test.go"
      _ -> "test/" ++ intercalate "_" parts ++ ".lawspec.test." ++ if target == "typescript" then "ts" else "mjs"
    stub = case target of
      "python" -> header "#" ++ concat ["\ndef " ++ n ++ "(" ++ nativeArgs args ++ ") -> " ++ ty result ++ ":\n    raise NotImplementedError(" ++ q ("TODO: " ++ unitName u ++ "::" ++ n) ++ ")\n" | (n,args,result) <- functions']
      "java" -> header "//" ++ pkg ++ "public final class " ++ className ++ " {\n  private " ++ className ++ "() {}\n"
        ++ concat ["  public static " ++ ty result ++ " " ++ n ++ "(" ++ nativeArgs args ++ ") { throw new UnsupportedOperationException(" ++ q ("TODO: " ++ n) ++ "); }\n" | (n,args,result) <- functions'] ++ "}\n"
      "kotlin" -> header "//" ++ pkg ++ "object " ++ className ++ " {\n" ++ concat ["  fun " ++ n ++ "(" ++ nativeArgs args ++ "): " ++ ty result ++ " = TODO(" ++ q n ++ ")\n" | (n,args,result) <- functions'] ++ "}\n"
      "go" -> header "//" ++ "package " ++ base ++ "\n\n" ++ concat ["func " ++ n ++ "(" ++ nativeArgs args ++ ") " ++ ty result ++ " { panic(" ++ q ("TODO: " ++ n) ++ ") }\n" | (n,args,result) <- functions']
      "haskell" -> header "--" ++ "module " ++ moduleName ++ " where\nimport Data.Int (Int32)\nimport Data.Text (Text)\n" ++ concat [n ++ " :: " ++ intercalate " -> " (map ty (args ++ [result])) ++ "\n" ++ n ++ concatMap (const " _") args ++ " = error " ++ q ("TODO: " ++ n) ++ "\n" | (n,args,result) <- functions']
      _ -> header "//" ++ concat ["export function " ++ n ++ "(" ++ nativeArgs args ++ ")" ++ (if target == "typescript" then ": " ++ ty result else "") ++ " { throw new Error(" ++ q ("TODO: " ++ n) ++ "); }\n" | (n,args,result) <- functions']
    render (Var n) | take 6 n == "_input" = n
                   | target `elem` ["java", "kotlin"] = className ++ "." ++ fn n
                   | target == "haskell" = "Impl." ++ fn n
                   | otherwise = fn n
    render (BoolLit b) = literal (BoolLiteral b)
    render (StringLit text) = literal (TextLiteral text)
    render (Number n) | target == "go" = "int32(" ++ show n ++ ")"
                      | otherwise = if n < 0 then "(" ++ show n ++ ")" else show n
    render expression@(Apply f x)
      | target == "haskell" = "(" ++ render f ++ " " ++ render x ++ ")"
      | otherwise = let (callee,args) = application expression in render callee ++ "(" ++ comma (map render args) ++ ")"
    render (Compose f g) = "(" ++ render f ++ " . " ++ render g ++ ")"
    application (Apply f x) = let (callee,args) = application f in (callee,args ++ [x])
    application e = (e,[])
    count e = length (inputs e)
    lawFn i = "_lawspecLaw" ++ show i
    literal (BoolLiteral b) = if target `elem` ["python","haskell"] then show b else if b then "true" else "false"
    literal (IntLiteral n) = show n
    literal (TextLiteral text)
      | target == "haskell" = "(T.pack " ++ show text ++ ")"
      | target == "kotlin" = ktq text
      | otherwise = q text
    generator t = case (target,t) of
      ("java",Named "Bool") -> "Generator.booleans()"
      ("python",Named "Bool") -> "st.booleans()"
      ("go",Named "Bool") -> "rapid.Bool()"
      ("haskell",Named "Bool") -> "Gen.bool"
      ("kotlin",Named "Bool") -> "Arb.boolean()"
      (_,Named "Bool") -> "fc.boolean()"
      ("java",Named "Text") -> "Generator.stringsOf(Generator.asciiPrintableChars())"
      ("java",_) -> "Generator.integers()"
      ("python",Named "Text") -> "st.text()"
      ("python",_) -> "st.integers(min_value=-(2**31), max_value=2**31-1)"
      ("go",Named "Text") -> "rapid.String()"
      ("go",_) -> "rapid.Int32()"
      ("haskell",Named "Text") -> "Gen.text (Range.linear 0 100) Gen.unicode"
      ("haskell",_) -> "Gen.int32 Range.constantBounded"
      ("kotlin",Named "Text") -> "Arb.string()"
      ("kotlin",_) -> "Arb.int()"
      (_,Named "Text") -> "fc.string()"
      _ -> "fc.integer({min: -2147483648, max: 2147483647})"
    boundaries (Named "Bool") = map BoolLiteral [False, True]
    boundaries (Named "Text") = map TextLiteral ["", " ", "Hello, World!", "λ日本語😀", "a\n\t\"\\$\0z", "e\x0301"]
    boundaries _ = map IntLiteral [-2147483648,-1,0,2147483647]
    call i args = lawFn i ++ if target == "haskell" then concatMap (\a -> " (" ++ a ++ ")") args else "(" ++ comma args ++ ")"
    -- Every assertion carries its specification and evaluates each side once.
    replaceValues values expression = normal $ case expression of
      Var n -> maybe expression id (lookup n values)
      Apply f x -> Apply (replaceValues values f) (replaceValues values x)
      Compose f g -> Compose (replaceValues values f) (replaceValues values g)
      _ -> expression
    literalExpr (BoolLiteral b) = BoolLit b
    literalExpr (IntLiteral n) = Number n
    literalExpr (TextLiteral text) = StringLit text
    namedBindings bs = intercalate ", " [n ++ " = " ++ prettyExpr (literalExpr v) | (n,v) <- bs]
    label e kind bs = owner e ++ "::" ++ name e ++ ": " ++ kind ++ " [" ++ namedBindings bs ++ "]"
    replaceAssertion values (AssertEqual a b) = AssertEqual (replaceValues values a) (replaceValues values b)
    replaceAssertion values (AssertImplies g body) = AssertImplies (replaceValues values g) (replaceAssertion values body)
    replaceAssertion values (AssertAll bodies) = AssertAll (map (replaceAssertion values) bodies)
    lawAssertion e values = ("law: " ++ prettyExpanded e, replaceAssertion values (assertion e))
    examplesAndBoundaries e =
      [(label e ("example: " ++ exampleName ex) (bindings ex),
        [("expect " ++ prettyExpr (actual check) ++ " = " ++ prettyExpr (literalExpr (expected check)),
          AssertEqual (replaceValues [(n,literalExpr v) | (n,v) <- bindings ex] (actual check)) (literalExpr (expected check))) | check <- expectations ex]
        ++ [lawAssertion e [(inputId inp,literalExpr v) | inp <- inputs e, Just v <- [lookup (inputName inp) (bindings ex)]]])
       | ex <- examples (original e)]
      ++ [(label e ("boundary " ++ show j) bs, [lawAssertion e [(inputId inp,literalExpr v) | (inp,(_,v)) <- zip (inputs e) bs]])
         | j <- [0 .. maximum (map (length . boundaries . inputType) (inputs e)) - 1],
           let bs = [(inputName inp,values !! (j `mod` length values)) | inp <- inputs e, let values = boundaries (inputType inp)]]
    emitAssertion prefix context (text,AssertAll bodies) = concatMap (\body -> emitAssertion prefix context (text,body)) bodies
    emitAssertion prefix context (text,AssertImplies g consequence) =
      let body = emitAssertion (prefix ++ "  ") context (text,consequence) in
      case target of
        "python" -> prefix ++ "if " ++ render g ++ ":\n" ++ body
        "go" -> prefix ++ "if " ++ render g ++ " {\n" ++ body ++ prefix ++ "}\n"
        _ -> prefix ++ "if (" ++ render g ++ ") {\n" ++ body ++ prefix ++ "}\n"
    emitAssertion prefix context (text,AssertEqual a b) =
      let x = render a; y = render b; message = context ++ " | " ++ text in
      case target of
        "java" -> prefix ++ "{ var _lawspecActual = " ++ x ++ "; var _lawspecExpected = " ++ y ++ "; assertEquals(_lawspecExpected, _lawspecActual, " ++ q message ++ "); }\n"
        "python" -> prefix ++ "_lawspecActual = " ++ x ++ "\n" ++ prefix ++ "_lawspecExpected = " ++ y ++ "\n" ++ prefix ++ "assert _lawspecActual == _lawspecExpected, " ++ q message ++ " + f\" | actual={_lawspecActual!r}, expected={_lawspecExpected!r}\"\n"
        "go" -> prefix ++ "{ _lawspecActual := " ++ x ++ "; _lawspecExpected := " ++ y ++ "; if _lawspecActual != _lawspecExpected { t.Fatalf(\"%s | actual=%#v, expected=%#v\", " ++ q message ++ ", _lawspecActual, _lawspecExpected) } }\n"
        "kotlin" -> prefix ++ "withClue(" ++ ktq message ++ ") { val _lawspecActual = " ++ x ++ "; val _lawspecExpected = " ++ y ++ "; _lawspecActual shouldBe _lawspecExpected }\n"
        _ -> prefix ++ "{ const _lawspecActual = " ++ x ++ "; const _lawspecExpected = " ++ y ++ "; assert.strictEqual(_lawspecActual, _lawspecExpected, " ++ q message ++ "); }\n"
    propertyContext e = owner e ++ "::" ++ name e ++ ": property (inputs: " ++ comma (map inputName (inputs e)) ++ ")"
    jsTests (i,e) = comment fn "//" e
      ++ "function " ++ lawFn i ++ "(" ++ comma [inputId inp ++ if target == "typescript" then ": " ++ ty (inputType inp) else "" | inp <- inputs e] ++ ") {\n"
      ++ emitAssertion "  " (propertyContext e) (lawAssertion e []) ++ "}\n"
      ++ concat ["test(" ++ q context ++ ", () => {\n" ++ concatMap (emitAssertion "  " context) checks ++ "});\n" | (context,checks) <- examplesAndBoundaries e]
      ++ "test(" ++ q (name e ++ ": property") ++ ", () => fc.assert(fc.property(" ++ comma (map (generator . inputType) (inputs e) ++ [lawFn i]) ++ ")));\n"
    pyTests (i,e) = comment fn "#" e
      ++ concat ["def test_law" ++ show i ++ "_example" ++ show j ++ "() -> None:\n" ++ concatMap (emitAssertion "    " context) checks ++ "\n" | (j,(context,checks)) <- zip [0 :: Int ..] (examplesAndBoundaries e)]
      ++ "@given(" ++ comma [inputId inp ++ "=" ++ generator (inputType inp) | inp <- inputs e] ++ ")\ndef test_law" ++ show i ++ "_property(" ++ comma [inputId inp ++ ": " ++ ty (inputType inp) | inp <- inputs e] ++ ") -> None:\n"
      ++ emitAssertion "    " (propertyContext e) (lawAssertion e []) ++ "\n"
    javaTests (i,e) = comment fn "//" e
      ++ "  private static boolean " ++ lawFn i ++ "(" ++ comma [ty (inputType inp) ++ " " ++ inputId inp | inp <- inputs e] ++ ") {\n"
      ++ emitAssertion "    " (propertyContext e) (lawAssertion e []) ++ "    return true;\n  }\n"
      ++ concat ["  @Test @DisplayName(" ++ q context ++ ") void law" ++ show i ++ "Example" ++ show j ++ "() {\n" ++ concatMap (emitAssertion "    " context) checks ++ "  }\n" | (j,(context,checks)) <- zip [0 :: Int ..] (examplesAndBoundaries e)]
      ++ "  @Test @DisplayName(" ++ q (propertyContext e) ++ ") void law" ++ show i ++ "Property() { " ++ javaChecker e ++ ".forAll(" ++ javaGenerator e ++ ", value -> " ++ call i (javaValues e) ++ "); }\n"
    -- JetCheck requires distinct generated values; Bool-only domains are finite.
    javaChecker e
      | all ((== Named "Bool") . inputType) (inputs e) = "PropertyChecker.customized().withIterationCount(" ++ show (foldl (\n _ -> min 100 (n * 2)) (1 :: Int) (inputs e)) ++ ")"
      | otherwise = "PropertyChecker"
    javaGenerator e
      | [inp] <- inputs e = generator (inputType inp)
      | otherwise = "Generator.from(data -> java.util.List.of(" ++ comma ["data.generate(" ++ generator (inputType inp) ++ ")" | inp <- inputs e] ++ "))"
    javaValues e
      | count e == 1 = ["value"]
      | otherwise = ["(" ++ (case inputType inp of Named "Int32" -> "Integer"; Named "Bool" -> "Boolean"; _ -> "String") ++ ") value.get(" ++ show j ++ ")" | (j,inp) <- zip [0 :: Int ..] (inputs e)]
    goTests (i,e) = comment fn "//" e
      ++ "func TestLaw" ++ show i ++ "(t *testing.T) {\n"
      ++ concat [" t.Run(" ++ q context ++ ", func(t *testing.T) {\n" ++ concatMap (emitAssertion "  " context) checks ++ " })\n" | (context,checks) <- examplesAndBoundaries e]
      ++ " rapid.Check(t, func(t *rapid.T) {\n"
      ++ concat ["  " ++ inputId inp ++ " := " ++ generator (inputType inp) ++ ".Draw(t, " ++ q (inputName inp) ++ ")\n" | inp <- inputs e]
      ++ concat ["  _ = " ++ inputId inp ++ "\n" | inp <- inputs e]
      ++ emitAssertion "  " (propertyContext e) (lawAssertion e []) ++ " })\n}\n"
    hsGuard prefix [] body = body prefix
    hsGuard prefix (g:gs) body = prefix ++ "if " ++ render g ++ " then do\n" ++ hsGuard (prefix ++ "  ") gs body ++ prefix ++ "else pure ()\n"
    hsAssertion prefix (text,AssertAll bodies) = concatMap (\body -> hsAssertion prefix (text,body)) bodies
    hsAssertion prefix (text,AssertImplies g body) = hsGuard prefix [g] (\indent -> hsAssertion indent (text,body))
    hsAssertion prefix (text,AssertEqual a b) = prefix ++ "annotate " ++ show text ++ " $ (" ++ render a ++ ") `shouldBe` (" ++ render b ++ ")\n"
    hsProperty prefix (AssertAll bodies) = concatMap (hsProperty prefix) bodies
    hsProperty prefix (AssertImplies g body) = hsGuard prefix [g] (\indent -> hsProperty indent body)
    hsProperty prefix (AssertEqual a b) = prefix ++ "(" ++ render a ++ ") === (" ++ render b ++ ")\n"
    hsTests (_,e) = concat ["  it " ++ show context ++ " $ do\n" ++ concatMap (hsAssertion "    ") checks | (context,checks) <- examplesAndBoundaries e]
      ++ "  it " ++ show (propertyContext e) ++ " $ hedgehog $ do\n"
      ++ concat ["    " ++ inputId inp ++ " <- forAll (" ++ generator (inputType inp) ++ ")\n" | inp <- inputs e]
      ++ "    footnote " ++ show (propertyContext e ++ " | " ++ prettyExpanded e) ++ "\n"
      ++ hsProperty "    " (assertion e)
    ktq = concatMap (\c -> if c == '$' then "\\$" else [c]) . q
    ktTests (_,e) = concat ["  " ++ ktq context ++ " {\n" ++ concatMap (emitAssertion "    " context) checks ++ "  }\n" | (context,checks) <- examplesAndBoundaries e]
      ++ "  " ++ ktq (propertyContext e) ++ " { checkAll(arbitrary { listOf(" ++ comma [generator (inputType inp) ++ ".bind()" | inp <- inputs e] ++ ") }) { values ->\n"
      ++ concat ["    val " ++ inputId inp ++ " = values[" ++ show j ++ "] as " ++ ty (inputType inp) ++ "\n" | (j,inp) <- zip [0 :: Int ..] (inputs e)]
      ++ emitAssertion "    " (propertyContext e) (lawAssertion e []) ++ "  } }\n"
    tests = case target of
      "python" -> generated "#"
          ++ "from hypothesis import given, strategies as st\n"
          ++ (if null (functions u) then "" else "from "
          ++ unitName u
          ++ " import "
          ++ comma (map (fn . fst) (functions u))
          ++ "\n")
          ++ "\n"
          ++ concatMap pyTests indexed
      "java" -> generated "//"
          ++ pkg
          ++ "import org.jetbrains.jetCheck.Generator;\nimport org.jetbrains.jetCheck.PropertyChecker;\nimport org.junit.jupiter.api.Test;\nimport org.junit.jupiter.api.DisplayName;\nimport static org.junit.jupiter.api.Assertions.assertEquals;\npublic final class "
          ++ className
          ++ "LawSpecTest {\n"
          ++ concatMap javaTests indexed
          ++ "}\n"
      "go" -> generated "//" ++ "package " ++ base ++ "\nimport (\"testing\"; \"pgregory.net/rapid\")\n" ++ concatMap goTests indexed
      "haskell" -> generated "--"
          ++ "module "
          ++ moduleName
          ++ "Spec (spec) where\nimport Data.Int (Int32)\nimport Data.Text (Text)\nimport qualified Data.Text as T\nimport qualified "
          ++ moduleName
          ++ " as Impl\nimport Test.Hspec\nimport Control.Exception (SomeException, catch, displayException)\nimport Test.Hspec.Hedgehog (hedgehog)\nimport Hedgehog ((===), forAll, footnote)\nimport qualified Hedgehog.Gen as Gen\nimport qualified Hedgehog.Range as Range\n"
          ++ "annotate :: String -> Expectation -> Expectation\nannotate message action = catch action handler\n  where\n    handler :: SomeException -> IO ()\n    handler e = expectationFailure (message ++ \"\\n\" ++ displayException e)\n"
          ++ "spec :: Spec\nspec = do\n"
          ++ (if null ls then "  pure ()\n" else concatMap hsTests indexed)
      "kotlin" -> generated "//"
          ++ pkg
          ++ "import io.kotest.core.spec.style.StringSpec\nimport io.kotest.matchers.shouldBe\nimport io.kotest.assertions.withClue\nimport io.kotest.property.Arb\nimport io.kotest.property.arbitrary.int\nimport io.kotest.property.arbitrary.boolean\nimport io.kotest.property.arbitrary.arbitrary\nimport io.kotest.property.arbitrary.string\nimport io.kotest.property.checkAll\n"
          ++ "class "
          ++ className
          ++ "LawSpecTest : StringSpec({\n"
          ++ concatMap ktTests indexed
          ++ "})\n"
      _ -> generated "//"
          ++ "import { test } from 'node:test';\nimport assert from 'node:assert/strict';\nimport fc from 'fast-check';\nimport { "
          ++ comma (map (fn . fst) (functions u))
          ++ " } from '../src/"
          ++ slash
          ++ (if target == "typescript" then ".js" else ".mjs")
          ++ "';\n"
          ++ concatMap jsTests indexed

-- Paths and imports are transformed together so custom layouts remain executable.
emitWithLayout :: String -> Maybe String -> Maybe String -> [Unit] -> [Expanded] -> Either [Diagnostic] [Artifact]
emitWithLayout target sourceDir testDir us es = do
  files <- emit target us es
  let defaults = case target of
        "java" -> ("src/main/java", "src/test/java")
        "kotlin" -> ("src/main/kotlin", "src/test/kotlin")
        "python" -> ("src", "tests")
        "go" -> ("", "")
        _ -> ("src", "test")
      src = maybe (fst defaults) id sourceDir
      tst = maybe (snd defaults) id testDir
      safe p = (null p && target == "go") || (not (null p) && all (\part -> not (null part) && part /= "." && part /= ".." && all (\c -> isAlphaNum c || c `elem` ("_-" :: String)) part) (split '/' p))
  unless (safe src && safe tst) (Left [Diagnostic "layout" "output directories must be relative paths without traversal" Nothing])
  unless (target /= "go" || src == tst) (Left [Diagnostic "layout" "Go adapters and tests must share a source directory" Nothing])
  let prefix p f = if null p then f else p ++ "/" ++ f
      move old new f = prefix new (maybe f id (stripPrefix (if null old then "" else old ++ "/") f))
      rel a b = case (a,b) of
        (x:xs,y:ys) | x == y -> rel xs ys
        _ -> intercalate "/" (replicate (length a) ".." ++ b)
      relative = rel (split '/' tst) (split '/' src)
      importRoot = if null relative then "." else if ".." `isPrefixOf` relative then relative else "./" ++ relative
      replace old new text
        | null text = []
        | Just rest <- stripPrefix old text = new ++ replace old new rest
        | c:rest <- text = c:replace old new rest
        | otherwise = []
      adjust a = a { artifactPath = if ownership a == "user" then move (fst defaults) src (artifactPath a) else move (snd defaults) tst (artifactPath a)
                   , artifactContent = if target `elem` ["javascript","typescript"] && ownership a == "generated" then replace " } from '../src/" (" } from '"
                       ++ importRoot
                       ++ "/") (artifactContent a) else artifactContent a }
      result = map adjust files
  unless (length result == length (nub (map (map toLower . artifactPath) result))) (Left [Diagnostic "collision" "custom layout causes an output collision" Nothing])
  pure result
