module LawSpec.Emit (emit, emitWithLayout, targets) where

import LawSpec.Model
import LawSpec.Compile (prettyExpanded)
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T
import Data.Char (toUpper, toLower, isAlphaNum, isAscii)
import Data.List (intercalate, nub, stripPrefix, isPrefixOf)
import Control.Monad (unless)

targets :: [String]
targets = ["java","python","javascript","typescript","go","haskell","kotlin"]
q :: String -> String
q = T.unpack . T.decodeUtf8 . encode
split :: Char -> String -> [String]
split c s = case break (==c) s of (a,[]) -> [a]; (a,_:b) -> a:split c b
cap :: String -> String
cap [] = []
cap (a:b) = toUpper a:b
pascal :: String -> String
pascal = concatMap cap . split '_'
comma :: [String] -> String
comma = intercalate ", "
comment :: (String -> String) -> String -> Expanded -> String
comment native prefix e = unlines [prefix ++ " " ++ map safe l | l <- lines text]
  where text = "Law: " ++ name e ++ "\nDescription: " ++ interpolate (description (original e)) ++ "\nRationale: " ++ interpolate (rationale (original e)) ++ "\nReferences: " ++ intercalate ", " (references (original e)) ++ "\nExpansion:\n" ++ unlines (trace e) ++ prettyExpanded e
        interpolate [] = []
        interpolate ('{':'{':xs) = '{':interpolate xs
        interpolate ('}':'}':xs) = '}':interpolate xs
        interpolate ('{':xs) = case break (== '}') xs of
          (n,'}':rest) -> native n ++ interpolate rest
          _ -> xs
        interpolate (c:xs) = c:interpolate xs
        safe '\\' = '／'
        safe c | c < ' ' || c == '\x2028' || c == '\x2029' = ' '
               | otherwise = c
reserved :: [String]
reserved = words "class interface enum public private protected static return import package module where data type newtype case of if then else let in do forall object fun val var when is as null true false None True False def lambda pass raise from with yield async await export default function const new delete switch throw try catch finally break continue for while match typealias struct func map range select defer go chan int string error assert test"

emit :: String -> [Unit] -> [Expanded] -> Either [Diagnostic] [Artifact]
emit target us es = do
  unless (target `elem` targets) (Left [Diagnostic "target" ("unknown target: " ++ target) Nothing])
  let bad = [n | u <- us, n <- map fst (functions u) ++ split '.' (unitName u), n `elem` reserved || not (all (\c -> isAscii c && (isAlphaNum c || c == '_')) n)]
  unless (null bad) (Left [Diagnostic "identifier" ("reserved target identifier: " ++ comma bad) Nothing])
  let files = concatMap (emitUnit target es) (filter (\u -> not (null (functions u)) || any ((== unitName u) . owner) es) us)
  unless (length (map artifactPath files) == length (nub (map (map toLower . artifactPath) files))) (Left [Diagnostic "collision" "units map to the same output path" Nothing])
  let generatedNames u = map (\(n,_) -> if target == "go" then cap n else n) (functions u)
  unless (all (\u -> let ns = generatedNames u in length ns == length (nub ns)) us) (Left [Diagnostic "collision" "functions map to the same target identifier" Nothing])
  pure files

emitUnit :: String -> [Expanded] -> Unit -> [Artifact]
emitUnit target allLaws u = [Artifact stubPath stub "user", Artifact testPath tests "generated"]
  where
    parts = split '.' (unitName u)
    base = last parts
    packageName = intercalate "." (init parts)
    className = pascal base
    moduleName = intercalate "." (map pascal parts)
    slash = intercalate "/" parts
    hsSlash = intercalate "/" (map pascal parts)
    javaSlash = intercalate "/" (init parts ++ [className])
    ls = filter ((== unitName u) . owner) allLaws
    indexed = zip [0 :: Int ..] ls
    fn n = if target == "go" then cap n else n
    ty (Named "Int32") = case target of "python" -> "int"; "java" -> "int"; "kotlin" -> "Int"; "go" -> "int32"; "haskell" -> "Int32"; _ -> "number"
    ty _ = case target of "python" -> "str"; "java" -> "String"; "kotlin" -> "String"; "go" -> "string"; "haskell" -> "Text"; _ -> "string"
    functions' = [(fn n, a,b) | (n,Arrow a b) <- functions u]
    header prefix = prefix ++ " Scaffolded by LawSpec. User-owned; never overwritten.\n"
    generated prefix = prefix ++ " Generated by LawSpec 0.2.1. Do not edit.\n"
    pkg = if null packageName then "" else "package " ++ packageName ++ (if target == "java" then ";\n" else "\n")
    stubPath = case target of
      "java" -> "src/main/java/" ++ javaSlash ++ ".java"
      "kotlin" -> "src/main/kotlin/" ++ javaSlash ++ ".kt"
      "python" -> "src/" ++ slash ++ ".py"
      "haskell" -> "src/" ++ hsSlash ++ ".hs"
      "go" -> slash ++ "/adapter.go"
      _ -> "src/" ++ slash ++ if target == "typescript" then ".ts" else ".mjs"
    testPath = case target of
      "java" -> "src/test/java/" ++ javaSlash ++ "LawSpecTest.java"
      "kotlin" -> "src/test/kotlin/" ++ javaSlash ++ "LawSpecTest.kt"
      "python" -> "tests/test_" ++ intercalate "_" parts ++ "_lawspec.py"
      "haskell" -> "test/" ++ hsSlash ++ "Spec.hs"
      "go" -> slash ++ "/lawspec_test.go"
      _ -> "test/" ++ intercalate "_" parts ++ ".lawspec.test." ++ if target == "typescript" then "ts" else "mjs"
    stub = case target of
      "python" -> header "#"
          ++ concat ["\ndef "
          ++ n
          ++ "(value: "
          ++ ty a
          ++ ") -> "
          ++ ty b
          ++ ":\n    raise NotImplementedError("
          ++ q ("TODO: "
          ++ unitName u
          ++ "::"
          ++ n)
          ++ ")\n" | (n,a,b) <- functions']
      "java" -> header "//"
          ++ pkg
          ++ "public final class "
          ++ className
          ++ " {\n  private "
          ++ className
          ++ "() {}\n"
          ++ concat ["  public static "
          ++ ty b
          ++ " "
          ++ n
          ++ "("
          ++ ty a
          ++ " value) { throw new UnsupportedOperationException("
          ++ q ("TODO: "
          ++ n)
          ++ "); }\n" | (n,a,b) <- functions']
          ++ "}\n"
      "kotlin" -> header "//" ++ pkg ++ concat ["fun " ++ n ++ "(value: " ++ ty a ++ "): " ++ ty b ++ " = TODO(" ++ q n ++ ")\n" | (n,a,b) <- functions']
      "go" -> header "//"
          ++ "package "
          ++ base
          ++ "\n\n"
          ++ concat ["func "
          ++ n
          ++ "(value "
          ++ ty a
          ++ ") "
          ++ ty b
          ++ " { panic("
          ++ q ("TODO: "
          ++ n)
          ++ ") }\n" | (n,a,b) <- functions']
      "haskell" -> header "--"
          ++ "module "
          ++ moduleName
          ++ " where\nimport Data.Int (Int32)\nimport Data.Text (Text)\n"
          ++ concat [n
          ++ " :: "
          ++ ty a
          ++ " -> "
          ++ ty b
          ++ "\n"
          ++ n
          ++ " _ = error "
          ++ q ("TODO: "
          ++ n)
          ++ "\n" | (n,a,b) <- functions']
      _ -> header "//"
          ++ concat ["export function "
          ++ n
          ++ "(value"
          ++ (if target == "typescript" then ": "
          ++ ty a else "")
          ++ ")"
          ++ (if target == "typescript" then ": "
          ++ ty b else "")
          ++ " { throw new Error("
          ++ q ("TODO: "
          ++ n)
          ++ "); }\n" | (n,a,b) <- functions']
    render (Var n) | take 6 n == "_input" = n
                   | target == "java" = className ++ "." ++ fn n
                   | target == "haskell" = "Impl." ++ fn n
                   | otherwise = fn n
    render (Number n) = if n < 0 then "(" ++ show n ++ ")" else show n
    render (Apply f x) | target == "haskell" = "(" ++ render f ++ " " ++ render x ++ ")"
                       | otherwise = render f ++ "(" ++ render x ++ ")"
    render (Compose f g) = "(" ++ render f ++ " . " ++ render g ++ ")"
    predicate e | target == "java" = "java.util.Objects.equals(" ++ render (left e) ++ ", " ++ render (right e) ++ ")"
                | target `elem` ["javascript","typescript"] = render (left e) ++ " === " ++ render (right e)
                | otherwise = render (left e) ++ " == " ++ render (right e)
    vars e = map inputId (inputs e)
    count e = length (inputs e)
    lawFn i = "_lawspecLaw" ++ show i
    exampleArgs e ex = [show (maybe 0 id (lookup (inputName v) (bindings ex))) | v <- inputs e]
    cases e = [("example: "
        ++ exampleName ex, exampleArgs e ex) | ex <- examples (original e)]
        ++ [("boundary "
        ++ show n, replicate (count e) (show n)) | n <- [-2147483648,-1,0,2147483647 :: Integer]]
    call i args = lawFn i ++ if target == "haskell" then concatMap (\a -> " (" ++ a ++ ")") args else "(" ++ comma args ++ ")"
    jsTests (i,e) = comment fn "//" e
        ++ "function "
        ++ lawFn i
        ++ "("
        ++ comma [v
        ++ if target == "typescript" then ": number" else "" | v <- vars e]
        ++ ") { return "
        ++ predicate e
        ++ "; }\n"
        ++ concat ["test("
        ++ q (name e
        ++ ": "
        ++ label)
        ++ ", () => assert.ok("
        ++ call i args
        ++ "));\n" | (label,args) <- cases e]
        ++ "test("
        ++ q (name e
        ++ ": property")
        ++ ", () => fc.assert(fc.property("
        ++ comma (replicate (count e) "fc.integer({min: -2147483648, max: 2147483647})"
        ++ [lawFn i])
        ++ ")));\n"
    pyTests (i,e) = comment fn "#" e
        ++ "def "
        ++ lawFn i
        ++ "("
        ++ comma [v
        ++ ": int" | v <- vars e]
        ++ ") -> bool:\n    return "
        ++ predicate e
        ++ "\n\n"
        ++ concat ["def test_law"
        ++ show i
        ++ "_example"
        ++ show j
        ++ "() -> None:\n    # "
        ++ label
        ++ "\n    assert "
        ++ call i args
        ++ "\n\n" | (j,(label,args)) <- zip [0 :: Int ..] (cases e)]
        ++ "@given("
        ++ comma [v
        ++ "=st.integers(min_value=-(2**31), max_value=2**31-1)" | v <- vars e]
        ++ ")\ndef test_law"
        ++ show i
        ++ "_property("
        ++ comma [v
        ++ ": int" | v <- vars e]
        ++ ") -> None:\n    assert "
        ++ call i (vars e)
        ++ "\n\n"
    javaTests (i,e) = comment fn "//" e
        ++ "  private static boolean "
        ++ lawFn i
        ++ "("
        ++ comma ["int "
        ++ v | v <- vars e]
        ++ ") { return "
        ++ predicate e
        ++ "; }\n"
        ++ concat ["  @Test void law"
        ++ show i
        ++ "Example"
        ++ show j
        ++ "() { assertTrue("
        ++ call i args
        ++ "); }\n" | (j,(_,args)) <- zip [0 :: Int ..] (cases e)]
        ++ "  @Test void law"
        ++ show i
        ++ "Property() { PropertyChecker.forAll("
        ++ javaGenerator e
        ++ ", value -> "
        ++ call i (javaValues e)
        ++ "); }\n"
    javaGenerator e
      | count e == 1 = "Generator.integers()"
      | otherwise = "Generator.from(data -> java.util.List.of(" ++ comma (replicate (count e) "data.generate(Generator.integers())") ++ "))"
    javaValues e
      | count e == 1 = ["value"]
      | otherwise = ["value.get(" ++ show j ++ ")" | j <- [0..count e-1]]
    goTests (i,e) = comment fn "//" e
        ++ "func "
        ++ lawFn i
        ++ "("
        ++ comma [v
        ++ " int32" | v <- vars e]
        ++ ") bool { return "
        ++ predicate e
        ++ " }\n"
        ++ "func TestLaw"
        ++ show i
        ++ "(t *testing.T) {\n"
        ++ concat [" t.Run("
        ++ q label
        ++ ", func(t *testing.T) { if !"
        ++ call i args
        ++ " { t.Fatal("
        ++ q (name e)
        ++ ") } })\n" | (label,args) <- cases e]
        ++ " rapid.Check(t, func(t *rapid.T) {\n"
        ++ concat ["  "
        ++ v
        ++ " := rapid.Int32().Draw(t, "
        ++ q (inputName inp)
        ++ ")\n" | inp <- inputs e, let v = inputId inp]
        ++ "  if !"
        ++ call i (vars e)
        ++ " { t.Fatalf(\"law failed: %v\", []int32{"
        ++ comma (vars e)
        ++ "}) }\n })\n}\n"
    hsDefs (i,e) = comment fn "--" e
        ++ lawFn i
        ++ " :: "
        ++ concat (replicate (count e) "Int32 -> ")
        ++ "Bool\n"
        ++ lawFn i
        ++ " "
        ++ unwords (vars e)
        ++ " = "
        ++ predicate e
        ++ "\n"
    hsTests (i,e) = concat ["  it "
        ++ q (name e
        ++ ": "
        ++ label)
        ++ " $ "
        ++ call i args
        ++ " `shouldBe` True\n" | (label,args) <- cases e]
        ++ "  it "
        ++ q (name e
        ++ ": property")
        ++ " $ hedgehog $ do\n"
        ++ concat ["    "
        ++ v
        ++ " <- forAll (Gen.int32 Range.constantBounded)\n" | v <- vars e]
        ++ "    assert ("
        ++ call i (vars e)
        ++ ")\n"
    ktq = concatMap (\c -> if c == '$' then "\\$" else [c]) . q
    ktDefs (i,e) = comment fn "//" e ++ "private fun " ++ lawFn i ++ "(" ++ comma [v ++ ": Int" | v <- vars e] ++ "): Boolean = " ++ predicate e ++ "\n"
    ktTests (i,e) = concat ["  "
        ++ ktq (name e
        ++ ": "
        ++ label)
        ++ " { "
        ++ call i args
        ++ " shouldBe true }\n" | (label,args) <- cases e]
        ++ "  "
        ++ ktq (name e
        ++ ": property")
        ++ " { checkAll(Arb.list(Arb.int(), "
        ++ show (count e)
        ++ ".."
        ++ show (count e)
        ++ ")) { values -> "
        ++ call i ["values["
        ++ show j
        ++ "]" | j <- [0..count e-1]]
        ++ " shouldBe true } }\n"
    tests = case target of
      "python" -> generated "#"
          ++ "from hypothesis import given, strategies as st\n"
          ++ (if null (functions u) then "" else "from "
          ++ unitName u
          ++ " import "
          ++ comma (map (fn . fst) (functions u))
          ++ "\n")
          ++ "\n"
          ++ concatMap pyTests indexed
      "java" -> generated "//"
          ++ pkg
          ++ "import org.jetbrains.jetCheck.Generator;\nimport org.jetbrains.jetCheck.PropertyChecker;\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertTrue;\npublic final class "
          ++ className
          ++ "LawSpecTest {\n"
          ++ concatMap javaTests indexed
          ++ "}\n"
      "go" -> generated "//" ++ "package " ++ base ++ "\nimport (\"testing\"; \"pgregory.net/rapid\")\n" ++ concatMap goTests indexed
      "haskell" -> generated "--"
          ++ "module "
          ++ moduleName
          ++ "Spec (spec) where\nimport Data.Int (Int32)\nimport qualified "
          ++ moduleName
          ++ " as Impl\nimport Test.Hspec\nimport Test.Hspec.Hedgehog (hedgehog)\nimport Hedgehog (assert, forAll)\nimport qualified Hedgehog.Gen as Gen\nimport qualified Hedgehog.Range as Range\n"
          ++ concatMap hsDefs indexed
          ++ "spec :: Spec\nspec = do\n"
          ++ (if null ls then "  pure ()\n" else concatMap hsTests indexed)
      "kotlin" -> generated "//"
          ++ pkg
          ++ "import io.kotest.core.spec.style.StringSpec\nimport io.kotest.matchers.shouldBe\nimport io.kotest.property.Arb\nimport io.kotest.property.arbitrary.int\nimport io.kotest.property.arbitrary.list\nimport io.kotest.property.checkAll\n"
          ++ concatMap ktDefs indexed
          ++ "class "
          ++ className
          ++ "LawSpecTest : StringSpec({\n"
          ++ concatMap ktTests indexed
          ++ "})\n"
      _ -> generated "//"
          ++ "import { test } from 'node:test';\nimport assert from 'node:assert/strict';\nimport fc from 'fast-check';\nimport { "
          ++ comma (map (fn . fst) (functions u))
          ++ " } from '../src/"
          ++ slash
          ++ (if target == "typescript" then ".js" else ".mjs")
          ++ "';\n"
          ++ concatMap jsTests indexed

-- Paths and imports are transformed together so custom layouts remain executable.
emitWithLayout :: String -> Maybe String -> Maybe String -> [Unit] -> [Expanded] -> Either [Diagnostic] [Artifact]
emitWithLayout target sourceDir testDir us es = do
  files <- emit target us es
  let defaults = case target of
        "java" -> ("src/main/java", "src/test/java")
        "kotlin" -> ("src/main/kotlin", "src/test/kotlin")
        "python" -> ("src", "tests")
        "go" -> ("", "")
        _ -> ("src", "test")
      src = maybe (fst defaults) id sourceDir
      tst = maybe (snd defaults) id testDir
      safe p = (null p && target == "go") || (not (null p) && all (\part -> not (null part) && part /= "." && part /= ".." && all (\c -> isAlphaNum c || c `elem` ("_-" :: String)) part) (split '/' p))
  unless (safe src && safe tst) (Left [Diagnostic "layout" "output directories must be relative paths without traversal" Nothing])
  unless (target /= "go" || src == tst) (Left [Diagnostic "layout" "Go adapters and tests must share a source directory" Nothing])
  let prefix p f = if null p then f else p ++ "/" ++ f
      move old new f = prefix new (maybe f id (stripPrefix (if null old then "" else old ++ "/") f))
      rel a b = case (a,b) of
        (x:xs,y:ys) | x == y -> rel xs ys
        _ -> intercalate "/" (replicate (length a) ".." ++ b)
      relative = rel (split '/' tst) (split '/' src)
      importRoot = if null relative then "." else if ".." `isPrefixOf` relative then relative else "./" ++ relative
      replace old new text
        | null text = []
        | Just rest <- stripPrefix old text = new ++ replace old new rest
        | c:rest <- text = c:replace old new rest
        | otherwise = []
      adjust a = a { artifactPath = if ownership a == "user" then move (fst defaults) src (artifactPath a) else move (snd defaults) tst (artifactPath a)
                   , artifactContent = if target `elem` ["javascript","typescript"] && ownership a == "generated" then replace " } from '../src/" (" } from '"
                       ++ importRoot
                       ++ "/") (artifactContent a) else artifactContent a }
      result = map adjust files
  unless (length result == length (nub (map (map toLower . artifactPath) result))) (Left [Diagnostic "collision" "custom layout causes an output collision" Nothing])
  pure result
