-- | Native Gleam tokens and types. Shared Core expressions and runtime values
-- are compiled once on BEAM, with checked bridges at every public function.
-- ref:DEC-idiomatic-generated-types ref:DEC-readable-output-default
module LawSpec.GleamCode (string, call, tuple, function, external, fileDoc, nativeType, imports) where

import qualified LawSpec.Core as C
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.BeamCode as E
import LawSpec.Scalar (primitive, family, Family(..))
import Data.Char (ord)
import Numeric (showHex)

string :: String -> D.Doc
string s = D.text ('"' : concatMap escape s ++ "\"")
  where
    escape c | c == '"' || c == '\\' = ['\\',c]
    escape '\n' = "\\n"
    escape '\r' = "\\r"
    escape '\t' = "\\t"
    escape c | ord c < 32 || ord c >= 127 = "\\u{" ++ showHex (ord c) "}"
    escape c = [c]

call :: String -> [D.Doc] -> D.Doc
call name args = D.text name <> D.delimit 2 "(" ")" args

tuple :: [D.Doc] -> D.Doc
tuple = D.delimit 2 "#(" ")"

function :: String -> [D.Doc] -> D.Doc -> [D.Doc] -> D.Doc
function name args result body = D.group (D.text "pub fn " <> call name args <> D.text " -> " <> result <>
  D.text " {" <> D.nest 2 (D.softline <> D.joinWith D.softline body) <> D.softline <> D.text "}")

external :: String -> String -> String -> [D.Doc] -> D.Doc -> D.Doc
external owner foreignName name args result = call "@external" [D.text "erlang",string owner,string foreignName] <>
  D.hardline <> D.text "pub fn " <> call name args <> D.text " -> " <> result

fileDoc :: Bool -> [D.Doc] -> D.Doc
fileDoc editable body = D.text (if editable then "// User-owned LawSpec adapter. Implement these functions." else "// Generated by LawSpec. Do not edit.") <>
  D.hardline <> D.hardline <> D.joinWith (D.hardline <> D.hardline) body <> D.hardline

nativeType :: Bool -> [(C.Id,String)] -> [(C.Id,String)] -> C.Type -> Either String D.Doc
nativeType localData names parameters ty = case ty of
  C.TypeVariable identity -> maybe (Left "unbound Gleam native type parameter") (Right . D.text) (lookup identity parameters)
  C.Constructor n args -> do
    ts <- mapM argument args
    let applied name = if null ts then D.text name else call name ts
    case n of
      "List" -> pure (applied "List")
      "Maybe" -> pure (applied "option.Option")
      "Either" -> pure (call "Result" (reverse ts))
      "Nullable" -> pure (applied "types.Nullable")
      "Optional" -> pure (applied "types.Optional")
      _ | Just p <- primitive n, null ts -> pure $ case family p of
        IntegerFamily -> D.text "Int"
        Boolean -> D.text "Bool"
        Floating -> D.text ("types." ++ n)
        Complex -> D.text ("types." ++ n)
        Exact -> D.text ("types." ++ n)
        Character -> D.text "Int"
        Sequence -> case n of "Text" -> D.text "String"; "Bytes" -> D.text "BitArray"; _ -> call "List" [D.text "Int"]
        Identity -> D.text "types.Symbol"
        Absence -> D.text (if n == "Unit" then "Nil" else "types." ++ n)
      _ -> maybe (Left ("no Gleam native type: " ++ n))
        (pure . applied . ((if localData then "" else "data.") ++) . E.pascal) (lookup (C.Id n) names)
  C.Arrow _ _ -> Left "function-valued Gleam data is unsupported"
  where
    argument (C.TypeArgument t) = nativeType localData names parameters t
    argument (C.IndexArgument _) = Left "unerased Gleam type index"

imports :: Bool -> [C.Type] -> [D.Doc]
imports localData types =
  [D.text "import gleam/option" | "Maybe" `elem` names] ++
  [D.text "import lawspec/types" | any (`elem` names) (words "Nullable Optional Float32 Float64 Complex64 Complex128 Rational Decimal Symbol Null Undefined")] ++
  [D.text "import lawspec/data" | not localData && any user names]
  where
    names = concatMap named types
    named (C.Constructor n args) = n : concat [named t | C.TypeArgument t <- args]
    named (C.Arrow a b) = named a ++ named b
    named _ = []
    user n = primitive n == Nothing && n `notElem` words "List Maybe Either Nullable Optional"
