-- Native sealed interfaces and variants follow Go+'s resolved enum lowering.
module LawSpec.GoData (emitGoData, goDataType, goTypeReference, emitGoSchema, emitGoSchemaWithProfile, goCodec, goCodecWithContext, emitGoCodecs, requiresSchema, goDataKey, validateGoBindings, identifier, goNativeCodec, emitGoNativeCodecs, goGeneratedNames, goNativeTypeWithParameters) where

import LawSpec.GoTypeRefs
import qualified LawSpec.GoExpr as E
import LawSpec.Core.Total (constructorProofContracts)
import Control.Monad (unless, forM)
import Data.Char (isAscii, isAlphaNum, isLetter, toUpper, toLower, ord)
import Data.List (intercalate, nub, find)
import LawSpec.NativeBinding
import Numeric (showHex)
import qualified LawSpec.Core as C
import LawSpec.Core.Types (makeRegistry, checkType)
import LawSpec.Scalar (nativeRepresentation, primitives, primitiveName)
import qualified LawSpec.Core.Schema as S
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T
import qualified LawSpec.Code.Doc as D

type Names = [(C.Id, String)]

capitalize :: String -> String
capitalize [] = []
capitalize (c:cs) = toUpper c:cs

identifier :: String -> Either String ()
identifier name = unless valid (Left ("invalid Go data identifier: " ++ name))
  where
    valid = case name of
      c:cs -> isAscii c && isLetter c && all (\x -> isAscii x && (isAlphaNum x || x == '_')) cs
      [] -> False

namesFor :: [C.DataDeclaration] -> Either String Names
namesFor declarations = do
  let candidates = concat
        [[(C.dataId d, capitalize (C.dataName d))] ++
          [(C.constructorId c, capitalize (C.dataName d) ++ capitalize (C.constructorName c)) | c <- C.dataConstructors d]
        | d <- declarations]
      duplicate name xs = length (filter ((== map toLower name) . map toLower . snd) xs) > 1
      reserved name = take 7 name == "LawSpec"
      qualified = [(identity, if duplicate name candidates || reserved name then qualify (C.idText identity) else name) | (identity,name) <- candidates]
      names = [(identity, if duplicate name qualified || reserved name then "Data" ++ name ++ "_" ++ concatMap (\c -> showHex (ord c) "_") (C.idText identity) else name) | (identity,name) <- qualified]
  mapM_ (identifier . snd) names
  unless (length names == length (nub (map (map toLower . snd) names))) (Left "conflicting Go data identities")
  pure names
  where
    qualify = concatMap capitalize . words . map (\c -> if isAlphaNum c then c else ' ')

goGeneratedNames :: [C.DataDeclaration] -> Either String [String]
goGeneratedNames declarations = map snd <$> namesFor declarations

applied :: String -> [String] -> String
applied name [] = name
applied name args = name ++ "[" ++ intercalate ", " args ++ "]"

typeText :: Names -> [(C.Id, String)] -> C.Type -> Either String String
typeText names parameters ty = case ty of
  C.TypeVariable variable -> maybe (Left "unbound Go data parameter") Right (lookup variable parameters)
  C.Constructor name arguments -> do
    args <- mapM argument arguments
    case lookup (C.Id name) names of
      Just native -> pure (applied native args)
      Nothing -> case (name,args) of
        ("List",[inner]) -> pure ("[]" ++ inner)
        ("Maybe",[_]) -> pure (applied "LawSpecMaybe" args)
        ("Either",[_,_]) -> pure (applied "LawSpecEither" args)
        ("Nullable",[_]) -> pure (applied "LawSpecNullable" args)
        ("Optional",[_]) -> pure (applied "LawSpecOptional" args)
        ("Integer",[]) -> pure "*LawSpecBigInt"
        (_,[]) -> maybe (Left ("no Go data representation for " ++ name)) Right
          (case lookup name [("Decimal","LawSpecDecimal"),("Symbol","*LawSpecSymbol"),
                            ("Unit","LawSpecUnit"),("Null","LawSpecNull"),("Undefined","LawSpecUndefined")] of
            Just native -> Just native
            Nothing -> nativeRepresentation "go" name)
        _ -> Left ("no Go data representation for " ++ show ty)
  _ -> Left ("no Go data representation for " ++ show ty)
  where
    argument (C.TypeArgument t) = typeText names parameters t
    argument _ = Left "indexed Go data is not supported"

goDataType :: [C.DataDeclaration] -> C.Type -> Either String String
goDataType declarations ty = do
  registry <- makeRegistry declarations
  checkType registry ty
  names <- namesFor declarations
  typeText names [] ty

emitGoData :: D.Layout -> String -> [C.DataDeclaration] -> Either String String
emitGoData layout packageName declarations = do
  _ <- makeRegistry declarations
  identifier packageName
  unless (packageName `notElem` words "break default func interface select case defer go map struct chan else goto package switch const fallthrough if range type continue for import return var")
    (Left "reserved Go package name")
  names <- namesFor declarations
  definitions <- mapM (definition names) declarations
  pure (D.render (if layout == D.Compact then D.CompactTabs else layout) (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
    D.text ("package " ++ packageName) <>
    (if null definitions then mempty else D.hardline <> D.hardline <>
      D.joinWith (D.hardline <> D.hardline) definitions) <> D.hardline))
  where
    definition names declaration = do
      name <- lookupName names (C.dataId declaration)
      let parameters = zip (C.dataParameters declaration)
            [candidate | n <- [0::Int ..], let candidate = "T" ++ show n, candidate `notElem` map snd names]
          args = map snd parameters
          generic = applied name [arg ++ " any" | arg <- args]
          marker = "lawSpec" ++ name
      variants <- forM (C.dataConstructors declaration) $ \variant -> do
        variantName <- lookupName names (C.constructorId variant)
        fields <- forM (C.constructorFields variant) $ \field -> do
          let fieldName = capitalize (C.binderName field)
          identifier fieldName
          fieldType <- typeText names parameters (C.binderType field)
          pure (fieldName,fieldType)
        unless (length fields == length (nub (map fst fields))) (Left "Go constructor fields collide after export capitalization")
        let header = "type " ++ applied variantName [arg ++ " any" | arg <- args] ++ " struct"
            width = maximum (0 : map (length . fst) fields)
            field (n,t) = D.text (n ++ replicate (width - length n + 1) ' ' ++ t)
            body = if null fields then D.text "{}" else D.text " " <> D.block 8 (D.joinWith D.hardline (map field fields))
            method = "func (" ++ applied variantName args ++ ") " ++ marker ++ "(" ++ intercalate ", " args ++ ") {}"
        pure (D.text header <> body <> D.hardline <> D.hardline <> D.text method)
      pure (D.text ("type " ++ generic ++ " interface ") <>
        D.block 8 (D.text (marker ++ "(" ++ intercalate ", " args ++ ")")) <>
        (if null variants then mempty else D.hardline <> D.hardline <> D.joinWith (D.hardline <> D.hardline) variants))
    lookupName names identity = maybe (Left "unplanned Go data name") Right (lookup identity names)

-- Schema descriptions and native declarations share resolved Core identities.
q :: String -> String
q = T.unpack . T.decodeUtf8 . encode

emitGoSchema :: D.Layout -> String -> [C.DataDeclaration] -> Either String String
emitGoSchema = emitGoSchemaWithProfile 64

emitGoSchemaWithProfile :: Int -> D.Layout -> String -> [C.DataDeclaration] -> Either String String
emitGoSchemaWithProfile bits layout packageName declarations = do
  -- Reuse declaration validation, including exported name planning.
  _ <- emitGoData layout packageName declarations
  _ <- either (Left . show) Right (constructorProofContracts bits declarations)
  (schemas,contracts) <- S.dataSchemasWithContracts declarations
  callbacks <- forM contracts $ \contract -> do
    predicates <- forM (S.contractPredicates contract) $ \predicate -> do
      let fields = zip (map C.binderId (S.contractFields contract))
            ["fields[" ++ show i ++ "]" | i <- [0 :: Int ..]]
          nested = zip (nub (nestedIds predicate)) ["local" ++ show i | i <- [0 :: Int ..]]
          local identity = maybe "invalidField" id (lookup identity (fields ++ nested))
          ref ty = do
            value <- reference <$> S.typeReference (S.contractParameters contract) ty
            pure (E.call "lsSubstitute" [D.text value,D.text "types"])
          key ty = do
            value <- ref ty
            pure (value <> D.text ".key()")
      body <- E.renderExpressionWithContext declarations (D.text "bits") "schema" ref key local
        (\_ _ -> Left "external call in constructor predicate") predicate
      pure (D.text "func(schema *lawSpecSchema, types []lawSpecTypeRef, fields []LawSpecValue, bits int, symbols map[string]*lawSpecSymbol) bool " <>
        D.block 8 (D.text "return " <> E.call "lsTruth" [body]))
    pure (D.text ("{" ++ q (S.contractTag contract) ++ ", []lawSpecFieldPredicate") <>
      D.block 8 (D.joinWith D.hardline [predicate <> D.text "," | predicate <- predicates]) <> D.text "}")
  let array ty [] = D.text ("[]" ++ ty ++ "{}")
      array ty values = D.text ("[]" ++ ty) <> D.block 8
        (D.joinWith D.hardline [value <> D.text "," | value <- values])
      field value = D.text ("{" ++ q (S.fieldName value) ++ ", " ++ reference (S.fieldType value) ++ "}")
      constructor value = D.text ("{" ++ q (S.constructorTag value) ++ ", ") <>
        array "lawSpecFieldSchema" (map field (S.fields value)) <> D.text "}"
      definition value = D.text ("{" ++ q (S.typeName value) ++ ", " ++ show (S.parameterCount value) ++ ", ") <>
        array "lawSpecConstructorSchema" (map constructor (S.constructors value)) <> D.text "}"
      body = D.text "return lsNewSchemaWithContracts(" <> D.nest 8 (D.hardline <>
        array "lawSpecDataSchema" (map definition schemas) <> D.text "," <> D.hardline <>
        array "string" (map (D.text . q . primitiveName) primitives) <> D.text "," <> D.hardline <>
        array "lawSpecConstructorContract" callbacks <> D.text ",") <>
        D.hardline <> D.text ")"
  pure (D.render (if layout == D.Compact then D.CompactTabs else layout) (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
    D.text ("package " ++ packageName) <> D.hardline <> D.hardline <>
    D.text "func lawSpecDataSchemaRegistry() *lawSpecSchema " <> D.block 8 body <> D.hardline))

  where
    nestedIds term = (case C.expressionNode term of
      C.AllElements _ binder _ -> [C.binderId binder]
      C.AllPayloads _ predicates -> map (C.binderId . fst) predicates
      C.Match _ branches -> concatMap (map C.binderId . C.caseBinders) branches
      _ -> []) ++ concatMap nestedIds (C.children term)

-- Recursive codec factories are invoked inside conversion closures, so recursive
-- declarations do not recursively construct an infinite codec graph.
goCodec :: [C.DataDeclaration] -> C.Type -> Either String String
goCodec = goCodecUsing Nothing

goCodecWithContext :: String -> [C.DataDeclaration] -> C.Type -> Either String String
goCodecWithContext context = goCodecUsing (Just context)

goCodecUsing :: Maybe String -> [C.DataDeclaration] -> C.Type -> Either String String
goCodecUsing context declarations ty = do
  registry <- makeRegistry declarations
  checkType registry ty
  names <- namesFor declarations
  codec context names [] [] ty

codec :: Maybe String -> Names -> [(C.Id,String)] -> [(C.Id,String)] -> C.Type -> Either String String
codec = codecUsing "lawSpec" Nothing

codecUsing :: String -> Maybe Names -> Maybe String -> Names -> [(C.Id,String)] -> [(C.Id,String)] -> C.Type -> Either String String
codecUsing prefix nativeNames context names parameters codecs ty = case ty of
  C.TypeVariable variable -> maybe (Left "unbound Go codec parameter") Right (lookup variable codecs)
  C.Constructor name arguments -> do
    types <- mapM argument arguments
    children <- mapM (codecUsing prefix nativeNames context names parameters codecs) types
    native <- typeText (maybe names id nativeNames) parameters ty
    case lookup (C.Id name) names of
      Just dataName -> pure (invoke (prefix ++ dataName ++ "Codec") (["schema","bits"] ++ children ++ maybe [] pure context))
      Nothing -> case name of
        "List" -> pure (invoke "lsListCodec" (["schema","bits"] ++ children ++ maybe [] pure context))
        "Maybe" -> pure (invoke "lsMaybeCodec" (["schema","bits"] ++ children ++ maybe [] pure context))
        "Either" -> pure (invoke "lsEitherCodec" (["schema","bits"] ++ children ++ maybe [] pure context))
        "Nullable" -> pure (invoke "lsNullableCodec" (["schema","bits"] ++ children ++ maybe [] pure context))
        "Optional" -> pure (invoke "lsOptionalCodec" (["schema","bits"] ++ children ++ maybe [] pure context))
        _ | null types -> pure (invoke ("lsScalarCodec[" ++ native ++ "]") ["schema","bits",q name])
        _ -> Left "unsupported Go codec application"
  _ -> Left "unsupported Go codec type"
  where
    argument (C.TypeArgument value) = Right value
    argument _ = Left "indexed Go codec is not supported"
    invoke name arguments = name ++ "(" ++ intercalate ", " arguments ++ ")"

goNativeCodec :: [C.DataDeclaration] -> [ResolvedTypeBinding] -> C.Type -> Either String String
goNativeCodec declarations mappings ty = do
  names <- namesFor declarations
  codecUsing "lawSpecNative" (Just (nativeNamesFor names mappings)) (Just "symbols") names [] [] ty

goNativeTypeWithParameters :: [C.DataDeclaration] -> [ResolvedTypeBinding] -> [(C.Id,String)] -> C.Type -> Either String String
goNativeTypeWithParameters declarations mappings parameters ty = do
  names <- namesFor declarations
  typeText (nativeNamesFor names mappings) parameters ty

nativeNamesFor :: Names -> [ResolvedTypeBinding] -> Names
nativeNamesFor names mappings = [(identity, maybe name (intercalate "." . referenceParts)
  (lookup identity references)) | (identity,name) <- names]
  where
    references = [(C.dataId (resolvedDeclaration m), resolvedNativeType m) | m <- mappings] ++
      [(C.constructorId (resolvedConstructor c), resolvedNativeConstructor c) | m <- mappings, c <- resolvedConstructors m]

emitGoNativeCodecs :: D.Layout -> String -> [(String,String)] -> [C.DataDeclaration] -> [ResolvedTypeBinding] -> [C.Id] -> Either String String
emitGoNativeCodecs layout packageName imports declarations mappings needed =
  emitCodecs "lawSpecNative" mappings (Just needed) imports layout packageName declarations

emitGoCodecs :: D.Layout -> String -> [C.DataDeclaration] -> Either String String
emitGoCodecs = emitCodecs "lawSpec" [] Nothing []

emitCodecs :: String -> [ResolvedTypeBinding] -> Maybe [C.Id] -> [(String,String)] -> D.Layout -> String -> [C.DataDeclaration] -> Either String String
emitCodecs prefix mappings needed imports layout packageName declarations = do
  _ <- emitGoData layout packageName declarations
  names <- namesFor declarations
  definitions <- mapM (definition names) [d | d <- declarations, maybe True (C.dataId d `elem`) needed]
  pure (D.render (if layout == D.Compact then D.CompactTabs else layout) (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
    D.text ("package " ++ packageName) <>
    (if null imports then mempty else D.hardline <> D.hardline <>
      D.joinWith D.hardline [D.text ("import " ++ alias ++ " " ++ q path) | (alias,path) <- imports]) <>
    (if null definitions then mempty else D.hardline <> D.hardline <>
      D.joinWith (D.hardline <> D.hardline) definitions) <> D.hardline))
  where
    line = D.text
    linesDoc = D.joinWith D.hardline
    definition names declaration = do
      name <- lookupName names (C.dataId declaration)
      let parameters = zip (C.dataParameters declaration)
            [candidate | n <- [0::Int ..], let candidate = "T" ++ show n, candidate `notElem` map snd names]
          arguments = map snd parameters
          codecParameters = zip (C.dataParameters declaration) ["element" ++ show n | n <- [0::Int ..]]
          native = applied (maybe name id (lookup (C.dataId declaration) (nativeNamesFor names mappings))) arguments
          typeRef = "lsNamed(" ++ intercalate ", " (q (C.idText (C.dataId declaration)) : [value ++ ".typeRef" | (_,value) <- codecParameters]) ++ ")"
          params = ["schema *lawSpecSchema", "bits int"] ++
            [value ++ " lawSpecCodec[" ++ ty ++ "]" | ((_,ty),(_,value)) <- zip parameters codecParameters] ++
            ["contexts ...map[string]*lawSpecSymbol"]
          signature = "func " ++ applied (prefix ++ name ++ "Codec") [arg ++ " any" | arg <- arguments] ++
            "(" ++ intercalate ", " params ++ ") lawSpecCodec[" ++ native ++ "] "
      variants <- forM (C.dataConstructors declaration) $ \variant -> do
        variantName <- lookupName (nativeNamesFor names mappings) (C.constructorId variant)
        fields <- forM (C.constructorFields variant) $ \field -> do
          expression <- codecUsing prefix (Just (nativeNamesFor names mappings)) (Just "symbols") names parameters codecParameters (C.binderType field)
          fieldType <- typeText names parameters (C.binderType field)
          let mapped = find ((== C.constructorId variant) . C.constructorId . resolvedConstructor)
                [c | m <- mappings,c <- resolvedConstructors m]
              fieldName = maybe (capitalize (C.binderName field)) id
                (mapped >>= lookup (C.binderId field) . map (\(f,n) -> (C.binderId f,n)) . resolvedFields)
          pure (fieldName,C.binderName field,fieldType,expression)
        let mapped = find ((== C.constructorId variant) . C.constructorId . resolvedConstructor)
              [c | m <- mappings,c <- resolvedConstructors m]
            unit = maybe False ((== UnitConstructor) . resolvedConstructorStyle) mapped
            tag = C.idText (C.constructorId variant)
            concrete = applied variantName arguments
            width = maximum (0 : [length n | (n,_,_,_) <- fields])
            construct = if unit then line variantName else if null fields then line (concrete ++ "{}") else
              line concrete <> D.block 8 (linesDoc
                [line (n ++ ":" ++ replicate (width - length n + 1) ' ' ++ expression ++ ".toNative(data.fields[" ++ show index ++ "]),")
                | (index,(n,_,_,expression)) <- zip [0::Int ..] fields])
            encodeFields = if null fields then line "nil" else
              line "[]LawSpecValue" <> D.block 8 (linesDoc
                [line ("lsSchemaContext(" ++ q (tag ++ "." ++ original) ++ ", func() LawSpecValue ") <>
                  D.block 8 (line ("return " ++ expression ++ ".encode(native." ++ n ++ ", path)")) <> line "),"
                | (n,original,_,expression) <- fields])
            decode = line ("case " ++ q tag ++ ":") <> D.nest 8 (D.hardline <> line "return " <> construct)
            result = line ("return schema.construct(typeRef, " ++ q tag ++ ", ") <> encodeFields <> line ", bits, symbols)"
            encodeValue = if prefix == "lawSpec" then
              line ("case " ++ concrete ++ ":") <> D.nest 8 (D.hardline <> result)
              else line (if unit then "if any(value) == any(" ++ variantName ++ ") "
                else "if native, ok := any(value).(" ++ concrete ++ "); ok ") <>
                D.block 8 ((if not unit && null fields then line "_ = native" <> D.hardline else mempty) <> result)
        pure (decode,encodeValue)
      let decode = line ("func(value LawSpecValue) " ++ native ++ " ") <> D.block 8
            (line "data := value.Data.(lawSpecData)" <> D.hardline <>
             line "switch data.tag {" <> D.hardline <>
             linesDoc (map fst variants ++ [line "default:" <> D.nest 8 (D.hardline <> line "panic(\"unknown checked constructor\")")]) <>
             D.hardline <> line "}")
          encodeValue = line ("func(value " ++ native ++ ", path lawSpecPath) LawSpecValue ") <> D.block 8
            (if prefix == "lawSpec" then
              line "switch native := value.(type) {" <> D.hardline <>
              linesDoc (map snd variants ++ [line "default:" <> D.nest 8 (D.hardline <> line "_ = native" <> D.hardline <> failure)]) <>
              D.hardline <> line "}"
             else linesDoc (map snd variants ++ [failure]))
          failure = line ("panic(" ++ q ("unexpected native constructor for " ++ C.idText (C.dataId declaration)) ++ ")")
      (setup, hookDecode, hookEncode) <- case find ((== C.dataId declaration) . C.dataId . resolvedDeclaration) mappings >>= resolvedCodec of
        Nothing -> pure (mempty, decode, encodeValue)
        Just hook -> do
          let reference = intercalate "." . referenceParts
              invoke name args = name ++ "(" ++ intercalate ", " args ++ ")"
              logical = invoke ("lawSpec" ++ name ++ "Codec")
                (["schema","bits"] ++ [invoke "lsLogicalCodec" ["schema","bits",v ++ ".typeRef","symbols"] |
                  (_,v) <- codecParameters] ++ ["symbols"])
              context direction result expression =
                line ("return lsNativeContext(" ++ q ("native codec " ++ C.idText (C.dataId declaration) ++ " " ++ direction) ++ ", func() " ++ result ++ " ") <>
                D.block 8 (line "converted, err := " <> expression <> D.hardline <>
                  line "if err != nil " <> D.block 8 (line "panic(err)") <> D.hardline <>
                  line (if direction == "toNative" then "return converted" else "return canonical.encode(converted, path)")) <> line ")"
              decodeArgs = line "canonical.toNative(value)" : [line (v ++ ".toNative") | (_,v) <- codecParameters]
              encodeArgs = line "value" : [line ("func(child " ++ ty ++ ") LawSpecValue ") <>
                D.block 8 (line ("return " ++ v ++ ".encode(child, path)")) |
                  ((_,ty),(_,v)) <- zip parameters codecParameters]
              call name args = line (name ++ "(") <>
                D.nest 8 (D.hardline <> D.joinWith (line "," <> D.hardline) args <> line ",") <>
                D.hardline <> line ")"
          pure (line ("canonical := " ++ logical) <> D.hardline,
            line ("func(value LawSpecValue) " ++ native ++ " ") <> D.block 8
              (context "toNative" native (call (reference (codecToNative hook)) decodeArgs)),
            line ("func(value " ++ native ++ ", path lawSpecPath) LawSpecValue ") <> D.block 8
              (context "fromNative" "LawSpecValue" (call (reference (codecFromNative hook)) encodeArgs)))
      let body = line "symbols := lsSchemaSymbols(contexts)" <> D.hardline <> line ("typeRef := " ++ typeRef) <> D.hardline <> setup <>
            line "return lsCodec(schema, bits, typeRef," <>
            D.nest 8 (D.hardline <> hookDecode <> line "," <> D.hardline <> hookEncode <> line ", symbols)")
      pure (line signature <> D.block 8 body)
    lookupName names identity = maybe (Left "unplanned Go codec name") Right (lookup identity names)

validateGoBindings :: [C.DataDeclaration] -> [String] -> Either String ()
validateGoBindings declarations functions = do
  names <- namesFor declarations
  let collisions = [name | name <- functions, name `elem` map snd names || take 7 name == "LawSpec"]
  unless (null collisions) (Left ("Go adapter names collide with generated support: " ++ intercalate ", " collisions))
