-- Go native entry points and checked bodies live in each unit's source package.
module LawSpec.GoDefinitions (emitGoDefinitions, definitionCalls) where

import LawSpec.Core.Stages (stageFailures)
import Control.Monad (forM)
import LawSpec.Core.Policy
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.GoData as Native
import qualified LawSpec.GoExpr as E
import qualified LawSpec.Code.Doc as D
import Data.Char (toUpper)
import Data.List (nub, intercalate)

definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d), "lawSpecEvaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitGoDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitGoDefinitions _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitGoDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  bodies <- mapM (\(i, (owner, d)) -> (,) (owner, definitionOrchestrates d) <$> implementation contracts (i, d))
    (zip [0::Int ..] [(unitId u, d) | u <- units, d <- unitDefinitions u])
  -- A workflow calls its own package's adapters, so only that package has it.
  mapM (\unit -> unitFile [body | ((owner, orchestrates), body) <- bodies, not orchestrates || owner == unitId unit] unit) units
  where
    callees = definitionCalls units
    definitionIds = map (declarationId . definitionDeclaration) (concatMap unitDefinitions units)
    adapters = [(declarationId d, (idText (unitId u), d)) | u <- units, d <- unitDeclarations u,
      declarationId d `notElem` definitionIds]
    width = D.text (show bits)
    schema = "_lawSpecDefinitionSchema"
    symbols = D.text "symbols map[string]*LawSpecSymbol"
    line = D.text
    assign name value = line (name ++ " := ") <> value
    schemaCall method ty value = do
      reference <- D.text <$> Native.goTypeReference ty
      pure (E.call (schema ++ "." ++ method) [reference,value,width,line "symbols"])
    contextual identity resultType body = line "return " <> E.call "lsNativeContext"
      [E.quoted (idText identity),line ("func() " ++ resultType ++ " ") <> D.block 8 body]
    unitFile bodies unit = do
      wrappers <- mapM native (unitDefinitions unit)
      let identity = idText (unitId unit)
          packageName = reverse (takeWhile (/= '.') (reverse identity))
          source = line "// Generated by LawSpec. Do not edit." <> D.hardline <>
            line ("package " ++ packageName) <> D.hardline <> D.hardline <>
            line ("var " ++ schema ++ " = lawSpecDataSchemaRegistry()") <> D.hardline <> D.hardline <>
            line "type lawSpecDefinitions struct{}" <> D.hardline <> D.hardline <>
            line "var LawSpecDefinitions lawSpecDefinitions" <> D.hardline <> D.hardline <>
            D.joinWith (D.hardline <> D.hardline) (wrappers ++ bodies) <> D.hardline
      pure (Artifact (map (\c -> if c == '.' then '/' else c) identity ++ "/lawspec_definitions.go")
        (D.render (if layout == D.Compact then D.CompactTabs else layout) source) "generated" "source")
    implementation contracts (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          names = zip (nub (map binderId binders)) ["value" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved Go local") id (lookup identity names)
          arguments = [line (local (binderId binder) ++ " LawSpecValue") | binder <- definitionArguments d]
          external term values = case expressionNode term of
            ExternalCall identity _ | Just name <- lookup identity callees ->
              pure (E.call name (line "symbols":values))
            -- An orchestration calls an adapter of its own package natively:
            -- the values cross to native and back through the codecs.
            ExternalCall identity _ | Just (_, adapter) <- lookup identity adapters -> do
              let (parameterTypes, resultType) = functionType (declarationType adapter)
              codecs <- mapM (Native.goCodecWithContext "symbols" declarations) parameterTypes
              resultCodec <- Native.goCodecWithContext "symbols" declarations resultType
              nativeResult <- Native.goDataType declarations resultType
              -- A Unit argument is passed as its logical value, as the
              -- adapter stub declares it.
              let call = E.call (capitalize (declarationName adapter))
                    [if ty == Constructor "Unit" [] then value else E.call ("codec" ++ show i ++ ".toNative") [value]
                    | (i, (ty, value)) <- zip [0::Int ..] (zip parameterTypes values)]
                  -- Within its stage's timeout and hedge, when it has them.
                  result
                    | declarationAsync adapter = E.call "lsAwaitStep"
                        [ line "symbols"
                        , line ("func() LawSpecTask[" ++ nativeResult ++ "] ") <> D.block 8 (line "return " <> call)
                        , line ("func(native " ++ nativeResult ++ ") LawSpecValue ") <> D.block 8 (line "return resultCodec.fromNative(native)") ]
                    | otherwise = E.call "resultCodec.fromNative" [call]
              pure (line "func() LawSpecValue " <> D.block 8 (D.joinWith D.hardline
                ([line ("schema := " ++ schema), line ("bits := " ++ show bits), line "_ = bits"] ++
                 [assign ("codec" ++ show i) (line codec) | (i, (ty, codec)) <- zip [0::Int ..] (zip parameterTypes codecs), ty /= Constructor "Unit" []] ++
                 [assign "resultCodec" (line resultCodec), line "return " <> result])) <> line "()")
            _ -> Left "unresolved Go total call"
      rendered <- E.renderExpression declarations bits schema local external (definitionBody d)
      -- A workflow stage with policies runs under the workflow runtime.
      body <- case definitionPolicy d of
        Nothing -> pure rendered
        Just policy | policyFrame policy ->
          pure (E.call "lsRunWorkflow" [line "symbols", line "func() LawSpecValue " <> D.block 8 (line "return " <> rendered)])
        Just policy -> do
          failures <- forM (stageFailures d) $ \(kind, value) ->
            (\rendered' -> line ("case " ++ show kind ++ ": return ") <> rendered') <$>
              E.renderExpression declarations bits schema local external value
          let fail' = line "func(kind string) LawSpecValue " <> D.block 8 (D.joinWith D.hardline
                ([line "switch kind " <> D.block 8 (D.joinWith D.hardline failures) | not (null failures)] ++
                 [line "panic(\"unexpected stage failure: \" + kind)"]))
          config <- policyDoc (idText (declarationId (definitionDeclaration d))) fail' policy
          let key = case definitionArguments d of
                argument : _ -> line (local (binderId argument))
                [] -> line "LawSpecValue{}"
          pure (E.call "lsRunStage" [line "symbols", config,
            line "func() LawSpecValue " <> D.block 8 (line "return " <> rendered), key])
      -- Arguments and results were checked where they were built, decoded
      -- or drawn; the native wrappers check values crossing from adapters.
      let checks = []
          result = line "result"
      let contract = lookup (declarationId (definitionDeclaration d)) [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [assign "result" body,line "return " <> result])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checkedResult")] ++
                [(binderId b,"contractValue" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c ++ contractRuntimePostconditions c))]
              resolve identity = maybe (error "unbound Go definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression declarations bits schema resolve external predicate
                pure (E.call "lsRequireContract" [E.call "lsTruth" [expression],E.quoted stage])
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          pure (checks ++ pre ++ [assign "result" body,assign "checkedResult" result] ++
            post ++ [line "return checkedResult"])
      pure (line ("func lawSpecEvaluate" ++ show index) <>
        D.delimitTrailing 8 "(" ")" (symbols:arguments) <> line " LawSpecValue " <>
        D.block 8 (contextual (declarationId (definitionDeclaration d)) "LawSpecValue"
          (D.joinWith D.hardline statements)))
    evaluator identity = maybe (Left "unresolved Go policy definition") Right (lookup identity callees)
    policyDoc key fail' policy = do
      gates <- policyGates policy
      compensate <- case policyCompensate policy of
        Nothing -> pure (line "nil")
        Just undo -> (\name -> line ("func(value LawSpecValue) { _ = " ++ name ++ "(symbols, value) }")) <$> evaluator undo
      retry <- case policyRetry policy of
        Nothing -> pure (line "nil")
        Just r -> do
          let (kind, delay, step, factor, cap) = case retryStrategy r of
                Immediate -> ("immediate", 0, 0, 0, -1)
                Fixed d -> ("fixed", d, 0, 0, -1)
                Linear d s -> ("linear", d, s, 0, -1)
                Exponential d f c -> ("exponential", d, 0, f, maybe (-1) id c)
                Fibonacci d -> ("fibonacci", d, 0, 0, -1)
                Custom _ -> ("custom", 0, 0, 0, -1)
          condition <- case retryWhen r of
            Nothing -> pure (line "nil")
            Just p -> (\name -> line ("func(failure LawSpecValue) bool { return lsTruth(" ++ name ++ "(symbols, failure)) }")) <$> evaluator p
          decide <- case retryStrategy r of
            Custom f -> (\name -> line ("func(attempt int64, failure LawSpecValue, previous int64) (int64, bool) { return lsRetryDecision(" ++
              name ++ "(symbols, lsInteger64(attempt), failure, lsDuration(previous))) }")) <$> evaluator f
            _ -> pure (line "nil")
          pure (line "&lawSpecRetry" <> D.block 8 (D.joinWith D.hardline
            [ line ("Strategy: " ++ show (kind :: String) ++ ",")
            , line ("Delay: " ++ show (delay :: Integer) ++ ", Step: " ++ show (step :: Integer) ++ ", Factor: " ++ show (factor :: Integer) ++ ", Cap: " ++ show (cap :: Integer) ++ ",")
            , line ("Attempts: " ++ show (retryAttempts r) ++ ",")
            , line ("Jitter: " ++ show (jitterName (retryJitter r)) ++ ",")
            , line "When: " <> condition <> line ","
            , line "Decide: " <> decide <> line "," ]))
      pure (line "lawSpecStagePolicy" <> D.block 8 (D.joinWith D.hardline
        [ line ("Stage: " ++ show (policyStage policy) ++ ",")
        , line "Retry: " <> retry <> line ","
        , line ("Timeout: " ++ show (maybe (-1) id (policyTimeout policy)) ++ ",")
        , line ("Key: " ++ show key ++ ",")
        , line "Gates: []lawSpecGate" <> D.block 8 (D.joinWith D.hardline [gate <> line "," | gate <- gates]) <> line ","
        , line ("Cache: " ++ show (maybe (-1) id (policyCache policy)) ++ ",")
        , line ("Wraps: " ++ (if null (policyFailures policy) then "false" else "true") ++ ",")
        , line "Fail: " <> fail' <> line ","
        , line "Compensate: " <> compensate <> line ","
        , line ("Hedge: " ++ maybe "nil" (\h -> "&lawSpecHedge{Delay: " ++ show (hedgeDelay h) ++ ", Most: " ++ show (hedgeMost h) ++ "}") (policyHedge policy) ++ ",") ]))
    -- A gate's callbacks call the unit's copies of the resilience unit's
    -- state machines, with the policy's numbers.
    policyGates policy = do
      breaker <- forM (policyBreaker policy) $ \b -> do
        start <- evaluator (breakerStart b)
        admit <- evaluator (breakerAdmit b)
        record <- evaluator (breakerRecord b)
        pure (gateDoc "breaker" (start ++ "(symbols, lsInteger64(now))") (admit ++ "(symbols, state, lsInteger64(now))")
          (Just (record ++ "(symbols, " ++ integers [breakerFailures b, breakerWindow b, breakerCooldown b] ++ ", state, lsInteger64(now), lsBool(succeeded))")) (-2))
      limit <- forM (policyLimit policy) $ \l -> do
        start <- evaluator (limitStart l)
        admit <- evaluator (limitAdmit l)
        let numbers = integers [limitCount l, limitPeriod l]
        pure (gateDoc "limit" (start ++ "(symbols, " ++ numbers ++ ", lsInteger64(now))") (admit ++ "(symbols, " ++ numbers ++ ", state, lsInteger64(now))")
          Nothing (waitCode (limitWait l)))
      bulkhead <- forM (policyBulkhead policy) $ \b -> do
        start <- evaluator (bulkheadStart b)
        admit <- evaluator (bulkheadAdmit b)
        release <- evaluator (bulkheadRelease b)
        let n = integers [bulkheadLimit b]
        pure (gateDoc "bulkhead" (start ++ "(symbols, " ++ n ++ ", lsInteger64(now))") (admit ++ "(symbols, " ++ n ++ ", state, lsInteger64(now))")
          (Just (release ++ "(symbols, state)")) (waitCode (bulkheadWait b)))
      pure (maybe [] pure breaker ++ maybe [] pure limit ++ maybe [] pure bulkhead)
    gateDoc kind start admit finish wait = line "lawSpecGate" <> D.block 8 (D.joinWith D.hardline
      [ line ("Kind: " ++ show (kind :: String) ++ ",")
      , line ("Start: func(now int64) LawSpecValue { return " ++ start ++ " },")
      , line ("Admit: func(state LawSpecValue, now int64) LawSpecValue { return " ++ admit ++ " },")
      , line ("Finish: " ++ maybe "nil" (\f -> "func(state LawSpecValue, now int64, succeeded bool) LawSpecValue { return " ++ f ++ " }") finish ++ ",")
      , line ("Wait: " ++ show (wait :: Integer) ++ ",") ])
    integers numbers = intercalate ", " ["lsInteger64(" ++ show n ++ ")" | n <- numbers]
    waitCode wait = case wait of
      Nothing -> -2
      Just Nothing -> -1
      Just (Just d) -> d
    jitterName j = case j of
      NoJitter -> "none" :: String
      FullJitter -> "full"
      EqualJitter -> "equal"
      DecorrelatedJitter -> "decorrelated"
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          values = ["value" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.goDataType declarations) args
      resultType <- Native.goDataType declarations result
      codecs <- mapM (Native.goCodecWithContext "symbols" declarations) args
      resultCodec <- Native.goCodecWithContext "symbols" declarations result
      name <- maybe (Left "unresolved Go native call") Right (lookup (declarationId declaration) callees)
      let parameters = symbols : [line (value ++ " " ++ ty) | (value,ty) <- zip values types]
          inputs = concat [[assign ("codec" ++ show i) (line codec),
            assign ("argument" ++ show i) (E.call ("codec" ++ show i ++ ".fromNative") [line value])]
            | (i,(value,codec)) <- zip [0::Int ..] (zip values codecs)]
          invocation = E.call name (line "symbols" : [line ("argument" ++ show i) | i <- [0 .. length args - 1]])
      pure (line ("func (lawSpecDefinitions) " ++ capitalize (declarationName declaration)) <>
        D.delimitTrailing 8 "(" ")" parameters <> line (" " ++ resultType ++ " ") <>
        D.block 8 (contextual (declarationId declaration) resultType (D.joinWith D.hardline
          ([line ("schema := " ++ schema),line ("bits := " ++ show bits)] ++ inputs ++
           [assign "resultCodec" (line resultCodec),assign "result" invocation,
            line "return " <> E.call "resultCodec.toNative" [line "result"]]))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat
        [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
    capitalize [] = []
    capitalize (c:cs) = toUpper c:cs
