-- Go native entry points and checked bodies live in each unit's source package.
module LawSpec.GoDefinitions (emitGoDefinitions, definitionCalls) where

import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.GoData as Native
import qualified LawSpec.GoExpr as E
import qualified LawSpec.Code.Doc as D
import Data.Char (toUpper)
import Data.List (nub)

definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d), "lawSpecEvaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitGoDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitGoDefinitions _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitGoDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  bodies <- mapM (implementation contracts) (zip [0::Int ..] (concatMap unitDefinitions units))
  mapM (unitFile bodies) units
  where
    callees = definitionCalls units
    width = D.text (show bits)
    schema = "_lawSpecDefinitionSchema"
    symbols = D.text "symbols map[string]*LawSpecSymbol"
    line = D.text
    assign name value = line (name ++ " := ") <> value
    schemaCall method ty value = do
      reference <- D.text <$> Native.goTypeReference ty
      pure (E.call (schema ++ "." ++ method) [reference,value,width,line "symbols"])
    contextual identity resultType body = line "return " <> E.call "lsNativeContext"
      [E.quoted (idText identity),line ("func() " ++ resultType ++ " ") <> D.block 8 body]
    unitFile bodies unit = do
      wrappers <- mapM native (unitDefinitions unit)
      let identity = idText (unitId unit)
          packageName = reverse (takeWhile (/= '.') (reverse identity))
          source = line "// Generated by LawSpec. Do not edit." <> D.hardline <>
            line ("package " ++ packageName) <> D.hardline <> D.hardline <>
            line ("var " ++ schema ++ " = lawSpecDataSchemaRegistry()") <> D.hardline <> D.hardline <>
            line "type lawSpecDefinitions struct{}" <> D.hardline <> D.hardline <>
            line "var LawSpecDefinitions lawSpecDefinitions" <> D.hardline <> D.hardline <>
            D.joinWith (D.hardline <> D.hardline) (wrappers ++ bodies) <> D.hardline
      pure (Artifact (map (\c -> if c == '.' then '/' else c) identity ++ "/lawspec_definitions.go")
        (D.render (if layout == D.Compact then D.CompactTabs else layout) source) "generated" "source")
    implementation contracts (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          names = zip (nub (map binderId binders)) ["value" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved Go local") id (lookup identity names)
          arguments = [line (local (binderId binder) ++ " LawSpecValue") | binder <- definitionArguments d]
          external term values = case expressionNode term of
            ExternalCall identity _ -> do
              name <- maybe (Left "unresolved Go total call") Right (lookup identity callees)
              pure (E.call name (line "symbols":values))
            _ -> Left "expected Go definition call"
      body <- E.renderExpression declarations bits schema local external (definitionBody d)
      checks <- mapM (\binder -> do
        value <- schemaCall "validate" (binderType binder) (line (local (binderId binder)))
        pure (line (local (binderId binder) ++ " = ") <> value)) (definitionArguments d)
      result <- schemaCall "validate" (expressionType (definitionBody d)) (line "result")
      let contract = lookup (declarationId (definitionDeclaration d)) [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [assign "result" body,line "return " <> result])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checkedResult")] ++
                [(binderId b,"contractValue" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c ++ contractRuntimePostconditions c))]
              resolve identity = maybe (error "unbound Go definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression declarations bits schema resolve external predicate
                pure (E.call "lsRequireContract" [E.call "lsTruth" [expression],E.quoted stage])
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          pure (checks ++ pre ++ [assign "result" body,assign "checkedResult" result] ++
            post ++ [line "return checkedResult"])
      pure (line ("func lawSpecEvaluate" ++ show index) <>
        D.delimitTrailing 8 "(" ")" (symbols:arguments) <> line " LawSpecValue " <>
        D.block 8 (contextual (declarationId (definitionDeclaration d)) "LawSpecValue"
          (D.joinWith D.hardline statements)))
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          values = ["value" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.goDataType declarations) args
      resultType <- Native.goDataType declarations result
      codecs <- mapM (Native.goCodecWithContext "symbols" declarations) args
      resultCodec <- Native.goCodecWithContext "symbols" declarations result
      name <- maybe (Left "unresolved Go native call") Right (lookup (declarationId declaration) callees)
      let parameters = symbols : [line (value ++ " " ++ ty) | (value,ty) <- zip values types]
          inputs = concat [[assign ("codec" ++ show i) (line codec),
            assign ("argument" ++ show i) (E.call ("codec" ++ show i ++ ".fromNative") [line value])]
            | (i,(value,codec)) <- zip [0::Int ..] (zip values codecs)]
          invocation = E.call name (line "symbols" : [line ("argument" ++ show i) | i <- [0 .. length args - 1]])
      pure (line ("func (lawSpecDefinitions) " ++ capitalize (declarationName declaration)) <>
        D.delimitTrailing 8 "(" ")" parameters <> line (" " ++ resultType ++ " ") <>
        D.block 8 (contextual (declarationId declaration) resultType (D.joinWith D.hardline
          ([line ("schema := " ++ schema),line ("bits := " ++ show bits)] ++ inputs ++
           [assign "resultCodec" (line resultCodec),assign "result" invocation,
            line "return " <> E.call "resultCodec.toNative" [line "result"]]))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat
        [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
    capitalize [] = []
    capitalize (c:cs) = toUpper c:cs
