-- Go test scaffolding consumes checked propositions and generation plans.
module LawSpec.GoProperties (Config(..), emitTests) where

import LawSpec.Bounds (inputRange)
import LawSpec.Backend
import LawSpec.Common
import LawSpec.TestNames (unitTestNames, lawWords)
import LawSpec.Testing
import qualified LawSpec.Core as C
import qualified LawSpec.Core.Value as V
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.GoExpr as E
import qualified LawSpec.GoTestHelpers as Helpers
import Data.List (intercalate, stripPrefix)

data Config = Config
  { packageName :: String
  -- An async adapter's call, awaited.
  , awaitResult :: String -> D.Doc -> D.Doc
  , schemaNeeded :: Bool
  , constructorContracts :: Bool
  , nativeGenerators :: Bool
  , nodeBudget :: Integer
  , machineBits :: Int
  , expression :: Expr -> D.Doc
  , literal :: V.Value -> Either [Diagnostic] D.Doc
  , checked :: Type -> D.Doc -> D.Doc
  , structural :: Type -> Bool
  , reference :: Type -> D.Doc
  , typeKey :: Type -> String
  , generator :: Type -> D.Doc
  -- A generator drawing a top-level integer from a refinement's range.
  , generatorWithin :: Maybe (Integer, Integer) -> Type -> D.Doc
  , nativeFunction :: String -> String
  , nativeArgument :: Type -> D.Doc -> D.Doc
  , nativeResult :: Type -> D.Doc -> D.Doc
  -- The statements that install a law's handlers in symbols, for each case.
  , handlerInstalls :: Expanded -> [D.Doc]
  }

text = D.text
statements = D.joinWith D.hardline
separate = D.joinWith (D.hardline <> D.hardline)
block = D.block 8
call = E.call
quoted = E.quoted
number :: Show a => a -> D.Doc
number = text . show
returned x = text "return " <> x
bind n x = text (n ++ " := ") <> x
assign n x = statements [bind n x,text ("_ = " ++ n)]
closure parameters result body = text ("func(" ++ parameters ++ ")" ++
  (if null result then "" else " " ++ result) ++ " ") <> block body
truth x = call "lsTruth" [x]
conjunction [] = text "true"
conjunction xs = D.joinWith (text " && ") xs
symbols = statements [text "symbols := map[string]*lawSpecSymbol{}",text "_ = symbols"]
fromValues xs = statements [assign (inputId input) (text ("_values[" ++ show index ++ "]")) |
  (index,input) <- zip [0::Int ..] xs]

emitTests :: Config -> Unit -> [Expanded] -> Either [Diagnostic] D.Doc
emitTests Config{..} unit laws = do
  let testNames = unitTestNames "go" (map name laws)
  bodies <- mapM (law testNames) (zip [0::Int ..] laws)
  -- A law checked only by lsRefinedCase draws its inputs without rapid.
  let refinedOnly e = not (constructorContracts || nativeGenerators || any (maybe False (const True) . generatorIndex) (generationPlan e)
        || any (structural . inputType) (inputs e)) && (any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract")
      needsRapid = schemaNeeded || harnessed || any (\e -> finiteCases e == Nothing && not (refinedOnly e)) laws
      importDoc = text "import (" <> D.nest 8 (D.hardline <>
        statements ([quoted "flag" | needsRapid] ++ [quoted "fmt" | schemaNeeded] ++ [quoted "os" | needsRapid || sharing] ++
          [quoted "testing" | not (null laws)]) <>
        (if needsRapid then D.hardline <> D.hardline <> quoted "pgregory.net/rapid" else mempty)) <>
        D.hardline <> text ")"
  pure $ separate ([text "// Generated by LawSpec." <> D.hardline <> text ("package " ++ packageName)] ++
    [importDoc | schemaNeeded || not (null laws)] ++ [seedDoc | needsRapid] ++ [clockDoc] ++ [testMainDoc | sharing] ++ [Helpers.assertionDoc] ++
    [Helpers.dataHelpersDoc machineBits generator | schemaNeeded] ++
    map contract (contracts unit) ++ bodies ++ map benchmark (maybe [] C.harnessBenchmarks settings)) <> D.hardline
  where
    -- The harness plane (LawSpec.Harness). A test the harness runs is a
    -- function of rapid.TB (harness:Name), which the generated Test calls
    -- through the runtime; parallel marks every test parallel.
    settings = C.unitHarnessSettings unit
    harnessed = settings /= Nothing
    parallel = maybe False C.harnessParallel settings
    testFunction name body = case stripPrefix "harness:" name of
      Just rest -> text ("func lawspecHarness" ++ rest ++ "(t rapid.TB) ") <> block body
      Nothing -> goTest name body
    goTest name body = text ("func Test" ++ name ++ "(t *testing.T) ") <> block (if parallel then statements [text "t.Parallel()", body] else body)
    runSettings h = C.harnessTimeout h /= Nothing || C.harnessRepeat h /= 1 || C.harnessRetries h /= 0 || observed h
    observed h = not (null (C.harnessCover h) && null (C.harnessClassify h) && null (C.harnessLabels h)) || C.harnessTarget h /= Nothing
    observations e =
      let h = C.propertyHarness (original e)
          label = owner e ++ "::" ++ name e
          pairs xs = text "[]lsHarnessPair{" <> D.joinWith (text ", ") [text "{" <> quoted l <> text ", " <> truth (expr w) <> text "}" | (l, w) <- xs] <> text "}"
      in [call "lsHarnessObserve" [quoted label, pairs [(l, w) | C.Cover _ l w <- C.harnessCover h], pairs [(l, c) | (c, l) <- C.harnessClassify h],
            text "[]LawSpecValue{" <> D.joinWith (text ", ") (map expr (C.harnessLabels h)) <> text "}"] | observed h] ++
         [call "lsHarnessTarget" [expr score, quoted label] | Just score <- [C.harnessTarget h]]
    -- The tests a law's harness wraps, skips or expects to fail.
    harnessTests fn label h kinds docs = case (C.harnessSkip h, C.harnessKnownFailing h) of
      (Just reason, _) -> [goTest (fn ++ "_Skipped") (call "lsHarnessSkip" [text "t", quoted label, quoted reason])]
      (_, Just reason) -> docs ++ [goTest (fn ++ "_KnownFailing") (call "lsHarnessKnownFailing" [text "t", quoted label, quoted ("Test" ++ fn ++ "_KnownFailing"), quoted reason,
        text "[]func(rapid.TB){" <> D.joinWith (text ", ") [text ("lawspecHarness" ++ fn ++ k) | k <- kinds] <> text "}"])]
      _ | runSettings h -> docs ++ [goTest (fn ++ k) (call "lsHarnessRun" [text "t", quoted label, quoted ("Test" ++ fn ++ k),
            number (maybe 0 id (C.harnessTimeout h)), number (C.harnessRepeat h), number (C.harnessRetries h),
            text "[]lsHarnessCover{" <> D.joinWith (text ", ") [text ("{" ++ show p ++ ", ") <> quoted l <> text "}" | k == "_Property", C.Cover p l _ <- C.harnessCover h] <> text "}",
            text (if k == "_Property" && observed h then "true" else "false"), text ("lawspecHarness" ++ fn ++ k)]) | k <- kinds]
        | otherwise -> docs
    benchmark (n, body) = goTest ("Benchmark" ++ concatMap capital (lawWords n)) (statements [symbols,
      call "lsHarnessBenchmark" [text "t", quoted n, closure "" "" (text "_ = " <> expr body)]])
    capital (c : cs) = toEnum (fromEnum c - (if c >= 'a' && c <= 'z' then 32 else 0)) : cs
    capital [] = []
    -- A property whose inputs harness strategies draw.
    harnessProperty fn label e check = do
      let h = C.propertyHarness (original e)
          strategyOf inp = [(n, d) | (i, n, d) <- C.harnessDraws h, i == C.binderId (C.quantifiedBinder inp)]
      draws <- mapM (\plan -> do
        let inp = domainInput plan
            predicate = conjunction (map (truth . expr) (inputRefinements inp))
        case strategyOf inp of
          (strategy, d) : _ -> do
            value <- drawDoc inp strategy d
            pure [assign (inputId inp) (call "lsHarnessCheckDrawn" [quoted strategy, quoted (inputName inp),
              closure (inputId inp ++ " LawSpecValue") "bool" (returned predicate), value])]
          [] -> pure ([assign (inputId inp) (generatorWithin (inputRange machineBits inp) (inputType inp) <> text ".Draw(t, " <> quoted (inputId inp) <> text ")")] ++
            [text "if !(" <> predicate <> text ") " <> block (text "t.SkipNow()") | not (null (inputRefinements inp))])) (generationPlan e)
      pure $ testFunction (fn ++ "_Property") $ call "lsRapidCheck" [text "t",number (cases (generation e)),
        closure "t *rapid.T" "" $ statements ([symbols] ++ concat draws ++ handlerInstalls e ++ resourceDocs e ++ [check])]
    drawDoc inp strategy d = case d of
      C.DrawAny ty -> pure ((if ty == inputType inp then generatorWithin (inputRange machineBits inp) ty else generator ty) <> text ".Draw(t, \"value\")")
      C.DrawOneOf _ values -> pure (call "lsHarnessOneOf" [text "t", text "[]func() LawSpecValue{" <>
        D.joinWith (text ", ") [closure "" "LawSpecValue" (returned (expr v)) | v <- values] <> text "}"])
      C.DrawFrequency alternatives -> do
        options <- mapM (\(w, a) -> (\doc -> text ("{" ++ show w ++ ", ") <> closure "" "LawSpecValue" (returned doc) <> text "}") <$> drawDoc inp strategy a) alternatives
        pure (call "lsHarnessFrequency" [text "t", text "[]lsHarnessWeighted{" <> D.joinWith (text ", ") options <> text "}"])
      C.DrawSuchThat inner binder predicate limit -> do
        doc <- drawDoc inp strategy inner
        pure (call "lsHarnessSuchThat" [closure "" "LawSpecValue" (returned doc),
          closure (localName (C.binderId binder) ++ " LawSpecValue") "bool" (returned (truth (expr predicate))), number limit, quoted strategy])
      C.DrawBind binder from rest -> do
        fromDoc <- drawDoc inp strategy from
        restDoc <- drawDoc inp strategy rest
        pure (closure (localName (C.binderId binder) ++ " LawSpecValue") "LawSpecValue" (returned restDoc) <> text "(" <> fromDoc <> text ")")
    -- LAWSPEC_SEED fixes rapid's seed, so a run can be repeated exactly
    -- (lawspec test records the seed of every passing run).
    seedDoc = text "func init() " <> block (text "if seed := os.Getenv(\"LAWSPEC_SEED\"); seed != \"\" " <>
      block (text "_ = flag.Set(\"rapid.seed\", seed)"))
    -- Workflows wait on a virtual clock under test.
    clockDoc = text "func init() " <> block (text "LawSpecUseVirtualClock(0)")
    expr = expression
    -- A law's resources: each case acquires them, and releases them when it
    -- ends, the last first, even when it fails (defer).
    resourceDocs e = concat (map resourceDoc (C.propertyResources (original e)))
    -- A shared resource (share R per ...): the runtime keeps one per scope
    -- key, resets it before each later use, and releases it in TestMain.
    resourceDoc r
      | Just key <- C.resourceShared r, Just reset <- C.resourceReset r =
          let local = localName (C.binderId (C.resourceBinder r))
          in [ assign local (call "lsShare" [quoted key, closure "" "LawSpecValue" (returned (expr (C.resourceAcquire r))),
                 closure (local ++ " LawSpecValue") "" (text "_ = " <> expr reset),
                 closure (local ++ " LawSpecValue") "" (text "_ = " <> expr (C.resourceRelease r))])
             , text "defer lsUnshare(" <> quoted key <> text ")" ]
      | otherwise =
          [ assign (localName (C.binderId (C.resourceBinder r))) (expr (C.resourceAcquire r))
          , text "defer func() " <> block (text "_ = " <> expr (C.resourceRelease r)) <> text "()" ]
    sharing = any (\e -> any ((/= Nothing) . C.resourceShared) (C.propertyResources (original e))) laws
    -- Shared resources are released when the test binary ends.
    testMainDoc = text "func TestMain(m *testing.M) " <> block (statements
      [text "code := m.Run()", text "lsReleaseShared()", text "os.Exit(code)"])
    assertionDoc context proposition = case proposition of
      AssertAll ps -> statements (map (assertionDoc context) ps)
      AssertImplies guard body -> text "if " <> truth (expr guard) <> text " " <>
        block (assertionDoc context body)
      AssertEqual a b ->
        let message = quoted (context ++ " | expect " ++ prettyExpr a ++ " = " ++ prettyExpr b)
            thunk = closure "" "LawSpecValue" . returned . expr
        in if structural (expressionType a)
          then call "_lawspecDataAssert" [message,reference (expressionType a),text "symbols",thunk a,thunk b]
          else call "_lawspecAssert" [text "t",message,thunk a,thunk b]
    contract c =
      let args = contractArguments c
          (rn,rt) = contractResult c
          params = intercalate ", " ("symbols map[string]*lawSpecSymbol" : [n ++ " LawSpecValue" | (n,_) <- args])
          context stage ps = quoted (contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps))
          require stage ps = call "lsRequireContract" [conjunction (map (truth . expr) ps),context stage ps]
          invocation = awaitResult (contractName c) (call (nativeFunction (contractName c)) [nativeArgument ty (text n) | (n,ty) <- args])
      in text ("func _lawspec_call_" ++ contractName c ++ "(" ++ params ++ ") LawSpecValue ") <>
        block (statements [require "precondition" (contractPreconditions c),
          bind rn (nativeResult rt invocation),require "postcondition" (contractPostconditions c),returned (text rn)])
    law testNames (index,e) = do
      let label = owner e ++ "::" ++ name e
          h = C.propertyHarness (original e)
          base = drop 4 (testNames !! index)
          fn = (if C.harnessSkip h == Nothing && (C.harnessKnownFailing h /= Nothing || runSettings h) then "harness:" else "") ++ base
      exampleDocs <- mapM (\(i,ex) -> pure $ testFunction (fn ++ "_Example" ++ show i) $ statements
        ([symbols] ++ handlerInstalls e ++ [assign n (expr v) | (n,v) <- bindings ex] ++ resourceDocs e ++
        map (assertionDoc (label ++ " example " ++ exampleName ex)) (expectations ex) ++
        [assertionDoc label (assertion e)])) (zip [0::Int ..] (examples (original e)))
      boundaryDocs <- mapM (\(i,vs) -> do
        values <- mapM literal vs
        pure $ testFunction (fn ++ "_Boundary" ++ show i) $ statements
          ([symbols] ++ handlerInstalls e ++ [assign (inputId inp) (checked (inputType inp) v) | (inp,v) <- zip (inputs e) values] ++
          resourceDocs e ++ [assertionDoc (label ++ " boundary " ++ show i) (assertion e)]))
        (zip [0::Int ..] (maybe (boundaryCases e) id (finiteCases e)))
      let check = statements (observations e ++ [assertionDoc (label ++ " property") (assertion e)])
      property <- if finiteCases e /= Nothing then pure []
        else if not (null (C.harnessDraws h)) then (:[]) <$> harnessProperty fn label e check
        else if constructorContracts || nativeGenerators || any (maybe False (const True) . generatorIndex) (generationPlan e)
          then (:[]) <$> contextualProperty fn label e check
        else if any (structural . inputType) (inputs e) then pure [structuralProperty fn label e check]
        else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract"
          then (:[]) <$> refinedProperty fn label e check
          else pure [testFunction (fn ++ "_Property") $ call "rapid.Check" [text "t",
            closure "t *rapid.T" "" $ statements ([assign "seed" (text "rapid.Int32().Draw(t, \"seed\")"),symbols] ++ handlerInstalls e ++
              [assign (inputId inp) (call "lsSample" [quoted (typeKey (inputType inp)),
                text ("int(seed)+" ++ show i),number machineBits]) | (i,inp) <- zip [0::Int ..] (inputs e)] ++ resourceDocs e ++ [check])]]
      let kinds = ["_Example" ++ show i | i <- [0 .. length exampleDocs - 1]] ++ ["_Boundary" ++ show i | i <- [0 .. length boundaryDocs - 1]] ++
            ["_Property" | not (null property)]
      pure $ metadataDocument 100 "//" e <> separate (harnessTests base label h kinds (exampleDocs ++ boundaryDocs ++ property))
    contextualProperty fn label e check = do
      draws <- mapM (\plan -> do
        seeds <- mapM literal (generatorBoundaries plan)
        let inp = domainInput plan
            ty = inputType inp
            hints = [expr hint | hint <- generatorHints plan, expressionType hint == ty,
              case C.expressionNode hint of C.Constant _ -> True; C.Local _ -> True; _ -> False]
            strategy = case (if nativeGenerators then [] else requiredSymbol plan) of
              value:_ -> call "rapid.Just" [expr value]
              -- The target is evaluated from the inputs drawn above.
              [] | Just indexed <- generatorIndex plan -> call "lsIndexedDataStrategy"
                [text "_lawspecSchema",reference ty,number machineBits,number nodeBudget,
                 expr (indexedTarget indexed),
                 -- Go requires trailing commas across lines; keep the table on one line.
                 text "map[string][]string{" <> D.joinWith (text ", ")
                   [quoted (C.idText tag) <> text ": {" <> D.joinWith (text ", ") (map quoted texts) <> text "}"
                   | (tag,texts) <- indexedEquations indexed] <> text "}",
                 text "_lawspecScalarGenerator"]
              [] -> call "lsCheckedDataStrategyWithAttempts" $
                [text "_lawspecSchema",reference ty,number machineBits,number nodeBudget,number (maxAttempts (generation e)),
                 text "symbols",E.array (seeds ++ hints),text "_lawspecScalarGenerator"] ++
                [text "lawSpecNativeFactories()" | nativeGenerators]
            suffix = if nativeGenerators || null (requiredSymbol plan) then text ".requireValue()" else mempty
        pure (assign (inputId inp) (strategy <> text ".Draw(t, " <>
          quoted (inputId inp) <> text ")" <> suffix))) (generationPlan e)
      let base = call "rapid.Custom" [closure "t *rapid.T" "[]LawSpecValue" $
            statements (draws ++ [returned (E.array (map (text . inputId) (inputs e)))])]
          predicates = concatMap inputRefinements (inputs e)
          strategy = if null predicates then base else call "lsBoundedFilter"
            [base,number (maxAttempts (generation e)),
             closure "_values []LawSpecValue" "bool" (statements
               [fromValues (inputs e),returned (conjunction (map (truth . expr) predicates))])]
      pure $ testFunction (fn ++ "_Property") $ call "lsRapidCheck" [text "t",number (cases (generation e)),
        closure "t *rapid.T" "" $ statements ([symbols,
          bind "_values" (strategy <> text ".Draw(t, " <> quoted label <> text ")"),
          fromValues (inputs e)] ++ handlerInstalls e ++ resourceDocs e ++ [check])]
    requiredSymbol plan
      | inputType (domainInput plan) /= C.scalarType "Symbol" = []
      | otherwise = concatMap required (generatorPredicates plan)
      where
        current = C.binderId (generatorBinder plan)
        required term = case C.expressionNode term of
          C.ShortCircuit C.And a b -> required a ++ required b
          C.Binary C.Equal _ a b -> [value | (local,value) <- [(a,b),(b,a)],
            C.expressionNode local == C.Local current,
            expressionType value == C.scalarType "Symbol",
            current `notElem` C.freeBinders value,
            case C.expressionNode value of C.Constant _ -> True; C.Local _ -> True; _ -> False]
          _ -> []
    structuralProperty fn label e check =
      let draws = [bind (inputId inp) (generatorWithin (inputRange machineBits inp) (inputType inp) <> text ".Draw(t, " <> quoted (inputId inp) <> text ")") | inp <- inputs e]
          base = call "rapid.Custom" [closure "t *rapid.T" "[]LawSpecValue" $
            statements (draws ++ [returned (E.array (map (text . inputId) (inputs e)))])]
          predicates = concatMap inputRefinements (inputs e)
          strategy = if null predicates then base else call "lsBoundedFilter"
            [base,number (maxAttempts (generation e)),
             closure "_values []LawSpecValue" "bool" (statements
               [fromValues (inputs e),returned (conjunction (map (truth . expr) predicates))])]
      in testFunction (fn ++ "_Property") $ call "lsRapidCheck" [text "t",number (cases (generation e)),
        closure "t *rapid.T" "" $ statements ([symbols,
          bind "_values" (strategy <> text ".Draw(t, " <> quoted label <> text ")"),fromValues (inputs e)] ++ handlerInstalls e ++ resourceDocs e ++ [check])]
    domain e (index,plan) = do
      seeds <- mapM literal (generatorBoundaries plan)
      let inp = domainInput plan
          prior = take index (inputs e)
          bounds = text "[]lawSpecBound{" <> D.joinWith (text ", ")
            [text "{" <> quoted op <> text ", " <> expr v <> text "}" | (op,v) <- domainBounds plan] <> text "}"
          candidates = call "lsDomainCandidates" [quoted (typeKey (inputType inp)),text "_seed",number machineBits,
            bounds,E.array (seeds ++ map expr (generatorHints plan))]
          seedFn = closure "_values []LawSpecValue, _seed int" "[]LawSpecValue"
            (statements [fromValues prior,returned candidates])
          predicate = closure "_values []LawSpecValue" "bool" (statements
            [fromValues (prior ++ [inp]),returned (conjunction (map (truth . expr) (inputRefinements inp)))])
      pure (text "lawSpecDomain{" <> seedFn <> text ", " <> predicate <> text "}")
    refinedProperty fn label e check = do
      domains <- mapM (domain e) (zip [0::Int ..] (generationPlan e))
      let cfg = generation e
          callback = closure "_values []LawSpecValue" "" (statements ([fromValues (inputs e)] ++ handlerInstalls e ++ resourceDocs e ++ [check]))
          invocation = call "lsRefinedCase" [text "[]lawSpecDomain{" <> D.joinWith (text ", ") domains <> text "}",
            text "seed",number (maxAttempts cfg),number (maxShrinks cfg),callback,
            quoted (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ testFunction (fn ++ "_Property") $ statements
        [text "defer " <> closure "" "" (text "if err := recover(); err != nil " <>
          block (text "t.Fatalf(\"%v\", err)")) <> text "()",
         text ("for seed := 0; seed < " ++ show (cases cfg) ++ "; seed++ ") <>
          block (statements [symbols,invocation])]
    cap [] = []
    cap (c:cs) = (if c >= 'a' && c <= 'z' then toEnum (fromEnum c - 32) else c):cs
