-- Native Haskell functions over pure, checked total-definition implementations.
module LawSpec.HaskellDefinitions (emitHaskellDefinitions, definitionCalls) where

import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.HaskellData as Native
import LawSpec.Collections (isCollectionsType)
import qualified LawSpec.HaskellExpr as E
import qualified LawSpec.Code.Doc as D
import Data.Char (toUpper)
import Data.List (nub, intercalate)

definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d), "Definitions.evaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitHaskellDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitHaskellDefinitions _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitHaskellDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  bodies <- mapM (implementation contracts) (zip [0::Int ..] (concatMap unitDefinitions units))
  wrappers <- mapM nativeUnit (filter (not . null . unitDefinitions) units)
  pure (file "LawSpecDefinitionBodies" [] bodies : wrappers)
  where
    names = definitionCalls units
    text = D.text
    file name imports bodies = Artifact ("src/" ++ map (\c -> if c == '.' then '/' else c) name ++ ".hs")
      (D.render layout (D.joinWith D.hardline (map text
        (["-- Generated by LawSpec. Do not edit.", "module " ++ name ++ " where", "",
          "import qualified Prelude as P", "import qualified Data.Int as I", "import qualified Data.Word as W",
          "import qualified Data.Text as T", "import qualified Data.ByteString as B", "import qualified Data.Complex as C",
          "import LawSpecRuntime (Scalar(..))", "import qualified LawSpecRuntime as LS",
          "import qualified LawSpecSchema as Schema", "import qualified LawSpecCodecs as Codec",
          "import qualified LawSpecData as Data", "import qualified LawSpecDataSchema as DataSchema",
          "import qualified LawSpecDataCodecs as Codecs"] ++
         concat [["import qualified LawSpecCollectionCodecs as Collections", "import qualified Data.Set as Set",
                  "import qualified Data.Map.Strict as Map", "import qualified Data.Sequence as Seq"]
                 | any (isCollectionsType . idText . dataId) declarations] ++ imports ++
         (if null imports then "" : environment else []) ++ [""])) <>
        D.hardline <> D.joinWith (D.hardline <> D.hardline) bodies <> D.hardline)) "generated" "source"
    environment = ["_lawspecSchema :: Schema.Schema",
      "_lawspecSchema = P.either P.error P.id DataSchema.schema",
      "_lawspecBits :: P.Int", "_lawspecBits = " ++ show bits]
    signature name types = D.group (text (name ++ " ::") <>
      D.nest 2 (D.softline <> D.joinWith (text " ->" <> D.softline) types))
    context identity body = E.apply "Codec.context" [E.quoted (idText identity)] <> text " P.$ do" <>
      D.nest 2 (D.hardline <> D.joinWith D.hardline body)
    binding name arguments body = text (unwords (name : "symbols" : arguments) ++ " =") <>
      D.nest 2 (D.hardline <> body)
    validate ty value = do
      ref <- Native.haskellTypeReferenceDoc ty
      pure (E.apply "Schema.validateWith" [E.apply "P.Just" [text "symbols"],text "_lawspecSchema",ref,text "_lawspecBits",value])
    implementation contracts (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          locals = zip (nub (map binderId binders)) ["value" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved Haskell local") id (lookup identity locals)
          arguments = map (local . binderId) (definitionArguments d)
          name = "evaluate" ++ show index
          external term values = case expressionNode term of
            ExternalCall identity _ -> do
              callee <- maybe (Left "unresolved Haskell total call") Right (lookup identity names)
              pure (E.checked (E.apply (drop (length ("Definitions." :: String)) callee) (text "symbols":values)))
            _ -> Left "expected Haskell definition call"
      -- Arguments and results were checked where they were built, decoded
      -- or drawn; the native wrappers check values crossing from adapters.
      let checks = []
      body <- E.renderExpression declarations bits "_lawspecSchema" "symbols" local external (definitionBody d)
      let result = E.apply "P.pure" [text "result"]
      let evaluate = text "let result =" <> D.nest 6 (D.hardline <> body)
          checkedResult = D.group (E.apply "LS.forceScalar" [text "result"] <> text " `P.seq`" <>
            D.nest 2 (D.softline <> result))
          contract = lookup (declarationId (definitionDeclaration d))
            [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [evaluate,checkedResult])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checkedResult")] ++
                [(binderId b,"contractValue" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c ++ contractRuntimePostconditions c))]
              resolve identity = maybe (error "unbound Haskell definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression declarations bits "_lawspecSchema" "symbols" resolve external predicate
                pure (D.group (text "if " <> E.apply "LS.truth" [expression] <>
                  D.nest 2 (D.softline <> text "then P.Right ()" <> D.softline <>
                    text "else " <> E.apply "P.Left" [E.quoted (stage ++ " failed")])) )
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          pure (checks ++ pre ++ [evaluate,
            D.group (text "checkedResult <-" <> D.nest 2 (D.softline <> checkedResult))] ++
            post ++ [text "P.Right checkedResult"])
      pure (signature name (text "LS.SymbolContext" : replicate (length arguments) (text "LS.Scalar") ++
          [text "P.Either P.String LS.Scalar"]) <> D.hardline <>
        binding name arguments (context (declarationId (definitionDeclaration d)) statements))
    nativeUnit unit = do
      methods <- mapM native (unitDefinitions unit)
      let name = "LawSpecDefinitions." ++ intercalate "." (map modulePart (split '.' (idText (unitId unit))))
      pure (file name ["import qualified LawSpecDefinitionBodies as Definitions"] methods)
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          name = declarationName declaration
          values = ["value" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.haskellDataType declarations) args
      resultType <- Native.haskellDataType declarations result
      codecs <- mapM (Native.haskellCodecDocWithContext (E.apply "P.Just" [text "symbols"]) declarations "_lawspecSchema" "_lawspecBits") args
      resultCodec <- Native.haskellCodecDocWithContext (E.apply "P.Just" [text "symbols"]) declarations "_lawspecSchema" "_lawspecBits" result
      callee <- maybe (Left "unresolved native Haskell call") Right (lookup (declarationId declaration) names)
      let checks = [D.group (text ("argument" ++ show i ++ " <-") <>
            D.nest 2 (D.softline <> E.apply "Codec.encode" [codec,text value]))
            | (i,(codec,value)) <- zip [0::Int ..] (zip codecs values)]
          invoke = E.apply callee (text "symbols" : [text ("argument" ++ show i) | i <- [0 .. length args - 1]])
      pure (signature name (text "LS.SymbolContext" : map text types ++
          [text "P.Either P.String " <> E.parens (text resultType)]) <> D.hardline <>
        binding name values (context (declarationId declaration)
          (checks ++ [D.group (text "result <-" <> D.nest 2 (D.softline <> invoke)),
            E.apply "Codec.decode" [resultCodec,text "result"]])) <>
        D.nest 2 (D.hardline <> text "where" <>
          D.nest 2 (D.hardline <> D.joinWith D.hardline (map text environment))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
    split delimiter value = case break (== delimiter) value of
      (a,[]) -> [a]
      (a,_:rest) -> a : split delimiter rest
    modulePart = concatMap capitalize . split '_'
    capitalize [] = []
    capitalize (c:cs) = toUpper c:cs
