-- Application-owned Haskell ADTs cross the same checked schema as generated ADTs.
module LawSpec.HaskellNativeBinding (emitBindings) where

import Control.Monad (forM, unless)
import Data.Char (isUpper, isLower, toUpper, toLower)
import Data.List (intercalate, nub, isSuffixOf, isPrefixOf, isInfixOf)
import qualified LawSpec.Core as C
import LawSpec.Backend (inputs, inputType)
import LawSpec.Common
import LawSpec.Testing
import LawSpec.NativeBinding
import LawSpec.NativeRequest
import qualified LawSpec.HaskellData as H
import qualified LawSpec.HaskellDefinitions as Definitions
import qualified LawSpec.HaskellExpr as E
import qualified LawSpec.CoreNativeScalarEmit as Scalar
import qualified LawSpec.Code.Doc as D

emitBindings :: Bool -> BindingPlan -> Plan -> [Artifact] -> Either String [Artifact]
emitBindings minify plan testing files = do
  unless (bindingRustCrate plan == Nothing) (Left "rustCrate is only valid for Rust bindings")
  mapM_ (reference False . resolvedGeneratorFactory) generators
  mapM_ (reference True) typeRefs
  mapM_ (reference False) hookRefs
  mapM_ (reference False . snd) (bindingFunctions plan)
  let generatedModules = [map (\c -> if c == '/' then '.' else c) (take (length relative - 3) relative) |
        file <- files, ".hs" `isSuffixOf` artifactPath file,
        (_, '/':relative) <- [break (== '/') (artifactPath file)]] ++
        ["LawSpecNativeCodecs", "LawSpecNativeGenerators"]
  unless (all (`notElem` generatedModules) applicationModules)
    (Left "Haskell application module shadows a generated module")
  mapM_ selector [name | m <- mappings,c <- resolvedConstructors m,(_,name) <- resolvedFields c]
  let types = [(C.dataId (resolvedDeclaration m), qualify (resolvedNativeType m)) | m <- mappings]
      constructors = [(C.constructorId (resolvedConstructor c),
        (qualify (resolvedNativeConstructor c), [alias (moduleOf (resolvedNativeConstructor c)) ++ "." ++ field |
          (_,field) <- resolvedFields c])) | m <- mappings,c <- resolvedConstructors m]
      modules = map nativeImport (nub (map moduleOf (typeRefs ++ hookRefs)))
      hooks = [(C.dataId (resolvedDeclaration m),(qualify (codecToNative hook),qualify (codecFromNative hook))) |
        m <- mappings,Just hook <- [resolvedCodec m]]
  codecs <- H.emitHaskellCodecsWithHooks layout declarations "LawSpecNativeCodecs" modules types constructors hooks
  concrete <- if null generators then pure [] else reachableGeneratorTypes declarations representations
    [inputType i | p <- plannedUnits testing,property <- plannedProperties p,i <- inputs property]
  let usedGenerators = [g | g <- generators, any (\case C.Constructor name _ -> C.Id name == resolvedGeneratorType g; _ -> False) concrete]
  generatorFiles <- if null usedGenerators then pure [] else do
    methods <- forM (zip [0::Int ..] usedGenerators) $ \(index,g) -> do
      branches <- forM [ty | ty@(C.Constructor name _) <- concrete,C.Id name == resolvedGeneratorType g] $ \ty -> do
        let arguments = case ty of C.Constructor _ args -> [t | C.TypeArgument t <- args]; _ -> []
            names = ["child" ++ show i | i <- [0::Int ..length arguments-1]]
        childCodecs <- mapM (nativeCodec "bits") arguments
        resultCodec <- nativeCodec "bits" ty
        ref <- H.haskellTypeReferenceDoc ty
        let invocation = E.apply (qualify (resolvedGeneratorFactory g))
              [E.apply "Strategies.nativeArguments" [codec,D.text name] | (codec,name) <- zip childCodecs names]
            value = E.apply "P.Right" [E.apply "Strategies.nativeValues" [resultCodec,invocation]]
        pure (D.text "| reference P.== " <> ref <> D.text " = case arguments of" <>
          D.nest 2 (D.hardline <> D.text ("[" ++ intercalate ", " names ++ "]") <> D.text " -> " <> value <>
            D.hardline <> D.text "_ -> P.Left \"native generator argument arity mismatch\""))
      pure (D.text ("factory" ++ show index ++ " reference arguments") <>
        D.nest 2 (D.hardline <> D.joinWith D.hardline (branches ++
          [D.text "| P.otherwise = P.Left \"unplanned native generator instantiation\""])))
    let imports = ["Prelude as P", "Data.Int as I", "Data.Word as W", "Data.Text as T",
          "Data.ByteString as B", "Data.Complex as C", "LawSpecRuntime as LS",
          "LawSpecSchema as Schema", "LawSpecCodecs as Codec", "LawSpecData as Data",
          "LawSpecNativeCodecs as NativeCodecs", "LawSpecDataStrategies as Strategies"] ++
          map nativeImport (nub (map moduleOf typeRefs ++ map (moduleOf . resolvedGeneratorFactory) usedGenerators))
        registry = E.array [D.text ("(" ++ show (C.idText (resolvedGeneratorType g)) ++ ", factory" ++ show i ++ ")") |
          (i,g) <- zip [0::Int ..] usedGenerators]
        source = D.joinWith D.hardline (map D.text (["-- Generated by LawSpec. Do not edit.",
          "module LawSpecNativeGenerators where", ""] ++ map ("import qualified " ++) imports ++ ["",
          "factories :: LS.SymbolContext -> Schema.Schema -> P.Int -> [(P.String, Strategies.NativeFactory)]"])) <>
          D.hardline <> D.text "factories symbols _lawspecSchema bits =" <> D.nest 2 (D.hardline <> registry) <>
          D.nest 2 (D.hardline <> D.text "where" <> D.nest 2 (D.hardline <>
            D.joinWith (D.hardline <> D.hardline) methods)) <> D.hardline
    pure [Artifact "test/LawSpecNativeGenerators.hs" (D.render layout source) "generated" "test"]
  emitted <- fmap concat $ forM (plannedUnits testing) $ \p -> do
    let unit = plannedUnit p
        defined = map (C.declarationId . C.definitionDeclaration) (C.unitDefinitions unit)
        adapters = [d | d <- C.unitDeclarations unit,C.declarationId d `notElem` defined]
        bound d = lookup (C.declarationId d) [(C.declarationId a,r) | (a,r) <- bindingFunctions plan]
        boundAdapters = [(d,r) | d <- adapters,Just r <- [bound d]]
        moduleName = intercalate "." (map modulePart (split '.' (C.idText (C.unitId unit))))
        path = "src/" ++ map (\c -> if c == '.' then '/' else c) moduleName ++ ".hs"
    if null boundAdapters && null usedGenerators then pure [] else do
      unless (null boundAdapters || length boundAdapters == length adapters) (Left "a Haskell bound unit must map every adapter")
      unless (moduleName `notElem` map (moduleOf . snd) boundAdapters)
        (Left "Haskell application module shadows its generated adapter module")
      methods <- mapM bridge boundAdapters
      ordinary <- either (Left . show) Right $
        Scalar.nativeScalarEmitWithAdapterBindings
          [(C.declarationId d,C.declarationName d) | (d,_) <- boundAdapters]
          (not (null usedGenerators)) minify declarations (Definitions.definitionCalls (map plannedUnit (plannedUnits testing)))
          bits "haskell" unit (plannedProperties p)
      let imports = ["Prelude as P", "Data.Int as I", "Data.Word as W", "Data.Text as T",
            "Data.ByteString as B", "Data.Complex as C", "LawSpecRuntime as LS",
            "LawSpecSchema as Schema", "LawSpecCodecs as Codec", "LawSpecData as Data",
            "LawSpecDataSchema as DataSchema", "LawSpecDataCodecs as Codecs",
            "LawSpecNativeCodecs as NativeCodecs"] ++ map nativeImport (nub (map moduleOf typeRefs ++ map (moduleOf . snd) boundAdapters))
          source = D.joinWith D.hardline (map D.text
            (["-- Generated by LawSpec. Do not edit.", "module " ++ moduleName ++ " where", ""] ++
             map ("import qualified " ++) imports ++ ["", "_lawspecSchema :: Schema.Schema",
             "_lawspecSchema = P.either P.error P.id DataSchema.schema", ""])) <>
            D.joinWith (D.hardline <> D.hardline) methods <> D.hardline
      pure ([Artifact path (D.render layout source) "generated" "source" | not (null boundAdapters)] ++
        [f | f <- ordinary, null boundAdapters || artifactPath f /= path])
  let support = Artifact "src/LawSpecNativeCodecs.hs" codecs "generated" "source"
  unless (all ((/= artifactPath support) . artifactPath) files) (Left "unit shadows Haskell native codec support")
  let generated = [f | f <- files,artifactPath f `notElem` map artifactPath emitted] ++ [support] ++ generatorFiles ++ emitted
  stubs <- generatorStubs generated
  pure (generated ++ stubs)
  where
    representations = bindingRepresentations plan
    generators = resolvedGenerators representations
    mappings = resolvedTypes representations
    declarations = planDataDeclarations testing
    bits = planMachineBits testing
    layout = D.selectLayout minify (D.Pretty 100)
    typeRefs = [resolvedNativeType m | m <- mappings] ++
      [resolvedNativeConstructor c | m <- mappings,c <- resolvedConstructors m]
    hookRefs = [ref | m <- mappings,Just hook <- [resolvedCodec m],ref <- [codecToNative hook,codecFromNative hook]]
    applicationModules = nub (map moduleOf (typeRefs ++ hookRefs ++ map snd (bindingFunctions plan) ++
      map resolvedGeneratorFactory generators))
    aliases = zip applicationModules ["NativeModule" ++ show i | i <- [0::Int ..]]
    alias name = maybe (error "unresolved Haskell application module") id (lookup name aliases)
    nativeImport name = name ++ " as " ++ alias name
    qualify ref = alias (moduleOf ref) ++ "." ++ last (referenceParts ref)
    moduleOf = intercalate "." . init . referenceParts
    generatorStubs generated = do
      let requested = filter resolvedGeneratorStub generators
          owners = nub (map (moduleOf . resolvedGeneratorFactory) requested)
          generatedModules = [map (\c -> if c == '/' then '.' else c) (take (length relative - 3) relative) |
            file <- generated, ".hs" `isSuffixOf` artifactPath file,
            (_, '/':relative) <- [break (== '/') (artifactPath file)]]
          occupied = generatedModules ++ map moduleOf (typeRefs ++ hookRefs ++ map snd (bindingFunctions plan))
          conflicts a b = map toLower a == map toLower b
          runtimeModule name = name `elem` words
            ("Prelude Hedgehog Numeric Test.Hspec Control.Exception Control.Monad " ++
             "Control.Monad.State.Strict Data.Int Data.Word Data.Text Data.ByteString " ++
             "Data.Complex Data.Bits Data.Char Data.List Data.Ratio Data.Unique " ++
             "Data.Maybe Data.Map.Strict") ||
            any (`isPrefixOf` name) ["Hedgehog.", "GHC.", "LawSpec"]
      forM owners $ \owner -> do
        unless (not (runtimeModule owner) && not (any (conflicts owner) occupied) &&
          not (any (\other -> owner /= other && conflicts owner other) owners))
          (Left "Haskell generator scaffold module conflicts with application, generated or runtime modules")
        bodies <- forM (filter ((== owner) . moduleOf . resolvedGeneratorFactory) requested) $ \generator -> do
          let name = last (referenceParts (resolvedGeneratorFactory generator))
              parameters = [(C.Id ("scaffold::" ++ show i),"a" ++ show i) | i <- [0 .. generatorParameterCount generator - 1]]
              ty = C.Constructor (C.idText (resolvedGeneratorType generator))
                [C.TypeArgument (C.TypeVariable identity) | (identity,_) <- parameters]
          unless (name /= "_") (Left "Haskell generator scaffold cannot declare the wildcard identifier")
          native <- H.haskellNativeTypeWithParameters declarations
            [(C.dataId (resolvedDeclaration m),qualify (resolvedNativeType m)) | m <- mappings] parameters ty
          let gen value = D.text "H.Gen " <> D.text value
              signature = D.group (D.text (name ++ " ::") <> D.nest 2 (D.softline <>
                D.joinWith (D.text " ->" <> D.softline) (map (gen . snd) parameters ++ [gen native])))
              arguments = ["_argument" ++ show i | i <- [0 .. length parameters - 1]]
          pure (signature <> D.hardline <> D.text (unwords (name:arguments) ++ " =") <>
            D.nest 2 (D.hardline <> E.apply "Prelude.error" [E.quoted ("Implement generator for " ++ C.idText (resolvedGeneratorType generator))]))
        let body = D.joinWith (D.hardline <> D.hardline) bodies
            rendered = D.render (D.Pretty 80) body
            imports = ["import qualified " ++ name ++ " as " ++ short |
              (name,short) <- [("Prelude","Prelude"),("Prelude","P"),("Hedgehog","H"),("Data.Int","I"),("Data.Word","W"),
                ("Data.Text","T"),("Data.ByteString","B"),("Data.Complex","C"),
                ("LawSpecRuntime","LS"),("LawSpecData","Data")] ++
                [(name,alias name) | name <- nub (map (moduleOf . resolvedNativeType) mappings)],
              (short ++ ".") `isInfixOf` rendered]
        pure (Artifact ("test/" ++ map (\c -> if c == '.' then '/' else c) owner ++ ".hs")
          (D.render (D.Pretty 80) (D.text "-- User-owned native generator factories. Implement before running properties." <>
            D.hardline <> D.text ("module " ++ owner ++ " where") <> D.hardline <> D.hardline <>
            D.joinWith D.hardline (map D.text imports) <> D.hardline <> D.hardline <> body <> D.hardline)) "user" "test")
    selector name = unless (not (null name) && (isLower (head name) || head name == '_') &&
      name `notElem` words "case class data default deriving do else foreign if import in infix infixl infixr instance let module newtype of then type where")
      (Left ("invalid Haskell native value identifier: " ++ name))
    reference upper ref = do
      let parts = referenceParts ref
      unless (length parts >= 2 && all (\n -> not (null n) && isUpper (head n)) (init parts))
        (Left "Haskell native references require a qualified application module")
      if upper then unless (not (null (last parts)) && isUpper (head (last parts)))
        (Left "Haskell native types and constructors must begin with an uppercase letter")
        else selector (last parts)
      unless (moduleOf ref `notElem` ["LawSpecNativeCodecs","LawSpecDataCodecs","LawSpecData", "LawSpecDataSchema"])
        (Left "Haskell native reference shadows generated support")
    split c s = case break (==c) s of (a,[]) -> [a]; (a,_:b) -> a:split c b
    modulePart = concatMap cap . split '_'
    cap [] = []; cap (c:cs) = toUpper c:cs
    nativeCodec bitsName ty = do
      converter <- H.haskellCodecDocIn (Just (E.apply "P.Just" [D.text "symbols"]))
        "NativeCodecs." declarations "_lawspecSchema" bitsName ty
      nativeType <- H.haskellDataTypeWithRepresentations declarations
        [(C.dataId (resolvedDeclaration m),qualify (resolvedNativeType m)) | m <- mappings] ty
      pure (E.parens (converter <> D.text (" :: Codec.Codec " ++ nativeType)))
    bridge (declaration,ref) = do
      let (args,result) = C.functionType (C.declarationType declaration)
          values = ["value" ++ show i | i <- [0::Int ..length args-1]]
          scope = Just (E.apply "P.Just" [D.text "symbols"])
          codec namespace = H.haskellCodecDocIn scope namespace declarations "_lawspecSchema" (show bits)
      types <- mapM (H.haskellDataType declarations) (args ++ [result])
      canonical <- mapM (codec "Codecs.") args
      native <- mapM (nativeCodec (show bits)) args
      resultNative <- nativeCodec (show bits) result
      resultCanonical <- codec "Codecs." result
      let bind name expression = D.group (D.text (name ++ " <-") <> D.nest 2 (D.softline <> expression))
          argumentChecks = concat
            [[bind ("logical" ++ show i) (E.apply "Codec.encode" [c,D.text value]),
              bind ("argument" ++ show i) (E.apply "Codec.decode" [n,D.text ("logical" ++ show i)])] |
              (i,(value,c,n)) <- zip [0::Int ..] (zip3 values canonical native)]
          invoke = E.apply (qualify ref) [D.text ("argument" ++ show i) | i <- [0..length args-1]]
          resultBinding = D.group (D.text "let nativeResult =" <> D.nest 4 (D.softline <> invoke))
          -- Unit's codec ignores its payload; force the call even for Unit.
          encodeResult = D.group (D.text "nativeResult `P.seq`" <> D.nest 2 (D.softline <>
            E.apply "Codec.encode" [resultNative,D.text "nativeResult"]))
          body = E.apply "Codec.context" [E.quoted ("native binding " ++ C.idText (C.declarationId declaration))] <>
            D.text " P.$ do" <> D.nest 2 (D.hardline <> D.joinWith D.hardline
              (argumentChecks ++ [resultBinding,bind "logicalResult" encodeResult,
                E.apply "Codec.decode" [resultCanonical,D.text "logicalResult"]]))
      pure (D.group (D.text (C.declarationName declaration ++ " ::") <> D.nest 2 (D.softline <>
          D.joinWith (D.text " ->" <> D.softline) (D.text "LS.SymbolContext" : map D.text types))) <>
        D.hardline <> D.text (unwords (C.declarationName declaration : "symbols" : values) ++ " =") <>
        D.nest 2 (D.hardline <> E.apply "P.either P.error P.id" [E.parens body]))
