-- Native Haskell functions over pure, checked total-definition implementations.
module LawSpec.HaskellDefinitions (emitHaskellDefinitions, definitionCalls) where

import Control.Monad (forM)
import LawSpec.Core.Policy
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.HaskellData as Native
import LawSpec.Collections (isCollectionsType)
import qualified LawSpec.HaskellExpr as E
import qualified LawSpec.Code.Doc as D
import Data.Char (toUpper)
import Data.List (nub, intercalate)

-- Workflows call adapters, so they live in LawSpecWorkflows, apart from the
-- bodies adapters may import.
definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d),
  (if definitionOrchestrates d then "Workflows" else "Definitions") ++ ".evaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitHaskellDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitHaskellDefinitions _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitHaskellDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  let indexed = zip [0::Int ..] (concatMap unitDefinitions units)
  bodies <- mapM (implementation contracts "Definitions") [x | x@(_, d) <- indexed, not (definitionOrchestrates d)]
  workflows <- mapM (implementation contracts "Workflows") [x | x@(_, d) <- indexed, definitionOrchestrates d]
  wrappers <- mapM (nativeUnit False) (filter (any (not . definitionOrchestrates) . unitDefinitions) units)
  workflowWrappers <- mapM (nativeUnit True) (filter (any definitionOrchestrates . unitDefinitions) units)
  let adapterImports = nub ["import qualified " ++ moduleOf owner | (_, (owner, _)) <- adapters]
  pure (file "LawSpecDefinitionBodies" [] bodies :
    [file "LawSpecWorkflows" ("import qualified LawSpecDefinitionBodies as Definitions" : adapterImports ++ "" : environment) workflows
    | not (null workflows)] ++
    wrappers ++ workflowWrappers)
  where
    names = definitionCalls units
    text = D.text
    file name imports bodies = Artifact ("src/" ++ map (\c -> if c == '.' then '/' else c) name ++ ".hs")
      (D.render layout (D.joinWith D.hardline (map text
        (["-- Generated by LawSpec. Do not edit.", "module " ++ name ++ " where", "",
          "import qualified Prelude as P", "import qualified Data.Int as I", "import qualified Data.Word as W",
          "import qualified Data.Text as T", "import qualified Data.ByteString as B", "import qualified Data.Complex as C",
          "import LawSpecRuntime (Scalar(..))", "import qualified LawSpecRuntime as LS",
          "import qualified LawSpecSchema as Schema", "import qualified LawSpecCodecs as Codec",
          "import qualified LawSpecData as Data", "import qualified LawSpecDataSchema as DataSchema",
          "import qualified LawSpecDataCodecs as Codecs"] ++
         concat [["import qualified LawSpecCollectionCodecs as Collections", "import qualified Data.Set as Set",
                  "import qualified Data.Map.Strict as Map", "import qualified Data.Sequence as Seq"]
                 | any (isCollectionsType . idText . dataId) declarations] ++ imports ++
         (if null imports then "" : environment else []) ++ [""])) <>
        D.hardline <> D.joinWith (D.hardline <> D.hardline) bodies <> D.hardline)) "generated" "source"
    environment = ["_lawspecSchema :: Schema.Schema",
      "_lawspecSchema = P.either P.error P.id DataSchema.schema",
      "_lawspecBits :: P.Int", "_lawspecBits = " ++ show bits]
    signature name types = D.group (text (name ++ " ::") <>
      D.nest 2 (D.softline <> D.joinWith (text " ->" <> D.softline) types))
    context identity body = E.apply "Codec.context" [E.quoted (idText identity)] <> text " P.$ do" <>
      D.nest 2 (D.hardline <> D.joinWith D.hardline body)
    binding name arguments body = text (unwords (name : "symbols" : arguments) ++ " =") <>
      D.nest 2 (D.hardline <> body)
    validate ty value = do
      ref <- Native.haskellTypeReferenceDoc ty
      pure (E.apply "Schema.validateWith" [E.apply "P.Just" [text "symbols"],text "_lawspecSchema",ref,text "_lawspecBits",value])
    adapters = [ (callee, (owner, adapter)) | d <- concatMap unitDefinitions units, definitionOrchestrates d
               , callee <- callsIn (definitionBody d), Just (owner, adapter) <- [lookup callee adapterTable] ]
    adapterTable = [(declarationId d, (unitId u, d)) | u <- units, d <- unitDeclarations u,
      declarationId d `notElem` map (declarationId . definitionDeclaration) (concatMap unitDefinitions units)]
    callsIn expression = case expressionNode expression of
      ExternalCall callee arguments -> callee : concatMap callsIn arguments
      _ -> concatMap callsIn (children expression)
    moduleOf owner = intercalate "." (map modulePart (split '.' (idText owner)))
    evaluator localName identity = maybe (Left "unresolved Haskell policy definition") (Right . localName) (lookup identity names)
    policyDoc localName key policy = do
      gates <- policyGates localName policy
      compensate <- case policyCompensate policy of
        Nothing -> pure (text "P.Nothing")
        Just undo -> (\name -> text ("(P.Just (\\value -> P.either P.error P.id (" ++ name ++ " symbols value)))")) <$> evaluator localName undo
      retry <- case policyRetry policy of
        Nothing -> pure (text "P.Nothing")
        Just r -> do
          let (kind, delay, step, factor, cap) = case retryStrategy r of
                Immediate -> ("immediate", 0, 0, 0, -1)
                Fixed d' -> ("fixed", d', 0, 0, -1)
                Linear d' s' -> ("linear", d', s', 0, -1)
                Exponential d' f c -> ("exponential", d', 0, f, maybe (-1) id c)
                Fibonacci d' -> ("fibonacci", d', 0, 0, -1)
                Custom _ -> ("custom", 0, 0, 0, -1)
              number n = text (if n < 0 then "(" ++ show (n :: Integer) ++ ")" else show n)
          condition <- case retryWhen r of
            Nothing -> pure (text "P.Nothing")
            Just p -> (\name -> text ("(P.Just (\\failure -> LS.truth (P.either P.error P.id (" ++ name ++ " symbols failure))))")) <$> evaluator localName p
          decide <- case retryStrategy r of
            Custom f -> (\name -> text ("(P.Just (\\attempt failure previous -> LS.retryDecision (P.either P.error P.id (" ++ name ++
              " symbols (LS.SInteger \"Integer\" attempt) failure (LS.durationScalar previous)))))")) <$> evaluator localName f
            _ -> pure (text "P.Nothing")
          pure (E.apply "P.Just" [E.apply "LS.Retry" [E.quoted kind, number delay, number step, number factor, number cap,
            number (retryAttempts r), E.quoted (jitterName (retryJitter r)), condition, decide]])
      pure (E.apply "LS.StagePolicy" [E.quoted (policyStage policy), retry, text (maybe "(-1)" show (policyTimeout policy)),
        E.quoted key, text "[" <> D.joinWith (text ", ") gates <> text "]", text (maybe "(-1)" show (policyCache policy)),
        text (if null (policyFailures policy) then "P.False" else "P.True"), compensate,
        text (maybe "P.Nothing" (\h -> "(P.Just (" ++ show (hedgeDelay h) ++ ", " ++ show (hedgeMost h) ++ "))") (policyHedge policy))])
    -- A gate's callbacks call the unit's copies of the resilience unit's
    -- state machines, with the policy's numbers.
    policyGates localName policy = do
      let checked call = "(P.either P.error P.id (" ++ call ++ "))"
          integer n = "(LS.SInteger \"Integer\" " ++ (if n < 0 then "(" ++ show n ++ ")" else show (n :: Integer)) ++ ")"
          integers = unwords . map integer
          now = "(LS.SInteger \"Integer\" now)"
          gate kind start admit finish wait = E.apply "LS.Gate" [E.quoted kind, text ("(\\now -> " ++ checked start ++ ")"),
            text ("(\\state now -> " ++ checked admit ++ ")"),
            text (maybe "P.Nothing" (\f -> "(P.Just (\\state now succeeded -> " ++ checked f ++ "))") finish), text ("(" ++ show (wait :: Integer) ++ ")")]
          waitCode wait = case wait of
            Nothing -> -2
            Just Nothing -> -1
            Just (Just d') -> d'
      breaker <- forM (policyBreaker policy) $ \b -> do
        start <- evaluator localName (breakerStart b)
        admit <- evaluator localName (breakerAdmit b)
        record <- evaluator localName (breakerRecord b)
        pure (gate "breaker" (start ++ " symbols " ++ now) (admit ++ " symbols state " ++ now)
          (Just (record ++ " symbols " ++ integers [breakerFailures b, breakerWindow b, breakerCooldown b] ++ " state " ++ now ++ " (LS.SBool succeeded)")) (-2))
      limit <- forM (policyLimit policy) $ \l -> do
        start <- evaluator localName (limitStart l)
        admit <- evaluator localName (limitAdmit l)
        let numbers = integers [limitCount l, limitPeriod l]
        pure (gate "limit" (start ++ " symbols " ++ numbers ++ " " ++ now) (admit ++ " symbols " ++ numbers ++ " state " ++ now)
          Nothing (waitCode (limitWait l)))
      bulkhead <- forM (policyBulkhead policy) $ \b -> do
        start <- evaluator localName (bulkheadStart b)
        admit <- evaluator localName (bulkheadAdmit b)
        release <- evaluator localName (bulkheadRelease b)
        let n = integers [bulkheadLimit b]
        pure (gate "bulkhead" (start ++ " symbols " ++ n ++ " " ++ now) (admit ++ " symbols " ++ n ++ " state " ++ now)
          (Just (release ++ " symbols state")) (waitCode (bulkheadWait b)))
      pure (maybe [] pure breaker ++ maybe [] pure limit ++ maybe [] pure bulkhead)
    jitterName j = case j of
      NoJitter -> "none" :: String
      FullJitter -> "full"
      EqualJitter -> "equal"
      DecorrelatedJitter -> "decorrelated"
    implementation contracts home (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          locals = zip (nub (map binderId binders)) ["value" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved Haskell local") id (lookup identity locals)
          arguments = map (local . binderId) (definitionArguments d)
          name = "evaluate" ++ show index
          -- Calls within the same module are unqualified.
          localName callee = case break (== '.') callee of
            (prefix, '.' : rest) | prefix == home -> rest
            _ -> callee
          external term values = case expressionNode term of
            ExternalCall identity _ | Just callee <- lookup identity names ->
              pure (E.checked (E.apply (localName callee) (text "symbols":values)))
            -- A workflow calls an adapter natively, through the codecs.
            ExternalCall identity _ | Just (owner, adapter) <- lookup identity adapterTable -> do
              let (parameterTypes, resultType) = functionType (declarationType adapter)
                  context' = E.apply "P.Just" [text "symbols"]
              codecs <- mapM (Native.haskellCodecDocWithContext context' declarations "_lawspecSchema" "_lawspecBits") parameterTypes
              resultCodec <- Native.haskellCodecDocWithContext context' declarations "_lawspecSchema" "_lawspecBits" resultType
              let call = E.apply (moduleOf owner ++ "." ++ declarationName adapter)
                    [E.checked (E.apply "Codec.decode" [codec, value]) | (codec, value) <- zip codecs values]
              -- An async step runs within its stage's timeout and hedge,
              -- when it has them.
              pure $ if declarationAsync adapter
                then E.apply "LS.awaitStep" [text "symbols", call,
                  text "(\\_native -> " <> E.checked (E.apply "Codec.encode" [resultCodec, text "_native"]) <> text ")"]
                else E.checked (E.apply "Codec.encode" [resultCodec, call])
            _ -> Left "unresolved Haskell total call"
      -- Arguments and results were checked where they were built, decoded
      -- or drawn; the native wrappers check values crossing from adapters.
      let checks = []
      rendered <- E.renderExpression declarations bits "_lawspecSchema" "symbols" local external (definitionBody d)
      -- A workflow stage with policies runs under the workflow runtime.
      body <- case definitionPolicy d of
        Nothing -> pure rendered
        Just policy | policyFrame policy -> pure (E.apply "LS.runWorkflow" [text "symbols", text "(\\() -> " <> rendered <> text ")"])
        Just policy -> do
          config <- policyDoc localName (idText (declarationId (definitionDeclaration d))) policy
          let key = case arguments of
                argument : _ -> text argument
                [] -> text "(LS.SAbsent \"Unit\")"
          pure (E.apply "LS.runStage" [text "symbols", config, text "(\\() -> " <> rendered <> text ")", key])
      let result = E.apply "P.pure" [text "result"]
      let evaluate = text "let result =" <> D.nest 6 (D.hardline <> body)
          checkedResult = D.group (E.apply "LS.forceScalar" [text "result"] <> text " `P.seq`" <>
            D.nest 2 (D.softline <> result))
          contract = lookup (declarationId (definitionDeclaration d))
            [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [evaluate,checkedResult])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checkedResult")] ++
                [(binderId b,"contractValue" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c ++ contractRuntimePostconditions c))]
              resolve identity = maybe (error "unbound Haskell definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression declarations bits "_lawspecSchema" "symbols" resolve external predicate
                pure (D.group (text "if " <> E.apply "LS.truth" [expression] <>
                  D.nest 2 (D.softline <> text "then P.Right ()" <> D.softline <>
                    text "else " <> E.apply "P.Left" [E.quoted (stage ++ " failed")])) )
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          pure (checks ++ pre ++ [evaluate,
            D.group (text "checkedResult <-" <> D.nest 2 (D.softline <> checkedResult))] ++
            post ++ [text "P.Right checkedResult"])
      pure (signature name (text "LS.SymbolContext" : replicate (length arguments) (text "LS.Scalar") ++
          [text "P.Either P.String LS.Scalar"]) <> D.hardline <>
        binding name arguments (context (declarationId (definitionDeclaration d)) statements))
    nativeUnit workflows unit = do
      methods <- mapM native [d | d <- unitDefinitions unit, definitionOrchestrates d == workflows]
      let name = (if workflows then "LawSpecWorkflows." else "LawSpecDefinitions.") ++
            intercalate "." (map modulePart (split '.' (idText (unitId unit))))
      pure (file name [if workflows then "import qualified LawSpecWorkflows as Workflows"
        else "import qualified LawSpecDefinitionBodies as Definitions"] methods)
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          name = declarationName declaration
          values = ["value" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.haskellDataType declarations) args
      resultType <- Native.haskellDataType declarations result
      codecs <- mapM (Native.haskellCodecDocWithContext (E.apply "P.Just" [text "symbols"]) declarations "_lawspecSchema" "_lawspecBits") args
      resultCodec <- Native.haskellCodecDocWithContext (E.apply "P.Just" [text "symbols"]) declarations "_lawspecSchema" "_lawspecBits" result
      callee <- maybe (Left "unresolved native Haskell call") Right (lookup (declarationId declaration) names)
      let checks = [D.group (text ("argument" ++ show i ++ " <-") <>
            D.nest 2 (D.softline <> E.apply "Codec.encode" [codec,text value]))
            | (i,(codec,value)) <- zip [0::Int ..] (zip codecs values)]
          invoke = E.apply callee (text "symbols" : [text ("argument" ++ show i) | i <- [0 .. length args - 1]])
      pure (signature name (text "LS.SymbolContext" : map text types ++
          [text "P.Either P.String " <> E.parens (text resultType)]) <> D.hardline <>
        binding name values (context (declarationId declaration)
          (checks ++ [D.group (text "result <-" <> D.nest 2 (D.softline <> invoke)),
            E.apply "Codec.decode" [resultCodec,text "result"]])) <>
        D.nest 2 (D.hardline <> text "where" <>
          D.nest 2 (D.hardline <> D.joinWith D.hardline (map text environment))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
    split delimiter value = case break (== delimiter) value of
      (a,[]) -> [a]
      (a,_:rest) -> a : split delimiter rest
    modulePart = concatMap capitalize . split '_'
    capitalize [] = []
    capitalize (c:cs) = toUpper c:cs
