-- | Java property scaffolding consumes checked propositions and generation plans.
module LawSpec.JavaProperties (Config(..), emitTests) where

import LawSpec.Bounds (inputRange, drawRange)
import qualified LawSpec.Core as C
import LawSpec.Backend
import LawSpec.Common
import LawSpec.Testing
import qualified LawSpec.Core.Value as V
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.JavaExpr as E
import qualified LawSpec.JavaTestHelpers as Helpers
import Data.List (intercalate, stripPrefix)
import LawSpec.TestNames (unitTestNames, lawWords)

-- | What the Java test emitter needs besides the plan: names, layout and
-- bindings, gathered so the emitter takes one argument.
data Config = Config
  { packageName :: String
  -- An async adapter's call, awaited.
  , awaitResult :: String -> D.Doc -> D.Doc
  , className :: String
  , schemaNeeded :: Bool
  , nativeGenerators :: Bool
  , constructorContracts :: Bool
  , nodeBudget :: Integer
  , machineBits :: Int
  , expression :: Expr -> D.Doc
  , literal :: V.Value -> Either [Diagnostic] D.Doc
  , checked :: Type -> D.Doc -> D.Doc
  , structural :: Type -> Bool
  , custom :: Type -> Bool
  , reference :: Type -> D.Doc
  , typeKey :: Type -> String
  , generator :: Type -> D.Doc
  -- A generator drawing a top-level integer from a refinement's range.
  , generatorWithin :: Maybe (Integer, Integer) -> Type -> D.Doc
  , nativeArgument :: Type -> D.Doc -> D.Doc
  , nativeResult :: Type -> D.Doc -> D.Doc
  -- The statements that install a law's handlers in symbols, for each case.
  , handlerInstalls :: Expanded -> [D.Doc]
  -- Each input's descriptor, for LawSpec's own search (LawSpec.Search):
  -- Nothing when the law takes no part in it.
  , searchDescriptors :: Expanded -> Maybe [String]
  }

text = D.text
statements = D.joinWith D.hardline
separate = D.joinWith (D.hardline <> D.hardline)
block = D.block 2
call = E.call
quoted = E.quoted
number :: Show a => a -> D.Doc
number = text . show
statement x = x <> text ";"
returned x = statement (text "return " <> x)
bind n x = D.group (text ("var " ++ n ++ " =") <> D.nest 4 (D.softline <> x) <> text ";")
lambda parameters body = D.group (text (parameters ++ " ->") <> D.nest 4 (D.softline <> body))
closure parameters body = D.multiline (text (parameters ++ " -> ") <> block body)
chain base methods = D.group (D.nest 4 base <> D.nest 4
  (mconcat [D.softbreak <> call ("." ++ name) args | (name,args) <- methods]))
runtime name = call ("LawSpecRuntime." ++ name)
truth x = runtime "truth" [x]
conjunction [] = text "true"
conjunction [x] = x
conjunction xs = D.group (D.nest 4 (D.joinWith (D.softline <> text "&& ") xs))
symbols = text "var symbols = new HashMap<String, Object>();"
fromValues xs = statements [bind (inputId input) (text ("_values.get(" ++ show index ++ ")")) |
  (index,input) <- zip [0::Int ..] xs]

-- | Laws become tests in Java's own property framework, so they run with the
-- tools the project already uses. ref:DEC-native-property-frameworks
emitTests :: Config -> Unit -> [Expanded] -> Either [Diagnostic] D.Doc
emitTests Config{..} unit laws = do
  let testNames = unitTestNames "java" (map name laws)
  bodies <- mapM (law testNames) (zip [0::Int ..] laws)
  let needsProperty = any ((== Nothing) . finiteCases) laws
      imports = ["java.util.HashMap" | not (null laws)] ++ ["java.util.Map",
        "lawspec.runtime.LawSpecRuntime", "lawspec.runtime.LawSpecRuntime.Value"] ++
        ["org.jetbrains.jetCheck.Generator" | schemaNeeded || needsProperty] ++
        ["org.jetbrains.jetCheck.PropertyChecker" | needsProperty] ++
        ["org.junit.jupiter.api.Test" | not (null laws)]
      members = [D.group (text "private static final lawspec.runtime.LawSpecSchema _schema =" <>
        D.nest 4 (D.softline <> text "lawspec.runtime.LawSpecDataSchema.create();")) | schemaNeeded] ++
        [seedDoc | needsProperty] ++
        -- Workflows wait on a virtual clock under test, and workflows and
        -- mailboxes read the Clock handler a law installs.
        [text "static " <> block (statements (text "LawSpecRuntime.useVirtualClock(0);" :
          [text "lawspec.Time.registerClock();" | installsClock unit]))] ++
        [text "static " <> block (statement (call "lawspec.testing.LawSpecHarness.parallelism"
          [quoted (unitName unit), quoted "threads (JUnit concurrent execution)", text "Runtime.getRuntime().availableProcessors()"])) | parallel] ++
        [Helpers.scalarHelpersDoc] ++ [Helpers.dataHelpersDoc machineBits generator | schemaNeeded] ++
        map contract (contracts unit) ++ bodies ++ map benchmark (maybe [] C.harnessBenchmarks settings)
  pure $ text "// Generated by LawSpec." <> D.hardline <>
    (if null packageName then mempty else text ("package " ++ packageName ++ ";") <> D.hardline <> D.hardline) <>
    text "import static org.junit.jupiter.api.Assertions.assertTrue;" <> D.hardline <> D.hardline <>
    statements [text ("import " ++ name ++ ";") | name <- imports] <> D.hardline <> D.hardline <>
    -- order random: LawSpec's seeded order (LawSpecOrder); parallel: JUnit's
    -- concurrent mode, enabled for such classes in junit-platform.properties.
    (if orderRandom then text "@org.junit.jupiter.api.TestMethodOrder(lawspec.testing.LawSpecOrder.class)" <> D.hardline else mempty) <>
    (if parallel then text "@org.junit.jupiter.api.parallel.Execution(org.junit.jupiter.api.parallel.ExecutionMode.CONCURRENT)" <> D.hardline else mempty) <>
    text ("public final class " ++ className ++ "LawSpecTest ") <> block (separate members) <> D.hardline
  where
    -- The harness plane (LawSpec.Harness). A test the harness runs is a
    -- method without @Test (harness:name), which the generated test passes
    -- to the runtime.
    settings = C.unitHarnessSettings unit
    orderRandom = maybe False C.harnessOrderRandom settings
    parallel = maybe False C.harnessParallel settings
    testFunction name body = case (stripPrefix "harness:" name, lookup name searchHooks) of
      (Just rest, hook) -> text ("void lawspecHarness" ++ rest ++ "() throws Throwable ") <> block (hooked hook body)
      (Nothing, Just hook) -> throwingTest name (hooked (Just hook) body)
      (Nothing, Nothing) -> junitTest name body
    hooked hook body = maybe body (\(before, after) -> statements ([before, body] ++ after)) hook
    -- LawSpec's own search (LawSpec.Search): a law's property test first
    -- replays the failing inputs the failure database kept, and a law with
    -- `target maximize` climbs after it, as JetCheck has no targeting. Each
    -- uses the law's case method, which checks one tuple of inputs.
    searchHooks =
      [ (propertyName index e ++ "_property", (statement (runtime "searchReplay" [quoted label, inputs', caseRef]),
          [statement (runtime "searchClimb" [quoted label, inputs', caseRef]) | C.harnessTarget (C.propertyHarness (original e)) /= Nothing]))
      | (index, e) <- zip [0::Int ..] laws, Just _ <- [searchDescriptors e]
      , let label = owner e ++ "::" ++ name e
            inputs' = text ("_lawspecInputs" ++ show index)
            caseRef = text ("this::_lawspecCase" ++ show index) ]
    propertyName index e =
      let h = C.propertyHarness (original e)
          base = unitTestNames "java" (map name laws) !! index
      in (if C.harnessSkip h == Nothing && (C.harnessKnownFailing h /= Nothing || runSettings h) then "harness:" else "") ++ base
    junitTest name body = text "@Test" <> D.hardline <> text ("void " ++ name ++ "() ") <> block body
    throwingTest name body = text "@Test" <> D.hardline <> text ("void " ++ name ++ "() throws Throwable ") <> block body
    runSettings h = C.harnessTimeout h /= Nothing || C.harnessRepeat h /= 1 || C.harnessRetries h /= 0 || observed h
    observed h = not (null (C.harnessCover h) && null (C.harnessClassify h) && null (C.harnessLabels h)) || C.harnessTarget h /= Nothing
    strings xs = text "new String[] {" <> D.commaSep (map quoted xs) <> text "}"
    booleans xs = text "new boolean[] {" <> D.commaSep xs <> text "}"
    observations e =
      let h = C.propertyHarness (original e)
          label = owner e ++ "::" ++ name e
      in [statement (call "lawspec.testing.LawSpecHarness.observe" [quoted label,
            strings [l | C.Cover _ l _ <- C.harnessCover h], booleans [truth (expr w) | C.Cover _ _ w <- C.harnessCover h],
            strings [l | (_, l) <- C.harnessClassify h], booleans [truth (expr c) | (c, _) <- C.harnessClassify h],
            text "new Value[] {" <> D.commaSep (map expr (C.harnessLabels h)) <> text "}"]) | observed h] ++
         [statement (call "lawspec.testing.LawSpecHarness.target" [expr score, quoted label]) | Just score <- [C.harnessTarget h]]
    -- The tests a law's harness wraps, skips or expects to fail.
    harnessTests fn label h kinds docs = case (C.harnessSkip h, C.harnessKnownFailing h) of
      (Just reason, _) -> [text "@org.junit.jupiter.api.Disabled(" <> quoted (label ++ ": " ++ reason) <> text ")" <> D.hardline <>
        junitTest (fn ++ "_skipped") mempty]
      (_, Just reason) -> docs ++ [junitTest (fn ++ "_knownFailing") (statement (call "lawspec.testing.LawSpecHarness.knownFailing"
        [quoted label, quoted (fn ++ "_knownFailing"), quoted reason,
         call "java.util.List.<lawspec.testing.LawSpecHarness.Body>of" [text ("this::lawspecHarness" ++ fn ++ k) | k <- kinds]]))]
      _ | runSettings h -> docs ++ [throwingTest (fn ++ k) (statement (call "lawspec.testing.LawSpecHarness.run"
            [quoted label, quoted (fn ++ k), number (maybe 0 id (C.harnessTimeout h)), number (C.harnessRepeat h), number (C.harnessRetries h),
             text "new int[] {" <> D.commaSep [number p | k == "_property", C.Cover p _ _ <- C.harnessCover h] <> text "}",
             strings [l | k == "_property", C.Cover _ l _ <- C.harnessCover h],
             text (if k == "_property" && observed h then "true" else "false"), text ("this::lawspecHarness" ++ fn ++ k)])) | k <- kinds]
        | otherwise -> docs
    benchmark (n, body) = throwingTest ("benchmark" ++ concatMap capital (lawWords n)) (statements [symbols,
      statement (call "lawspec.testing.LawSpecHarness.benchmark" [quoted n, closure "()" (statement (text "var _measured = " <> expr body))])])
    capital (c : cs) = toEnum (fromEnum c - (if c >= 'a' && c <= 'z' then 32 else 0)) : cs
    capital [] = []
    -- A property whose inputs harness strategies draw: the strategies draw
    -- in JetCheck's generator; their values' refinements are checked in the
    -- property, and the other inputs' filter the generator.
    harnessProperty fn label e check = do
      let h = C.propertyHarness (original e)
          strategyOf inp = [(n, d) | (i, n, d) <- C.harnessDraws h, i == C.binderId (C.quantifiedBinder inp)]
      draws <- mapM (\plan -> do
        let inp = domainInput plan
        case strategyOf inp of
          (strategy, d) : _ -> bind (inputId inp) <$> drawDoc inp strategy d
          [] -> pure (bind (inputId inp) (call "_environment.<Value>generate" [generatorWithin (inputRange machineBits inp) (inputType inp)]))) (generationPlan e)
      let defaults = [inp | inp <- inputs e, null (strategyOf inp)]
          strategyChecks = [statement (call "lawspec.testing.LawSpecHarness.checkDrawn" [quoted strategy, quoted (inputName inp),
              conjunction (map (truth . expr) (inputRefinements inp)), text (inputId inp)])
            | inp <- inputs e, (strategy, _) : _ <- [strategyOf inp], not (null (inputRefinements inp))]
          base = call "Generator.from" [closure "_environment" (statements
            ([symbols] ++ draws ++ [returned (call "new _LawSpecInputs" [call "java.util.List.of" [text (inputId inp) | inp <- inputs e], text "symbols"])]))]
          predicates = concatMap inputRefinements defaults
          bindingsDoc = statements [text "var symbols = _inputs.symbols();", text "var _values = _inputs.values();", fromValues (inputs e)]
          generator = if null predicates then base else chain base [("suchThat",
            [closure "_inputs" (statements [bindingsDoc, returned (conjunction (map (truth . expr) predicates))])])]
      pure $ testFunction (fn ++ "_property") $ statement $ chain (text "_lawspecChecker()")
        [("withIterationCount",[number (cases (generation e))]),
         ("forAll",[generator, closure "_inputs" (statements ([bindingsDoc] ++ strategyChecks ++ handlerInstalls e ++ [check, returned (text "true")]))])]
    -- A choice among n: a wide draw, reduced, so the weights hold.
    chooser = text "_n -> _environment.generate(Generator.integers(0, java.lang.Integer.MAX_VALUE)) % _n"
    drawDoc inp strategy d = case d of
      C.DrawAny ty aim -> pure (call "_environment.<Value>generate" [maybe (generator ty) (\range -> generatorWithin (Just range) ty) (drawRange machineBits inp ty aim)])
      C.DrawOneOf _ values -> pure (call "lawspec.testing.LawSpecHarness.oneOf" [chooser,
        call "java.util.List.<java.util.function.Supplier<Value>>of" [lambda "()" (expr v) | v <- values]])
      C.DrawFrequency alternatives -> do
        options <- mapM (\(w, a) -> (\doc -> call "new lawspec.testing.LawSpecHarness.Weighted" [number w, lambda "()" doc]) <$> drawDoc inp strategy a) alternatives
        pure (call "lawspec.testing.LawSpecHarness.frequency" [chooser, call "java.util.List.of" options])
      C.DrawSuchThat inner binder predicate limit -> do
        doc <- drawDoc inp strategy inner
        pure (call "lawspec.testing.LawSpecHarness.suchThat" [lambda "()" doc, lambda (localName (C.binderId binder)) (truth (expr predicate)), number limit, quoted strategy])
      C.DrawBind binder from rest -> do
        fromDoc <- drawDoc inp strategy from
        restDoc <- drawDoc inp strategy rest
        pure (text "((java.util.function.Function<Value, Value>) " <> lambda (localName (C.binderId binder)) restDoc <> text ").apply(" <> fromDoc <> text ")")
    -- LAWSPEC_SEED fixes jetCheck's seed, so a run can be repeated exactly
    -- (lawspec test records the seed of every passing run).
    seedDoc = text "private static PropertyChecker.Parameters _lawspecChecker() " <> block (statements
      [ text "var seed = System.getenv(\"LAWSPEC_SEED\");"
      , text "return seed == null ? PropertyChecker.customized() : PropertyChecker.customized().withSeed(Long.parseLong(seed));" ])
    expr = expression
    assertionDoc context proposition = case proposition of
      AssertAll ps -> statements (map (assertionDoc context) ps)
      AssertImplies guard body -> text "if (" <> truth (expr guard) <> text ") " <>
        block (assertionDoc context body)
      AssertEqual a b ->
        let message = quoted (context ++ " | expect " ++ prettyExpr a ++ " = " ++ prettyExpr b)
        in statement (call "_lawspecAssert" ([message] ++ (if custom (expressionType a) then [reference (expressionType a),text "symbols"] else []) ++
          [lambda "()" (expr a),lambda "()" (expr b)]))
    -- A law's resources: each case acquires them, then runs, then releases
    -- them, the last first, even when the case fails.
    bracketed e docs = foldr wrap (statements docs) (C.propertyResources (original e))
      where
        -- A shared resource (share R per ...): the runtime keeps one per
        -- scope key, resets it before each later use, and releases it when
        -- the JVM exits. Its reset and release see it under another name,
        -- as a lambda may not redeclare the local.
        wrap r inner | Just key <- C.resourceShared r, Just reset <- C.resourceReset r =
          let rid = C.binderId (C.resourceBinder r)
              local = localName rid
              other = C.Id (C.idText rid ++ "shared")
              usingIt body = closure (localName other) (bind "unused" (expr (C.renameLocal rid other body)))
          in statements [bind local (runtime "share" [quoted key, lambda "()" (expr (C.resourceAcquire r)), usingIt reset, usingIt (C.resourceRelease r),
              text (if C.resourceConcurrent r then "true" else "false")]),
            text "try " <> block inner <> text " finally " <> block (statement (runtime "unshare" [quoted key]))]
        wrap r inner =
          let local = localName (C.binderId (C.resourceBinder r))
          in statements [bind local (expr (C.resourceAcquire r)),
            text "try " <> block inner <> text " finally " <> block (bind (local ++ "Released") (expr (C.resourceRelease r)))]
    contract c =
      let args = contractArguments c
          (rn,rt) = contractResult c
          params = text "Map<String, Object> symbols" : [text ("Value " ++ n) | (n,_) <- args]
          context stage ps = quoted (contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps))
          require stage ps = statement (runtime "requireContract" [conjunction (map (truth . expr) ps),context stage ps])
          invocation = awaitResult (adapterName unit (C.contractDeclaration c)) (call (className ++ "." ++ adapterName unit (C.contractDeclaration c)) [nativeArgument ty (text n) | (n,ty) <- args])
      in call ("private static Value _lawspec_call_" ++ contractName c) params <> text " " <>
        block (statements [require "precondition" (contractPreconditions c),
          bind rn (nativeResult rt invocation),require "postcondition" (contractPostconditions c),returned (text rn)])
    law testNames (index,e) = do
      let label = owner e ++ "::" ++ name e
          h = C.propertyHarness (original e)
          base = testNames !! index
          fn = (if C.harnessSkip h == Nothing && (C.harnessKnownFailing h /= Nothing || runSettings h) then "harness:" else "") ++ base
      exampleDocs <- mapM (\(i,ex) -> pure $ testFunction (fn ++ "_example" ++ show i) $ statements
        ([symbols] ++ handlerInstalls e ++ [bind n (expr v) | (n,v) <- bindings ex] ++
        [bracketed e (map (assertionDoc (label ++ " example " ++ exampleName ex)) (expectations ex) ++
          [assertionDoc label (assertion e)])])) (zip [0::Int ..] (examples (original e)))
      boundaryDocs <- mapM (\(i,vs) -> do
        values <- mapM literal vs
        pure $ testFunction (fn ++ "_boundary" ++ show i) $ statements
          ([symbols] ++ handlerInstalls e ++ [bind (inputId inp) (checked (inputType inp) v) | (inp,v) <- zip (inputs e) values] ++
          [bracketed e [assertionDoc (label ++ " boundary " ++ show i) (assertion e)]]))
        (zip [0::Int ..] (maybe (boundaryCases e) id (finiteCases e)))
      let descriptors = searchDescriptors e
          remembered doc = case descriptors of
            Nothing -> doc
            Just _ -> text "try " <> block doc <> text " catch (RuntimeException | Error _lawspecError) " <> block (statements
              [statement (runtime "searchRemember" [quoted label, text ("_lawspecInputs" ++ show index),
                 call "java.util.List.of" [text (inputId inp) | inp <- inputs e]]), text "throw _lawspecError;"])
          searchDocs = case descriptors of
            Nothing -> []
            Just ds ->
              let refinements = concatMap inputRefinements (inputs e)
              in [ text ("private static final java.util.List<String> _lawspecInputs" ++ show index ++ " = java.util.List.of(") <>
                     D.commaSep (map quoted ds) <> text ");"
                 , text ("private Double _lawspecCase" ++ show index ++ "(java.util.List<Value> _values) throws Exception ") <> block (statements
                     ([symbols] ++ handlerInstalls e ++
                      [bind (inputId inp) (checked (inputType inp) (text ("_values.get(" ++ show i ++ ")"))) | (i, inp) <- zip [0::Int ..] (inputs e)] ++
                      [text "if (!(" <> conjunction (map (truth . expr) refinements) <> text ")) return null;" | not (null refinements)] ++
                      [bracketed e [assertionDoc (label ++ " search") (assertion e)],
                       returned (maybe (text "0.0") (\score -> runtime "searchNumber" [expr score]) (C.harnessTarget h))])) ]
      let check = bracketed e (observations e ++ [remembered (assertionDoc (label ++ " property") (assertion e))])
      property <- if finiteCases e /= Nothing then pure []
        else if not (null (C.harnessDraws h)) then (:[]) <$> harnessProperty fn label e check
        else if nativeGenerators || any (structural . inputType) (inputs e) then (:[]) <$> structuralProperty fn e check
        else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract"
          then (:[]) <$> refinedProperty fn label e check
          else pure [testFunction (fn ++ "_property") $ statement $ call "_lawspecChecker().forAll"
            [text "Generator.integers()",closure "seed" $ statements ([symbols] ++ handlerInstalls e ++
              [bind (inputId inp) (runtime "sample" [quoted (typeKey (inputType inp)),
                text ("seed + " ++ show i),number machineBits]) | (i,inp) <- zip [0::Int ..] (inputs e)] ++
              [check,returned (text "true")])]]
      let kinds = ["_example" ++ show i | i <- [0 .. length exampleDocs - 1]] ++ ["_boundary" ++ show i | i <- [0 .. length boundaryDocs - 1]] ++
            ["_property" | not (null property)]
      pure $ metadataDocument 98 "//" e <> separate (searchDocs ++ harnessTests base label h kinds (exampleDocs ++ boundaryDocs ++ property))
    structuralProperty fn e check = do
      strategies <- mapM (contextualStrategy (generation e)) (generationPlan e)
      let predicatesFor inp = concatMap conjuncts (inputRefinements inp)
          generate inp = call "_environment.<Value>generate"
            [maybe (generatorWithin (inputRange machineBits inp) (inputType inp)) id (lookup (inputId inp) strategies)]
          prepare inp | nativeGenerators = generate inp
          prepare inp = prepareElements (C.binderId (C.quantifiedBinder inp))
            (predicatesFor inp) (generate inp)
          valueGenerator = call "java.util.List.of" [text (inputId inp) | inp <- inputs e]
          base = call (if nativeGenerators then "Generator.<_LawSpecInputs>from" else "Generator.from") [closure "_environment" (statements
            ([symbols] ++ [bind (inputId inp) (prepare inp) | inp <- inputs e] ++
             [returned (call "new _LawSpecInputs" [valueGenerator,text "symbols"])]))]
          predicates = concatMap inputRefinements (inputs e)
          bindingsDoc = statements [text "var symbols = _inputs.symbols();",
            text "var _values = _inputs.values();",fromValues (inputs e)]
          captured = if nativeGenerators then call "lawspec.testing.LawSpecDataStrategies.capture" [base] else base
          inputName = if nativeGenerators then "_captured" else "_inputs"
          unpack = [bind "_inputs" (call "_captured.requireValue" []) | nativeGenerators]
          strategy = if null predicates then captured else chain captured [("suchThat",
            [closure inputName (statements
              ([text "if (_captured.error() != null) return true;" | nativeGenerators] ++
               unpack ++ [bindingsDoc,returned (conjunction (map (truth . expr) predicates))]))])]
          callback = closure inputName (statements (unpack ++ [bindingsDoc] ++ handlerInstalls e ++ [check,returned (text "true")]))
      -- Keep JetCheck's native tree shrinking and its growing list budget.
      let invocation count size = statement $ chain (text "_lawspecChecker()")
            [("withIterationCount",[number count]),
             ("withSizeHint",[lambda "_iteration" size]),
             ("forAll",[strategy,callback])]
          growing iteration = text "(int) " <> call "Math.min"
            [text "java.lang.Integer.MAX_VALUE",text ("2L * " ++ iteration ++ " + 8")]
          body | nativeGenerators || constructorContracts =
            text ("for (int _case = 0; _case < " ++ show (cases (generation e)) ++ "; _case++) ") <>
              block (statements [bind "_sizeHint" (growing "_case"),invocation (1 :: Int) (text "_sizeHint")])
            | otherwise = invocation (cases (generation e)) (growing "_iteration")
      pure $ testFunction (fn ++ "_property") body
    contextualStrategy settings plan = do
      let input = domainInput plan
          ty = inputType input
      seeds <- mapM literal (generatorBoundaries plan)
      let hints = [expr hint | hint <- generatorHints plan, expressionType hint == ty,
            case C.expressionNode hint of
              C.Constant _ -> True
              C.Local _ -> True
              _ -> False]
          strategy = case requiredSymbol plan of
            value:_ -> call "Generator.constant" [expr value]
            [] | Just indexed <- generatorIndex plan ->
              -- The target is evaluated from inputs drawn earlier in this environment.
              call "lawspec.testing.LawSpecDataStrategies.indexedGenerator"
                [text "_schema",reference ty,number machineBits,number nodeBudget,
                 expr (indexedTarget indexed),equationsDoc (indexedEquations indexed),
                 text (className ++ "LawSpecTest::_lawspecScalarGenerator")]
            [] | nativeGenerators || constructorContracts -> chain
              (call "lawspec.testing.LawSpecDataStrategies.checkedGenerator"
                ([text "_schema",reference ty,number machineBits,number nodeBudget,number (maxAttempts settings),
                 text "symbols",call "java.util.List.of" (seeds ++ hints),
                 text (className ++ "LawSpecTest::_lawspecScalarGenerator")] ++
                [call "lawspec.testing.LawSpecNativeGenerators.factories" [] | nativeGenerators]))
              [("map",[D.group (text "lawspec.testing.LawSpecDataStrategies.Checked" <> D.nest 4 (D.softbreak <> text "::requireValue"))])]
            [] -> generatorWithin (inputRange machineBits input) ty
      pure (inputId input,strategy)
    equationsDoc equations = call "java.util.Map.ofEntries"
      [call "java.util.Map.entry" [quoted (C.idText tag), call "java.util.List.of" (map quoted texts)]
      | (tag,texts) <- equations]
    requiredSymbol plan
      | nativeGenerators = []
      | inputType (domainInput plan) /= C.scalarType "Symbol" = []
      | otherwise = concatMap required (generatorPredicates plan)
      where
        current = C.binderId (generatorBinder plan)
        required term = case C.expressionNode term of
          C.ShortCircuit C.And a b -> required a ++ required b
          C.Binary C.Equal _ a b -> [value | (local,value) <- [(a,b),(b,a)],
            C.expressionNode local == C.Local current,
            expressionType value == C.scalarType "Symbol",
            current `notElem` C.freeBinders value,
            case C.expressionNode value of
              C.Constant _ -> True
              C.Local _ -> True
              _ -> False]
          _ -> []
    conjuncts term = case C.expressionNode term of
      C.ShortCircuit C.And left right -> conjuncts left ++ conjuncts right
      _ -> [term]
    -- Mapping the framework's native list tree preserves its shrink history.
    -- Every already-valid list is a fixed point; empty element domains still
    -- have the empty-list witness. Keep the final predicate check for any
    -- constraints that relate the entire list to other values.
    prepareElements identity predicates original = foldl prepare original
      [(binder,predicate) | term <- predicates,
        C.AllElements value binder predicate <- [C.expressionNode term],
        C.Local name <- [C.expressionNode value], name == identity]
      where
        prepare value (binder,predicate) =
          let name = localName (C.binderId binder)
              prepared = prepareElements (C.binderId binder) (conjuncts predicate) (text name)
          in runtime "refineElements" [value,lambda name prepared,lambda name (expr predicate)]
    domain e (index,plan) = do
      seeds <- mapM literal (generatorBoundaries plan)
      let inp = domainInput plan
          prior = take index (inputs e)
          bounds = array "LawSpecRuntime.Bound"
            [call "new LawSpecRuntime.Bound" [quoted op,expr v] | (op,v) <- domainBounds plan]
          candidates = runtime "domainCandidates" [quoted (typeKey (inputType inp)),text "_seed",number machineBits,
            bounds,E.array (seeds ++ map expr (generatorHints plan))]
          seedFn = closure "(_values, _seed)" (statements ([fromValues prior | not (null prior)] ++ [returned candidates]))
          predicate = closure "_values" (statements
            [fromValues (prior ++ [inp]),returned (conjunction (map (truth . expr) (inputRefinements inp)))])
      pure (call "new LawSpecRuntime.Domain" [seedFn,predicate])
    refinedProperty fn label e check = do
      domains <- mapM (domain e) (zip [0::Int ..] (generationPlan e))
      let cfg = generation e
          callback = closure "_values" (statements ([fromValues (inputs e)] ++ handlerInstalls e ++ [check]))
          invocation = runtime "refinedCase" [array "LawSpecRuntime.Domain" domains,
            text "seed",number (maxAttempts cfg),number (maxShrinks cfg),callback,
            quoted (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ testFunction (fn ++ "_property") $ statement $ chain (text "_lawspecChecker()")
        [("withIterationCount",[number (cases cfg)]),
         ("forAll",[text "Generator.integers()",closure "seed" (statements [symbols,statement invocation,returned (text "true")])])]
    array name values = D.group (text ("new " ++ name ++ "[] {") <>
      D.nest 2 (D.softbreak <> D.commaSep values) <> D.softbreak <> text "}")

-- Whether a unit's laws install a Clock handler, so the test registers how
-- the runtime reads one (lawspec.time's registerClock).
installsClock :: Unit -> Bool
installsClock unit = or [ C.abilityKey a == "lawspec.time::ability::Clock"
                        | p <- C.unitProperties unit, (a, _) <- C.propertyHandlers p ]
