-- Native entry points and checked implementation helpers for total definitions.
module LawSpec.JavaDefinitions (emitJavaDefinitions, emitJvmDefinitionBodies, definitionCalls) where

import Control.Monad (forM)
import Data.Char (toUpper)
import Data.List (intercalate)
import LawSpec.Common
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import qualified LawSpec.JavaData as Native
import qualified LawSpec.JavaExpr as E
import qualified LawSpec.Code.Doc as D

definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d),
  "lawspec.runtime.LawSpecDefinitionBodies.evaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitJavaDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitJavaDefinitions = emitDefinitions True

emitJvmDefinitionBodies :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitJvmDefinitionBodies = emitDefinitions False

emitDefinitions :: Bool -> D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitDefinitions _ _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitDefinitions withNative layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  methods <- mapM (implementation contracts) (zip [0::Int ..] (concatMap unitDefinitions units))
  let source = file "lawspec.runtime" "LawSpecDefinitionBodies"
        ["java.util.Map", "lawspec.runtime.LawSpecRuntime.Value"] methods
  native <- if withNative then mapM nativeUnit (filter (not . null . unitDefinitions) units) else pure []
  pure (source : native)
  where
    assign name value = D.group (D.text ("var " ++ name ++ " =") <>
      D.nest 4 (D.softline <> value) <> D.text ";")
    contextual identity body = D.text "try " <> D.block 2 body <>
      D.text " catch (RuntimeException error) " <>
      D.block 2 (assign "context" (E.quoted (idText identity ++ ": ")) <> D.hardline <>
        D.text "throw " <> E.call "new IllegalArgumentException"
          [D.text "context + error.getMessage()",D.text "error"] <> D.text ";")
    callees = definitionCalls units
    file package name imports methods = Artifact
      ("src/main/java/" ++ map (\c -> if c == '.' then '/' else c) package ++ "/" ++ name ++ ".java")
      (D.render layout (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
        D.text ("package " ++ package ++ ";") <> D.hardline <> D.hardline <>
        D.joinWith D.hardline [D.text ("import " ++ item ++ ";") | item <- imports] <>
        D.hardline <> D.hardline <> D.text ("public final class " ++ name ++ " ") <>
        D.block 2 (D.joinWith (D.hardline <> D.hardline)
          ([D.text ("private " ++ name ++ "() {}"),
            D.text "private static final lawspec.runtime.LawSpecSchema _schema =" <>
              D.nest 4 (D.hardline <> D.text "lawspec.runtime.LawSpecDataSchema.create();")] ++ methods)) <> D.hardline))
      "generated" "source"
    nativeUnit unit = do
      let parts = split '.' (idText (unitId unit))
          name = concatMap capitalize (split '_' (last parts))
          package = intercalate "." ("lawspec" : "definitions" : init parts)
      methods <- mapM native (unitDefinitions unit)
      pure (file package name ["java.util.Map"] methods)
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
      nativeArgs <- mapM (Native.javaDataTypeDoc declarations) args
      nativeResult <- Native.javaDataTypeDoc declarations result
      codecs <- mapM (Native.javaCodecDocWithContext (D.text "symbols") declarations bits) args
      resultCodec <- Native.javaCodecDocWithContext (D.text "symbols") declarations bits result
      evaluator <- maybe (Left "unresolved Java definition") Right (lookup (declarationId declaration) callees)
      let parameters = D.text "Map<String, Object> symbols" :
            [ty <> D.text (" value" ++ show i) | (i,ty) <- zip [0::Int ..] nativeArgs]
          opening = "public static " ++ D.render D.Compact nativeResult ++ " " ++ declarationName declaration ++ "("
          normalSignature = D.group (D.text "public static " <> nativeResult <>
            D.text (" " ++ declarationName declaration ++ "(") <>
            D.nest 4 (D.softbreak <> D.group (D.commaSep parameters)) <> D.text ") ")
          wrappedSignature = D.text "public static " <> nativeResult <>
            D.nest 4 (D.hardline <> D.text (declarationName declaration ++ "(") <>
              D.nest 4 (D.softbreak <> D.group (D.commaSep parameters)) <> D.text ") ")
          signature = D.prefixChoice opening normalSignature wrappedSignature
          input i codec = [assign ("codec" ++ show i) codec,
            D.text ("var argument" ++ show i ++ " = codec" ++ show i ++ ".encode(value" ++ show i ++ ");")]
          invocation = E.call evaluator (D.text "symbols" : [D.text ("argument" ++ show i) | i <- [0 .. length args - 1]])
          body = concat [input i codec | (i,codec) <- zip [0::Int ..] codecs] ++
            [assign "result" invocation,
             assign "resultCodec" resultCodec,
             D.text "return resultCodec.decode(result);"]
      pure (signature <> D.block 2 (contextual (declarationId declaration) (D.joinWith D.hardline body)))
    implementation contracts (index,d) = do
      let args = definitionArguments d
          binders = args ++ nestedBinders (definitionBody d)
          names = [(binderId b,"value" ++ show i) | (i,b) <- zip [0::Int ..] binders]
          local identity = maybe (error "unbound Java definition binder") id (lookup identity names)
          external expression values = case expressionNode expression of
            ExternalCall identity _ -> do
              name <- maybe (Left "unknown Java definition") Right (lookup identity callees)
              pure (E.call name (D.text "symbols":values))
            _ -> Left "expected resolved definition call"
          signature = E.call ("public static Value evaluate" ++ show index)
            (D.text "Map<String, Object> symbols" : [D.text ("Value input" ++ show i) | i <- [0..length args-1]]) <> D.text " "
      checks <- forM (zip [0::Int ..] args) $ \(i,b) -> do
        ref <- E.reference (binderType b)
        pure (assign (local (binderId b))
          (E.call "_schema.validate" [ref,D.text ("input" ++ show i),D.text (show bits),D.text "symbols"]))
      body <- E.renderExpression declarations bits local external (definitionBody d)
      ref <- E.reference (expressionType (definitionBody d))
      let contract = lookup (declarationId (definitionDeclaration d)) [(contractDeclaration c,c) | c <- contracts]
          validated = E.call "_schema.validate" [ref,D.text "result",D.text (show bits),D.text "symbols"]
      statements <- case contract of
        Nothing -> pure (checks ++ [assign "result" body,D.text "return " <> validated <> D.text ";"])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c)) (map (local . binderId) args) ++
                [(binderId (contractResult c),"checkedResult")] ++
                [(binderId b,"contractValue" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c))]
              resolve identity = maybe (error "unbound Java definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression declarations bits resolve external predicate
                pure (E.call "LawSpecRuntime.requireContract"
                  [E.call "LawSpecRuntime.truth" [expression],E.quoted stage] <> D.text ";")
          pre <- mapM (require "precondition") (contractPreconditions c)
          post <- mapM (require "postcondition") (contractPostconditions c)
          pure (checks ++ pre ++ [assign "result" body,assign "checkedResult" validated] ++
            post ++ [D.text "return checkedResult;"])
      pure (signature <> D.block 2 (contextual (declarationId (definitionDeclaration d))
        (D.joinWith D.hardline statements)))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat
        [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
    split delimiter value = case break (== delimiter) value of
      (a,[]) -> [a]
      (a,_:rest) -> a : split delimiter rest
    capitalize [] = []
    capitalize (c:cs) = toUpper c : cs
