-- Java property scaffolding consumes checked propositions and generation plans.
module LawSpec.JavaProperties (Config(..), emitTests) where

import qualified LawSpec.Core as C
import LawSpec.Backend
import LawSpec.Common
import LawSpec.Testing
import qualified LawSpec.Core.Value as V
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.JavaExpr as E
import qualified LawSpec.JavaTestHelpers as Helpers
import Data.List (intercalate)

data Config = Config
  { packageName :: String
  , className :: String
  , schemaNeeded :: Bool
  , nativeGenerators :: Bool
  , constructorContracts :: Bool
  , nodeBudget :: Integer
  , machineBits :: Int
  , expression :: Expr -> D.Doc
  , literal :: V.Value -> Either [Diagnostic] D.Doc
  , checked :: Type -> D.Doc -> D.Doc
  , structural :: Type -> Bool
  , custom :: Type -> Bool
  , reference :: Type -> D.Doc
  , typeKey :: Type -> String
  , generator :: Type -> D.Doc
  , nativeArgument :: Type -> D.Doc -> D.Doc
  , nativeResult :: Type -> D.Doc -> D.Doc
  }

text = D.text
statements = D.joinWith D.hardline
separate = D.joinWith (D.hardline <> D.hardline)
block = D.block 2
call = E.call
quoted = E.quoted
number :: Show a => a -> D.Doc
number = text . show
statement x = x <> text ";"
returned x = statement (text "return " <> x)
bind n x = D.group (text ("var " ++ n ++ " =") <> D.nest 4 (D.softline <> x) <> text ";")
lambda parameters body = D.group (text (parameters ++ " ->") <> D.nest 4 (D.softline <> body))
closure parameters body = D.multiline (text (parameters ++ " -> ") <> block body)
chain base methods = D.group (D.nest 4 base <> D.nest 4
  (mconcat [D.softbreak <> call ("." ++ name) args | (name,args) <- methods]))
runtime name = call ("LawSpecRuntime." ++ name)
truth x = runtime "truth" [x]
conjunction [] = text "true"
conjunction [x] = x
conjunction xs = D.group (D.nest 4 (D.joinWith (D.softline <> text "&& ") xs))
symbols = text "var symbols = new HashMap<String, Object>();"
testFunction name body = text "@Test" <> D.hardline <> text ("void " ++ name ++ "() ") <> block body
fromValues xs = statements [bind (inputId input) (text ("_values.get(" ++ show index ++ ")")) |
  (index,input) <- zip [0::Int ..] xs]

emitTests :: Config -> Unit -> [Expanded] -> Either [Diagnostic] D.Doc
emitTests Config{..} unit laws = do
  bodies <- mapM law (zip [0::Int ..] laws)
  let needsProperty = any ((== Nothing) . finiteCases) laws
      imports = ["java.util.HashMap" | not (null laws)] ++ ["java.util.Map",
        "lawspec.runtime.LawSpecRuntime", "lawspec.runtime.LawSpecRuntime.Value"] ++
        ["org.jetbrains.jetCheck.Generator" | schemaNeeded || needsProperty] ++
        ["org.jetbrains.jetCheck.PropertyChecker" | needsProperty] ++
        ["org.junit.jupiter.api.Test" | not (null laws)]
      members = [D.group (text "private static final lawspec.runtime.LawSpecSchema _schema =" <>
        D.nest 4 (D.softline <> text "lawspec.runtime.LawSpecDataSchema.create();")) | schemaNeeded] ++
        [Helpers.scalarHelpersDoc] ++ [Helpers.dataHelpersDoc machineBits generator | schemaNeeded] ++
        map contract (contracts unit) ++ bodies
  pure $ text "// Generated by LawSpec." <> D.hardline <>
    (if null packageName then mempty else text ("package " ++ packageName ++ ";") <> D.hardline <> D.hardline) <>
    text "import static org.junit.jupiter.api.Assertions.assertTrue;" <> D.hardline <> D.hardline <>
    statements [text ("import " ++ name ++ ";") | name <- imports] <> D.hardline <> D.hardline <>
    text ("public final class " ++ className ++ "LawSpecTest ") <> block (separate members) <> D.hardline
  where
    expr = expression
    assertionDoc context proposition = case proposition of
      AssertAll ps -> statements (map (assertionDoc context) ps)
      AssertImplies guard body -> text "if (" <> truth (expr guard) <> text ") " <>
        block (assertionDoc context body)
      AssertEqual a b ->
        let message = quoted (context ++ " | expect " ++ prettyExpr a ++ " = " ++ prettyExpr b)
        in statement (call "_lawspecAssert" ([message] ++ (if custom (expressionType a) then [reference (expressionType a),text "symbols"] else []) ++
          [lambda "()" (expr a),lambda "()" (expr b)]))
    contract c =
      let args = contractArguments c
          (rn,rt) = contractResult c
          params = text "Map<String, Object> symbols" : [text ("Value " ++ n) | (n,_) <- args]
          context stage ps = quoted (contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps))
          require stage ps = statement (runtime "requireContract" [conjunction (map (truth . expr) ps),context stage ps])
          invocation = call (className ++ "." ++ contractName c) [nativeArgument ty (text n) | (n,ty) <- args]
      in call ("private static Value _lawspec_call_" ++ contractName c) params <> text " " <>
        block (statements [require "precondition" (contractPreconditions c),
          bind rn (nativeResult rt invocation),require "postcondition" (contractPostconditions c),returned (text rn)])
    law (index,e) = do
      let label = owner e ++ "::" ++ name e
          fn = "law" ++ show index
      exampleDocs <- mapM (\(i,ex) -> pure $ testFunction (fn ++ "Example" ++ show i) $ statements
        ([symbols] ++ [bind n (expr v) | (n,v) <- bindings ex] ++
        map (assertionDoc (label ++ " example " ++ exampleName ex)) (expectations ex) ++
        [assertionDoc label (assertion e)])) (zip [0::Int ..] (examples (original e)))
      boundaryDocs <- mapM (\(i,vs) -> do
        values <- mapM literal vs
        pure $ testFunction (fn ++ "Boundary" ++ show i) $ statements
          ([symbols] ++ [bind (inputId inp) (checked (inputType inp) v) | (inp,v) <- zip (inputs e) values] ++
          [assertionDoc (label ++ " boundary " ++ show i) (assertion e)]))
        (zip [0::Int ..] (maybe (boundaryCases e) id (finiteCases e)))
      let check = assertionDoc (label ++ " property") (assertion e)
      property <- if finiteCases e /= Nothing then pure []
        else if nativeGenerators || any (structural . inputType) (inputs e) then (:[]) <$> structuralProperty fn e check
        else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract"
          then (:[]) <$> refinedProperty fn label e check
          else pure [testFunction (fn ++ "Property") $ statement $ call "PropertyChecker.forAll"
            [text "Generator.integers()",closure "seed" $ statements ([symbols] ++
              [bind (inputId inp) (runtime "sample" [quoted (typeKey (inputType inp)),
                text ("seed + " ++ show i),number machineBits]) | (i,inp) <- zip [0::Int ..] (inputs e)] ++
              [check,returned (text "true")])]]
      pure $ metadataDocument 98 "//" e <> separate (exampleDocs ++ boundaryDocs ++ property)
    structuralProperty fn e check = do
      strategies <- mapM (contextualStrategy (generation e)) (generationPlan e)
      let predicatesFor inp = concatMap conjuncts (inputRefinements inp)
          generate inp = call "_environment.<Value>generate"
            [maybe (generator (inputType inp)) id (lookup (inputId inp) strategies)]
          prepare inp | nativeGenerators = generate inp
          prepare inp = prepareElements (C.binderId (C.quantifiedBinder inp))
            (predicatesFor inp) (generate inp)
          valueGenerator = call "java.util.List.of" [text (inputId inp) | inp <- inputs e]
          base = call (if nativeGenerators then "Generator.<_LawSpecInputs>from" else "Generator.from") [closure "_environment" (statements
            ([symbols] ++ [bind (inputId inp) (prepare inp) | inp <- inputs e] ++
             [returned (call "new _LawSpecInputs" [valueGenerator,text "symbols"])]))]
          predicates = concatMap inputRefinements (inputs e)
          bindingsDoc = statements [text "var symbols = _inputs.symbols();",
            text "var _values = _inputs.values();",fromValues (inputs e)]
          captured = if nativeGenerators then call "lawspec.testing.LawSpecDataStrategies.capture" [base] else base
          inputName = if nativeGenerators then "_captured" else "_inputs"
          unpack = [bind "_inputs" (call "_captured.requireValue" []) | nativeGenerators]
          strategy = if null predicates then captured else chain captured [("suchThat",
            [closure inputName (statements
              ([text "if (_captured.error() != null) return true;" | nativeGenerators] ++
               unpack ++ [bindingsDoc,returned (conjunction (map (truth . expr) predicates))]))])]
          callback = closure inputName (statements (unpack ++ [bindingsDoc,check,returned (text "true")]))
      -- Keep JetCheck's native tree shrinking and its growing list budget.
      let invocation count size = statement $ chain (text "PropertyChecker.customized()")
            [("withIterationCount",[number count]),
             ("withSizeHint",[lambda "_iteration" size]),
             ("forAll",[strategy,callback])]
          growing iteration = text "(int) " <> call "Math.min"
            [text "java.lang.Integer.MAX_VALUE",text ("2L * " ++ iteration ++ " + 8")]
          body | nativeGenerators || constructorContracts =
            text ("for (int _case = 0; _case < " ++ show (cases (generation e)) ++ "; _case++) ") <>
              block (statements [bind "_sizeHint" (growing "_case"),invocation (1 :: Int) (text "_sizeHint")])
            | otherwise = invocation (cases (generation e)) (growing "_iteration")
      pure $ testFunction (fn ++ "Property") body
    contextualStrategy settings plan = do
      let input = domainInput plan
          ty = inputType input
      seeds <- mapM literal (generatorBoundaries plan)
      let hints = [expr hint | hint <- generatorHints plan, expressionType hint == ty,
            case C.expressionNode hint of
              C.Constant _ -> True
              C.Local _ -> True
              _ -> False]
          strategy = case requiredSymbol plan of
            value:_ -> call "Generator.constant" [expr value]
            [] | Just indexed <- generatorIndex plan ->
              -- The target is evaluated from inputs drawn earlier in this environment.
              call "lawspec.testing.LawSpecDataStrategies.indexedGenerator"
                [text "_schema",reference ty,number machineBits,number nodeBudget,
                 expr (indexedTarget indexed),equationsDoc (indexedEquations indexed),
                 text (className ++ "LawSpecTest::_lawspecScalarGenerator")]
            [] | nativeGenerators || constructorContracts -> chain
              (call "lawspec.testing.LawSpecDataStrategies.checkedGenerator"
                ([text "_schema",reference ty,number machineBits,number nodeBudget,number (maxAttempts settings),
                 text "symbols",call "java.util.List.of" (seeds ++ hints),
                 text (className ++ "LawSpecTest::_lawspecScalarGenerator")] ++
                [call "lawspec.testing.LawSpecNativeGenerators.factories" [] | nativeGenerators]))
              [("map",[D.group (text "lawspec.testing.LawSpecDataStrategies.Checked" <> D.nest 4 (D.softbreak <> text "::requireValue"))])]
            [] -> generator ty
      pure (inputId input,strategy)
    equationsDoc equations = call "java.util.Map.ofEntries"
      [call "java.util.Map.entry" [quoted (C.idText tag), call "java.util.List.of" (map quoted texts)]
      | (tag,texts) <- equations]
    requiredSymbol plan
      | nativeGenerators = []
      | inputType (domainInput plan) /= C.scalarType "Symbol" = []
      | otherwise = concatMap required (generatorPredicates plan)
      where
        current = C.binderId (generatorBinder plan)
        required term = case C.expressionNode term of
          C.ShortCircuit C.And a b -> required a ++ required b
          C.Binary C.Equal _ a b -> [value | (local,value) <- [(a,b),(b,a)],
            C.expressionNode local == C.Local current,
            expressionType value == C.scalarType "Symbol",
            current `notElem` C.freeBinders value,
            case C.expressionNode value of
              C.Constant _ -> True
              C.Local _ -> True
              _ -> False]
          _ -> []
    conjuncts term = case C.expressionNode term of
      C.ShortCircuit C.And left right -> conjuncts left ++ conjuncts right
      _ -> [term]
    -- Mapping the framework's native list tree preserves its shrink history.
    -- Every already-valid list is a fixed point; empty element domains still
    -- have the empty-list witness. Keep the final predicate check for any
    -- constraints that relate the entire list to other values.
    prepareElements identity predicates original = foldl prepare original
      [(binder,predicate) | term <- predicates,
        C.AllElements value binder predicate <- [C.expressionNode term],
        C.Local name <- [C.expressionNode value], name == identity]
      where
        prepare value (binder,predicate) =
          let name = localName (C.binderId binder)
              prepared = prepareElements (C.binderId binder) (conjuncts predicate) (text name)
          in runtime "refineElements" [value,lambda name prepared,lambda name (expr predicate)]
    domain e (index,plan) = do
      seeds <- mapM literal (generatorBoundaries plan)
      let inp = domainInput plan
          prior = take index (inputs e)
          bounds = array "LawSpecRuntime.Bound"
            [call "new LawSpecRuntime.Bound" [quoted op,expr v] | (op,v) <- domainBounds plan]
          candidates = runtime "domainCandidates" [quoted (typeKey (inputType inp)),text "_seed",number machineBits,
            bounds,E.array (seeds ++ map expr (generatorHints plan))]
          seedFn = closure "(_values, _seed)" (statements ([fromValues prior | not (null prior)] ++ [returned candidates]))
          predicate = closure "_values" (statements
            [fromValues (prior ++ [inp]),returned (conjunction (map (truth . expr) (inputRefinements inp)))])
      pure (call "new LawSpecRuntime.Domain" [seedFn,predicate])
    refinedProperty fn label e check = do
      domains <- mapM (domain e) (zip [0::Int ..] (generationPlan e))
      let cfg = generation e
          callback = closure "_values" (statements [fromValues (inputs e),check])
          invocation = runtime "refinedCase" [array "LawSpecRuntime.Domain" domains,
            text "seed",number (maxAttempts cfg),number (maxShrinks cfg),callback,
            quoted (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ testFunction (fn ++ "Property") $ statement $ chain (text "PropertyChecker.customized()")
        [("withIterationCount",[number (cases cfg)]),
         ("forAll",[text "Generator.integers()",closure "seed" (statements [symbols,statement invocation,returned (text "true")])])]
    array name values = D.group (text ("new " ++ name ++ "[] {") <>
      D.nest 2 (D.softbreak <> D.commaSep values) <> D.softbreak <> text "}")
