-- Kotlin test documents consume checked propositions and native generation plans.
module LawSpec.KotlinProperties (Config(..), emitTests) where

import LawSpec.Bounds (inputRange)
import qualified LawSpec.Core as C
import Control.Monad (foldM)
import LawSpec.Backend
import LawSpec.Common
import LawSpec.Testing
import qualified LawSpec.Core.Value as V
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.KotlinExpr as E
import qualified LawSpec.KotlinTestHelpers as Helpers
import Data.List (intercalate, sort)

data Config = Config
  { packageName :: String
  -- An async adapter's call, awaited.
  , awaitResult :: String -> D.Doc -> D.Doc
  , className :: String
  , constructorContracts :: Bool
  , nativeGenerators :: Bool
  , nodeBudget :: Integer
  , machineBits :: Int
  , expression :: Expr -> D.Doc
  , literal :: V.Value -> Either [Diagnostic] D.Doc
  , checked :: Type -> D.Doc -> D.Doc
  , structural :: Type -> Bool
  , reference :: Type -> D.Doc
  , typeKey :: Type -> String
  , generator :: Type -> D.Doc
  -- A generator drawing a top-level integer from a refinement's range.
  , generatorWithin :: Maybe (Integer, Integer) -> Type -> D.Doc
  , nativeArgument :: Type -> D.Doc -> D.Doc
  , nativeResult :: Type -> D.Doc -> D.Doc
  -- The statements that install a law's handlers in symbols, for each case.
  , handlerInstalls :: Expanded -> [D.Doc]
  }

text = D.text
statements = D.joinWith D.hardline
separate = D.joinWith (D.hardline <> D.hardline)
block = D.block 4
call = E.call
quoted = E.quoted
number :: Show a => a -> D.Doc
number = text . show
bind name value = D.group (text ("val " ++ name ++ " =") <> D.nest 4 (D.softline <> value))
closure parameters body = D.multiline (text "{" <>
  (if null parameters then mempty else text (" " ++ parameters ++ " ->")) <>
  D.nest 4 (D.hardline <> body) <> D.hardline <> text "}")
trailing invocation parameters body = invocation <> text " " <> closure parameters body
runtime name = call ("LawSpecRuntime." ++ name)
truth value = runtime "truth" [value]
conjunction [] = text "true"
conjunction xs = D.group (D.joinWith (text " &&" <> D.softline) xs)
symbols = text "val symbols = mutableMapOf<String, Any>()"
testFunction name body = quoted name <> text " " <> block body
fromValues xs = statements [bind (inputId input) (text ("_values[" ++ show index ++ "]")) |
  (index,input) <- zip [0::Int ..] xs]

emitTests :: Config -> Unit -> [Expanded] -> Either [Diagnostic] D.Doc
emitTests Config{..} unit laws = do
  bodies <- mapM law (zip [0::Int ..] laws)
  let imports = sort $ ["io.kotest.core.spec.style.StringSpec", "io.kotest.property.checkAll",
        "io.kotest.property.Arb", "io.kotest.property.PropTestConfig", "lawspec.runtime.LawSpecRuntime", "lawspec.runtime.LawSpecSchema",
        "lawspec.runtime.LawSpecDataSchema", "lawspec.runtime.LawSpecDataCodecs",
        "lawspec.runtime.LawSpecKotlinCodecs", "lawspec.testing.LawSpecKotlinStrategies",
        "lawspec.testing.lawspecFlatMap", "lawspec.testing.lawspecList", "lawspec.testing.lawspecChoice"] ++
        map ("io.kotest.property.arbitrary." ++) ["int","boolean","float","double","map","bind","filter","constant","element"]
  pure $ text "// Generated by LawSpec." <> D.hardline <>
    (if null packageName then mempty else text ("package " ++ packageName) <> D.hardline <> D.hardline) <>
    statements [text ("import " ++ name) | name <- imports] <> D.hardline <> D.hardline <>
    separate ([seedDoc, Helpers.assertionDoc, Helpers.dataHelpersDoc machineBits generator] ++
      map contract (contracts unit)) <> D.hardline <> D.hardline <>
    text ("class " ++ className ++ "LawSpecTest : StringSpec(") <>
    -- Workflows wait on a virtual clock under test.
    block (separate (text "lawspec.runtime.LawSpecRuntime.useVirtualClock(0)" : bodies)) <> text ")" <> D.hardline
  where
    -- LAWSPEC_SEED fixes Kotest's seed, so a run can be repeated exactly
    -- (lawspec test records the seed of every passing run).
    seedDoc = text "@OptIn(io.kotest.common.ExperimentalKotest::class)" <> D.hardline <>
      text "private fun _lawspecConfig(iterations: Int): PropTestConfig =" <> D.nest 4 (D.hardline <>
      text "PropTestConfig(seed = System.getenv(\"LAWSPEC_SEED\")?.toLong(), iterations = iterations)")
    expr = expression
    assertionDoc context proposition = case proposition of
      AssertAll ps -> statements (map (assertionDoc context) ps)
      AssertImplies guard body -> text "if (" <> truth (expr guard) <> text ") " <>
        block (assertionDoc context body)
      AssertEqual a b ->
        let message = quoted (context ++ " | expect " ++ prettyExpr a ++ " = " ++ prettyExpr b)
            isData = structural (expressionType a)
        in call (if isData then "_lawspecDataAssert" else "_lawspecAssert")
          ([message] ++ (if isData then [reference (expressionType a),text "symbols"] else []) ++
          [closure "" (expr a),closure "" (expr b)])
    contract c =
      let args = contractArguments c
          (rn,rt) = contractResult c
          params = text "symbols: MutableMap<String, Any>" : [text (n ++ ": LawSpecRuntime.Value") | (n,_) <- args]
          context stage ps = quoted (contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps))
          require stage ps = runtime "requireContract" [conjunction (map (truth . expr) ps),context stage ps]
          invocation = awaitResult (adapterName unit (C.contractDeclaration c)) (call (className ++ "." ++ adapterName unit (C.contractDeclaration c)) [nativeArgument ty (text n) | (n,ty) <- args])
      in call ("private fun _lawspec_call_" ++ contractName c) params <> text ": LawSpecRuntime.Value " <>
        block (statements [require "precondition" (contractPreconditions c),
          bind rn (nativeResult rt invocation),require "postcondition" (contractPostconditions c),text "return " <> text rn])
    -- A law's resources: each case acquires them, then runs, then releases
    -- them, the last first, even when the case fails.
    bracketed e docs = foldr wrap (statements docs) (C.propertyResources (original e))
      where
        wrap r inner =
          let local = localName (C.binderId (C.resourceBinder r))
          in statements [bind local (expr (C.resourceAcquire r)),
            text "try " <> block inner <> text " finally " <> block (expr (C.resourceRelease r))]
    law (index,e) = do
      let label = owner e ++ "::" ++ name e
          fn = "law" ++ show index
      exampleDocs <- mapM (\(i,ex) -> pure $ testFunction (fn ++ "Example" ++ show i) $ statements
        ([symbols] ++ handlerInstalls e ++ [bind n (expr v) | (n,v) <- bindings ex] ++
        [bracketed e (map (assertionDoc (label ++ " example " ++ exampleName ex)) (expectations ex) ++
          [assertionDoc label (assertion e)])])) (zip [0::Int ..] (examples (original e)))
      boundaryDocs <- mapM (\(i,vs) -> do
        values <- mapM literal vs
        pure $ testFunction (fn ++ "Boundary" ++ show i) $ statements
          ([symbols] ++ handlerInstalls e ++ [bind (inputId inp) (checked (inputType inp) v) | (inp,v) <- zip (inputs e) values] ++
          [bracketed e [assertionDoc (label ++ " boundary " ++ show i) (assertion e)]]))
        (zip [0::Int ..] (maybe (boundaryCases e) id (finiteCases e)))
      let check = bracketed e [assertionDoc (label ++ " property") (assertion e)]
      property <- if finiteCases e /= Nothing then pure []
        else if constructorContracts || nativeGenerators || any (maybe False (const True) . generatorIndex) (generationPlan e)
          then (:[]) <$> contextualProperty fn label e check
        else if any (structural . inputType) (inputs e) then pure [nativeProperty fn label e check]
        else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract"
          then (:[]) <$> refinedProperty fn label e check
          else pure [nativeProperty fn label e check]
      pure $ metadataDocument 96 "//" e <> separate (exampleDocs ++ boundaryDocs ++ property)
    contextualProperty fn label e check = do
      let bindings xs = statements [text "val symbols = _inputs.symbols",
            text "val _values = _inputs.values",fromValues xs]
          state value = call "LawSpecKotlinStrategies.Case"
            [value,text "symbols",text "_checked.error"]
          step prior (index,plan) = do
            let input = domainInput plan
                ty = inputType input
            seeds <- mapM literal (generatorBoundaries plan)
            let hints = [expr hint | hint <- generatorHints plan, expressionType hint == ty,
                  case C.expressionNode hint of
                    C.Constant _ -> True
                    C.Local _ -> True
                    _ -> False]
                strategy = case (if nativeGenerators then [] else requiredSymbol plan) of
                  value:_ -> call "Arb.constant" [call "LawSpecKotlinStrategies.Checked" [expr value,text "null"]]
                  -- The target is evaluated from the inputs bound above.
                  [] | Just indexed <- generatorIndex plan -> call "LawSpecKotlinStrategies.indexedGenerator"
                    [text "_schema",reference ty,number machineBits,number nodeBudget,text "symbols",
                     expr (indexedTarget indexed),
                     call "mapOf" [quoted (C.idText tag) <> text " to " <> call "listOf" (map quoted texts)
                       | (tag,texts) <- indexedEquations indexed],
                     text "::_lawspecScalarGenerator"]
                  [] -> call "LawSpecKotlinStrategies.checkedGenerator" $
                    [text "_schema",reference ty,number machineBits,number nodeBudget,
                     number (maxAttempts (generation e)),text "symbols",call "listOf" (seeds ++ hints)] ++
                    [text "lawspec.testing.LawSpecNativeGenerators.factories()" | nativeGenerators] ++
                    [text "::_lawspecScalarGenerator"]
                added = trailing (strategy <> text ".map") "_checked"
                  (text "if (_checked.error != null) " <> block (state (text "_values")) <>
                   text " else " <> block (state (text "_values + _checked.requireValue()")))
            pure $ trailing (call "lawspecFlatMap" [prior]) "_inputs"
              (text "if (_inputs.error != null) " <> block (text "Arb.constant(_inputs)") <>
               text " else " <> block (statements [bindings (take index (inputs e)),added]))
      base <- foldM step (text "LawSpecKotlinStrategies.cases()") (zip [0::Int ..] (generationPlan e))
      let predicates = concatMap inputRefinements (inputs e)
          strategy = if null predicates then base else trailing
            (call "LawSpecKotlinStrategies.filterCases" [base,number (maxAttempts (generation e))]) "_inputs"
            (statements [bindings (inputs e),conjunction (map (truth . expr) predicates)])
          body = statements ([text "val symbols = _inputs.symbols",
            text "val _values = _inputs.requireValues()",fromValues (inputs e)] ++ handlerInstalls e ++ [check])
      pure $ testFunction (fn ++ "Property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases (generation e))],strategy]) "_inputs" body
    requiredSymbol plan
      | inputType (domainInput plan) /= C.scalarType "Symbol" = []
      | otherwise = concatMap required (generatorPredicates plan)
      where
        current = C.binderId (generatorBinder plan)
        required term = case C.expressionNode term of
          C.ShortCircuit C.And a b -> required a ++ required b
          C.Binary C.Equal _ a b -> [value | (local,value) <- [(a,b),(b,a)],
            C.expressionNode local == C.Local current,
            expressionType value == C.scalarType "Symbol",
            current `notElem` C.freeBinders value,
            case C.expressionNode value of
              C.Constant _ -> True
              C.Local _ -> True
              _ -> False]
          _ -> []
    nativeProperty fn label e check =
      let tuple = foldl (\prior inp -> trailing (call "Arb.bind" [prior,generatorWithin (inputRange machineBits inp) (inputType inp)])
            "_values, _value" (text "_values + _value"))
            (text "Arb.constant(emptyList<LawSpecRuntime.Value>())") (inputs e)
          base = trailing (tuple <> text ".map") "_values"
            (text "Pair(_values, mutableMapOf<String, Any>())")
          predicates = concatMap inputRefinements (inputs e)
          bindingsDoc = statements [text "val symbols = _inputs.second",
            text "val _values = _inputs.first",fromValues (inputs e)]
          strategy = if null predicates then base else trailing (base <> text ".filter") "_inputs"
            (statements [bindingsDoc,conjunction (map (truth . expr) predicates)])
      in testFunction (fn ++ "Property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases (generation e))],strategy]) "_inputs"
        (statements ([bindingsDoc] ++ handlerInstalls e ++ [check]))
    domain e (index,plan) = do
      seeds <- mapM literal (generatorBoundaries plan)
      let inp = domainInput plan
          prior = take index (inputs e)
          bounds = E.array [call "LawSpecRuntime.Bound" [quoted op,expr v] | (op,v) <- domainBounds plan]
          candidates = runtime "domainCandidates" [quoted (typeKey (inputType inp)),text "_seed",number machineBits,
            bounds,E.array (seeds ++ map expr (generatorHints plan))]
          seedFn = closure "_values, _seed" (statements ([fromValues prior | not (null prior)] ++ [candidates]))
          predicate = closure "_values" (statements
            [fromValues (prior ++ [inp]),conjunction (map (truth . expr) (inputRefinements inp))])
      pure (call "LawSpecRuntime.Domain" [seedFn,predicate])
    refinedProperty fn label e check = do
      domains <- mapM (domain e) (zip [0::Int ..] (generationPlan e))
      let cfg = generation e
          callback = closure "_values" (statements ([fromValues (inputs e)] ++ handlerInstalls e ++ [check]))
          invocation = runtime "refinedCase" [E.array domains,
            text "seed",number (maxAttempts cfg),number (maxShrinks cfg),callback,
            quoted (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ testFunction (fn ++ "Property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases cfg)],text "Arb.int()"]) "seed" (statements [symbols,invocation])
