-- Application bindings reuse the Kotlin schema codecs and canonical adapter ABI.
module LawSpec.KotlinNativeBinding (emitBindings) where

import Control.Monad (forM, unless)
import Data.Char (toUpper, toLower)
import Data.List (intercalate, nub, isPrefixOf, find)
import qualified LawSpec.Core as C
import LawSpec.Common
import LawSpec.Backend (unitName, inputs, inputType)
import qualified LawSpec.CoreNativeScalarEmit as Scalar
import qualified LawSpec.JavaDefinitions as Definitions
import LawSpec.Testing
import LawSpec.NativeBinding
import LawSpec.NativeRequest
import qualified LawSpec.KotlinData as K
import qualified LawSpec.KotlinExpr as E
import qualified LawSpec.Code.Doc as D
import LawSpec.RuntimeSources (runtimeSource)

emitBindings :: Bool -> BindingPlan -> Plan -> [Artifact] -> Either String [Artifact]
emitBindings minify plan testing files = do
  unless (bindingRustCrate plan == Nothing) (Left "rustCrate is only valid for Rust bindings")
  unless (null mappings || not (null (bindingFunctions plan)) || not (null (bindingCalls plan)) || not (null generators))
    (Left "native types require function bindings")
  mapM_ K.identifier [name | (_,MethodCall name) <- bindingCalls plan]
  mapM_ (mapM_ K.identifier . referenceParts) ([r | (_,r) <- bindingFunctions plan] ++
    [r | (_,ConstructorCall r) <- bindingCalls plan] ++
    [resolvedNativeType m | m <- mappings] ++ [resolvedNativeConstructor c | m <- mappings,c <- resolvedConstructors m] ++
    [ref | m <- mappings, Just hook <- [resolvedCodec m], ref <- [codecToNative hook, codecFromNative hook]])
  mapM_ (K.identifier . snd) [f | m <- mappings,c <- resolvedConstructors m,f <- resolvedFields c]
  codecs <- K.emitKotlinNativeCodecs layout declarations mappings
  -- Method and constructor bindings call through Java, which can name a
  -- generic native class raw: one static method each, taking and returning
  -- Object.
  -- An async method is a suspend function, which Kotlin calls itself.
  let javaCalls = [c | c@(d,nativeCall) <- bindingCalls plan,
        not (C.declarationAsync d && case nativeCall of MethodCall _ -> True; _ -> False)]
  calls <- forM (zip [0::Int ..] javaCalls) $ \(index,(d,nativeCall)) -> do
    let (args,_) = C.functionType (C.declarationType d)
    casts <- mapM javaCast args
    let parameters = ["java.lang.Object value" ++ show i | i <- [0 .. length args - 1]]
        cast i = maybe ("value" ++ show i) (\t -> "((" ++ t ++ ") value" ++ show i ++ ")") (casts !! i)
        handleArgument = lookup True [(isHandle t,i) | (i,t) <- zip [0::Int ..] args]
    expression <- case nativeCall of
      MethodCall name -> case handleArgument of
        Just i -> pure (cast i ++ "." ++ name ++ "(" ++ intercalate ", " [cast j | j <- [0 .. length args - 1], j /= i] ++ ")")
        Nothing -> Left ("method binding without a handle argument: " ++ C.idText (C.declarationId d))
      ConstructorCall r -> pure ("new " ++ intercalate "." (referenceParts r) ++ "(" ++
        intercalate ", " [cast i | (i,t) <- zip [0..] args, t /= C.scalarType "Unit"] ++ ")")
      StaticCall _ -> Left "static binding among method bindings"
    let body = case nativeCall of
          MethodCall _ | snd (C.functionType (C.declarationType d)) == C.scalarType "Unit" ->
            [expression ++ ";", "return null;"]
          _ -> ["return " ++ expression ++ ";"]
    pure (C.declarationId d, "call" ++ show index,
      "  public static java.lang.Object call" ++ show index ++ "(" ++ intercalate ", " parameters ++ ") {\n" ++
      concatMap (\line -> "    " ++ line ++ "\n") body ++ "  }\n")
  let callSupport = [Artifact "src/main/java/lawspec/runtime/LawSpecNativeCalls.java"
        ("// Generated by LawSpec. Do not edit.\npackage lawspec.runtime;\n\n" ++
         "@SuppressWarnings({\"rawtypes\", \"unchecked\"})\npublic final class LawSpecNativeCalls {\n" ++
         "  private LawSpecNativeCalls() {}\n" ++ concatMap (\(_,_,source) -> "\n" ++ source) calls ++ "}\n")
        "generated" "source" | not (null calls)]
  bridges <- fmap concat $ forM (plannedUnits testing) $ \p -> do
    let unit = plannedUnit p
        definitions = map (C.declarationId . C.definitionDeclaration) (C.unitDefinitions unit)
        adapters = [d | d <- C.unitDeclarations unit,C.declarationId d `notElem` definitions]
        bound d = lookup (C.declarationId d) ([(C.declarationId a,StaticCall r) | (a,r) <- bindingFunctions plan] ++
          [(C.declarationId a,c) | (a,c) <- bindingCalls plan])
        parts = split '.' (unitName unit)
    mapM_ K.identifier parts
    if not (any (maybe False (const True) . bound) adapters) then pure [] else do
      unless (all (maybe False (const True) . bound) adapters) (Left "a Kotlin bound unit must map every adapter")
      bodies <- forM adapters $ \d -> do
        let (args,result) = C.functionType (C.declarationType d)
            Just ref = bound d
        argTypes <- mapM (K.kotlinDataTypeDoc declarations) args
        resultType <- K.kotlinDataTypeDoc declarations result
        canonical <- mapM (K.kotlinCodecDocWithContext (D.text "symbols") declarations) args
        native <- mapM (K.kotlinNativeCodecDoc declarations) args
        canonicalResult <- K.kotlinCodecDocWithContext (D.text "symbols") declarations result
        nativeResult <- K.kotlinNativeCodecDoc declarations result
        nativeResultType <- K.kotlinNativeTypeDoc declarations mappings [] result
        let values = [D.text ("value" ++ show i) | i <- [0::Int ..length args-1]]
            converted = [method n "decode" [method c "encode" [v]] | (n,c,v) <- zip3 native canonical values]
            returned = method canonicalResult "decode" [method nativeResult "encode" [D.text "result"]]
        maybeElement <- case result of
          C.Constructor "Maybe" [C.TypeArgument element] -> Just <$> K.kotlinNativeTypeDoc declarations mappings [] element
          _ -> pure Nothing
        resultBody <- case ref of
          StaticCall r -> do
            let application = E.call (intercalate "." (referenceParts r)) converted
            pure $ if result == C.scalarType "Unit" then application <> D.hardline <> D.text "Unit" else
              D.text "val result = " <> application <> D.hardline <> returned
          _ -> do
            application <- case ref of
              MethodCall name | C.declarationAsync d -> case lookup True [(isHandle t,i) | (i,t) <- zip [0::Int ..] args] of
                Just i -> do
                  receiver <- javaCast (args !! i) >>= maybe (Left ("an async method binding needs a bound handle type: " ++
                    C.idText (C.declarationId d))) Right
                  pure (D.text "(" <> converted !! i <> D.text " as " <> D.text receiver <> D.text ")" <>
                    E.call ("." ++ name) [v | (j,v) <- zip [0..] converted, j /= i])
                Nothing -> Left ("method binding without a handle argument: " ++ C.idText (C.declarationId d))
              _ -> do
                helper <- maybe (Left "unplanned native call") Right
                  (lookup (C.declarationId d) [(identity,name) | (identity,name,_) <- calls])
                pure (E.call ("lawspec.runtime.LawSpecNativeCalls." ++ helper) converted)
            pure $ if result == C.scalarType "Unit" then application <> D.hardline <> D.text "Unit"
              -- A method's null is Nothing; anything else is Just.
              else case maybeElement of
                Just element -> D.text "val found: Any? = " <> application <> D.hardline <>
                  D.text "val result: " <> nativeResultType <> D.text " = if (found == null) LawSpecRuntime.Nothing() else " <>
                    D.text "LawSpecRuntime.Just(found as " <> element <> D.text ")" <> D.hardline <> returned
                Nothing -> D.text "val result = " <> application <> D.text " as " <> nativeResultType <> D.hardline <> returned
        -- An async adapter's bridge suspends on its native call; a constructor completes at once.
        pure (D.text (if C.declarationAsync d then "suspend fun " else "fun ") <> E.call (C.declarationName d) [v <> D.text ": " <> t | (t,v) <- zip argTypes values] <>
          D.text ": " <> resultType <> D.text " " <> D.block 4
          (D.text "val symbols = mutableMapOf<String, Any>()" <> D.hardline <>
           D.text "return try " <> D.block 4 resultBody <> D.text " catch (error: RuntimeException) " <>
           D.block 4 (D.text "throw " <> E.call "IllegalArgumentException"
             [E.quoted ("native binding " ++ C.idText (C.declarationId d) ++ ": ") <> D.text " + error.message",D.text "error"])))
      let name = concatMap cap (split '_' (last parts))
          package = intercalate "." (init parts)
          path = "src/main/kotlin/" ++ concatMap (++ "/") (init parts) ++ name ++ ".kt"
          header = (if null package then mempty else D.text ("package " ++ package) <> D.hardline <> D.hardline) <>
            D.text "import lawspec.runtime.*" <> D.hardline <> D.hardline
          source = header <> D.text ("object " ++ name ++ " ") <> D.block 4
            (D.text "private val schema = LawSpecDataSchema.create()" <> D.hardline <>
             D.text ("private val bits = " ++ show bits) <> D.hardline <> D.hardline <>
             D.joinWith (D.hardline <> D.hardline) bodies)
      pure [Artifact path (render source) "generated" "source"]
  dataFiles <- if any ((== "src/main/java/lawspec/runtime/LawSpecDataSchema.java") . artifactPath) files then pure []
    else K.emitKotlinDataWithProfile bits layout declarations
  generatorFiles <- if null generators then pure [] else do
    let roots = [inputType input | unit <- plannedUnits testing, property <- plannedProperties unit, input <- inputs property]
    concrete <- if any ((>0) . generatorParameterCount) generators
      then reachableGeneratorTypes declarations representations roots else pure []
    methods <- forM (zip [0::Int ..] generators) $ \(index,generator) -> do
      mapM_ K.identifier (referenceParts (resolvedGeneratorFactory generator))
      let family = C.idText (resolvedGeneratorType generator)
          instances = if generatorParameterCount generator == 0 then [C.Constructor family []]
            else [ty | ty@(C.Constructor name _) <- concrete, name == family]
      branches <- forM instances $ \ty -> do
        let args = case ty of C.Constructor _ args -> [t | C.TypeArgument t <- args]; _ -> []
        children <- forM (zip [0::Int ..] args) $ \(i,child) -> do
          bridge <- K.kotlinNativeCodecDoc declarations child
          pure (D.text ("val child" ++ show i ++ " = ") <>
            E.call "LawSpecKotlinStrategies.nativeArguments" [bridge,D.text ("arguments[" ++ show i ++ "]")])
        bridge <- K.kotlinNativeCodecDoc declarations ty
        tyRef <- E.reference ty
        pure (D.text "if (type == " <> tyRef <> D.text ") " <> D.block 4
          (D.joinWith D.hardline (children ++
            [D.text "val source = " <> E.call (intercalate "." (referenceParts (resolvedGeneratorFactory generator)))
              [D.text ("child" ++ show i) | i <- [0..length args-1]],
             D.text "return " <> E.call "LawSpecKotlinStrategies.nativeValues" [bridge,D.text "source"]])))
      pure (D.text "private fun " <> E.call ("factory" ++ show index) (map D.text
        ["schema: LawSpecSchema", "type: LawSpecSchema.Named", "bits: Int", "symbols: MutableMap<String, Any>",
         "arguments: List<Arb<LawSpecRuntime.Value>>"]) <>
        D.text ": Arb<LawSpecRuntime.Value> " <> D.block 4 (D.joinWith D.hardline (branches ++
          [D.text "throw IllegalArgumentException(\"unplanned native generator instantiation: \" + type)"])))
    let entries = [E.quoted (C.idText (resolvedGeneratorType generator)) <>
          D.text " to " <> E.call "LawSpecKotlinStrategies.NativeFactory" [D.text ("::factory" ++ show i)] |
            (i,generator) <- zip [0::Int ..] generators]
        registry = D.text "fun factories(): Map<String, LawSpecKotlinStrategies.NativeFactory> = " <>
          E.call "mapOf" entries
        helper = Artifact "src/test/kotlin/lawspec/testing/LawSpecNativeGenerators.kt" (render
          (D.text "package lawspec.testing" <> D.hardline <> D.hardline <>
           D.text "import io.kotest.property.Arb" <> D.hardline <>
           D.text "import lawspec.runtime.*" <> D.hardline <> D.hardline <>
           D.text "object LawSpecNativeGenerators " <> D.block 4
            (D.joinWith (D.hardline <> D.hardline) (registry:methods)))) "generated" "test"
    emitted <- either (Left . show) Right $ concat <$> mapM (\unit ->
      Scalar.nativeScalarEmitWithNativeGenerators True minify declarations
        (Definitions.definitionCalls (map plannedUnit (plannedUnits testing))) bits "kotlin"
        (plannedUnit unit) (plannedProperties unit))
        [unit | unit <- plannedUnits testing, not (null (plannedProperties unit))]
    pure (helper : [file | file <- emitted,artifactPlacement file == "test"] ++
      [Artifact path (runtimeSource key) "generated" "test" |
        (path,key) <- [("src/test/kotlin/lawspec/testing/LawSpecKotlinStrategies.kt","kotlin-data-strategies"),
          ("src/test/kotlin/lawspec/testing/LawSpecStrategies.kt","kotlin-strategies")],
        not (any ((== path) . artifactPath) files)])
  let support = Artifact "src/main/kotlin/lawspec/runtime/LawSpecNativeCodecs.kt" codecs "generated" "source"
      runtime = [Artifact "src/main/java/lawspec/runtime/LawSpecRuntime.java" (runtimeSource "java") "generated" "source" |
        not (any ((== "src/main/java/lawspec/runtime/LawSpecRuntime.java") . artifactPath) files)]
  unless (all ((/= artifactPath support) . artifactPath) files) (Left "unit shadows native codec support")
  let generated = [f | f <- files,artifactPath f `notElem` map artifactPath (bridges ++ generatorFiles)] ++ dataFiles ++ runtime ++ [support] ++ callSupport ++ bridges ++ generatorFiles
  stubs <- generatorStubs generated
  pure (generated ++ stubs)
  where
    declarations = planDataDeclarations testing
    bits = planMachineBits testing
    representations = bindingRepresentations plan
    mappings = resolvedTypes representations
    generators = resolvedGenerators representations
    layout = D.selectLayout minify (D.Pretty 100)
    render doc = D.render layout (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <> doc <> D.hardline)
    split c s = case break (==c) s of (a,[]) -> [a]; (a,_:b) -> a:split c b
    cap [] = []; cap (a:rest) = toUpper a:rest
    method value name args = value <> D.text "." <> E.call name args
    handleDeclaration name = find (\d -> C.dataHandle d && C.dataId d == C.Id name) declarations
    isHandle (C.Constructor name []) = handleDeclaration name /= Nothing
    isHandle _ = False
    -- The Java class a native argument is cast to before the call: a handle's
    -- bound class, or the erasure of the argument's Kotlin type; none for an
    -- unbound handle and Kotlin-only types.
    javaCast ty = case ty of
      C.Constructor name [] | Just d <- handleDeclaration name ->
        pure (intercalate "." . referenceParts . resolvedNativeType <$>
          find ((== C.dataId d) . C.dataId . resolvedDeclaration) mappings)
      _ -> do
        native <- K.kotlinNativeTypeDoc declarations mappings [] ty
        let erased = takeWhile (/= '<') (D.render D.Compact native)
        pure $ case lookup erased kotlinClasses of
          Just java -> Just java
          Nothing | "kotlin." `isPrefixOf` erased -> Nothing
                  | otherwise -> Just erased
    kotlinClasses =
      [("kotlin.Boolean","java.lang.Boolean"),("kotlin.Byte","java.lang.Byte"),("kotlin.Short","java.lang.Short"),
       ("kotlin.Int","java.lang.Integer"),("kotlin.Long","java.lang.Long"),("kotlin.Float","java.lang.Float"),
       ("kotlin.Double","java.lang.Double"),("kotlin.Char","java.lang.Character"),("kotlin.String","java.lang.String"),
       ("kotlin.ByteArray","byte[]"),("kotlin.IntArray","int[]"),("kotlin.collections.List","java.util.List"),
       ("kotlin.collections.Set","java.util.Set"),("kotlin.collections.Map","java.util.Map"),
       ("kotlin.collections.ArrayDeque","kotlin.collections.ArrayDeque")]

    generatorStubs generated = do
      let requested = filter resolvedGeneratorStub generators
          owner = init . referenceParts . resolvedGeneratorFactory
          owners = nub (map owner requested)
          classPath = intercalate "/"
          conflicts a b = map toLower a == map toLower b ||
            (a ++ "/") `isPrefixOf` b || (b ++ "/") `isPrefixOf` a
          existing = [take (length relative - suffix) relative | file <- generated,
            (prefix,suffix) <- [("src/main/kotlin/",3),("src/test/kotlin/",3),("src/main/java/",5)],
            prefix `isPrefixOf` artifactPath file, let relative = drop (length prefix) (artifactPath file)]
          application = [classPath (referenceParts ref) | ref <- map resolvedNativeType mappings ++
            map resolvedNativeConstructor (concatMap resolvedConstructors mappings)] ++
            [classPath (referenceParts r) | (_,ConstructorCall r) <- bindingCalls plan] ++
            [classPath (init parts) | ref <- map snd (bindingFunctions plan) ++
              [r | mapping <- mappings, Just hook <- [resolvedCodec mapping], r <- [codecToNative hook,codecFromNative hook]],
              let parts = referenceParts ref, length parts >= 3]
      forM owners $ \parts -> do
        unless (length parts >= 2) (Left "Kotlin generator scaffold requires a package, object and function")
        unless (head parts `notElem` ["kotlin","java"])
          (Left "Kotlin generator scaffold cannot use a reserved runtime package")
        let name = last parts
            path = classPath parts
        unless (not (any (conflicts path) ("io/kotest/property/Arb":existing ++ application)) &&
          not (any (\other -> other /= parts && conflicts path (classPath other)) owners))
          (Left "Kotlin generator scaffold object conflicts with another class or package")
        unless (name `notElem` (words "java kotlin io lawspec" ++
          [head ref | mapping <- mappings, let ref = referenceParts (resolvedNativeType mapping), not (null ref)]))
          (Left "Kotlin generator scaffold object shadows a signature package")
        bodies <- forM (filter ((== parts) . owner) requested) $ \generator -> do
          let methodName = last (referenceParts (resolvedGeneratorFactory generator))
              parameters = [(C.Id ("scaffold::" ++ show i),"T" ++ show i) | i <- [0 .. generatorParameterCount generator - 1]]
              ty = C.Constructor (C.idText (resolvedGeneratorType generator))
                [C.TypeArgument (C.TypeVariable identity) | (identity,_) <- parameters]
          unless (not (null parameters) || methodName `notElem` words "hashCode toString")
            (Left "Kotlin generator scaffold function conflicts with kotlin.Any")
          native <- K.kotlinNativeTypeDoc declarations mappings parameters ty
          let generic = if null parameters then mempty else D.text ("<" ++ intercalate ", " (map snd parameters) ++ "> ")
              arb value = D.group (D.text "io.kotest.property.Arb<" <> D.nest 4 (D.softbreak <> value) <> D.text ">")
              signature = D.text "fun " <> generic <> E.call methodName
                [D.text ("argument" ++ show i ++ ": ") <> arb (D.text name) | (i,(_,name)) <- zip [0::Int ..] parameters] <>
                D.text ": " <> arb native
          pure (signature <> D.text " " <> D.block 4 (D.text "throw " <>
            E.call "kotlin.NotImplementedError" [E.quoted ("Implement generator for " ++ C.idText (resolvedGeneratorType generator))]))
        pure (Artifact ("src/test/kotlin/" ++ path ++ ".kt") (D.render (D.Pretty 100)
          (D.text "// User-owned native generator factories. Implement before running properties." <> D.hardline <>
           D.text ("package " ++ intercalate "." (init parts)) <> D.hardline <> D.hardline <>
           D.text ("object " ++ name ++ " ") <> D.block 4 (D.joinWith (D.hardline <> D.hardline) bodies) <> D.hardline)) "user" "test")
