-- | Kotlin test documents consume checked propositions and native generation plans.
module LawSpec.KotlinProperties (Config(..), emitTests) where

import LawSpec.Bounds (inputRange)
import qualified LawSpec.Core as C
import Control.Monad (foldM)
import LawSpec.Backend
import LawSpec.Common
import LawSpec.TestNames (unitTestNames)
import LawSpec.Testing
import qualified LawSpec.Core.Value as V
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.KotlinExpr as E
import qualified LawSpec.KotlinTestHelpers as Helpers
import Data.List (intercalate, sort, stripPrefix)

-- | What the Kotlin test emitter needs besides the plan: names, layout and
-- bindings, gathered so the emitter takes one argument.
data Config = Config
  { packageName :: String
  -- An async adapter's call, awaited.
  , awaitResult :: String -> D.Doc -> D.Doc
  , className :: String
  , constructorContracts :: Bool
  , nativeGenerators :: Bool
  , nodeBudget :: Integer
  , machineBits :: Int
  , expression :: Expr -> D.Doc
  , literal :: V.Value -> Either [Diagnostic] D.Doc
  , checked :: Type -> D.Doc -> D.Doc
  , structural :: Type -> Bool
  , reference :: Type -> D.Doc
  , typeKey :: Type -> String
  , generator :: Type -> D.Doc
  -- A generator drawing a top-level integer from a refinement's range.
  , generatorWithin :: Maybe (Integer, Integer) -> Type -> D.Doc
  , nativeArgument :: Type -> D.Doc -> D.Doc
  , nativeResult :: Type -> D.Doc -> D.Doc
  -- The statements that install a law's handlers in symbols, for each case.
  , handlerInstalls :: Expanded -> [D.Doc]
  -- Each input's descriptor, for LawSpec's own search (LawSpec.Search):
  -- Nothing when the law takes no part in it.
  , searchDescriptors :: Expanded -> Maybe [String]
  }

text = D.text
statements = D.joinWith D.hardline
separate = D.joinWith (D.hardline <> D.hardline)
block = D.block 4
call = E.call
quoted = E.quoted
number :: Show a => a -> D.Doc
number = text . show
bind name value = D.group (text ("val " ++ name ++ " =") <> D.nest 4 (D.softline <> value))
closure parameters body = D.multiline (text "{" <>
  (if null parameters then mempty else text (" " ++ parameters ++ " ->")) <>
  D.nest 4 (D.hardline <> body) <> D.hardline <> text "}")
trailing invocation parameters body = invocation <> text " " <> closure parameters body
runtime name = call ("LawSpecRuntime." ++ name)
truth value = runtime "truth" [value]
conjunction [] = text "true"
conjunction xs = D.group (D.joinWith (text " &&" <> D.softline) xs)
symbols = text "val symbols = mutableMapOf<String, Any>()"
fromValues xs = statements [bind (inputId input) (text ("_values[" ++ show index ++ "]")) |
  (index,input) <- zip [0::Int ..] xs]

-- | Laws become tests in Kotlin's own property framework, so they run with the
-- tools the project already uses. ref:DEC-native-property-frameworks
emitTests :: Config -> Unit -> [Expanded] -> Either [Diagnostic] D.Doc
emitTests Config{..} unit laws = do
  let testNames = unitTestNames "kotlin" (map name laws)
  bodies <- mapM (law testNames) (zip [0::Int ..] laws)
  let imports = sort $ ["io.kotest.core.spec.style.StringSpec", "io.kotest.property.checkAll",
        "io.kotest.property.Arb", "io.kotest.property.PropTestConfig", "lawspec.runtime.LawSpecRuntime", "lawspec.runtime.LawSpecSchema",
        "lawspec.runtime.LawSpecDataSchema", "lawspec.runtime.LawSpecDataCodecs",
        "lawspec.runtime.LawSpecKotlinCodecs", "lawspec.testing.LawSpecKotlinStrategies",
        "lawspec.testing.lawspecFlatMap", "lawspec.testing.lawspecList", "lawspec.testing.lawspecChoice"] ++
        map ("io.kotest.property.arbitrary." ++) ["int","boolean","float","double","map","bind","filter","constant","element"]
  pure $ text "// Generated by LawSpec." <> D.hardline <>
    (if null packageName then mempty else text ("package " ++ packageName) <> D.hardline <> D.hardline) <>
    statements [text ("import " ++ name) | name <- imports] <> D.hardline <> D.hardline <>
    separate ([seedDoc, Helpers.assertionDoc, Helpers.dataHelpersDoc machineBits generator] ++
      map contract (contracts unit)) <> D.hardline <> D.hardline <>
    text ("class " ++ className ++ "LawSpecTest : StringSpec(") <>
    -- Workflows wait on a virtual clock under test, and workflows and
    -- mailboxes read the Clock handler a law installs.
    block (separate (statements (text "lawspec.runtime.LawSpecRuntime.useVirtualClock(0)" :
      [text "lawspec.Time.registerClock()" | installsClock unit]) :
      [call "lawspec.testing.LawSpecHarness.parallelism" [quoted unitLabel, quoted "coroutines on a thread per processor (Kotest concurrency)",
         text "Runtime.getRuntime().availableProcessors()"] | parallel] ++
      ordered (bodies ++ map benchmark (maybe [] C.harnessBenchmarks settings)))) <> text ")" <>
    -- parallel: Kotest runs the tests concurrently, on as many threads as
    -- processors.
    (if parallel then text " " <> block (statements
      ([text "override fun concurrency(): Int = Runtime.getRuntime().availableProcessors()" | parallel] ++
       [text "@Suppress(\"OVERRIDE_DEPRECATION\")" <> D.hardline <> text "override fun threads(): Int = Runtime.getRuntime().availableProcessors()" | parallel]))
     else mempty) <> D.hardline
  where
    -- The harness plane (LawSpec.Harness). A test the harness runs is a
    -- suspending function value (harness:name), which the generated test
    -- passes to the runtime shared with Java.
    settings = C.unitHarnessSettings unit
    orderRandom = maybe False C.harnessOrderRandom settings
    parallel = maybe False C.harnessParallel settings
    unitLabel = C.idText (C.unitId unit)
    -- order random: LawSpec registers the unit's tests in an order the
    -- run's seed chooses. A local String.invoke collects them, and they are
    -- registered, shuffled, after the block that declares them.
    testType = "suspend io.kotest.core.test.TestScope.() -> Unit"
    ordered docs
      | orderRandom =
          [ text ("val _lawspecTests = mutableListOf<Pair<String, " ++ testType ++ ">>()")
          , text "run " <> block (statements
              [text ("operator fun String.invoke(test: " ++ testType ++ ") { _lawspecTests.add(this to test) }"), separate docs])
          , text "for ((name, test) in lawspec.testing.LawSpecHarness.shuffled(" <> quoted unitLabel <> text ", _lawspecTests)) name(test)" ]
      | otherwise = docs
    testFunction name body = case stripPrefix "harness:" name of
      Just rest -> text ("val lawspecHarness" ++ takeWhile (/= ':') rest ++ ": suspend () -> Unit = ") <> closure "" body
      Nothing -> quoted name <> text " " <> block body
    runSettings h = C.harnessTimeout h /= Nothing || C.harnessRepeat h /= 1 || C.harnessRetries h /= 0 || observed h
    observed h = not (null (C.harnessCover h) && null (C.harnessClassify h) && null (C.harnessLabels h)) || C.harnessTarget h /= Nothing
    harness name' = call ("lawspec.testing.LawSpecHarness." ++ name')
    body name' = text "lawspec.testing.LawSpecHarness.Body { kotlinx.coroutines.runBlocking { " <> text name' <> text "() } }"
    observations e =
      let h = C.propertyHarness (original e)
          label = owner e ++ "::" ++ name e
      in [harness "observe" [quoted label,
            call "arrayOf<String>" [quoted l | C.Cover _ l _ <- C.harnessCover h], call "booleanArrayOf" [truth (expr w) | C.Cover _ _ w <- C.harnessCover h],
            call "arrayOf<String>" [quoted l | (_, l) <- C.harnessClassify h], call "booleanArrayOf" [truth (expr c) | (c, _) <- C.harnessClassify h],
            call "arrayOf<LawSpecRuntime.Value>" (map expr (C.harnessLabels h))] | observed h] ++
         [harness "target" [expr score, quoted label] | Just score <- [C.harnessTarget h]]
    -- The tests a law's harness wraps, skips or expects to fail.
    harnessTests fn label h kinds docs = case (C.harnessSkip h, C.harnessKnownFailing h) of
      (Just reason, _) -> [quoted (fn ++ "_skipped: " ++ label) <> text ".config(enabled = false) " <> block (text ("// " ++ reason))]
      (_, Just reason) -> docs ++ [quoted (fn ++ "_knownFailing: " ++ label) <> text " " <> block (harness "knownFailing"
        [quoted label, quoted (fn ++ "_knownFailing"), quoted reason, call "listOf" [body ("lawspecHarness" ++ fn ++ k) | k <- kinds]])]
      _ | runSettings h -> docs ++ [quoted (fn ++ k ++ (if k == "_property" then ": " ++ label else "")) <> text " " <> block (harness "run"
            [quoted label, quoted (fn ++ k), number (maybe 0 id (C.harnessTimeout h)), number (C.harnessRepeat h), number (C.harnessRetries h),
             call "intArrayOf" [number p | k == "_property", C.Cover p _ _ <- C.harnessCover h],
             call "arrayOf<String>" [quoted l | k == "_property", C.Cover _ l _ <- C.harnessCover h],
             text (if k == "_property" && observed h then "true" else "false"), body ("lawspecHarness" ++ fn ++ k)]) | k <- kinds]
        | otherwise -> docs
    benchmark (n, b) = quoted ("benchmark " ++ n) <> text " " <> block (statements [symbols,
      harness "benchmark" [quoted n, text "lawspec.testing.LawSpecHarness.Body { val _measured = " <> expr b <> text " }"]])
    -- A property whose inputs harness strategies draw, from Kotest's
    -- random source; their values' refinements are checked in the property.
    harnessProperty fn label e check = do
      let h = C.propertyHarness (original e)
          strategyOf inp = [(n, d) | (i, n, d) <- C.harnessDraws h, i == C.binderId (C.quantifiedBinder inp)]
      draws <- mapM (\plan -> do
        let inp = domainInput plan
        case strategyOf inp of
          (strategy, d) : _ -> bind (inputId inp) <$> drawDoc inp strategy d
          [] -> pure (bind (inputId inp) (generatorWithin (inputRange machineBits inp) (inputType inp) <> text ".sample(_random).value"))) (generationPlan e)
      let defaults = [inp | inp <- inputs e, null (strategyOf inp)]
          strategyChecks = [harness "checkDrawn" [quoted strategy, quoted (inputName inp),
              conjunction (map (truth . expr) (inputRefinements inp)), text (inputId inp)]
            | inp <- inputs e, (strategy, _) : _ <- [strategyOf inp], not (null (inputRefinements inp))]
          base = trailing (text "io.kotest.property.arbitrary.arbitrary") "_random" (statements
            ([symbols] ++ draws ++ [call "Pair" [call "listOf" [text (inputId inp) | inp <- inputs e], text "symbols"]]))
          predicates = concatMap inputRefinements defaults
          bindingsDoc = statements [text "val symbols = _inputs.second", text "val _values = _inputs.first", fromValues (inputs e)]
          strategy = if null predicates then base else trailing (base <> text ".filter") "_inputs"
            (statements [bindingsDoc, conjunction (map (truth . expr) predicates)])
      pure $ testFunction (fn ++ "_property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases (generation e))], strategy]) "_inputs"
        (statements ([bindingsDoc] ++ strategyChecks ++ handlerInstalls e ++ [check]))
    chooser = text "java.util.function.IntUnaryOperator { _n -> _random.random.nextInt(_n) }"
    drawDoc inp strategy d = case d of
      C.DrawAny ty -> pure ((if ty == inputType inp then generatorWithin (inputRange machineBits inp) ty else generator ty) <> text ".sample(_random).value")
      C.DrawOneOf _ values -> pure (harness "oneOf" [chooser, call "listOf" [text "java.util.function.Supplier { " <> expr v <> text " }" | v <- values]])
      C.DrawFrequency alternatives -> do
        options <- mapM (\(w, a) -> (\doc -> harness "Weighted" [number w, text "java.util.function.Supplier { " <> doc <> text " }"]) <$> drawDoc inp strategy a) alternatives
        pure (harness "frequency" [chooser, call "listOf" options])
      C.DrawSuchThat inner binder predicate limit -> do
        doc <- drawDoc inp strategy inner
        pure (harness "suchThat" [text "java.util.function.Supplier { " <> doc <> text " }",
          text ("java.util.function.Predicate<LawSpecRuntime.Value> { " ++ localName (C.binderId binder) ++ " -> ") <> truth (expr predicate) <> text " }",
          number limit, quoted strategy])
      C.DrawBind binder from rest -> do
        fromDoc <- drawDoc inp strategy from
        restDoc <- drawDoc inp strategy rest
        pure (text "run " <> block (statements [bind (localName (C.binderId binder)) fromDoc, restDoc]))
    -- LAWSPEC_SEED fixes Kotest's seed, so a run can be repeated exactly
    -- (lawspec test records the seed of every passing run).
    seedDoc = text "@OptIn(io.kotest.common.ExperimentalKotest::class)" <> D.hardline <>
      text "private fun _lawspecConfig(iterations: Int): PropTestConfig =" <> D.nest 4 (D.hardline <>
      text "PropTestConfig(seed = System.getenv(\"LAWSPEC_SEED\")?.toLong(), iterations = iterations)")
    expr = expression
    assertionDoc context proposition = case proposition of
      AssertAll ps -> statements (map (assertionDoc context) ps)
      AssertImplies guard body -> text "if (" <> truth (expr guard) <> text ") " <>
        block (assertionDoc context body)
      AssertEqual a b ->
        let message = quoted (context ++ " | expect " ++ prettyExpr a ++ " = " ++ prettyExpr b)
            isData = structural (expressionType a)
        in call (if isData then "_lawspecDataAssert" else "_lawspecAssert")
          ([message] ++ (if isData then [reference (expressionType a),text "symbols"] else []) ++
          [closure "" (expr a),closure "" (expr b)])
    contract c =
      let args = contractArguments c
          (rn,rt) = contractResult c
          params = text "symbols: MutableMap<String, Any>" : [text (n ++ ": LawSpecRuntime.Value") | (n,_) <- args]
          context stage ps = quoted (contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps))
          require stage ps = runtime "requireContract" [conjunction (map (truth . expr) ps),context stage ps]
          invocation = awaitResult (adapterName unit (C.contractDeclaration c)) (call (className ++ "." ++ adapterName unit (C.contractDeclaration c)) [nativeArgument ty (text n) | (n,ty) <- args])
      in call ("private fun _lawspec_call_" ++ contractName c) params <> text ": LawSpecRuntime.Value " <>
        block (statements [require "precondition" (contractPreconditions c),
          bind rn (nativeResult rt invocation),require "postcondition" (contractPostconditions c),text "return " <> text rn])
    -- A law's resources: each case acquires them, then runs, then releases
    -- them, the last first, even when the case fails.
    bracketed e docs = foldr wrap (statements docs) (C.propertyResources (original e))
      where
        -- A shared resource (share R per ...): the runtime keeps one per
        -- scope key, resets it before each later use, and releases it when
        -- the JVM exits. Each piece runs blocking, as it may suspend.
        wrap r inner | Just key <- C.resourceShared r, Just reset <- C.resourceReset r =
          let local = localName (C.binderId (C.resourceBinder r))
              blocking body = text "kotlinx.coroutines.runBlocking " <> block body
          in statements [bind local (runtime "share" [quoted key, closure "" (blocking (expr (C.resourceAcquire r))),
              closure local (statements [blocking (expr reset)]), closure local (statements [blocking (expr (C.resourceRelease r))]),
              text (if C.resourceConcurrent r then "true" else "false")]),
            text "try " <> block inner <> text " finally " <> block (runtime "unshare" [quoted key])]
        wrap r inner =
          let local = localName (C.binderId (C.resourceBinder r))
          in statements [bind local (expr (C.resourceAcquire r)),
            text "try " <> block inner <> text " finally " <> block (expr (C.resourceRelease r))]
    law testNames (index,e) = do
      let label = owner e ++ "::" ++ name e
          h = C.propertyHarness (original e)
          base' = testNames !! index
          fn = (if C.harnessSkip h == Nothing && (C.harnessKnownFailing h /= Nothing || runSettings h) then "harness:" else "") ++ base'
      exampleDocs <- mapM (\(i,ex) -> pure $ testFunction (fn ++ "_example" ++ show i) $ statements
        ([symbols] ++ handlerInstalls e ++ [bind n (expr v) | (n,v) <- bindings ex] ++
        [bracketed e (map (assertionDoc (label ++ " example " ++ exampleName ex)) (expectations ex) ++
          [assertionDoc label (assertion e)])])) (zip [0::Int ..] (examples (original e)))
      boundaryDocs <- mapM (\(i,vs) -> do
        values <- mapM literal vs
        pure $ testFunction (fn ++ "_boundary" ++ show i) $ statements
          ([symbols] ++ handlerInstalls e ++ [bind (inputId inp) (checked (inputType inp) v) | (inp,v) <- zip (inputs e) values] ++
          [bracketed e [assertionDoc (label ++ " boundary " ++ show i) (assertion e)]]))
        (zip [0::Int ..] (maybe (boundaryCases e) id (finiteCases e)))
      -- LawSpec's own search (LawSpec.Search): the failure database's
      -- inputs are replayed before the law's generated cases, a failing
      -- case's inputs are kept, and a law with `target maximize` climbs
      -- after them, as Kotest has no targeting.
      let descriptors = searchDescriptors e
          inputsName = "_lawspecInputs" ++ show index
          caseName = "_lawspecCase" ++ show index
          remembered doc = case descriptors of
            Nothing -> doc
            Just _ -> text "try " <> block doc <> text " catch (_lawspecError: Throwable) " <> block (statements
              [runtime "searchRemember" [quoted label, text inputsName, call "listOf" [text (inputId inp) | inp <- inputs e]], text "throw _lawspecError"])
          searchCase = text ("lawspec.runtime.LawSpecRuntime.SearchCase { _values -> kotlinx.coroutines.runBlocking { " ++ caseName ++ "(_values) } }")
          (searchBefore, searchAfter) = case descriptors of
            Nothing -> ([], [])
            Just ds ->
              let refinements = concatMap inputRefinements (inputs e)
              in ( [ bind inputsName (call "listOf" (map quoted ds))
                   , text ("val " ++ caseName ++ ": suspend (List<lawspec.runtime.LawSpecRuntime.Value>) -> Double? = lawspecCase@") <> closure "_values" (statements
                       ([symbols] ++ handlerInstalls e ++
                        [bind (inputId inp) (checked (inputType inp) (text ("_values[" ++ show i ++ "]"))) | (i, inp) <- zip [0::Int ..] (inputs e)] ++
                        [text "if (!(" <> conjunction (map (truth . expr) refinements) <> text ")) return@lawspecCase null" | not (null refinements)] ++
                        [bracketed e [assertionDoc (label ++ " search") (assertion e)],
                         maybe (text "0.0") (\score -> runtime "searchNumber" [expr score]) (C.harnessTarget h)]))
                   , quoted (base' ++ "_replay") <> text " " <> block (runtime "searchReplay" [quoted label, text inputsName, searchCase]) ]
                 , [quoted (base' ++ "_search") <> text " " <> block (runtime "searchClimb" [quoted label, text inputsName, searchCase]) | C.harnessTarget h /= Nothing] )
      let check = bracketed e (observations e ++ [remembered (assertionDoc (label ++ " property") (assertion e))])
      property <- if finiteCases e /= Nothing then pure []
        else if not (null (C.harnessDraws h)) then (:[]) <$> harnessProperty fn label e check
        else if constructorContracts || nativeGenerators || any (maybe False (const True) . generatorIndex) (generationPlan e)
          then (:[]) <$> contextualProperty fn label e check
        else if any (structural . inputType) (inputs e) then pure [nativeProperty fn label e check]
        else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract"
          then (:[]) <$> refinedProperty fn label e check
          else pure [nativeProperty fn label e check]
      let kinds = ["_example" ++ show i | i <- [0 .. length exampleDocs - 1]] ++ ["_boundary" ++ show i | i <- [0 .. length boundaryDocs - 1]] ++
            ["_property" | not (null property)]
      pure $ metadataDocument 96 "//" e <> separate (searchBefore ++ harnessTests base' label h kinds (exampleDocs ++ boundaryDocs ++ property) ++ searchAfter)
    contextualProperty fn label e check = do
      let bindings xs = statements [text "val symbols = _inputs.symbols",
            text "val _values = _inputs.values",fromValues xs]
          state value = call "LawSpecKotlinStrategies.Case"
            [value,text "symbols",text "_checked.error"]
          step prior (index,plan) = do
            let input = domainInput plan
                ty = inputType input
            seeds <- mapM literal (generatorBoundaries plan)
            let hints = [expr hint | hint <- generatorHints plan, expressionType hint == ty,
                  case C.expressionNode hint of
                    C.Constant _ -> True
                    C.Local _ -> True
                    _ -> False]
                strategy = case (if nativeGenerators then [] else requiredSymbol plan) of
                  value:_ -> call "Arb.constant" [call "LawSpecKotlinStrategies.Checked" [expr value,text "null"]]
                  -- The target is evaluated from the inputs bound above.
                  [] | Just indexed <- generatorIndex plan -> call "LawSpecKotlinStrategies.indexedGenerator"
                    [text "_schema",reference ty,number machineBits,number nodeBudget,text "symbols",
                     expr (indexedTarget indexed),
                     call "mapOf" [quoted (C.idText tag) <> text " to " <> call "listOf" (map quoted texts)
                       | (tag,texts) <- indexedEquations indexed],
                     text "::_lawspecScalarGenerator"]
                  [] -> call "LawSpecKotlinStrategies.checkedGenerator" $
                    [text "_schema",reference ty,number machineBits,number nodeBudget,
                     number (maxAttempts (generation e)),text "symbols",call "listOf" (seeds ++ hints)] ++
                    [text "lawspec.testing.LawSpecNativeGenerators.factories()" | nativeGenerators] ++
                    [text "::_lawspecScalarGenerator"]
                added = trailing (strategy <> text ".map") "_checked"
                  (text "if (_checked.error != null) " <> block (state (text "_values")) <>
                   text " else " <> block (state (text "_values + _checked.requireValue()")))
            pure $ trailing (call "lawspecFlatMap" [prior]) "_inputs"
              (text "if (_inputs.error != null) " <> block (text "Arb.constant(_inputs)") <>
               text " else " <> block (statements [bindings (take index (inputs e)),added]))
      base <- foldM step (text "LawSpecKotlinStrategies.cases()") (zip [0::Int ..] (generationPlan e))
      let predicates = concatMap inputRefinements (inputs e)
          strategy = if null predicates then base else trailing
            (call "LawSpecKotlinStrategies.filterCases" [base,number (maxAttempts (generation e))]) "_inputs"
            (statements [bindings (inputs e),conjunction (map (truth . expr) predicates)])
          body = statements ([text "val symbols = _inputs.symbols",
            text "val _values = _inputs.requireValues()",fromValues (inputs e)] ++ handlerInstalls e ++ [check])
      pure $ testFunction (fn ++ "_property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases (generation e))],strategy]) "_inputs" body
    requiredSymbol plan
      | inputType (domainInput plan) /= C.scalarType "Symbol" = []
      | otherwise = concatMap required (generatorPredicates plan)
      where
        current = C.binderId (generatorBinder plan)
        required term = case C.expressionNode term of
          C.ShortCircuit C.And a b -> required a ++ required b
          C.Binary C.Equal _ a b -> [value | (local,value) <- [(a,b),(b,a)],
            C.expressionNode local == C.Local current,
            expressionType value == C.scalarType "Symbol",
            current `notElem` C.freeBinders value,
            case C.expressionNode value of
              C.Constant _ -> True
              C.Local _ -> True
              _ -> False]
          _ -> []
    nativeProperty fn label e check =
      let tuple = foldl (\prior inp -> trailing (call "Arb.bind" [prior,generatorWithin (inputRange machineBits inp) (inputType inp)])
            "_values, _value" (text "_values + _value"))
            (text "Arb.constant(emptyList<LawSpecRuntime.Value>())") (inputs e)
          base = trailing (tuple <> text ".map") "_values"
            (text "Pair(_values, mutableMapOf<String, Any>())")
          predicates = concatMap inputRefinements (inputs e)
          bindingsDoc = statements [text "val symbols = _inputs.second",
            text "val _values = _inputs.first",fromValues (inputs e)]
          strategy = if null predicates then base else trailing (base <> text ".filter") "_inputs"
            (statements [bindingsDoc,conjunction (map (truth . expr) predicates)])
      in testFunction (fn ++ "_property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases (generation e))],strategy]) "_inputs"
        (statements ([bindingsDoc] ++ handlerInstalls e ++ [check]))
    domain e (index,plan) = do
      seeds <- mapM literal (generatorBoundaries plan)
      let inp = domainInput plan
          prior = take index (inputs e)
          bounds = E.array [call "LawSpecRuntime.Bound" [quoted op,expr v] | (op,v) <- domainBounds plan]
          candidates = runtime "domainCandidates" [quoted (typeKey (inputType inp)),text "_seed",number machineBits,
            bounds,E.array (seeds ++ map expr (generatorHints plan))]
          seedFn = closure "_values, _seed" (statements ([fromValues prior | not (null prior)] ++ [candidates]))
          predicate = closure "_values" (statements
            [fromValues (prior ++ [inp]),conjunction (map (truth . expr) (inputRefinements inp))])
      pure (call "LawSpecRuntime.Domain" [seedFn,predicate])
    refinedProperty fn label e check = do
      domains <- mapM (domain e) (zip [0::Int ..] (generationPlan e))
      let cfg = generation e
          callback = closure "_values" (statements ([fromValues (inputs e)] ++ handlerInstalls e ++ [check]))
          invocation = runtime "refinedCase" [E.array domains,
            text "seed",number (maxAttempts cfg),number (maxShrinks cfg),callback,
            quoted (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ testFunction (fn ++ "_property: " ++ label) $ trailing
        (call "checkAll" [call "_lawspecConfig" [number (cases cfg)],text "Arb.int()"]) "seed" (statements [symbols,invocation])

-- Whether a unit's laws install a Clock handler, so the test registers how
-- the runtime reads one (lawspec.time's registerClock).
installsClock :: Unit -> Bool
installsClock unit = or [ C.abilityKey a == "lawspec.time::ability::Clock"
                        | p <- C.unitProperties unit, (a, _) <- C.propertyHandlers p ]
