-- | Kotlin native APIs over shared JVM total-definition bodies.
module LawSpec.KotlinDefinitions (emitKotlinDefinitions) where

import Control.Monad (forM)
import Data.Char (toUpper)
import Data.List (intercalate)
import LawSpec.Common
import LawSpec.Core
import qualified LawSpec.KotlinData as Native
import qualified LawSpec.KotlinExpr as E
import qualified LawSpec.JavaDefinitions as Jvm
import qualified LawSpec.Code.Doc as D
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T

-- | Checked definitions are emitted as ordinary Kotlin code, so adapters and tests call
-- the same proved implementation. ref:DEC-total-definitions
emitKotlinDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitKotlinDefinitions layout bits declarations units = do
  bodies <- Jvm.emitJvmDefinitionBodies layout bits declarations units
  native <- forM (filter (not . null . unitDefinitions) units) $ \unit -> do
    let parts = split '.' (idText (unitId unit))
        name = concatMap capitalize (split '_' (last parts))
        package = intercalate "." ("lawspec" : "definitions" : init parts)
        types = concatMap (typeNames . declarationType . definitionDeclaration) (unitDefinitions unit)
        imports = ["LawSpecDataCodecs" | any (\name -> Id name `elem` map dataId declarations) types] ++
          ["LawSpecDataSchema"] ++ ["LawSpecKotlinCodecs" | any (`elem`
            ["Nullable","Optional","Unit","Null","Undefined","Symbol","CodePointText"]) types]
    methods <- mapM definition (unitDefinitions unit)
    let content = D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
          D.text ("package " ++ package) <> D.hardline <> D.hardline <>
          D.joinWith D.hardline [D.text ("import lawspec.runtime." ++ item) | item <- imports] <>
          D.hardline <> D.hardline <> D.text ("object " ++ name ++ " ") <>
          D.block 4 (D.joinWith (D.hardline <> D.hardline)
            ([D.text "private val schema = LawSpecDataSchema.create()",
              D.text ("private const val bits = " ++ show bits)] ++ methods)) <> D.hardline
    pure (Artifact ("src/main/kotlin/" ++ map (\c -> if c == '.' then '/' else c) package ++ "/" ++ name ++ ".kt")
      (D.render layout content) "generated" "source")
  bridge <- adapterBridge
  pure (bodies ++ native ++ bridge)
  where
    -- Kotlin adapters, called from the shared JVM bodies through Kotlin
    -- codecs.
    adapterBridge = case Jvm.orchestratedAdapters units of
      [] -> pure []
      adapters -> do
        methods <- forM adapters $ \(identity, (owner, adapter)) -> do
          let (args, result) = functionType (declarationType adapter)
              parts = split '.' (idText owner)
              cls = intercalate "." (init parts ++ [concatMap capitalize (split '_' (last parts))])
          codecs <- mapM (Native.kotlinCodecDocWithContext (D.text "symbols") declarations) args
          resultCodec <- Native.kotlinCodecDocWithContext (D.text "symbols") declarations result
          let parameters = D.text "symbols: MutableMap<String, Any>" :
                [D.text ("value" ++ show i ++ ": LawSpecRuntime.Value") | i <- [0 .. length args - 1]]
              invocation = call (cls ++ "." ++ declarationName adapter)
                [codec <> D.text (".decode(value" ++ show i ++ ")") | (i, codec) <- zip [0::Int ..] codecs]
              -- A suspending adapter runs as a coroutine the workflow awaits,
              -- within its stage's timeout and hedge when it has them.
              body
                | declarationAsync adapter = call "LawSpecRuntime.awaitStep"
                    [D.text "symbols", D.text "{ CoroutineScope(Dispatchers.Default).future { " <> invocation <> D.text " } }",
                     D.text "{ native -> " <> resultCodec <> D.text ".encode(native) }"]
                | otherwise = resultCodec <> D.text ".encode(" <> invocation <> D.text ")"
          pure (D.text "@JvmStatic" <> D.hardline <> D.text ("fun " ++ Jvm.kotlinAdapterBridge identity) <>
            D.delimitTrailing 4 "(" ")" parameters <> D.text ": LawSpecRuntime.Value = " <> body)
        let asynchronous = any (declarationAsync . snd . snd) adapters
            content = D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
              D.text "package lawspec.runtime" <> D.hardline <> D.hardline <>
              (if asynchronous
                then D.joinWith D.hardline (map D.text ["import kotlinx.coroutines.CoroutineScope",
                  "import kotlinx.coroutines.Dispatchers", "import kotlinx.coroutines.future.future"]) <> D.hardline <> D.hardline
                else mempty) <>
              D.text "object LawSpecKotlinAdapters " <>
              D.block 4 (D.joinWith (D.hardline <> D.hardline)
                ([D.text "private val schema = LawSpecDataSchema.create()",
                  D.text ("private const val bits = " ++ show bits)] ++ methods)) <> D.hardline
        pure [Artifact "src/main/kotlin/lawspec/runtime/LawSpecKotlinAdapters.kt" (D.render layout content) "generated" "source"]
    typeNames (Constructor name args) = name : concat [typeNames ty | TypeArgument ty <- args]
    typeNames (Arrow a b) = typeNames a ++ typeNames b
    typeNames _ = []
    callees = Jvm.definitionCalls units
    call name values = D.text name <> D.delimitTrailing 4 "(" ")" values
    assign name value = D.group (D.text ("val " ++ name ++ " =") <> D.nest 4 (D.softline <> value))
    definition d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
      types <- mapM (Native.kotlinDataTypeDoc declarations) args
      resultType <- Native.kotlinDataTypeDoc declarations result
      codecs <- mapM (Native.kotlinCodecDocWithContext (D.text "symbols") declarations) args
      resultCodec <- Native.kotlinCodecDocWithContext (D.text "symbols") declarations result
      evaluator <- maybe (Left "unresolved Kotlin definition") Right (lookup (declarationId declaration) callees)
      let parameters = D.text "symbols: MutableMap<String, Any>" :
            [D.text ("value" ++ show i ++ ": ") <> ty | (i,ty) <- zip [0::Int ..] types]
          signature = D.text ("fun " ++ declarationName declaration) <>
            D.delimitTrailing 4 "(" ")" parameters <> D.text ": " <> resultType <> D.text " "
          input i codec = [assign ("codec" ++ show i) codec,
            D.text ("val argument" ++ show i ++ " = codec" ++ show i ++ ".encode(value" ++ show i ++ ")")]
          body = concat [input i codec | (i,codec) <- zip [0::Int ..] codecs] ++
            [assign "result" (call evaluator (D.text "symbols" : [D.text ("argument" ++ show i) | i <- [0 .. length args - 1]])),
             assign "resultCodec" resultCodec,D.text "return resultCodec.decode(result)"]
          context = E.quoted (idText (declarationId declaration) ++ ": ")
          guarded = D.text "try " <> D.block 4 (D.joinWith D.hardline body) <>
            D.text " catch (error: RuntimeException) " <> D.block 4
              (D.text "throw " <> call "IllegalArgumentException"
                [D.group (context <> D.text " +" <> D.nest 4 (D.softline <> D.text "error.message")),D.text "error"])
      pure (signature <> D.block 4 guarded)
    split delimiter value = case break (== delimiter) value of
      (a,[]) -> [a]
      (a,_:rest) -> a : split delimiter rest
    capitalize [] = []
    capitalize (c:cs) = toUpper c : cs
