-- Typed mailboxes for implementation code. Every `mailbox jobs of Job`
-- becomes, on each target, a mailbox type named JobsMailbox: send never
-- waits, one receiver takes messages in the order they arrived, and close
-- refuses later sends. A mailbox can also be offered on a node (serve) and
-- sent to from other nodes (connect); a send between nodes waits until the
-- mailbox has the message, and runs once however often it is resent.
module LawSpec.Mailboxes (mailboxArtifacts, mailboxClassName) where

import Data.Char (toUpper)
import Data.List (intercalate, nub)
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..), Diagnostic(..))
import LawSpec.MachineSpec (describe)
import LawSpec.PythonData (pythonTypeReferenceDoc, requiresSchema)
import LawSpec.PythonTypes (pythonDataTypeDoc)
import LawSpec.Testing (Plan(..), PlannedUnit(..))

-- jobs's class is JobsMailbox.
mailboxClassName :: String -> String
mailboxClassName n = case n of
  c : cs -> toUpper c : cs ++ "Mailbox"
  [] -> "Mailbox"

mailboxArtifacts :: String -> Plan -> Either [Diagnostic] [Artifact]
mailboxArtifacts target plan = case concatMap C.unitMailboxes units of
  [] -> Right []
  boxes -> either (\message -> Left [Diagnostic "mailboxes" message Nothing]) Right $ case target of
    "python" -> python bits datas boxes
    _ -> Right []
  where
    units = map plannedUnit (plannedUnits plan)
    datas = planDataDeclarations plan
    bits = planMachineBits plan

python :: Int -> [C.DataDeclaration] -> [C.Mailbox] -> Either String [Artifact]
python bits datas boxes = do
  let names = map C.mailboxName boxes
  if length (nub names) /= length names then Left ("two mailboxes share a name: " ++ unwords names) else pure ()
  (table, classes) <- foldl (\acc b -> do
      (t, cs) <- acc
      native <- D.render (D.Pretty 1000) <$> pythonDataTypeDoc datas (C.mailboxType b)
      case describe bits datas t (C.mailboxType b) of
        Right (d, t') -> pure (t', cs ++ [cls b native (Just d)])
        Left _ -> pure (t, cs ++ [cls b native (Nothing :: Maybe String)])) (Right ([], [])) boxes
  let header =
        [ "# Generated by LawSpec. Do not edit."
        , "\"\"\"Typed mailboxes: many senders, one receiver."
        , ""
        , "send never waits; receive takes messages in the order they arrived;"
        , "close refuses later sends. serve(node, name) offers a mailbox to other"
        , "nodes, and connect(node, address) sends to one from another node: such a"
        , "send waits until the mailbox has the message, and it is delivered once."
        , "\"\"\""
        , "from __future__ import annotations"
        , ""
        , "import builtins as _builtins"
        , "import lawspec_runtime as ls"
        , "try:"
        , "    import lawspec_data as data"
        , "    import lawspec_schema as _schema"
        , "    _SCHEMA = data.make_schema()"
        , "except ImportError:"
        , "    _SCHEMA = None"
        , ""
        , "_TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ show (unwords (map snd (reverse table))) ++ ")})"
        , ""
        , ""
        , "def _native(reference, value):"
        , "    return value if reference is None else _SCHEMA.to_native(reference, value)"
        , ""
        , ""
        , "def _logical(reference, value):"
        , "    return value if reference is None else _SCHEMA.from_native(reference, value)" ]
  pure [Artifact "src/lawspec_mailboxes.py" (unlines header ++ concatMap ("\n\n" ++) classes) "generated" "source"]
  where
    reference ty = if requiresSchema datas ty then either (const "None") (D.render (D.Pretty 1000)) (pythonTypeReferenceDoc ty) else "None"
    cls b native wire = unlines $
      [ "class " ++ name ++ ":"
      , "    \"\"\"Mailbox " ++ C.mailboxName b ++ ": messages of " ++ native ++ " from any number of senders,"
      , "    taken by one receiver.\"\"\""
      , ""
      , "    def __init__(self, mailbox: ls.Mailbox | None = None, logical: bool = False):"
      , "        self._mailbox = ls.Mailbox() if mailbox is None else mailbox"
      , "        self._logical = logical"
      , ""
      , "    def send(self, value: " ++ native ++ ") -> None:"
      , "        \"\"\"Queues value without waiting.\"\"\""
      , "        self._mailbox.send(_logical(" ++ ref ++ ", value) if self._logical else value)"
      , ""
      , "    def receive(self, timeout: float | None = None) -> " ++ native ++ ":"
      , "        \"\"\"The next message; waits up to timeout seconds (forever when None),"
      , "        then raises TimeoutError; raises ls.ActorStopped once closed and empty.\"\"\""
      , "        value = self._mailbox.receive(timeout)"
      , "        return _native(" ++ ref ++ ", value) if self._logical else value"
      , ""
      , "    def close(self) -> None:"
      , "        \"\"\"Refuses later sends; messages already sent can still be received.\"\"\""
      , "        self._mailbox.close()" ] ++
      case wire of
        Nothing -> []
        Just d ->
          [ ""
          , "    @staticmethod"
          , "    def serve(node: ls.Node, name: str) -> " ++ name ++ ":"
          , "        \"\"\"A mailbox on node that other nodes send to at <node address>/name.\"\"\""
          , "        return " ++ name ++ "(node.mailbox(name, ls.read_descriptor(" ++ show d ++ ")[0], _TYPES), logical=True)"
          , ""
          , "    @staticmethod"
          , "    def connect(node: ls.Node, address: str, timeout: float = 5.0) -> " ++ name ++ "Sender:"
          , "        \"\"\"Sends to the mailbox served at address on another node.\"\"\""
          , "        return " ++ name ++ "Sender(node.remote_mailbox(address, ls.read_descriptor(" ++ show d ++ ")[0], _TYPES, timeout))"
          , ""
          , ""
          , "class " ++ name ++ "Sender:"
          , "    \"\"\"Sends to mailbox " ++ C.mailboxName b ++ " on another node.\"\"\""
          , ""
          , "    def __init__(self, remote: ls.RemoteMailbox):"
          , "        self._remote = remote"
          , ""
          , "    def send(self, value: " ++ native ++ ") -> None:"
          , "        \"\"\"Sends value; waits until the mailbox has it, or raises ls.Unreachable.\"\"\""
          , "        self._remote.send(_logical(" ++ ref ++ ", value))" ]
      where
        name = mailboxClassName (C.mailboxName b)
        ref = reference (C.mailboxType b)
