-- Typed mailboxes for implementation code. Every `mailbox jobs of Job`
-- becomes, on each target, a mailbox type named JobsMailbox: send never
-- waits, one receiver takes messages in the order they arrived, and close
-- refuses later sends. A mailbox can also be offered on a node (serve) and
-- sent to from other nodes (connect); a send between nodes waits until the
-- mailbox has the message, and runs once however often it is resent.
module LawSpec.Mailboxes (mailboxArtifacts, mailboxClassName) where

import Data.Char (toUpper)
import Data.List (intercalate, isInfixOf, nub)
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..), Diagnostic(..))
import LawSpec.MachineSpec (describe)
import LawSpec.PythonData (pythonTypeReferenceDoc, requiresSchema)
import LawSpec.PythonTypes (pythonDataTypeDoc)
import LawSpec.JavaData (javaDataType, javaCodecDocWithContext)
import LawSpec.KotlinData (kotlinDataType, kotlinCodecDocWithContext)
import LawSpec.Scalar (isInteger)
import LawSpec.Testing (Plan(..), PlannedUnit(..))

-- jobs's class is JobsMailbox.
mailboxClassName :: String -> String
mailboxClassName n = case n of
  c : cs -> toUpper c : cs ++ "Mailbox"
  [] -> "Mailbox"

mailboxArtifacts :: String -> Plan -> Either [Diagnostic] [Artifact]
mailboxArtifacts target plan = case concatMap C.unitMailboxes units of
  [] -> Right []
  boxes -> either (\message -> Left [Diagnostic "mailboxes" message Nothing]) Right $ case target of
    "python" -> python bits datas boxes
    "java" -> mapM (jvm False bits datas) boxes
    "kotlin" -> mapM (jvm True bits datas) boxes
    _ -> Right []
  where
    units = map plannedUnit (plannedUnits plan)
    datas = planDataDeclarations plan
    bits = planMachineBits plan

python :: Int -> [C.DataDeclaration] -> [C.Mailbox] -> Either String [Artifact]
python bits datas boxes = do
  let names = map C.mailboxName boxes
  if length (nub names) /= length names then Left ("two mailboxes share a name: " ++ unwords names) else pure ()
  (table, classes) <- foldl (\acc b -> do
      (t, cs) <- acc
      native <- D.render (D.Pretty 1000) <$> pythonDataTypeDoc datas (C.mailboxType b)
      case describe bits datas t (C.mailboxType b) of
        Right (d, t') -> pure (t', cs ++ [cls b native (Just d)])
        Left _ -> pure (t, cs ++ [cls b native (Nothing :: Maybe String)])) (Right ([], [])) boxes
  let header =
        [ "# Generated by LawSpec. Do not edit."
        , "\"\"\"Typed mailboxes: many senders, one receiver."
        , ""
        , "send never waits; receive takes messages in the order they arrived;"
        , "close refuses later sends. serve(node, name) offers a mailbox to other"
        , "nodes, and connect(node, address) sends to one from another node: such a"
        , "send waits until the mailbox has the message, and it is delivered once."
        , "\"\"\""
        , "from __future__ import annotations"
        , ""
        , "import builtins as _builtins"
        , "import lawspec_runtime as ls"
        , "try:"
        , "    import lawspec_data as data"
        , "    import lawspec_schema as _schema"
        , "    _SCHEMA = data.make_schema()"
        , "except ImportError:"
        , "    _SCHEMA = None"
        , ""
        , "_TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ show (unwords (map snd (reverse table))) ++ ")})"
        , ""
        , ""
        , "def _native(reference, value):"
        , "    return value if reference is None else _SCHEMA.to_native(reference, value)"
        , ""
        , ""
        , "def _logical(reference, value):"
        , "    return value if reference is None else _SCHEMA.from_native(reference, value)" ]
  pure [Artifact "src/lawspec_mailboxes.py" (unlines header ++ concatMap ("\n\n" ++) classes) "generated" "source"]
  where
    reference ty = if requiresSchema datas ty then either (const "None") (D.render (D.Pretty 1000)) (pythonTypeReferenceDoc ty) else "None"
    cls b native wire = unlines $
      [ "class " ++ name ++ ":"
      , "    \"\"\"Mailbox " ++ C.mailboxName b ++ ": messages of " ++ native ++ " from any number of senders,"
      , "    taken by one receiver.\"\"\""
      , ""
      , "    def __init__(self, mailbox: ls.Mailbox | None = None, logical: bool = False):"
      , "        self._mailbox = ls.Mailbox() if mailbox is None else mailbox"
      , "        self._logical = logical"
      , ""
      , "    def send(self, value: " ++ native ++ ") -> None:"
      , "        \"\"\"Queues value without waiting.\"\"\""
      , "        self._mailbox.send(_logical(" ++ ref ++ ", value) if self._logical else value)"
      , ""
      , "    def receive(self, timeout: float | None = None) -> " ++ native ++ ":"
      , "        \"\"\"The next message; waits up to timeout seconds (forever when None),"
      , "        then raises TimeoutError; raises ls.ActorStopped once closed and empty.\"\"\""
      , "        value = self._mailbox.receive(timeout)"
      , "        return _native(" ++ ref ++ ", value) if self._logical else value"
      , ""
      , "    def close(self) -> None:"
      , "        \"\"\"Refuses later sends; messages already sent can still be received.\"\"\""
      , "        self._mailbox.close()" ] ++
      case wire of
        Nothing -> []
        Just d ->
          [ ""
          , "    @staticmethod"
          , "    def serve(node: ls.Node, name: str) -> " ++ name ++ ":"
          , "        \"\"\"A mailbox on node that other nodes send to at <node address>/name.\"\"\""
          , "        return " ++ name ++ "(node.mailbox(name, ls.read_descriptor(" ++ show d ++ ")[0], _TYPES), logical=True)"
          , ""
          , "    @staticmethod"
          , "    def connect(node: ls.Node, address: str, timeout: float = 5.0) -> " ++ name ++ "Sender:"
          , "        \"\"\"Sends to the mailbox served at address on another node.\"\"\""
          , "        return " ++ name ++ "Sender(node.remote_mailbox(address, ls.read_descriptor(" ++ show d ++ ")[0], _TYPES, timeout))"
          , ""
          , ""
          , "class " ++ name ++ "Sender:"
          , "    \"\"\"Sends to mailbox " ++ C.mailboxName b ++ " on another node.\"\"\""
          , ""
          , "    def __init__(self, remote: ls.RemoteMailbox):"
          , "        self._remote = remote"
          , ""
          , "    def send(self, value: " ++ native ++ ") -> None:"
          , "        \"\"\"Sends value; waits until the mailbox has it, or raises ls.Unreachable.\"\"\""
          , "        self._remote.send(_logical(" ++ ref ++ ", value))" ]
      where
        name = mailboxClassName (C.mailboxName b)
        ref = reference (C.mailboxType b)

-- lawspec.mailboxes.JobsMailbox: a Java class for Java projects and a Kotlin
-- class for Kotlin ones (whose data types and codecs are Kotlin's).
jvm :: Bool -> Int -> [C.DataDeclaration] -> C.Mailbox -> Either String Artifact
jvm kotlin bits datas b = do
  let ty = C.mailboxType b
      name = mailboxClassName (C.mailboxName b)
      scalar = case ty of
        C.Constructor n [] | isInteger n || n `elem` ["Bool", "Text"] -> Just n
        _ -> Nothing
      wire = either (const Nothing) Just (describe bits datas [] ty)
  native <- if kotlin then kotlinDataType datas ty else javaDataType datas ty
  codec <- case scalar of
    Just n -> pure ("LawSpecRuntime.scalarConversion(" ++ show n ++ ", " ++ show bits ++ ")")
    Nothing
      | kotlin -> (\c -> "run { val symbols = mutableMapOf<String, Any>(); val codec = " ++ c ++
                          "; LawSpecRuntime.conversion<" ++ native ++ ">({ codec.encode(it) }, { codec.decode(it) }) }")
                  . D.render (D.Pretty 1000) <$> kotlinCodecDocWithContext (D.text "symbols") datas ty
      | otherwise -> (\c -> "LawSpecRuntime.conversion((" ++ c ++ ")::encode, (" ++ c ++ ")::decode)")
                  . D.render (D.Pretty 1000) <$> javaCodecDocWithContext (D.text "symbols") datas bits ty
  let imports = [ "import lawspec.runtime." ++ x | x <- ["LawSpecDataCodecs", "LawSpecDataSchema", "LawSpecKotlinCodecs"], (x ++ ".") `isInfixOf` codec ]
      descriptorText = maybe "(unit)" fst wire
      typesText = maybe "" (unwords . map snd . reverse . snd) wire
      doc = "Mailbox " ++ C.mailboxName b ++ ": messages from any number of senders, taken by one receiver."
  pure $ if kotlin
    then Artifact ("src/main/kotlin/lawspec/mailboxes/" ++ name ++ ".kt") (unlines $
      [ "// Generated by LawSpec from mailbox " ++ C.mailboxName b ++ ". Do not edit."
      , "package lawspec.mailboxes"
      , ""
      , "import lawspec.runtime.LawSpecRuntime" ] ++ imports ++
      [ ""
      , "/**"
      , " * " ++ doc ++ " send never waits; receive takes messages in the order they"
      , " * arrived; close refuses later sends. serve offers it to other nodes, and connect sends to one"
      , " * on another node: such a send waits until the mailbox has the message, delivered once."
      , " */"
      , "class " ++ name ++ " private constructor(private val mailbox: LawSpecRuntime.Mailbox<Any>, private val logical: Boolean) {"
      , "    constructor() : this(LawSpecRuntime.Mailbox<Any>(), false)"
      , ""
      , "    /** Queues value without waiting. */"
      , "    fun send(value: " ++ native ++ ") = mailbox.send(if (logical) conversion().toLogical(value) else value)"
      , ""
      , "    /** The next message; waits up to timeout (forever when null), then throws IllegalStateException; throws ActorStopped once closed and empty. */"
      , "    @JvmOverloads"
      , "    fun receive(timeout: java.time.Duration? = null): " ++ native ++ " {"
      , "        val value = mailbox.receive(timeout)"
      , "        @Suppress(\"UNCHECKED_CAST\")"
      , "        return (if (logical) conversion().toNative(value as LawSpecRuntime.Value) else value) as " ++ native
      , "    }"
      , ""
      , "    /** Refuses later sends; messages already sent can still be received. */"
      , "    fun close() = mailbox.close()"
      , ""
      , "    /** Sends to mailbox " ++ C.mailboxName b ++ " on another node. */"
      , "    class Sender internal constructor(private val remote: LawSpecRuntime.RemoteMailbox) {"
      , "        /** Sends value; waits until the mailbox has it, or throws Unreachable. */"
      , "        fun send(value: " ++ native ++ ") = remote.send(conversion().toLogical(value))"
      , "    }"
      , ""
      , "    companion object {"
      , "        private val schema = lawspec.runtime.LawSpecDataSchema.create()"
      , "        private const val bits = " ++ show bits
      , "        private val TYPES = LawSpecRuntime.valuesOf(" ++ show typesText ++ ")"
      , "        private val DESCRIPTOR = LawSpecRuntime.descriptor(" ++ show descriptorText ++ ")"
      , ""
      , "        private fun conversion(): LawSpecRuntime.Conversion = " ++ codec
      , ""
      , "        /** A mailbox on node that other nodes send to at {node address}/name. */"
      , "        @JvmStatic"
      , "        @Suppress(\"UNCHECKED_CAST\")"
      , "        fun serve(node: LawSpecRuntime.Node, name: String): " ++ name ++ " ="
      , "            " ++ name ++ "(node.mailbox(name, DESCRIPTOR, TYPES) as LawSpecRuntime.Mailbox<Any>, true)"
      , ""
      , "        /** Sends to the mailbox served at address on another node. */"
      , "        @JvmStatic"
      , "        @JvmOverloads"
      , "        fun connect(node: LawSpecRuntime.Node, address: String, timeout: Double = 5.0): Sender ="
      , "            Sender(node.remoteMailbox(address, DESCRIPTOR, TYPES, timeout))"
      , "    }"
      , "}" ]) "generated" "source"
    else Artifact ("src/main/java/lawspec/mailboxes/" ++ name ++ ".java") (unlines $
      [ "// Generated by LawSpec from mailbox " ++ C.mailboxName b ++ ". Do not edit."
      , "package lawspec.mailboxes;"
      , ""
      , "import lawspec.runtime.LawSpecRuntime;"
      , ""
      , "/**"
      , " * " ++ doc ++ " send never waits; receive takes messages in the order they"
      , " * arrived; close refuses later sends. serve offers it to other nodes, and connect sends to one"
      , " * on another node: such a send waits until the mailbox has the message, delivered once."
      , " */"
      , "public final class " ++ name ++ " {"
      , "  private static final LawSpecRuntime.Values TYPES = LawSpecRuntime.valuesOf(" ++ show typesText ++ ");"
      , "  private static final Object DESCRIPTOR = LawSpecRuntime.descriptor(" ++ show descriptorText ++ ");"
      , "  private final LawSpecRuntime.Mailbox<Object> mailbox;"
      , "  private final boolean logical;"
      , ""
      , "  public " ++ name ++ "() {"
      , "    this(new LawSpecRuntime.Mailbox<Object>(), false);"
      , "  }"
      , ""
      , "  private " ++ name ++ "(LawSpecRuntime.Mailbox<Object> mailbox, boolean logical) {"
      , "    this.mailbox = mailbox;"
      , "    this.logical = logical;"
      , "  }"
      , ""
      ] ++ [ l | scalar == Nothing, l <- ["  private static final lawspec.runtime.LawSpecSchema _schema =", "      lawspec.runtime.LawSpecDataSchema.create();", ""] ] ++
      [ "  @SuppressWarnings(\"unused\")"
      , "  private static LawSpecRuntime.Conversion conversion() {"
      , "    var symbols = new java.util.HashMap<String, Object>();"
      , "    return " ++ codec ++ ";"
      , "  }"
      , ""
      , "  /** Queues value without waiting. */"
      , "  public void send(" ++ native ++ " value) {"
      , "    mailbox.send(logical ? conversion().toLogical(value) : value);"
      , "  }"
      , ""
      , "  /** The next message, waiting forever; throws ActorStopped once closed and empty. */"
      , "  public " ++ native ++ " receive() {"
      , "    return receive(null);"
      , "  }"
      , ""
      , "  /** The next message; waits up to timeout (forever when null), then throws IllegalStateException. */"
      , "  @SuppressWarnings(\"unchecked\")"
      , "  public " ++ native ++ " receive(java.time.Duration timeout) {"
      , "    var value = mailbox.receive(timeout);"
      , "    return (" ++ native ++ ") (logical ? conversion().toNative((LawSpecRuntime.Value) value) : value);"
      , "  }"
      , ""
      , "  /** Refuses later sends; messages already sent can still be received. */"
      , "  public void close() {"
      , "    mailbox.close();"
      , "  }"
      , ""
      , "  /** A mailbox on node that other nodes send to at {node address}/name. */"
      , "  @SuppressWarnings({\"unchecked\", \"rawtypes\"})"
      , "  public static " ++ name ++ " serve(LawSpecRuntime.Node node, String name) {"
      , "    return new " ++ name ++ "((LawSpecRuntime.Mailbox) node.mailbox(name, DESCRIPTOR, TYPES), true);"
      , "  }"
      , ""
      , "  /** Sends to the mailbox served at address on another node. */"
      , "  public static Sender connect(LawSpecRuntime.Node node, String address) {"
      , "    return connect(node, address, 5.0);"
      , "  }"
      , ""
      , "  public static Sender connect(LawSpecRuntime.Node node, String address, double timeout) {"
      , "    return new Sender(node.remoteMailbox(address, DESCRIPTOR, TYPES, timeout));"
      , "  }"
      , ""
      , "  /** Sends to mailbox " ++ C.mailboxName b ++ " on another node. */"
      , "  public static final class Sender {"
      , "    private final LawSpecRuntime.RemoteMailbox remote;"
      , ""
      , "    Sender(LawSpecRuntime.RemoteMailbox remote) {"
      , "      this.remote = remote;"
      , "    }"
      , ""
      , "    /** Sends value; waits until the mailbox has it, or throws Unreachable. */"
      , "    public void send(" ++ native ++ " value) {"
      , "      remote.send(conversion().toLogical(value));"
      , "    }"
      , "  }"
      , "}" ]) "generated" "source"
