-- Typed mailboxes for implementation code. Every `mailbox jobs of Job`
-- becomes, on each target, a mailbox type named JobsMailbox: send never
-- waits, one receiver takes messages in the order they arrived, and close
-- refuses later sends. A mailbox can also be offered on a node (serve) and
-- sent to from other nodes (connect); a send between nodes waits until the
-- mailbox has the message, and runs once however often it is resent.
module LawSpec.Mailboxes (mailboxArtifacts, mailboxClassName) where

import Data.Char (toUpper)
import Data.List (intercalate, nub)
import qualified LawSpec.Code.Doc as D
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..), Diagnostic(..))
import LawSpec.MachineSpec (describe)
import LawSpec.PythonData (pythonTypeReferenceDoc, requiresSchema)
import LawSpec.PythonTypes (pythonDataTypeDoc)
import LawSpec.HaskellData (haskellNativeTypeWithParameters, haskellCodecDoc)
import LawSpec.Testing (Plan(..), PlannedUnit(..))

-- jobs's class is JobsMailbox.
mailboxClassName :: String -> String
mailboxClassName n = case n of
  c : cs -> toUpper c : cs ++ "Mailbox"
  [] -> "Mailbox"

mailboxArtifacts :: String -> Plan -> Either [Diagnostic] [Artifact]
mailboxArtifacts target plan = case concatMap C.unitMailboxes units of
  [] -> Right []
  boxes -> either (\message -> Left [Diagnostic "mailboxes" message Nothing]) Right $ case target of
    "python" -> python bits datas boxes
    "haskell" -> concat <$> mapM (haskell bits datas) [u | u <- units, not (null (C.unitMailboxes u))]
    _ -> Right []
  where
    units = map plannedUnit (plannedUnits plan)
    datas = planDataDeclarations plan
    bits = planMachineBits plan

python :: Int -> [C.DataDeclaration] -> [C.Mailbox] -> Either String [Artifact]
python bits datas boxes = do
  let names = map C.mailboxName boxes
  if length (nub names) /= length names then Left ("two mailboxes share a name: " ++ unwords names) else pure ()
  (table, classes) <- foldl (\acc b -> do
      (t, cs) <- acc
      native <- D.render (D.Pretty 1000) <$> pythonDataTypeDoc datas (C.mailboxType b)
      case describe bits datas t (C.mailboxType b) of
        Right (d, t') -> pure (t', cs ++ [cls b native (Just d)])
        Left _ -> pure (t, cs ++ [cls b native (Nothing :: Maybe String)])) (Right ([], [])) boxes
  let header =
        [ "# Generated by LawSpec. Do not edit."
        , "\"\"\"Typed mailboxes: many senders, one receiver."
        , ""
        , "send never waits; receive takes messages in the order they arrived;"
        , "close refuses later sends. serve(node, name) offers a mailbox to other"
        , "nodes, and connect(node, address) sends to one from another node: such a"
        , "send waits until the mailbox has the message, and it is delivered once."
        , "\"\"\""
        , "from __future__ import annotations"
        , ""
        , "import builtins as _builtins"
        , "import lawspec_runtime as ls"
        , "try:"
        , "    import lawspec_data as data"
        , "    import lawspec_schema as _schema"
        , "    _SCHEMA = data.make_schema()"
        , "except ImportError:"
        , "    _SCHEMA = None"
        , ""
        , "_TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ show (unwords (map snd (reverse table))) ++ ")})"
        , ""
        , ""
        , "def _native(reference, value):"
        , "    return value if reference is None else _SCHEMA.to_native(reference, value)"
        , ""
        , ""
        , "def _logical(reference, value):"
        , "    return value if reference is None else _SCHEMA.from_native(reference, value)" ]
  pure [Artifact "src/lawspec_mailboxes.py" (unlines header ++ concatMap ("\n\n" ++) classes) "generated" "source"]
  where
    reference ty = if requiresSchema datas ty then either (const "None") (D.render (D.Pretty 1000)) (pythonTypeReferenceDoc ty) else "None"
    cls b native wire = unlines $
      [ "class " ++ name ++ ":"
      , "    \"\"\"Mailbox " ++ C.mailboxName b ++ ": messages of " ++ native ++ " from any number of senders,"
      , "    taken by one receiver.\"\"\""
      , ""
      , "    def __init__(self, mailbox: ls.Mailbox | None = None, logical: bool = False):"
      , "        self._mailbox = ls.Mailbox() if mailbox is None else mailbox"
      , "        self._logical = logical"
      , ""
      , "    def send(self, value: " ++ native ++ ") -> None:"
      , "        \"\"\"Queues value without waiting.\"\"\""
      , "        self._mailbox.send(_logical(" ++ ref ++ ", value) if self._logical else value)"
      , ""
      , "    def receive(self, timeout: float | None = None) -> " ++ native ++ ":"
      , "        \"\"\"The next message; waits up to timeout seconds (forever when None),"
      , "        then raises TimeoutError; raises ls.ActorStopped once closed and empty.\"\"\""
      , "        value = self._mailbox.receive(timeout)"
      , "        return _native(" ++ ref ++ ", value) if self._logical else value"
      , ""
      , "    def close(self) -> None:"
      , "        \"\"\"Refuses later sends; messages already sent can still be received.\"\"\""
      , "        self._mailbox.close()" ] ++
      case wire of
        Nothing -> []
        Just d ->
          [ ""
          , "    @staticmethod"
          , "    def serve(node: ls.Node, name: str) -> " ++ name ++ ":"
          , "        \"\"\"A mailbox on node that other nodes send to at <node address>/name.\"\"\""
          , "        return " ++ name ++ "(node.mailbox(name, ls.read_descriptor(" ++ show d ++ ")[0], _TYPES), logical=True)"
          , ""
          , "    @staticmethod"
          , "    def connect(node: ls.Node, address: str, timeout: float = 5.0) -> " ++ name ++ "Sender:"
          , "        \"\"\"Sends to the mailbox served at address on another node.\"\"\""
          , "        return " ++ name ++ "Sender(node.remote_mailbox(address, ls.read_descriptor(" ++ show d ++ ")[0], _TYPES, timeout))"
          , ""
          , ""
          , "class " ++ name ++ "Sender:"
          , "    \"\"\"Sends to mailbox " ++ C.mailboxName b ++ " on another node.\"\"\""
          , ""
          , "    def __init__(self, remote: ls.RemoteMailbox):"
          , "        self._remote = remote"
          , ""
          , "    def send(self, value: " ++ native ++ ") -> None:"
          , "        \"\"\"Sends value; waits until the mailbox has it, or raises ls.Unreachable.\"\"\""
          , "        self._remote.send(_logical(" ++ ref ++ ", value))" ]
      where
        name = mailboxClassName (C.mailboxName b)
        ref = reference (C.mailboxType b)

-- A unit's mailboxes as the module LawSpecMailboxes.<Unit>: for jobs of Job,
-- JobsMailbox with newJobsMailbox, sendJobs (never waits), receiveJobs,
-- receiveJobsWithin (microseconds), closeJobs; serveJobs offers one on a
-- node, and connectJobs / sendJobsTo send to one on another node, waiting
-- until it has the message.
haskell :: Int -> [C.DataDeclaration] -> C.Unit -> Either String [Artifact]
haskell bits datas unit = do
  let boxes = C.unitMailboxes unit
  (table, parts) <- foldl (\acc b -> do
      (t, ps) <- acc
      native <- haskellNativeTypeWithParameters datas [] [] (C.mailboxType b)
      codec <- D.render (D.Pretty 10000) <$> haskellCodecDoc datas "_lawspecSchema" "_lawspecBits" (C.mailboxType b)
      case describe bits datas t (C.mailboxType b) of
        Right (d, t') -> pure (t', ps ++ [(b, paren native, "(" ++ codec ++ " :: Codec.Codec " ++ paren native ++ ")", Just d)])
        Left _ -> pure (t, ps ++ [(b, paren native, "(" ++ codec ++ " :: Codec.Codec " ++ paren native ++ ")", Nothing)])) (Right ([], [])) boxes
  let body = concatMap box parts
      used prefix = prefix `isInfixOf'` body
      header =
        [ "-- Generated by LawSpec. Do not edit."
        , "-- | Typed mailboxes of unit " ++ unitName ++ ": many senders, one receiver."
        , "-- A send never waits; a receive takes messages in the order they arrived;"
        , "-- close refuses later sends. serve offers a mailbox on a node, and connect"
        , "-- sends to one on another node: such a send waits until the mailbox has"
        , "-- the message, and it is delivered once."
        , "module " ++ moduleName ++ " where"
        , ""
        , "import qualified Prelude as P"
        , "import qualified Control.Exception as E"
        , "import qualified LawSpecRuntime as LS"
        , "import qualified LawSpecCodecs as Codec"
        , "import qualified LawSpecSchema as Schema"
        , "import qualified LawSpecDataSchema as DataSchema" ] ++
        [ "import " ++ line | (prefix, line) <- imports, used prefix ] ++
        [ ""
        , "_lawspecSchema :: Schema.Schema"
        , "_lawspecSchema = P.either P.error P.id DataSchema.schema"
        , ""
        , "_lawspecBits :: P.Int"
        , "_lawspecBits = " ++ show bits
        , ""
        , "_lawspecTypes :: LS.DataTable"
        , "_lawspecTypes = [(LS.descriptorName n, f) | f@(LS.DescList (LS.DescAtom \"data\" : n : _)) <- LS.readDescriptor " ++ show (unwords (map snd (reverse table))) ++ "]"
        , ""
        , "_lawspecDescriptor :: P.String -> LS.Descriptor"
        , "_lawspecDescriptor text = case LS.readDescriptor text of"
        , "  form : _ -> form"
        , "  [] -> P.error \"empty descriptor\""
        , ""
        , "_lawspecOr :: P.Either P.String a -> P.IO a"
        , "_lawspecOr = P.either (E.throwIO P.. E.ErrorCall) P.pure" ]
  pure [Artifact ("src/" ++ map (\c -> if c == '.' then '/' else c) moduleName ++ ".hs") (unlines header ++ body) "generated" "source"]
  where
    unitName = C.idText (C.unitId unit)
    moduleName = intercalate "." ("LawSpecMailboxes" : map (concatMap cap . splitOn '_') (splitOn '.' unitName))
    cap s = case s of
      c : cs -> toUpper c : cs
      [] -> []
    splitOn delimiter value = case break (== delimiter) value of
      (a, []) -> [a]
      (a, _ : rest) -> a : splitOn delimiter rest
    paren t = if ' ' `elem` t && take 1 t /= "(" && take 1 t /= "[" then "(" ++ t ++ ")" else t
    isInfixOf' needle hay = any (\i -> take (length needle) (drop i hay) == needle) [0 .. length hay - length needle]
    imports =
      [ ("I.", "qualified Data.Int as I"), ("W.", "qualified Data.Word as W"), ("T.", "qualified Data.Text as T")
      , ("B.", "qualified Data.ByteString as B"), ("C.", "qualified Data.Complex as C")
      , ("Seq.", "qualified Data.Sequence as Seq"), ("Set.", "qualified Data.Set as Set")
      , ("Map.", "qualified Data.Map.Strict as Map"), ("Data.", "qualified LawSpecData as Data")
      , ("Codecs.", "qualified LawSpecDataCodecs as Codecs")
      , ("Collections.", "qualified LawSpecCollectionCodecs as Collections") ]
    box (b, native, codec, wire) = unlines $
      [ ""
      , "-- | Mailbox " ++ n ++ ": messages of " ++ native ++ " from any number of senders, taken by"
      , "-- one receiver."
      , "data " ++ cls ++ " = " ++ cls ++ " (LS.Mailbox " ++ native ++ ") | " ++ cls ++ "Served (LS.Mailbox LS.Scalar)"
      , ""
      , "-- | A mailbox in this process."
      , "new" ++ cls ++ " :: P.IO " ++ cls
      , "new" ++ cls ++ " = " ++ cls ++ " P.<$> LS.newMailbox"
      , ""
      , "-- | Queues a message without waiting."
      , "send" ++ base ++ " :: " ++ cls ++ " -> " ++ native ++ " -> P.IO ()"
      , "send" ++ base ++ " (" ++ cls ++ " box) value = LS.sendMailbox box value"
      , "send" ++ base ++ " (" ++ cls ++ "Served box) value = _lawspecOr (Codec.encode " ++ codec ++ " value) P.>>= LS.sendMailbox box"
      , ""
      , "-- | The next message, waiting for it; throws LS.ActorStopped once closed and empty."
      , "receive" ++ base ++ " :: " ++ cls ++ " -> P.IO " ++ native
      , "receive" ++ base ++ " (" ++ cls ++ " box) = LS.receiveMailbox box"
      , "receive" ++ base ++ " (" ++ cls ++ "Served box) = LS.receiveMailbox box P.>>= (_lawspecOr P.. Codec.decode " ++ codec ++ ")"
      , ""
      , "-- | The next message within the given microseconds, or Nothing."
      , "receive" ++ base ++ "Within :: P.Int -> " ++ cls ++ " -> P.IO (P.Maybe " ++ native ++ ")"
      , "receive" ++ base ++ "Within micros (" ++ cls ++ " box) = LS.receiveMailboxWithin micros box"
      , "receive" ++ base ++ "Within micros (" ++ cls ++ "Served box) = LS.receiveMailboxWithin micros box P.>>= P.traverse (_lawspecOr P.. Codec.decode " ++ codec ++ ")"
      , ""
      , "-- | Refuses later sends; messages already sent can still be received."
      , "close" ++ base ++ " :: " ++ cls ++ " -> P.IO ()"
      , "close" ++ base ++ " (" ++ cls ++ " box) = LS.closeMailbox box"
      , "close" ++ base ++ " (" ++ cls ++ "Served box) = LS.closeMailbox box" ] ++
      case wire of
        Nothing -> []
        Just d ->
          [ ""
          , "-- | A mailbox on a node that other nodes send to at <node address>/name."
          , "serve" ++ base ++ " :: LS.Node -> P.String -> P.IO " ++ cls
          , "serve" ++ base ++ " node name = " ++ cls ++ "Served P.<$> LS.nodeMailbox node name _lawspecTypes (_lawspecDescriptor " ++ show d ++ ")"
          , ""
          , "-- | Sends to a mailbox served on another node."
          , "newtype " ++ cls ++ "Sender = " ++ cls ++ "Sender LS.RemoteMailbox"
          , ""
          , "-- | The mailbox served at an address on another node."
          , "connect" ++ base ++ " :: LS.Node -> P.String -> " ++ cls ++ "Sender"
          , "connect" ++ base ++ " node address = " ++ cls ++ "Sender (LS.remoteMailbox node address _lawspecTypes (_lawspecDescriptor " ++ show d ++ "))"
          , ""
          , "-- | Sends a message; waits until the mailbox has it, or throws LS.Unreachable."
          , "send" ++ base ++ "To :: " ++ cls ++ "Sender -> " ++ native ++ " -> P.IO ()"
          , "send" ++ base ++ "To (" ++ cls ++ "Sender remote) value = _lawspecOr (Codec.encode " ++ codec ++ " value) P.>>= LS.sendRemote remote" ]
      where
        n = C.mailboxName b
        base = cap n
        cls = mailboxClassName n
