module LawSpec.NativeScalarEmit (nativeScalarEmit) where
import LawSpec.Model
import qualified LawSpec.Domain as D
import LawSpec.Scalar
import LawSpec.RuntimeSources
import LawSpec.Compile (typedExpression, normal)
import Data.Aeson (encode)
import qualified Data.Text.Lazy as T
import qualified Data.Text.Lazy.Encoding as T
import Data.List (intercalate, isPrefixOf, isInfixOf)

q :: String -> String
q = T.unpack . T.decodeUtf8 . encode
key :: Type -> String
key (Applied n t) = n ++ " " ++ key t
key t = prettyType t
nativeScalarEmit :: Int -> String -> Unit -> [Expanded] -> Either [Diagnostic] [Artifact]
nativeScalarEmit bits target u allLaws = do
  tests <- concat <$> mapM lawTests (zip [0 :: Int ..] ls)
  wrappers <- concat <$> mapM contractWrapper (contracts u)
  let completeHeader = if hs then replace "spec :: Spec" (wrappers ++ "spec :: Spec") testHeader else if kt then replace "class " (wrappers ++ "class ") testHeader else (if go && not ("rapid.Check" `isInfixOf` tests) then replace "; \"pgregory.net/rapid\"" "" testHeader else testHeader) ++ wrappers
  pure ([Artifact stubPath stub "user" "source", Artifact testPath (completeHeader ++ tests ++ (if hs || go then "" else if kt then "})\n" else "}\n")) "generated" "test"] ++ [Artifact (intercalate "/" parts ++ "/lawspec_runtime.go") (replace "RUNTIME_PACKAGE" (last parts) (runtimeSource "go")) "generated" "source" | go])
  where
    kt = target == "kotlin"
    hs = target == "haskell"
    go = target == "go"
    parts = split (unitName u)
    cls = concatMap cap (splitOn '_' (last parts))
    pkg = intercalate "." (init parts)
    path = intercalate "/" (init parts ++ [cls])
    root = if kt then "kotlin" else "java"
    ext = if kt then ".kt" else ".java"
    stubPath | hs = "src/" ++ intercalate "/" (map hsPart parts) ++ ".hs"
             | go = intercalate "/" parts ++ "/adapter.go"
             | otherwise = "src/main/" ++ root ++ "/" ++ path ++ ext
    testPath | hs = "test/" ++ intercalate "/" (map hsPart parts) ++ "Spec.hs"
             | go = intercalate "/" parts ++ "/lawspec_test.go"
             | otherwise = "src/test/" ++ root ++ "/" ++ path ++ "LawSpecTest" ++ ext
    ls = filter ((== unitName u) . owner) allLaws
    header | go = "package " ++ last parts ++ "\n"
           | hs = "module " ++ intercalate "." (map hsPart parts) ++ " where\nimport LawSpecRuntime (Scalar, IntegerValue, integerValue)\nimport Data.Int\nimport Data.ByteString (ByteString)\nimport Data.Word\nimport Data.Text (Text)\nimport Data.Complex (Complex)\n"
           | otherwise = (if null pkg then "" else "package " ++ pkg ++ ";\n") ++ "import lawspec.runtime.LawSpecRuntime;\n" ++ (if kt then "" else "import lawspec.runtime.LawSpecRuntime.Value;\n")
    valueType = if go then "LawSpecValue" else if hs then "Scalar" else if kt then "LawSpecRuntime.Value" else "Value"
    stub | hs || go = (if hs then "--" else "//") ++ " User-owned LawSpec adapter.\n" ++ header ++ concatMap stubFn (functions u)
         | otherwise = "// User-owned LawSpec adapter.\n" ++ header ++ (if kt then "object " else "public final class ") ++ cls ++ " {\n" ++ concatMap stubFn (functions u) ++ "}\n"
    native t = maybe valueType id (nativeRepresentation target (key t))
    nativeArg t = if t == Named "Integer" then (if hs then "Integer" else if go then "*LawSpecBigInt" else "java.math.BigInteger") else if t == Named "Unit" && not hs then valueType else native t
    stubFn (n,t) = let (args,r) = functionType t; names = ["value" ++ show i | i <- [0 :: Int .. length args-1]] in
      if hs then n ++ " :: " ++ intercalate " -> " (map nativeArg args ++ [native r]) ++ "\n" ++ n ++ concatMap (const " _") args ++ " = error " ++ q (prettyType t) ++ "\n"
      else if go then "// " ++ prettyType t ++ "\nfunc " ++ cap n ++ "(" ++ intercalate ", " [x ++ " " ++ nativeArg a | (x,a) <- zip names args] ++ ") " ++ (if r == Named "Unit" then "" else native r) ++ " { panic(" ++ q n ++ ") }\n"
      else "  // " ++ prettyType t ++ "\n" ++ if kt then "  fun " ++ n ++ "(" ++ intercalate ", " [x ++ ": " ++ nativeArg a | (x,a) <- zip names args] ++ "): " ++ native r ++ " = TODO(" ++ q n ++ ")\n"
      else "  public static " ++ native r ++ " " ++ n ++ "(" ++ intercalate ", " [nativeArg a ++ " " ++ x | (x,a) <- zip names args] ++ ") { throw new UnsupportedOperationException(" ++ q (n ++ " -> " ++ prettyType r) ++ "); }\n"
    testHeader = testHeaderBase ++ (if hs || kt then "" else testHelpers)
    testHeaderBase | go = "// Generated by LawSpec.\n" ++ header ++ "import (\"testing\"; \"pgregory.net/rapid\")\n"
               | hs = "-- Generated by LawSpec.\nmodule " ++ intercalate "." (map hsPart parts) ++ "Spec (spec) where\nimport Test.Hspec\nimport Control.Exception (SomeException, catch, displayException)\nimport Test.Hspec.Hedgehog (hedgehog, modifyMaxSuccess)\nimport Hedgehog (forAll, evalIO, footnote)\nimport qualified Hedgehog.Gen as Gen\nimport qualified Hedgehog.Range as Range\nimport LawSpecRuntime (Scalar(..))\nimport qualified LawSpecRuntime as LS\nimport qualified " ++ intercalate "." (map hsPart parts) ++ " as Impl\n" ++ testHelpers ++ "spec :: Spec\nspec = do\n"
               | otherwise = "// Generated by LawSpec.\n" ++ header ++ if kt then "import io.kotest.core.spec.style.StringSpec\nimport io.kotest.property.checkAll\nimport io.kotest.property.Arb\nimport io.kotest.property.arbitrary.int\n" ++ testHelpers ++ "class " ++ cls ++ "LawSpecTest : StringSpec({\n" else "import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertTrue;\nimport java.util.*;\nimport org.jetbrains.jetCheck.Generator;\nimport org.jetbrains.jetCheck.PropertyChecker;\npublic final class " ++ cls ++ "LawSpecTest {\n"
    testHelpers
      | hs = "_lawspecAssert :: String -> Scalar -> Scalar -> IO ()\n_lawspecAssert context actual expected = catch action handler\n  where\n    action = if LS.equal actual expected then pure () else expectationFailure (context ++ \" | actual=\" ++ show actual ++ \" expected=\" ++ show expected)\n    handler :: SomeException -> IO ()\n    handler e = expectationFailure (context ++ \" | \" ++ displayException e)\n"
      | go = "func _lawspecAssert(t interface { Fatalf(string, ...any) }, context string, actual, expected func() LawSpecValue) { lsAssert(context,actual,expected) }\n"
      | kt = "private fun _lawspecAssert(context: String, actual: () -> LawSpecRuntime.Value, expected: () -> LawSpecRuntime.Value) { try { val a = actual(); val b = expected(); check(LawSpecRuntime.equal(a,b)) { \"$context | actual=$a expected=$b\" } } catch(error: Exception) { throw AssertionError(context, error) } }\n"
      | otherwise = "  private static void _lawspecAssert(String context, java.util.function.Supplier<Value> actual, java.util.function.Supplier<Value> expected) { try { var a = actual.get(); var b = expected.get(); assertTrue(LawSpecRuntime.equal(a,b), context + \" | actual=\" + a + \" expected=\" + b); } catch(RuntimeException error) { throw new AssertionError(context, error); } }\n"
    quote = if kt then concatMap (\c -> if c == '$' then "\\$" else [c]) . q else q
    call n args | hs = "(LS." ++ n ++ concatMap (\a -> " (" ++ a ++ ")") args ++ ")"
                | go = "ls" ++ cap n ++ "(" ++ intercalate ", " args ++ ")"
                | otherwise = "LawSpecRuntime." ++ n ++ "(" ++ intercalate ", " args ++ ")"
    arr xs | hs = "[" ++ intercalate ", " xs ++ "]"
           | go = "[]LawSpecValue{" ++ intercalate ", " xs ++ "}"
           | otherwise = (if kt then "arrayOf(" else "new Value[]{") ++ intercalate ", " xs ++ (if kt then ")" else "}")
    scalar s | hs = "(" ++ show s ++ ")"
             | otherwise = case s of
      SInteger t n -> call "integer" [q t,q (show n)]
      SBool b -> call "bool" [if b then "true" else "false"]
      SDecimal c e -> call "decimal" [q (show c),q (show e)]
      SRational n d -> call "rational" [q (show n),q (show d)]
      SFloat t bits' -> call "floating" [q t,q bits']
      SComplex t r i -> call "complex" [q t,scalar r,scalar i]
      SCharacter t c -> call "character" [q t,show c]
      SSequence t xs -> call "sequence" [q t,(if go then "[]int{" else if kt then "intArrayOf(" else "new int[]{") ++ intercalate "," (map show xs) ++ (if kt then ")" else "}")]
      SSymbol i d -> call "symbol" [quote i,quote d,"symbols"]
      SAbsent t -> call "absent" [q t]
      SPresent t v -> call "present" [q t,if go then maybe "nil" (\x -> "lsPointer(" ++ scalar x ++ ")") v else maybe "null" scalar v]
    convert t v = call "convert" [q (key t),v,show bits]
    typed env e = either (Left . pure . (\m -> Diagnostic "typed-ir" m Nothing)) Right (typedExpression bits env (normal e))
    render (TypedExpr t e cs conversion) = case (e,cs) of
      (Var n,_) -> if n `elem` map fst (functions u) then (if hs then "Impl." ++ n else if go then cap n else cls ++ "." ++ n) else n
      (DecimalNumber c p,_) -> convert t (scalar (SDecimal c p))
      (Number n,_) -> convert t (scalar (SInteger "BigInt" n))
      (ScalarLit s,_) -> convert t (scalar s)
      (BoolLit b,_) -> scalar (SBool b)
      (StringLit s,_) -> scalar (textScalar s)
      (Annotate _ _,[a]) -> convert t (render a)
      (Binary op _ _,[a,b]) | op `elem` ["&&","||"] -> call "bool" ["(" ++ call "truth" [render a] ++ " " ++ op ++ " " ++ call "truth" [render b] ++ ")"]
      (Unary "!" _,[a]) -> call "bool" [(if hs then "not (" else "!(") ++ call "truth" [render a] ++ ")"]
      (Binary op _ _,[a,b]) -> call "binary" [q op,render a,render b]
      (Unary "-" _,[a]) -> call "helper" [q "negate",arr [render a],show bits]
      (Apply _ _,_) | (Var n,_) <- application e, "prelude." `isPrefixOf` n -> call "helper" [q (drop 8 n),arr (map render cs),show bits]
      (Apply _ _,_) | (Var n,_) <- application e, n `elem` map contractName (contracts u) ->
        let (_,args) = typedApplication (TypedExpr t e cs conversion)
            values = [convert (bridgeType a) (render a) | a <- args]
        in if hs then "(_lawspec_call_" ++ n ++ concatMap (\v -> " (" ++ v ++ ")") values ++ ")" else "_lawspec_call_" ++ n ++ "(" ++ intercalate ", " ("symbols":values) ++ ")"
      (Apply _ _,_) ->
        let (callee,args) = typedApplication (TypedExpr t e cs conversion)
            invoke = if hs then "(" ++ render callee ++ concatMap (\a -> " (" ++ adapterArg a ++ ")") args ++ ")" else render callee ++ "(" ++ intercalate ", " [adapterArg a | a <- args] ++ ")"
        in if t == Named "Unit" && not hs then
          if go then "func() LawSpecValue { " ++ invoke ++ "; return lsAbsent(\"Unit\") }()"
          else if kt then "run { " ++ invoke ++ "; LawSpecRuntime.absent(\"Unit\") }" else "LawSpecRuntime.unit(() -> " ++ invoke ++ ")"
          else call "fromNative" [q (key t),invoke,show bits]
      _ -> error ("unrenderable expression " ++ show e)
    adapterArg a | bridgeType a == Named "Unit" && not hs = render a
    adapterArg a = case nativeRepresentation target (key (bridgeType a)) of
      Nothing -> if go then "lsClone(" ++ convert (bridgeType a) (render a) ++ ")" else convert (bridgeType a) (render a)
      Just _ -> let nativeType = nativeArg (bridgeType a); converted = call "toNative" [q (key (bridgeType a)),render a,show bits] in
        if hs then converted else if go then converted ++ ".(" ++ nativeType ++ ")" else if kt then "(" ++ converted ++ " as " ++ nativeType ++ ")" else "((" ++ nativeType ++ ") " ++ converted ++ ")"
    envFor e = functions u ++ [(inputId i,inputType i) | i <- inputs e]
    assign n v | hs = "    let " ++ n ++ " = " ++ v ++ "\n"
               | go = "    " ++ n ++ " := " ++ v ++ "; _ = " ++ n ++ "\n"
               | otherwise = "    " ++ (if kt then "val " else "var ") ++ n ++ " = " ++ v ++ ";\n"
    code env indent context a = case a of
      AssertAll as -> concat <$> mapM (code env indent context) as
      AssertImplies g body -> do
        gt <- typed env g
        rest <- code env (indent ++ "  ") context body
        pure (if hs then indent ++ "if " ++ call "truth" [render gt] ++ " then do\n" ++ rest ++ indent ++ "else pure ()\n" else indent ++ "if (" ++ call "truth" [render gt] ++ ") {\n" ++ rest ++ indent ++ "}\n")
      AssertEqual a b -> do
        at <- typed env a; bt <- typed env b
        let av = if literalLike a then convert (expressionType bt) (render at) else render at
            bv = if literalLike b then convert (expressionType at) (render bt) else render bt
        pure $ indent ++ if hs then "_lawspecAssert " ++ quote context ++ " (" ++ av ++ ") (" ++ bv ++ ")\n"
          else if go then "_lawspecAssert(t, " ++ quote context ++ ", func() LawSpecValue { return " ++ av ++ " }, func() LawSpecValue { return " ++ bv ++ " })\n"
          else if kt then "_lawspecAssert(" ++ quote context ++ ", { " ++ av ++ " }, { " ++ bv ++ " })\n"
          else "_lawspecAssert(" ++ quote context ++ ", () -> " ++ av ++ ", () -> " ++ bv ++ ");\n"
    literalLike (Number _) = True
    literalLike (DecimalNumber _ _) = True
    literalLike (ScalarLit s) = scalarName s `elem` ["Null","Undefined","Nullable","Optional"]
    literalLike _ = False
    block n body | hs = "  it " ++ q n ++ " $ do\n" ++ body
                 | go = "func Test" ++ cap n ++ "(t *testing.T) {\n    symbols := map[string]*lawSpecSymbol{}; _ = symbols\n" ++ body ++ "}\n"
                 | kt = "  " ++ q n ++ " {\n    val symbols = mutableMapOf<String, Any>();\n" ++ body ++ "  }\n"
                 | otherwise = "  @Test " ++ (if kt then "fun " ++ n ++ "()" else "void " ++ n ++ "()") ++ " {\n" ++ (if kt then "    val symbols = mutableMapOf<String, Any>();\n" else "    var symbols = new HashMap<String,Object>();\n") ++ body ++ "  }\n"
    boundaries (Named n) = scalarBoundaries bits n
    boundaries (Applied n t) = SPresent n Nothing : map (SPresent n . Just) (boundaries t)
    boundaries _ = []
    lawTests (i,e) = do
      let env = envFor e; label = owner e ++ "::" ++ name e; fn = "law" ++ show i
      exs <- concat <$> mapM (\(j,ex) -> do
        assignments <- mapM (\(n,v) -> do
          let t = maybe (Named "BigInt") id (lookup n [(inputName inp,inputType inp) | inp <- inputs e])
              variable = maybe n id (lookup n [(inputName inp,inputId inp) | inp <- inputs e])
          value <- typed env (Annotate (literalExpr v) t)
          pure (assign variable (render value))) (bindings ex)
        expectedChecks <- concat <$> mapM (\c -> code env "    " (label ++ " example " ++ exampleName ex) (AssertEqual (replaceExprVars [(inputName inp,Var (inputId inp)) | inp <- inputs e] (actual c)) (literalExpr (expected c)))) (expectations ex)
        lawCheck <- code env "    " label (assertion e)
        pure (block (fn ++ "Example" ++ show j) (concat assignments ++ expectedChecks ++ lawCheck))) (zip [0 :: Int ..] (examples (original e)))
      finite <- either failure pure (D.finiteTuples bits (generation e) (inputs e))
      cases' <- maybe (either failure pure (D.boundaryTuples bits e)) pure finite
      boundariesTests <- concat <$> mapM (\(j,vs) -> do
        check <- code env "    " (label ++ " boundary " ++ show j) (assertion e)
        pure (block (fn ++ "Boundary" ++ show j) (concat [assign (inputId inp) (convert (inputType inp) (scalar v)) | (inp,v) <- zip (inputs e) vs] ++ check))) (zip [0 :: Int ..] cases')
      propertyCheck <- code env "    " (label ++ " property") (assertion e)
      let assignments = concat [assign (inputId inp) (call "sample" [q (key (inputType inp)),if go then "int(seed) + " ++ show j else if hs then "seed + " ++ show j else "seed + " ++ show j,show bits]) | (j,inp) <- zip [0 :: Int ..] (inputs e)]
          propertyBody = assignments ++ propertyCheck
          propertyTest
            | hs = "  it " ++ q (label ++ " property") ++ " $ hedgehog $ do\n    seed <- forAll (Gen.int (Range.linear (-1000000) 1000000))\n    footnote " ++ q label ++ "\n    evalIO $ do\n" ++ unlines ["  " ++ l | l <- lines propertyBody]
            | go = "func Test" ++ cap fn ++ "Property(t *testing.T) { rapid.Check(t, func(t *rapid.T) {\n    seed := rapid.Int32().Draw(t, \"seed\"); _ = seed\n    symbols := map[string]*lawSpecSymbol{}; _ = symbols\n" ++ propertyBody ++ "}) }\n"
            | kt = "  " ++ q (label ++ " property") ++ " { checkAll(Arb.int()) { seed ->\n    val symbols = mutableMapOf<String, Any>();\n" ++ propertyBody ++ "  } }\n"
            | otherwise = "  @Test void " ++ fn ++ "Property() { PropertyChecker.forAll(Generator.integers(), seed -> {\n    var symbols = new HashMap<String,Object>();\n" ++ propertyBody ++ "    return true;\n  }); }\n"
      refined <- refinedProperty fn label e propertyCheck
      pure (exs ++ boundariesTests ++ if maybe False (const True) finite then "" else if any (not . null . inputRefinements) (inputs e) || propertyKind e == "contract" then refined else propertyTest)
    failure m = Left [Diagnostic "refinement-generation" m Nothing]
    conjunction [] = if hs then "True" else "true"
    conjunction xs = intercalate " && " ["(" ++ x ++ ")" | x <- xs]
    contractWrapper c = do
      let mapping = zip (map fst (contractArguments c) ++ [fst (contractResult c)]) ["_arg" ++ show j | j <- [0::Int ..]]
          args = [(maybe n id (lookup n mapping),baseType t) | (n,t) <- contractArguments c]
          rn = maybe "_result" id (lookup (fst (contractResult c)) mapping)
          rt = baseType (snd (contractResult c))
          env = args ++ [(rn,rt)]
          replaced = replaceExprVars [(n,Var v) | (n,v) <- mapping]
          invoke = (if hs then "Impl." else if go then "" else cls ++ ".") ++ (if go then cap (contractName c) else contractName c) ++
            (if hs then concatMap (\(n,t) -> " (" ++ adapterArg (TypedExpr t (Var n) [] Nothing) ++ ")") args
             else "(" ++ intercalate ", " [adapterArg (TypedExpr t (Var n) [] Nothing) | (n,t) <- args] ++ ")")
          result = if rt == Named "Unit" && not hs then (if go then "func() LawSpecValue { " ++ invoke ++ "; return lsAbsent(\"Unit\") }()" else if kt then "run { " ++ invoke ++ "; LawSpecRuntime.absent(\"Unit\") }" else "LawSpecRuntime.unit(() -> " ++ invoke ++ ")") else call "fromNative" [q (key rt),invoke,show bits]
          context stage ps = contractName c ++ " " ++ stage ++ ": " ++ intercalate " && " (map prettyExpr ps)
          symbolParam = if go then "symbols map[string]*lawSpecSymbol" else if kt then "symbols: MutableMap<String, Any>" else "Map<String,Object> symbols"
          params = symbolParam:[if go then n ++ " LawSpecValue" else if kt then n ++ ": LawSpecRuntime.Value" else "Value " ++ n | (n,_) <- args]
      pre <- mapM (fmap (\v -> call "truth" [render v]) . typed env . replaced) (contractPreconditions c)
      post <- mapM (fmap (\v -> call "truth" [render v]) . typed env . replaced) (contractPostconditions c)
      let preContext = context "precondition" (contractPreconditions c); postContext = context "postcondition" (contractPostconditions c)
      pure $ if hs then "_lawspec_call_" ++ contractName c ++ " :: " ++ intercalate " -> " (replicate (length args+1) "Scalar") ++ "\n_lawspec_call_" ++ contractName c ++ concatMap ((" " ++) . fst) args ++ " =\n  LS.contract " ++ quote preContext ++ " (" ++ conjunction pre ++ ") $\n    let " ++ rn ++ " = " ++ result ++ "\n    in " ++ rn ++ " `seq` LS.contract " ++ quote postContext ++ " (" ++ conjunction post ++ ") " ++ rn ++ "\n"
        else (if go then "func " else if kt then "private fun " else "  private static Value ") ++ "_lawspec_call_" ++ contractName c ++ "(" ++ intercalate ", " params ++ ")" ++ (if go then " LawSpecValue" else if kt then ": LawSpecRuntime.Value" else "") ++ " {\n" ++
          "    " ++ call "requireContract" [conjunction pre,quote preContext] ++ ";\n" ++ assign rn result ++ "    " ++ call "requireContract" [conjunction post,quote postContext] ++ ";\n    return " ++ rn ++ ";\n  }\n"
    domainCode e (index,plan) = do
      let inp=domainInput plan; env=envFor e; prior=take index (inputs e)
          bindings' xs = concat [if hs then inputId i ++ " = _values !! " ++ show j ++ "; " else if go then inputId i ++ " := _values[" ++ show j ++ "]; _ = " ++ inputId i ++ "; " else if kt then "val " ++ inputId i ++ " = _values[" ++ show j ++ "]; " else "var " ++ inputId i ++ " = _values.get(" ++ show j ++ "); " | (j,i) <- zip [0::Int ..] xs]
          lambda xs seed value = if hs then "(\\_values" ++ (if seed then " _seed" else "") ++ " -> " ++ (if null xs then "" else "let { " ++ bindings' xs ++ "} in ") ++ value ++ ")"
            else if go then "func(_values []LawSpecValue" ++ (if seed then ", _seed int" else "") ++ ") " ++ (if seed then "[]LawSpecValue" else "bool") ++ " { " ++ bindings' xs ++ "return " ++ value ++ " }"
            else if kt then "{ _values" ++ (if seed then ", _seed" else "") ++ " -> " ++ bindings' xs ++ value ++ " }"
            else "(_values" ++ (if seed then ", _seed" else "") ++ ") -> { " ++ bindings' xs ++ "return " ++ value ++ "; }"
      bs <- mapM (\(op,v) -> do value <- render <$> typed env v; pure (if hs then "(" ++ q op ++ "," ++ value ++ ")" else if go then "{" ++ q op ++ "," ++ value ++ "}" else (if kt then "LawSpecRuntime.Bound(" else "new LawSpecRuntime.Bound(") ++ q op ++ "," ++ value ++ ")")) (domainBounds plan)
      hints <- mapM (fmap render . typed env) (D.domainHints inp)
      ps <- mapM (fmap (\v -> call "truth" [render v]) . typed env) (inputRefinements inp)
      let restrictions = (if hs then "[" else if go then "[]lawSpecBound{" else if kt then "arrayOf(" else "new LawSpecRuntime.Bound[]{") ++ intercalate "," bs ++ (if hs then "]" else if kt then ")" else "}")
          candidates = call "domainCandidates" [q (key (inputType inp)),"_seed",show bits,restrictions,arr (map scalar (D.boundaries bits (inputType inp)) ++ hints)]
      pure $ if hs then "LS.Domain " ++ lambda prior True candidates ++ " " ++ lambda (prior++[inp]) False (conjunction ps)
        else (if go then "lawSpecDomain{" else if kt then "LawSpecRuntime.Domain(" else "new LawSpecRuntime.Domain(") ++ lambda prior True candidates ++ ", " ++ lambda (prior++[inp]) False (conjunction ps) ++ (if go then "}" else ")")
    refinedProperty fn label e check = do
      ds <- mapM (domainCode e) (zip [0::Int ..] (generationPlan e))
      let cfg=generation e
          domains = (if hs then "[" else if go then "[]lawSpecDomain{" else if kt then "arrayOf(" else "new LawSpecRuntime.Domain[]{") ++ intercalate ", " ds ++ (if hs then "]" else if kt then ")" else "}")
          binds = concat [assign (inputId inp) (if hs then "_values !! " ++ show j else if go || kt then "_values[" ++ show j ++ "]" else "_values.get(" ++ show j ++ ")") | (j,inp) <- zip [0::Int ..] (inputs e)]
          callback = if hs then "_check"
                     else if go then "func(_values []LawSpecValue) {\n" ++ binds ++ check ++ "  }"
                     else if kt then "{ _values ->\n" ++ binds ++ check ++ "  }"
                     else "_values -> {\n" ++ binds ++ check ++ "  }"
          invocation = call "refinedCase" [domains,"seed",show (maxAttempts cfg),show (maxShrinks cfg),callback,quote (label ++ " | " ++ intercalate "; " (map prettyExpr (concatMap inputRefinements (inputs e))))]
      pure $ if hs then "  modifyMaxSuccess (const " ++ show (cases cfg) ++ ") $ it " ++ q (label ++ " property") ++ " $ hedgehog $ do\n    seed <- forAll (Gen.int (Range.linear 0 2147483647))\n    footnote " ++ q label ++ "\n    let _check _values = do\n" ++ unlines ["      " ++ line | line <- lines (binds ++ check)] ++ "    evalIO $ " ++ invocation ++ "\n"
        else if go then "func Test" ++ cap fn ++ "Property(t *testing.T) {\n    defer func(){if err:=recover();err!=nil{t.Fatalf(\"%v\",err)}}()\n    for seed := 0; seed < " ++ show (cases cfg) ++ "; seed++ {\n    symbols := map[string]*lawSpecSymbol{}; _ = symbols\n    " ++ invocation ++ "\n  }\n}\n"
        else if kt then "  " ++ q (label ++ " property") ++ " { checkAll(" ++ show (cases cfg) ++ ", Arb.int()) { seed ->\n    val symbols = mutableMapOf<String, Any>();\n    " ++ invocation ++ "\n  } }\n"
        else "  @Test void " ++ fn ++ "Property() { PropertyChecker.customized().withIterationCount(" ++ show (cases cfg) ++ ").forAll(Generator.integers(), seed -> {\n    var symbols = new HashMap<String,Object>();\n    " ++ invocation ++ ";\n    return true;\n  }); }\n"
    hsPart = concatMap cap . splitOn '_'
    split = splitOn '.'
    splitOn c s = case break (== c) s of (a,[]) -> [a]; (a,_:b) -> a:splitOn c b
    cap [] = []
    cap (c:cs) = (if c >= 'a' && c <= 'z' then toEnum (fromEnum c - 32) else c):cs

application :: Expr -> (Expr,[Expr])
application (Apply f x) = let (n,args) = application f in (n,args ++ [x])
application e = (e,[])
typedApplication :: TypedExpr -> (TypedExpr,[TypedExpr])
typedApplication (TypedExpr _ (Apply _ _) [f,x] _) = let (n,args) = typedApplication f in (n,args ++ [x])
typedApplication e = (e,[])

replace :: String -> String -> String -> String
replace old new text | old `isPrefixOf` text = new ++ replace old new (drop (length old) text)
replace _ _ [] = []
replace old new (c:cs) = c:replace old new cs
