module LawSpec.Prelude (preludeSource) where
import LawSpec.Model
preludeSource :: Source
preludeSource = Source "<prelude>" $ unlines
  [ "unit prelude"
  , ""
  , "law `left inverse`"
  , "  (f :: b -> a)"
  , "  (g :: a -> b)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      (f . g) x = x"
  , "  end"
  , ""
  , "  description is"
  , "    \"applying {g} to a value and then applying {f} yields the original value\""
  , "  end"
  , ""
  , "  rationale is"
  , "    \"{g} must preserve enough information for {f} to recover the original value\""
  , "  end"
  , "end"
  , ""
  , "law `round trip identity is preserved`"
  , "  (a :: x -> y)"
  , "  (b :: y -> x)"
  , "requires"
  , "  Eq x"
  , "is"
  , "  definition is"
  , "    `left inverse` b a"
  , "  end"
  , ""
  , "  description is"
  , "    \"applying {a} to a value and then applying {b} yields the original value\""
  , "  end"
  , ""
  , "  rationale is"
  , "    \"{a} must preserve enough information for {b} to recover the original value\""
  , "  end"
  , "end"
  , ""
  , "law `equivalent`"
  , "  (f :: a -> b)"
  , "  (g :: a -> b)"
  , "requires"
  , "  Eq b"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f x = g x"
  , "  end"
  , ""
  , "  description is"
  , "    \"{f} and {g} produce the same result for every input\""
  , "  end"
  , ""
  , "  rationale is"
  , "    \"{f} and {g} are alternative implementations of the same behavior\""
  , "  end"
  , "end"
  , ""
  , "law `idempotent`"
  , "  (f :: a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      (f . f) x = f x"
  , "  end"
  , "end"
  , ""
  , "law `satisfies`"
  , "  (predicate :: a -> Bool)"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) . predicate x"
  , "  end"
  , "  description is"
  , "    \"{predicate} is true for every input\""
  , "  end"
  , "end"
  , ""
  , "law `left inverse when`"
  , "  (predicate :: a -> Bool)"
  , "  (f :: b -> a)"
  , "  (g :: a -> b)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) . predicate x implies f (g x) = x"
  , "  end"
  , "  description is"
  , "    \"When {predicate} holds, applying {g} then {f} recovers the input\""
  , "  end"
  , "end"
  , ""
  , "law `commutative`"
  , "  (f :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) ."
  , "      f x y = f y x"
  , "  end"
  , "  description is"
  , "    \"Swapping the inputs to {f} preserves the result\""
  , "  end"
  , "end"
  , ""
  , "law `associative`"
  , "  (f :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) (z :: a) ."
  , "      f (f x y) z = f x (f y z)"
  , "  end"
  , "  description is"
  , "    \"Regrouping applications of {f} preserves the result\""
  , "  end"
  , "end"
  , ""
  , "law `left identity`"
  , "  (f :: a -> a -> a)"
  , "  (e :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f e x = x"
  , "  end"
  , "  description is"
  , "    \"{e} is left identity for {f}\""
  , "  end"
  , "end"
  , ""
  , "law `right identity`"
  , "  (f :: a -> a -> a)"
  , "  (e :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f x e = x"
  , "  end"
  , "  description is"
  , "    \"{e} is right identity for {f}\""
  , "  end"
  , "end"
  , ""
  , "law `identity`"
  , "  (f :: a -> a -> a)"
  , "  (e :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f e x = x and f x e = x"
  , "  end"
  , "  description is"
  , "    \"{e} is a two-sided identity for {f}\""
  , "  end"
  , "end"
  , ""
  , "law `left absorbing element`"
  , "  (f :: a -> a -> a)"
  , "  (zero :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f zero x = zero"
  , "  end"
  , "  description is"
  , "    \"{zero} absorbs left inputs of {f}\""
  , "  end"
  , "end"
  , ""
  , "law `right absorbing element`"
  , "  (f :: a -> a -> a)"
  , "  (zero :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f x zero = zero"
  , "  end"
  , "  description is"
  , "    \"{zero} absorbs right inputs of {f}\""
  , "  end"
  , "end"
  , ""
  , "law `absorbing element`"
  , "  (f :: a -> a -> a)"
  , "  (zero :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f zero x = zero and f x zero = zero"
  , "  end"
  , "  description is"
  , "    \"{zero} absorbs both inputs of {f}\""
  , "  end"
  , "end"
  , ""
  , "law `left distributive`"
  , "  (f :: a -> a -> a)"
  , "  (g :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) (z :: a) ."
  , "      f x (g y z) = g (f x y) (f x z)"
  , "  end"
  , "  description is"
  , "    \"{f} distributes over {g} on left sides\""
  , "  end"
  , "end"
  , ""
  , "law `right distributive`"
  , "  (f :: a -> a -> a)"
  , "  (g :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) (z :: a) ."
  , "      f (g x y) z = g (f x z) (f y z)"
  , "  end"
  , "  description is"
  , "    \"{f} distributes over {g} on right sides\""
  , "  end"
  , "end"
  , ""
  , "law `distributive`"
  , "  (f :: a -> a -> a)"
  , "  (g :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) (z :: a) ."
  , "      f x (g y z) = g (f x y) (f x z) and f (g x y) z = g (f x z) (f y z)"
  , "  end"
  , "  description is"
  , "    \"{f} distributes over {g} on both sides\""
  , "  end"
  , "end"
  , ""
  , "law `idempotent operation`"
  , "  (f :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f x x = x"
  , "  end"
  , "  description is"
  , "    \"Combining a value with itself using {f} leaves it unchanged\""
  , "  end"
  , "end"
  , ""
  , "law `left inverse element`"
  , "  (f :: a -> a -> a)"
  , "  (inverse :: a -> a)"
  , "  (e :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f (inverse x) x = e"
  , "  end"
  , "  description is"
  , "    \"{inverse} supplies left inverses for {f} with identity {e}\""
  , "  end"
  , "end"
  , ""
  , "law `right inverse element`"
  , "  (f :: a -> a -> a)"
  , "  (inverse :: a -> a)"
  , "  (e :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f x (inverse x) = e"
  , "  end"
  , "  description is"
  , "    \"{inverse} supplies right inverses for {f} with identity {e}\""
  , "  end"
  , "end"
  , ""
  , "law `invertible`"
  , "  (f :: a -> a -> a)"
  , "  (inverse :: a -> a)"
  , "  (e :: a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f (inverse x) x = e and f x (inverse x) = e"
  , "  end"
  , "  description is"
  , "    \"{inverse} supplies two-sided inverses for {f} with identity {e}\""
  , "  end"
  , "end"
  , ""
  , "law `left division`"
  , "  (f :: a -> a -> a)"
  , "  (divideLeft :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) ."
  , "      f x (divideLeft x y) = y and divideLeft x (f x y) = y"
  , "  end"
  , "  description is"
  , "    \"{divideLeft} uniquely solves {f} x result = y\""
  , "  end"
  , "end"
  , ""
  , "law `right division`"
  , "  (f :: a -> a -> a)"
  , "  (divideRight :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) ."
  , "      f (divideRight x y) y = x and divideRight (f x y) y = x"
  , "  end"
  , "  description is"
  , "    \"{divideRight} uniquely solves {f} result y = x\""
  , "  end"
  , "end"
  , ""
  , "law `divisible`"
  , "  (f :: a -> a -> a)"
  , "  (divideLeft :: a -> a -> a)"
  , "  (divideRight :: a -> a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) (y :: a) ."
  , "      f x (divideLeft x y) = y and divideLeft x (f x y) = y and f (divideRight x y) y = x and divideRight (f x y) y = x"
  , "  end"
  , "  description is"
  , "    \"{divideLeft} and {divideRight} recover either input of {f}\""
  , "  end"
  , "end"
  , ""
  , "law `involution`"
  , "  (f :: a -> a)"
  , "requires"
  , "  Eq a"
  , "is"
  , "  definition is"
  , "    `for all` (x :: a) ."
  , "      f (f x) = x"
  , "  end"
  , "  description is"
  , "    \"Applying {f} twice restores the original input\""
  , "  end"
  , "end"
  ]
