-- Checked application bridges reuse the framework-independent Python schema.
module LawSpec.PythonNativeBinding (emitBindings) where

import Control.Monad (forM, unless)
import Data.Char (toLower)
import Data.List (intercalate, nub, isPrefixOf, isSuffixOf)
import qualified LawSpec.Core as C
import LawSpec.Common
import LawSpec.Backend (unitName)
import LawSpec.Testing
import LawSpec.NativeBinding
import LawSpec.NativeRequest
import qualified LawSpec.PythonTypes as P
import qualified LawSpec.PythonData as Data
import qualified LawSpec.PythonDefinitions as Definitions
import qualified LawSpec.CoreScalarEmit as Scalar
import LawSpec.RuntimeSources (runtimeSource)
import qualified LawSpec.Code.Doc as D

emitBindings :: Bool -> BindingPlan -> Plan -> [Artifact] -> Either String [Artifact]
emitBindings minify bindings plan files = do
  unless (bindingRustCrate bindings == Nothing)
    (Left "rustCrate is only valid for Rust native bindings")
  unless (null mappings || not (null functions) || not (null generators))
    (Left "native type mappings require a function or generator binding")
  let refs = nub (map snd functions ++
        [ref | mapping <- mappings, Just hook <- [resolvedCodec mapping],
          ref <- [resolvedNativeType mapping, codecToNative hook, codecFromNative hook]] ++
        [resolvedNativeConstructor constructor | mapping <- mappings,
          constructor <- resolvedConstructors mapping])
  imports <- forM (zip [0::Int ..] refs) $ \(i,NativeRef parts) -> do
    unless (length parts >= 2) (Left "Python native references require a module and attribute")
    mapM_ P.identifier parts
    pure (D.text ("from " ++ intercalate "." (init parts) ++ " import " ++ last parts ++
      " as _native_" ++ show i))
  let reference ref = D.text ("_native_" ++ show (length (takeWhile (/=ref) refs)))
  entries <- forM (concatMap resolvedConstructors mappings) $ \constructor -> do
    mapM_ (P.identifier . snd) (resolvedFields constructor)
    pure (D.text (P.q (C.idText (C.constructorId (resolvedConstructor constructor)))) <>
      D.text ": " <> D.delimit 4 "(" ")"
        [reference (resolvedNativeConstructor constructor),
         P.array [D.text (P.q name) | (_,name) <- resolvedFields constructor]])
  let hooks = [D.text (P.q (C.idText (C.dataId (resolvedDeclaration mapping)))) <>
        D.text ": " <> D.delimit 4 "(" ")"
          (map reference [resolvedNativeType mapping, codecToNative hook, codecFromNative hook]) |
        mapping <- mappings, Just hook <- [resolvedCodec mapping]]
      common = map D.text
        ["# Generated by LawSpec. Do not edit.", "import builtins as _builtins",
         "import lawspec_runtime as ls",
         "import lawspec_data as data", "import lawspec_schema as _schema"]
      schemas = [D.text "_canonical = data.make_schema()",
        D.text "_native = _canonical.with_native_bindings" <>
          D.delimit 4 "(" ")" [D.delimit 4 "{" "}" entries, D.delimit 4 "{" "}" hooks]]
      support = Artifact "src/lawspec_native.py"
        (render (D.joinWith D.hardline (common ++ imports) <>
          D.hardline <> D.hardline <> D.joinWith D.hardline schemas)) "generated" "source"
  bridges <- fmap concat $ forM (plannedUnits plan) $ \planned -> do
    let unit = plannedUnit planned
        definitions = map (C.declarationId . C.definitionDeclaration) (C.unitDefinitions unit)
        adapters = [d | d <- C.unitDeclarations unit, C.declarationId d `notElem` definitions]
        bound d = lookup (C.declarationId d) [(C.declarationId decl,ref) | (decl,ref) <- functions]
    if not (any (maybe False (const True) . bound) adapters) then pure [] else do
      unless (all (maybe False (const True) . bound) adapters)
        (Left "a Python bound unit must map every adapter")
      bodies <- forM adapters $ \decl -> do
        let (args,result) = C.functionType (C.declarationType decl)
        argTypes <- mapM (Data.pythonDataTypeDoc (planDataDeclarations plan)) args
        resultType <- Data.pythonDataTypeDoc (planDataDeclarations plan) result
        refs' <- mapM Data.pythonTypeReferenceDoc args
        resultRef <- Data.pythonTypeReferenceDoc result
        let values = [D.text ("value" ++ show i) | i <- [0::Int ..length args-1]]
            bits = D.text (show (planMachineBits plan))
            convert schema method ref value = P.invoke (schema ++ "." ++ method) [ref,value,bits,D.text "symbols"]
            converted = [convert "bridge._native" "to_native" ty
              (convert "bridge._canonical" "from_native" ty value) | (ty,value) <- zip refs' values]
            Just ref = bound decl
            application = reference ref <> D.delimitTrailing 4 "(" ")" converted
            resultBody = if result == C.scalarType "Unit"
              then [application, D.text "return None"]
              else [D.text "result = " <> application,
                D.text "return " <> convert "bridge._canonical" "to_native" resultRef
                  (convert "bridge._native" "from_native" resultRef (D.text "result"))]
            signature = D.text ("def " ++ C.declarationName decl) <>
              D.delimitTrailing 4 "(" ")" [value <> D.text ": " <> ty | (value,ty) <- zip values argTypes] <>
              D.text " -> " <> (if result == C.scalarType "Unit" then D.text "None" else resultType)
        pure (P.suite signature (D.text "symbols = {}" <> D.hardline <>
          P.suite (D.text "try") (D.joinWith D.hardline resultBody) <> D.hardline <>
          P.suite (D.text "except (ValueError, TypeError, ArithmeticError, AttributeError) as error")
            (D.text "raise ValueError" <> D.delimitTrailing 4 "(" ")"
              [D.text (P.q ("native binding " ++ C.idText (C.declarationId decl) ++ ": ")) <>
                D.text " + str(error)"] <> D.text " from error")))
      let pathname = "src/" ++ map (\c -> if c == '.' then '/' else c) (unitName unit) ++ ".py"
          header = common ++ [D.text "import lawspec_native as bridge"] ++ imports
      pure [Artifact pathname (render (D.joinWith D.hardline header <>
        D.hardline <> D.hardline <> D.hardline <>
        D.joinWith (D.hardline <> D.hardline <> D.hardline) bodies)) "generated" "source"]
  dataFiles <- if any ((== "src/lawspec_data.py") . artifactPath) files then pure []
    else Data.emitPythonDataWithProfile (planMachineBits plan) layout (planDataDeclarations plan)
  generatorFiles <- if null generators then pure [] else do
    generatorImports <- forM (zip [0::Int ..] generators) $ \(i,generator) -> do
      let parts = referenceParts (resolvedGeneratorFactory generator)
      unless (length parts >= 2) (Left "Python generator references require a module and attribute")
      mapM_ P.identifier parts
      pure (D.text ("from " ++ intercalate "." (init parts) ++ " import ") <>
        D.delimitTrailing 4 "(" ")" [D.text (last parts ++ " as _factory_" ++ show i)])
    let factories = D.text "_factories = " <> D.delimitTrailing 4 "{" "}"
          [D.text (P.q (C.idText (resolvedGeneratorType generator)) ++ ": _factory_" ++ show i) |
            (i,generator) <- zip [0::Int ..] generators]
        wrapper = P.suite (D.text "def strategy" <> D.delimitTrailing 4 "(" ")"
          (map D.text ["schema", "reference", "bits", "budget", "scalar", "symbols=None", "witnesses=()", "index=None"]))
          (D.text "return " <> P.invoke "_strategy" (map D.text
            ["schema", "reference", "bits", "budget", "scalar", "symbols", "witnesses",
             "native_generators=_factories", "native_schema=bridge._native", "index=index"]))
        header = map D.text ["# Generated by LawSpec. Do not edit.",
          "import lawspec_native as bridge", "from lawspec_data_strategies import strategy as _strategy"]
        helper = Artifact "tests/lawspec_native_generators.py" (render
          (D.joinWith D.hardline (header ++ generatorImports) <>
           D.hardline <> D.hardline <> factories <> D.hardline <> D.hardline <> D.hardline <> wrapper)) "generated" "test"
    emitted <- either (Left . show) Right $ concat <$> mapM (\unit ->
      Scalar.scalarEmitWithNativeGenerators True minify (planDataDeclarations plan)
        (Definitions.definitionCalls (map plannedUnit (plannedUnits plan)))
        (planMachineBits plan) "python" (plannedUnit unit) (plannedProperties unit))
        [unit | unit <- plannedUnits plan, not (null (plannedProperties unit))]
    pure (helper : [file | file <- emitted, artifactPlacement file == "test"] ++
      [Artifact "tests/lawspec_data_strategies.py" (runtimeSource "python-data-strategies") "generated" "test" |
        not (any ((== "tests/lawspec_data_strategies.py") . artifactPath) files)])
  let replacements = map artifactPath (bridges ++ generatorFiles)
  unless (all ((/= "src/lawspec_native.py") . artifactPath) files)
    (Left "unit shadows generated lawspec_native support")
  let runtime = [Artifact "src/lawspec_runtime.py" (runtimeSource "python") "generated" "source" |
        not (any ((== "src/lawspec_runtime.py") . artifactPath) files)]
  let generated = [file | file <- files, artifactPath file `notElem` replacements] ++
        dataFiles ++ runtime ++ [support] ++ bridges ++ generatorFiles
  stubs <- generatorStubs generators mappings (refs ++ map resolvedNativeType mappings) generated
  pure (generated ++ stubs)
  where
    representations = bindingRepresentations bindings
    mappings = resolvedTypes representations
    functions = bindingFunctions bindings
    generators = resolvedGenerators representations
    layout = D.selectLayout minify (D.Pretty 79)
    render doc = D.render layout (doc <> D.hardline)

-- A scaffold is an application factory, not a second generator implementation.
-- Keep it readable even when generated support is compact, and let the shared
-- file planner preserve it and report changes to its required signature.
generatorStubs :: [ResolvedGeneratorBinding] -> [ResolvedTypeBinding] -> [NativeRef] -> [Artifact] -> Either String [Artifact]
generatorStubs generators mappings applicationRefs files = do
  let requested = filter resolvedGeneratorStub generators
      moduleParts = init . referenceParts . resolvedGeneratorFactory
      modules = nub (map moduleParts requested)
      modulePath = intercalate "/"
      conflicts a b = let x = map toLower a; y = map toLower b
        in x == y || (x ++ "/") `isPrefixOf` y || (y ++ "/") `isPrefixOf` x
      existing = [take (length relative - 3) relative | file <- files,
        let path = artifactPath file,
        root <- ["src/", "tests/"], root `isPrefixOf` path,
        let relative = drop (length root) path, ".py" `isSuffixOf` relative]
      applicationModules = [modulePath (init parts) | NativeRef parts <- applicationRefs,
        length parts >= 2]
      dependencies = words "builtins sys typing hypothesis pytest dataclasses fractions decimal math struct functools"
  forM modules $ \parts -> do
    let path = modulePath parts
    unless (not (null parts)) (Left "Python generator scaffolds require a module and attribute")
    unless (not (any (conflicts path) (existing ++ applicationModules ++ dependencies)) &&
      not (any (\other -> other /= parts && conflicts path (modulePath other)) modules))
      (Left ("Python generator scaffold module conflicts with another module: " ++ path))
    bodies <- forM (filter ((== parts) . moduleParts) requested) $ \generator -> do
      let name = last (referenceParts (resolvedGeneratorFactory generator))
          arguments = [D.text ("argument_" ++ show i ++ ": _strategies.SearchStrategy") |
            i <- [0 .. generatorParameterCount generator - 1]]
          resultLabel = maybe (C.idText (resolvedGeneratorType generator))
            (intercalate "." . referenceParts) (lookup (resolvedGeneratorType generator)
              [(C.dataId (resolvedDeclaration mapping),resolvedNativeType mapping) | mapping <- mappings])
      unless (name /= "_strategies")
        (Left "Python generator scaffold factory conflicts with its strategy import")
      pure (P.suite (D.text ("def " ++ name) <> D.delimitTrailing 4 "(" ")" arguments <>
        D.text " -> _strategies.SearchStrategy")
        (D.text ("# Native result: " ++ resultLabel) <> D.hardline <>
         D.text "# Return a native strategy; argument strategies retain their shrinkers." <>
         D.hardline <> D.text "raise NotImplementedError" <> D.delimitTrailing 4 "(" ")"
          [D.text (P.q ("Implement generator for " ++ C.idText (resolvedGeneratorType generator)))]))
    pure (Artifact ("tests/" ++ path ++ ".py")
      (D.render (D.Pretty 79)
        (D.text "# User-owned native generator factories. Implement before running properties." <>
         D.hardline <> D.text "from hypothesis import strategies as _strategies" <>
         D.hardline <> D.hardline <> D.hardline <>
         D.joinWith (D.hardline <> D.hardline <> D.hardline) bodies <> D.hardline))
      "user" "test")
