-- Native Python declarations and checked constructor predicate callbacks.
module LawSpec.PythonData (emitPythonData, emitPythonDataWithProfile, pythonDataType, pythonTypeReference, pythonDataTypeDoc, pythonDataTypeDocWith, pythonTypeReferenceDoc, requiresSchema) where

import LawSpec.Time (isDurationType)
import Control.Monad (unless, forM)
import qualified LawSpec.Core as C
import qualified LawSpec.Core.Schema as S
import LawSpec.Core.Types (makeRegistry, freeExistentials)
import LawSpec.Core.Total (constructorProofContracts)
import LawSpec.Common (Artifact(..))
import LawSpec.Scalar (primitives, primitiveName)
import LawSpec.RuntimeSources (runtimeSource)
import LawSpec.PythonTypes
import LawSpec.DataNames (isProduct)
import qualified LawSpec.PythonExpr as E
import qualified LawSpec.Code.Doc as D

emitPythonData :: D.Layout -> [C.DataDeclaration] -> Either String [Artifact]
emitPythonData = emitPythonDataWithProfile 64

emitPythonDataWithProfile :: Int -> D.Layout -> [C.DataDeclaration] -> Either String [Artifact]
emitPythonDataWithProfile bits layout declarations = do
  _ <- makeRegistry declarations
  _ <- either (Left . show) Right (constructorProofContracts bits declarations)
  names <- namesFor declarations
  (schemas,contracts) <- S.dataSchemasWithContracts declarations
  let available = ["_lawspec_field_predicate" ++ show index | index <- [0 :: Int ..],
        "_lawspec_field_predicate" ++ show index `notElem` map snd names]
      entries = zip available [(contract,predicate) | contract <- contracts,
        predicate <- S.contractPredicates contract]
      bindings = [(S.contractTag contract,name) | (name,(contract,_)) <- entries]
  callbacks <- forM entries $ \(name,(contract,predicate)) -> do
    let fields = zip (map C.binderId (S.contractFields contract))
          ["_fields[" ++ show i ++ "]" | i <- [0 :: Int ..]]
        local identity = maybe "_invalid_field" id (lookup identity fields)
        ref ty = do
          value <- reference <$> S.typeReference (S.contractParameters contract) ty
          pure (if variable ty then E.call "_schema.substitute" [value,D.text "_types"] else value)
        key ty | variable ty = E.call "_schema.type_key" . pure <$> ref ty
               | otherwise = pure (E.quoted (E.typeKey ty))
    body <- E.renderExpressionWithContext declarations (D.text "bits") ref key local
      (\_ _ -> Left "external call in constructor predicate") predicate
    pure (suite (D.text "def " <> invoke name (map D.text
      ["_lawspec_schema","_types","_fields","bits","symbols"])) (D.text "return " <> body))
  -- A handle has no class: its values are the adapters' own objects.
  classes <- concat <$> mapM (definition names) [d | d <- declarations, collectionContainer (C.idText (C.dataId d)) == Nothing,
    not (isDurationType (C.idText (C.dataId d))), not (C.dataHandle d)]
  metadata <- mapM (definitionSchema names bindings) schemas
  let header = map D.text
        ["# Generated by LawSpec. Do not edit.", "from __future__ import annotations", "",
         "import builtins as _builtins", "import dataclasses as _dataclasses", "",
         "import lawspec_runtime as ls", "import lawspec_schema as _schema"]
      factory = suite (D.text "def make_schema()")
        (D.joinWith (D.hardline <> D.hardline) (callbacks ++
          [D.text "return " <> invoke "_schema.Schema"
            [array metadata, array (map (D.text . q . primitiveName) primitives)]]))
      source = D.joinWith D.hardline header <> D.hardline <> D.hardline <> D.hardline <>
        D.joinWith (D.hardline <> D.hardline <> D.hardline) (classes ++ [factory]) <> D.hardline
  pure [Artifact "src/lawspec_data.py" (D.render layout source) "generated" "source",
        Artifact "src/lawspec_schema.py" (runtimeSource "python-schema") "generated" "source"]
  where
    handles = handleTypes declarations
    variable (C.TypeVariable _) = True
    variable (C.Constructor _ args) = any (\arg -> case arg of C.TypeArgument ty -> variable ty; _ -> False) args
    variable (C.Arrow a b) = variable a || variable b
    definition names declaration = do
      name <- lookupName names (C.dataId declaration)
      let parameters = zip (C.dataParameters declaration)
            [candidate | n <- [0::Int ..], let candidate = "_T" ++ show n, candidate `notElem` map snd names]
          args = map (D.text . snd) parameters
          base = suite (D.text "class " <> application name args)
            (D.text "__slots__ = ()" <> D.hardline <> D.hardline <>
             suite (D.text "def __new__(cls, *args, **kwargs)")
              (suite (D.text ("if cls is " ++ name))
                (D.text "raise _builtins.TypeError(" <> D.text (q ("construct a variant of " ++ C.dataName declaration)) <> D.text ")") <>
               D.hardline <> D.text "return _builtins.object.__new__(cls)"))
      variants <- forM (C.dataConstructors declaration) $ \constructor -> do
        native <- lookupName names (C.constructorId constructor)
        -- A GADT case is generic only in the parameters it leaves open and in
        -- its existentials; its base class applies its refinements.
        let existentials = zip (C.constructorExistentials constructor)
              [candidate | n <- [0::Int ..], let candidate = "_E" ++ show n, candidate `notElem` map snd names]
            scope = parameters ++ existentials
            open = [D.text v | (p, v) <- parameters, p `notElem` map fst (C.constructorEquations constructor)] ++
              map (D.text . snd) existentials
        baseArgs <- forM parameters $ \(p, v) -> maybe (pure (D.text v)) (typeDocWith handles "" names scope)
          (lookup p (C.constructorEquations constructor))
        fields <- forM (C.constructorFields constructor) $ \field -> do
          identifier (C.binderName field)
          unless (take 2 (C.binderName field) /= "__") (Left "Python data fields cannot replace special methods")
          ty <- typeDocWith handles "" names scope (C.binderType field)
          pure (D.text (C.binderName field ++ ": ") <> ty)
        -- Each field-only existential's type travels as a witness text.
        let free = freeExistentials declaration constructor
            witnesses = [D.text (S.witnessFieldName (length free) k ++ ": str") | k <- [0 .. length free - 1]]
        let fields' = fields ++ witnesses
        pure (D.text "@_dataclasses.dataclass(frozen=True, slots=True, eq=False)" <> D.hardline <>
          suite (D.text "class " <> application native open <>
            (if isProduct declaration then mempty else D.text "(" <> application name baseArgs <> D.text ")"))
            (if null fields' then D.text "pass" else D.joinWith D.hardline fields'))
      -- A product is a single dataclass named after its type.
      pure ([base | not (isProduct declaration)] ++ variants)
    definitionSchema names bindings schema = do
      variants <- forM (S.constructors schema) $ \constructor -> do
        native <- if collectionContainer (S.typeName schema) /= Nothing || isDurationType (S.typeName schema) then pure "None"
          else lookupName names (C.Id (S.constructorTag constructor))
        let predicates = [D.text name | (tag,name) <- bindings, tag == S.constructorTag constructor]
        pure (invoke "_schema.Constructor"
          ([D.text (q (S.constructorTag constructor)),
           array [invoke "_schema.Field" [D.text (q (S.fieldName field)),reference (S.fieldType field)] | field <- S.fields constructor],
           D.text native] ++ [array predicates | not (null predicates)] ++
           [D.text "indices=" <> array (map (D.text . q) (S.constructorIndex constructor)) | not (null (S.constructorIndex constructor))] ++
           [D.text "refinements=" <> array [array [D.text (show index), reference pattern] | (index, pattern) <- S.constructorRefinements constructor]
             | not (null (S.constructorRefinements constructor))] ++
           [D.text ("existentials=" ++ show (S.constructorExistentials constructor)) | S.constructorExistentials constructor > 0] ++
           [D.text "witnesses=" <> array (map (D.text . show) (S.constructorWitnesses constructor)) | not (null (S.constructorWitnesses constructor))]))
      pure (invoke "_schema.Definition"
        ([D.text (q (S.typeName schema)), D.text (show (S.parameterCount schema)),array variants] ++
         [D.text "handle=True" | S.typeName schema `elem` [C.idText (C.dataId d) | d <- declarations, C.dataHandle d]]))
