-- | Framework-independent total definitions with checked native Python APIs.
module LawSpec.PythonDefinitions (emitPythonDefinitions, definitionCalls) where

import Control.Monad (forM)
import LawSpec.Core.Policy
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.PythonData as Native
import qualified LawSpec.PythonExpr as E
import qualified LawSpec.Code.Doc as D
import Data.List (nub, sort, intercalate)

-- | Generated tests call checked definitions by these names, so every test
-- file agrees.
definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d), "_definitions.evaluate_" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

-- | Checked definitions are emitted as ordinary Python code, so adapters and tests call
-- the same proved implementation. ref:DEC-total-definitions
emitPythonDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitPythonDefinitions _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitPythonDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  bodies <- mapM (implementation contracts) (zip [0::Int ..] (concatMap unitDefinitions units))
  wrappers <- mapM nativeUnit (filter (not . null . unitDefinitions) units)
  pure (file "src/lawspec_definition_bodies.py" ["import importlib as _importlib"] (adapterLoader : bodies) : wrappers)
  where
    width = D.text (show bits)
    callees = definitionCalls units
    definitionIds = map (declarationId . definitionDeclaration) (concatMap unitDefinitions units)
    adapters = [(declarationId d, (idText (unitId u), d)) | u <- units, d <- unitDeclarations u,
      declarationId d `notElem` definitionIds]
    file path imports bodies = Artifact path (D.render layout (
      D.text "# Generated by LawSpec. Do not edit." <> D.hardline <>
      D.text "from __future__ import annotations" <> D.hardline <> D.hardline <>
      D.text "import builtins as _builtins" <>
      D.hardline <> D.hardline <>
      D.joinWith D.hardline (map D.text (sort (imports ++
         ["import lawspec_data as data", "import lawspec_runtime as ls", "import lawspec_schema as _schema"]))) <>
      D.hardline <> D.hardline <> D.text "_lawspec_schema = data.make_schema()" <>
      D.hardline <> D.hardline <> D.hardline <>
      D.joinWith (D.hardline <> D.hardline <> D.hardline) bodies <> D.hardline)) "generated" "source"
    contextual identity body = E.suite (D.text "try") body <> D.hardline <>
      E.suite (D.text "except " <> D.delimitTrailing 4 "(" ")"
        (map D.text ["_builtins.ValueError", "_builtins.TypeError", "_builtins.OverflowError"]) <> D.text " as error")
        (D.text "raise " <> E.call "_builtins.ValueError"
          [D.group (E.quoted (idText identity ++ ": ") <> D.softline <>
            D.text "+ _builtins.str(error)")] <> D.text " from error")
    assign name value = D.text (name ++ " = ") <> value
    -- Adapter modules load when first called, so an adapter that imports its
    -- unit's definitions does not make a cycle.
    adapterLoader = E.suite (D.text "def _adapters(module: _builtins.str)")
      (D.text "return _importlib.import_module(module)")
    schemaCall name ty value = do
      ref <- Native.pythonTypeReferenceDoc ty
      pure (E.call ("_lawspec_schema." ++ name) [ref,value,width,D.text "symbols"])
    implementation contracts (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          names = zip (nub (map binderId binders)) ["value_" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved Python local") id (lookup identity names)
          arguments = map (local . binderId) (definitionArguments d)
          external term values = case expressionNode term of
            ExternalCall declaration _ | Just name <- lookup declaration callees ->
              pure (E.call (drop (length ("_definitions." :: String)) name) (D.text "symbols":values))
            -- An orchestration calls an adapter natively: the values cross
            -- to native and back through the schema, as in the tests.
            ExternalCall declaration _ | Just (owner, adapter) <- lookup declaration adapters -> do
              let (parameterTypes, resultType) = functionType (declarationType adapter)
              nativeValues <- sequence [schemaCall "to_native" ty value | (ty, value) <- zip parameterTypes values]
              let invocation = E.call ("_adapters(" ++ show owner ++ ")." ++ declarationName adapter) nativeValues
              -- A Unit adapter returns None, which is the Unit value.
              let fromNative value
                    | resultType == Constructor "Unit" [] = pure (E.call "ls.unit_result" [value])
                    | otherwise = schemaCall "from_native" resultType value
              if declarationAsync adapter
                then do
                  -- Within its stage's timeout and hedge, when it has them.
                  convert <- fromNative (D.text "_native")
                  pure (E.call "ls.await_step" [D.text "symbols", D.text "lambda: " <> invocation, D.text "lambda _native: " <> convert])
                else fromNative invocation
            _ -> Left "unresolved Python total call"
      rendered <- E.renderExpression declarations bits local external (definitionBody d)
      -- A workflow stage with policies runs under the workflow runtime.
      body <- case definitionPolicy d of
        Nothing -> pure rendered
        Just policy | policyFrame policy -> pure (E.call "ls.run_workflow" [D.text "symbols", D.text "lambda: " <> rendered])
        Just policy -> do
          config <- policyDoc (idText (declarationId (definitionDeclaration d))) policy
          let key = case arguments of
                argument : _ -> D.text argument
                [] -> D.text "None"
          pure (E.call "ls.run_stage" [D.text "symbols", config, D.text "lambda: " <> rendered, key])
      -- Arguments and results were checked where they were built, decoded
      -- or drawn; the native wrappers check values crossing from adapters.
      let checks = []
          result = D.text "result"
      let contract = lookup (declarationId (definitionDeclaration d)) [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [assign "result" body,D.text "return " <> result])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checked_result")] ++
                [(binderId b,"contract_value_" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c ++ contractRuntimePostconditions c))]
              resolve identity = maybe (error "unbound definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression declarations bits resolve external predicate
                pure (E.call "ls.require_contract" [expression,E.quoted stage])
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          pure (checks ++ pre ++ [assign "result" body,assign "checked_result" result] ++
            post ++ [D.text "return checked_result"])
      pure (E.suite (D.text ("def evaluate_" ++ show index) <>
        D.delimitTrailing 4 "(" ")" (map D.text ("symbols":arguments)))
        (contextual (declarationId (definitionDeclaration d)) (D.joinWith D.hardline
          statements)))
    evaluator identity = maybe (Left "unresolved Python policy definition") (Right . drop (length ("_definitions." :: String)))
      (lookup identity callees)
    policyDoc key policy = do
      gates <- policyGates policy
      retry <- case policyRetry policy of
        Nothing -> pure (D.text "None")
        Just r -> do
          strategy <- case retryStrategy r of
            Immediate -> pure (tuple [E.quoted "immediate"])
            Fixed delay -> pure (tuple [E.quoted "fixed", int delay])
            Linear delay step -> pure (tuple [E.quoted "linear", int delay, int step])
            Exponential delay factor cap -> pure (tuple [E.quoted "exponential", int delay, int factor, maybe (D.text "None") int cap])
            Fibonacci delay -> pure (tuple [E.quoted "fibonacci", int delay])
            Custom decide -> do
              name <- evaluator decide
              pure (tuple [E.quoted "custom", D.text ("lambda attempt, error, previous: ls.retry_decision(" ++ name ++
                "(symbols, attempt, error, ls.DataValue(\"lawspec.time::type::Duration::Duration\", (previous,))))")])
          condition <- case retryWhen r of
            Nothing -> pure (D.text "None")
            Just p -> (\name -> D.text ("lambda error: " ++ name ++ "(symbols, error)")) <$> evaluator p
          pure (E.call "ls.Retry" [strategy, int (retryAttempts r), E.quoted (jitterName (retryJitter r)), condition])
      compensate <- case policyCompensate policy of
        Nothing -> pure (D.text "None")
        Just undo -> (\name -> D.text ("lambda value: " ++ name ++ "(symbols, value)")) <$> evaluator undo
      pure (E.call "ls.StagePolicy" [E.quoted (policyStage policy), retry, maybe (D.text "None") int (policyTimeout policy),
        E.quoted key, tuple gates, maybe (D.text "None") int (policyCache policy),
        D.text (if null (policyFailures policy) then "False" else "True"), compensate,
        maybe (D.text "None") (\h -> tuple [int (hedgeDelay h), int (hedgeMost h)]) (policyHedge policy)])
    -- A gate's callbacks call the unit's copies of the resilience unit's
    -- state machines, with the policy's numbers.
    policyGates policy = do
      breaker <- forM (policyBreaker policy) $ \b -> do
        start <- evaluator (breakerStart b)
        admit <- evaluator (breakerAdmit b)
        record <- evaluator (breakerRecord b)
        pure (E.call "ls.Gate" [E.quoted "breaker", lambda ["now"] (start ++ "(symbols, now)"),
          lambda ["state", "now"] (admit ++ "(symbols, state, now)"),
          lambda ["state", "now", "succeeded"] (record ++ "(symbols, " ++ show (breakerFailures b) ++ ", " ++ show (breakerWindow b) ++ ", " ++
            show (breakerCooldown b) ++ ", state, now, succeeded)"), D.text "None"])
      limit <- forM (policyLimit policy) $ \l -> do
        start <- evaluator (limitStart l)
        admit <- evaluator (limitAdmit l)
        let numbers = show (limitCount l) ++ ", " ++ show (limitPeriod l)
        pure (E.call "ls.Gate" [E.quoted "limit", lambda ["now"] (start ++ "(symbols, " ++ numbers ++ ", now)"),
          lambda ["state", "now"] (admit ++ "(symbols, " ++ numbers ++ ", state, now)"), D.text "None", waitDoc (limitWait l)])
      bulkhead <- forM (policyBulkhead policy) $ \b -> do
        start <- evaluator (bulkheadStart b)
        admit <- evaluator (bulkheadAdmit b)
        release <- evaluator (bulkheadRelease b)
        let n = show (bulkheadLimit b)
        pure (E.call "ls.Gate" [E.quoted "bulkhead", lambda ["now"] (start ++ "(symbols, " ++ n ++ ", now)"),
          lambda ["state", "now"] (admit ++ "(symbols, " ++ n ++ ", state, now)"),
          lambda ["state", "now", "succeeded"] (release ++ "(symbols, state)"), waitDoc (bulkheadWait b)])
      pure (maybe [] pure breaker ++ maybe [] pure limit ++ maybe [] pure bulkhead)
    lambda parameters body = D.text ("lambda " ++ intercalate ", " parameters ++ ": " ++ body)
    waitDoc wait = case wait of
      Nothing -> D.text "None"
      Just Nothing -> D.text "-1"
      Just (Just d) -> int d
    tuple [] = D.text "()"
    tuple items = D.text "(" <> D.joinWith (D.text ", ") items <> D.text ",)"
    int n = D.text (show n)
    jitterName j = case j of
      NoJitter -> "none"
      FullJitter -> "full"
      EqualJitter -> "equal"
      DecorrelatedJitter -> "decorrelated"
    nativeUnit unit = do
      wrappers <- mapM native (unitDefinitions unit)
      let path = "src/lawspec_definitions/" ++ map (\c -> if c == '.' then '/' else c) (idText (unitId unit)) ++ ".py"
      pure (file path ["import lawspec_definition_bodies as _definitions"] wrappers)
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          values = ["value_" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.pythonDataTypeDoc declarations) args
      resultType <- Native.pythonDataTypeDoc declarations result
      arguments <- sequence [schemaCall "from_native" ty (D.text value) | (ty,value) <- zip args values]
      name <- maybe (Left "unresolved Python native call") Right (lookup (declarationId declaration) callees)
      output <- schemaCall "to_native" result (D.text "result")
      let parameters = D.text "symbols: _builtins.dict[_builtins.str, _builtins.object]" :
            [D.text (value ++ ": ") <> ty | (value,ty) <- zip values types]
          inputs = [assign ("argument_" ++ show i) value | (i,value) <- zip [0::Int ..] arguments]
          invocation = E.call name (D.text "symbols" : [D.text ("argument_" ++ show i) | i <- [0 .. length args - 1]])
      pure (E.suite (D.text ("def " ++ declarationName declaration) <>
        D.delimitTrailing 4 "(" ")" parameters <> D.text " -> " <> resultType)
        (contextual (declarationId declaration) (D.joinWith D.hardline
          (inputs ++ [assign "result" invocation,D.text "return " <> output]))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat
        [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
