-- Remote evaluation. Every checked definition whose types have wire
-- descriptors can be evaluated by another node, by its content hash: the
-- Merkle digest of the definition and everything it reaches (see
-- LawSpec.Dependencies), so two nodes agree on a hash exactly when they hold
-- the same definition. Each target generates a small module, lawspec_remote,
-- mapping each hash to its definition and descriptors, with serve(node) and
-- evaluate(node, address, name, args...).
module LawSpec.Remote (Remote(..), remoteManifest, remoteArtifacts) where

import Control.Monad (foldM)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import qualified LawSpec.Dependencies as D
import LawSpec.MachineSpec (describe)
import LawSpec.Testing (Plan(..), PlannedUnit(..))

data Remote = Remote
  { remoteId :: C.Id
  -- The definition's qualified name, such as example.actors::modelDeposit.
  , remoteName :: String
  , remoteDigest :: String
  , remoteArguments :: [String]
  , remoteResult :: String
  }

-- A content hash names its algorithm, so nodes never compare hashes of two
-- kinds: sha3-256: then the SHA3-256 Merkle hash in hexadecimal.
contentName :: String -> String
contentName h = "sha3-256:" ++ h

-- The data types the descriptors use, and each definition that can be
-- evaluated remotely. Orchestrations (which call adapters) and definitions
-- over types without descriptors are left out.
remoteManifest :: Plan -> ([String], [Remote])
remoteManifest plan = (map snd (reverse table), reverse remotes)
  where
    units = map plannedUnit (plannedUnits plan)
    graph = D.dependencyGraph (planDataDeclarations plan) units
    bits = planMachineBits plan
    datas = planDataDeclarations plan
    (table, remotes) = foldl add ([], []) [d | u <- units, d <- C.unitDefinitions u, not (C.definitionOrchestrates d)]
    add (t, acc) d =
      let declaration = C.definitionDeclaration d
          identity = C.declarationId declaration
          (args, result) = C.functionType (C.declarationType declaration)
          described = do
            (ds, t') <- foldM (\(xs, tt) ty -> (\(x, tt') -> (xs ++ [x], tt')) <$> describe bits datas tt ty) ([], t) args
            (r, t'') <- describe bits datas t' result
            pure (ds, r, t'')
      in case (described, D.contentHash graph (D.DeclarationNode identity)) of
        (Right (ds, r, t'), Just h) -> (t', Remote identity (C.idText identity) (contentName h) ds r : acc)
        _ -> (t, acc)

-- The target's lawspec_remote module, given how the target calls each
-- checked definition on logical values.
remoteArtifacts :: String -> [(C.Id, String)] -> Plan -> [Artifact]
remoteArtifacts target calls plan = case (target, remotes) of
  (_, []) -> []
  ("python", _) -> [Artifact "src/lawspec_remote.py" python "generated" "source"]
  ("go", _) ->
    [ Artifact (intercalate "/" parts ++ "/lawspec_remote.go") (go (last parts) mine) "generated" "source"
    | u <- map plannedUnit (plannedUnits plan)
    , let unit = C.idText (C.unitId u)
          parts = splitDots unit
          mine = [r | r <- remotes, takeWhile (/= ':') (remoteName r) == unit, Just _ <- [callable r]]
    , not (null mine) ]
  (t, _) | t `elem` ["java", "kotlin"] -> [Artifact "src/main/java/lawspec/remote/LawSpecRemote.java" java "generated" "source"]
  ("rust", _) -> [Artifact "src/lawspec_remote.rs" rust "generated" "source"]
  ("javascript", _) -> [Artifact "src/lawspec_remote.mjs" (web False) "generated" "source"]
  ("typescript", _) -> [Artifact "src/lawspec_remote.ts" (web True) "generated" "source"]
  ("haskell", _) -> [Artifact "src/LawSpecRemote.hs" haskell "generated" "source"]
  _ -> []
  where
    splitDots s = case break (== '.') s of
      (a, []) -> [a]
      (a, _ : rest) -> a : splitDots rest
    go package mine = unlines $
      [ "// Generated by LawSpec. Do not edit."
      , "package " ++ package
      , ""
      , "import \"time\""
      , ""
      , "// Checked definitions that other nodes can evaluate, by content hash."
      , "// LawSpecServeDefinitions lets other nodes evaluate them on a node;"
      , "// LawSpecEvaluateRemote evaluates one on the node at an address. Values"
      , "// are logical values, as the runtime's checks use them."
      , ""
      , "var lawSpecRemoteTypes = LawSpecTypes(" ++ quote (unwords forms) ++ ")"
      , ""
      , "// lawSpecRemoteDefinitions maps a qualified name to its content hash and"
      , "// how to evaluate it."
      , "var lawSpecRemoteDefinitions = map[string]struct {"
      , "\tdigest     string"
      , "\tdefinition LawSpecRemoteDefinition"
      , "}{" ] ++
      [ "\t" ++ quote (remoteName r) ++ ": {" ++ quote (remoteDigest r) ++ ", LawSpecRemoteDefinition{func(a []LawSpecValue) LawSpecValue { return " ++
          call ++ "(map[string]*LawSpecSymbol{}" ++ concat [", a[" ++ show i ++ "]" | i <- [0 .. length (remoteArguments r) - 1]] ++ ") }, " ++
          "[]any{" ++ intercalate ", " ["LawSpecDescriptor(" ++ quote d ++ ")" | d <- remoteArguments r] ++ "}, LawSpecDescriptor(" ++ quote (remoteResult r) ++ ")}},"
      | r <- mine, Just call <- [callable r] ] ++
      [ "}"
      , ""
      , "// LawSpecServeDefinitions lets other nodes evaluate these definitions on"
      , "// node, and returns the address they are served at."
      , "func LawSpecServeDefinitions(node *LawSpecNode) (string, error) {"
      , "\ttable := map[string]LawSpecRemoteDefinition{}"
      , "\tfor _, entry := range lawSpecRemoteDefinitions {"
      , "\t\ttable[entry.digest] = entry.definition"
      , "\t}"
      , "\treturn node.ServeDefinitions(table, lawSpecRemoteTypes, \"definitions\")"
      , "}"
      , ""
      , "// LawSpecDefinitionDigest is the content hash of the definition with this"
      , "// qualified name."
      , "func LawSpecDefinitionDigest(name string) string {"
      , "\treturn lawSpecRemoteDefinitions[name].digest"
      , "}"
      , ""
      , "// LawSpecEvaluateRemote evaluates the named definition on the node at"
      , "// address, by its content hash; it fails with LawSpecUnreachable when that"
      , "// node does not answer within the timeout."
      , "func LawSpecEvaluateRemote(node *LawSpecNode, address, name string, timeout time.Duration, args ...LawSpecValue) (LawSpecValue, error) {"
      , "\tentry := lawSpecRemoteDefinitions[name]"
      , "\td := entry.definition"
      , "\treturn node.Evaluate(address, entry.digest, args, d.Arguments, d.Result, lawSpecRemoteTypes, timeout, \"definitions\")"
      , "}" ]
    (forms, remotes) = remoteManifest plan
    callable r = lookup (remoteId r) calls
    quote s = show s
    python = unlines $
      [ "# Generated by LawSpec. Do not edit."
      , "\"\"\"Checked definitions that other nodes can evaluate, by content hash."
      , ""
      , "serve(node) lets other nodes evaluate them on this node; evaluate(node,"
      , "address, name, *args) evaluates one on the node at address. Values are"
      , "logical values, as the runtime's checks use them."
      , "\"\"\""
      , "import lawspec_runtime as ls"
      , "import lawspec_definition_bodies as _definitions"
      , ""
      , if null forms then "TYPES = ls.Values({})"
        else "TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ quote (unwords forms) ++ ")})"
      , ""
      , "# name: (content hash, function, argument descriptors, result descriptor)"
      , "DEFINITIONS = {" ] ++
      [ "    " ++ quote (remoteName r) ++ ": (" ++ quote (remoteDigest r) ++ ", lambda *args: " ++ call ++ "({}, *args), " ++
        "[" ++ intercalate ", " [descriptor d | d <- remoteArguments r] ++ "], " ++ descriptor (remoteResult r) ++ "),"
      | r <- remotes, Just call <- [callable r] ] ++
      [ "}"
      , ""
      , ""
      , "def serve(node):"
      , "    \"\"\"Lets other nodes evaluate these definitions on node.\"\"\""
      , "    return node.serve_definitions({h: (f, a, r) for h, f, a, r in DEFINITIONS.values()}, TYPES)"
      , ""
      , ""
      , "def digest(name):"
      , "    \"\"\"The content hash of the definition with this qualified name.\"\"\""
      , "    return DEFINITIONS[name][0]"
      , ""
      , ""
      , "def evaluate(node, address, name, *args, timeout=5.0):"
      , "    \"\"\"Evaluates the named definition on the node at address, by its"
      , "    content hash; raises Unreachable when that node does not answer.\"\"\""
      , "    h, _, a, r = DEFINITIONS[name]"
      , "    return node.evaluate(address, h, list(args), a, r, TYPES, timeout=timeout)" ]
    descriptor d = "ls.read_descriptor(" ++ quote d ++ ")[0]"
    jdescriptor d = "LawSpecRuntime.descriptor(" ++ quote d ++ ")"
    java = unlines $
      [ "// Generated by LawSpec. Do not edit."
      , "package lawspec.remote;"
      , ""
      , "import java.util.List;"
      , "import java.util.Map;"
      , "import lawspec.runtime.LawSpecRuntime;"
      , ""
      , "/**"
      , " * Checked definitions that other nodes can evaluate, by content hash. serve(node) lets other"
      , " * nodes evaluate them on this node; evaluate(node, address, name, args) evaluates one on the node"
      , " * at address. Values are logical values, as the runtime's checks use them."
      , " */"
      , "public final class LawSpecRemote {"
      , "  private LawSpecRemote() {}"
      , ""
      , "  public static final LawSpecRuntime.Values TYPES = LawSpecRuntime.valuesOf(" ++ quote (unwords forms) ++ ");"
      , ""
      , "  private record Entry(String digest, LawSpecRuntime.Definition definition) {}"
      , ""
      , "  private static final Map<String, Entry> DEFINITIONS = new java.util.HashMap<>();"
      , ""
      , "  static {" ] ++
      concat
      [ [ "    DEFINITIONS.put("
        , "        " ++ quote (remoteName r) ++ ","
        , "        new Entry("
        , "            " ++ quote (remoteDigest r) ++ ","
        , "            new LawSpecRuntime.Definition("
        , "                args -> " ++ call ++ "(new java.util.HashMap<String, Object>()" ++
            concat [", args.get(" ++ show i ++ ")" | i <- [0 .. length (remoteArguments r) - 1]] ++ "),"
        , "                List.of(" ++ intercalate ", " (map jdescriptor (remoteArguments r)) ++ "),"
        , "                " ++ jdescriptor (remoteResult r) ++ ")));" ]
      | r <- remotes, Just call <- [callable r] ] ++
      [ "  }"
      , ""
      , "  /** Lets other nodes evaluate these definitions on node. */"
      , "  public static String serve(LawSpecRuntime.Node node) {"
      , "    var table = new java.util.HashMap<String, LawSpecRuntime.Definition>();"
      , "    for (var entry : DEFINITIONS.values()) table.put(entry.digest(), entry.definition());"
      , "    return node.serveDefinitions(table, TYPES);"
      , "  }"
      , ""
      , "  /** The content hash of the definition with this qualified name. */"
      , "  public static String digest(String name) {"
      , "    return DEFINITIONS.get(name).digest();"
      , "  }"
      , ""
      , "  /** Evaluates the named definition on the node at address, by its content hash; throws Unreachable when that node does not answer within 5 seconds. */"
      , "  public static LawSpecRuntime.Value evaluate(LawSpecRuntime.Node node, String address, String name, LawSpecRuntime.Value... args) {"
      , "    return evaluate(node, address, name, List.of(args), 5.0);"
      , "  }"
      , ""
      , "  public static LawSpecRuntime.Value evaluate("
      , "      LawSpecRuntime.Node node, String address, String name, List<LawSpecRuntime.Value> args, double timeout) {"
      , "    var entry = DEFINITIONS.get(name);"
      , "    if (entry == null) throw new IllegalArgumentException(\"no remote definition \" + name);"
      , "    var definition = entry.definition();"
      , "    return node.evaluate(address, entry.digest(), args, definition.arguments(), definition.result(), TYPES, timeout);"
      , "  }"
      , "}" ]
    rust = unlines $
      [ "// Generated by LawSpec. Do not edit."
      , "//! Checked definitions that other nodes can evaluate, by content hash."
      , "//!"
      , "//! serve(node) lets other nodes evaluate them on this node; evaluate(node,"
      , "//! address, name, args) evaluates one on the node at address. Values are"
      , "//! logical values (ls::Value), as the runtime's checks use them."
      , "#![allow(dead_code)]"
      , "use crate::lawspec_runtime as ls;"
      , ""
      , "fn wire_types() -> ls::Values {"
      , "    ls::values_table(" ++ quote (unwords forms) ++ ")"
      , "}"
      , ""
      , "/// (qualified name, content hash, function, argument descriptors, result descriptor)"
      , "pub const DEFINITIONS: &[(&str, &str, ls::ModelCallback, &[&str], &str)] = &[" ] ++
      [ "    (" ++ quote (remoteName r) ++ ", " ++ quote (remoteDigest r) ++ ", " ++ call ++ " as ls::ModelCallback, &[" ++
        intercalate ", " (map quote (remoteArguments r)) ++ "], " ++ quote (remoteResult r) ++ "),"
      | r <- remotes, Just call <- [callable r] ] ++
      [ "];"
      , ""
      , "/// Lets other nodes evaluate these definitions on node."
      , "pub fn serve(node: &ls::net::Node) -> ls::Result<String> {"
      , "    let table: Vec<ls::net::RemoteDefinition> = DEFINITIONS"
      , "        .iter()"
      , "        .map(|(_, digest, function, arguments, result)| {"
      , "            let function = *function;"
      , "            let call: std::sync::Arc<dyn Fn(Vec<ls::Value>) -> ls::Result<ls::Value> + Send + Sync> ="
      , "                std::sync::Arc::new(move |args| function(&mut ls::Context::default(), args));"
      , "            (digest.to_string(), call, arguments.iter().map(|d| ls::descriptor(d)).collect(), ls::descriptor(result))"
      , "        })"
      , "        .collect();"
      , "    node.serve_definitions(table, wire_types(), \"definitions\")"
      , "}"
      , ""
      , "/// The content hash of the definition with this qualified name."
      , "pub fn digest(name: &str) -> Option<&'static str> {"
      , "    DEFINITIONS.iter().find(|d| d.0 == name).map(|d| d.1)"
      , "}"
      , ""
      , "/// Evaluates the named definition on the node at address, by its content"
      , "/// hash; fails as unreachable when that node does not answer in time."
      , "pub fn evaluate(node: &ls::net::Node, address: &str, name: &str, args: &[ls::Value]) -> ls::Result<ls::Value> {"
      , "    let (_, digest, _, arguments, result) ="
      , "        DEFINITIONS.iter().find(|d| d.0 == name).ok_or_else(|| format!(\"no definition {name}\"))?;"
      , "    let arguments: Vec<ls::Sexp> = arguments.iter().map(|d| ls::descriptor(d)).collect();"
      , "    node.evaluate(address, digest, args, &arguments, &ls::descriptor(result), &wire_types(), std::time::Duration::from_secs(5), \"definitions\")"
      , "}" ]
    web ts = unlines $
      [ "// Generated by LawSpec; do not edit. Checked definitions that other nodes"
      , "// can evaluate, by content hash. serve(node) lets other nodes evaluate them"
      , "// on this node; evaluate(node, address, name, ...args) evaluates one on the"
      , "// node at address. Values are logical values, as the runtime's checks use"
      , "// them (integers are bigints)."
      , "import * as ls from './lawspec_runtime." ++ ext ++ "';"
      , "import * as _definitions from './lawspec_definition_bodies." ++ ext ++ "';"
      , ""
      , "const TYPES = ls.valuesFrom(" ++ quote (unwords (forms ++ ["(unit)"])) ++ ")[0];"
      , "const d = (text" ++ typed "string" ++ ")" ++ typed "any" ++ " => ls.readDescriptor(text)[0];"
      , ""
      , "/** name: [content hash, function, argument descriptors, result descriptor] */"
      , "export const DEFINITIONS" ++ typed "Record<string, [string, (...args: any[]) => any, any[], any]>" ++ " = {" ] ++
      [ "  " ++ quote (remoteName r) ++ ": [" ++ quote (remoteDigest r) ++ ", " ++ wrap call ++ ", [" ++
        intercalate ", " ["d(" ++ quote x ++ ")" | x <- remoteArguments r] ++ "], d(" ++ quote (remoteResult r) ++ ")],"
      | r <- remotes, Just call <- [callable r] ] ++
      [ "};"
      , ""
      , "/** Lets other nodes evaluate these definitions on node. */"
      , "export function serve(node" ++ typed "ls.Node" ++ ")" ++ typed "string" ++ " {"
      , "  const table" ++ typed "Record<string, [any, any[], any]>" ++ " = {};"
      , "  for (const [h, f, a, r] of Object.values(DEFINITIONS)) table[h] = [f, a, r];"
      , "  return node.serveDefinitions(table, TYPES);"
      , "}"
      , ""
      , "/** The content hash of the definition with this qualified name. */"
      , "export function digest(name" ++ typed "string" ++ ")" ++ typed "string" ++ " {"
      , "  return DEFINITIONS[name][0];"
      , "}"
      , ""
      , "/**"
      , " * Evaluates the named definition on the node at address, by its content"
      , " * hash; rejects with ls.Unreachable when that node does not answer."
      , " */"
      , "export function evaluate(node" ++ typed "ls.Node" ++ ", address" ++ typed "string" ++ ", name" ++ typed "string" ++ ", ...args" ++ typed "any[]" ++ ")" ++ typed "Promise<any>" ++ " {"
      , "  const [h, , a, r] = DEFINITIONS[name];"
      , "  return node.evaluate(address, h, args, a, r, TYPES);"
      , "}" ]
      where
        ext = if ts then "js" else "mjs"
        typed t = if ts then ": " ++ t else ""
        wrap call = case stripAwait call of
          (True, f) -> "async (...args" ++ typed "any[]" ++ ") => " ++ callee f ++ "(new Map(), ...args)"
          (False, f) -> "(...args" ++ typed "any[]" ++ ") => " ++ callee f ++ "(new Map(), ...args)"
        callee f = if ts then "(" ++ f ++ " as any)" else f
        stripAwait c = if take 6 c == "await " then (True, drop 6 c) else (False, c)
    haskell = haskellRemote forms [(r, call) | r <- remotes, Just call <- [callable r]]

-- | The Haskell module LawSpecRemote: definitions, serve, digest and
-- evaluate, over logical values (LS.Scalar).
haskellRemote :: [String] -> [(Remote, String)] -> String
haskellRemote forms entries = unlines $
  [ "-- Generated by LawSpec. Do not edit."
  , "-- | Checked definitions that other nodes can evaluate, by content hash."
  , "--"
  , "-- serve lets other nodes evaluate them on a node; evaluate evaluates one,"
  , "-- by its qualified name, on the node at an address. Values are logical"
  , "-- values (LS.Scalar), as the runtime's checks use them."
  , "module LawSpecRemote (definitions, types, serve, digest, evaluate) where"
  , ""
  , "import qualified Prelude as P"
  , "import qualified Control.Exception as E"
  , "import qualified LawSpecRuntime as LS"
  , "import qualified LawSpecDefinitionBodies as Definitions"
  , ""
  , "-- | The data types the descriptors use."
  , "types :: LS.DataTable"
  , "types = [(LS.descriptorName n, f) | f@(LS.DescList (LS.DescAtom \"data\" : n : _)) <- LS.readDescriptor " ++ show (unwords forms) ++ "]"
  , ""
  , "d :: P.String -> LS.Descriptor"
  , "d text = case LS.readDescriptor text of"
  , "  form : _ -> form"
  , "  [] -> P.error \"empty descriptor\""
  , ""
  , "call :: (LS.SymbolContext -> [LS.Scalar] -> P.Either P.String LS.Scalar) -> [LS.Scalar] -> P.IO LS.Scalar"
  , "call f args = do"
  , "  symbols <- LS.newSymbolContext"
  , "  P.either (E.throwIO P.. E.ErrorCall) P.pure (f symbols args)"
  , ""
  , "-- | Each definition by qualified name: its content hash, function,"
  , "-- argument descriptors and result descriptor."
  , "definitions :: [(P.String, (P.String, [LS.Scalar] -> P.IO LS.Scalar, [LS.Descriptor], LS.Descriptor))]"
  , "definitions =" ] ++
  zipWith (\i (r, f) -> (if i == (0 :: Int) then "  [ " else "  , ") ++ "(" ++ show (remoteName r) ++ ", (" ++ show (remoteDigest r) ++
      ", call (\\s a -> case a of { [" ++ intercalate ", " (args r) ++ "] -> " ++ unwords (f : "s" : args r) ++
      "; _ -> P.Left \"wrong number of arguments\" }), [" ++ intercalate ", " ["d " ++ show x | x <- remoteArguments r] ++ "], d " ++
      show (remoteResult r) ++ "))") [0 ..] entries ++
  [ "  ]" | not (null entries) ] ++ [ "  []" | null entries ] ++
  [ ""
  , "-- | Lets other nodes evaluate these definitions on a node."
  , "serve :: LS.Node -> P.IO P.String"
  , "serve node = LS.serveDefinitions node types [(h, f, a, r) | (_, (h, f, a, r)) <- definitions]"
  , ""
  , "-- | The content hash of the definition with this qualified name."
  , "digest :: P.String -> P.Maybe P.String"
  , "digest name = (\\(h, _, _, _) -> h) P.<$> P.lookup name definitions"
  , ""
  , "-- | Evaluates the named definition on the node at an address, by its"
  , "-- content hash, waiting up to 5 seconds (LS.Unreachable after that)."
  , "evaluate :: LS.Node -> P.String -> P.String -> [LS.Scalar] -> P.IO LS.Scalar"
  , "evaluate node address name args = case P.lookup name definitions of"
  , "  P.Just (h, _, a, r) -> LS.evaluateRemote node address h args a r types 5"
  , "  P.Nothing -> E.throwIO (E.ErrorCall (\"no definition \" P.++ name))" ]
  where args r = ["x" ++ show k | k <- [0 .. length (remoteArguments r) - 1]]
