-- Remote evaluation. Every checked definition whose types have wire
-- descriptors can be evaluated by another node, by its content hash: the
-- Merkle digest of the definition and everything it reaches (see
-- LawSpec.Dependencies), so two nodes agree on a hash exactly when they hold
-- the same definition. Each target generates a small module, lawspec_remote,
-- mapping each hash to its definition and descriptors, with serve(node) and
-- evaluate(node, address, name, args...).
module LawSpec.Remote (Remote(..), remoteManifest, remoteArtifacts) where

import Control.Monad (foldM)
import Data.List (intercalate)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import qualified LawSpec.Dependencies as D
import LawSpec.Digest (digestHex)
import LawSpec.MachineSpec (describe)
import LawSpec.Testing (Plan(..), PlannedUnit(..))

data Remote = Remote
  { remoteId :: C.Id
  -- The definition's qualified name, such as example.actors::modelDeposit.
  , remoteName :: String
  , remoteDigest :: String
  , remoteArguments :: [String]
  , remoteResult :: String
  }

-- The data types the descriptors use, and each definition that can be
-- evaluated remotely. Orchestrations (which call adapters) and definitions
-- over types without descriptors are left out.
remoteManifest :: Plan -> ([String], [Remote])
remoteManifest plan = (map snd (reverse table), reverse remotes)
  where
    units = map plannedUnit (plannedUnits plan)
    graph = D.dependencyGraph (planDataDeclarations plan) units
    bits = planMachineBits plan
    datas = planDataDeclarations plan
    (table, remotes) = foldl add ([], []) [d | u <- units, d <- C.unitDefinitions u, not (C.definitionOrchestrates d)]
    add (t, acc) d =
      let declaration = C.definitionDeclaration d
          identity = C.declarationId declaration
          (args, result) = C.functionType (C.declarationType declaration)
          described = do
            (ds, t') <- foldM (\(xs, tt) ty -> (\(x, tt') -> (xs ++ [x], tt')) <$> describe bits datas tt ty) ([], t) args
            (r, t'') <- describe bits datas t' result
            pure (ds, r, t'')
      in case (described, D.nodeDigest graph (D.DeclarationNode identity)) of
        (Right (ds, r, t'), Just h) -> (t', Remote identity (C.idText identity) (digestHex h) ds r : acc)
        _ -> (t, acc)

-- The target's lawspec_remote module, given how the target calls each
-- checked definition on logical values.
remoteArtifacts :: String -> [(C.Id, String)] -> Plan -> [Artifact]
remoteArtifacts target calls plan = case (target, remotes) of
  (_, []) -> []
  ("python", _) -> [Artifact "src/lawspec_remote.py" python "generated" "source"]
  ("haskell", _) -> [Artifact "src/LawSpecRemote.hs" haskell "generated" "source"]
  _ -> []
  where
    (forms, remotes) = remoteManifest plan
    callable r = lookup (remoteId r) calls
    quote s = show s
    python = unlines $
      [ "# Generated by LawSpec. Do not edit."
      , "\"\"\"Checked definitions that other nodes can evaluate, by content hash."
      , ""
      , "serve(node) lets other nodes evaluate them on this node; evaluate(node,"
      , "address, name, *args) evaluates one on the node at address. Values are"
      , "logical values, as the runtime's checks use them."
      , "\"\"\""
      , "import lawspec_runtime as ls"
      , "import lawspec_definition_bodies as _definitions"
      , ""
      , if null forms then "TYPES = ls.Values({})"
        else "TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ quote (unwords forms) ++ ")})"
      , ""
      , "# name: (content hash, function, argument descriptors, result descriptor)"
      , "DEFINITIONS = {" ] ++
      [ "    " ++ quote (remoteName r) ++ ": (" ++ quote (remoteDigest r) ++ ", lambda *args: " ++ call ++ "({}, *args), " ++
        "[" ++ intercalate ", " [descriptor d | d <- remoteArguments r] ++ "], " ++ descriptor (remoteResult r) ++ "),"
      | r <- remotes, Just call <- [callable r] ] ++
      [ "}"
      , ""
      , ""
      , "def serve(node):"
      , "    \"\"\"Lets other nodes evaluate these definitions on node.\"\"\""
      , "    return node.serve_definitions({h: (f, a, r) for h, f, a, r in DEFINITIONS.values()}, TYPES)"
      , ""
      , ""
      , "def digest(name):"
      , "    \"\"\"The content hash of the definition with this qualified name.\"\"\""
      , "    return DEFINITIONS[name][0]"
      , ""
      , ""
      , "def evaluate(node, address, name, *args, timeout=5.0):"
      , "    \"\"\"Evaluates the named definition on the node at address, by its"
      , "    content hash; raises Unreachable when that node does not answer.\"\"\""
      , "    h, _, a, r = DEFINITIONS[name]"
      , "    return node.evaluate(address, h, list(args), a, r, TYPES, timeout=timeout)" ]
    descriptor d = "ls.read_descriptor(" ++ quote d ++ ")[0]"
    haskell = haskellRemote forms [(r, call) | r <- remotes, Just call <- [callable r]]

-- | The Haskell module LawSpecRemote: definitions, serve, digest and
-- evaluate, over logical values (LS.Scalar).
haskellRemote :: [String] -> [(Remote, String)] -> String
haskellRemote forms entries = unlines $
  [ "-- Generated by LawSpec. Do not edit."
  , "-- | Checked definitions that other nodes can evaluate, by content hash."
  , "--"
  , "-- serve lets other nodes evaluate them on a node; evaluate evaluates one,"
  , "-- by its qualified name, on the node at an address. Values are logical"
  , "-- values (LS.Scalar), as the runtime's checks use them."
  , "module LawSpecRemote (definitions, types, serve, digest, evaluate) where"
  , ""
  , "import qualified Prelude as P"
  , "import qualified Control.Exception as E"
  , "import qualified LawSpecRuntime as LS"
  , "import qualified LawSpecDefinitionBodies as Definitions"
  , ""
  , "-- | The data types the descriptors use."
  , "types :: LS.DataTable"
  , "types = [(LS.descriptorName n, f) | f@(LS.DescList (LS.DescAtom \"data\" : n : _)) <- LS.readDescriptor " ++ show (unwords forms) ++ "]"
  , ""
  , "d :: P.String -> LS.Descriptor"
  , "d text = case LS.readDescriptor text of"
  , "  form : _ -> form"
  , "  [] -> P.error \"empty descriptor\""
  , ""
  , "call :: (LS.SymbolContext -> [LS.Scalar] -> P.Either P.String LS.Scalar) -> [LS.Scalar] -> P.IO LS.Scalar"
  , "call f args = do"
  , "  symbols <- LS.newSymbolContext"
  , "  P.either (E.throwIO P.. E.ErrorCall) P.pure (f symbols args)"
  , ""
  , "-- | Each definition by qualified name: its content hash, function,"
  , "-- argument descriptors and result descriptor."
  , "definitions :: [(P.String, (P.String, [LS.Scalar] -> P.IO LS.Scalar, [LS.Descriptor], LS.Descriptor))]"
  , "definitions =" ] ++
  zipWith (\i (r, f) -> (if i == (0 :: Int) then "  [ " else "  , ") ++ "(" ++ show (remoteName r) ++ ", (" ++ show (remoteDigest r) ++
      ", call (\\s a -> case a of { [" ++ intercalate ", " (args r) ++ "] -> " ++ unwords (f : "s" : args r) ++
      "; _ -> P.Left \"wrong number of arguments\" }), [" ++ intercalate ", " ["d " ++ show x | x <- remoteArguments r] ++ "], d " ++
      show (remoteResult r) ++ "))") [0 ..] entries ++
  [ "  ]" | not (null entries) ] ++ [ "  []" | null entries ] ++
  [ ""
  , "-- | Lets other nodes evaluate these definitions on a node."
  , "serve :: LS.Node -> P.IO P.String"
  , "serve node = LS.serveDefinitions node types [(h, f, a, r) | (_, (h, f, a, r)) <- definitions]"
  , ""
  , "-- | The content hash of the definition with this qualified name."
  , "digest :: P.String -> P.Maybe P.String"
  , "digest name = (\\(h, _, _, _) -> h) P.<$> P.lookup name definitions"
  , ""
  , "-- | Evaluates the named definition on the node at an address, by its"
  , "-- content hash, waiting up to 5 seconds (LS.Unreachable after that)."
  , "evaluate :: LS.Node -> P.String -> P.String -> [LS.Scalar] -> P.IO LS.Scalar"
  , "evaluate node address name args = case P.lookup name definitions of"
  , "  P.Just (h, _, a, r) -> LS.evaluateRemote node address h args a r types 5"
  , "  P.Nothing -> E.throwIO (E.ErrorCall (\"no definition \" P.++ name))" ]
  where args r = ["x" ++ show k | k <- [0 .. length (remoteArguments r) - 1]]
