-- | Reusable generated definitions: native public signatures, checked logical
-- implementation bodies, and no dependency on a property-testing framework.
module LawSpec.RustDefinitions (operationBridges, abilityTrait, emitRustDefinitions, definitionNames, workflowAdapterUnits) where

import Data.List (intercalate)
import LawSpec.Core.Policy
import Control.Monad (forM)
import Data.Char (isAlphaNum)
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import qualified LawSpec.RustData as Native
import qualified LawSpec.RustAbilityPaths as Abilities
import LawSpec.AbilityNames (interfaceName)
import qualified LawSpec.RustExpr as E
import qualified LawSpec.Code.Doc as D

-- | Package-wide resolved IDs, not display names, select implementation bodies.
definitionNames :: [Unit] -> [(Id,String)]
definitionNames units = [(declarationId (definitionDeclaration d),"evaluate_" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

-- | The adapters workflows call, numbered for their bridges, with their units.
adapterCallsOf :: [Unit] -> [(Int, (Id, Declaration))]
adapterCallsOf units = zip [0::Int ..] (nubIds
  [ (unitId u, a) | d <- concatMap unitDefinitions units, definitionOrchestrates d
  , callee <- callsIn (definitionBody d), u <- units, a <- unitDeclarations u
  , declarationId a == callee, callee `notElem` definitionIds ])
  where
    definitionIds = map (declarationId . definitionDeclaration) (concatMap unitDefinitions units)
    nubIds = foldr (\x acc -> if any ((== declarationId (snd x)) . declarationId . snd) acc then acc else x : acc) []
    callsIn expression = case expressionNode expression of
      ExternalCall callee arguments -> callee : concatMap callsIn arguments
      _ -> concatMap callsIn (children expression)

-- | The units whose adapter modules the definitions file calls.
workflowAdapterUnits :: [Unit] -> [Id]
workflowAdapterUnits units = foldr (\x acc -> if x `elem` acc then acc else x : acc) []
  [owner | (_, (owner, _)) <- adapterCallsOf units]

-- The bridge of each ability operation (LawSpec.AbilityEmit.Rust), by
-- identity, from the crate root.
operationBridges :: [Unit] -> [(Id, String)]
operationBridges = Abilities.performBridges

-- An ability's trait, from the crate root.
abilityTrait :: [Unit] -> AbilityRef -> String
abilityTrait units ref = case Abilities.traitPath units ref of
  "dyn std::any::Any" -> "std::any::Any"
  path -> path

-- | Checked definitions are emitted as ordinary Rust code, so adapters and tests call
-- the same proved implementation. ref:DEC-total-definitions
emitRustDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String String
emitRustDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  implementations <- mapM (implementation contracts) (concatMap unitDefinitions units)
  bridges <- mapM bridge adapterCalls
  modules <- forM (filter (not . null . unitDefinitions) units) $ \unit -> do
    functions <- mapM native (unitDefinitions unit)
    pure (D.text ("pub mod " ++ moduleName unit ++ " ") <> D.block 4
      (D.text "use super::ls;" <> D.hardline <> D.hardline <>
        D.joinWith (D.hardline <> D.hardline) functions))
  pure (D.render layout (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
    D.text "#![allow(unused_variables, dead_code, non_snake_case)]" <> D.hardline <>
    D.text "use crate::lawspec_runtime as ls;" <> D.hardline <> D.hardline <>
    D.joinWith (D.hardline <> D.hardline) (modules ++ implementations ++ bridges) <> D.hardline))
  where
    -- Workflows call adapters natively, each through a bridge that converts
    -- checked values to native ones and back.
    adapterCalls = adapterCallsOf units
    names = definitionNames units ++ [(declarationId a, "adapter_call_" ++ show i) | (i, (_, a)) <- adapterCalls] ++
      -- Each operation's bridge finds the handler installed in the context.
      [(identity, "crate::" ++ path) | (identity, path) <- operationBridges units]
    bridge (i, (owner, a)) = do
      let (args,result) = functionType (declarationType a)
      types <- mapM (Native.rustDataType declarations) args
      resultType <- Native.rustDataType declarations result
      refs <- mapM E.reference args
      let decode n (ty, ref) = D.text ("let native_" ++ show n ++ " = ") <> E.call ("<" ++ ty ++ " as ls::FromValue>::from_value")
            [E.call "schema.native_value_with_context" [D.text ("arguments[" ++ show n ++ "].clone()"), D.text "&" <> ref, D.text (show bits), D.text "ctx"] <> D.text "?"] <> D.text "?;"
          -- An adapter that uses abilities gets their handlers first.
          uses = [ability | ability <- declarationUses a, not (isFail ability)]
          handlerBindings = [D.text ("let handler_" ++ show k ++ " = ctx.handler::<std::sync::Arc<dyn crate::" ++ abilityTrait units ability ++ ">>(" ++ show (abilityKey ability) ++ ")?;")
            | (k, ability) <- zip [0 :: Int ..] uses]
          handlers = [D.text ("&*handler_" ++ show k) | k <- [0 .. length uses - 1]]
          plainCall = E.call ("crate::" ++ ownerModule owner ++ "::" ++ declarationName a) (handlers ++ [D.text ("native_" ++ show n) | n <- [0 .. length args - 1]])
          -- An adapter that fails with E: its native code calls ls::fail.
          call = case [(ability, failure) | ability@(AbilityRef _ [failure]) <- declarationUses a, isFail ability] of
            (ability, failure) : _ -> E.call ("ls::native_failures::<" ++ either error id (Native.rustDataType declarations failure) ++ ", _>")
              [D.text (show (abilityKey ability)), D.text "|native| ls::IntoValue::into_value(native)", D.text "|| " <> plainCall,
               D.text (Abilities.mappedFailures Nothing [b | u <- units, unitId u == owner, b <- unitFailureBindings u] failure)]
            [] -> plainCall
          -- An async step runs within its stage's timeout and hedge, when it
          -- has them; each hedged attempt starts from copies of the inputs.
          started = E.call ("crate::" ++ ownerModule owner ++ "::" ++ declarationName a) [D.text ("native_" ++ show n ++ ".clone()") | n <- [0 .. length args - 1]]
          finish
            | declarationAsync a = [E.call "ls::await_step" [D.text "ctx", D.text "|| " <> started,
                D.text ("|native_result: " ++ resultType ++ "| ls::IntoValue::into_value(native_result)")]]
            | otherwise = [D.text ("let native_result: " ++ resultType ++ " = ") <> call <> D.text ";",
                D.text "Ok(ls::IntoValue::into_value(native_result))"]
      pure (D.text ("fn adapter_call_" ++ show i) <>
        D.delimitTrailing 4 "(" ")" [D.text "ctx: &mut ls::Context", D.text "arguments: Vec<ls::Value>"] <>
        D.text " -> ls::Result<ls::Value> " <> D.block 4 (D.joinWith D.hardline
          ([D.text "let schema = crate::lawspec_schema::schema()?;"] ++ zipWith decode [0::Int ..] (zip types refs) ++ handlerBindings ++ finish)))
    evaluator identity = maybe (Left "unresolved Rust policy definition") Right (lookup identity names)
    policyDoc key policy = do
      gates <- policyGates policy
      compensate <- case policyCompensate policy of
        Nothing -> pure (D.text "None")
        Just undo -> (\name -> D.text ("Some(|ctx: &mut ls::Context, value: ls::Value| -> ls::Result<ls::Value> { " ++ name ++ "(ctx, vec![value]) })")) <$> evaluator undo
      retry <- case policyRetry policy of
        Nothing -> pure (D.text "None")
        Just r -> do
          let (kind, delay, step, factor, cap) = case retryStrategy r of
                Immediate -> ("immediate", 0, 0, 0, -1)
                Fixed d' -> ("fixed", d', 0, 0, -1)
                Linear d' s -> ("linear", d', s, 0, -1)
                Exponential d' f c -> ("exponential", d', 0, f, maybe (-1) id c)
                Fibonacci d' -> ("fibonacci", d', 0, 0, -1)
                Custom _ -> ("custom", 0, 0, 0, -1)
          condition <- case retryWhen r of
            Nothing -> pure (D.text "None")
            Just p -> (\name -> D.text ("Some(|ctx: &mut ls::Context, failure: ls::Value| -> ls::Result<bool> { " ++ name ++
              "(ctx, vec![failure])?.boolean() })")) <$> evaluator p
          decide <- case retryStrategy r of
            Custom f -> (\name -> D.text ("Some(|ctx: &mut ls::Context, attempt: i64, failure: ls::Value, previous: i64| -> ls::Result<Option<i64>> { " ++
              "ls::retry_decision(" ++ name ++ "(ctx, vec![ls::Value::Integer(ls::BigInt::from(attempt)), failure, ls::duration(previous)])?) })")) <$> evaluator f
            _ -> pure (D.text "None")
          pure (D.text "Some(ls::Retry " <> D.block 4 (D.joinWith D.hardline
            [ D.text ("strategy: " ++ show (kind :: String) ++ ",")
            , D.text ("delay: " ++ show (delay :: Integer) ++ ", step: " ++ show (step :: Integer) ++ ", factor: " ++ show (factor :: Integer) ++ ", cap: " ++ show (cap :: Integer) ++ ",")
            , D.text ("attempts: " ++ show (retryAttempts r) ++ ",")
            , D.text ("jitter: " ++ show (jitterName (retryJitter r)) ++ ",")
            , D.text "when: " <> condition <> D.text ","
            , D.text "decide: " <> decide <> D.text "," ]) <> D.text ")")
      pure (D.text "ls::StagePolicy " <> D.block 4 (D.joinWith D.hardline
        [ D.text ("stage: " ++ show (policyStage policy) ++ ",")
        , D.text "retry: " <> retry <> D.text ","
        , D.text ("timeout: " ++ show (maybe (-1) id (policyTimeout policy)) ++ ",")
        , D.text ("key: " ++ show key ++ ",")
        , D.text "gates: vec!" <> D.delimitTrailing 4 "[" "]" gates <> D.text ","
        , D.text ("cache: " ++ show (maybe (-1) id (policyCache policy)) ++ ",")
        , D.text ("wraps: " ++ (if null (policyFailures policy) then "false" else "true") ++ ",")
        , D.text "compensate: " <> compensate <> D.text ","
        , D.text ("hedge: " ++ maybe "None" (\h -> "Some((" ++ show (hedgeDelay h) ++ ", " ++ show (hedgeMost h) ++ "))") (policyHedge policy) ++ ",") ]))
    -- A gate's callbacks call the unit's copies of the resilience unit's
    -- state machines, with the policy's numbers.
    policyGates policy = do
      breaker <- forM (policyBreaker policy) $ \b -> do
        start <- evaluator (breakerStart b)
        admit <- evaluator (breakerAdmit b)
        record <- evaluator (breakerRecord b)
        pure (gateDoc "breaker" (start ++ "(ctx, vec![" ++ nowValue ++ "])") (admit ++ "(ctx, vec![state, " ++ nowValue ++ "])")
          (Just (record ++ "(ctx, vec![" ++ integers [breakerFailures b, breakerWindow b, breakerCooldown b] ++ ", state, " ++ nowValue ++ ", ls::Value::Bool(succeeded)])")) (-2))
      limit <- forM (policyLimit policy) $ \l -> do
        start <- evaluator (limitStart l)
        admit <- evaluator (limitAdmit l)
        let numbers = integers [limitCount l, limitPeriod l]
        pure (gateDoc "limit" (start ++ "(ctx, vec![" ++ numbers ++ ", " ++ nowValue ++ "])")
          (admit ++ "(ctx, vec![" ++ numbers ++ ", state, " ++ nowValue ++ "])") Nothing (waitCode (limitWait l)))
      bulkhead <- forM (policyBulkhead policy) $ \b -> do
        start <- evaluator (bulkheadStart b)
        admit <- evaluator (bulkheadAdmit b)
        release <- evaluator (bulkheadRelease b)
        let n = integers [bulkheadLimit b]
        pure (gateDoc "bulkhead" (start ++ "(ctx, vec![" ++ n ++ ", " ++ nowValue ++ "])")
          (admit ++ "(ctx, vec![" ++ n ++ ", state, " ++ nowValue ++ "])") (Just (release ++ "(ctx, vec![state])")) (waitCode (bulkheadWait b)))
      pure (maybe [] pure breaker ++ maybe [] pure limit ++ maybe [] pure bulkhead)
    nowValue = "ls::Value::Integer(ls::BigInt::from(now))"
    integers numbers = intercalate ", " ["ls::Value::Integer(ls::BigInt::from(" ++ show n ++ "i64))" | n <- numbers]
    gateDoc kind start admit finish wait = D.text "ls::Gate " <> D.block 4 (D.joinWith D.hardline
      [ D.text ("kind: " ++ show (kind :: String) ++ ",")
      , D.text ("start: |ctx: &mut ls::Context, now: i64| -> ls::Result<ls::Value> { " ++ start ++ " },")
      , D.text ("admit: |ctx: &mut ls::Context, state: ls::Value, now: i64| -> ls::Result<ls::Value> { " ++ admit ++ " },")
      , D.text ("finish: " ++ maybe "None" (\f -> "Some(|ctx: &mut ls::Context, state: ls::Value, now: i64, succeeded: bool| -> ls::Result<ls::Value> { " ++ f ++ " })") finish ++ ",")
      , D.text ("wait: " ++ show (wait :: Integer) ++ ",") ])
    waitCode wait = case wait of
      Nothing -> -2
      Just Nothing -> -1
      Just (Just d') -> d'
    jitterName j = case j of
      NoJitter -> "none" :: String
      FullJitter -> "full"
      EqualJitter -> "equal"
      DecorrelatedJitter -> "decorrelated"
    lowerFirst (c:cs) = toEnum (fromEnum c + (if c >= 'A' && c <= 'Z' then 32 else 0)) : cs
    lowerFirst [] = []
    ownerModule = map (\c -> if isAlphaNum c || c == '_' then c else '_') . idText
    moduleName = map (\c -> if isAlphaNum c || c == '_' then c else '_') . idText . unitId
    nameFor d = maybe (Left "unresolved Rust total definition") Right
      (lookup (declarationId (definitionDeclaration d)) names)
    native d = do
      name <- nameFor d
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
      types <- mapM (Native.rustDataType declarations) args
      resultType <- Native.rustDataType declarations result
      resultRef <- E.reference result
      let values = [D.text ("value" ++ show i) | i <- [0 .. length args - 1]]
          -- A handler's parameter is named for its ability; Async's is r#async.
          handlers = [ (ability, rawKeyword (lowerFirst (interfaceName a))) | ability <- declarationUses declaration, not (isFail ability)
                     , Just (_, a) <- [findAbility units ability] ]
          parameters = D.text "ctx: &mut ls::Context" :
            [D.text (name ++ ": std::sync::Arc<dyn crate::" ++ abilityTrait units ability ++ ">") | (ability, name) <- handlers] ++
            [D.text ("value" ++ show i ++ ": " ++ ty) | (i,ty) <- zip [0::Int ..] types]
          -- Native code passes a definition's handlers explicitly; they are
          -- installed in the context, where its operations find them.
          installs = [D.text ("ctx.install_handlers(vec![" ++ intercalate ", " ["(" ++ show (abilityKey ability) ++ ".to_string(), ls::installed(" ++ name ++ "))" | (ability, name) <- handlers] ++ "]);")
                     | not (null handlers)]
          signature = D.text ("pub fn " ++ declarationName declaration) <>
            D.delimitTrailing 4 "(" ")" parameters <> D.text (" -> ls::Result<" ++ resultType ++ "> ")
          architecture = [E.call "ls::require_architecture" [D.text (show bits)] <> D.text "?;"
            | nativeMachine [] (declarationType declaration)]
          body = architecture ++ installs ++
            [D.text "let arguments = " <> E.vector (map (\value -> E.call "ls::IntoValue::into_value" [value]) values) <> D.text ";"
            ,D.text "let result = " <> E.call ("super::" ++ name) [D.text "ctx",D.text "arguments"] <> D.text "?;"
            ,D.text "let schema = crate::lawspec_schema::schema()?;"
            ,D.text "let result = " <> E.call "schema.native_value_with_context" [D.text "result",D.text "&" <> resultRef,D.text (show bits),D.text "ctx"] <> D.text "?;"
            ,E.call ("<" ++ resultType ++ " as ls::FromValue>::from_value") [D.text "result"]]
      pure (signature <> D.block 4 (D.joinWith D.hardline body))
    implementation contracts d = do
      name <- nameFor d
      let args = definitionArguments d
          locals = [(binderId b,"argument_" ++ show i) | (i,b) <- zip [0::Int ..] args]
          signature = D.text ("pub(crate) fn " ++ name) <>
            D.delimitTrailing 4 "(" ")" [D.text "ctx: &mut ls::Context",D.text "arguments: Vec<ls::Value>"] <>
            D.text " -> ls::Result<ls::Value> "
      -- Arguments and results were checked where they were built, decoded
      -- or drawn; the native wrappers check values crossing from adapters.
      let checks = [D.text ("let " ++ local ++ " = arguments.next().unwrap();") | (_,(_,local)) <- zip args locals]
      rendered <- E.renderExpression declarations bits names locals (definitionBody d)
      -- A workflow stage with policies runs under the workflow runtime.
      body <- case definitionPolicy d of
        Nothing -> pure rendered
        Just policy | policyFrame policy ->
          pure (E.call "ls::run_workflow" [D.text "ctx",
            D.text "|ctx: &mut ls::Context| -> ls::Result<ls::Value> " <> D.block 4 (D.text "Ok(" <> rendered <> D.text ")")] <> D.text "?")
        Just policy -> do
          config <- policyDoc (idText (declarationId (definitionDeclaration d))) policy
          let key = case locals of
                (_, local) : _ -> D.text (local ++ ".clone()")
                [] -> D.text "ls::Value::Unit"
          pure (E.call "ls::run_stage" [D.text "ctx", D.text "&" <> config,
            D.text "|ctx: &mut ls::Context| -> ls::Result<ls::Value> " <> D.block 4 (D.text "Ok(" <> rendered <> D.text ")"), key] <> D.text "?")
      let arity = D.text ("if arguments.len() != " ++ show (length args) ++ " ") <>
            D.block 4 (D.text "return Err" <> D.delimitTrailing 4 "(" ")"
              [D.group (D.text (E.quoted
                (idText (declarationId (definitionDeclaration d)) ++ ": definition argument count mismatch")) <>
                D.nest 4 (D.softbreak <> D.text ".into()"))] <> D.text ";")
      let prefix = [arity,D.text "let schema = crate::lawspec_schema::schema()?;",
            D.text "let mut arguments = arguments.into_iter();"] ++ checks
          evaluate = D.text "let result = " <> body <> D.text ";"
          checkedResult = D.text "Ok::<ls::Value, String>(result)"
          contract = lookup (declarationId (definitionDeclaration d))
            [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (prefix ++ [evaluate,checkedResult])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c)) (map snd locals) ++
                [(binderId (contractResult c),"checked")]
              require stage predicate = do
                expression <- E.renderExpression declarations bits names aliases predicate
                pure (D.text "let predicate = " <> expression <> D.text ";" <> D.hardline <>
                  D.text "if !predicate.boolean()? " <> D.block 4
                    (D.text "return " <> E.call "Err" [E.stringLiteral (stage ++ " failed") <> D.text ".into()"] <> D.text ";"))
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          -- Rustfmt hangs a fitting call, but wraps its arguments when the
          -- continuation would reach the right margin (12-column indentation).
          let checkedBinding = if length (D.render D.Compact checkedResult) + 2 < 88
                then D.hang 4 (D.text "let checked =") (checkedResult <> D.text "?;")
                else D.text "let checked = " <> checkedResult <> D.text "?;"
              inner = D.joinWith D.hardline (prefix ++ pre ++ [evaluate,checkedBinding] ++ post ++
                [D.text "Ok(checked)"])
          pure [D.text "let result = (|| " <> D.block 4 inner <> D.text ")();",
            D.text "let context = " <> E.stringLiteral (idText (declarationId (definitionDeclaration d))) <> D.text ";",
            D.text "result.map_err(|error: String| format!(\"{context}: {error}\"))"]
      pure (signature <> D.block 4 (D.joinWith D.hardline statements))
    -- Inspect every variant, including unselected native machine fields.
    nativeMachine seen ty = case ty of
      Constructor name args -> name `elem` ["IntSize","UIntSize","UIntPtr"] ||
        any (\a -> case a of TypeArgument t -> nativeMachine seen t; _ -> False) args ||
        (name `notElem` seen && any (any (any (nativeMachine (name:seen) . binderType) . constructorFields) . dataConstructors)
          (filter ((== Id name) . dataId) declarations))
      Arrow a b -> nativeMachine seen a || nativeMachine seen b
      _ -> False

-- A Rust keyword used as a name, as a raw identifier.
rawKeyword :: String -> String
rawKeyword name
  | name `elem` words "as async await break const continue dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return static struct trait true type unsafe use where while abstract become box do final macro override priv typeof unsized virtual yield try gen union" = "r#" ++ name
  | otherwise = name
