-- Reusable generated definitions: native public signatures, checked logical
-- implementation bodies, and no dependency on a property-testing framework.
module LawSpec.RustDefinitions (emitRustDefinitions, definitionNames) where

import Control.Monad (forM)
import Data.Char (isAlphaNum)
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import qualified LawSpec.RustData as Native
import qualified LawSpec.RustExpr as E
import qualified LawSpec.Code.Doc as D

-- Package-wide resolved IDs, not display names, select implementation bodies.
definitionNames :: [Unit] -> [(Id,String)]
definitionNames units = [(declarationId (definitionDeclaration d),"evaluate_" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitRustDefinitions :: D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String String
emitRustDefinitions layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  implementations <- mapM (implementation contracts) (concatMap unitDefinitions units)
  modules <- forM (filter (not . null . unitDefinitions) units) $ \unit -> do
    functions <- mapM native (unitDefinitions unit)
    pure (D.text ("pub mod " ++ moduleName unit ++ " ") <> D.block 4
      (D.text "use super::ls;" <> D.hardline <> D.hardline <>
        D.joinWith (D.hardline <> D.hardline) functions))
  pure (D.render layout (D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
    D.text "#![allow(unused_variables, dead_code, non_snake_case)]" <> D.hardline <>
    D.text "use crate::lawspec_runtime as ls;" <> D.hardline <> D.hardline <>
    D.joinWith (D.hardline <> D.hardline) (modules ++ implementations) <> D.hardline))
  where
    names = definitionNames units
    moduleName = map (\c -> if isAlphaNum c || c == '_' then c else '_') . idText . unitId
    nameFor d = maybe (Left "unresolved Rust total definition") Right
      (lookup (declarationId (definitionDeclaration d)) names)
    native d = do
      name <- nameFor d
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
      types <- mapM (Native.rustDataType declarations) args
      resultType <- Native.rustDataType declarations result
      resultRef <- E.reference result
      let values = [D.text ("value" ++ show i) | i <- [0 .. length args - 1]]
          parameters = D.text "ctx: &mut ls::Context" :
            [D.text ("value" ++ show i ++ ": " ++ ty) | (i,ty) <- zip [0::Int ..] types]
          signature = D.text ("pub fn " ++ declarationName declaration) <>
            D.delimitTrailing 4 "(" ")" parameters <> D.text (" -> ls::Result<" ++ resultType ++ "> ")
          architecture = [E.call "ls::require_architecture" [D.text (show bits)] <> D.text "?;"
            | nativeMachine [] (declarationType declaration)]
          body = architecture ++
            [D.text "let arguments = " <> E.vector (map (\value -> E.call "ls::IntoValue::into_value" [value]) values) <> D.text ";"
            ,D.text "let result = " <> E.call ("super::" ++ name) [D.text "ctx",D.text "arguments"] <> D.text "?;"
            ,D.text "let schema = crate::lawspec_schema::schema()?;"
            ,D.text "let result = " <> E.call "schema.native_value_with_context" [D.text "result",D.text "&" <> resultRef,D.text (show bits),D.text "ctx"] <> D.text "?;"
            ,E.call ("<" ++ resultType ++ " as ls::FromValue>::from_value") [D.text "result"]]
      pure (signature <> D.block 4 (D.joinWith D.hardline body))
    implementation contracts d = do
      name <- nameFor d
      let args = definitionArguments d
          locals = [(binderId b,"argument_" ++ show i) | (i,b) <- zip [0::Int ..] args]
          signature = D.text ("pub(crate) fn " ++ name) <>
            D.delimitTrailing 4 "(" ")" [D.text "ctx: &mut ls::Context",D.text "arguments: Vec<ls::Value>"] <>
            D.text " -> ls::Result<ls::Value> "
      checks <- forM (zip args locals) $ \(binder,(_,local)) -> do
        ref <- E.reference (binderType binder)
        pure (D.text ("let " ++ local ++ " = ") <>
          E.call "schema.validate_with_context" [D.text "arguments.next().unwrap()",D.text "&" <> ref,D.text (show bits),D.text "ctx"] <> D.text "?;")
      resultRef <- E.reference (expressionType (definitionBody d))
      body <- E.renderExpression declarations bits names locals (definitionBody d)
      let arity = D.text ("if arguments.len() != " ++ show (length args) ++ " ") <>
            D.block 4 (D.text "return Err" <> D.delimitTrailing 4 "(" ")"
              [D.group (D.text (E.quoted
                (idText (declarationId (definitionDeclaration d)) ++ ": definition argument count mismatch")) <>
                D.nest 4 (D.softbreak <> D.text ".into()"))] <> D.text ";")
      let prefix = [arity,D.text "let schema = crate::lawspec_schema::schema()?;",
            D.text "let mut arguments = arguments.into_iter();"] ++ checks
          evaluate = D.text "let result = " <> body <> D.text ";"
          checkedResult = E.call "schema.validate_with_context" [D.text "result",D.text "&" <> resultRef,D.text (show bits),D.text "ctx"]
          contract = lookup (declarationId (definitionDeclaration d))
            [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (prefix ++ [evaluate,checkedResult])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c)) (map snd locals) ++
                [(binderId (contractResult c),"checked")]
              require stage predicate = do
                expression <- E.renderExpression declarations bits names aliases predicate
                pure (D.text "let predicate = " <> expression <> D.text ";" <> D.hardline <>
                  D.text "if !predicate.boolean()? " <> D.block 4
                    (D.text "return " <> E.call "Err" [E.stringLiteral (stage ++ " failed") <> D.text ".into()"] <> D.text ";"))
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          -- Rustfmt hangs a fitting call, but wraps its arguments when the
          -- continuation would reach the right margin (12-column indentation).
          let checkedBinding = if length (D.render D.Compact checkedResult) + 2 < 88
                then D.hang 4 (D.text "let checked =") (checkedResult <> D.text "?;")
                else D.text "let checked = " <> checkedResult <> D.text "?;"
              inner = D.joinWith D.hardline (prefix ++ pre ++ [evaluate,checkedBinding] ++ post ++
                [D.text "Ok(checked)"])
          pure [D.text "let result = (|| " <> D.block 4 inner <> D.text ")();",
            D.text "let context = " <> E.stringLiteral (idText (declarationId (definitionDeclaration d))) <> D.text ";",
            D.text "result.map_err(|error: String| format!(\"{context}: {error}\"))"]
      pure (signature <> D.block 4 (D.joinWith D.hardline statements))
    -- Inspect every variant, including unselected native machine fields.
    nativeMachine seen ty = case ty of
      Constructor name args -> name `elem` ["IntSize","UIntSize","UIntPtr"] ||
        any (\a -> case a of TypeArgument t -> nativeMachine seen t; _ -> False) args ||
        (name `notElem` seen && any (any (any (nativeMachine (name:seen) . binderType) . constructorFields) . dataConstructors)
          (filter ((== Id name) . dataId) declarations))
      Arrow a b -> nativeMachine seen a || nativeMachine seen b
      _ -> False
