-- Rust consumes an execution plan made entirely from typed core.
module LawSpec.RustEmit (emitRust, rustType) where
import LawSpec.Core
import qualified LawSpec.Backend as Presentation
import LawSpec.Common
import LawSpec.Testing
import LawSpec.Scalar
import LawSpec.RuntimeSources
import Data.Char (ord, isAlphaNum, isAscii, toLower)
import Data.List (intercalate, find, nub)
import Numeric (showHex)
import Control.Monad (forM, unless)

q :: String -> String
q s = '"':concatMap escape s ++ "\"" where
  escape '"' = "\\\""
  escape '\\' = "\\\\"
  escape c | ord c < 32 || ord c == 127 = "\\u{" ++ showHex (ord c) "}"
           | otherwise = [c]
comma :: [String] -> String
comma = intercalate ", "
ident :: String -> String
ident = map (\c -> if isAlphaNum c || c == '_' then c else '_')
rustType :: Type -> Either String String
rustType (Constructor n []) = maybe (Left ("no Rust representation for " ++ n)) Right (nativeRepresentation "rust" n)
rustType (Constructor n [TypeArgument a]) | n `elem` ["Nullable","Optional"] = (\t -> "ls::" ++ n ++ "<" ++ t ++ ">") <$> rustType a
rustType t = Left ("no Rust representation for " ++ show t)
rustArgumentType :: Type -> Either String String
rustArgumentType (Constructor "Integer" []) = Right "ls::BigInt"
rustArgumentType (Constructor n [TypeArgument a]) | n `elem` ["Nullable","Optional"] = (\t -> "ls::" ++ n ++ "<" ++ t ++ ">") <$> rustArgumentType a
rustArgumentType t = rustType t
machineType :: Type -> Bool
machineType (Constructor n args) = n `elem` ["IntSize","UIntSize","UIntPtr"] || any (\a -> case a of TypeArgument t -> machineType t; _ -> False) args
machineType (Arrow a b) = machineType a || machineType b
machineType _ = False
typeName :: Type -> String
typeName (Constructor n args) = unwords (n:[typeName t | TypeArgument t <- args])
typeName t = show t

emitRust :: Plan -> Either [Diagnostic] [Artifact]
emitRust Plan{..} = either (Left . pure . (\m -> Diagnostic "rust" m Nothing)) Right $ do
  let declarations = concatMap (unitDeclarations . plannedUnit) plannedUnits
      keywords = words "as async await break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while abstract become box do final macro override priv typeof unsized virtual yield try gen"
  unless (all (\d -> declarationName d `notElem` keywords && all (\c -> isAscii c && (isAlphaNum c || c == '_')) (declarationName d)) declarations) (Left "reserved or invalid Rust adapter identifier")
  unless (all (\u -> let n = ident (idText (unitId (plannedUnit u))) in n `notElem` keywords && all (\c -> isAscii c && (isAlphaNum c || c == '_')) n) plannedUnits) (Left "reserved or invalid Rust module identifier")
  units <- concat <$> mapM emitUnit plannedUnits
  unless (length units == length (nub (map (map toLower . artifactPath) units))) (Left "units map to the same Rust output path")
  let files = units ++
        [ Artifact "src/lawspec_runtime.rs" (runtimeSource "rust") "generated" "source"
        , Artifact "src/lawspec_modules.rs" ("// Generated by LawSpec. Do not edit.\n#[path = \"lawspec_runtime.rs\"] pub mod lawspec_runtime;\n" ++ concat ["#[path = " ++ q (map (\c -> if c == '.' then '/' else c) (idText (unitId (plannedUnit u))) ++ ".rs") ++ "] pub mod " ++ ident (idText (unitId (plannedUnit u))) ++ ";\n" | u <- plannedUnits]) "generated" "source"
        , Artifact "tests/support/lawspec_strategies.rs" (runtimeSource "rust-strategies") "generated" "test"
        ]
  unless (length files == length (nub (map (map toLower . artifactPath) files))) (Left "Rust runtime or module path collision")
  pure files
  where
    bits = show planMachineBits
    emitUnit PlannedUnit{..} = do
      let unit = plannedUnit
          modulePath = map (\c -> if c == '.' then '/' else c) (idText (unitId unit))
          testName = ident (idText (unitId unit))
          declarations = unitDeclarations unit
          declarationNames = [(declarationId d,"call_" ++ show n) | (n,d) <- zip [0::Int ..] declarations]
          localNames p = [(binderId (quantifiedBinder a),"input_" ++ show n) | (n,a) <- zip [0::Int ..] (propertyInputs p)]
          render names e = case expressionNode e of
            Constant v -> literal v
            Local n -> maybe (Left ("unbound Rust binder: " ++ idText n)) (Right . (++ ".clone()")) (lookup n names)
            ExternalCall n args -> do
              fn <- maybe (Left "unknown Rust declaration") Right (lookup n declarationNames)
              xs <- mapM (render names) args
              pure ("{ let args = vec![" ++ comma xs ++ "]; " ++ fn ++ "(ctx, args).map_err(|e| format!(" ++ q (idText n ++ ": {e}") ++ "))? }")
            Binary op evidence a b -> do
              x <- render names a; y <- render names b
              let domain = case evidence of Numeric t -> typeName t; Structural t -> typeName t
              pure ("ls::binary(" ++ q (binaryName op) ++ ", " ++ q domain ++ ", " ++ x ++ ", " ++ y ++ ")?")
            Unary Negate a -> (\x -> "ls::negate(" ++ x ++ ")?") <$> render names a
            Unary Not a -> (\x -> "ls::Value::Bool(!(" ++ x ++ ").boolean()?)") <$> render names a
            ShortCircuit op a b -> do
              x <- render names a; y <- render names b
              pure ("ls::Value::Bool((" ++ x ++ ").boolean()? " ++ (if op == And then "&&" else "||") ++ " (" ++ y ++ ").boolean()?)")
            Convert _ t a -> (\x -> "(" ++ x ++ ").convert(" ++ q (typeName t) ++ ", " ++ bits ++ ")?") <$> render names a
            Helper b args -> do
              xs <- mapM (render names) args
              let name = case b of Length -> "length"; IsPresent -> "isPresent"; PresentValue -> "presentValue"; RealPart -> "real"; ImaginaryPart -> "imag"; IsNaN -> "isNaN"; IsInfinite -> "isInfinite"; IsFinite -> "isFinite"; IsNegativeZero -> "isNegativeZero"; RoundHalfEven -> "round"; Checked -> "checked"
              pure ("ls::helper(" ++ q name ++ ", vec![" ++ comma xs ++ "])?")
          proposition names label indent p = case p of
            Equation _ a b -> do
              x <- render names a; y <- render names b
              pure (indent ++ "{ let left = " ++ x ++ "; let right = " ++ y ++ "; if !ls::equal(&left, &right)? { return Err(format!(" ++ q "{}: {:?} != {:?}" ++ ", " ++ q (label ++ " | expect " ++ Presentation.propositionText p) ++ ", left, right)); } }\n")
            Implication g body -> do
              guard <- render names g
              inner <- proposition names label (indent ++ "  ") body
              pure (indent ++ "if (" ++ guard ++ ").boolean()? {\n" ++ inner ++ indent ++ "}\n")
            Conjunction ps -> concat <$> mapM (proposition names label indent) ps
          predicate names label p = do
            v <- render names p
            pure ("  if !(" ++ v ++ ").boolean()? { return Err(" ++ q label ++ ".into()); }\n")
      stubs <- forM declarations $ \d -> do
        let (args,result) = functionType (declarationType d)
        argTypes <- mapM rustArgumentType args
        resultType <- rustType result
        pure ("pub fn " ++ declarationName d ++ "(" ++ comma ["value" ++ show i ++ ": " ++ t | (i,t) <- zip [0::Int ..] argTypes] ++ ") -> " ++ resultType ++ " { todo!(" ++ q (idText (declarationId d)) ++ ") }\n")
      wrappers <- forM declarations $ \d -> do
        let (args,result) = functionType (declarationType d)
            fn = maybe "missing" id (lookup (declarationId d) declarationNames)
            contract = find ((== declarationId d) . contractDeclaration) (unitContracts unit)
            names = case contract of Nothing -> []; Just c -> [(binderId b,"arg_" ++ show n) | (n,b) <- zip [0::Int ..] (contractArguments c)] ++ [(binderId (contractResult c),"result")]
        args' <- forM (zip [0::Int ..] args) $ \(i,t) -> do
          ty <- rustArgumentType t
          pure $ if typeName t == "CodeUnit16"
            then "match arg_" ++ show i ++ ".clone() { ls::Value::CodeUnit16(x) => x, _ => return Err(\"expected CodeUnit16\".into()) }"
            else "<" ++ ty ++ " as ls::FromValue>::from_value(ls::native_value(arg_" ++ show i ++ ".clone(), " ++ q (typeName t) ++ ")?)?"
        pre <- maybe (Right "") (fmap concat . mapM (predicate names (declarationName d ++ " precondition")) . contractPreconditions) contract
        post <- maybe (Right "") (fmap concat . mapM (predicate names (declarationName d ++ " postcondition")) . contractPostconditions) contract
        let call = "adapter::" ++ declarationName d ++ "(" ++ comma args' ++ ")"
            wrap = if typeName result == "CodeUnit16" then "ls::Value::CodeUnit16(" ++ call ++ ")" else "ls::IntoValue::into_value(" ++ call ++ ")"
        pure ("fn " ++ fn ++ "(ctx: &mut ls::Context, args: Vec<ls::Value>) -> ls::Result<ls::Value> {\n"
          ++ (if machineType (declarationType d) then "  ls::require_architecture(" ++ bits ++ ")?;\n" else "")
          ++ concat ["  let arg_" ++ show i ++ " = args[" ++ show i ++ "].clone();\n" | i <- [0..length args-1]]
          ++ pre ++ "  let result = ls::validate(" ++ wrap ++ ", " ++ q (typeName result) ++ ", " ++ bits ++ ")?;\n" ++ post ++ "  Ok(result)\n}\n")
      tests <- forM (zip [0::Int ..] plannedProperties) $ \(index,pp) -> do
        let p = plannedProperty pp
            names = localNames p
            label = propertyName p
            law = "law_" ++ show index
            args = comma [n ++ ": ls::Value" | (_,n) <- names]
            context = "  let ctx = &mut ls::Context::default();\n"
            inputsFrom values = do xs <- mapM literal values; pure (comma xs)
        body <- proposition names label "  " (propertyBody p)
        valid <- concat <$> forM (concatMap quantifiedPredicates (propertyInputs p)) (\predicateExpr -> do
          term <- render names predicateExpr
          pure ("  if !(" ++ term ++ ").boolean()? { return Ok(false); }\n"))
        strategies <- forM (zip3 [0::Int ..] (propertyInputs p) (generatorRequirements pp)) $ \(i,input,requirement) -> do
          bounds <- forM (quantifiedBounds input) $ \(op,e) -> do
            v <- render names e
            pure ("(" ++ q (binaryName op) ++ ", " ++ v ++ ")")
          hints <- mapM (render names) (generatorHints requirement)
          seeds <- mapM literal (generatorBoundaries requirement)
          let construct = if null bounds
                then "Ok::<_, String>(Some(ls_gen::strategy_with_profile(" ++ q (typeName (binderType (quantifiedBinder input))) ++ ", " ++ bits ++ ")?))"
                else "ls_gen::bounded_integer(" ++ q (typeName (binderType (quantifiedBinder input))) ++ ", vec![" ++ comma bounds ++ "], " ++ bits ++ ")"
          pure ("  let strategy = strategy.prop_flat_map(|mut case| {\n"
            ++ "    if case.values.len() != " ++ show i ++ " { return proptest::strategy::Just(case).boxed(); }\n"
            ++ "    let candidate = (|| -> ls::Result<Option<proptest::strategy::BoxedStrategy<ls::Value>>> {\n"
            ++ "      let ctx = &mut case.context;\n"
            ++ concat ["      let " ++ n ++ " = case.values[" ++ show j ++ "].clone();\n" | (j,(_,n)) <- zip [0::Int ..] (take i names)]
            ++ "      let base = " ++ construct ++ "?;\n"
            ++ "      let seeds = vec![" ++ comma (hints ++ seeds) ++ "];\n      Ok(base.map(|base| ls_gen::seeded(base, seeds)))\n    })().unwrap_or_else(|e| panic!(\"{e}\"));\n"
            ++ "    match candidate { Some(s) => (proptest::strategy::Just(case), s).prop_map(|(mut case,x)| { case.values.push(x); case }).boxed(), None => {case.values.clear(); proptest::strategy::Just(case).boxed()} }\n  }).boxed();\n")
        fixed <- concat <$> forM (maybe (boundaryCases pp) id (finiteCases pp)) (\values -> do
          callArgs <- inputsFrom values
          pure ("  { let ctx = &mut ls::Context::default(); let values = vec![" ++ callArgs ++ "]; " ++ law ++ "(ctx, " ++ comma ["values[" ++ show i ++ "].clone()" | i <- [0..length names-1]] ++ ")?; }\n"))
        examples <- concat <$> forM (propertyExamples p) (\e -> do
          bindings <- forM (exampleBindings e) $ \(i,x) -> do
            value <- render [] x
            n <- maybe (Left "unbound example input") Right (lookup i names)
            pure ("    let " ++ n ++ " = " ++ value ++ ";\n")
          checks <- concat <$> mapM (proposition names (label ++ " example " ++ exampleName e) "    ") (exampleExpectations e)
          lawCheck <- proposition names label "    " (propertyBody p)
          pure ("  { let ctx = &mut ls::Context::default();\n" ++ concat bindings ++ checks ++ lawCheck ++ "  }\n"))
        let predicateFn = "valid_" ++ show index
            tupleArgs = comma ["case.values[" ++ show n ++ "].clone()" | n <- [0..length names-1]]
            random = case finiteCases pp of
              Just _ -> ""
              Nothing -> "  let strategy = proptest::strategy::Just(ls_gen::Case::default()).boxed();\n" ++ concat strategies
                ++ "  let strategy = strategy.prop_filter(" ++ q (label ++ " refinement") ++ ", |case| case.values.len() == " ++ show (length names) ++ " && " ++ predicateFn ++ "(&mut case.context.clone(), " ++ tupleArgs ++ ").unwrap_or_else(|e| panic!(\"{e}\")));\n"
                ++ "  let config = proptest::test_runner::Config { cases: " ++ show (cases (propertyGeneration p)) ++ ", max_global_rejects: " ++ show (maxAttempts (propertyGeneration p)) ++ ", max_shrink_iters: " ++ show (maxShrinks (propertyGeneration p)) ++ ", ..Default::default() };\n"
                ++ "  proptest::test_runner::TestRunner::new(config).run(&strategy, |mut case| " ++ law ++ "(&mut case.context, " ++ tupleArgs ++ ").map_err(proptest::test_runner::TestCaseError::fail)).map_err(|e| format!(\"{e}\"))?;\n"
        pure (Presentation.metadata "//" pp ++ "fn " ++ law ++ "(ctx: &mut ls::Context, " ++ args ++ ") -> ls::Result<()> {\n" ++ body ++ "  Ok(())\n}\n"
          ++ "fn " ++ predicateFn ++ "(ctx: &mut ls::Context, " ++ args ++ ") -> ls::Result<bool> {\n" ++ valid ++ "  Ok(true)\n}\n"
          ++ "#[test]\nfn test_" ++ show index ++ "() -> ls::Result<()> {\n" ++ context ++ fixed ++ examples ++ random ++ "  Ok(())\n}\n")
      pure [Artifact ("src/" ++ modulePath ++ ".rs") ("// Scaffolded by LawSpec. User-owned; never overwritten.\n#![allow(unused_variables, unused_imports, non_snake_case)]\nuse crate::lawspec_runtime as ls;\n" ++ concat stubs) "user" "source"
           ,Artifact ("tests/" ++ testName ++ "_lawspec.rs") ("// Generated by LawSpec. Do not edit.\n#![allow(unused_variables, unused_imports, dead_code)]\n#[path = \"../src/lawspec_runtime.rs\"] mod lawspec_runtime;\n#[path = \"support/lawspec_strategies.rs\"] mod ls_gen;\n#[path = " ++ q ("../src/" ++ modulePath ++ ".rs") ++ "] mod adapter;\nuse lawspec_runtime as ls;\nuse proptest::strategy::Strategy;\n" ++ concat wrappers ++ concat tests) "generated" "test"]

literal :: Scalar -> Either String String
literal s = case s of
  SInteger _ n -> pure ("ls::Value::Integer(" ++ big n ++ ")")
  SBool b -> pure ("ls::Value::Bool(" ++ (if b then "true" else "false") ++ ")")
  SDecimal c e -> pure ("ls::Value::Decimal(ls::Decimal::new(" ++ big c ++ ", " ++ big e ++ "))")
  SRational n d -> pure ("ls::Value::Rational(ls::BigRational::new(" ++ big n ++ ", " ++ big d ++ "))")
  SFloat t b -> pure ("ls::Value::" ++ (if t == "Float32" then "Float32(f32" else "Float64(f64") ++ "::from_bits(0x" ++ b ++ "))")
  SComplex t r i -> do
    a <- literal r; b <- literal i
    let component = if t == "Complex64" then "f32" else "f64"
        variant = if t == "Complex64" then "Complex32" else "Complex64"
        unbox x = "<" ++ component ++ " as ls::FromValue>::from_value(" ++ x ++ ")?"
    pure ("ls::Value::" ++ variant ++ "(ls::" ++ variant ++ "::new(" ++ unbox a ++ ", " ++ unbox b ++ "))")
  SSequence "Text" xs -> pure ("ls::Value::Text(" ++ q (map toEnum xs) ++ ".to_owned())")
  SSequence t xs -> pure ("ls::Value::" ++ t ++ "(vec![" ++ comma (map show xs) ++ "])")
  SCharacter "Char" n -> pure ("ls::Value::Char(char::from_u32(" ++ show n ++ ").unwrap())")
  SCharacter t n -> pure ("ls::Value::" ++ t ++ "(" ++ show n ++ ")")
  SSymbol i d -> pure ("ls::Value::Symbol(ctx.symbol(" ++ q i ++ ", " ++ q d ++ "))")
  SAbsent n -> pure ("ls::Value::" ++ n)
  SPresent n Nothing -> pure ("ls::Value::" ++ n ++ "(None)")
  SPresent n (Just v) -> (\x -> "ls::Value::" ++ n ++ "(Some(Box::new(" ++ x ++ ")))") <$> literal v
  where big n = "ls::BigInt::parse_bytes(b" ++ q (show n) ++ ", 10).unwrap()"
