-- Native public JS/TS entry points over framework-independent checked bodies.
module LawSpec.WebDefinitions (emitWebDefinitions, definitionCalls) where

import Control.Monad (forM)
import LawSpec.Core.Policy
import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Core.Evidence (runtimePostconditions)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.WebData as Native
import qualified LawSpec.WebExpr as E
import qualified LawSpec.Code.Doc as D
import Data.List (nub, sort, intercalate, stripPrefix, isPrefixOf)

-- An asynchronous definition's call is marked "await ", so callers await it.
definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(identity, (if identity `elem` waiting then "await " else "") ++ "_definitions.evaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units), let identity = declarationId (definitionDeclaration d)]
  where waiting = asyncDefinitions units

-- Workflows (and their stages) that call an asynchronous adapter, directly or
-- through another such definition, are async functions.
asyncDefinitions :: [Unit] -> [Id]
asyncDefinitions units = grow []
  where
    definitions = concatMap unitDefinitions units
    definitionIds = map (declarationId . definitionDeclaration) definitions
    asyncAdapters = [declarationId d | u <- units, d <- unitDeclarations u, declarationAsync d, declarationId d `notElem` definitionIds]
    callsIn expression = case expressionNode expression of
      ExternalCall callee arguments -> callee : concatMap callsIn arguments
      _ -> concatMap callsIn (children expression)
    grow known =
      let next = nub [ declarationId (definitionDeclaration d) | d <- definitions, definitionOrchestrates d
                     , any (\callee -> callee `elem` asyncAdapters || callee `elem` known) (callsIn (definitionBody d)) ]
      in if sort next == sort known then known else grow next

-- A definition call's function, without its await mark.
plainCall :: String -> String
plainCall name = maybe name id (stripPrefix "await " name)

emitWebDefinitions :: Bool -> D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitWebDefinitions _ _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitWebDefinitions ts layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  bodies <- mapM (implementation contracts) (zip [0::Int ..] (concatMap unitDefinitions units))
  wrappers <- mapM nativeUnit (filter (not . null . unitDefinitions) units)
  pure (file ("src/lawspec_definition_bodies." ++ extension) "./" adapterImports bodies : wrappers)
  where
    extension = if ts then "ts" else "mjs"
    importExtension = if ts then "js" else "mjs"
    width = D.text (show bits)
    callees = definitionCalls units
    definitionIds = map (declarationId . definitionDeclaration) (concatMap unitDefinitions units)
    adapters = [(declarationId d, (idText (unitId u), d)) | u <- units, d <- unitDeclarations u,
      declarationId d `notElem` definitionIds]
    -- The adapter modules orchestrations call, imported from the bodies file.
    adapterAlias owner = "_adapters_" ++ map (\c -> if c == '.' then '_' else c) owner
    adapterImports = nub [ "import * as " ++ adapterAlias owner ++ " from './" ++
                             map (\c -> if c == '.' then '/' else c) owner ++ "." ++ importExtension ++ "';"
                         | d <- concatMap unitDefinitions units, definitionOrchestrates d
                         , callee <- calls (definitionBody d), Just (owner, _) <- [lookup callee adapters] ]
    calls expression = case expressionNode expression of
      ExternalCall callee arguments -> callee : concatMap calls arguments
      _ -> concatMap calls (children expression)
    annotation ty = if ts then D.text ": " <> ty else mempty
    file path root imports bodies = Artifact path (D.render layout (
      D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
      D.joinWith D.hardline (map D.text (sort (imports ++
        ["import * as " ++ alias ++ " from '" ++ root ++ moduleName ++ "." ++ importExtension ++ "';"
        | (alias,moduleName) <- [("data","lawspec_data"),("ls","lawspec_runtime"),("schema","lawspec_schema")]]))) <>
      D.hardline <> D.hardline <> D.text "const _lawspec_schema = data.makeSchema();" <>
      D.hardline <> D.hardline <>
      D.joinWith (D.hardline <> D.hardline) bodies <> D.hardline)) "generated" "source"
    contextual identity body = D.text "try " <> D.block 2 body <>
      D.text " catch (error) " <> D.block 2
        (D.text "throw " <> E.call "new globalThis.Error"
          [D.group (E.quotedValue (idText identity ++ ": ") <> D.text " +" <>
            D.nest 4 (D.softline <> E.call "globalThis.String" [D.text "error"])),D.text "{cause: error}"] <> D.text ";")
    assign name value = D.text ("const " ++ name ++ " = ") <> value <> D.text ";"
    schemaCall name ty value = do
      ref <- Native.webTypeReferenceDoc ty
      pure (E.call ("_lawspec_schema." ++ name) [ref,value,width,D.text "symbols"])
    symbols = D.text "symbols" <> annotation (D.text "Map<string, symbol>")
    implementation contracts (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          names = zip (nub (map binderId binders)) ["value" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved JS/TS local") id (lookup identity names)
          arguments = [D.text (local (binderId binder)) <> annotation (D.text "unknown") | binder <- definitionArguments d]
          asynchronous = declarationId (definitionDeclaration d) `elem` asyncDefinitions units
          awaitIf condition expression = if condition then D.text "(await " <> expression <> D.text ")" else expression
          external term values = case expressionNode term of
            ExternalCall identity _ | Just name <- lookup identity callees ->
              pure (awaitIf ("await " `isPrefixOf` name)
                (E.call (drop (length ("_definitions." :: String)) (plainCall name)) (D.text "symbols":values)))
            -- An orchestration calls an adapter natively: the values cross
            -- to native and back through the schema, as in the tests.
            ExternalCall identity _ | Just (owner, adapter) <- lookup identity adapters -> do
              let (parameterTypes, resultType) = functionType (declarationType adapter)
              nativeValues <- sequence [schemaCall "toNative" ty value | (ty, value) <- zip parameterTypes values]
              schemaCall "fromNative" resultType
                (awaitIf (declarationAsync adapter) (E.call (adapterAlias owner ++ "." ++ declarationName adapter) nativeValues))
            _ -> Left "unresolved JS/TS total call"
      rendered <- (if asynchronous then E.renderAsyncExpression else E.renderExpression) ts declarations bits local external (definitionBody d)
      -- A workflow stage with policies runs under the workflow runtime.
      body <- case definitionPolicy d of
        Nothing -> pure rendered
        Just policy | policyFrame policy -> pure (awaitIf asynchronous (E.call (if asynchronous then "ls.runWorkflowAsync" else "ls.runWorkflow")
          [D.text "symbols", D.text (if asynchronous then "async () => " else "() => ") <> rendered]))
        Just policy -> do
          config <- policyDoc (idText (declarationId (definitionDeclaration d))) policy
          let key = case definitionArguments d of
                argument : _ -> D.text (local (binderId argument))
                [] -> D.text "null"
          pure (awaitIf asynchronous (E.call (if asynchronous then "ls.runStageAsync" else "ls.runStage")
            [D.text "symbols", config, D.text (if asynchronous then "async () => " else "() => ") <> rendered, key]))
      -- Arguments and results were checked where they were built, decoded
      -- or drawn; the native wrappers check values crossing from adapters.
      let checks = []
          result = D.text "result"
      let contract = lookup (declarationId (definitionDeclaration d)) [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [assign "result" body,D.text "return " <> result <> D.text ";"])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checked_result")] ++
                [(binderId b,"contract_value_" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c ++ contractRuntimePostconditions c))]
              resolve identity = maybe (error "unbound definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression ts declarations bits resolve external predicate
                pure (E.call "ls.requireContract" [expression,E.quoted stage] <> D.text ";")
          pre <- mapM (require "precondition") (contractPreconditions c)
          -- Proved by the totality audit; see LawSpec.Core.Evidence.
          post <- mapM (require "postcondition") (runtimePostconditions c)
          pure (checks ++ pre ++ [assign "result" body,assign "checked_result" result] ++
            post ++ [D.text "return checked_result;"])
      pure (D.text ((if asynchronous then "export async function evaluate" else "export function evaluate") ++ show index) <>
        D.delimitTrailing 4 "(" ")" (symbols:arguments) <> annotation (D.text (if asynchronous then "Promise<unknown>" else "unknown")) <> D.text " " <>
        D.block 2 (contextual (declarationId (definitionDeclaration d)) (D.joinWith D.hardline
          statements)))
    evaluator identity = maybe (Left "unresolved JS/TS policy definition") (Right . drop (length ("_definitions." :: String)) . plainCall)
      (lookup identity callees)
    policyDoc key policy = do
      gates <- policyGates policy
      compensate <- case policyCompensate policy of
        Nothing -> pure (D.text "null")
        Just undo -> (\name -> arrow ["value"] (name ++ "(symbols, value)")) <$> evaluator undo
      retry <- case policyRetry policy of
        Nothing -> pure (D.text "null")
        Just r -> do
          strategy <- case retryStrategy r of
            Immediate -> pure (array [E.quoted "immediate"])
            Fixed delay -> pure (array [E.quoted "fixed", big delay])
            Linear delay step -> pure (array [E.quoted "linear", big delay, big step])
            Exponential delay factor cap -> pure (array [E.quoted "exponential", big delay, big factor, maybe (D.text "null") big cap])
            Fibonacci delay -> pure (array [E.quoted "fibonacci", big delay])
            Custom decide -> do
              name <- evaluator decide
              pure (array [E.quoted "custom", D.text ("(attempt, error, previous) => ls.retryDecision(" ++ name ++
                "(symbols, attempt, error, new ls.DataValue('lawspec.time::type::Duration::Duration', [previous])))")])
          condition <- case retryWhen r of
            Nothing -> pure (D.text "null")
            Just p -> (\name -> D.text ("(error) => " ++ name ++ "(symbols, error)")) <$> evaluator p
          pure (object [("strategy", strategy), ("attempts", big (retryAttempts r)), ("jitter", E.quoted (jitterName (retryJitter r))), ("when", condition)])
      pure (object [("stage", E.quoted (policyStage policy)), ("retry", retry), ("timeout", maybe (D.text "null") big (policyTimeout policy)),
        ("key", E.quoted key), ("gates", array gates), ("cache", maybe (D.text "null") big (policyCache policy)),
        ("wraps", D.text (if null (policyFailures policy) then "false" else "true")), ("compensate", compensate),
        ("hedge", maybe (D.text "null") (\h -> array [big (hedgeDelay h), big (hedgeMost h)]) (policyHedge policy))])
    -- A gate's callbacks call the unit's copies of the resilience unit's
    -- state machines, with the policy's numbers.
    policyGates policy = do
      breaker <- forM (policyBreaker policy) $ \b -> do
        start <- evaluator (breakerStart b)
        admit <- evaluator (breakerAdmit b)
        record <- evaluator (breakerRecord b)
        pure (object [("kind", E.quoted "breaker"), ("start", arrow ["now"] (start ++ "(symbols, now)")),
          ("admit", arrow ["state", "now"] (admit ++ "(symbols, state, now)")),
          ("finish", arrow ["state", "now", "succeeded"] (record ++ "(symbols, " ++ bigs [breakerFailures b, breakerWindow b, breakerCooldown b] ++ ", state, now, succeeded)")),
          ("wait", D.text "null")])
      limit <- forM (policyLimit policy) $ \l -> do
        start <- evaluator (limitStart l)
        admit <- evaluator (limitAdmit l)
        let numbers = bigs [limitCount l, limitPeriod l]
        pure (object [("kind", E.quoted "limit"), ("start", arrow ["now"] (start ++ "(symbols, " ++ numbers ++ ", now)")),
          ("admit", arrow ["state", "now"] (admit ++ "(symbols, " ++ numbers ++ ", state, now)")),
          ("finish", D.text "null"), ("wait", waitDoc (limitWait l))])
      bulkhead <- forM (policyBulkhead policy) $ \b -> do
        start <- evaluator (bulkheadStart b)
        admit <- evaluator (bulkheadAdmit b)
        release <- evaluator (bulkheadRelease b)
        let n = bigs [bulkheadLimit b]
        pure (object [("kind", E.quoted "bulkhead"), ("start", arrow ["now"] (start ++ "(symbols, " ++ n ++ ", now)")),
          ("admit", arrow ["state", "now"] (admit ++ "(symbols, " ++ n ++ ", state, now)")),
          ("finish", arrow ["state", "now", "succeeded"] (release ++ "(symbols, state)")), ("wait", waitDoc (bulkheadWait b))])
      pure (maybe [] pure breaker ++ maybe [] pure limit ++ maybe [] pure bulkhead)
    arrow parameters body = D.text ("(" ++ intercalate ", " [p ++ (if ts then ": any" else "") | p <- parameters] ++ ") => " ++ body)
    bigs numbers = intercalate ", " [show n ++ "n" | n <- numbers]
    waitDoc wait = case wait of
      Nothing -> D.text "null"
      Just Nothing -> D.text "-1n"
      Just (Just d) -> big d
    array items = D.text "[" <> D.joinWith (D.text ", ") items <> D.text "]"
    object fields = D.text "{" <> D.joinWith (D.text ", ") [D.text (key ++ ": ") <> value | (key, value) <- fields] <> D.text "}"
    big n = D.text (show n ++ "n")
    jitterName j = case j of
      NoJitter -> "none"
      FullJitter -> "full"
      EqualJitter -> "equal"
      DecorrelatedJitter -> "decorrelated"
    nativeUnit unit = do
      wrappers <- mapM native (unitDefinitions unit)
      let unitName = idText (unitId unit)
          depth = 1 + length (filter (== '.') unitName)
          root = concat (replicate depth "../")
          path = "src/lawspec_definitions/" ++ map (\c -> if c == '.' then '/' else c) unitName ++ "." ++ extension
      pure (file path root ["import * as _definitions from '" ++ root ++ "lawspec_definition_bodies." ++ importExtension ++ "';"] wrappers)
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          values = ["value" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.webDataTypeDoc declarations) args
      resultType <- Native.webDataTypeDoc declarations result
      arguments <- sequence [schemaCall "fromNative" ty (D.text value) | (ty,value) <- zip args values]
      name <- maybe (Left "unresolved JS/TS native call") Right (lookup (declarationId declaration) callees)
      output <- schemaCall "toNative" result (D.text "result")
      let parameters = symbols : [D.text value <> annotation ty | (value,ty) <- zip values types]
          inputs = [assign ("argument" ++ show i) value | (i,value) <- zip [0::Int ..] arguments]
          waiting = "await " `isPrefixOf` name
          invocation = (if waiting then D.text "await " else mempty) <>
            E.call (plainCall name) (D.text "symbols" : [D.text ("argument" ++ show i) | i <- [0 .. length args - 1]])
      pure (D.text ((if waiting then "export async function " else "export function ") ++ declarationName declaration) <>
        D.delimitTrailing 4 "(" ")" parameters <> annotation (if waiting then D.text "Promise<" <> resultType <> D.text ">" else resultType) <> D.text " " <>
        D.block 2 (contextual (declarationId declaration) (D.joinWith D.hardline
          (inputs ++ [assign "result" invocation,D.text "return " <> output <> D.text ";"]))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat
        [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
