-- Native public JS/TS entry points over framework-independent checked bodies.
module LawSpec.WebDefinitions (emitWebDefinitions, definitionCalls) where

import LawSpec.Core
import LawSpec.Core.DefinitionContracts (checkedDefinitionContracts)
import LawSpec.Common (Artifact(..))
import qualified LawSpec.WebData as Native
import qualified LawSpec.WebExpr as E
import qualified LawSpec.Code.Doc as D
import Data.List (nub, sort)

definitionCalls :: [Unit] -> [(Id,String)]
definitionCalls units = [(declarationId (definitionDeclaration d), "_definitions.evaluate" ++ show i)
  | (i,d) <- zip [0::Int ..] (concatMap unitDefinitions units)]

emitWebDefinitions :: Bool -> D.Layout -> Int -> [DataDeclaration] -> [Unit] -> Either String [Artifact]
emitWebDefinitions _ _ _ _ units | null (concatMap unitDefinitions units) = pure []
emitWebDefinitions ts layout bits declarations units = do
  contracts <- checkedDefinitionContracts bits declarations units
  bodies <- mapM (implementation contracts) (zip [0::Int ..] (concatMap unitDefinitions units))
  wrappers <- mapM nativeUnit (filter (not . null . unitDefinitions) units)
  pure (file ("src/lawspec_definition_bodies." ++ extension) "./" [] bodies : wrappers)
  where
    extension = if ts then "ts" else "mjs"
    importExtension = if ts then "js" else "mjs"
    width = D.text (show bits)
    callees = definitionCalls units
    annotation ty = if ts then D.text ": " <> ty else mempty
    file path root imports bodies = Artifact path (D.render layout (
      D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
      D.joinWith D.hardline (map D.text (sort (imports ++
        ["import * as " ++ alias ++ " from '" ++ root ++ moduleName ++ "." ++ importExtension ++ "';"
        | (alias,moduleName) <- [("data","lawspec_data"),("ls","lawspec_runtime"),("schema","lawspec_schema")]]))) <>
      D.hardline <> D.hardline <> D.text "const _lawspec_schema = data.makeSchema();" <>
      D.hardline <> D.hardline <>
      D.joinWith (D.hardline <> D.hardline) bodies <> D.hardline)) "generated" "source"
    contextual identity body = D.text "try " <> D.block 2 body <>
      D.text " catch (error) " <> D.block 2
        (D.text "throw " <> E.call "new globalThis.Error"
          [D.group (E.quotedValue (idText identity ++ ": ") <> D.text " +" <>
            D.nest 4 (D.softline <> E.call "globalThis.String" [D.text "error"])),D.text "{cause: error}"] <> D.text ";")
    assign name value = D.text ("const " ++ name ++ " = ") <> value <> D.text ";"
    schemaCall name ty value = do
      ref <- Native.webTypeReferenceDoc ty
      pure (E.call ("_lawspec_schema." ++ name) [ref,value,width,D.text "symbols"])
    symbols = D.text "symbols" <> annotation (D.text "Map<string, symbol>")
    implementation contracts (index,d) = do
      let binders = definitionArguments d ++ nestedBinders (definitionBody d)
          names = zip (nub (map binderId binders)) ["value" ++ show i | i <- [0::Int ..]]
          local identity = maybe (error "unresolved JS/TS local") id (lookup identity names)
          arguments = [D.text (local (binderId binder)) <> annotation (D.text "unknown") | binder <- definitionArguments d]
          external term values = case expressionNode term of
            ExternalCall identity _ -> do
              name <- maybe (Left "unresolved JS/TS total call") Right (lookup identity callees)
              pure (E.call (drop (length ("_definitions." :: String)) name) (D.text "symbols":values))
            _ -> Left "expected JS/TS definition call"
      body <- E.renderExpression ts declarations bits local external (definitionBody d)
      checks <- mapM (\binder -> do
        value <- schemaCall "validate" (binderType binder) (D.text (local (binderId binder)))
        pure (D.text (local (binderId binder) ++ " = ") <> value <> D.text ";")) (definitionArguments d)
      result <- schemaCall "validate" (expressionType (definitionBody d)) (D.text "result")
      let contract = lookup (declarationId (definitionDeclaration d)) [(contractDeclaration c,c) | c <- contracts]
      statements <- case contract of
        Nothing -> pure (checks ++ [assign "result" body,D.text "return " <> result <> D.text ";"])
        Just c -> do
          let aliases = zip (map binderId (contractArguments c))
                (map (local . binderId) (definitionArguments d)) ++
                [(binderId (contractResult c),"checked_result")] ++
                [(binderId b,"contract_value_" ++ show i) | (i,b) <- zip [0::Int ..]
                  (concatMap nestedBinders (contractPreconditions c ++ contractPostconditions c))]
              resolve identity = maybe (error "unbound definition contract binder") id (lookup identity aliases)
              require stage predicate = do
                expression <- E.renderExpression ts declarations bits resolve external predicate
                pure (E.call "ls.requireContract" [expression,E.quoted stage] <> D.text ";")
          pre <- mapM (require "precondition") (contractPreconditions c)
          post <- mapM (require "postcondition") (contractPostconditions c)
          pure (checks ++ pre ++ [assign "result" body,assign "checked_result" result] ++
            post ++ [D.text "return checked_result;"])
      pure (D.text ("export function evaluate" ++ show index) <>
        D.delimitTrailing 4 "(" ")" (symbols:arguments) <> annotation (D.text "unknown") <> D.text " " <>
        D.block 2 (contextual (declarationId (definitionDeclaration d)) (D.joinWith D.hardline
          statements)))
    nativeUnit unit = do
      wrappers <- mapM native (unitDefinitions unit)
      let unitName = idText (unitId unit)
          depth = 1 + length (filter (== '.') unitName)
          root = concat (replicate depth "../")
          path = "src/lawspec_definitions/" ++ map (\c -> if c == '.' then '/' else c) unitName ++ "." ++ extension
      pure (file path root ["import * as _definitions from '" ++ root ++ "lawspec_definition_bodies." ++ importExtension ++ "';"] wrappers)
    native d = do
      let declaration = definitionDeclaration d
          (args,result) = functionType (declarationType declaration)
          values = ["value" ++ show i | i <- [0 .. length args - 1]]
      types <- mapM (Native.webDataTypeDoc declarations) args
      resultType <- Native.webDataTypeDoc declarations result
      arguments <- sequence [schemaCall "fromNative" ty (D.text value) | (ty,value) <- zip args values]
      name <- maybe (Left "unresolved JS/TS native call") Right (lookup (declarationId declaration) callees)
      output <- schemaCall "toNative" result (D.text "result")
      let parameters = symbols : [D.text value <> annotation ty | (value,ty) <- zip values types]
          inputs = [assign ("argument" ++ show i) value | (i,value) <- zip [0::Int ..] arguments]
          invocation = E.call name (D.text "symbols" : [D.text ("argument" ++ show i) | i <- [0 .. length args - 1]])
      pure (D.text ("export function " ++ declarationName declaration) <>
        D.delimitTrailing 4 "(" ")" parameters <> annotation resultType <> D.text " " <>
        D.block 2 (contextual (declarationId declaration) (D.joinWith D.hardline
          (inputs ++ [assign "result" invocation,D.text "return " <> output <> D.text ";"]))))
    nestedBinders expression = case expressionNode expression of
      AllElements value binder predicate -> nestedBinders value ++ [binder] ++ nestedBinders predicate
      AllPayloads value predicates -> nestedBinders value ++ concat
        [binder : nestedBinders predicate | (binder,predicate) <- predicates]
      Match value cases -> nestedBinders value ++ concat
        [caseBinders branch ++ nestedBinders (caseBody branch) | branch <- cases]
      _ -> concatMap nestedBinders (children expression)
