-- Native JS classes and TS generic unions rendered from checked Core.
module LawSpec.WebData (emitWebData, emitWebDataWithProfile, webDataType, webTypeReference, webDataTypeDoc, webTypeReferenceDoc, requiresSchema) where

import Control.Monad (unless, forM)
import Data.List (nub, intercalate, isPrefixOf)
import qualified LawSpec.Backend as Backend
import qualified LawSpec.Core as C
import qualified LawSpec.Core.Schema as S
import LawSpec.Core.Types (makeRegistry)
import LawSpec.Common (Artifact(..))
import LawSpec.Scalar
import LawSpec.RuntimeSources (runtimeSource)
import qualified LawSpec.Code.Doc as D

import LawSpec.WebTypes
import LawSpec.DataNames (isProduct)
import LawSpec.Core.Total (constructorProofContracts)
import qualified LawSpec.WebExpr as E

-- Target imports and a known TypeScript signature slot are substituted. Runtime
-- expressions and literals stay opaque; no whitespace rewriting is performed.
replace :: String -> String -> String -> String
replace _ _ [] = []
replace old new source
  | old `isPrefixOf` source = new ++ replace old new (drop (length old) source)
  | c:rest <- source = c : replace old new rest

emitWebData :: Bool -> D.Layout -> [C.DataDeclaration] -> Either String [Artifact]
emitWebData ts = emitWebDataWithProfile ts 64

emitWebDataWithProfile :: Bool -> Int -> D.Layout -> [C.DataDeclaration] -> Either String [Artifact]
emitWebDataWithProfile ts bits layout declarations = do
  _ <- makeRegistry declarations
  _ <- either (Left . show) Right (constructorProofContracts bits declarations)
  names <- namesFor declarations
  (schemas,contracts) <- S.dataSchemasWithContracts declarations
  let available = ["_lawspec_field_predicate" ++ show index | index <- [0 :: Int ..],
        "_lawspec_field_predicate" ++ show index `notElem` map snd names]
      entries = zip available [(contract,predicate) | contract <- contracts,
        predicate <- S.contractPredicates contract]
      bindings = [(S.contractTag contract,name) | (name,(contract,_)) <- entries]
  callbacks <- forM entries $ \(name,(contract,predicate)) -> do
    let fields = zip (map C.binderId (S.contractFields contract))
          ["_fields[" ++ show i ++ "]" | i <- [0 :: Int ..]]
        nested = zip (nub (nestedIds predicate)) ["_local" ++ show i | i <- [0 :: Int ..]]
        local identity = maybe "_invalid_field" id (lookup identity (fields ++ nested))
        ref ty = do
          value <- reference <$> S.typeReference (S.contractParameters contract) ty
          pure (if variable ty then E.call "schema.substitute" [value,D.text "_types"] else value)
        typeKey ty | variable ty = E.call "schema.typeKey" . pure <$> ref ty
                   | otherwise = pure (E.quoted (Backend.scalarTypeKey ty))
        parameter (name,ty) = D.text name <> if ts then D.text (": " ++ ty) else mempty
    body <- E.renderExpressionWithContext ts declarations (D.text "bits") ref typeKey local
      (\_ _ -> Left "external call in constructor predicate") predicate
    pure (D.text "function " <> D.text name <> D.delimitTrailing 4 "(" ")"
      (map parameter [("_lawspec_schema","schema.Schema"),("_types","ReadonlyArray<schema.Named>"),
        ("_fields","ReadonlyArray<unknown>"),("bits","number"),("symbols","Map<string, symbol>")]) <>
      D.text " " <> D.block 2 (D.text "return " <> body <>
        (if ts then D.text " as boolean" else mempty) <> D.text ";"))
  classes <- concat <$> mapM (definition names) declarations
  metadata <- mapM (definitionSchema names bindings) schemas
  let extension = if ts then "ts" else "mjs"
      importExtension = if ts then "js" else "mjs"
      header = D.text "// Generated by LawSpec. Do not edit." <> D.hardline <>
        D.text ("import * as ls from './lawspec_runtime." ++ importExtension ++ "';") <> D.hardline <>
        D.text ("import * as schema from './lawspec_schema." ++ importExtension ++ "';")
      factory = D.text "export function makeSchema() " <> D.block 2
        (D.joinWith (D.hardline <> D.hardline) (callbacks ++ [D.text "return " <> invoke "new schema.Schema"
          [array metadata, array (map (D.text . q . primitiveName) primitives),
           D.block 2 (D.joinWith D.hardline (map D.text ["nothing: Nothing,", "just: Just,", "left: Left,", "right: Right,", "presence: Presence,"]))] <> D.text ";"]))
      source = D.joinWith (D.hardline <> D.hardline)
        (header : builtins ++ classes ++ [factory]) <> D.hardline
      typedRuntime = if ts then replace "predicates = []"
        "predicates: FieldPredicate[] = []" $
        replace "      indices = [],\n      refinements = [],"
          "      indices: ReadonlyArray<string> = [],\n      refinements: ReadonlyArray<readonly [number, Named | Parameter]> = []," $
        replace "constructor(name, args = [])"
          "constructor(name: string, args: ReadonlyArray<Named | Parameter> = [])" (runtimeSource "web-schema")
        else runtimeSource "web-schema"
      runtime = (if ts then unlines ["// @ts-nocheck", "export type FieldPredicate = (",
          "    schema: Schema,", "    types: ReadonlyArray<Named>,",
          "    fields: ReadonlyArray<unknown>,", "    bits: number,",
          "    symbols: Map<string, symbol>,", ") => boolean;", ""] else "") ++
        replace "./lawspec_runtime.mjs" ("./lawspec_runtime." ++ importExtension) typedRuntime
  pure [Artifact ("src/lawspec_data." ++ extension) (D.render layout source) "generated" "source",
        Artifact ("src/lawspec_schema." ++ extension) runtime "generated" "source"]
  where
    nestedIds expression = (case C.expressionNode expression of
      C.AllElements _ binder _ -> [C.binderId binder]
      C.AllPayloads _ predicates -> map (C.binderId . fst) predicates
      C.Match _ branches -> concatMap (map C.binderId . C.caseBinders) branches
      _ -> []) ++ concatMap nestedIds (C.children expression)
    variable (C.TypeVariable _) = True
    variable (C.Constructor _ args) = any (\arg -> case arg of C.TypeArgument ty -> variable ty; _ -> False) args
    variable (C.Arrow a b) = variable a || variable b
    alias name parameters variants = if ts then
      D.text ("export type " ++ name ++ (if null parameters then "" else "<" ++ intercalate ", " parameters ++ ">") ++ " =") <>
        D.group (D.nest 2 (D.softline <> D.joinWith (D.softline <> D.text "| ") variants)) <> D.text ";"
      else D.text "/**" <> D.hardline <>
        (if null parameters then mempty else D.text (" * @template " ++ intercalate ", " parameters) <> D.hardline) <>
        D.text " * @typedef {" <> D.joinWith (D.text " | ") variants <> D.text ("} " ++ name) <> D.hardline <> D.text " */"
    nativeClass name parameters fields =
      (if ts || null parameters then mempty else D.text ("/** @template " ++ intercalate ", " parameters ++ " */") <> D.hardline) <>
      D.text "export class " <> (if ts then application name (map D.text parameters) else D.text name) <> D.text " " <>
      D.block 2 (D.joinWith D.hardline
        ([D.text "declare private readonly _lawspecBrand: void;" | ts] ++
         [D.text (if ts then "readonly " else "") <> key field <>
          (if ts then D.text ": " <> ty else mempty) <> D.text ";" | (field,ty) <- fields]) <>
         (if null fields && not ts then mempty else D.hardline <> D.hardline) <>
         D.text "constructor" <> D.delimitTrailing 4 "(" ")"
           [D.text ("value" ++ show i) <> (if ts then D.text ": " <> ty else mempty) | (i,(_,ty)) <- zip [0::Int ..] fields] <>
         D.text " " <> D.block 2 (D.joinWith D.hardline
           ([D.text "this" <> D.text ("." ++ field ++ " = value" ++ show i ++ ";") | (i,(field,_)) <- zip [0::Int ..] fields] ++
            [D.text "Object.freeze(this);"])))
    key name = if name `elem` ["constructor","__proto__"] then D.text ("[" ++ q name ++ "]") else D.text name
    builtins =
      [alias "Maybe" ["T"] [D.text "Nothing<T>", D.text "Just<T>"],
       nativeClass "Nothing" ["T"] [], nativeClass "Just" ["T"] [("value",D.text "T")],
       alias "Either" ["L","R"] [D.text "Left<L, R>",D.text "Right<L, R>"],
       nativeClass "Left" ["L","R"] [("value",D.text "L")],
       nativeClass "Right" ["L","R"] [("value",D.text "R")],
       D.text (if ts then "export class Presence<T> extends ls.Presence " else "export class Presence extends ls.Presence ") <>
         D.block 2 ((if ts then D.text "declare readonly value: T | undefined;" <> D.hardline <> D.hardline else mempty) <>
           D.text (if ts then "constructor(kind: 'Nullable' | 'Optional', present: boolean, value?: T) " else "constructor(kind, present, value) ") <>
           D.block 2 (D.text "super(kind, present, value);"))]
    definition names declaration = do
      name <- lookupName names (C.dataId declaration)
      let parameters = zip (C.dataParameters declaration)
            [candidate | n <- [0::Int ..], let candidate = "T" ++ show n, candidate `notElem` map snd names]
          args = map snd parameters
      variants <- forM (C.dataConstructors declaration) $ \constructor -> do
        native <- lookupName names (C.constructorId constructor)
        -- A GADT case is generic in the parameters it leaves open and in its
        -- existentials; the union admits it only where its refinements hold.
        let equations = C.constructorEquations constructor
            existentials = zip (C.constructorExistentials constructor)
              [candidate | n <- [0::Int ..], let candidate = "E" ++ show n, candidate `notElem` map snd names]
            scope = parameters ++ existentials
            open = [v | (p, v) <- parameters, p `notElem` map fst equations] ++ map snd existentials
            classArgs = if ts && not (null equations) then open else args
        fields <- forM (C.constructorFields constructor) $ \field -> do
          identifier False (C.binderName field)
          unless (C.binderName field /= "_lawspecBrand") (Left "reserved TypeScript data field: _lawspecBrand")
          ty <- typeDoc "" names scope (C.binderType field)
          pure (C.binderName field,ty)
        member <- if not ts || null equations then pure (application native (map D.text classArgs)) else do
          patterns <- mapM (\(p, ty) -> typeDoc "" names [(e, "infer " ++ v) | (e, v) <- existentials] ty >>= \pattern ->
            pure (maybe (D.text "never") D.text (lookup p parameters), pattern)) equations
          pure (D.text "([" <> D.commaSep (map fst patterns) <> D.text "] extends [" <> D.commaSep (map snd patterns) <>
            D.text "] ? " <> application native (map D.text classArgs) <> D.text " : never)")
        pure (member,nativeClass native classArgs fields)
      -- A product's class is the type itself; only sums need a union alias.
      pure ([alias name args (if null variants then [D.text "never"] else map fst variants) | not (isProduct declaration)] ++ map snd variants)
    -- Optional trailing arguments up to the last one that is needed.
    trimmed values needed = take (length needed - length (takeWhile not (reverse needed))) values
    definitionSchema names bindings schema = do
      variants <- forM (S.constructors schema) $ \constructor -> do
        native <- lookupName names (C.Id (S.constructorTag constructor))
        pure (invoke "new schema.Constructor"
          ([D.text (q (S.constructorTag constructor)),
           array [invoke "new schema.Field" [D.text (q (S.fieldName field)),reference (S.fieldType field)] | field <- S.fields constructor],
           D.text native] ++ trimmed
             [ array [D.text callback | (tag,callback) <- bindings, tag == S.constructorTag constructor]
             , D.text "null"
             , array (map (D.text . q) (S.constructorIndex constructor))
             , array [array [D.text (show index), reference pattern] | (index, pattern) <- S.constructorRefinements constructor]
             , D.text (show (S.constructorExistentials constructor)) ]
             [ any ((== S.constructorTag constructor) . fst) bindings, False
             , not (null (S.constructorIndex constructor))
             , not (null (S.constructorRefinements constructor))
             , S.constructorExistentials constructor > 0 ]))
      pure (invoke "new schema.Definition"
        [D.text (q (S.typeName schema)),D.text (show (S.parameterCount schema)),array variants])
