// Generated by LawSpec. Do not edit.
package lawspec;

/**
 * The default handlers of lawspec.crypto: SHA3-256 and SHAKE256 (FIPS 202),
 * ML-KEM-768 (FIPS 203), ML-DSA-65 (FIPS 204), AES-256-GCM, and
 * SLH-DSA-SHAKE-128f (FIPS 205) as the alternative Signature handler.
 *
 * <p>ML-KEM, ML-DSA, SHA3-256 and AES-GCM come from the JDK (JDK 24 and
 * later); SHAKE256 of any length and SLH-DSA from Bouncy Castle
 * (org.bouncycastle:bcprov-jdk18on).
 *
 * <p>A secret key's bytes are its seed: d || z (64 bytes) for ML-KEM-768 and
 * xi (32 bytes) for ML-DSA-65; the JDK makes the key from the seed. Public
 * keys, ciphertexts and signatures are the standards' encodings.
 */
public final class Crypto {
  private Crypto() {}

  private static final java.security.SecureRandom SECURE = new java.security.SecureRandom();

  static byte[] randomBytes(int n) {
    byte[] out = new byte[n];
    SECURE.nextBytes(out);
    return out;
  }

  static byte[] concat(byte[]... parts) {
    int length = 0;
    for (byte[] part : parts) length += part.length;
    byte[] out = new byte[length];
    int at = 0;
    for (byte[] part : parts) {
      java.lang.System.arraycopy(part, 0, out, at, part.length);
      at += part.length;
    }
    return out;
  }

  /** A source of randomness that gives these bytes, in order: how the JDK makes a key from its seed. */
  static final class Seeded extends java.security.SecureRandom {
    private final byte[] bytes;
    private int at;

    Seeded(byte[] bytes) {
      this.bytes = bytes.clone();
    }

    @Override
    public void nextBytes(byte[] out) {
      if (at + out.length > bytes.length) throw new IllegalStateException("the seed is too short");
      java.lang.System.arraycopy(bytes, at, out, 0, out.length);
      at += out.length;
    }
  }

  // FIPS 202.
  public static byte[] sha3_256(byte[] message) {
    try {
      return java.security.MessageDigest.getInstance("SHA3-256").digest(message);
    } catch (java.security.GeneralSecurityException failed) {
      throw new IllegalStateException(failed);
    }
  }

  public static byte[] shake256(byte[] message, int length) {
    var digest = new org.bouncycastle.crypto.digests.SHAKEDigest(256);
    digest.update(message, 0, message.length);
    byte[] out = new byte[Math.max(length, 0)];
    digest.doFinal(out, 0, out.length);
    return out;
  }

  // The SubjectPublicKeyInfo prefixes of the standards' public keys.
  private static final byte[] ML_KEM_768_SPKI = java.util.HexFormat.of().parseHex("308204b2300b0609608648016503040402038204a100");
  private static final byte[] ML_DSA_65_SPKI = java.util.HexFormat.of().parseHex("308207b2300b0609608648016503040312038207a100");

  static java.security.KeyPair keyPair(String algorithm, java.security.spec.NamedParameterSpec parameters, byte[] seed) {
    try {
      var generator = java.security.KeyPairGenerator.getInstance(algorithm);
      generator.initialize(parameters, new Seeded(seed));
      return generator.generateKeyPair();
    } catch (java.security.GeneralSecurityException failed) {
      throw new IllegalArgumentException(failed);
    }
  }

  static byte[] rawPublic(java.security.PublicKey key, int length) {
    byte[] encoded = key.getEncoded();
    return java.util.Arrays.copyOfRange(encoded, encoded.length - length, encoded.length);
  }

  static java.security.PublicKey publicKey(String algorithm, byte[] prefix, byte[] raw) throws java.security.GeneralSecurityException {
    return java.security.KeyFactory.getInstance(algorithm).generatePublic(new java.security.spec.X509EncodedKeySpec(concat(prefix, raw)));
  }

  // FIPS 203: ML-KEM-768. A secret key is the seed d || z.
  public static byte[] mlKem768PublicKey(byte[] seed) {
    return rawPublic(keyPair("ML-KEM-768", java.security.spec.NamedParameterSpec.ML_KEM_768, seed).getPublic(), 1184);
  }

  /** The ciphertext and the shared secret; randomness gives the message m (32 bytes). */
  public static byte[][] mlKem768Encapsulate(byte[] publicKey, java.security.SecureRandom randomness) {
    try {
      var encapsulated = javax.crypto.KEM.getInstance("ML-KEM")
          .newEncapsulator(publicKey("ML-KEM", ML_KEM_768_SPKI, publicKey), randomness).encapsulate();
      return new byte[][] {encapsulated.encapsulation(), encapsulated.key().getEncoded()};
    } catch (java.security.GeneralSecurityException failed) {
      throw new IllegalArgumentException(failed);
    }
  }

  public static byte[] mlKem768Decapsulate(java.security.PrivateKey key, byte[] ciphertext) {
    try {
      return javax.crypto.KEM.getInstance("ML-KEM").newDecapsulator(key).decapsulate(ciphertext).getEncoded();
    } catch (java.security.GeneralSecurityException failed) {
      throw new IllegalArgumentException(failed);
    }
  }

  public static byte[] mlKem768Decapsulate(byte[] seed, byte[] ciphertext) {
    return mlKem768Decapsulate(keyPair("ML-KEM-768", java.security.spec.NamedParameterSpec.ML_KEM_768, seed).getPrivate(), ciphertext);
  }

  // FIPS 204: ML-DSA-65. A secret key is the seed xi.
  public static byte[] mlDsa65PublicKey(byte[] seed) {
    return rawPublic(keyPair("ML-DSA-65", java.security.spec.NamedParameterSpec.ML_DSA_65, seed).getPublic(), 1952);
  }

  /** Hedged, or deterministic (rnd all zero, as FIPS 204 defines it). The JDK signs with an empty context. */
  public static byte[] mlDsa65Sign(byte[] seed, byte[] message, boolean deterministic) {
    try {
      var signer = java.security.Signature.getInstance("ML-DSA");
      signer.initSign(keyPair("ML-DSA-65", java.security.spec.NamedParameterSpec.ML_DSA_65, seed).getPrivate(),
          deterministic ? new Seeded(new byte[32]) : SECURE);
      signer.update(message);
      return signer.sign();
    } catch (java.security.GeneralSecurityException failed) {
      throw new IllegalArgumentException(failed);
    }
  }

  public static boolean mlDsa65Verify(byte[] publicKey, byte[] message, byte[] signature) {
    try {
      var verifier = java.security.Signature.getInstance("ML-DSA");
      verifier.initVerify(publicKey("ML-DSA", ML_DSA_65_SPKI, publicKey));
      verifier.update(message);
      return verifier.verify(signature);
    } catch (java.security.GeneralSecurityException | RuntimeException failed) {
      return false;
    }
  }

  /**
   * Verification with a context string. The JDK's ML-DSA takes none, so a
   * non-empty context goes to Bouncy Castle's.
   */
  public static boolean mlDsa65Verify(byte[] publicKey, byte[] message, byte[] signature, byte[] context) {
    if (context.length == 0) return mlDsa65Verify(publicKey, message, signature);
    try {
      var verifier = new org.bouncycastle.crypto.signers.MLDSASigner();
      verifier.init(false, new org.bouncycastle.crypto.params.ParametersWithContext(
          new org.bouncycastle.crypto.params.MLDSAPublicKeyParameters(org.bouncycastle.crypto.params.MLDSAParameters.ml_dsa_65, publicKey), context));
      verifier.update(message, 0, message.length);
      return verifier.verifySignature(signature);
    } catch (RuntimeException failed) {
      return false;
    }
  }

  // FIPS 205: SLH-DSA-SHAKE-128f. A secret key is SK.seed || SK.prf || PK.seed || PK.root.
  public static byte[][] slhDsaKeyPair(byte[] skSeed, byte[] skPrf, byte[] pkSeed) {
    var generator = new org.bouncycastle.crypto.generators.SLHDSAKeyPairGenerator();
    generator.init(new org.bouncycastle.crypto.params.SLHDSAKeyGenerationParameters(
        new Seeded(concat(skSeed, skPrf, pkSeed)), org.bouncycastle.crypto.params.SLHDSAParameters.shake_128f));
    var pair = generator.generateKeyPair();
    return new byte[][] {
      ((org.bouncycastle.crypto.params.SLHDSAPublicKeyParameters) pair.getPublic()).getEncoded(),
      ((org.bouncycastle.crypto.params.SLHDSAPrivateKeyParameters) pair.getPrivate()).getEncoded()
    };
  }

  public static byte[] slhDsaSign(byte[] secretKey, byte[] message, byte[] context) {
    var signer = new org.bouncycastle.crypto.signers.SLHDSASigner();
    var key = new org.bouncycastle.crypto.params.SLHDSAPrivateKeyParameters(org.bouncycastle.crypto.params.SLHDSAParameters.shake_128f, secretKey);
    signer.init(true, new org.bouncycastle.crypto.params.ParametersWithContext(
        new org.bouncycastle.crypto.params.ParametersWithRandom(key, SECURE), context));
    return signer.generateSignature(message);
  }

  public static boolean slhDsaVerify(byte[] publicKey, byte[] message, byte[] signature, byte[] context) {
    try {
      var verifier = new org.bouncycastle.crypto.signers.SLHDSASigner();
      verifier.init(false, new org.bouncycastle.crypto.params.ParametersWithContext(
          new org.bouncycastle.crypto.params.SLHDSAPublicKeyParameters(org.bouncycastle.crypto.params.SLHDSAParameters.shake_128f, publicKey), context));
      return verifier.verifySignature(message, signature);
    } catch (RuntimeException failed) {
      return false;
    }
  }

  // AES-256-GCM: a sealed message is the 12-byte nonce, the ciphertext and the 16-byte tag.
  public static byte[] aes256GcmEncrypt(byte[] key, byte[] nonce, byte[] plaintext, byte[] associated) {
    try {
      var cipher = javax.crypto.Cipher.getInstance("AES/GCM/NoPadding");
      cipher.init(javax.crypto.Cipher.ENCRYPT_MODE, new javax.crypto.spec.SecretKeySpec(key, "AES"),
          new javax.crypto.spec.GCMParameterSpec(128, nonce));
      cipher.updateAAD(associated);
      return cipher.doFinal(plaintext);
    } catch (java.security.GeneralSecurityException failed) {
      throw new IllegalArgumentException(failed);
    }
  }

  /** The plaintext, or null when the key, nonce, tag or associated data do not match. */
  public static byte[] aes256GcmDecrypt(byte[] key, byte[] nonce, byte[] sealed, byte[] associated) {
    if (key.length != 32 || nonce.length != 12 || sealed.length < 16) return null;
    try {
      var cipher = javax.crypto.Cipher.getInstance("AES/GCM/NoPadding");
      cipher.init(javax.crypto.Cipher.DECRYPT_MODE, new javax.crypto.spec.SecretKeySpec(key, "AES"),
          new javax.crypto.spec.GCMParameterSpec(128, nonce));
      cipher.updateAAD(associated);
      return cipher.doFinal(sealed);
    } catch (java.security.GeneralSecurityException failed) {
      return null;
    }
  }

  /** SHA3-256 and SHAKE256. */
  public static final class HashHandler implements lawspec.abilities.lawspec.Crypto.Hash {
    @Override
    public @@Digest@@ sha3(byte[] value0) {
      return new @@Digest@@(sha3_256(value0));
    }

    @Override
    public byte[] shake(byte[] value0, java.lang.Integer value1) {
      return shake256(value0, value1);
    }
  }

  /** ML-KEM-768. */
  public static final class KeyExchangeHandler implements lawspec.abilities.lawspec.Crypto.KeyExchange {
    @Override
    public @@ExchangeKeyPair@@ exchangeKeyPair() {
      byte[] seed = randomBytes(64);
      return new @@ExchangeKeyPair@@(new @@ExchangePublicKey@@(mlKem768PublicKey(seed)), new @@ExchangeSecretKey@@(seed));
    }

    @Override
    public @@Encapsulated@@ encapsulate(@@ExchangePublicKey@@ value0) {
      byte[][] made = mlKem768Encapsulate(value0.value(), SECURE);
      return new @@Encapsulated@@(new @@Ciphertext@@(made[0]), new @@SharedSecret@@(made[1]));
    }

    @Override
    public @@SharedSecret@@ decapsulate(@@ExchangeSecretKey@@ value0, @@Ciphertext@@ value1) {
      return new @@SharedSecret@@(mlKem768Decapsulate(value0.value(), value1.value()));
    }
  }

  /** ML-DSA-65, hedged. */
  public static final class SignatureHandler implements lawspec.abilities.lawspec.Crypto.Signature {
    @Override
    public @@SigningKeyPair@@ signingKeyPair() {
      byte[] seed = randomBytes(32);
      return new @@SigningKeyPair@@(new @@VerifyingKey@@(mlDsa65PublicKey(seed)), new @@SigningKey@@(seed));
    }

    @Override
    public @@SignatureBytes@@ sign(@@SigningKey@@ value0, byte[] value1) {
      return new @@SignatureBytes@@(mlDsa65Sign(value0.value(), value1, false));
    }

    @Override
    public java.lang.Boolean verify(@@VerifyingKey@@ value0, byte[] value1, @@SignatureBytes@@ value2) {
      return mlDsa65Verify(value0.value(), value1, value2.value());
    }
  }

  /**
   * SLH-DSA-SHAKE-128f, hedged: the alternative Signature handler. Bind it in
   * lawspec.json: {"ability": "lawspec.crypto::Signature", "native": ["lawspec",
   * "Crypto", "SlhDsaSignatureHandler"]}.
   */
  public static final class SlhDsaSignatureHandler implements lawspec.abilities.lawspec.Crypto.Signature {
    @Override
    public @@SigningKeyPair@@ signingKeyPair() {
      byte[][] pair = slhDsaKeyPair(randomBytes(16), randomBytes(16), randomBytes(16));
      return new @@SigningKeyPair@@(new @@VerifyingKey@@(pair[0]), new @@SigningKey@@(pair[1]));
    }

    @Override
    public @@SignatureBytes@@ sign(@@SigningKey@@ value0, byte[] value1) {
      return new @@SignatureBytes@@(slhDsaSign(value0.value(), value1, new byte[0]));
    }

    @Override
    public java.lang.Boolean verify(@@VerifyingKey@@ value0, byte[] value1, @@SignatureBytes@@ value2) {
      return slhDsaVerify(value0.value(), value1, value2.value(), new byte[0]);
    }
  }

  /** AES-256-GCM, a fresh random nonce per message. */
  public static final class AeadHandler implements lawspec.abilities.lawspec.Crypto.Aead {
    @Override
    public @@AeadKey@@ aeadKey() {
      return new @@AeadKey@@(randomBytes(32));
    }

    @Override
    public @@AeadKey@@ deriveAeadKey(@@SharedSecret@@ value0, byte[] value1) {
      return new @@AeadKey@@(shake256(concat(value0.value(), value1), 32));
    }

    @Override
    public @@Sealed@@ seal(@@AeadKey@@ value0, byte[] value1, byte[] value2) {
      byte[] nonce = randomBytes(12);
      return new @@Sealed@@(concat(nonce, aes256GcmEncrypt(value0.value(), nonce, value1, value2)));
    }

    @Override
    public lawspec.runtime.LawSpecRuntime.Maybe<byte[]> unseal(@@AeadKey@@ value0, @@Sealed@@ value1, byte[] value2) {
      byte[] sealed = value1.value();
      byte[] opened = sealed.length < 12 ? null
          : aes256GcmDecrypt(value0.value(), java.util.Arrays.copyOf(sealed, 12), java.util.Arrays.copyOfRange(sealed, 12, sealed.length), value2);
      return opened == null ? new lawspec.runtime.LawSpecRuntime.Nothing<>() : new lawspec.runtime.LawSpecRuntime.Just<>(opened);
    }
  }
}
