// Generated by LawSpec. Do not edit.
package lawspec;

/** The default handlers of lawspec.host: the process's file system, environment and free ports. */
public final class Host {
  private Host() {}

  /** Files by path; a relative path is from the working directory. */
  public static final class FileSystemHandler implements lawspec.abilities.lawspec.Host.FileSystem {
    @Override
    public lawspec.runtime.LawSpecRuntime.Maybe<byte[]> readBytes(java.lang.String value0) {
      try {
        return new lawspec.runtime.LawSpecRuntime.Just<>(java.nio.file.Files.readAllBytes(java.nio.file.Path.of(value0)));
      } catch (java.io.IOException | RuntimeException failed) {
        return new lawspec.runtime.LawSpecRuntime.Nothing<>();
      }
    }

    @Override
    public void writeBytes(java.lang.String value0, byte[] value1) {
      try {
        java.nio.file.Files.write(java.nio.file.Path.of(value0), value1);
      } catch (java.io.IOException failed) {
        throw new java.io.UncheckedIOException(failed);
      }
    }

    @Override
    public java.lang.Boolean pathExists(java.lang.String value0) {
      try {
        return java.nio.file.Files.exists(java.nio.file.Path.of(value0), java.nio.file.LinkOption.NOFOLLOW_LINKS);
      } catch (RuntimeException failed) {
        return false;
      }
    }

    @Override
    public void removePath(java.lang.String value0) {
      java.nio.file.Path path = java.nio.file.Path.of(value0);
      try {
        if (java.nio.file.Files.isDirectory(path, java.nio.file.LinkOption.NOFOLLOW_LINKS)) {
          try (var walk = java.nio.file.Files.walk(path)) {
            for (java.nio.file.Path entry : walk.sorted(java.util.Comparator.reverseOrder()).toList()) {
              java.nio.file.Files.delete(entry);
            }
          }
        } else {
          java.nio.file.Files.deleteIfExists(path);
        }
      } catch (java.io.IOException failed) {
        throw new java.io.UncheckedIOException(failed);
      }
    }

    @Override
    public java.lang.String temporaryDirectory(java.lang.String value0) {
      return temporary(value0, true);
    }

    @Override
    public java.lang.String temporaryFile(java.lang.String value0) {
      return temporary(value0, false);
    }
  }

  public static java.lang.String temporary(java.lang.String prefix, boolean directory) {
    try {
      return (directory ? java.nio.file.Files.createTempDirectory(prefix) : java.nio.file.Files.createTempFile(prefix, "")).toString();
    } catch (java.io.IOException failed) {
      throw new java.io.UncheckedIOException(failed);
    }
  }

  public static boolean validName(java.lang.String name) {
    return !name.isEmpty() && name.indexOf('=') < 0 && name.indexOf('\0') < 0;
  }

  /** The process's environment. */
  public static final class EnvironmentHandler implements lawspec.abilities.lawspec.Host.Environment {
    @Override
    public lawspec.runtime.LawSpecRuntime.Maybe<java.lang.String> environmentVariable(java.lang.String value0) {
      java.lang.String value = validName(value0) ? java.lang.System.getenv(value0) : null;
      return value == null ? new lawspec.runtime.LawSpecRuntime.Nothing<>() : new lawspec.runtime.LawSpecRuntime.Just<>(value);
    }

    @Override
    public java.lang.String environmentSnapshot() {
      return lawspec.runtime.LawSpecRuntime.acquireResource("environment");
    }

    @Override
    public void restoreEnvironment(java.lang.String value0) {
      lawspec.runtime.LawSpecRuntime.releaseResource("environment", value0);
    }
  }

  /** A TCP port on 127.0.0.1 the operating system reports free. */
  public static final class PortsHandler implements lawspec.abilities.lawspec.Host.Ports {
    @Override
    public java.lang.Integer freePort() {
      try (var socket = new java.net.ServerSocket(0, 1, java.net.InetAddress.getLoopbackAddress())) {
        return socket.getLocalPort();
      } catch (java.io.IOException failed) {
        throw new java.io.UncheckedIOException(failed);
      }
    }
  }
}
