-- Typed actors for Go implementation code (see LawSpec.Actors).
--
-- Every actor becomes a struct named for its handle type in
-- lawspec_actors.go of its unit's package, beside the adapters it calls:
-- StartAccountActor(...) makes the state with the start adapter and runs it
-- in a LawSpecActor; each handler is a method that sends its message and
-- returns the reply and an error (the handler's panic, or a stopped actor),
-- and Tell<Handler> sends it without waiting. Stop refuses further messages.
-- Start<Actor>Under starts one under a LawSpecSupervisor with a lifetime;
-- a crash then restarts it from its restart adapter (or its start). Every
-- supervisor becomes a struct too: Start<Name>Supervisor starts its
-- children, which are its exported fields.
module LawSpec.Actors.Go (emit) where

import Data.Char (toUpper)
import Data.List (intercalate, nub)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (unitName)
import LawSpec.GoData (goDataType)
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ _ datas actors supervisions = mapM unitFile (nub (map (unitName . actorUnit) actors))
  where
    unitFile u = do
      let mine = [a | a <- actors, unitName (actorUnit a) == u]
          sups = [s | s <- supervisions, unitName (supervisionUnit s) == u]
          parts = splitOn '.' u
      bodies <- mapM (actorText datas) mine
      let header =
            [ "// Generated by LawSpec. Do not edit."
            , "package " ++ last parts
            , "" ] ++
            [ "import \"time\"\n" | not (null sups) ] ++
            [ "// Typed actors for this unit. Start<Actor> starts one; each handler method"
            , "// sends a message and waits for the reply, and Tell<Handler> sends it"
            , "// without waiting. Messages are handled one at a time, in the order they"
            , "// arrive. A handler's panic crashes the actor and is an error for its"
            , "// caller; a supervised actor then restarts, any other stops."
            ]
      pure (Artifact (intercalate "/" parts ++ "/lawspec_actors.go")
        (unlines (header ++ concat bodies ++ concatMap supervisorText sups)) "generated" "source")

actorText :: [C.DataDeclaration] -> Actor -> Either String [String]
actorText datas a = do
  own <- goDataType datas (actorState a)
  startArgs <- mapM argument (actorStartArguments a)
  methods <- mapM (handler own) (actorHandlers a)
  let cls = actorClass a
      params = [p ++ " " ++ n | (p, t, n) <- startArgs, not (unit t)]
      values = [if unit t then "lsAbsent(\"Unit\")" else p | (p, t, _) <- startArgs]
      made = awaited (actorStart a) (adapter (actorStart a) ++ "(" ++ intercalate ", " values ++ ")")
      restarted = case actorRestart a of
        Just d -> awaited d (adapter d ++ "(state.(" ++ own ++ "))")
        Nothing -> made
      names = [p | (p, t, _) <- startArgs, not (unit t)]
  pure $
    [ ""
    , "// " ++ cls ++ " is actor " ++ actorName a ++ ": it owns its state and handles one message"
    , "// at a time."
    , "type " ++ cls ++ " struct{ actor *LawSpecActor }"
    , ""
    , "// Start" ++ cls ++ " makes the actor's state with " ++ adapter (actorStart a) ++ " and starts the actor."
    , "func Start" ++ cls ++ "(" ++ intercalate ", " params ++ ") " ++ cls ++ " {"
    , "\treturn Start" ++ cls ++ "Under(" ++ intercalate ", " (["nil", "LawSpecPermanent"] ++ names) ++ ")"
    , "}"
    , ""
    , "// Start" ++ cls ++ "Under starts the actor under supervisor (when not nil) with a"
    , "// lifetime (LawSpecPermanent, LawSpecTransient or LawSpecTemporary). After a"
    , "// crash it restarts " ++ maybe "from its start" (\d -> "from its last state by " ++ adapter d) (actorRestart a) ++ "."
    , "func Start" ++ cls ++ "Under(" ++ intercalate ", " (["supervisor *LawSpecSupervisor", "lifetime string"] ++ params) ++ ") " ++ cls ++ " {"
    , "\tactor := NewLawSpecActorWithRestart(" ++ made ++ ", func(state any) any {"
    , "\t\treturn " ++ restarted
    , "\t})"
    , "\tif supervisor != nil {"
    , "\t\tsupervisor.SuperviseActor(actor, lifetime)"
    , "\t}"
    , "\treturn " ++ cls ++ "{actor}"
    , "}" ] ++ concat methods ++
    [ ""
    , "// Crash crashes the actor as a failing handler would, after the messages"
    , "// already sent: for testing how it restarts."
    , "func (a " ++ cls ++ ") Crash() error {"
    , "\treturn a.actor.Crash(\"crashed on purpose\")"
    , "}"
    , ""
    , "// Monitor calls notify with \"crashed\" after each crash, and \"stopped\" once"
    , "// the actor stops."
    , "func (a " ++ cls ++ ") Monitor(notify func(LawSpecExit)) {"
    , "\ta.actor.Monitor(notify)"
    , "}"
    , ""
    , "// Link links two actors: when either crashes, the other crashes too."
    , "func (a " ++ cls ++ ") Link(other interface{ Actor() *LawSpecActor }) {"
    , "\ta.actor.Link(other.Actor())"
    , "}"
    , ""
    , "// Actor is the runtime actor underneath."
    , "func (a " ++ cls ++ ") Actor() *LawSpecActor {"
    , "\treturn a.actor"
    , "}"
    , ""
    , "// Stop refuses further messages; those already sent are still handled."
    , "func (a " ++ cls ++ ") Stop() {"
    , "\ta.actor.Stop()"
    , "}" ]
  where
    unit t = t == C.Constructor "Unit" []
    adapter d = capitalize (C.declarationName d)
    awaited d call = if C.declarationAsync d then call ++ ".Await()" else call
    argument (p, t) = do
      n <- if unit t then pure "LawSpecValue" else goDataType datas t
      pure (p, t, n)
    handler own h = do
      args <- mapM argument (handlerArguments h)
      reply <- traverse (goDataType datas) (handlerReply h)
      let cls = actorClass a
          name = capitalize (handlerName h)
          params = intercalate ", " [p ++ " " ++ n | (p, _, n) <- args]
          values = [if unit t then "lsAbsent(\"Unit\")" else p | (p, t, _) <- args]
          call = awaited (handlerDeclaration h) (adapter (handlerDeclaration h) ++ "(" ++ intercalate ", " (("state.(" ++ own ++ ")") : values) ++ ")")
          step = case reply of
            Just _ ->
              [ "func(state any) (any, any) {"
              , "\t\tout := " ++ call
              , "\t\treturn out.First, out.Second"
              , "\t}" ]
            Nothing ->
              [ "func(state any) (any, any) {"
              , "\t\treturn nil, " ++ call
              , "\t}" ]
          inline prefix suffix = case step of
            first : rest -> (prefix ++ first) : init rest ++ [last rest ++ suffix]
            [] -> []
      pure $
        [ ""
        , "// " ++ name ++ " sends " ++ handlerName h ++ " and waits for the reply."
        , "func (a " ++ cls ++ ") " ++ name ++ "(" ++ params ++ ") " ++ maybe "error" (\r -> "(" ++ r ++ ", error)") reply ++ " {" ] ++
        (case reply of
          Just r ->
            inline "\treply, err := a.actor.Call(" ")" ++
            [ "\tif err != nil {"
            , "\t\tvar none " ++ r
            , "\t\treturn none, err"
            , "\t}"
            , "\treturn reply.(" ++ r ++ "), nil" ]
          Nothing ->
            inline "\t_, err := a.actor.Call(" ")" ++
            [ "\treturn err" ]) ++
        [ "}"
        , ""
        , "// Tell" ++ name ++ " sends " ++ handlerName h ++ " without waiting for the reply."
        , "func (a " ++ cls ++ ") Tell" ++ name ++ "(" ++ params ++ ") error {" ] ++
        inline "\treturn a.actor.Cast(" ")" ++
        [ "}" ]

-- A supervisor's struct: Start<Name>Supervisor starts the runtime
-- supervisor and each child under it, in order; each child is a field.
supervisorText :: Supervision -> [String]
supervisorText s =
  [ ""
  , "// " ++ cls ++ " is supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++
      show (supervisionRestarts s) ++ " restarts in " ++ show (supervisionPeriod s) ++ "µs."
  , "type " ++ cls ++ " struct {"
  , "\tsupervisor *LawSpecSupervisor" ] ++
  [ "\t" ++ capitalize name ++ " " ++ childClass child | (_, name, child) <- supervisionChildren s ] ++
  [ "}"
  , ""
  , "// Start" ++ cls ++ " starts the supervisor and its children."
  , "func Start" ++ cls ++ "() " ++ cls ++ " {"
  , "\treturn Start" ++ cls ++ "Under(nil, LawSpecPermanent)"
  , "}"
  , ""
  , "// Start" ++ cls ++ "Under starts it under parent (when not nil) with a lifetime."
  , "func Start" ++ cls ++ "Under(parent *LawSpecSupervisor, lifetime string) " ++ cls ++ " {"
  , "\town := NewLawSpecSupervisor(" ++ strategyName ++ ", " ++ show (supervisionRestarts s) ++ ", " ++
      show (supervisionPeriod s) ++ "*time.Microsecond)" ] ++
  [ "\t" ++ local name ++ " := Start" ++ childClass child ++ "Under(own, " ++ lifetimeName l ++ ")"
  | (l, name, child) <- supervisionChildren s ] ++
  [ "\tif parent != nil {"
  , "\t\tparent.SuperviseSupervisor(own, lifetime)"
  , "\t}"
  , "\treturn " ++ cls ++ "{" ++ intercalate ", " ("own" : [local name | (_, name, _) <- supervisionChildren s]) ++ "}"
  , "}"
  , ""
  , "// Monitor calls notify with \"crashed\" when the supervisor passes its restart"
  , "// limit, and \"stopped\" once stopped."
  , "func (s " ++ cls ++ ") Monitor(notify func(LawSpecExit)) {"
  , "\ts.supervisor.Monitor(notify)"
  , "}"
  , ""
  , "// Stop stops every child, last started first, without restarting them."
  , "func (s " ++ cls ++ ") Stop() {"
  , "\ts.supervisor.Stop()"
  , "}"
  , ""
  , "// Supervisor is the runtime supervisor underneath."
  , "func (s " ++ cls ++ ") Supervisor() *LawSpecSupervisor {"
  , "\treturn s.supervisor"
  , "}" ]
  where
    cls = supervisionClass s
    local name = "child" ++ capitalize name
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    strategyName = case supervisionStrategy s of
      OneForOne -> "LawSpecOneForOne"
      OneForAll -> "LawSpecOneForAll"
      RestForOne -> "LawSpecRestForOne"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one"
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    lifetimeName l = case l of
      Permanent -> "LawSpecPermanent"
      Transient -> "LawSpecTransient"
      Temporary -> "LawSpecTemporary"

capitalize :: String -> String
capitalize [] = []
capitalize (c:cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn c s = case break (== c) s of
  (x, []) -> [x]
  (x, _:rest) -> x : splitOn c rest
