-- | Typed actors for Go implementation code (see LawSpec.Actors).
--
-- Every actor becomes a struct named for its handle type in
-- lawspec_actors.go of its unit's package, beside the adapters it calls:
-- StartAccountActor(...) makes the state with the start adapter and runs it
-- in a LawSpecActor; each handler is a method that sends its message and
-- returns the reply and an error (the handler's panic, or a stopped actor),
-- and Tell<Handler> sends it without waiting. Stop refuses further messages.
-- Start<Actor>Under starts one under a LawSpecSupervisor with a lifetime;
-- a crash then restarts it from its restart adapter (or its start). Every
-- supervisor becomes a struct too: Start<Name>Supervisor starts its
-- children, which are its exported fields.
module LawSpec.Actors.Go (emit) where

import Data.Char (toUpper)
import Data.List (intercalate, nub)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (unitName)
import LawSpec.GoData (goDataType, goCodec, requiresSchema)
import LawSpec.MachineSpec (describe)
import Control.Monad (foldM)
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))

-- | Actors become a typed class, or Go's idiom for one, generated from the
-- declaration. ref:DEC-actors-otp-supervision
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ bits datas actors supervisions = mapM unitFile (nub (map (unitName . actorUnit) actors))
  where
    unitFile u = do
      let mine = [a | a <- actors, unitName (actorUnit a) == u]
          sups = [s | s <- supervisions, unitName (supervisionUnit s) == u]
          parts = splitOn '.' u
          -- Each actor's messages as wire descriptors, for serving it and
          -- calling it across nodes; an actor whose types have none stays local.
          wired (table, acc) a = case foldM (handlerWire bits datas) (table, []) (actorHandlers a) of
            Right (table', hs) -> (table', acc ++ [(actorName a, reverse hs)])
            Left _ -> (table, acc)
          (types, wires) = foldl wired ([], []) mine
          schemaUsed = or [requiresSchema datas t | (_, hs) <- wires, (h, _, _) <- hs
                          , t <- maybe [] pure (handlerReply h) ++ map snd (handlerArguments h)]
      bodies <- mapM (\a -> (++) <$> actorText datas a <*> remoteText bits datas a (lookup (actorName a) wires)) mine
      let header =
            [ "// Generated by LawSpec. Do not edit."
            , "package " ++ last parts
            , "" ] ++
            [ "import \"time\"\n" | not (null sups) || not (null wires) ] ++
            [ "var lawSpecActorTypes = LawSpecTypes(" ++ show (unwords (map snd (reverse types))) ++ ")\n" | not (null wires) ] ++
            [ "var lawSpecActorSchema = lawSpecDataSchemaRegistry()\n" | schemaUsed ] ++
            [ "// Typed actors for this unit. Start<Actor> starts one; each handler method"
            , "// sends a message and waits for the reply, and Tell<Handler> sends it"
            , "// without waiting. Messages are handled one at a time, in the order they"
            , "// arrive. A handler's panic crashes the actor and is an error for its"
            , "// caller; a supervised actor then restarts, any other stops."
            ]
      pure (Artifact (intercalate "/" parts ++ "/lawspec_actors.go")
        (unlines (header ++ concat bodies ++ concatMap supervisorText sups)) "generated" "source")

actorText :: [C.DataDeclaration] -> Actor -> Either String [String]
actorText datas a = do
  own <- goDataType datas (actorState a)
  startArgs <- mapM argument (actorStartArguments a)
  methods <- mapM (handler own) (actorHandlers a)
  let cls = actorClass a
      params = [p ++ " " ++ n | (p, t, n) <- startArgs, not (unit t)]
      values = [if unit t then "lsAbsent(\"Unit\")" else p | (p, t, _) <- startArgs]
      made = awaited (actorStart a) (adapter (actorStart a) ++ "(" ++ intercalate ", " values ++ ")")
      restarted = case actorRestart a of
        Just d -> awaited d (adapter d ++ "(state.(" ++ own ++ "))")
        Nothing -> made
      names = [p | (p, t, _) <- startArgs, not (unit t)]
  pure $
    [ ""
    , "// " ++ cls ++ " is actor " ++ actorName a ++ ": it owns its state and handles one message"
    , "// at a time."
    , "type " ++ cls ++ " struct{ actor *LawSpecActor }"
    , ""
    , "// Start" ++ cls ++ " makes the actor's state with " ++ adapter (actorStart a) ++ " and starts the actor."
    , "func Start" ++ cls ++ "(" ++ intercalate ", " params ++ ") " ++ cls ++ " {"
    , "\treturn Start" ++ cls ++ "Under(" ++ intercalate ", " (["nil", "LawSpecPermanent"] ++ names) ++ ")"
    , "}"
    , ""
    , "// Start" ++ cls ++ "Under starts the actor under supervisor (when not nil) with a"
    , "// lifetime (LawSpecPermanent, LawSpecTransient or LawSpecTemporary). After a"
    , "// crash it restarts " ++ maybe "from its start" (\d -> "from its last state by " ++ adapter d) (actorRestart a) ++ "."
    , "func Start" ++ cls ++ "Under(" ++ intercalate ", " (["supervisor *LawSpecSupervisor", "lifetime string"] ++ params) ++ ") " ++ cls ++ " {"
    , "\tactor := NewLawSpecActorWithRestart(" ++ made ++ ", func(state any) any {"
    , "\t\treturn " ++ restarted
    , "\t})"
    , "\tif supervisor != nil {"
    , "\t\tsupervisor.SuperviseActor(actor, lifetime)"
    , "\t}"
    , "\treturn " ++ cls ++ "{actor}"
    , "}" ] ++ concat methods ++
    [ ""
    , "// Crash crashes the actor as a failing handler would, after the messages"
    , "// already sent: for testing how it restarts."
    , "func (a " ++ cls ++ ") Crash() error {"
    , "\treturn a.actor.Crash(\"crashed on purpose\")"
    , "}"
    , ""
    , "// Monitor calls notify with \"crashed\" after each crash, and \"stopped\" once"
    , "// the actor stops."
    , "func (a " ++ cls ++ ") Monitor(notify func(LawSpecExit)) {"
    , "\ta.actor.Monitor(notify)"
    , "}"
    , ""
    , "// Link links two actors: when either crashes, the other crashes too."
    , "func (a " ++ cls ++ ") Link(other interface{ Actor() *LawSpecActor }) {"
    , "\ta.actor.Link(other.Actor())"
    , "}"
    , ""
    , "// Actor is the runtime actor underneath."
    , "func (a " ++ cls ++ ") Actor() *LawSpecActor {"
    , "\treturn a.actor"
    , "}"
    , ""
    , "// Stop refuses further messages; those already sent are still handled."
    , "func (a " ++ cls ++ ") Stop() {"
    , "\ta.actor.Stop()"
    , "}" ]
  where
    unit t = t == C.Constructor "Unit" []
    adapter d = capitalize (C.declarationName d)
    awaited d call = if C.declarationAsync d then call ++ ".Await()" else call
    argument (p, t) = do
      n <- if unit t then pure "LawSpecValue" else goDataType datas t
      pure (p, t, n)
    handler own h = do
      args <- mapM argument (handlerArguments h)
      reply <- traverse (goDataType datas) (handlerReply h)
      let cls = actorClass a
          name = capitalize (handlerName h)
          params = intercalate ", " [p ++ " " ++ n | (p, _, n) <- args]
          values = [if unit t then "lsAbsent(\"Unit\")" else p | (p, t, _) <- args]
          call = awaited (handlerDeclaration h) (adapter (handlerDeclaration h) ++ "(" ++ intercalate ", " (("state.(" ++ own ++ ")") : values) ++ ")")
          step = case reply of
            Just _ ->
              [ "func(state any) (any, any) {"
              , "\t\tout := " ++ call
              , "\t\treturn out.First, out.Second"
              , "\t}" ]
            Nothing ->
              [ "func(state any) (any, any) {"
              , "\t\treturn nil, " ++ call
              , "\t}" ]
          inline prefix suffix = case step of
            first : rest -> (prefix ++ first) : init rest ++ [last rest ++ suffix]
            [] -> []
      pure $
        [ ""
        , "// " ++ name ++ " sends " ++ handlerName h ++ " and waits for the reply."
        , "func (a " ++ cls ++ ") " ++ name ++ "(" ++ params ++ ") " ++ maybe "error" (\r -> "(" ++ r ++ ", error)") reply ++ " {" ] ++
        (case reply of
          Just r ->
            inline "\treply, err := a.actor.Call(" ")" ++
            [ "\tif err != nil {"
            , "\t\tvar none " ++ r
            , "\t\treturn none, err"
            , "\t}"
            , "\treturn reply.(" ++ r ++ "), nil" ]
          Nothing ->
            inline "\t_, err := a.actor.Call(" ")" ++
            [ "\treturn err" ]) ++
        [ "}"
        , ""
        , "// Tell" ++ name ++ " sends " ++ handlerName h ++ " without waiting for the reply."
        , "func (a " ++ cls ++ ") Tell" ++ name ++ "(" ++ params ++ ") error {" ] ++
        inline "\treturn a.actor.Cast(" ")" ++
        [ "}" ]

-- | A handler's argument and reply descriptors (adding data types to the
-- table).
type HandlerWire = (Handler, [String], String)

handlerWire :: Int -> [C.DataDeclaration] -> ([(String, String)], [HandlerWire]) -> Handler -> Either String ([(String, String)], [HandlerWire])
handlerWire bits datas (table, acc) h = do
  (args, table') <- foldM (\(xs, t) (_, ty) -> (\(x, t') -> (xs ++ [x], t')) <$> describe bits datas t ty) ([], table) (handlerArguments h)
  (reply, table'') <- describe bits datas table' (maybe (C.Constructor "Unit" []) id (handlerReply h))
  pure (table'', (h, args, reply) : acc)

-- | Serve, Connect<Actor> and the <Actor>Remote proxy: values cross the
-- network as logical values, converted with the unit's codecs.
remoteText :: Int -> [C.DataDeclaration] -> Actor -> Maybe [HandlerWire] -> Either String [String]
remoteText _ _ _ Nothing = pure []
remoteText bits datas a (Just hs) = do
  own <- goDataType datas (actorState a)
  served <- mapM (serveEntry own) hs
  methods <- mapM proxyMethod hs
  pure $
    [ ""
    , "// Serve lets other nodes call this actor at <node address>/name, and returns"
    , "// that address."
    , "func (a " ++ cls ++ ") Serve(node *LawSpecNode, name string) (string, error) {"
    , "\treturn node.Serve(name, a.actor, map[string]LawSpecRemoteHandler{" ] ++ concat served ++
    [ "\t}, lawSpecActorTypes)"
    , "}"
    , ""
    , "// " ++ cls ++ "Remote is actor " ++ actorName a ++ " on another node: each method sends its"
    , "// message and waits for the reply."
    , "type " ++ cls ++ "Remote struct{ remote *LawSpecRemoteActor }"
    , ""
    , "// Connect" ++ cls ++ " is the actor served at address on another node; each call"
    , "// waits up to timeout, then fails with LawSpecUnreachable."
    , "func Connect" ++ cls ++ "(node *LawSpecNode, address string, timeout time.Duration) " ++ cls ++ "Remote {"
    , "\treturn " ++ cls ++ "Remote{node.RemoteActor(address, map[string]LawSpecSignature{" ] ++
    [ "\t\t" ++ show (handlerName h) ++ ": {" ++ descriptors ds ++ ", LawSpecDescriptor(" ++ show r ++ ")},"
    | (h, ds, r) <- hs ] ++
    [ "\t}, lawSpecActorTypes, timeout)}"
    , "}" ] ++ concat methods
  where
    cls = actorClass a
    unit t = t == C.Constructor "Unit" []
    descriptors ds = "[]any{" ++ intercalate ", " ["LawSpecDescriptor(" ++ show d ++ ")" | d <- ds] ++ "}"
    codec ty = replace "schema, bits" ("lawSpecActorSchema, " ++ show bits) <$> goCodec datas ty
    toNative ty value
      | unit ty = pure value
      | requiresSchema datas ty = (\c -> c ++ ".toNative(" ++ value ++ ")") <$> codec ty
      | C.Constructor n [] <- ty = (\g -> "lsToNative(" ++ show n ++ ", " ++ value ++ ", " ++ show bits ++ ").(" ++ g ++ ")") <$> goDataType datas ty
      | otherwise = Left "no Go conversion for this type"
    toLogical ty value
      | unit ty = pure value
      | requiresSchema datas ty = (\c -> c ++ ".fromNative(" ++ value ++ ")") <$> codec ty
      | C.Constructor n [] <- ty = pure ("lsFromNative(" ++ show n ++ ", " ++ value ++ ", " ++ show bits ++ ")")
      | otherwise = Left "no Go conversion for this type"
    adapter d = capitalize (C.declarationName d)
    awaited d call = if C.declarationAsync d then call ++ ".Await()" else call
    serveEntry own (h, ds, r) = do
      args <- mapM (\(i, (_, ty)) -> toNative ty ("args[" ++ show i ++ "]")) (zip [0 :: Int ..] (handlerArguments h))
      let call = awaited (handlerDeclaration h) (adapter (handlerDeclaration h) ++ "(" ++ intercalate ", " (("state.(" ++ own ++ ")") : args) ++ ")")
      body <- case handlerReply h of
        Just reply -> do
          logical <- toLogical reply "out.First"
          pure [ "\t\t\tout := " ++ call, "\t\t\treturn " ++ logical ++ ", out.Second" ]
        Nothing -> pure [ "\t\t\treturn lsAbsent(\"Unit\"), " ++ call ]
      pure $ [ "\t\t" ++ show (handlerName h) ++ ": {func(state any, args []LawSpecValue) (LawSpecValue, any) {" ] ++ body ++
        [ "\t\t}, " ++ descriptors ds ++ ", LawSpecDescriptor(" ++ show r ++ ")}," ]
    proxyMethod (h, _, _) = do
      params <- mapM (\(p, ty) -> (\n -> p ++ " " ++ n) <$> (if unit ty then pure "LawSpecValue" else goDataType datas ty)) (handlerArguments h)
      logicals <- mapM (\(p, ty) -> toLogical ty p) (handlerArguments h)
      let name = capitalize (handlerName h)
          send = "r.remote.Call(" ++ intercalate ", " (show (handlerName h) : logicals) ++ ")"
      case handlerReply h of
        Just reply -> do
          native <- goDataType datas reply
          back <- toNative reply "reply"
          pure [ ""
               , "// " ++ name ++ " sends " ++ handlerName h ++ " and waits for the reply."
               , "func (r " ++ cls ++ "Remote) " ++ name ++ "(" ++ intercalate ", " params ++ ") (" ++ native ++ ", error) {"
               , "\treply, err := " ++ send
               , "\tif err != nil {"
               , "\t\tvar none " ++ native
               , "\t\treturn none, err"
               , "\t}"
               , "\treturn " ++ back ++ ", nil"
               , "}" ]
        Nothing -> pure
          [ ""
          , "// " ++ name ++ " sends " ++ handlerName h ++ " and waits for it to be handled."
          , "func (r " ++ cls ++ "Remote) " ++ name ++ "(" ++ intercalate ", " params ++ ") error {"
          , "\t_, err := " ++ send
          , "\treturn err"
          , "}" ]

replace :: String -> String -> String -> String
replace old new s = case s of
  [] -> []
  _ | take (length old) s == old -> new ++ replace old new (drop (length old) s)
  c : rest -> c : replace old new rest

-- | A supervisor's struct: Start<Name>Supervisor starts the runtime
-- supervisor and each child under it, in order; each child is a field.
supervisorText :: Supervision -> [String]
supervisorText s =
  [ ""
  , "// " ++ cls ++ " is supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++
      show (supervisionRestarts s) ++ " restarts in " ++ show (supervisionPeriod s) ++ "µs."
  , "type " ++ cls ++ " struct {"
  , "\tsupervisor *LawSpecSupervisor" ] ++
  [ "\t" ++ capitalize name ++ " " ++ childClass child | (_, name, child) <- supervisionChildren s ] ++
  [ "}"
  , ""
  , "// Start" ++ cls ++ " starts the supervisor and its children."
  , "func Start" ++ cls ++ "() " ++ cls ++ " {"
  , "\treturn Start" ++ cls ++ "Under(nil, LawSpecPermanent)"
  , "}"
  , ""
  , "// Start" ++ cls ++ "Under starts it under parent (when not nil) with a lifetime."
  , "func Start" ++ cls ++ "Under(parent *LawSpecSupervisor, lifetime string) " ++ cls ++ " {"
  , "\town := NewLawSpecSupervisor(" ++ strategyName ++ ", " ++ show (supervisionRestarts s) ++ ", " ++
      show (supervisionPeriod s) ++ "*time.Microsecond)" ] ++
  [ "\t" ++ local name ++ " := Start" ++ childClass child ++ "Under(own, " ++ lifetimeName l ++ ")"
  | (l, name, child) <- supervisionChildren s ] ++
  [ "\tif parent != nil {"
  , "\t\tparent.SuperviseSupervisor(own, lifetime)"
  , "\t}"
  , "\treturn " ++ cls ++ "{" ++ intercalate ", " ("own" : [local name | (_, name, _) <- supervisionChildren s]) ++ "}"
  , "}"
  , ""
  , "// Monitor calls notify with \"crashed\" when the supervisor passes its restart"
  , "// limit, and \"stopped\" once stopped."
  , "func (s " ++ cls ++ ") Monitor(notify func(LawSpecExit)) {"
  , "\ts.supervisor.Monitor(notify)"
  , "}"
  , ""
  , "// Stop stops every child, last started first, without restarting them."
  , "func (s " ++ cls ++ ") Stop() {"
  , "\ts.supervisor.Stop()"
  , "}"
  , ""
  , "// Supervisor is the runtime supervisor underneath."
  , "func (s " ++ cls ++ ") Supervisor() *LawSpecSupervisor {"
  , "\treturn s.supervisor"
  , "}" ]
  where
    cls = supervisionClass s
    local name = "child" ++ capitalize name
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    strategyName = case supervisionStrategy s of
      OneForOne -> "LawSpecOneForOne"
      OneForAll -> "LawSpecOneForAll"
      RestForOne -> "LawSpecRestForOne"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one"
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    lifetimeName l = case l of
      Permanent -> "LawSpecPermanent"
      Transient -> "LawSpecTransient"
      Temporary -> "LawSpecTemporary"

capitalize :: String -> String
capitalize [] = []
capitalize (c:cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn c s = case break (== c) s of
  (x, []) -> [x]
  (x, _:rest) -> x : splitOn c rest
