-- Typed actors for Haskell implementation code (see LawSpec.Actors).
--
-- A unit's actors become the module LawSpecActors.<Unit>. Actor account
-- (handle type AccountActor) gets a record AccountHandlers of its adapters
-- (one field per adapter, on ++ the adapter's name), startAccountActor,
-- account<Handler> per handler (send and wait for the reply),
-- tellAccount<Handler> (send without waiting) and stopAccountActor. The
-- handlers come in as a record rather than by importing the adapter module,
-- so the adapter module itself can use its actors without an import cycle;
-- LawSpecActors.<Unit>.Adapters binds each record to the unit's adapters
-- for every other module.
module LawSpec.Actors.Haskell (emit) where

import Data.Char (isAlphaNum, toUpper)
import Data.List (intercalate, isPrefixOf, nub, sort)
import qualified LawSpec.Core as C
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision)
import LawSpec.Backend (adapterName)
import LawSpec.Common (Artifact(..))
import LawSpec.HaskellData (haskellNativeTypeWithParameters)

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ _ datas actors _ = concat <$> mapM unitModules units
  where
    units = nub [C.idText (C.unitId (actorUnit a)) | a <- actors]
    unitModules unit = do
      let owned = [a | a <- actors, C.idText (C.unitId (actorUnit a)) == unit]
      sources <- mapM (actorSource datas) owned
      let typed = moduleOf unit
          body = concatMap snd sources
          header =
            [ "-- Generated by LawSpec. Do not edit."
            , "-- | Typed actors of unit " ++ unit ++ "."
            , "--"
            , "-- Each actor owns its state and handles one message at a time, in the"
            , "-- order they arrive. Start one with its handlers (your adapters; the"
            , "-- module " ++ typed ++ ".Adapters has them bound), then send it"
            , "-- messages: each handler function waits for the reply, and its tell"
            , "-- form does not."
            , "module " ++ typed
            , "  ( " ++ intercalate "\n  , " (concatMap exports owned) ++ " ) where"
            , ""
            , "import qualified LawSpecRuntime as LS" ] ++ importsFor (concatMap fst sources)
          adapters =
            [ "-- Generated by LawSpec. Do not edit."
            , "-- | The actors of unit " ++ unit ++ " with their handlers bound to its adapters."
            , "module " ++ typed ++ ".Adapters (" ++ intercalate ", " [handlersValue a | a <- owned] ++ ") where"
            , ""
            , "import " ++ typed
            , "import qualified " ++ moduleOf' unit ++ " as Impl" ] ++
            concat
              [ [ ""
                , "-- | Actor " ++ actorName a ++ "'s handlers: the unit's adapters."
                , handlersValue a ++ " :: " ++ handlersType a
                , handlersValue a ++ " = " ++ handlersType a
                , "  { " ++ intercalate "\n  , " [field d ++ " = Impl." ++ adapterName (actorUnit a) (C.declarationId d) | d <- adapters' a] ++ " }" ]
              | a <- owned ]
      pure [ Artifact (path typed) (unlines header ++ body) "generated" "source"
           , Artifact (path (typed ++ ".Adapters")) (unlines adapters) "generated" "source" ]
    path m = "src/" ++ map (\c -> if c == '.' then '/' else c) m ++ ".hs"
    exports a =
      [handlersType a ++ "(..)", actorClass a, "start" ++ actorClass a] ++
      concat [[call a h, tell a h] | h <- actorHandlers a] ++ ["stop" ++ actorClass a]
    importsFor qualifiers =
      [ "import " ++ line | (prefix, line) <- imports, prefix `elem` qualifiers ]
    imports =
      [ ("P.", "qualified Prelude as P"), ("I.", "qualified Data.Int as I")
      , ("W.", "qualified Data.Word as W"), ("T.", "qualified Data.Text as T")
      , ("B.", "qualified Data.ByteString as B"), ("C.", "qualified Data.Complex as C")
      , ("Seq.", "qualified Data.Sequence as Seq"), ("Set.", "qualified Data.Set as Set")
      , ("Map.", "qualified Data.Map.Strict as Map"), ("Data.", "qualified LawSpecData as Data") ]

-- The module of a unit's typed actors, and of its adapters.
moduleOf, moduleOf' :: String -> String
moduleOf unit = "LawSpecActors." ++ moduleOf' unit
moduleOf' unit = intercalate "." (map (concatMap capitalize . splitOn '_') (splitOn '.' unit))

handlersType, handlersValue :: Actor -> String
handlersType a = capitalize (actorName a) ++ "Handlers"
handlersValue a = actorName a ++ "Handlers"

-- The start adapter, then each handler's.
adapters' :: Actor -> [C.Declaration]
adapters' a = actorStart a : map handlerDeclaration (actorHandlers a)

field :: C.Declaration -> String
field d = "on" ++ capitalize (C.declarationName d)

call, tell :: Actor -> Handler -> String
call a h = actorName a ++ capitalize (handlerName h)
tell a h = "tell" ++ capitalize (actorName a) ++ capitalize (handlerName h)

-- One actor's declarations, with the qualifiers its types use.
actorSource :: [C.DataDeclaration] -> Actor -> Either String ([String], String)
actorSource datas a = do
  let native = haskellNativeTypeWithParameters datas [] []
  state <- native (actorState a)
  fields <- mapM (\d -> do
    let (args, result) = C.functionType (C.declarationType d)
    texts <- mapM native args
    r <- native result
    pure (field d ++ " :: " ++ intercalate " -> " (map parenthesize texts ++ [io d (parenthesize r)]))) (adapters' a)
  startArgs <- mapM (\(p, t) -> (,) p <$> native t) (actorStartArguments a)
  handlers <- mapM (handlerSource native) (actorHandlers a)
  let cls = actorClass a
      ty = handlersType a
      params = [(p, t) | ((p, t), (_, ct)) <- zip startArgs (actorStartArguments a), not (unit ct)]
      values = [if unit ct then "()" else p | ((p, _), (_, ct)) <- zip startArgs (actorStartArguments a)]
      start = field (actorStart a) ++ " handlers" ++ concatMap (' ' :) values
      text = unlines $
        [ ""
        , "-- | Actor " ++ actorName a ++ "'s handlers: its start adapter, then one per message."
        , "data " ++ ty ++ " = " ++ ty
        , "  { " ++ intercalate "\n  , " fields ++ " }"
        , ""
        , "-- | A running " ++ actorName a ++ " actor."
        , "data " ++ cls ++ " = " ++ cls ++ " " ++ ty ++ " (LS.Actor " ++ parenthesize state ++ ")"
        , ""
        , "-- | Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor."
        , "start" ++ cls ++ " :: " ++ intercalate " -> " (ty : map (parenthesize . snd) params ++ ["P.IO " ++ cls])
        , "start" ++ cls ++ " handlers" ++ concatMap ((' ' :) . fst) params ++ " = do"
        , "  state <- " ++ (if C.declarationAsync (actorStart a) then start else "P.pure (" ++ start ++ ")")
        , "  " ++ cls ++ " handlers P.<$> LS.newActor state" ] ++
        concatMap (\(h, (argTypes, reply, step)) ->
          let args = map fst (handlerArguments h)
              lhs = " (" ++ cls ++ " handlers actor)" ++ concatMap (' ' :) args
              signature result = intercalate " -> " (cls : map parenthesize argTypes ++ ["P.IO " ++ result])
          in [ ""
             , "-- | Sends " ++ handlerName h ++ " and waits for the reply."
             , call a h ++ " :: " ++ signature (maybe "()" parenthesize reply)
             , call a h ++ lhs ++ " = LS.callActor actor " ++ step
             , ""
             , "-- | Sends " ++ handlerName h ++ " without waiting for the reply."
             , tell a h ++ " :: " ++ signature "()"
             , tell a h ++ lhs ++ " = LS.castActor actor " ++ step ]) (zip (actorHandlers a) handlers) ++
        [ ""
        , "-- | Refuses further messages; those already sent are still handled."
        , "stop" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
        , "stop" ++ cls ++ " (" ++ cls ++ " _ actor) = LS.stopActor actor" ]
  pure (qualifiersOf text, text)
  where
    unit t = t == C.Constructor "Unit" []
    io d r = if C.declarationAsync d then "P.IO " ++ parenthesize r else r
    handlerSource native h = do
      argTypes <- mapM (native . snd) (handlerArguments h)
      reply <- traverse native (handlerReply h)
      let d = handlerDeclaration h
          applied = "(" ++ field d ++ " handlers state" ++ concatMap ((' ' :) . fst) (handlerArguments h) ++ ")"
          split = case handlerReply h of
            Just _ -> "(\\(Data.Pair reply next) -> (reply, next))"
            Nothing -> "(\\next -> ((), next))"
          step = if C.declarationAsync d
            then "(\\state -> P.fmap " ++ split ++ " " ++ applied ++ ")"
            else "(\\state -> P.pure (" ++ split ++ " " ++ applied ++ "))"
      pure (argTypes, reply, step)

-- The module qualifiers a text uses (e.g. "I." in I.Int32).
qualifiersOf :: String -> [String]
qualifiersOf text = sort (nub (go text))
  where
    go [] = []
    go s@(c : rest)
      | c `elem` ['A' .. 'Z'], (name, after) <- span (\x -> isAlphaNum x || x == '.') s =
          prefixes name ++ go after
      | otherwise = go rest
    prefixes name = [ take (i + 1) name | (i, '.') <- zip [0 ..] name, not ("." `isPrefixOf` drop (i + 1) name) ]

parenthesize :: String -> String
parenthesize text
  | ' ' `elem` text && not ("(" `isPrefixOf` text) && not ("[" `isPrefixOf` text) = "(" ++ text ++ ")"
  | otherwise = text

capitalize :: String -> String
capitalize [] = []
capitalize (c : cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn delimiter value = case break (== delimiter) value of
  (a, []) -> [a]
  (a, _ : rest) -> a : splitOn delimiter rest
