-- Typed actors for Haskell implementation code (see LawSpec.Actors).
--
-- A unit's actors become the module LawSpecActors.<Unit>. Actor account
-- (handle type AccountActor) gets a record AccountHandlers of its adapters
-- (one field per adapter, on ++ the adapter's name), startAccountActor,
-- account<Handler> per handler (send and wait for the reply),
-- tellAccount<Handler> (send without waiting), crashAccountActor (for
-- testing restarts) and stopAccountActor; startAccountActorUnder starts it
-- under a runtime supervisor with a lifetime. A supervisor bank becomes
-- BankSupervisor, a record of its children (bankAccount, ...), with
-- startBankSupervisor (taking the handler records of the actors beneath it),
-- startBankSupervisorUnder and stopBankSupervisor. Typed actors and
-- supervisors are instances of LS.Supervisable, LS.Monitorable and (actors)
-- LS.Linkable. The handlers come in as a record rather than by importing
-- the adapter module, so the adapter module itself can use its actors
-- without an import cycle; LawSpecActors.<Unit>.Adapters binds each record
-- to the unit's adapters for every other module.
module LawSpec.Actors.Haskell (emit) where

import Data.Char (isAlphaNum, toLower, toUpper)
import Data.List (intercalate, isPrefixOf, nub, sort)
import qualified LawSpec.Core as C
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))
import LawSpec.Backend (adapterName)
import LawSpec.Common (Artifact(..))
import LawSpec.HaskellData (haskellNativeTypeWithParameters, haskellCodecDoc)
import LawSpec.MachineSpec (describe)
import qualified LawSpec.Code.Doc as D
import Control.Monad (foldM)

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ bits datas actors supervisions = concat <$> mapM unitModules units
  where
    units = nub [C.idText (C.unitId (actorUnit a)) | a <- actors]
    unitModules unit = do
      let owned = [a | a <- actors, C.idText (C.unitId (actorUnit a)) == unit]
          supervisors = [s | s <- supervisions, C.idText (C.unitId (supervisionUnit s)) == unit]
          -- Each actor's messages as wire descriptors, for serving it and
          -- calling it across nodes; an actor whose types have none (or no
          -- codec) stays local.
          wired (table, acc) a = case foldM (handlerWire bits datas) (table, []) (actorHandlers a) of
            Right (table', hs) -> (table', acc ++ [(actorName a, reverse hs)])
            Left _ -> (table, acc)
          (types, wires) = foldl wired ([], []) owned
      sources <- mapM (\a -> actorSource datas (lookup (actorName a) wires) a) owned
      let typed = moduleOf unit
          remoteHelpers = if null wires then "" else unlines
            [ ""
            , "-- Values crossing the network are logical; handlers and callers use"
            , "-- native ones, converted with the data types' codecs."
            , "_lawspecSchema :: Schema.Schema"
            , "_lawspecSchema = P.either P.error P.id DataSchema.schema"
            , ""
            , "_lawspecBits :: P.Int"
            , "_lawspecBits = " ++ show bits
            , ""
            , "_lawspecTypes :: LS.DataTable"
            , "_lawspecTypes = [(LS.descriptorName n, f) | f@(LS.DescList (LS.DescAtom \"data\" : n : _)) <- LS.readDescriptor " ++ show (unwords (map snd (reverse types))) ++ "]"
            , ""
            , "_lawspecDescriptor :: P.String -> LS.Descriptor"
            , "_lawspecDescriptor text = case LS.readDescriptor text of"
            , "  form : _ -> form"
            , "  [] -> P.error \"empty descriptor\"" ]
          body = remoteHelpers ++ concatMap snd sources ++ concatMap (supervisorSource supervisions) supervisors
          header =
            [ "-- Generated by LawSpec. Do not edit."
            , "-- | Typed actors of unit " ++ unit ++ "."
            , "--"
            , "-- Each actor owns its state and handles one message at a time, in the"
            , "-- order they arrive. Start one with its handlers (your adapters; the"
            , "-- module " ++ typed ++ ".Adapters has them bound), then send it"
            , "-- messages: each handler function waits for the reply, and its tell"
            , "-- form does not. A handler that throws crashes the actor: the caller"
            , "-- gets LS.ActorCrashed, and an actor under a supervisor restarts (from"
            , "-- its restart adapter, or its start) while any other stops."
            , "module " ++ typed
            , "  ( " ++ intercalate "\n  , " (concatMap exports owned ++ concatMap supervisorExports supervisors) ++ " ) where"
            , ""
            , "import qualified LawSpecRuntime as LS" ] ++ importsFor (qualifiersOf remoteHelpers ++ concatMap fst sources)
          adapters =
            [ "-- Generated by LawSpec. Do not edit."
            , "-- | The actors of unit " ++ unit ++ " with their handlers bound to its adapters."
            , "module " ++ typed ++ ".Adapters (" ++ intercalate ", " [handlersValue a | a <- owned] ++ ") where"
            , ""
            , "import " ++ typed
            , "import qualified " ++ moduleOf' unit ++ " as Impl" ] ++
            concat
              [ [ ""
                , "-- | Actor " ++ actorName a ++ "'s handlers: the unit's adapters."
                , handlersValue a ++ " :: " ++ handlersType a
                , handlersValue a ++ " = " ++ handlersType a
                , "  { " ++ intercalate "\n  , " [field d ++ " = Impl." ++ adapterName (actorUnit a) (C.declarationId d) | d <- adapters' a] ++ " }" ]
              | a <- owned ]
      pure [ Artifact (path typed) (unlines header ++ body) "generated" "source"
           , Artifact (path (typed ++ ".Adapters")) (unlines adapters) "generated" "source" ]
    path m = "src/" ++ map (\c -> if c == '.' then '/' else c) m ++ ".hs"
    exports a =
      [handlersType a ++ "(..)", actorClass a, "start" ++ actorClass a, "start" ++ actorClass a ++ "Under"] ++
      concat [[call a h, tell a h] | h <- actorHandlers a] ++ ["crash" ++ actorClass a, "stop" ++ actorClass a] ++
      (case lookup (actorName a) wiresAll of
         Just _ -> ["serve" ++ actorClass a, actorClass a ++ "Remote", "connect" ++ actorClass a] ++
           ["remote" ++ capitalize (call a h) | h <- actorHandlers a]
         Nothing -> [])
    wiresAll = snd (foldl (\(table, acc) a -> case foldM (handlerWire bits datas) (table, []) (actorHandlers a) of
      Right (table', hs) -> (table', acc ++ [(actorName a, hs)])
      Left _ -> (table, acc)) ([], []) actors)
    supervisorExports s = [supervisionClass s ++ "(..)", "start" ++ supervisionClass s, "start" ++ supervisionClass s ++ "Under", "stop" ++ supervisionClass s]
    importsFor qualifiers =
      [ "import " ++ line | (prefix, line) <- imports, prefix `elem` qualifiers ]
    imports =
      [ ("P.", "qualified Prelude as P"), ("I.", "qualified Data.Int as I")
      , ("W.", "qualified Data.Word as W"), ("T.", "qualified Data.Text as T")
      , ("B.", "qualified Data.ByteString as B"), ("C.", "qualified Data.Complex as C")
      , ("Seq.", "qualified Data.Sequence as Seq"), ("Set.", "qualified Data.Set as Set")
      , ("Map.", "qualified Data.Map.Strict as Map"), ("Data.", "qualified LawSpecData as Data")
      , ("E.", "qualified Control.Exception as E"), ("Schema.", "qualified LawSpecSchema as Schema")
      , ("Codec.", "qualified LawSpecCodecs as Codec"), ("Codecs.", "qualified LawSpecDataCodecs as Codecs")
      , ("DataSchema.", "qualified LawSpecDataSchema as DataSchema")
      , ("Collections.", "qualified LawSpecCollectionCodecs as Collections") ]

-- The module of a unit's typed actors, and of its adapters.
moduleOf, moduleOf' :: String -> String
moduleOf unit = "LawSpecActors." ++ moduleOf' unit
moduleOf' unit = intercalate "." (map (concatMap capitalize . splitOn '_') (splitOn '.' unit))

handlersType, handlersValue :: Actor -> String
handlersType a = capitalize (actorName a) ++ "Handlers"
handlersValue a = actorName a ++ "Handlers"

-- The start adapter, then each handler's, then the restart adapter's.
adapters' :: Actor -> [C.Declaration]
adapters' a = actorStart a : map handlerDeclaration (actorHandlers a) ++ maybe [] pure (actorRestart a)

field :: C.Declaration -> String
field d = "on" ++ capitalize (C.declarationName d)

call, tell :: Actor -> Handler -> String
call a h = actorName a ++ capitalize (handlerName h)
tell a h = "tell" ++ capitalize (actorName a) ++ capitalize (handlerName h)

-- A handler's argument and reply descriptors (adding data types to the
-- table) and the codecs of its argument and reply types.
type HandlerWire = (Handler, [String], String, [String], String)

handlerWire :: Int -> [C.DataDeclaration] -> ([(String, String)], [HandlerWire]) -> Handler -> Either String ([(String, String)], [HandlerWire])
handlerWire bits datas (table, acc) h = do
  let replyType = maybe (C.Constructor "Unit" []) id (handlerReply h)
      codec ty = D.render (D.Pretty 10000) <$> haskellCodecDoc datas "_lawspecSchema" "_lawspecBits" ty
  (args, table') <- foldM (\(xs, t) (_, ty) -> (\(x, t') -> (xs ++ [x], t')) <$> describe bits datas t ty) ([], table) (handlerArguments h)
  (reply, table'') <- describe bits datas table' replyType
  argCodecs <- mapM (codec . snd) (handlerArguments h)
  replyCodec <- codec replyType
  pure (table'', (h, args, reply, argCodecs, replyCodec) : acc)

-- One actor's declarations, with the qualifiers its types use.
actorSource :: [C.DataDeclaration] -> Maybe [HandlerWire] -> Actor -> Either String ([String], String)
actorSource datas wire a = do
  let native = haskellNativeTypeWithParameters datas [] []
  state <- native (actorState a)
  fields <- mapM (\d -> do
    let (args, result) = C.functionType (C.declarationType d)
    texts <- mapM native args
    r <- native result
    pure (field d ++ " :: " ++ intercalate " -> " (map parenthesize texts ++ [io d (parenthesize r)]))) (adapters' a)
  startArgs <- mapM (\(p, t) -> (,) p <$> native t) (actorStartArguments a)
  handlers <- mapM (handlerSource native) (actorHandlers a)
  let cls = actorClass a
      ty = handlersType a
      params = [(p, t) | ((p, t), (_, ct)) <- zip startArgs (actorStartArguments a), not (unit ct)]
      values = [if unit ct then "()" else p | ((p, _), (_, ct)) <- zip startArgs (actorStartArguments a)]
      start = field (actorStart a) ++ " handlers" ++ concatMap (' ' :) values
      starting = if C.declarationAsync (actorStart a) then start else "P.pure (" ++ start ++ ")"
      restart = case actorRestart a of
        Just d | C.declarationAsync d -> "(\\previous -> " ++ field d ++ " handlers previous)"
        Just d -> "(\\previous -> P.pure (" ++ field d ++ " handlers previous))"
        Nothing -> "(\\_ -> " ++ starting ++ ")"
      startSignature extra = intercalate " -> " (extra ++ ty : map (parenthesize . snd) params ++ ["P.IO " ++ cls])
      text = unlines $
        [ ""
        , "-- | Actor " ++ actorName a ++ "'s handlers: its start adapter, then one per message."
        , "data " ++ ty ++ " = " ++ ty
        , "  { " ++ intercalate "\n  , " fields ++ " }"
        , ""
        , "-- | A running " ++ actorName a ++ " actor."
        , "data " ++ cls ++ " = " ++ cls ++ " " ++ ty ++ " (LS.Actor " ++ parenthesize state ++ ")"
        , ""
        , "-- | Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor."
        , "-- After a crash under a supervisor, it restarts " ++ maybe "from its start" (\d -> "from " ++ C.declarationName d) (actorRestart a) ++ "."
        , "start" ++ cls ++ " :: " ++ startSignature []
        , "start" ++ cls ++ " handlers" ++ concatMap ((' ' :) . fst) params ++ " = do"
        , "  state <- " ++ starting
        , "  " ++ cls ++ " handlers P.<$> LS.newRestartableActor " ++ restart ++ " state"
        , ""
        , "-- | Starts the actor under a supervisor, with a lifetime."
        , "start" ++ cls ++ "Under :: " ++ startSignature ["LS.Supervisor", "LS.Lifetime"]
        , "start" ++ cls ++ "Under supervisor lifetime handlers" ++ concatMap ((' ' :) . fst) params ++ " = do"
        , "  started@(" ++ cls ++ " _ actor) <- start" ++ cls ++ " handlers" ++ concatMap ((' ' :) . fst) params
        , "  LS.superviseActor supervisor actor lifetime"
        , "  P.pure started"
        , ""
        , "instance LS.Supervisable " ++ cls ++ " where"
        , "  asChild (" ++ cls ++ " _ actor) = LS.asChild actor"
        , ""
        , "instance LS.Linkable " ++ cls ++ " where"
        , "  linkPoint (" ++ cls ++ " _ actor) = LS.linkPoint actor"
        , ""
        , "instance LS.Monitorable " ++ cls ++ " where"
        , "  monitor (" ++ cls ++ " _ actor) = LS.monitor actor" ] ++
        concatMap (\(h, (argTypes, reply, step)) ->
          let args = map fst (handlerArguments h)
              lhs = " (" ++ cls ++ " handlers actor)" ++ concatMap (' ' :) args
              signature result = intercalate " -> " (cls : map parenthesize argTypes ++ ["P.IO " ++ result])
          in [ ""
             , "-- | Sends " ++ handlerName h ++ " and waits for the reply."
             , call a h ++ " :: " ++ signature (maybe "()" parenthesize reply)
             , call a h ++ lhs ++ " = LS.callActor actor " ++ step
             , ""
             , "-- | Sends " ++ handlerName h ++ " without waiting for the reply."
             , tell a h ++ " :: " ++ signature "()"
             , tell a h ++ lhs ++ " = LS.castActor actor " ++ step ]) (zip (actorHandlers a) handlers) ++
        [ ""
        , "-- | Crashes the actor as a failing handler would, after the messages"
        , "-- already sent: for testing how it restarts."
        , "crash" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
        , "crash" ++ cls ++ " (" ++ cls ++ " _ actor) = LS.crashActor actor \"crashed on purpose\""
        , ""
        , "-- | Refuses further messages; those already sent are still handled. A"
        , "-- permanent child of a supervisor restarts instead."
        , "stop" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
        , "stop" ++ cls ++ " (" ++ cls ++ " _ actor) = LS.stopActor actor" ] ++ remote
      steps = zip (actorHandlers a) handlers
      descriptor x = "_lawspecDescriptor " ++ show x
      remote = case wire of
        Nothing -> []
        Just hs ->
          [ ""
          , "-- | Lets other nodes call this actor at <node address>/name; returns"
          , "-- that address."
          , "serve" ++ cls ++ " :: LS.Node -> P.String -> " ++ cls ++ " -> P.IO P.String"
          , "serve" ++ cls ++ " node name (" ++ cls ++ " handlers actor) = LS.serveActor node name actor _lawspecTypes" ] ++
          zipWith (\i (h, ds, r, argCodecs, replyCodec) ->
            let args = map fst (handlerArguments h)
                wireArgs = ["argument" ++ show k | k <- [0 .. length args - 1]]
                step = maybe "" (\(_, (_, _, s)) -> s) (lookup (handlerName h) [(handlerName x, (x, y)) | (x, y) <- steps])
            in (if i == (0 :: Int) then "  [ " else "  , ") ++ "(" ++ show (handlerName h) ++ ", [" ++ intercalate ", " (map descriptor ds) ++ "], " ++
                 descriptor r ++ ", \\state arguments -> case arguments of\n      [" ++ intercalate ", " wireArgs ++ "] -> do\n" ++
                 concat ["        " ++ v ++ " <- LS.orWire (Codec.decode (" ++ c ++ ") " ++ w ++ ")\n" | (v, w, c) <- zip3 args wireArgs argCodecs] ++
                 "        (reply, next) <- " ++ step ++ " state\n" ++
                 "        encoded <- LS.orWire (Codec.encode (" ++ replyCodec ++ ") reply)\n" ++
                 "        P.pure (encoded, next)\n" ++
                 "      _ -> E.throwIO (E.ErrorCall \"wrong number of arguments\"))") [0 ..] hs ++
          [ if null hs then "  []" else "  ]"
          , ""
          , "-- | Actor " ++ actorName a ++ " on another node."
          , "newtype " ++ cls ++ "Remote = " ++ cls ++ "Remote LS.RemoteActor"
          , ""
          , "-- | The actor served at an address on another node; each call waits up"
          , "-- to 5 seconds, then throws LS.Unreachable."
          , "connect" ++ cls ++ " :: LS.Node -> P.String -> " ++ cls ++ "Remote"
          , "connect" ++ cls ++ " node address = " ++ cls ++ "Remote (LS.remoteActor node address _lawspecTypes"
          , "  [" ++ intercalate ", " ["(" ++ show (handlerName h) ++ ", ([" ++ intercalate ", " (map descriptor ds) ++ "], " ++ descriptor r ++ "))" | (h, ds, r, _, _) <- hs] ++ "] 5)" ] ++
          concat
          [ let args = map fst (handlerArguments h)
                name = "remote" ++ capitalize (call a h)
                argTypes = maybe [] (\(t, _, _) -> t) (lookup (handlerName h) [(handlerName x, y) | (x, y) <- steps])
                replyText = maybe "()" (\(_, rr, _) -> maybe "()" parenthesize rr) (lookup (handlerName h) [(handlerName x, y) | (x, y) <- steps])
            in [ ""
               , "-- | Sends " ++ handlerName h ++ " to the remote actor and waits for the reply."
               , name ++ " :: " ++ intercalate " -> " ((cls ++ "Remote") : map parenthesize argTypes ++ ["P.IO " ++ replyText])
               , name ++ " (" ++ cls ++ "Remote remote)" ++ concatMap (' ' :) args ++ " = do" ] ++
               [ "  " ++ v ++ "' <- LS.orWire (Codec.encode (" ++ c ++ ") " ++ v ++ ")" | (v, c) <- zip args argCodecs ] ++
               [ "  reply <- LS.callRemote remote " ++ show (handlerName h) ++ " [" ++ intercalate ", " [v ++ "'" | v <- args] ++ "]"
               , "  LS.orWire (Codec.decode (" ++ replyCodec ++ ") reply)" ]
          | (h, _, _, argCodecs, replyCodec) <- hs ]
  pure (qualifiersOf text, text)
  where
    unit t = t == C.Constructor "Unit" []
    io d r = if C.declarationAsync d then "P.IO " ++ parenthesize r else r
    handlerSource native h = do
      argTypes <- mapM (native . snd) (handlerArguments h)
      reply <- traverse native (handlerReply h)
      let d = handlerDeclaration h
          applied = "(" ++ field d ++ " handlers state" ++ concatMap ((' ' :) . fst) (handlerArguments h) ++ ")"
          split = case handlerReply h of
            Just _ -> "(\\(Data.Pair reply next) -> (reply, next))"
            Nothing -> "(\\next -> ((), next))"
          step = if C.declarationAsync d
            then "(\\state -> P.fmap " ++ split ++ " " ++ applied ++ ")"
            else "(\\state -> P.pure (" ++ split ++ " " ++ applied ++ "))"
      pure (argTypes, reply, step)

-- The actors beneath a supervisor, in start order, each once.
actorsBeneath :: [Supervision] -> Supervision -> [Actor]
actorsBeneath all' s = nubBy' actorClass (concatMap child (supervisionChildren s))
  where
    child (_, _, ActorChild a) = [a]
    child (_, _, SupervisorChild cls) = concat [actorsBeneath all' t | t <- all', supervisionClass t == cls]
    nubBy' key = foldr (\x acc -> x : filter ((/= key x) . key) acc) []

-- A supervisor's record of children, its start functions and stop.
supervisorSource :: [Supervision] -> Supervision -> String
supervisorSource all' s = unlines $
  [ ""
  , "-- | Supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++ show (supervisionRestarts s)
      ++ " restarts in " ++ show (supervisionPeriod s) ++ " microseconds."
  , "data " ++ cls ++ " = " ++ cls
  , "  { " ++ intercalate "\n  , " ((supervisorField ++ " :: LS.Supervisor") :
      [childField name ++ " :: " ++ childClass c | (_, name, c) <- supervisionChildren s]) ++ " }"
  , ""
  , "-- | Starts the supervisor and its children, in order."
  , "start" ++ cls ++ " :: " ++ intercalate " -> " (map handlersType beneath ++ ["P.IO " ++ cls])
  , "start" ++ cls ++ concatMap ((' ' :) . handlersValue) beneath ++ " = do"
  , "  own <- LS.newSupervisor LS." ++ strategyName ++ " " ++ show (supervisionRestarts s) ++ " " ++ show (supervisionPeriod s) ] ++
  [ "  " ++ childVar name ++ " <- " ++ startChild l c | (l, name, c) <- supervisionChildren s ] ++
  [ "  P.pure (" ++ cls ++ " own" ++ concatMap (\(_, name, _) -> ' ' : childVar name) (supervisionChildren s) ++ ")"
  , ""
  , "-- | Starts the supervisor under another, with a lifetime."
  , "start" ++ cls ++ "Under :: " ++ intercalate " -> " (["LS.Supervisor", "LS.Lifetime"] ++ map handlersType beneath ++ ["P.IO " ++ cls])
  , "start" ++ cls ++ "Under supervisor lifetime" ++ concatMap ((' ' :) . handlersValue) beneath ++ " = do"
  , "  started <- start" ++ cls ++ concatMap ((' ' :) . handlersValue) beneath
  , "  LS.superviseSupervisor supervisor (" ++ supervisorField ++ " started) lifetime"
  , "  P.pure started"
  , ""
  , "-- | Stops every child, last started first, without restarting them."
  , "stop" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
  , "stop" ++ cls ++ " = LS.stopSupervisor P.. " ++ supervisorField
  , ""
  , "instance LS.Supervisable " ++ cls ++ " where"
  , "  asChild = LS.asChild P.. " ++ supervisorField
  , ""
  , "instance LS.Monitorable " ++ cls ++ " where"
  , "  monitor = LS.monitor P.. " ++ supervisorField ]
  where
    cls = supervisionClass s
    beneath = actorsBeneath all' s
    supervisorField = uncapital cls
    childField name = supervisionName s ++ capitalize name
    childVar name = "child" ++ capitalize name
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    startChild l c = case c of
      ActorChild a -> "start" ++ actorClass a ++ "Under own LS." ++ lifetimeName l ++ " " ++ handlersValue a
      SupervisorChild n -> "start" ++ n ++ "Under own LS." ++ lifetimeName l ++
        concat [' ' : handlersValue a | t <- all', supervisionClass t == n, a <- actorsBeneath all' t]
    lifetimeName l = case l of
      Permanent -> "Permanent"
      Transient -> "Transient"
      Temporary -> "Temporary"
    strategyName = case supervisionStrategy s of
      OneForOne -> "OneForOne"
      OneForAll -> "OneForAll"
      RestForOne -> "RestForOne"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one"
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    uncapital n = case n of
      c : cs -> toLower c : cs
      [] -> []

-- The module qualifiers a text uses (e.g. "I." in I.Int32).
qualifiersOf :: String -> [String]
qualifiersOf text = sort (nub (go text))
  where
    go [] = []
    go s@(c : rest)
      | c `elem` ['A' .. 'Z'], (name, after) <- span (\x -> isAlphaNum x || x == '.') s =
          prefixes name ++ go after
      | otherwise = go rest
    prefixes name = [ take (i + 1) name | (i, '.') <- zip [0 ..] name, not ("." `isPrefixOf` drop (i + 1) name) ]

parenthesize :: String -> String
parenthesize text
  | ' ' `elem` text && not ("(" `isPrefixOf` text) && not ("[" `isPrefixOf` text) = "(" ++ text ++ ")"
  | otherwise = text

capitalize :: String -> String
capitalize [] = []
capitalize (c : cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn delimiter value = case break (== delimiter) value of
  (a, []) -> [a]
  (a, _ : rest) -> a : splitOn delimiter rest
