-- Typed actors for Haskell implementation code (see LawSpec.Actors).
--
-- A unit's actors become the module LawSpecActors.<Unit>. Actor account
-- (handle type AccountActor) gets a record AccountHandlers of its adapters
-- (one field per adapter, on ++ the adapter's name), startAccountActor,
-- account<Handler> per handler (send and wait for the reply),
-- tellAccount<Handler> (send without waiting), crashAccountActor (for
-- testing restarts) and stopAccountActor; startAccountActorUnder starts it
-- under a runtime supervisor with a lifetime. A supervisor bank becomes
-- BankSupervisor, a record of its children (bankAccount, ...), with
-- startBankSupervisor (taking the handler records of the actors beneath it),
-- startBankSupervisorUnder and stopBankSupervisor. Typed actors and
-- supervisors are instances of LS.Supervisable, LS.Monitorable and (actors)
-- LS.Linkable. The handlers come in as a record rather than by importing
-- the adapter module, so the adapter module itself can use its actors
-- without an import cycle; LawSpecActors.<Unit>.Adapters binds each record
-- to the unit's adapters for every other module.
module LawSpec.Actors.Haskell (emit) where

import Data.Char (isAlphaNum, toLower, toUpper)
import Data.List (intercalate, isPrefixOf, nub, sort)
import qualified LawSpec.Core as C
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))
import LawSpec.Backend (adapterName)
import LawSpec.Common (Artifact(..))
import LawSpec.HaskellData (haskellNativeTypeWithParameters)

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ _ datas actors supervisions = concat <$> mapM unitModules units
  where
    units = nub [C.idText (C.unitId (actorUnit a)) | a <- actors]
    unitModules unit = do
      let owned = [a | a <- actors, C.idText (C.unitId (actorUnit a)) == unit]
          supervisors = [s | s <- supervisions, C.idText (C.unitId (supervisionUnit s)) == unit]
      sources <- mapM (actorSource datas) owned
      let typed = moduleOf unit
          body = concatMap snd sources ++ concatMap (supervisorSource supervisions) supervisors
          header =
            [ "-- Generated by LawSpec. Do not edit."
            , "-- | Typed actors of unit " ++ unit ++ "."
            , "--"
            , "-- Each actor owns its state and handles one message at a time, in the"
            , "-- order they arrive. Start one with its handlers (your adapters; the"
            , "-- module " ++ typed ++ ".Adapters has them bound), then send it"
            , "-- messages: each handler function waits for the reply, and its tell"
            , "-- form does not. A handler that throws crashes the actor: the caller"
            , "-- gets LS.ActorCrashed, and an actor under a supervisor restarts (from"
            , "-- its restart adapter, or its start) while any other stops."
            , "module " ++ typed
            , "  ( " ++ intercalate "\n  , " (concatMap exports owned ++ concatMap supervisorExports supervisors) ++ " ) where"
            , ""
            , "import qualified LawSpecRuntime as LS" ] ++ importsFor (concatMap fst sources)
          adapters =
            [ "-- Generated by LawSpec. Do not edit."
            , "-- | The actors of unit " ++ unit ++ " with their handlers bound to its adapters."
            , "module " ++ typed ++ ".Adapters (" ++ intercalate ", " [handlersValue a | a <- owned] ++ ") where"
            , ""
            , "import " ++ typed
            , "import qualified " ++ moduleOf' unit ++ " as Impl" ] ++
            concat
              [ [ ""
                , "-- | Actor " ++ actorName a ++ "'s handlers: the unit's adapters."
                , handlersValue a ++ " :: " ++ handlersType a
                , handlersValue a ++ " = " ++ handlersType a
                , "  { " ++ intercalate "\n  , " [field d ++ " = Impl." ++ adapterName (actorUnit a) (C.declarationId d) | d <- adapters' a] ++ " }" ]
              | a <- owned ]
      pure [ Artifact (path typed) (unlines header ++ body) "generated" "source"
           , Artifact (path (typed ++ ".Adapters")) (unlines adapters) "generated" "source" ]
    path m = "src/" ++ map (\c -> if c == '.' then '/' else c) m ++ ".hs"
    exports a =
      [handlersType a ++ "(..)", actorClass a, "start" ++ actorClass a, "start" ++ actorClass a ++ "Under"] ++
      concat [[call a h, tell a h] | h <- actorHandlers a] ++ ["crash" ++ actorClass a, "stop" ++ actorClass a]
    supervisorExports s = [supervisionClass s ++ "(..)", "start" ++ supervisionClass s, "start" ++ supervisionClass s ++ "Under", "stop" ++ supervisionClass s]
    importsFor qualifiers =
      [ "import " ++ line | (prefix, line) <- imports, prefix `elem` qualifiers ]
    imports =
      [ ("P.", "qualified Prelude as P"), ("I.", "qualified Data.Int as I")
      , ("W.", "qualified Data.Word as W"), ("T.", "qualified Data.Text as T")
      , ("B.", "qualified Data.ByteString as B"), ("C.", "qualified Data.Complex as C")
      , ("Seq.", "qualified Data.Sequence as Seq"), ("Set.", "qualified Data.Set as Set")
      , ("Map.", "qualified Data.Map.Strict as Map"), ("Data.", "qualified LawSpecData as Data") ]

-- The module of a unit's typed actors, and of its adapters.
moduleOf, moduleOf' :: String -> String
moduleOf unit = "LawSpecActors." ++ moduleOf' unit
moduleOf' unit = intercalate "." (map (concatMap capitalize . splitOn '_') (splitOn '.' unit))

handlersType, handlersValue :: Actor -> String
handlersType a = capitalize (actorName a) ++ "Handlers"
handlersValue a = actorName a ++ "Handlers"

-- The start adapter, then each handler's, then the restart adapter's.
adapters' :: Actor -> [C.Declaration]
adapters' a = actorStart a : map handlerDeclaration (actorHandlers a) ++ maybe [] pure (actorRestart a)

field :: C.Declaration -> String
field d = "on" ++ capitalize (C.declarationName d)

call, tell :: Actor -> Handler -> String
call a h = actorName a ++ capitalize (handlerName h)
tell a h = "tell" ++ capitalize (actorName a) ++ capitalize (handlerName h)

-- One actor's declarations, with the qualifiers its types use.
actorSource :: [C.DataDeclaration] -> Actor -> Either String ([String], String)
actorSource datas a = do
  let native = haskellNativeTypeWithParameters datas [] []
  state <- native (actorState a)
  fields <- mapM (\d -> do
    let (args, result) = C.functionType (C.declarationType d)
    texts <- mapM native args
    r <- native result
    pure (field d ++ " :: " ++ intercalate " -> " (map parenthesize texts ++ [io d (parenthesize r)]))) (adapters' a)
  startArgs <- mapM (\(p, t) -> (,) p <$> native t) (actorStartArguments a)
  handlers <- mapM (handlerSource native) (actorHandlers a)
  let cls = actorClass a
      ty = handlersType a
      params = [(p, t) | ((p, t), (_, ct)) <- zip startArgs (actorStartArguments a), not (unit ct)]
      values = [if unit ct then "()" else p | ((p, _), (_, ct)) <- zip startArgs (actorStartArguments a)]
      start = field (actorStart a) ++ " handlers" ++ concatMap (' ' :) values
      starting = if C.declarationAsync (actorStart a) then start else "P.pure (" ++ start ++ ")"
      restart = case actorRestart a of
        Just d | C.declarationAsync d -> "(\\previous -> " ++ field d ++ " handlers previous)"
        Just d -> "(\\previous -> P.pure (" ++ field d ++ " handlers previous))"
        Nothing -> "(\\_ -> " ++ starting ++ ")"
      startSignature extra = intercalate " -> " (extra ++ ty : map (parenthesize . snd) params ++ ["P.IO " ++ cls])
      text = unlines $
        [ ""
        , "-- | Actor " ++ actorName a ++ "'s handlers: its start adapter, then one per message."
        , "data " ++ ty ++ " = " ++ ty
        , "  { " ++ intercalate "\n  , " fields ++ " }"
        , ""
        , "-- | A running " ++ actorName a ++ " actor."
        , "data " ++ cls ++ " = " ++ cls ++ " " ++ ty ++ " (LS.Actor " ++ parenthesize state ++ ")"
        , ""
        , "-- | Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor."
        , "-- After a crash under a supervisor, it restarts " ++ maybe "from its start" (\d -> "from " ++ C.declarationName d) (actorRestart a) ++ "."
        , "start" ++ cls ++ " :: " ++ startSignature []
        , "start" ++ cls ++ " handlers" ++ concatMap ((' ' :) . fst) params ++ " = do"
        , "  state <- " ++ starting
        , "  " ++ cls ++ " handlers P.<$> LS.newRestartableActor " ++ restart ++ " state"
        , ""
        , "-- | Starts the actor under a supervisor, with a lifetime."
        , "start" ++ cls ++ "Under :: " ++ startSignature ["LS.Supervisor", "LS.Lifetime"]
        , "start" ++ cls ++ "Under supervisor lifetime handlers" ++ concatMap ((' ' :) . fst) params ++ " = do"
        , "  started@(" ++ cls ++ " _ actor) <- start" ++ cls ++ " handlers" ++ concatMap ((' ' :) . fst) params
        , "  LS.superviseActor supervisor actor lifetime"
        , "  P.pure started"
        , ""
        , "instance LS.Supervisable " ++ cls ++ " where"
        , "  asChild (" ++ cls ++ " _ actor) = LS.asChild actor"
        , ""
        , "instance LS.Linkable " ++ cls ++ " where"
        , "  linkPoint (" ++ cls ++ " _ actor) = LS.linkPoint actor"
        , ""
        , "instance LS.Monitorable " ++ cls ++ " where"
        , "  monitor (" ++ cls ++ " _ actor) = LS.monitor actor" ] ++
        concatMap (\(h, (argTypes, reply, step)) ->
          let args = map fst (handlerArguments h)
              lhs = " (" ++ cls ++ " handlers actor)" ++ concatMap (' ' :) args
              signature result = intercalate " -> " (cls : map parenthesize argTypes ++ ["P.IO " ++ result])
          in [ ""
             , "-- | Sends " ++ handlerName h ++ " and waits for the reply."
             , call a h ++ " :: " ++ signature (maybe "()" parenthesize reply)
             , call a h ++ lhs ++ " = LS.callActor actor " ++ step
             , ""
             , "-- | Sends " ++ handlerName h ++ " without waiting for the reply."
             , tell a h ++ " :: " ++ signature "()"
             , tell a h ++ lhs ++ " = LS.castActor actor " ++ step ]) (zip (actorHandlers a) handlers) ++
        [ ""
        , "-- | Crashes the actor as a failing handler would, after the messages"
        , "-- already sent: for testing how it restarts."
        , "crash" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
        , "crash" ++ cls ++ " (" ++ cls ++ " _ actor) = LS.crashActor actor \"crashed on purpose\""
        , ""
        , "-- | Refuses further messages; those already sent are still handled. A"
        , "-- permanent child of a supervisor restarts instead."
        , "stop" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
        , "stop" ++ cls ++ " (" ++ cls ++ " _ actor) = LS.stopActor actor" ]
  pure (qualifiersOf text, text)
  where
    unit t = t == C.Constructor "Unit" []
    io d r = if C.declarationAsync d then "P.IO " ++ parenthesize r else r
    handlerSource native h = do
      argTypes <- mapM (native . snd) (handlerArguments h)
      reply <- traverse native (handlerReply h)
      let d = handlerDeclaration h
          applied = "(" ++ field d ++ " handlers state" ++ concatMap ((' ' :) . fst) (handlerArguments h) ++ ")"
          split = case handlerReply h of
            Just _ -> "(\\(Data.Pair reply next) -> (reply, next))"
            Nothing -> "(\\next -> ((), next))"
          step = if C.declarationAsync d
            then "(\\state -> P.fmap " ++ split ++ " " ++ applied ++ ")"
            else "(\\state -> P.pure (" ++ split ++ " " ++ applied ++ "))"
      pure (argTypes, reply, step)

-- The actors beneath a supervisor, in start order, each once.
actorsBeneath :: [Supervision] -> Supervision -> [Actor]
actorsBeneath all' s = nubBy' actorClass (concatMap child (supervisionChildren s))
  where
    child (_, _, ActorChild a) = [a]
    child (_, _, SupervisorChild cls) = concat [actorsBeneath all' t | t <- all', supervisionClass t == cls]
    nubBy' key = foldr (\x acc -> x : filter ((/= key x) . key) acc) []

-- A supervisor's record of children, its start functions and stop.
supervisorSource :: [Supervision] -> Supervision -> String
supervisorSource all' s = unlines $
  [ ""
  , "-- | Supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++ show (supervisionRestarts s)
      ++ " restarts in " ++ show (supervisionPeriod s) ++ " microseconds."
  , "data " ++ cls ++ " = " ++ cls
  , "  { " ++ intercalate "\n  , " ((supervisorField ++ " :: LS.Supervisor") :
      [childField name ++ " :: " ++ childClass c | (_, name, c) <- supervisionChildren s]) ++ " }"
  , ""
  , "-- | Starts the supervisor and its children, in order."
  , "start" ++ cls ++ " :: " ++ intercalate " -> " (map handlersType beneath ++ ["P.IO " ++ cls])
  , "start" ++ cls ++ concatMap ((' ' :) . handlersValue) beneath ++ " = do"
  , "  own <- LS.newSupervisor LS." ++ strategyName ++ " " ++ show (supervisionRestarts s) ++ " " ++ show (supervisionPeriod s) ] ++
  [ "  " ++ childVar name ++ " <- " ++ startChild l c | (l, name, c) <- supervisionChildren s ] ++
  [ "  P.pure (" ++ cls ++ " own" ++ concatMap (\(_, name, _) -> ' ' : childVar name) (supervisionChildren s) ++ ")"
  , ""
  , "-- | Starts the supervisor under another, with a lifetime."
  , "start" ++ cls ++ "Under :: " ++ intercalate " -> " (["LS.Supervisor", "LS.Lifetime"] ++ map handlersType beneath ++ ["P.IO " ++ cls])
  , "start" ++ cls ++ "Under supervisor lifetime" ++ concatMap ((' ' :) . handlersValue) beneath ++ " = do"
  , "  started <- start" ++ cls ++ concatMap ((' ' :) . handlersValue) beneath
  , "  LS.superviseSupervisor supervisor (" ++ supervisorField ++ " started) lifetime"
  , "  P.pure started"
  , ""
  , "-- | Stops every child, last started first, without restarting them."
  , "stop" ++ cls ++ " :: " ++ cls ++ " -> P.IO ()"
  , "stop" ++ cls ++ " = LS.stopSupervisor P.. " ++ supervisorField
  , ""
  , "instance LS.Supervisable " ++ cls ++ " where"
  , "  asChild = LS.asChild P.. " ++ supervisorField
  , ""
  , "instance LS.Monitorable " ++ cls ++ " where"
  , "  monitor = LS.monitor P.. " ++ supervisorField ]
  where
    cls = supervisionClass s
    beneath = actorsBeneath all' s
    supervisorField = uncapital cls
    childField name = supervisionName s ++ capitalize name
    childVar name = "child" ++ capitalize name
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    startChild l c = case c of
      ActorChild a -> "start" ++ actorClass a ++ "Under own LS." ++ lifetimeName l ++ " " ++ handlersValue a
      SupervisorChild n -> "start" ++ n ++ "Under own LS." ++ lifetimeName l ++
        concat [' ' : handlersValue a | t <- all', supervisionClass t == n, a <- actorsBeneath all' t]
    lifetimeName l = case l of
      Permanent -> "Permanent"
      Transient -> "Transient"
      Temporary -> "Temporary"
    strategyName = case supervisionStrategy s of
      OneForOne -> "OneForOne"
      OneForAll -> "OneForAll"
      RestForOne -> "RestForOne"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one"
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    uncapital n = case n of
      c : cs -> toLower c : cs
      [] -> []

-- The module qualifiers a text uses (e.g. "I." in I.Int32).
qualifiersOf :: String -> [String]
qualifiersOf text = sort (nub (go text))
  where
    go [] = []
    go s@(c : rest)
      | c `elem` ['A' .. 'Z'], (name, after) <- span (\x -> isAlphaNum x || x == '.') s =
          prefixes name ++ go after
      | otherwise = go rest
    prefixes name = [ take (i + 1) name | (i, '.') <- zip [0 ..] name, not ("." `isPrefixOf` drop (i + 1) name) ]

parenthesize :: String -> String
parenthesize text
  | ' ' `elem` text && not ("(" `isPrefixOf` text) && not ("[" `isPrefixOf` text) = "(" ++ text ++ ")"
  | otherwise = text

capitalize :: String -> String
capitalize [] = []
capitalize (c : cs) = toUpper c : cs

splitOn :: Char -> String -> [String]
splitOn delimiter value = case break (== delimiter) value of
  (a, []) -> [a]
  (a, _ : rest) -> a : splitOn delimiter rest
