-- Typed actors for Java and Kotlin implementation code (see LawSpec.Actors).
--
-- Every actor becomes a class lawspec.actors.<Handle> (AccountActor): Java
-- source for Java projects, Kotlin source for Kotlin projects, since each
-- calls the user's adapters natively (a Kotlin adapter object, possibly with
-- suspend handlers). start(...) makes the state with the start adapter and
-- runs it in a LawSpecRuntime.Actor; each handler is a method that sends its
-- message and returns the reply, tell<Handler> sends it without waiting, and
-- stop() refuses further messages.
module LawSpec.Actors.Jvm (emit) where

import Data.Char (toUpper)
import Data.List (intercalate, stripPrefix)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (adapterName, unitName)
import LawSpec.JavaData (javaDataType, identifier)
import LawSpec.KotlinData (kotlinDataType)
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit target _ _ datas actors supervisions = (++) <$> mapM artifact actors <*> mapM supervisorArtifact supervisions
  where
    kotlin = target == "kotlin"
    directory = if kotlin then "src/main/kotlin/lawspec/actors/" else "src/main/java/lawspec/actors/"
    extension = if kotlin then ".kt" else ".java"
    artifact a = do
      identifier (actorClass a)
      mapM_ (reserved a) (actorHandlers a)
      source <- (if kotlin then kotlinSource else javaSource) datas a
      pure (Artifact (directory ++ actorClass a ++ extension) source "generated" "source")
    supervisorArtifact s = do
      identifier (supervisionClass s)
      mapM_ (\(_, name, _) -> identifier name) (supervisionChildren s)
      pure (Artifact (directory ++ supervisionClass s ++ extension)
        ((if kotlin then kotlinSupervisor else javaSupervisor) s) "generated" "source")
    reserved a h
      | handlerName h `elem` ["start", "stop", "crash", "monitor", "link"] || ("tell" ++ capital (handlerName h)) `elem` map handlerName (actorHandlers a) =
          Left ("actor " ++ actorName a ++ ": handler " ++ handlerName h ++ " clashes with a method of " ++ actorClass a ++ "; rename it")
      | otherwise = pure ()

-- The class holding a unit's adapters: example.actors has example.Actors.
adapterClass :: C.Unit -> String
adapterClass u = intercalate "." (init parts ++ [concatMap capital (split '_' (last parts))])
  where parts = split '.' (unitName u)

adapterCall :: Actor -> C.Declaration -> [String] -> String
adapterCall a d args = adapterClass (actorUnit a) ++ "." ++ adapterName (actorUnit a) (C.declarationId d) ++
  "(" ++ intercalate ", " args ++ ")"

isUnit :: C.Type -> Bool
isUnit t = t == C.Constructor "Unit" []

javaSource :: [C.DataDeclaration] -> Actor -> Either String String
javaSource datas a = do
  own <- boxed (actorState a)
  let startArgs = [(p, t) | (p, t) <- actorStartArguments a]
  startParams <- sequence [(\n -> n ++ " " ++ p) <$> native t | (p, t) <- startArgs, not (isUnit t)]
  methods <- mapM (handler own) (actorHandlers a)
  let startValues = [if isUnit t then "LawSpecRuntime.absent(\"Unit\")" else p | (p, t) <- startArgs]
      initial = awaited (actorStart a) (adapterCall a (actorStart a) startValues)
      restart = case actorRestart a of
        Just d -> "s -> " ++ awaited d (adapterCall a d ["s"])
        Nothing -> "s -> " ++ initial
      startNames = [p | (p, t) <- startArgs, not (isUnit t)]
  pure $ unlines $
    [ "// Generated by LawSpec from actor " ++ actorName a ++ ". Do not edit."
    , "package lawspec.actors;"
    , ""
    , "import lawspec.runtime.LawSpecRuntime;"
    , ""
    , "/**"
    , " * Actor " ++ actorName a ++ ": owns its state and handles one message at a time, in the order they"
    , " * arrive. Each handler method sends a message and returns the reply; tell methods send it"
    , " * without waiting. A handler that throws crashes the actor: the caller gets"
    , " * LawSpecRuntime.ActorCrashed, and a supervised actor restarts (from its restart adapter, or its"
    , " * start) while any other stops."
    , " */"
    , "public final class " ++ cls ++ " {"
    , "  private final LawSpecRuntime.Actor<" ++ own ++ "> actor;"
    , ""
    , "  private " ++ cls ++ "(LawSpecRuntime.Actor<" ++ own ++ "> actor) {"
    , "    this.actor = actor;"
    , "  }"
    , ""
    , "  /** Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor. */"
    , "  public static " ++ cls ++ " start(" ++ intercalate ", " startParams ++ ") {"
    , "    return start(" ++ intercalate ", " (startNames ++ ["null", "LawSpecRuntime.Supervisor.PERMANENT"]) ++ ");"
    , "  }"
    , ""
    , "  /**"
    , "   * Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor, under supervisor"
    , "   * (when not null) with the given lifetime."
    , "   */"
    , "  public static " ++ cls ++ " start(" ++ intercalate ", " (startParams ++ ["LawSpecRuntime.Supervisor supervisor", "String lifetime"]) ++ ") {"
    , "    var actor = new LawSpecRuntime.Actor<" ++ own ++ ">(" ++ initial ++ ", " ++ restart ++ ");"
    , "    if (supervisor != null) supervisor.supervise(actor, lifetime);"
    , "    return new " ++ cls ++ "(actor);"
    , "  }"
    ] ++ concatMap ("" :) methods ++
    [ ""
    , "  /** Crashes the actor as a failing handler would, after the messages already sent: for testing how it restarts. */"
    , "  public void crash() {"
    , "    actor.crash();"
    , "  }"
    , ""
    , "  /** notify gets Exit(\"crashed\", cause) after each crash, and Exit(\"stopped\", null) once it stops. */"
    , "  public void monitor(java.util.function.Consumer<LawSpecRuntime.Exit> notify) {"
    , "    actor.monitor(notify);"
    , "  }"
    , ""
    , "  /** When either actor crashes, the other crashes too. */"
    , "  public void link(" ++ cls ++ " other) {"
    , "    actor.link(other.actor);"
    , "  }"
    , ""
    , "  /** Refuses further messages; those already sent are still handled. */"
    , "  public void stop() {"
    , "    actor.stop();"
    , "  }"
    , "}" ]
  where
    cls = actorClass a
    boxed t = shorten <$> javaDataType datas t
    native t = (\b -> maybe b id (lookup b unboxed)) <$> boxed t
    awaited d call = if C.declarationAsync d then call ++ ".join()" else call
    handler own h = do
      params <- sequence [(\n -> n ++ " " ++ p) <$> native t | (p, t) <- handlerArguments h]
      reply <- traverse boxed (handlerReply h)
      result <- maybe (pure "void") native (handlerReply h)
      let call = awaited (handlerDeclaration h) (adapterCall a (handlerDeclaration h) ("s" : map fst (handlerArguments h)))
          replyType = maybe "Object" id reply
          step = case reply of
            Just _ -> "s -> {\n      var next = " ++ call ++ ";\n      return new LawSpecRuntime.Next<" ++ replyType ++ ", " ++ own ++
              ">(next.first(), next.second());\n    }"
            Nothing -> "s -> new LawSpecRuntime.Next<Object, " ++ own ++ ">(null, " ++ call ++ ")"
          name = handlerName h
      pure
        [ "  /** Sends " ++ name ++ " and waits for the reply. */"
        , "  public " ++ result ++ " " ++ name ++ "(" ++ intercalate ", " params ++ ") {"
        , "    " ++ (if reply == Nothing then "" else "return ") ++ "actor.<" ++ replyType ++ ">call(" ++ step ++ ");"
        , "  }"
        , ""
        , "  /** Sends " ++ name ++ " without waiting for the reply. */"
        , "  public void tell" ++ capital name ++ "(" ++ intercalate ", " params ++ ") {"
        , "    actor.cast(" ++ step ++ ");"
        , "  }" ]

kotlinSource :: [C.DataDeclaration] -> Actor -> Either String String
kotlinSource datas a = do
  own <- kotlinDataType datas (actorState a)
  let startArgs = actorStartArguments a
  startParams <- sequence [(\n -> p ++ ": " ++ n) <$> kotlinDataType datas t | (p, t) <- startArgs, not (isUnit t)]
  methods <- mapM (handler own) (actorHandlers a)
  let startValues = [if isUnit t then "kotlin.Unit" else p | (p, t) <- startArgs]
      initial = awaited (actorStart a) (adapterCall a (actorStart a) startValues)
      restart = case actorRestart a of
        Just d -> "{ s -> " ++ awaited d (adapterCall a d ["s"]) ++ " }"
        Nothing -> "{ _ -> " ++ initial ++ " }"
  pure $ unlines $
    [ "// Generated by LawSpec from actor " ++ actorName a ++ ". Do not edit."
    , "package lawspec.actors"
    , ""
    , "import lawspec.runtime.LawSpecRuntime"
    , ""
    , "/**"
    , " * Actor " ++ actorName a ++ ": owns its state and handles one message at a time, in the order they"
    , " * arrive. Each handler method sends a message and returns the reply; tell methods send it"
    , " * without waiting. A handler that throws crashes the actor: the caller gets"
    , " * LawSpecRuntime.ActorCrashed, and a supervised actor restarts (from its restart adapter, or its"
    , " * start) while any other stops."
    , " */"
    , "class " ++ cls ++ " private constructor(private val actor: LawSpecRuntime.Actor<" ++ own ++ ">) {"
    , "    companion object {"
    , "        /**"
    , "         * Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor, under"
    , "         * supervisor (when given) with the given lifetime."
    , "         */"
    , "        @JvmStatic"
    , "        @JvmOverloads"
    , "        fun start(" ++ intercalate ", " (startParams ++ ["supervisor: LawSpecRuntime.Supervisor? = null", "lifetime: String = LawSpecRuntime.Supervisor.PERMANENT"]) ++ "): " ++ cls ++ " {"
    , "            val actor = LawSpecRuntime.Actor<" ++ own ++ ">(" ++ initial ++ ") " ++ restart
    , "            supervisor?.supervise(actor, lifetime)"
    , "            return " ++ cls ++ "(actor)"
    , "        }"
    , "    }"
    ] ++ concatMap ("" :) methods ++
    [ ""
    , "    /** Crashes the actor as a failing handler would, after the messages already sent: for testing how it restarts. */"
    , "    fun crash() = actor.crash()"
    , ""
    , "    /** notify gets Exit(\"crashed\", cause) after each crash, and Exit(\"stopped\", null) once it stops. */"
    , "    fun monitor(notify: (LawSpecRuntime.Exit) -> kotlin.Unit) = actor.monitor { notify(it) }"
    , ""
    , "    /** When either actor crashes, the other crashes too. */"
    , "    fun link(other: " ++ cls ++ ") = actor.link(other.actor)"
    , ""
    , "    /** Refuses further messages; those already sent are still handled. */"
    , "    fun stop() = actor.stop()"
    , "}" ]
  where
    cls = actorClass a
    awaited d call = if C.declarationAsync d then "kotlinx.coroutines.runBlocking { " ++ call ++ " }" else call
    handler own h = do
      params <- sequence [(\n -> p ++ ": " ++ n) <$> kotlinDataType datas t | (p, t) <- handlerArguments h]
      reply <- traverse (kotlinDataType datas) (handlerReply h)
      let call = awaited (handlerDeclaration h) (adapterCall a (handlerDeclaration h) ("s" : map fst (handlerArguments h)))
          replyType = maybe "kotlin.Unit" id reply
          step = case reply of
            Just _ -> "{ s ->\n            val next = " ++ call ++ "\n            LawSpecRuntime.Next<" ++ replyType ++ ", " ++ own ++
              ">(next.first, next.second)\n        }"
            Nothing -> "{ s -> LawSpecRuntime.Next<" ++ replyType ++ ", " ++ own ++ ">(kotlin.Unit, " ++ call ++ ") }"
          name = handlerName h
      pure
        [ "    /** Sends " ++ name ++ " and waits for the reply. */"
        , "    fun " ++ name ++ "(" ++ intercalate ", " params ++ "): " ++ replyType ++ " ="
        , "        actor.call<" ++ replyType ++ "> " ++ step
        , ""
        , "    /** Sends " ++ name ++ " without waiting for the reply. */"
        , "    fun tell" ++ capital name ++ "(" ++ intercalate ", " params ++ ") {"
        , "        actor.cast " ++ step
        , "    }" ]

-- A supervisor's class: start() makes the runtime supervisor and starts
-- each child under it, in order; each child is a field.
javaSupervisor :: Supervision -> String
javaSupervisor s = unlines $
  [ "// Generated by LawSpec from supervisor " ++ supervisionName s ++ ". Do not edit."
  , "package lawspec.actors;"
  , ""
  , "import lawspec.runtime.LawSpecRuntime;"
  , ""
  , "/** Supervisor " ++ supervisionName s ++ ": " ++ strategyText s ++ ", at most " ++ show (supervisionRestarts s) ++
      " restarts in " ++ seconds s ++ "s. */"
  , "public final class " ++ cls ++ " {"
  , "  private final LawSpecRuntime.Supervisor supervisor;" ] ++
  [ "  public final " ++ childClass c ++ " " ++ name ++ ";" | (_, name, c) <- supervisionChildren s ] ++
  [ ""
  , "  private " ++ cls ++ "(" ++ intercalate ", " ("LawSpecRuntime.Supervisor supervisor" : [childClass c ++ " " ++ name | (_, name, c) <- supervisionChildren s]) ++ ") {"
  , "    this.supervisor = supervisor;" ] ++
  [ "    this." ++ name ++ " = " ++ name ++ ";" | (_, name, _) <- supervisionChildren s ] ++
  [ "  }"
  , ""
  , "  /** Starts the supervisor and its children. */"
  , "  public static " ++ cls ++ " start() {"
  , "    return start(null, LawSpecRuntime.Supervisor.PERMANENT);"
  , "  }"
  , ""
  , "  /** Starts the supervisor and its children, under parent (when not null) with the given lifetime. */"
  , "  public static " ++ cls ++ " start(LawSpecRuntime.Supervisor parent, String lifetime) {"
  , "    var own = new LawSpecRuntime.Supervisor(" ++ show (strategyName s) ++ ", " ++ show (supervisionRestarts s) ++ ", " ++ seconds s ++ ");" ] ++
  [ "    var " ++ name ++ " = " ++ childClass c ++ ".start(own, " ++ show (lifetimeName l) ++ ");" | (l, name, c) <- supervisionChildren s ] ++
  [ "    if (parent != null) parent.supervise(own, lifetime);"
  , "    return new " ++ cls ++ "(" ++ intercalate ", " ("own" : [name | (_, name, _) <- supervisionChildren s]) ++ ");"
  , "  }"
  , ""
  , "  /** notify gets Exit(\"crashed\", cause) when it passes its restart limit, and Exit(\"stopped\", null) once stopped. */"
  , "  public void monitor(java.util.function.Consumer<LawSpecRuntime.Exit> notify) {"
  , "    supervisor.monitor(notify);"
  , "  }"
  , ""
  , "  /** Stops every child, last started first, without restarting them. */"
  , "  public void stop() {"
  , "    supervisor.stop();"
  , "  }"
  , "}" ]
  where cls = supervisionClass s

kotlinSupervisor :: Supervision -> String
kotlinSupervisor s = unlines $
  [ "// Generated by LawSpec from supervisor " ++ supervisionName s ++ ". Do not edit."
  , "package lawspec.actors"
  , ""
  , "import lawspec.runtime.LawSpecRuntime"
  , ""
  , "/** Supervisor " ++ supervisionName s ++ ": " ++ strategyText s ++ ", at most " ++ show (supervisionRestarts s) ++
      " restarts in " ++ seconds s ++ "s. */"
  , "class " ++ cls ++ " private constructor("
  , "    private val supervisor: LawSpecRuntime.Supervisor" ++ concatMap (\(_, name, c) -> ",\n    val " ++ name ++ ": " ++ childClass c) (supervisionChildren s) ++ ","
  , ") {"
  , "    companion object {"
  , "        /** Starts the supervisor and its children, under parent (when given) with the given lifetime. */"
  , "        @JvmStatic"
  , "        @JvmOverloads"
  , "        fun start(parent: LawSpecRuntime.Supervisor? = null, lifetime: String = LawSpecRuntime.Supervisor.PERMANENT): " ++ cls ++ " {"
  , "            val own = LawSpecRuntime.Supervisor(" ++ show (strategyName s) ++ ", " ++ show (supervisionRestarts s) ++ ", " ++ seconds s ++ ")" ] ++
  [ "            val " ++ name ++ " = " ++ childClass c ++ ".start(own, " ++ show (lifetimeName l) ++ ")" | (l, name, c) <- supervisionChildren s ] ++
  [ "            parent?.supervise(own, lifetime)"
  , "            return " ++ cls ++ "(" ++ intercalate ", " ("own" : [name | (_, name, _) <- supervisionChildren s]) ++ ")"
  , "        }"
  , "    }"
  , ""
  , "    /** notify gets Exit(\"crashed\", cause) when it passes its restart limit, and Exit(\"stopped\", null) once stopped. */"
  , "    fun monitor(notify: (LawSpecRuntime.Exit) -> kotlin.Unit) = supervisor.monitor { notify(it) }"
  , ""
  , "    /** Stops every child, last started first, without restarting them. */"
  , "    fun stop() = supervisor.stop()"
  , "}" ]
  where cls = supervisionClass s

childClass :: Child -> String
childClass c = case c of
  ActorChild a -> actorClass a
  SupervisorChild n -> n

strategyName :: Supervision -> String
strategyName s = case supervisionStrategy s of
  OneForOne -> "one_for_one"
  OneForAll -> "one_for_all"
  RestForOne -> "rest_for_one"

strategyText :: Supervision -> String
strategyText s = case supervisionStrategy s of
  OneForOne -> "one for one"
  OneForAll -> "one for all"
  RestForOne -> "rest for one"

lifetimeName :: Lifetime -> String
lifetimeName l = case l of
  Permanent -> "permanent"
  Transient -> "transient"
  Temporary -> "temporary"

-- The period in seconds, as a decimal literal.
seconds :: Supervision -> String
seconds s = let (whole, micros) = supervisionPeriod s `divMod` 1000000
                pad m = replicate (6 - length m) '0' ++ m
            in show whole ++ "." ++ (case reverse (dropWhile (== '0') (reverse (pad (show micros)))) of
                                      "" -> "0"
                                      digits -> digits)

capital :: String -> String
capital (c : rest) = toUpper c : rest
capital [] = []

split :: Char -> String -> [String]
split c s = case break (== c) s of
  (a, _ : rest) -> a : split c rest
  (a, []) -> [a]

-- java.lang names read better unqualified.
shorten :: String -> String
shorten [] = []
shorten s@(c : rest) = case stripPrefix "java.lang." s of
  Just after -> shorten after
  Nothing -> c : shorten rest

unboxed :: [(String, String)]
unboxed = [ ("Byte", "byte"), ("Short", "short"), ("Integer", "int"), ("Long", "long")
          , ("Float", "float"), ("Double", "double"), ("Character", "char"), ("Boolean", "boolean") ]
