-- Typed actors for Java and Kotlin implementation code (see LawSpec.Actors).
--
-- Every actor becomes a class lawspec.actors.<Handle> (AccountActor): Java
-- source for Java projects, Kotlin source for Kotlin projects, since each
-- calls the user's adapters natively (a Kotlin adapter object, possibly with
-- suspend handlers). start(...) makes the state with the start adapter and
-- runs it in a LawSpecRuntime.Actor; each handler is a method that sends its
-- message and returns the reply, tell<Handler> sends it without waiting, and
-- stop() refuses further messages.
module LawSpec.Actors.Jvm (emit) where

import Data.Char (toUpper)
import Data.List (intercalate, stripPrefix)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (adapterName, unitName)
import LawSpec.JavaData (javaDataType, identifier)
import LawSpec.KotlinData (kotlinDataType)
import LawSpec.Actors.Types (Actor(..), Handler(..))

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> Either String [Artifact]
emit target _ _ datas = mapM artifact
  where
    kotlin = target == "kotlin"
    artifact a = do
      identifier (actorClass a)
      mapM_ (reserved a) (actorHandlers a)
      source <- (if kotlin then kotlinSource else javaSource) datas a
      let directory = if kotlin then "src/main/kotlin/lawspec/actors/" else "src/main/java/lawspec/actors/"
      pure (Artifact (directory ++ actorClass a ++ (if kotlin then ".kt" else ".java")) source "generated" "source")
    reserved a h
      | handlerName h `elem` ["start", "stop"] || ("tell" ++ capital (handlerName h)) `elem` map handlerName (actorHandlers a) =
          Left ("actor " ++ actorName a ++ ": handler " ++ handlerName h ++ " clashes with a method of " ++ actorClass a ++ "; rename it")
      | otherwise = pure ()

-- The class holding a unit's adapters: example.actors has example.Actors.
adapterClass :: C.Unit -> String
adapterClass u = intercalate "." (init parts ++ [concatMap capital (split '_' (last parts))])
  where parts = split '.' (unitName u)

adapterCall :: Actor -> C.Declaration -> [String] -> String
adapterCall a d args = adapterClass (actorUnit a) ++ "." ++ adapterName (actorUnit a) (C.declarationId d) ++
  "(" ++ intercalate ", " args ++ ")"

isUnit :: C.Type -> Bool
isUnit t = t == C.Constructor "Unit" []

javaSource :: [C.DataDeclaration] -> Actor -> Either String String
javaSource datas a = do
  own <- boxed (actorState a)
  let startArgs = [(p, t) | (p, t) <- actorStartArguments a]
  startParams <- sequence [(\n -> n ++ " " ++ p) <$> native t | (p, t) <- startArgs, not (isUnit t)]
  methods <- mapM (handler own) (actorHandlers a)
  let startValues = [if isUnit t then "LawSpecRuntime.absent(\"Unit\")" else p | (p, t) <- startArgs]
      initial = awaited (actorStart a) (adapterCall a (actorStart a) startValues)
  pure $ unlines $
    [ "// Generated by LawSpec from actor " ++ actorName a ++ ". Do not edit."
    , "package lawspec.actors;"
    , ""
    , "import lawspec.runtime.LawSpecRuntime;"
    , ""
    , "/**"
    , " * Actor " ++ actorName a ++ ": owns its state and handles one message at a time, in the order they"
    , " * arrive. Each handler method sends a message and returns the reply; tell methods send it"
    , " * without waiting."
    , " */"
    , "public final class " ++ cls ++ " {"
    , "  private final LawSpecRuntime.Actor<" ++ own ++ "> actor;"
    , ""
    , "  private " ++ cls ++ "(LawSpecRuntime.Actor<" ++ own ++ "> actor) {"
    , "    this.actor = actor;"
    , "  }"
    , ""
    , "  /** Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor. */"
    , "  public static " ++ cls ++ " start(" ++ intercalate ", " startParams ++ ") {"
    , "    return new " ++ cls ++ "(new LawSpecRuntime.Actor<>(" ++ initial ++ "));"
    , "  }"
    ] ++ concatMap ("" :) methods ++
    [ ""
    , "  /** Refuses further messages; those already sent are still handled. */"
    , "  public void stop() {"
    , "    actor.stop();"
    , "  }"
    , "}" ]
  where
    cls = actorClass a
    boxed t = shorten <$> javaDataType datas t
    native t = (\b -> maybe b id (lookup b unboxed)) <$> boxed t
    awaited d call = if C.declarationAsync d then call ++ ".join()" else call
    handler own h = do
      params <- sequence [(\n -> n ++ " " ++ p) <$> native t | (p, t) <- handlerArguments h]
      reply <- traverse boxed (handlerReply h)
      result <- maybe (pure "void") native (handlerReply h)
      let call = awaited (handlerDeclaration h) (adapterCall a (handlerDeclaration h) ("s" : map fst (handlerArguments h)))
          replyType = maybe "Object" id reply
          step = case reply of
            Just _ -> "s -> {\n      var next = " ++ call ++ ";\n      return new LawSpecRuntime.Next<" ++ replyType ++ ", " ++ own ++
              ">(next.first(), next.second());\n    }"
            Nothing -> "s -> new LawSpecRuntime.Next<Object, " ++ own ++ ">(null, " ++ call ++ ")"
          name = handlerName h
      pure
        [ "  /** Sends " ++ name ++ " and waits for the reply. */"
        , "  public " ++ result ++ " " ++ name ++ "(" ++ intercalate ", " params ++ ") {"
        , "    " ++ (if reply == Nothing then "" else "return ") ++ "actor.<" ++ replyType ++ ">call(" ++ step ++ ");"
        , "  }"
        , ""
        , "  /** Sends " ++ name ++ " without waiting for the reply. */"
        , "  public void tell" ++ capital name ++ "(" ++ intercalate ", " params ++ ") {"
        , "    actor.cast(" ++ step ++ ");"
        , "  }" ]

kotlinSource :: [C.DataDeclaration] -> Actor -> Either String String
kotlinSource datas a = do
  own <- kotlinDataType datas (actorState a)
  let startArgs = actorStartArguments a
  startParams <- sequence [(\n -> p ++ ": " ++ n) <$> kotlinDataType datas t | (p, t) <- startArgs, not (isUnit t)]
  methods <- mapM (handler own) (actorHandlers a)
  let startValues = [if isUnit t then "kotlin.Unit" else p | (p, t) <- startArgs]
      initial = awaited (actorStart a) (adapterCall a (actorStart a) startValues)
  pure $ unlines $
    [ "// Generated by LawSpec from actor " ++ actorName a ++ ". Do not edit."
    , "package lawspec.actors"
    , ""
    , "import lawspec.runtime.LawSpecRuntime"
    , ""
    , "/**"
    , " * Actor " ++ actorName a ++ ": owns its state and handles one message at a time, in the order they"
    , " * arrive. Each handler method sends a message and returns the reply; tell methods send it"
    , " * without waiting."
    , " */"
    , "class " ++ cls ++ " private constructor(private val actor: LawSpecRuntime.Actor<" ++ own ++ ">) {"
    , "    companion object {"
    , "        /** Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor. */"
    , "        @JvmStatic"
    , "        fun start(" ++ intercalate ", " startParams ++ "): " ++ cls ++ " = " ++ cls ++ "(LawSpecRuntime.Actor(" ++ initial ++ "))"
    , "    }"
    ] ++ concatMap ("" :) methods ++
    [ ""
    , "    /** Refuses further messages; those already sent are still handled. */"
    , "    fun stop() = actor.stop()"
    , "}" ]
  where
    cls = actorClass a
    awaited d call = if C.declarationAsync d then "kotlinx.coroutines.runBlocking { " ++ call ++ " }" else call
    handler own h = do
      params <- sequence [(\n -> p ++ ": " ++ n) <$> kotlinDataType datas t | (p, t) <- handlerArguments h]
      reply <- traverse (kotlinDataType datas) (handlerReply h)
      let call = awaited (handlerDeclaration h) (adapterCall a (handlerDeclaration h) ("s" : map fst (handlerArguments h)))
          replyType = maybe "kotlin.Unit" id reply
          step = case reply of
            Just _ -> "{ s ->\n            val next = " ++ call ++ "\n            LawSpecRuntime.Next<" ++ replyType ++ ", " ++ own ++
              ">(next.first, next.second)\n        }"
            Nothing -> "{ s -> LawSpecRuntime.Next<" ++ replyType ++ ", " ++ own ++ ">(kotlin.Unit, " ++ call ++ ") }"
          name = handlerName h
      pure
        [ "    /** Sends " ++ name ++ " and waits for the reply. */"
        , "    fun " ++ name ++ "(" ++ intercalate ", " params ++ "): " ++ replyType ++ " ="
        , "        actor.call<" ++ replyType ++ "> " ++ step
        , ""
        , "    /** Sends " ++ name ++ " without waiting for the reply. */"
        , "    fun tell" ++ capital name ++ "(" ++ intercalate ", " params ++ ") {"
        , "        actor.cast " ++ step
        , "    }" ]

capital :: String -> String
capital (c : rest) = toUpper c : rest
capital [] = []

split :: Char -> String -> [String]
split c s = case break (== c) s of
  (a, _ : rest) -> a : split c rest
  (a, []) -> [a]

-- java.lang names read better unqualified.
shorten :: String -> String
shorten [] = []
shorten s@(c : rest) = case stripPrefix "java.lang." s of
  Just after -> shorten after
  Nothing -> c : shorten rest

unboxed :: [(String, String)]
unboxed = [ ("Byte", "byte"), ("Short", "short"), ("Integer", "int"), ("Long", "long")
          , ("Float", "float"), ("Double", "double"), ("Character", "char"), ("Boolean", "boolean") ]
