-- Typed actors for Python implementation code (see LawSpec.Actors).
--
-- Every actor becomes a class named for its handle type in lawspec_actors:
-- AccountActor.start(...) makes the state with the start adapter and runs it
-- in an lawspec_runtime.Actor; each handler is a method that sends its
-- message and returns the reply, and tell_<handler> sends it without
-- waiting. stop() refuses further messages.
module LawSpec.Actors.Python (emit) where

import Data.List (intercalate, nub)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (adapterName, unitName)
import LawSpec.PythonTypes (identifier, pythonDataTypeDoc)
import LawSpec.PythonData (pythonTypeReferenceDoc, requiresSchema)
import LawSpec.MachineSpec (describe)
import Control.Monad (foldM)
import qualified LawSpec.Code.Doc as D
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))

emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ bits datas actors supervisions = do
  mapM_ (identifier . actorClass) actors
  mapM_ (identifier . supervisionClass) supervisions
  -- Each actor's messages as wire descriptors, for serving it and calling
  -- it across nodes; an actor whose types have none yet stays local.
  let wired (table, acc) a = case foldM (handlerWire bits datas) (table, []) (actorHandlers a) of
        Right (table', hs) -> (table', acc ++ [(actorName a, reverse hs)])
        Left _ -> (table, acc)
      (types, wires) = foldl wired ([], []) actors
  classes <- (++ map supervisorClassText supervisions) <$> mapM (\a -> actorClassText datas (lookup (actorName a) wires) a) actors
  let modules = nub (map (unitName . actorUnit) actors)
      header =
        [ "# Generated by LawSpec. Do not edit."
        , "\"\"\"Actors of " ++ intercalate ", " modules ++ "."
        , ""
        , "Each actor class runs one actor: start(...) makes its state and returns"
        , "the actor. Each handler method sends a message and returns the reply;"
        , "tell_<handler> sends it without waiting. Messages are handled one at a"
        , "time, in the order they arrive. A handler that raises crashes the actor:"
        , "the caller gets ls.ActorCrashed, and a supervised actor restarts (from"
        , "its restart adapter, or its start) while any other stops."
        , ""
        , "Each supervisor class starts its children and restarts them after a"
        , "crash; its children are attributes named as in the specification."
        , "\"\"\""
        , "from __future__ import annotations"
        , ""
        , "import builtins as _builtins"
        , "import lawspec_runtime as ls"
        , "import lawspec_data as data" ] ++
        [ "import " ++ m ++ " as " ++ alias m | m <- modules ]
      helper =
        [ ""
        , ""
        , "def _split(pair):"
        , "    return pair.first, pair.second"
        , ""
        , ""
        , "# Values crossing the network are logical; handlers and callers use"
        , "# native ones."
        , "_TYPES = ls.Values({str(f[1]): f for f in ls.read_descriptor(" ++ show (unwords (map snd (reverse types))) ++ ")})"
        , "_SCHEMA = data.make_schema() if hasattr(data, 'make_schema') else None"
        , ""
        , ""
        , "def _native(reference, value):"
        , "    return value if reference is None else _SCHEMA.to_native(reference, value)"
        , ""
        , ""
        , "def _logical(reference, value):"
        , "    return value if reference is None else _SCHEMA.from_native(reference, value)"
        , ""
        , ""
        , "def _served(reference, pair):"
        , "    return _logical(reference, pair.first), pair.second"
        , ""
        , ""
        , "def _d(text):"
        , "    return ls.read_descriptor(text)[0]" ]
  pure [Artifact "src/lawspec_actors.py" (unlines (header ++ helper) ++ concatMap ("\n\n" ++) classes) "generated" "source"]

alias :: String -> String
alias m = "_" ++ map (\c -> if c == '.' then '_' else c) m

-- A handler's argument and reply descriptors (adding data types to the
-- table) and schema references.
type HandlerWire = (Handler, [String], String)

handlerWire :: Int -> [C.DataDeclaration] -> ([(String, String)], [HandlerWire]) -> Handler -> Either String ([(String, String)], [HandlerWire])
handlerWire bits datas (table, acc) h = do
  (args, table') <- foldM (\(xs, t) (_, ty) -> (\(x, t') -> (xs ++ [x], t')) <$> describe bits datas t ty) ([], table) (handlerArguments h)
  (reply, table'') <- describe bits datas table' (maybe (C.Constructor "Unit" []) id (handlerReply h))
  pure (table'', (h, args, reply) : acc)

actorClassText :: [C.DataDeclaration] -> Maybe [HandlerWire] -> Actor -> Either String String
actorClassText datas wire a = do
  startArgs <- mapM argument (actorStartArguments a)
  methods <- mapM handler (actorHandlers a)
  let cls = actorClass a
      impl d = alias (unitName (actorUnit a)) ++ "." ++ adapterName (actorUnit a) (C.declarationId d)
      startParams = [arg | arg@(_, (t, _)) <- startArgs, not (unit t)]
      startValues = [if unit t then "ls.UNIT" else p | (p, (t, _)) <- startArgs]
      startCall = awaited (actorStart a) (impl (actorStart a) ++ "(" ++ intercalate ", " startValues ++ ")")
      restartCall = case actorRestart a of
        Just d -> "lambda s: " ++ awaited d (impl d ++ "(s)")
        Nothing -> "lambda s: " ++ startCall
      keywords = ["*", "supervisor: ls.Supervisor | None = None", "lifetime: str = 'permanent'"]
  pure $ unlines $
    [ "class " ++ cls ++ ":"
    , "    \"\"\"Actor " ++ actorName a ++ ": owns its state and handles one message at a time.\"\"\""
    , ""
    , "    def __init__(self, actor: ls.Actor):"
    , "        self._actor = actor"
    , ""
    , "    @staticmethod"
    , "    def start(" ++ intercalate ", " (map typed startParams ++ keywords) ++ ") -> " ++ cls ++ ":"
    , "        \"\"\"Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor,"
    , "        under supervisor when given.\"\"\""
    , "        actor = ls.Actor(" ++ startCall ++ ", restart=" ++ restartCall ++ ")"
    , "        if supervisor is not None:"
    , "            supervisor.supervise(actor, lifetime)"
    , "        return " ++ cls ++ "(actor)"
    ] ++ concatMap (\m -> "" : m) methods ++
    [ ""
    , "    def crash(self) -> None:"
    , "        \"\"\"Crashes the actor as a failing handler would, after the messages"
    , "        already sent: for testing how it restarts.\"\"\""
    , "        self._actor.crash()"
    , ""
    , "    def monitor(self, notify) -> None:"
    , "        \"\"\"notify(('crashed', cause)) after each crash, and"
    , "        notify(('stopped', None)) once it stops.\"\"\""
    , "        self._actor.monitor(notify)"
    , ""
    , "    def link(self, other) -> None:"
    , "        \"\"\"When either actor crashes, the other crashes too.\"\"\""
    , "        self._actor.link(other._actor)"
    , ""
    , "    def stop(self) -> None:"
    , "        \"\"\"Refuses further messages; those already sent are still handled.\"\"\""
    , "        self._actor.stop()" ] ++ remote
  where
    reference ty = if requiresSchema datas ty then either (const "None") (D.render (D.Pretty 1000)) (pythonTypeReferenceDoc ty) else "None"
    replyType h = maybe (C.Constructor "Unit" []) id (handlerReply h)
    implName d = alias (unitName (actorUnit a)) ++ "." ++ adapterName (actorUnit a) (C.declarationId d)
    remote = case wire of
      Nothing -> []
      Just hs ->
        [ ""
        , "    def serve(self, node: ls.Node, name: str) -> str:"
        , "        \"\"\"Lets other nodes call this actor at <node address>/name; returns"
        , "        that address.\"\"\""
        , "        return node.serve(name, self._actor, {" ] ++
        [ "            " ++ show (handlerName h) ++ ": (lambda s" ++ concatMap (\(p, _) -> ", " ++ p) (handlerArguments h) ++ ": " ++
            (let call = awaited (handlerDeclaration h) (implName (handlerDeclaration h) ++ "(" ++ intercalate ", " ("s" : [ "_native(" ++ reference ty ++ ", " ++ p ++ ")" | (p, ty) <- handlerArguments h]) ++ ")")
             in case handlerReply h of
                  Just r -> "_served(" ++ reference r ++ ", " ++ call ++ ")"
                  Nothing -> "(ls.UNIT, " ++ call ++ ")") ++
            ", [" ++ intercalate ", " ["_d(" ++ show d ++ ")" | d <- ds] ++ "], _d(" ++ show r ++ ")),"
        | (h, ds, r) <- hs ] ++
        [ "        }, _TYPES)"
        , ""
        , "    @staticmethod"
        , "    def connect(node: ls.Node, address: str, timeout: float = 5.0) -> " ++ actorClass a ++ "Remote:"
        , "        \"\"\"The actor served at address on another node; each call waits up"
        , "        to timeout seconds, then raises ls.Unreachable.\"\"\""
        , "        return " ++ actorClass a ++ "Remote(node.remote_actor(address, {" ] ++
        [ "            " ++ show (handlerName h) ++ ": ([" ++ intercalate ", " ["_d(" ++ show d ++ ")" | d <- ds] ++ "], _d(" ++ show r ++ ")),"
        | (h, ds, r) <- hs ] ++
        [ "        }, _TYPES, timeout))"
        , ""
        , ""
        , "class " ++ actorClass a ++ "Remote:"
        , "    \"\"\"Actor " ++ actorName a ++ " on another node: each method sends its message"
        , "    and waits for the reply.\"\"\""
        , ""
        , "    def __init__(self, remote: ls.RemoteActor):"
        , "        self._remote = remote" ] ++
        concat
        [ [ ""
          , "    def " ++ handlerName h ++ "(" ++ intercalate ", " ("self" : map fst (handlerArguments h)) ++ "):"
          , "        return _native(" ++ reference (replyType h) ++ ", self._remote.call(" ++ show (handlerName h) ++
              concatMap (\(p, ty) -> ", _logical(" ++ reference ty ++ ", " ++ p ++ ")") (handlerArguments h) ++ "))" ]
        | (h, _, _) <- hs ]
    unit t = t == C.Constructor "Unit" []
    typed (p, (_, native)) = p ++ ": " ++ native
    argument (p, t) = do
      native <- nativeType t
      pure (p, (t, native))
    nativeType t = D.render (D.Pretty 1000) <$> pythonDataTypeDoc datas t
    awaited d call = if C.declarationAsync d then "ls.await_task(" ++ call ++ ")" else call
    handler h = do
      args <- mapM argument (handlerArguments h)
      reply <- traverse nativeType (handlerReply h)
      let params = "self" : map (\(p, (_, n)) -> p ++ ": " ++ n) args
          call = awaited (handlerDeclaration h) (alias (unitName (actorUnit a)) ++ "." ++
            adapterName (actorUnit a) (C.declarationId (handlerDeclaration h)) ++ "(" ++ intercalate ", " ("s" : map fst args) ++ ")")
          step = case reply of
            Just _ -> "lambda s: _split(" ++ call ++ ")"
            Nothing -> "lambda s: (None, " ++ call ++ ")"
          name = handlerName h
      pure
        [ "    def " ++ name ++ "(" ++ intercalate ", " params ++ ") -> " ++ maybe "None" id reply ++ ":"
        , "        \"\"\"Sends " ++ name ++ " and waits for the reply.\"\"\""
        , "        return self._actor.call(" ++ step ++ ")"
        , ""
        , "    def tell_" ++ name ++ "(" ++ intercalate ", " params ++ ") -> None:"
        , "        \"\"\"Sends " ++ name ++ " without waiting for the reply.\"\"\""
        , "        self._actor.cast(" ++ step ++ ")" ]

-- A supervisor's class: start() makes the runtime supervisor and starts each
-- child under it, in order; each child is an attribute.
supervisorClassText :: Supervision -> String
supervisorClassText s = unlines $
  [ "class " ++ cls ++ ":"
  , "    \"\"\"Supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++
      show (supervisionRestarts s) ++ " restarts in " ++ seconds ++ "s.\"\"\""
  , "" ] ++
  [ "    " ++ name ++ ": " ++ childClass child | (_, name, child) <- supervisionChildren s ] ++
  [ ""
  , "    def __init__(self, supervisor: ls.Supervisor" ++ concatMap (\(_, name, child) -> ", " ++ name ++ ": " ++ childClass child) (supervisionChildren s) ++ "):"
  , "        self._supervisor = supervisor" ] ++
  [ "        self." ++ name ++ " = " ++ name | (_, name, _) <- supervisionChildren s ] ++
  [ ""
  , "    @staticmethod"
  , "    def start(*, supervisor: ls.Supervisor | None = None, lifetime: str = 'permanent') -> " ++ cls ++ ":"
  , "        \"\"\"Starts the supervisor and its children, under supervisor when given.\"\"\""
  , "        own = ls.Supervisor(" ++ show strategyName ++ ", max_restarts=" ++ show (supervisionRestarts s) ++ ", period=" ++ seconds ++ ")" ] ++
  [ "        " ++ name ++ " = " ++ childClass child ++ ".start(supervisor=own, lifetime=" ++ show (lifetimeName l) ++ ")"
  | (l, name, child) <- supervisionChildren s ] ++
  [ "        if supervisor is not None:"
  , "            supervisor.supervise(own, lifetime)"
  , "        return " ++ cls ++ "(own" ++ concatMap (\(_, name, _) -> ", " ++ name) (supervisionChildren s) ++ ")"
  , ""
  , "    def monitor(self, notify) -> None:"
  , "        \"\"\"notify(('crashed', cause)) when it passes its restart limit, and"
  , "        notify(('stopped', None)) once stopped.\"\"\""
  , "        self._supervisor.monitor(notify)"
  , ""
  , "    def stop(self) -> None:"
  , "        \"\"\"Stops every child, last started first, without restarting them.\"\"\""
  , "        self._supervisor.stop()" ]
  where
    cls = supervisionClass s
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    strategyName = case supervisionStrategy s of
      OneForOne -> "one_for_one" :: String
      OneForAll -> "one_for_all"
      RestForOne -> "rest_for_one"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one" :: String
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    lifetimeName l = case l of
      Permanent -> "permanent" :: String
      Transient -> "transient"
      Temporary -> "temporary"
    seconds = let (whole, micros) = supervisionPeriod s `divMod` 1000000
              in show whole ++ (if micros == 0 then "" else "." ++ reverse (dropWhile (== '0') (reverse (pad (show micros)))))
    pad m = replicate (6 - length m) '0' ++ m
