-- | Typed actors for Rust implementation code (see LawSpec.Actors).
--
-- Every actor becomes a struct named for its handle type in the module
-- lawspec_actors: AccountActor::start(...) makes the state with the start
-- adapter and runs it in an ls::actors::Actor; each handler is a method that
-- sends its message and returns the reply, and tell_<handler> sends it
-- without waiting. Both return ls::Result, which fails once the actor has
-- stopped (stop()), or when the handler crashed the actor. start_under runs
-- it under a supervisor, which restarts it (restart from, or its start)
-- after a crash. Every supervisor becomes a struct that starts its children
-- under a runtime ls::actors::Supervisor; its children are public fields.
-- Clones share the actor.
module LawSpec.Actors.Rust (emit) where

import Data.Char (isAlphaNum)
import Data.List (intercalate, nub)
import qualified LawSpec.Core as C
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (adapterName, unitName)
import LawSpec.RustData (rustDataType)
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))
import LawSpec.MachineSpec (describe)
import Control.Monad (foldM)

-- | Actors become a typed class, or Rust's idiom for one, generated from the
-- declaration. ref:DEC-actors-otp-supervision
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit _ _ bits datas actors supervisions = do
  -- Each actor's messages as wire descriptors, for serving it and calling
  -- it across nodes; an actor whose types have none yet stays local.
  let wired (table, acc) a = case foldM (handlerWire bits datas) (table, []) (actorHandlers a) of
        Right (table', hs) -> (table', acc ++ [(actorName a, reverse hs)])
        Left _ -> (table, acc)
      (types, wires) = foldl wired ([], []) actors
  structs <- (++ map supervisorStruct supervisions) <$> mapM (\a -> actorStruct datas (lookup (actorName a) wires) a) actors
  let modules = nub (map (unitName . actorUnit) actors)
      header =
        [ "// Generated by LawSpec. Do not edit."
        , "//! Actors of " ++ intercalate ", " modules ++ "."
        , "//!"
        , "//! Each struct runs one actor: start(...) makes its state and returns the"
        , "//! actor. Each handler method sends a message and returns the reply;"
        , "//! tell_<handler> sends it without waiting. Messages are handled one at a"
        , "//! time, in the order they arrive. A handler that fails (an Err or a"
        , "//! panic) crashes the actor: the call fails with \"the actor crashed: ...\","
        , "//! and a supervised actor restarts while any other stops. start_under"
        , "//! starts one under a supervisor. Each supervisor struct starts its"
        , "//! children, which are its public fields. Clones share the actor."
        , "#![allow(dead_code, unused_imports, non_snake_case)]"
        , "use crate::lawspec_runtime as ls;"
        , ""
        , "// The data types the actors' messages use on the wire."
        , "fn wire_types() -> ls::Values {"
        , "    ls::values_table(" ++ show (unwords (map snd (reverse types))) ++ ")"
        , "}" ]
  pure [Artifact "src/lawspec_actors.rs" (unlines header ++ concatMap ("\n" ++) structs) "generated" "source"]

-- | The crate module a unit's adapters are mounted at.
unitModule :: C.Unit -> String
unitModule = map (\c -> if isAlphaNum c || c == '_' then c else '_') . unitName

-- | A handler's argument and reply descriptors, adding data types to the table.
type HandlerWire = (Handler, [String], String)

handlerWire :: Int -> [C.DataDeclaration] -> ([(String, String)], [HandlerWire]) -> Handler -> Either String ([(String, String)], [HandlerWire])
handlerWire bits datas (table, acc) h = do
  (args, table') <- foldM (\(xs, t) (_, ty) -> (\(x, t') -> (xs ++ [x], t')) <$> describe bits datas t ty) ([], table) (handlerArguments h)
  (reply, table'') <- describe bits datas table' (maybe (C.Constructor "Unit" []) id (handlerReply h))
  pure (table'', (h, args, reply) : acc)

actorStruct :: [C.DataDeclaration] -> Maybe [HandlerWire] -> Actor -> Either String String
actorStruct datas wire a = do
  state <- rustDataType datas (actorState a)
  startArgs <- mapM argument (actorStartArguments a)
  methods <- mapM handler (actorHandlers a)
  remote <- case wire of
    Nothing -> pure []
    Just hs -> remoteParts hs
  let cls = actorClass a
      startParams = [p ++ ": " ++ t | (p, ty, t) <- startArgs, not (unit ty)]
      startNames = [p | (p, ty, _) <- startArgs, not (unit ty)]
      startCall = awaited (actorStart a) (impl (actorStart a) ++ "(" ++
        intercalate ", " [if unit ty then "()" else p ++ ".clone()" | (p, ty, _) <- startArgs] ++ ")")
      restart = case actorRestart a of
        Just d -> "move |state| Ok(" ++ awaited d (impl d ++ "(state)") ++ ")"
        Nothing -> "move |_| Ok(" ++ startCall ++ ")"
      supervision = ["supervisor: &ls::actors::Supervisor", "lifetime: ls::actors::Lifetime"]
  pure $ unlines $
    [ "/// Actor " ++ actorName a ++ ": owns its state and handles one message at a time."
    , "#[derive(Clone)]"
    , "pub struct " ++ cls ++ "(ls::actors::Actor<" ++ state ++ ">);"
    , ""
    , "impl " ++ cls ++ " {"
    , "    /// Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor."
    , "    pub fn start(" ++ intercalate ", " startParams ++ ") -> " ++ cls ++ " {"
    , "        " ++ cls ++ "(ls::actors::Actor::with_restart(" ++ startCall ++ ", " ++ restart ++ "))"
    , "    }"
    , ""
    , "    /// Starts the actor under supervisor, which restarts it after a crash"
    , "    /// " ++ (case actorRestart a of
                      Just d -> "from its last state, with " ++ C.declarationName d ++ "."
                      Nothing -> "from its start.")
    , "    pub fn start_under(" ++ intercalate ", " (supervision ++ startParams) ++ ") -> " ++ cls ++ " {"
    , "        let actor = " ++ cls ++ "::start(" ++ intercalate ", " startNames ++ ");"
    , "        supervisor.supervise(actor.0.clone(), lifetime);"
    , "        actor"
    , "    }"
    ] ++ concatMap ("" :) methods ++
    [ ""
    , "    /// Crashes the actor as a failing handler would, after the messages"
    , "    /// already sent: for testing how it restarts."
    , "    pub fn crash(&self) -> ls::Result<()> {"
    , "        self.0.crash(\"crashed on purpose\")"
    , "    }"
    , ""
    , "    /// notify(Exit::Crashed(cause)) after each crash, and notify(Exit::Stopped)"
    , "    /// once it stops."
    , "    pub fn monitor(&self, notify: impl Fn(ls::actors::Exit) + Send + Sync + 'static) {"
    , "        self.0.monitor(notify);"
    , "    }"
    , ""
    , "    /// When either actor crashes, the other crashes too."
    , "    pub fn link<T: Send + 'static>(&self, other: &ls::actors::Actor<T>) {"
    , "        self.0.link(other);"
    , "    }"
    , ""
    , "    /// The runtime actor, to link it or supervise it."
    , "    pub fn actor(&self) -> &ls::actors::Actor<" ++ state ++ "> {"
    , "        &self.0"
    , "    }"
    , ""
    , "    /// Refuses further messages; those already sent are still handled."
    , "    pub fn stop(&self) {"
    , "        self.0.stop();"
    , "    }" ] ++ fst' remote ++
    [ "}" ] ++ snd' remote
  where
    fst' r = case r of
      [] -> []
      (m, _) : _ -> m
    snd' r = case r of
      [] -> []
      (_, s) : _ -> s
    -- serve and connect, and the remote proxy struct.
    remoteParts hs = do
      typed <- mapM (\(h, ds, r) -> do
        args <- mapM argument (handlerArguments h)
        reply <- traverse (rustDataType datas) (handlerReply h)
        pure (h, ds, r, args, maybe "()" id reply)) hs
      let cls = actorClass a
          d text = "ls::descriptor(" ++ show text ++ ")"
          serveEntry (h, ds, r, args, _) =
            [ "        {"
            , "            let actor = self.clone();"
            , "            let handler: std::sync::Arc<dyn Fn(Vec<ls::Value>) -> ls::Result<ls::Value> + Send + Sync> ="
            , "                std::sync::Arc::new(move |args: Vec<ls::Value>| {"
            , "                    let mut args = args.into_iter();" ] ++
            [ "                    let " ++ p ++ ": " ++ t ++ " = ls::FromValue::from_value(args.next().ok_or_else(|| \"a missing argument\".to_string())?)?;"
            | (p, _, t) <- args ] ++
            [ "                    Ok(ls::IntoValue::into_value(actor." ++ handlerName h ++ "(" ++ intercalate ", " [p | (p, _, _) <- args] ++ ")?))"
            , "                });"
            , "            handlers.push((" ++ show (handlerName h) ++ ".to_string(), vec![" ++ intercalate ", " (map d ds) ++ "], " ++ d r ++ ", handler));"
            , "        }" ]
          methods' =
            [ ""
            , "    /// Lets other nodes call this actor at <node address>/name; returns"
            , "    /// that address."
            , "    pub fn serve(&self, node: &ls::net::Node, name: &str) -> ls::Result<String> {"
            , "        let mut handlers: Vec<ls::net::RemoteHandler> = Vec::new();" ] ++
            concatMap serveEntry typed ++
            [ "        node.serve(name, handlers, wire_types())"
            , "    }"
            , ""
            , "    /// The actor served at address on another node; each call waits up"
            , "    /// to timeout, then fails as unreachable."
            , "    pub fn connect(node: &ls::net::Node, address: &str, timeout: std::time::Duration) -> " ++ cls ++ "Remote {"
            , "        " ++ cls ++ "Remote(node.remote_actor(address, vec![" ++
                intercalate ", " ["(" ++ show (handlerName h) ++ ".to_string(), vec![" ++ intercalate ", " (map d ds) ++ "], " ++ d r ++ ")" | (h, ds, r, _, _) <- typed] ++
                "], wire_types(), timeout))"
            , "    }" ]
          proxy =
            [ ""
            , "/// Actor " ++ actorName a ++ " on another node: each method sends its message and"
            , "/// waits for the reply."
            , "pub struct " ++ cls ++ "Remote(ls::net::RemoteActor);"
            , ""
            , "impl " ++ cls ++ "Remote {" ] ++
            concat
            [ [ "    /// Sends " ++ handlerName h ++ " and waits for the reply."
              , "    pub fn " ++ handlerName h ++ "(" ++ intercalate ", " ("&self" : [p ++ ": " ++ t | (p, _, t) <- args]) ++ ") -> ls::Result<" ++ reply ++ "> {"
              , "        let reply = self.0.call(" ++ show (handlerName h) ++ ", &[" ++ intercalate ", " ["ls::IntoValue::into_value(" ++ p ++ ")" | (p, _, _) <- args] ++ "])?;"
              , "        ls::FromValue::from_value(reply)"
              , "    }"
              , "" ]
            | (h, _, _, args, reply) <- typed ] ++
            [ "}" ]
      pure [(methods', proxy)]
    unit t = t == C.Constructor "Unit" []
    impl d = "crate::" ++ unitModule (actorUnit a) ++ "::" ++ adapterName (actorUnit a) (C.declarationId d)
    awaited d call = if C.declarationAsync d then "ls::block_on(" ++ call ++ ")" else call
    argument (p, t) = (\native -> (rustName p, t, native)) <$> rustDataType datas t
    rustName p = map (\c -> if isAlphaNum c || c == '_' then c else '_') p
    handler h = do
      args <- mapM argument (handlerArguments h)
      reply <- traverse (rustDataType datas) (handlerReply h)
      let params = "&self" : [p ++ ": " ++ t | (p, _, t) <- args]
          call = awaited (handlerDeclaration h) (impl (handlerDeclaration h) ++ "(" ++ intercalate ", " ("state" : [p | (p, _, _) <- args]) ++ ")")
          step = case reply of
            Just _ -> "move |state| { let pair = " ++ call ++ "; Ok((pair.first, pair.second)) }"
            Nothing -> "move |state| Ok(((), " ++ call ++ "))"
          name = handlerName h
      pure
        [ "    /// Sends " ++ name ++ " and waits for the reply."
        , "    pub fn " ++ name ++ "(" ++ intercalate ", " params ++ ") -> ls::Result<" ++ maybe "()" id reply ++ "> {"
        , "        self.0.call(" ++ step ++ ")"
        , "    }"
        , ""
        , "    /// Sends " ++ name ++ " without waiting for the reply."
        , "    pub fn tell_" ++ name ++ "(" ++ intercalate ", " params ++ ") -> ls::Result<()> {"
        , "        self.0.tell(" ++ step ++ ")"
        , "    }" ]

-- | A supervisor's struct: start() makes the runtime supervisor and starts
-- each child under it, in order; each child is a public field.
supervisorStruct :: Supervision -> String
supervisorStruct s = unlines $
  [ "/// Supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++
      show (supervisionRestarts s) ++ " restarts in " ++ show (supervisionPeriod s) ++ " microseconds."
  , "#[derive(Clone)]"
  , "pub struct " ++ cls ++ " {"
  , "    supervisor: ls::actors::Supervisor," ] ++
  [ "    pub " ++ field name ++ ": " ++ childClass child ++ "," | (_, name, child) <- supervisionChildren s ] ++
  [ "}"
  , ""
  , "impl " ++ cls ++ " {"
  , "    /// Starts the supervisor and its children."
  , "    pub fn start() -> " ++ cls ++ " {"
  , "        " ++ cls ++ "::begin(None)"
  , "    }"
  , ""
  , "    /// Starts the supervisor and its children under parent."
  , "    pub fn start_under(parent: &ls::actors::Supervisor, lifetime: ls::actors::Lifetime) -> " ++ cls ++ " {"
  , "        " ++ cls ++ "::begin(Some((parent, lifetime)))"
  , "    }"
  , ""
  , "    fn begin(parent: Option<(&ls::actors::Supervisor, ls::actors::Lifetime)>) -> " ++ cls ++ " {"
  , "        let own = ls::actors::Supervisor::new(ls::actors::Strategy::" ++ strategy ++ ", " ++
      show (supervisionRestarts s) ++ ", std::time::Duration::from_micros(" ++ show (supervisionPeriod s) ++ "));" ] ++
  [ "        let " ++ field name ++ " = " ++ childClass child ++ "::start_under(&own, ls::actors::Lifetime::" ++ lifetime l ++ ");"
  | (l, name, child) <- supervisionChildren s ] ++
  [ "        if let Some((parent, lifetime)) = parent {"
  , "            parent.supervise(own.clone(), lifetime);"
  , "        }"
  , "        " ++ cls ++ " { supervisor: own" ++ concatMap (\(_, name, _) -> ", " ++ field name) (supervisionChildren s) ++ " }"
  , "    }"
  , ""
  , "    /// The runtime supervisor, to supervise more children."
  , "    pub fn supervisor(&self) -> &ls::actors::Supervisor {"
  , "        &self.supervisor"
  , "    }"
  , ""
  , "    /// notify(Exit::Crashed(cause)) when it passes its restart limit, and"
  , "    /// notify(Exit::Stopped) once stopped."
  , "    pub fn monitor(&self, notify: impl Fn(ls::actors::Exit) + Send + Sync + 'static) {"
  , "        self.supervisor.monitor(notify);"
  , "    }"
  , ""
  , "    /// Stops every child, last started first, without restarting them."
  , "    pub fn stop(&self) {"
  , "        self.supervisor.stop();"
  , "    }"
  , "}" ]
  where
    cls = supervisionClass s
    field = map (\c -> if isAlphaNum c || c == '_' then c else '_')
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    strategy = case supervisionStrategy s of
      OneForOne -> "OneForOne"
      OneForAll -> "OneForAll"
      RestForOne -> "RestForOne"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one" :: String
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    lifetime l = case l of
      Permanent -> "Permanent" :: String
      Transient -> "Transient"
      Temporary -> "Temporary"
