-- | Typed actors for JavaScript and TypeScript implementation code (see
-- LawSpec.Actors).
--
-- Every actor becomes a class named for its handle type in lawspec_actors:
-- AccountActor.start(...) makes the state with the start adapter and runs it
-- in a lawspec_runtime Actor; each handler is an async method that sends its
-- message and resolves to the reply, and tell<Handler> sends it without
-- waiting. stop() refuses further messages.
module LawSpec.Actors.Web (emit) where

import Control.Monad (foldM, forM, when)
import Data.Char (toUpper)
import Data.List (intercalate, isInfixOf, nub)
import qualified LawSpec.Core as C
import qualified LawSpec.Code.Doc as D
import LawSpec.Common (Artifact(..))
import LawSpec.Backend (adapterName, unitName)
import LawSpec.WebTypes (webDataTypeDocWith, webTypeReferenceDoc, requiresSchema)
import LawSpec.MachineSpec (describe)
import LawSpec.Actors.Types (Actor(..), Handler(..), Supervision(..), Child(..))
import LawSpec.Core.Machine (SupervisionStrategy(..), Lifetime(..))

-- | Actors become a typed class, or JavaScript and TypeScript's idiom for one,
-- generated from the declaration. ref:DEC-actors-otp-supervision
emit :: String -> Bool -> Int -> [C.DataDeclaration] -> [Actor] -> [Supervision] -> Either String [Artifact]
emit target _ bits datas actors supervisions = do
  -- Each actor's messages as wire descriptors, for serving it and calling
  -- it across nodes; an actor whose types have none yet stays local.
  let wired (table, acc) a = case foldM (handlerWire bits datas) (table, []) (actorHandlers a) of
        Right (table', hs) -> (table', acc ++ [(actorName a, reverse hs)])
        Left _ -> (table, acc)
      (types, wires) = foldl wired ([], []) actors
  classes <- (++ map (supervisorClassText ts supervisions) supervisions) <$>
    mapM (\a -> actorClassText ts datas (lookup (actorName a) wires) a) actors
  let modules = nub (map (unitName . actorUnit) actors)
      remote = not (null wires)
      helpers = if not remote then [] else
        [ ""
        , "// Values crossing the network are logical; handlers and callers use"
        , "// native ones."
        , "const _TYPES = ls.valuesFrom(" ++ show (unwords (map snd (reverse types) ++ ["(unit)"])) ++ ")[0];"
        , "const _SCHEMA" ++ (if ts then ": any" else "") ++ " = " ++ (if "data." `isInfixOf` classBody then "data.makeSchema()" else "null") ++ ";"
        , "const _native = (reference" ++ anyT ++ ", d" ++ anyT ++ ", value" ++ anyT ++ ")" ++ anyT ++ " => (reference === null ? ls.nativeScalar(d, value) : _SCHEMA.toNative(reference, value));"
        , "const _logical = (reference" ++ anyT ++ ", value" ++ anyT ++ ")" ++ anyT ++ " => (reference === null ? value : _SCHEMA.fromNative(reference, value));"
        , "const _served = (reference" ++ anyT ++ ", pair" ++ anyT ++ ")" ++ anyT ++ " => [_logical(reference, pair.first), pair.second];"
        , "const _d = (text" ++ (if ts then ": string" else "") ++ ")" ++ anyT ++ " => ls.readDescriptor(text)[0];" ]
      classBody = concat classes
      body = concatMap ("\n" ++) classes
      header =
        [ "// Generated by LawSpec; do not edit. Actors of " ++ intercalate ", " modules ++ ","
        , "// for implementation code. Each class runs one actor: start(...) makes its"
        , "// state and returns the actor. Each handler method sends a message and"
        , "// resolves to the reply; tell<Handler> sends it without waiting. Messages"
        , "// are handled one at a time, in the order they arrive. A handler that"
        , "// throws crashes the actor: the call rejects with ls.ActorCrashed, and a"
        , "// supervised actor restarts (from its restart adapter, or its start) while"
        , "// any other stops. start's last argument may be {supervisor, lifetime}."
        , "// Each supervisor class starts its children and restarts them after a"
        , "// crash; its children are properties named as in the specification."
        , importLine "ls" "lawspec_runtime" ] ++
        [ importLine "data" "lawspec_data" | "data." `isInfixOf` body ] ++
        [ importLine "schema" "lawspec_schema" | "schema." `isInfixOf` body ] ++
        [ importLine (alias m) (map (\c -> if c == '.' then '/' else c) m) | m <- modules ] ++ helpers
  pure [Artifact ("src/lawspec_actors." ++ (if ts then "ts" else "mjs")) (unlines header ++ body) "generated" "source"]
  where
    ts = target == "typescript"
    anyT = if ts then ": any" else ""
    importLine name file = "import * as " ++ name ++ " from './" ++ file ++ (if ts then ".js" else ".mjs") ++ "';"

alias :: String -> String
alias m = "_adapters_" ++ map (\c -> if c == '.' then '_' else c) m

-- | A handler's argument and reply descriptors, adding data types to the table.
type HandlerWire = (Handler, [String], String)

handlerWire :: Int -> [C.DataDeclaration] -> ([(String, String)], [HandlerWire]) -> Handler -> Either String ([(String, String)], [HandlerWire])
handlerWire bits datas (table, acc) h = do
  (args, table') <- foldM (\(xs, t) (_, ty) -> (\(x, t') -> (xs ++ [x], t')) <$> describe bits datas t ty) ([], table) (handlerArguments h)
  (reply, table'') <- describe bits datas table' (maybe (C.Constructor "Unit" []) id (handlerReply h))
  pure (table'', (h, args, reply) : acc)

actorClassText :: Bool -> [C.DataDeclaration] -> Maybe [HandlerWire] -> Actor -> Either String String
actorClassText ts datas wire a = do
  let names = map handlerName (actorHandlers a)
  forM_' names $ \n -> when (n `elem` ["start", "stop", "constructor", "crash", "crashNow", "monitor", "link", "serve", "connect"] || ("tell" ++ capital n) `elem` names || (n ++ "Now") `elem` names)
    (Left ("actor " ++ actorName a ++ "'s handler " ++ n ++ " clashes with a method of its generated class"))
  startArgs <- mapM argument (actorStartArguments a)
  methods <- forM (actorHandlers a) handler
  let cls = actorClass a
      startParams = [arg | arg@(_, (t, _)) <- startArgs, not (unit t)]
      startValues = [if unit t then "ls.UNIT" else p | (p, (t, _)) <- startArgs]
      field = if ts then "  readonly #actor: ls.Actor;" else "  #actor;"
      startCall = impl (actorStart a) ++ "(" ++ intercalate ", " startValues ++ ")"
      restart = case actorRestart a of
        Just d -> asyncWord d ++ "(s" ++ typed "any" ++ ") => " ++ awaited d (impl d ++ "(s)")
        Nothing -> asyncWord (actorStart a) ++ "() => " ++ awaited (actorStart a) startCall
      options = "options" ++ typed "{supervisor?: ls.Supervisor, lifetime?: string}" ++ " = {}"
  pure $ unlines $
    [ "/** Actor " ++ actorName a ++ ": owns its state and handles one message at a time. */"
    , "export class " ++ cls ++ " {"
    , field
    , ""
    , "  constructor(actor" ++ typed "ls.Actor" ++ ") {"
    , "    this.#actor = actor;"
    , "  }"
    , ""
    , "  /**"
    , "   * Makes the actor's state with " ++ C.declarationName (actorStart a) ++ " and starts the actor, under"
    , "   * options.supervisor when given, with options.lifetime ('permanent' by default)."
    , "   */"
    , "  static " ++ asyncWord (actorStart a) ++ "start(" ++ intercalate ", " (map param startParams ++ [options]) ++ ")" ++
        typed (promised (actorStart a) cls) ++ " {"
    , "    const actor = new ls.Actor(" ++ awaited (actorStart a) startCall ++ ", {restart: " ++ restart ++ "});"
    , "    if (options.supervisor !== undefined) options.supervisor.supervise(actor, options.lifetime ?? 'permanent');"
    , "    return new " ++ cls ++ "(actor);"
    , "  }"
    ] ++ concatMap ("" :) methods ++
    [ ""
    , "  /** Crashes the actor as a failing handler would, after the messages already sent: for testing how it restarts. */"
    , "  crash()" ++ typed "Promise<void>" ++ " {"
    , "    return this.#actor.crash();"
    , "  }"
    , ""
    , "  /** crash for synchronous code; the actor must have no messages waiting. */"
    , "  crashNow()" ++ typed "void" ++ " {"
    , "    this.#actor.crashNow();"
    , "  }"
    , ""
    , "  /** notify(['crashed', cause]) after each crash, and notify(['stopped', null]) once it stops. */"
    , "  monitor(notify" ++ typed "(event: [string, unknown]) => void" ++ ")" ++ typed "void" ++ " {"
    , "    this.#actor.monitor(notify);"
    , "  }"
    , ""
    , "  /** When either actor crashes, the other crashes too. */"
    , "  link(other" ++ typed "{readonly actor: ls.Actor}" ++ ")" ++ typed "void" ++ " {"
    , "    this.#actor.link(other.actor);"
    , "  }"
    , ""
    , "  /** The runtime actor, for links and supervision. */"
    , "  get actor()" ++ typed "ls.Actor" ++ " {"
    , "    return this.#actor;"
    , "  }"
    , ""
    , "  /** Refuses further messages; those already sent are still handled. */"
    , "  stop()" ++ typed "void" ++ " {"
    , "    this.#actor.stop();"
    , "  }" ] ++ serving ++
    [ "}" ] ++ proxy
  where
    reference ty = if requiresSchema datas ty then either (const "null") (D.render (D.Pretty 1000)) (webTypeReferenceDoc ty) else "null"
    replyType h = maybe (C.Constructor "Unit" []) id (handlerReply h)
    descriptors ds = "[" ++ intercalate ", " ["_d(" ++ show d ++ ")" | d <- ds] ++ "]"
    serving = case wire of
      Nothing -> []
      Just hs ->
        [ ""
        , "  /** Lets other nodes call this actor at <node address>/name; returns that address. */"
        , "  serve(node" ++ typed "ls.Node" ++ ", name" ++ typed "string" ++ ")" ++ typed "string" ++ " {"
        , "    return node.serve(name, this.#actor, {" ] ++
        [ "      " ++ show (handlerName h) ++ ": [" ++ asyncWord d ++ "(s" ++ typed "any" ++
            concatMap (\(p, _) -> ", " ++ p ++ typed "any") (handlerArguments h) ++ ") => " ++
            (let call = awaited d (impl d ++ "(" ++ intercalate ", " ("s" : ["_native(" ++ reference ty ++ ", _d(" ++ show x ++ "), " ++ p ++ ")" | ((p, ty), x) <- zip (handlerArguments h) ds]) ++ ")")
             in case handlerReply h of
                  Just r -> "_served(" ++ reference r ++ ", " ++ call ++ ")"
                  Nothing -> "[ls.UNIT, " ++ call ++ "]") ++
            ", " ++ descriptors ds ++ ", _d(" ++ show r ++ ")],"
        | (h, ds, r) <- hs, let d = handlerDeclaration h ] ++
        [ "    }, _TYPES);"
        , "  }"
        , ""
        , "  /** The actor served at address on another node; each call waits up to timeout seconds, then rejects with ls.Unreachable. */"
        , "  static connect(node" ++ typed "ls.Node" ++ ", address" ++ typed "string" ++ ", timeout = 5)" ++ typed (actorClass a ++ "Remote") ++ " {"
        , "    return new " ++ actorClass a ++ "Remote(node.remoteActor(address, {" ] ++
        [ "      " ++ show (handlerName h) ++ ": [" ++ descriptors ds ++ ", _d(" ++ show r ++ ")],"
        | (h, ds, r) <- hs ] ++
        [ "    }, _TYPES, timeout));"
        , "  }" ]
    proxy = case wire of
      Nothing -> []
      Just hs ->
        [ ""
        , "/** Actor " ++ actorName a ++ " on another node: each method sends its message and resolves to the reply. */"
        , "export class " ++ actorClass a ++ "Remote {"
        , if ts then "  readonly #remote: ls.RemoteActor;" else "  #remote;"
        , ""
        , "  constructor(remote" ++ typed "ls.RemoteActor" ++ ") {"
        , "    this.#remote = remote;"
        , "  }" ] ++
        concat
        [ [ ""
          , "  async " ++ handlerName h ++ "(" ++ intercalate ", " [p ++ typed "any" | (p, _) <- handlerArguments h] ++ ")" ++ typed "Promise<any>" ++ " {"
          , "    return _native(" ++ reference (replyType h) ++ ", _d(" ++ show r ++ "), await this.#remote.call(" ++ show (handlerName h) ++
              concatMap (\(p, ty) -> ", _logical(" ++ reference ty ++ ", " ++ p ++ ")") (handlerArguments h) ++ "));"
          , "  }" ]
        | (h, _, r) <- hs ] ++
        [ "}" ]
    forM_' xs f = mapM_ f xs
    unit t = t == C.Constructor "Unit" []
    typed t = if ts then ": " ++ t else ""
    param (p, (_, native)) = p ++ typed native
    argument (p, t) = do
      native <- nativeType t
      pure (p, (t, native))
    nativeType t = D.render (D.Pretty 1000) <$> webDataTypeDocWith datas [] t
    impl d = alias (unitName (actorUnit a)) ++ "." ++ adapterName (actorUnit a) (C.declarationId d)
    asyncWord d = if C.declarationAsync d then "async " else ""
    promised d t = if C.declarationAsync d then "Promise<" ++ t ++ ">" else t
    awaited d call = if C.declarationAsync d then "(await " ++ call ++ ")" else call
    capital (c : cs) = toUpper c : cs
    capital [] = []
    handler h = do
      args <- mapM argument (handlerArguments h)
      reply <- traverse nativeType (handlerReply h)
      let params = intercalate ", " (map param args)
          d = handlerDeclaration h
          call = impl d ++ "(" ++ intercalate ", " ("s" : map fst args) ++ ")"
          stateType = if ts then "(s: any)" else "(s)"
          step = case reply of
            Just _ -> asyncWord d ++ stateType ++ " => { const out = " ++ awaited d call ++ "; return [out.first, out.second]; }"
            Nothing -> asyncWord d ++ stateType ++ " => [undefined, " ++ awaited d call ++ "]"
          nowStep = case reply of
            Just _ -> stateType ++ " => { const out = " ++ call ++ "; return [out.first, out.second]; }"
            Nothing -> stateType ++ " => [undefined, " ++ call ++ "]"
          name = handlerName h
          result = maybe "void" id reply
      pure $
        [ "  /** Sends " ++ name ++ " and resolves to the reply. */"
        , "  " ++ name ++ "(" ++ params ++ ")" ++ typed ("Promise<" ++ result ++ ">") ++ " {"
        , "    return this.#actor.call(" ++ step ++ ")" ++ (if ts then " as Promise<" ++ result ++ ">" else "") ++ ";"
        , "  }"
        ] ++
        (if C.declarationAsync d then [] else
        [ ""
        , "  /** Handles " ++ name ++ " at once, for synchronous code; the actor must have no messages waiting. */"
        , "  " ++ name ++ "Now(" ++ params ++ ")" ++ typed result ++ " {"
        , "    return this.#actor.callNow(" ++ nowStep ++ ")" ++ (if ts then " as " ++ result else "") ++ ";"
        , "  }" ]) ++
        [ ""
        , "  /** Sends " ++ name ++ " without waiting for the reply. */"
        , "  tell" ++ capital name ++ "(" ++ params ++ ")" ++ typed "void" ++ " {"
        , "    this.#actor.cast(" ++ step ++ ");"
        , "  }" ]

-- | A supervisor's class: start() makes the runtime supervisor and starts each
-- child under it, in order; each child is a property. start is async when a
-- child's start is.
supervisorClassText :: Bool -> [Supervision] -> Supervision -> String
supervisorClassText ts all' s = unlines $
  [ "/** Supervisor " ++ supervisionName s ++ ": " ++ strategyText ++ ", at most " ++
      show (supervisionRestarts s) ++ " restarts in " ++ seconds ++ "s. */"
  , "export class " ++ cls ++ " {"
  , if ts then "  readonly #supervisor: ls.Supervisor;" else "  #supervisor;" ] ++
  [ "  " ++ (if ts then "readonly " ++ name ++ ": " ++ childClass child else name) ++ ";" | (_, name, child) <- children ] ++
  [ ""
  , "  constructor(supervisor" ++ typed "ls.Supervisor" ++ concatMap (\(_, name, child) -> ", " ++ name ++ typed (childClass child)) children ++ ") {"
  , "    this.#supervisor = supervisor;" ] ++
  [ "    this." ++ name ++ " = " ++ name ++ ";" | (_, name, _) <- children ] ++
  [ "  }"
  , ""
  , "  /** Starts the supervisor and its children, under options.supervisor when given. */"
  , "  static " ++ (if isAsync then "async " else "") ++ "start(options" ++
      typed "{supervisor?: ls.Supervisor, lifetime?: string}" ++ " = {})" ++
      typed (if isAsync then "Promise<" ++ cls ++ ">" else cls) ++ " {"
  , "    const own = new ls.Supervisor('" ++ strategyName ++ "', " ++ show (supervisionRestarts s) ++ ", " ++ seconds ++ ");" ] ++
  [ "    const " ++ name ++ " = " ++ (if childAsync child then "await " else "") ++ childClass child ++
      ".start(" ++ startArgs child ++ "{supervisor: own, lifetime: '" ++ lifetimeName l ++ "'});"
  | (l, name, child) <- children ] ++
  [ "    if (options.supervisor !== undefined) options.supervisor.supervise(own, options.lifetime ?? 'permanent');"
  , "    return new " ++ cls ++ "(own" ++ concatMap (\(_, name, _) -> ", " ++ name) children ++ ");"
  , "  }"
  , ""
  , "  /** notify(['crashed', cause]) when it passes its restart limit, and notify(['stopped', null]) once stopped. */"
  , "  monitor(notify" ++ typed "(event: [string, unknown]) => void" ++ ")" ++ typed "void" ++ " {"
  , "    this.#supervisor.monitor(notify);"
  , "  }"
  , ""
  , "  /** Stops every child, last started first, without restarting them. */"
  , "  stop()" ++ typed "void" ++ " {"
  , "    this.#supervisor.stop();"
  , "  }"
  , ""
  , "  /** The runtime supervisor, for nesting. */"
  , "  get supervisor()" ++ typed "ls.Supervisor" ++ " {"
  , "    return this.#supervisor;"
  , "  }"
  , "}" ]
  where
    cls = supervisionClass s
    children = supervisionChildren s
    typed t = if ts then ": " ++ t else ""
    childClass c = case c of
      ActorChild a -> actorClass a
      SupervisorChild n -> n
    -- Supervisors start actors without arguments (only Unit ones).
    startArgs _ = ""
    childAsync c = case c of
      ActorChild a -> C.declarationAsync (actorStart a)
      SupervisorChild n -> supervisorAsync n
    supervisorAsync n = or [any (childAsyncOf . thd) (supervisionChildren t) | t <- all', supervisionClass t == n]
    childAsyncOf c = case c of
      ActorChild a -> C.declarationAsync (actorStart a)
      SupervisorChild n -> supervisorAsync n
    thd (_, _, c) = c
    isAsync = any (childAsync . thd) children
    strategyName = case supervisionStrategy s of
      OneForOne -> "one_for_one" :: String
      OneForAll -> "one_for_all"
      RestForOne -> "rest_for_one"
    strategyText = case supervisionStrategy s of
      OneForOne -> "one for one" :: String
      OneForAll -> "one for all"
      RestForOne -> "rest for one"
    lifetimeName l = case l of
      Permanent -> "permanent" :: String
      Transient -> "transient"
      Temporary -> "temporary"
    seconds = let (whole, micros) = supervisionPeriod s `divMod` 1000000
              in show whole ++ (if micros == 0 then "" else "." ++ reverse (dropWhile (== '0') (reverse (pad (show micros)))))
    pad m = replicate (6 - length m) '0' ++ m
