# Generated by LawSpec. Do not edit.
"""Known-answer tests of lawspec.crypto's default handlers, against NIST's
vectors (see docs/reference/language/cryptography.md for the sources)."""
import hashlib

import lawspec.crypto as crypto

VECTORS = """@@VECTORS@@"""


def vectors(kind):
    found = []
    for line in VECTORS.splitlines():
        fields = line.split()
        if fields and fields[0] == kind:
            found.append([b"" if f == "-" else f for f in fields[1:]])
    assert found, kind
    return found


def unhex(text):
    return bytes.fromhex(text) if isinstance(text, str) else b""


def sha3(data):
    return hashlib.sha3_256(data).hexdigest()


def test_sha3_256():
    for message, digest in vectors("sha3-256"):
        assert crypto.sha3_256(unhex(message)).hex() == digest


def test_shake256():
    for message, length, output in vectors("shake256"):
        assert crypto.shake256(unhex(message), int(length)).hex() == output


def test_aes_256_gcm():
    for key, iv, plaintext, associated, ciphertext, tag in vectors("aes-256-gcm"):
        sealed = crypto.aes_256_gcm_encrypt(unhex(key), unhex(iv), unhex(plaintext), unhex(associated))
        assert sealed == unhex(ciphertext) + unhex(tag)
        assert crypto.aes_256_gcm_decrypt(unhex(key), unhex(iv), sealed, unhex(associated)) == unhex(plaintext)
        tampered = bytes([sealed[0] ^ 1]) + sealed[1:]
        assert crypto.aes_256_gcm_decrypt(unhex(key), unhex(iv), tampered, unhex(associated)) is None


def test_ml_kem_768_key_generation():
    for d, z, public_digest, _ in vectors("mlkem768-keygen"):
        public, secret = crypto.ml_kem_768_key_pair_from_seed(unhex(d) + unhex(z))
        assert sha3(public) == public_digest
        assert secret == unhex(d) + unhex(z)


def test_ml_kem_768_decapsulation_from_a_seed():
    # cryptography takes decapsulation keys as seeds, and encapsulates only
    # with fresh randomness, so the ACVP encapsulation and expanded-key
    # vectors are checked where a library allows it.
    for seed, ciphertext, secret in vectors("mlkem768-decaps-seed"):
        assert crypto.ml_kem_768_decapsulate(unhex(seed), unhex(ciphertext)).hex() == secret


def test_ml_kem_768_round_trip():
    for seed, _, _ in vectors("mlkem768-decaps-seed"):
        public, secret = crypto.ml_kem_768_key_pair_from_seed(unhex(seed))
        ciphertext, shared = crypto.ml_kem_768_encapsulate(public)
        assert crypto.ml_kem_768_decapsulate(secret, ciphertext) == shared


def test_ml_dsa_65_key_generation():
    for seed, public_digest, _ in vectors("mldsa65-keygen"):
        assert sha3(crypto.ml_dsa_65_public_key(unhex(seed))) == public_digest


def test_ml_dsa_65_verification():
    for public, message, context, signature, passed in vectors("mldsa65-verify"):
        assert crypto.ml_dsa_65_verify(unhex(public), unhex(message), unhex(signature), unhex(context)) == (passed == "true")


def test_ml_dsa_65_signature_from_a_seed():
    # cryptography signs hedged only, so the deterministic signature is
    # verified, not compared.
    for seed, message, signature in vectors("mldsa65-sign-seed"):
        public = crypto.ml_dsa_65_public_key(unhex(seed))
        assert crypto.ml_dsa_65_verify(public, unhex(message), unhex(signature))
        assert not crypto.ml_dsa_65_verify(public, unhex(message) + b"\0", unhex(signature))
        assert crypto.ml_dsa_65_verify(public, unhex(message), crypto.ml_dsa_65_sign(unhex(seed), unhex(message)))


def test_slh_dsa_shake_128f_key_generation():
    for sk_seed, sk_prf, pk_seed, public, secret_digest in vectors("slhdsa128f-keygen"):
        made_public, made_secret = crypto.slh_dsa_key_pair(unhex(sk_seed), unhex(sk_prf), unhex(pk_seed))
        assert made_public.hex() == public
        assert sha3(made_secret) == secret_digest


def test_slh_dsa_shake_128f_verification():
    for public, message, context, signature, passed in vectors("slhdsa128f-verify"):
        assert crypto.slh_dsa_verify(unhex(public), unhex(message), unhex(signature), unhex(context)) == (passed == "true")
        changed = bytes([unhex(message)[0] ^ 1]) + unhex(message)[1:]
        assert not crypto.slh_dsa_verify(unhex(public), changed, unhex(signature), unhex(context))


def test_slh_dsa_shake_128f_round_trip():
    for sk_seed, sk_prf, pk_seed, _, _ in vectors("slhdsa128f-keygen"):
        public, secret = crypto.slh_dsa_key_pair(unhex(sk_seed), unhex(sk_prf), unhex(pk_seed))
        signature = crypto.slh_dsa_sign(secret, b"LawSpec")
        assert crypto.slh_dsa_verify(public, b"LawSpec", signature)
        assert not crypto.slh_dsa_verify(public, b"LawSpeC", signature)
