# Generated by LawSpec. Do not edit.
"""The default handlers of lawspec.host: the process's file system,
environment and free ports."""
import builtins as _builtins
import os as _os
import shutil as _shutil
import socket as _socket

import lawspec_runtime as _ls
import lawspec_schema as _schema
import tempfile as _tempfile


class FileSystemHandler:
    """Files by path; a relative path is from the working directory."""

    def readBytes(self, value0: _builtins.str) -> _schema.Maybe[_builtins.bytes]:
        try:
            with open(value0, "rb") as file:
                return _schema.Just(file.read())
        except (OSError, ValueError):
            return _schema.Nothing()

    def writeBytes(self, value0: _builtins.str, value1: _builtins.bytes) -> None:
        with open(value0, "wb") as file:
            file.write(value1)

    def pathExists(self, value0: _builtins.str) -> _builtins.bool:
        try:
            return _os.path.lexists(value0)
        except ValueError:
            return False

    def removePath(self, value0: _builtins.str) -> None:
        try:
            if _os.path.isdir(value0) and not _os.path.islink(value0):
                _shutil.rmtree(value0)
            else:
                _os.remove(value0)
        except FileNotFoundError:
            pass

    def temporaryDirectory(self, value0: _builtins.str) -> _builtins.str:
        return _tempfile.mkdtemp(prefix=value0)

    def temporaryFile(self, value0: _builtins.str) -> _builtins.str:
        handle, path = _tempfile.mkstemp(prefix=value0)
        _os.close(handle)
        return path


def valid_name(name: str) -> bool:
    return name != "" and "=" not in name and "\0" not in name


class EnvironmentHandler:
    """The process's environment."""

    def environmentVariable(self, value0: _builtins.str) -> _schema.Maybe[_builtins.str]:
        value = _os.environ.get(value0) if valid_name(value0) else None
        return _schema.Nothing() if value is None else _schema.Just(value)

    def environmentSnapshot(self) -> _builtins.str:
        return _ls.acquire_resource("environment")

    def restoreEnvironment(self, value0: _builtins.str) -> None:
        _ls.release_resource("environment", value0)


class PortsHandler:
    """A TCP port on 127.0.0.1 the operating system reports free."""

    def freePort(self) -> _builtins.int:
        with _socket.socket(_socket.AF_INET, _socket.SOCK_STREAM) as probe:
            probe.bind(("127.0.0.1", 0))
            return probe.getsockname()[1]
