# Generated by LawSpec. Do not edit.
"""The default handlers of lawspec.random. Random is the generator of
`seeded random n` (a 64-bit linear congruential generator, the same on every
target), started at the run's seed: LAWSPEC_SEED, or 0. SecureRandom is the
operating system's cryptographically secure generator."""
import builtins as _builtins
import os as _os
import secrets as _secrets

_MODULUS = 1 << 64


def random_step(state: int) -> int:
    return (6364136223846793005 * (state % _MODULUS) + 1442695040888963407) % _MODULUS


def random_draw(state: int, bound: int) -> int:
    """A draw from 0 up to bound, as lawspec.random's randomDraw makes it."""
    if bound < 1:
        return 0
    first = random_step(state)
    bits = (first >> 32 << 32) + (random_step(first) >> 32)
    return bits % bound


def run_seed() -> int:
    value = _os.environ.get("LAWSPEC_SEED")
    return int(value) % _MODULUS if value else 0


class RandomHandler:
    """Reproducible draws from the run's seed."""

    def __init__(self, seed: int | None = None):
        self._state = run_seed() if seed is None else seed % _MODULUS

    def randomBelow(self, value0: _builtins.int) -> _builtins.int:
        state = self._state
        self._state = random_step(random_step(state))
        return random_draw(state, value0)


class SecureRandomHandler:
    """The operating system's generator (secrets)."""

    def secureBytes(self, value0: _builtins.int) -> _builtins.bytes:
        return _secrets.token_bytes(max(value0, 0))

    def secureBelow(self, value0: _builtins.int) -> _builtins.int:
        return _secrets.randbelow(value0) if value0 >= 1 else 0

    def secureToken(self) -> _builtins.str:
        return _secrets.token_hex(32)
