"""Embed reviewed runtime sources in the native and WASM compiler."""
from pathlib import Path
import json
import argparse
root = Path(__file__).resolve().parent.parent
files = [('python','lawspec_runtime.py'),('python-schema','lawspec_schema.py'),('python-data-strategies','lawspec_data_strategies.py'),('javascript','lawspec_runtime.mjs'),('web-schema','lawspec_schema.mjs'),('web-data-strategies','lawspec_data_strategies.mjs'),('java','LawSpecRuntime.java'),('java-schema','LawSpecSchema.java'),('java-data-strategies','LawSpecDataStrategies.java'),('go','lawspec_runtime.go'),('go-schema','lawspec_schema.go'),('go-codecs','lawspec_codecs.go'),('go-data-strategies','lawspec_data_strategies.go'),('haskell','LawSpecRuntime.hs'),('haskell-schema','LawSpecSchema.hs'),('haskell-codecs','LawSpecCodecs.hs'),('haskell-data-strategies','LawSpecDataStrategies.hs'),('rust','lawspec_runtime.rs'),('rust-strategies','lawspec_strategies.rs'),('kotlin-strategies','LawSpecStrategies.kt'),('kotlin-native','LawSpecKotlin.kt'),('kotlin-codecs','LawSpecKotlinCodecs.kt'),('kotlin-data-strategies','LawSpecKotlinStrategies.kt')]
lines = ['-- Generated by tools/embed-runtimes.py. Edit runtime/ sources.', 'module LawSpec.RuntimeSources (runtimeSource) where', 'runtimeSource :: String -> String']
for target, name in files:
    # JSON string quoting is compatible with Haskell for these ASCII runtime sources.
    lines.append('runtimeSource '+json.dumps(target)+' = '+json.dumps((root/'runtime'/name).read_text()))
lines.append('runtimeSource _ = ""')
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='verify embedding without writing')
options = parser.parse_args()
destination = root / 'src/LawSpec/RuntimeSources.hs'
content = '\n'.join(lines) + '\n'
if options.check:
    if destination.read_text() != content:
        parser.exit(1, 'RuntimeSources.hs is stale; run tools/embed-runtimes.py\n')
    print('Embedded runtime sources match reviewed runtime files')
else:
    destination.write_text(content)
