"""Embed reviewed runtime sources in the native and WASM compiler."""
from pathlib import Path
import json
root = Path(__file__).resolve().parent.parent
files = [('python','lawspec_runtime.py'),('javascript','lawspec_runtime.mjs'),('java','LawSpecRuntime.java'),('go','lawspec_runtime.go'),('haskell','LawSpecRuntime.hs'),('rust','lawspec_runtime.rs'),('rust-strategies','lawspec_strategies.rs')]
lines = ['-- Generated by tools/embed-runtimes.py. Edit runtime/ sources.', 'module LawSpec.RuntimeSources (runtimeSource) where', 'runtimeSource :: String -> String']
for target, name in files:
    # JSON string quoting is compatible with Haskell for these ASCII runtime sources.
    lines.append('runtimeSource '+json.dumps(target)+' = '+json.dumps((root/'runtime'/name).read_text()))
lines.append('runtimeSource _ = ""')
(root/'src/LawSpec/RuntimeSources.hs').write_text('\n'.join(lines)+'\n')
